### ISSUE TITLE
Some packages may be 404ing

### ISSUE THREAD

**Issue by ktalebian** [yarnpkg/yarn#8279] opened 2020-08-06 08:41 UTC
I don't know if this issue is wider than just one package, but visiting 

https://registry.yarnpkg.com/@gooddata/gooddata-js/-/gooddata-js-11.19.1.tgz

is 404ing. Visiting npm registry on the other hand resolves:

https://registry.npmjs.org/@gooddata/gooddata-js/-/gooddata-js-11.19.1.tgz

**Comment by BarakGong** [comment] 2020-08-06 08:44
It is. getting this on multiple packages:
https://registry.yarnpkg.com/@codler/react-native-keyboard-aware-scroll-view/-/react-native-keyboard-aware-scroll-view-1.0.0.tgz
https://registry.yarnpkg.com/@react-native-community/cameraroll/-/cameraroll-1.8.1.tgz

**Comment by georgeboot** [comment] 2020-08-06 08:44
Can confirm multiple packages are impacted.

**Comment by Antiarchitect** [comment] 2020-08-06 08:45
Confirm - @vuepress/core@^1.3.1

**Comment by kafka-yu** [comment] 2020-08-06 08:46
Confirmed!!  404, and 503 both meet

**Comment by seba4** [comment] 2020-08-06 08:50
Yea i have the same problem

**Comment by Mishasar** [comment] 2020-08-06 08:51
404 error https://registry.yarnpkg.com/@fortawesome/free-brands-svg-icons/-/free-brands-svg-icons-5.12.1.tgz

**Comment by ktalebian** [comment] 2020-08-06 08:56
Looks like an incident with npm https://status.npmjs.org/

**Comment by denis-chattermill** [comment] 2020-08-06 08:56
It took me a while to figure out isn't it a joke

<img width="791" alt="Screenshot 2020-08-06 at 11 19 34" src="https://user-images.githubusercontent.com/59914973/89512278-a8eaef00-d7db-11ea-999f-d8d6ff0ab6a3.png">

**Comment by strongpauly** [comment] 2020-08-06 08:58
https://status.yarnpkg.com/ isn't happy either

**Comment by ktalebian** [comment] 2020-08-06 09:01
@strongpauly I _think_ that page has been gone for a while now.

**Comment by DylanKas** [comment] 2020-08-06 09:05
Same with package like https://registry.yarnpkg.com/@simonwep/pickr and css-diff.
Error is either 404 or 503

**Comment by GrosTon1** [comment] 2020-08-06 09:05
registry.yarnpkg.com is only a DNS redirection as stated in https://twitter.com/yarnpkg/status/1088356674539270146

Issue comes from NPM, as their status page shows : https://status.npmjs.org/

**Comment by segadora** [comment] 2020-08-06 09:18
+1

**Comment by gabrnavarro** [comment] 2020-08-06 09:30
+1 https://registry.yarnpkg.com/@jest/core/-/core-24.9.0.tgz and a bunch of other packages

**Comment by shinoshu** [comment] 2020-08-06 09:37
https://registry.yarnpkg.com/@material-ui/core/-/core-4.11.0.tgz

**Comment by ashishsantikari** [comment] 2020-08-06 09:38
@material-ui too

**Comment by serifreedom** [comment] 2020-08-06 09:38
+1 https://registry.yarnpkg.com/@mrmlnc/readdir-enhanced/-/readdir-enhanced-2.2.1.tgz and many more... 
from TH

**Comment by crup** [comment] 2020-08-06 09:38
@loadable/component
@sentry/browser

Affected for me.

**Comment by efureev** [comment] 2020-08-06 09:39
+

**Comment by ashishsantikari** [comment] 2020-08-06 09:40
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥

**Comment by achretien** [comment] 2020-08-06 09:41
> registry.yarnpkg.com is only a DNS redirection as stated in https://twitter.com/yarnpkg/status/1088356674539270146
> 
> Issue comes from NPM, as their status page shows : https://status.npmjs.org/

Do we really need to list all scoped package ? or can we read the comments ?

**Comment by xapai** [comment] 2020-08-06 09:48
"Decentralization is a key", they told us.. "Don't put your eggs in one basket".. And here we go. One thing broke and we are reading comments instead of working.

**Comment by lkoida** [comment] 2020-08-06 09:49
the same for emotion and vue-emotion packages
this is the copy of yarn-error.log file both packaged present in yarn and npm registries
Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js add @egoist/vue-emotion

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

Yarn version: 
  1.22.4

Node version: 
  12.18.3

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@egoist%2fvue-emotion: Not found
      at Request.params.callback [as _callback] (/usr/share/yarn/lib/cli.js:66987:18)
      at Request.self.callback (/usr/share/yarn/lib/cli.js:140748:22)
      at Request.emit (events.js:315:20)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:141720:10)
      at Request.emit (events.js:315:20)
      at IncomingMessage.<anonymous> (/usr/share/yarn/lib/cli.js:141642:12)
      at Object.onceWrapper (events.js:421:28)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1220:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

npm manifest: 
  {
    "name": "test-emotion",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "ISC"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by BumjuneKim** [comment] 2020-08-06 09:50
+1

**Comment by Andrei-Vakulski** [comment] 2020-08-06 09:50
Same for:
"https://registry.yarnpkg.com/@reduxjs/toolkit/-/toolkit-1.4.0.tgz"
"https://registry.yarnpkg.com/@nestjs/common/-/common-7.4.2.tgz"

**Comment by tomaszwylezek** [comment] 2020-08-06 09:53
+1
error An unexpected error occurred: "https://registry.yarnpkg.com/@emotion/cache/-/cache-10.0.29.tgz: Request failed \"404 Not Found\"".

**Comment by ramon-b** [comment] 2020-08-06 09:54
Try to use https://replicate.npmjs.com/ as registry (yarn install --registry https://replicate.npmjs.com/). Working for me now.

**Comment by In-line** [comment] 2020-08-06 09:57
https://registry.yarnpkg.com/@material-ui/styles/-/styles-4.9.6.tgz

**Comment by xapai** [comment] 2020-08-06 09:58
> The registry https://replicate.npmjs.com/ (yarn install --registry https://replicate.npmjs.com/) seems to cause less trouble.

RIP replicate.npmjs.com inbox 😆

**Comment by danchapuk** [comment] 2020-08-06 10:00
Getting this error still  for ;
error An unexpected error occurred: "https://registry.yarnpkg.com/@rails/webpacker/-/webpacker-4.2.2.tgz: Request failed \"404 Not Found\"".
Also @rails/actioncable
@popperjs/core
@rails/activestorage
intermittently

**Comment by ruyi-kooboo** [comment] 2020-08-06 10:01
+1 for me.  I see that the corresponding plug-in is marked as invalid for npm on github

**Comment by zverexe** [comment] 2020-08-06 10:06
cannot install plugin too
@babel/plugin-transform-react-display-name

**Comment by GrosTon1** [comment] 2020-08-06 10:07
It is useless to comment with +1s or packages exemples as the issue is random on all scoped packages, it only makes it harder for newcomers to find the cause.

**Comment by Adam23** [comment] 2020-08-06 10:08
在线等 挺急的

**Comment by handrei** [comment] 2020-08-06 10:09
I noticed that only packages starting with @ are causing this error.

**Comment by RyuuGan** [comment] 2020-08-06 10:10
I guess it is because of NPM issues:

https://status.npmjs.org/incidents/cksjqc1w11v5

```
Issues accessing npmjs.com and installing scoped packages
```

<img width="684" alt="image" src="https://user-images.githubusercontent.com/426268/89520220-d33dac00-d7dd-11ea-96d2-ab457d7be8b6.png">

**Comment by achretien** [comment] 2020-08-06 10:11
Thx @RyuuGan it as been told many time before, you can just read the previous comments

**Comment by sontd-0882** [comment] 2020-08-06 10:13
Any update?

**Comment by ashishsantikari** [comment] 2020-08-06 10:17
For updates -> https://status.npmjs.org/
http://status.yarnpkg.com/

**Comment by PPan1215** [comment] 2020-08-06 10:21
any updates AT ALL?

**Comment by SMaverick78** [comment] 2020-08-06 10:28
https://registry.yarnpkg.com/@rollup/plugin-replace/-/plugin-replace-2.3.3.tgz: Request failed \"404 Not Found\""

**Comment by arnorhs** [comment] 2020-08-06 10:35
Same - getting errors on multiple packages

**Comment by DanteWitcher** [comment] 2020-08-06 10:44
the same, from https://registry.yarnpkg.com/@typescript-eslint/experimental-utils/-/experimental-utils-2.12.0.tgz

**Comment by meganoob1337** [comment] 2020-08-06 11:03
Same on multiple Packages

**Comment by sagarising** [comment] 2020-08-06 11:09
https://registry.yarnpkg.com/@typescript-eslint/parser/-/parser-2.34.0.tgz
Facing the same issue.
Request failed \"404 Not Found\"

**Comment by gmukul01** [comment] 2020-08-06 11:09
Facing the same issue for all the packages

**Comment by andrew-oreshko** [comment] 2020-08-06 11:11
Same, right now I'm not able to install any package.

**Comment by lamwilton** [comment] 2020-08-06 11:13
What the hell is going on with your crappy servers? Cant even install yarn itself!

**Comment by benderr** [comment] 2020-08-06 11:14
Сейчас зафиксят, не кипишуйте. 😄

**Comment by meganoob1337** [comment] 2020-08-06 11:20
> What the hell is going on with your crappy servers? Cant even install yarn itself!

Never really had issiues with NPM no need to be so hostile. I'm sure it was not intentional and they're doing the best they can. As if you never had a bug in your system...

**Comment by hendhyhutomo** [comment] 2020-08-06 11:23
https://status.npmjs.org/incidents/cksjqc1w11v5

You can keep track the Specific Incident Status here

**Comment by Skylade** [comment] 2020-08-06 11:25
I'm facing same issues with multiple packages - 404 not found

**Comment by Yukiioz** [comment] 2020-08-06 11:29
Try to use the Open-registry while waiting for the NPM one to work properly again:
```
# To start using Open-Registry
# Replace "npm" with your client (such as "yarn")
npm config set registry https://npm.open-registry.dev

# To stop using Open-Registry
# Replace "npm" with your client
npm config delete registry
```
https://open-registry.dev/

**Comment by emadel1990** [comment] 2020-08-06 11:31
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.     
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.    
[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 24 new dependencies.
info Direct dependencies
├─ @material-ui/core@4.11.0
├─ react-dom@16.13.1
└─ react@16.13.1
info All dependencies
├─ @babel/runtime@7.11.2
├─ @emotion/hash@0.8.0
├─ @material-ui/core@4.11.0
├─ @material-ui/styles@4.10.0
├─ @material-ui/system@4.9.14
├─ @types/prop-types@15.7.3
├─ @types/react-transition-group@4.4.0
├─ @types/react@16.9.44
Compiled successfully!


is up again! at least in material ui

**Comment by Adam23** [comment] 2020-08-06 11:31
`npm install -g yrm`

try other registry

```
yrm ls

  npm ---- https://registry.npmjs.org/
  cnpm --- http://r.cnpmjs.org/
* taobao - https://registry.npm.taobao.org/
  nj ----- https://registry.nodejitsu.com/
  rednpm - http://registry.mirror.cqupt.edu.cn/
  npmMirror  https://skimdb.npmjs.com/registry/
  edunpm - http://registry.enpmjs.org/
  yarn --- https://registry.yarnpkg.com
```

**Comment by muhammadmuhlas** [comment] 2020-08-06 11:37
It worked just now for me, maybe yours too

**Comment by meganoob1337** [comment] 2020-08-06 11:41
"We replaced the faulty cache and our telemetry indicates a significant improvement in error rates. We'll continue to monitor the situation and make sure all issues are fully resolved.
Posted 3 minutes ago. Aug 06, 2020 - 11:36 UTC"

From the NPM issue
https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by SMaverick78** [comment] 2020-08-06 12:03
It worked

**Comment by brunofin** [comment] 2020-08-06 12:10
Status: Resolved. Please close and lock this ticket.

**Closed** 2020-08-06 16:52 UTC
