### ISSUE TITLE
postpack is not called after yarn pack

### ISSUE THREAD

**Issue by thoov** [yarnpkg/yarn#7924] opened 2020-02-21 01:09 UTC
### Bug description

`postpack` is not called after `yarn pack` has completed. Also the success message about creating the tarball during `yarn pack`  no longer shows up. This only happens on node `12.16.*`

**What is the current behavior?**

When executing the command `yarn pack`, yarn invokes the user defined script `prepack` before packing but does not invoke `postpack`.

**What is the expected behavior?**

When executing the command `yarn pack`, yarn should invoke the user defined script `prepack` before and `postpack` after the packaging.

**Steps to Reproduce**
1.  Create a blank project (`yarn init`)
2. Add the following to `package.json`

```json
"scripts": {
  "prepack": "echo \"Hello\"",
  "postpack": "echo \"World\""
}
```
3. Run `yarn pack`

Expected Output:

```
yarn pack v1.22.0
$ echo "Hello"
Hello
$ echo "World"
World
success Wrote tarball to "/private/tmp/yarn-test/yarn-test-v1.0.0.tgz".
✨  Done in 0.06s.
```

Actual Output:
```
yarn pack v1.22.0
$ echo "Hello"
Hello
```

**Environment**

- Node Version: `12.16.0` & `12.16.1`
- Yarn v1 Version: `1.22.0` 
- OS and version: OSX 10.15.3

**Comment by thoov** [comment] 2020-02-21 01:10
cc @haochuan

**Comment by stefanpenner** [comment] 2020-06-15 16:40
This issue appears to continue into `node@^14`

**Comment by stefanpenner** [comment] 2020-06-15 18:16
The following PR https://github.com/yarnpkg/yarn/pull/8188 addresses the issue in-question, although additional root cause analysis is required.

**Comment by merceyz** [comment] 2021-01-02 01:54
Fixed in v2

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 01:54 UTC
