### ISSUE TITLE
yarn@0.27.3 consistently 404s on private packages

### ISSUE THREAD

**Issue by spencer-brown** [yarnpkg/yarn#3765] opened 2017-06-29 22:59 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
yarn@0.27.3 fails to install private packages on every run of `yarn` across several different projects/lockfiles, with a 404.

eg
<img width="1131" alt="screen shot 2017-06-29 at 3 55 41 pm" src="https://user-images.githubusercontent.com/5354793/27714033-7590524c-5ce3-11e7-9049-6f2f82372fe7.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

presumably, run `yarn` with `yarn@0.27.3` installed against any `yarn.lock` that includes private packages.

**What is the expected behavior?**

`yarn@0.27.3` installs private packages.

**Please mention your node.js, yarn and operating system version.**

node: 6.9.1
yarn: 0.27.3
OS: macOS@10.12.4, ubuntu 14.04.5 LTS

**Comment by bestander** [comment] 2017-06-29 23:58
Thanks, looks like this one slipped.
I am thinking of rolling back 0.27.3 to RC

**Comment by wearhere** [comment] 2017-06-30 00:02
Thanks for the quick response @bestander. Curious about "looks like this one slipped"—does Yarn not have tests for private module support? That's a huge part of our (and I would assume many folks') use of npm.

**Comment by bestander** [comment] 2017-06-30 00:06
I think we have never set up e2e tests for private modules.
Would you want to help us out, set up an account and write a test?
We can take care of the billing

**Comment by Daniel15** [comment] 2017-06-30 00:10
> We can take care of the billing

We don't necessarily need something like npm enterprise, we could just have some simple server that we host ourselves

**Comment by robinst** [comment] 2017-06-30 04:00
@bestander Looks like the Debian archive still has 0.27.3, is it possible to roll that back as well?: http://dl.yarnpkg.com/debian/dists/stable/main/binary-all/Packages

**Comment by bestander** [comment] 2017-06-30 04:16
I think it is more work than fix the 2 issues we have, we'll fix them ASAP

**Comment by Daniel15** [comment] 2017-06-30 04:20
@robinst No need to roll it back, you can install a specific version like this:
```
sudo apt-get install yarn=0.24.6-0
```

To keep it at that version (and never install a newer version), you can use mark the package as "held back":
```
sudo apt-mark hold yarn
```

Then just do `sudo apt-mark hold yarn && sudo apt-get upgrade` to get the newer version at some point in the future.

**Comment by robinst** [comment] 2017-06-30 04:25
@Daniel15 Thanks. Yeah, that's what I'm doing as a workaround (except with `0.24.6-1`). The `apt-get install` is in a Docker image, so it would be nicer if we could keep using stable instead.

**Comment by bestander** [comment] 2017-06-30 05:23
@spencer-brown can you confirm in what version it worked for you?
Have you tried 0.26?

**Comment by arcanis** [comment] 2017-06-30 09:49
0.26 is also affected, please use 0.25.4 instead. The commit that introduced the bug is https://github.com/yarnpkg/yarn/commit/33820719e2c049ff93e86d29251b96d496f2b6e8.

**Comment by bestander** [comment] 2017-06-30 19:30
Commented on a change that probably introduced the break.
We need to start the fix with proper tests in place https://github.com/yarnpkg/yarn/pull/3231#issuecomment-312353919

**Comment by bestander** [comment] 2017-06-30 20:56
@spencer-brown, can you confirm if the issue is still there in 0.27.4?

**Comment by scottyeck** [comment] 2017-06-30 21:37
@bestander Please ignore if I'm being another cook in the kitchen, but I can confirm the issue in 0.27.4...

![build__1780_-_fabrictech_cashmere_-_travis_ci](https://user-images.githubusercontent.com/3766777/27754883-a710ed18-5dba-11e7-9f13-e446340f84c8.jpg)

**Comment by bestander** [comment] 2017-06-30 21:41
@scottyeck, you are most certainly welcome.
Can you help us out a bit and check in which releases it worked.

These are the recent releases
```
     '0.24.4': '2017-05-12T17:30:22.376Z',
     '0.25.1': '2017-05-12T19:22:43.139Z',
     '0.24.5': '2017-05-15T18:52:11.047Z',
     '0.25.2': '2017-05-15T18:54:13.175Z',
     '0.24.6': '2017-05-23T20:05:58.254Z',
     '0.25.3': '2017-05-23T20:06:55.232Z',
     '0.25.4': '2017-06-01T12:30:04.516Z',
     '0.26.0': '2017-06-06T13:16:17.273Z',
     '0.26.1': '2017-06-07T14:12:38.092Z',
     '0.27.0': '2017-06-23T13:24:49.267Z',
     '0.27.1': '2017-06-27T10:02:40.390Z',
     '0.27.2': '2017-06-29T02:08:55.267Z',
     '0.27.3': '2017-06-29T20:45:10.584Z',
     '0.27.4': '2017-06-30T20:23:36.901Z' },
```

**Comment by scottyeck** [comment] 2017-06-30 21:43
I just rolled us back to `0.24.6`, which was our last usage without failure. I'll try the incremental upgrades over the next few moments and report back.

**Comment by scottyeck** [comment] 2017-06-30 22:20
Reporting back...
```
'0.24.4' - (did not test)
'0.25.1' - (did not test)
'0.24.5' - (did not test)
'0.25.2' - (did not test)
'0.24.6' - :)
'0.25.3' - :)
'0.25.4' - :)
'0.26.0' - (version not found?)
'0.26.1' - :)
'0.27.0' - :)
'0.27.1' - :)
'0.27.2' - :)
'0.27.3' - :)
'0.27.4' - :( <- only failure
```

**Comment by arcanis** [comment] 2017-06-30 22:27
That's really weird ... I just checked the 0.27.4 with my private pkg (`@arcanis/private-pkg`), and it works fine o0

**Comment by arcanis** [comment] 2017-06-30 22:32
I managed to reproduce the issue! For some reason, `yarn add <pkg-name>` manages to fetch the package when the cache is empty, but `yarn install` doesn't.

```
$> yarn add @arcanis/private-pkg
$> yarn cache clean
$> yarn install
```

**Comment by bestander** [comment] 2017-06-30 23:02
0.27.5 is coming with a patch in 20 minutes

**Comment by bestander** [comment] 2017-06-30 23:37
@scottyeck, can you test 0.27.5, it is available?

**Comment by scottyeck** [comment] 2017-06-30 23:40
@bestander Just a moment.

**Comment by scottyeck** [comment] 2017-06-30 23:49
`0.27.5` is available and OK on my end.

**Comment by BYK** [comment] 2017-07-05 13:06
@bestander @arcanis I think we're good to close this one?

**Comment by arcanis** [comment] 2017-07-05 13:41
Not until we merge https://github.com/yarnpkg/yarn/pull/3774 into master - right now it has only been cherry-picked into 0.27. Currently have a few things on my plate, so it will take a few days.

**Closed** 2017-07-07 12:01 UTC
Labels: bug-fetching, bug-high-priority, feature-private-registries, triaged

**Comment by daniel-nagy** [comment] 2017-07-13 15:26
This has broken installing private modules from our company's Bitbucket server.

```JSON
"private-module": "git+ssh://git@git:7999/project/private-module.git"
```

I rolled back to version `0.27.4` and it correctly installs the package.

**Comment by plmrry** [comment] 2017-09-07 18:49
In case this helps someone:

If you are copying an auth token from a `registry.npmjs.org` URL within `.npmrc`, make sure to include the protocol in the URL.

Yarn `>=1.0.0` was breaking our CI builds because #3987 prevents the use of protocol-relative URLs (e.g. `//registry.npmjs.org/`). The URL written to `.npmrc` by `npm login` is procotol-relative, which prevents Yarn from matching registry URLs to pathname URLs.

**Comment by ELD** [comment] 2017-09-08 20:36
We found that adding `always-auth=true` to the `.npmrc` helped out too.

**Comment by mweststrate** [comment] 2017-11-28 09:32
I run into a similar issue. For future readers, removing the private repository mapping from `.npmrc` fixed it for me (simply comment out a line that looks like)

```
@mycompany:registry=https://registry.npmjs.org/
```

**Comment by GeoffreyPlitt** [comment] 2017-12-19 00:02
None of these solutions worked for me.

**Comment by elyobo** [comment] 2018-01-02 00:57
Ongoing inconsistent occurrences of this for us too (version `1.3.2`)

**Comment by sundowndev** [comment] 2020-05-06 09:06
Same issue with yarn 1.22.4

My .npmrc

```
registry=https://registry.npmjs.org/
//registry.npmjs.org/:_authToken=${NPM_TOKEN}
```
