### ISSUE TITLE
Installation Problem: Can not select platform

### ISSUE THREAD

**Issue by nin-jin** [yarnpkg/yarn#4755] opened 2017-10-21 12:19 UTC
**Which operating system are you using:**

Windows 10 , Yandex Browser

**Please describe the steps you took when trying to install Yarn and what went wrong:**

I was click on "Windows" on page https://yarnpkg.com/en/docs/install
Nothing happens.

In console:
```
Uncaught TypeError: Cannot read property 'exec' of undefined
    at t.tokenize (jquery.slim.js:2209)
    at t.compile (jquery.slim.js:2626)
    at t.select (jquery.slim.js:2716)
    at Function.t [as find] (jquery.slim.js:884)
    at HTMLDocument.handlers (jquery.slim.js:5262)
    at HTMLDocument.dispatch (jquery.slim.js:5187)
    at HTMLDocument.g.handle (jquery.slim.js:5014)
```

**Comment by edmorley** [comment] 2017-10-26 12:03
Hi! This repo is for yarn the tool, for the website there's yarnpkg/website. Looking there I think this may be a dupe of yarnpkg/website#674 ? :-)

**Comment by Haroenv** [comment] 2017-12-05 10:17
It's a duplicate indeed, I can't replicate it on yandex on Mac btw

**Closed by Haroenv** 2017-12-05 10:17 UTC
