### ISSUE TITLE
yarn 0.23.2 unable to install from git+ssh repo

### ISSUE THREAD

**Issue by cskeppstedt** [yarnpkg/yarn#3203] opened 2017-04-20 08:47 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When trying to add a dependency with the git+ssh specification, yarn is unable to read from the remote repository. The repository is an internal Bitbucket server, where the read-access is controlled via ssh keys. The previous yarn-version I used (0.21.3) could install the package. The only difference between the two examples below is the version of yarn. Everything else (ssh keys, node version, etc) is the same.

```
$ yarn add git+ssh://git@internal-stash-server:7999/prj/repo.git
yarn add v0.23.2
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone git@internal-stash-server:7999/prj/repo.git /Users/chris.skeppstedt/Library/Caches/Yarn/v1/.tmp/b625ca2d4e9ba1f4eb42d720d250ce14
Directory: /Users/chris.skeppstedt/code/my-test-project
Output:
Cloning into '/Users/chris.skeppstedt/Library/Caches/Yarn/v1/.tmp/b625ca2d4e9ba1f4eb42d720d250ce14'...
Repository not found
The requested repository does not exist, or you do not have permission to access it.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

The package should be installed from the git+ssh specification. Here's a working example using yarn 0.21.3.

```
$ yarn add git+ssh://git@internal-stash-server:7999/prj/repo.git
yarn add v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ repo@1.0.0
✨  Done in 6.28s.
```

**Please mention your node.js, yarn and operating system version.**
node.js: 7.9.0
yarn: 0.23.2 (and 0.21.3)
os: macOS Sierra 0.12.4

**Comment by Nyoroon** [comment] 2017-04-20 12:27
Same on CentOS 7.

**Comment by Nyoroon** [comment] 2017-04-20 12:44
I thing that PR is causing problem: https://github.com/yarnpkg/yarn/pull/2990

**Comment by webark** [comment] 2017-04-22 13:34
Ran into this as well. Had to change to just using "ssh://" which seems to work for yarn, but not for npm which does want the "git+ssh://".

**Comment by andrewhavens** [comment] 2017-04-28 18:27
I'm having this issue also, but changing to `ssh://` as @webark mentioned did not solve the problem for me. This was working for me previously, but now it is not in version 0.23.2.

**Comment by webark** [comment] 2017-04-28 20:46
@andrewhavens really? huh. We're using a private hosted stash repo for some packages. And with doing a `"ssh://git@stash:7999/ccfe/cc-paths"` seemed to work for us. ONLY for yarn though.. npm doesn't know what to do with it.

**Comment by driesvints** [comment] 2017-05-02 09:43
I can confirm that this is also broken for us. Upgrading to the latest Yarn version (0.23.3) has broken our CI builds.

**Comment by driesvints** [comment] 2017-05-02 09:53
Using `ssh://` instead didn't fix the problem for us unfortunately. Getting the same issues.

**Comment by raido** [comment] 2017-05-02 10:06
Ran into this with v0.22 on CI after upgrading git+ssh:// linked package version. v0.23.3 fixed the issue.

**Comment by jarekb84** [comment] 2017-05-02 15:17
Same as others have mentioned, upgraded to v0.23.3 caused the issue and removing 'git+' fixed it as @webark mentioned.

**Comment by liam-potter** [comment] 2017-05-02 16:01
After spending several hours today trying to figure out what was going wrong, it turns out an old Pageant (one of the PuTTY apps) config had manipulated my GIT_SSH environment variable so it was ignoring my `known_hosts` file.

Removing that environment variable has resolved the issue for me with using a private GitHub repository and using a URL in the format `git+ssh://git@github.com/{organisation}/{repo}` with Yarn v0.23.3.

**Comment by yuricus** [comment] 2017-05-04 11:56
yarn 0.23.4 does not work for us, package specified with `git+ssh://git@myhost:myport/repo.git` when yarn generates git command it omits the protocol, resulting in connection timeout to default port
```[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone git@myhost:myport/repo.git the-dir
Cloning into '...'...
ssh: connect to host myhost port 22: Connection timed out
fatal: Could not read from remote repository.```

**Comment by fpauser** [comment] 2017-05-10 08:18
Same problems here. Installed `0.24.2` via `curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.2`, which solved the problem.

**Comment by i-prashant** [comment] 2017-05-12 13:29
Yup!...
With v0.23.4 , yarn install fails with git+ssh private repos.
With v0.24.2, yarn install works well!!

**Comment by stephanieder** [comment] 2017-05-24 14:06
Hello,
Someone has try with v0.24.5 ?

**Comment by bestander** [comment] 2017-06-29 05:37
We just landed this PR #3735 (will be in 0.28).
Can anyone check if it works?

**Comment by chrisdukey** [comment] 2017-06-29 14:02
I've just built from master and it's fixed the problem for me. Thanks!

**Closed** 2017-06-29 14:43 UTC
Labels: bug-resolution, feature-git, triaged

**Comment by francoispluchino** [comment] 2017-08-09 09:14
@bestander I use Yarn `0.28.4` (currently in RC), and I have an error `Couldn't find match for "master" in "" for "ssh://git@github.com/<username>/<repository>.git".` in the step 2.5 'Resolving packages...'. This error is random, And after a dozen immediate attempts (it can be less at times), Yarn install the dependencies.

The problem also exists for the `0.27.5` version. I can no longer tell you from which version of Yarn the problem is present, but it's been a few months now.

My url in package.json:

```json
{
    "dependencies": {
        "@vendor/package": "git+ssh://git@github.com/<username>/<repository>.git#master"
    }
}

**Comment by BYK** [comment] 2017-08-09 15:22
@francoispluchino I'd check if your SSH keys being made available to SSH agent at the time of `yarn install` since `yarn` uses `ssh` in batch mode which doesn't allow prompting.

You may also check your proxy and try using `git+https` urls to see if it fixes your problem. As a last resort I'd use one of the latest nightlies and see if it happens there. If it does, then please create a new issue with a reproduction script so we can reliably reproduce it and then fix.
