### ISSUE TITLE
[0.17.0] yarn --version fails (looking for a cache file)

### ISSUE THREAD

**Issue by IanVS** [yarnpkg/yarn#1819] opened 2016-11-14 18:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

```bash
❯ yarn --version
0.17.0
/Users/ianvs/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/Users/ianvs/Library/Caches/Yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /Users/ianvs/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /Users/ianvs/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/Users/ianvs/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/Users/ianvs/.nvm/versions/node/v6.3.1/lib/node_modules/yarn/node_modules/commander/index.js:825:13)
```

I'm also unable to `yarn install` due to another cache file not being found:

```bash
yarn install v0.17.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/ianvs/Library/Caches/Yarn/npm-cucumber-1.3.0-55eee8073fb576a98b83df0e082e42b860d91d9f'".
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install yarn@0.17.0 from npm
- Run `yarn --version`

**What is the expected behavior?**
Should not error

**Please mention your node.js, yarn and operating system version.**
node v6.3.1
yarn 0.17.0
osx 10.11

**Comment by scholtzm** [comment] 2016-11-14 19:04
The second issue has been reported in https://github.com/yarnpkg/yarn/issues/1818.

**Comment by IanVS** [comment] 2016-11-14 19:32
> The second issue has been reported in #1818.

That was a `yarn add`, but I agree it's all probably related.

**Comment by hobofan** [comment] 2016-11-14 19:37
Also a duplicate of https://github.com/yarnpkg/yarn/issues/1724

**Comment by bestander** [comment] 2016-11-15 14:53
Closing this one in favor of https://github.com/yarnpkg/yarn/issues/1724.
Going to resolve this today

**Closed by bestander** 2016-11-15 14:53 UTC
Labels: needs triage
