### ISSUE TITLE
`yarn add` broken when using workspaces

### ISSUE THREAD

**Issue by sdeleon28** [yarnpkg/yarn#4173] opened 2017-08-15 02:24 UTC
Running `yarn add` from inside a package directory (e.g. `packages/sdeleon28-b`) errors out when using workspaces. Minimal repro case at https://github.com/sdeleon28/yarn-add-workspaces

* Node: v8.2.1
* Yarn: 0.28.4
* OS: Mac OS Sierra

**Comment by BYK** [comment] 2017-08-15 13:57
Works/fixed on latest master.

That said thanks a lot for the effort you've put into reproduction steps since it was very easy to confirm :)

You can try using the nightlies if this is an immediate problem you need to solve. Otherwise, just wait a few more weeks for the 1.0 release.

**Closed by BYK** 2017-08-15 13:57 UTC
