### ISSUE TITLE
Support for installing packages using git+ssh directly from Github repos

### ISSUE THREAD

**Issue by addi90** [yarnpkg/yarn#849] opened 2016-10-12 10:36 UTC
**Do you want to request a _feature_ or report a _bug_?**
- Feature

**What is the current behavior?**
- Unable to install packages from github repos using `git+ssh` protocol

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
- I should be able to install packages using package names, packages github URL using both _https_ and _git+ssh_ protocols

**Please mention your node.js, yarn and operating system version.**
- Node 6.4, Yarn v0.15.1, Mac OSX El Capitan

**Comment by Itrulia** [comment] 2016-10-12 11:15
Without that being supported it is not usable for my company since we have lots of packages that are internal and only hosted on a git server.

**Comment by legraphista** [comment] 2016-10-12 11:24
+1 
Same issue, please also include support for `git+https` protocol

**Comment by addi90** [comment] 2016-10-12 11:53
@Itrulia I totally agree because even for us its the same scenario. Its important to provide this support for widespread commercial adoption. @wycats @kittens @paulirish

**Comment by fabien** [comment] 2016-10-12 13:05
This is a deal breaker for me as well. As an added request: AFAIK npm currently fetches git packages every single time, regardless of locking it to a specific commit. This is highly undesirable, so Yarn should also check a local cache and/or skip urls locked to a commit SHA1.

**Comment by Icarurs** [comment] 2016-10-12 13:59
Dupe of https://github.com/yarnpkg/yarn/issues/513.

**Closed** 2016-11-07 19:50 UTC
Labels: needs triage
