### ISSUE TITLE
Latest yarn creates `.bin/xx` links in cwd, rather than modules folder

### ISSUE THREAD

**Issue by tailhook** [yarnpkg/yarn#3881] opened 2017-07-10 12:26 UTC
When I do `yarn install --modules-folder=/usr/bin/node_modules` binary links are created in `./node_modules/.bin` rather than in `/usr/bin/node_modules/.bin/`

In previous versions, binaries were linked from `/usr/bin/node_modules/.bin` (i.e. subdir of `modules-folder`). It looks like it was broken in #3545 in particular by this commit: c5a32cc. But I'm not 100% sure.

I tried yarn 0.27.5 and 0.28.1 both have the bug. 0.24.6 works as expected.

**Comment by rally25rs** [comment] 2017-07-10 12:32
Duplicate of #3724 should be fixed by #3792

**Closed by rally25rs** 2017-07-10 12:32 UTC
