### ISSUE TITLE
`yarn add flat` does not behave as expected

### ISSUE THREAD

**Issue by glifchits** [yarnpkg/yarn#2242] opened 2016-12-13 19:42 UTC
I'm just trying out yarn now, so I do apologize if this is somehow blatantly obvious. In either case I can't see why this happens, after having read the `yarn add` docs. 

I'm trying to install `flat` [(NPM)](https://www.npmjs.com/package/flat) [(Github)](https://github.com/hughsk/flat)

**Do you want to request a *feature* or report a *bug*?**

This is probably a UX issue or an actual bug.

**What is the current behavior?**
```bash
# testing. this seems to work as expected
$ yarn add react
yarn add v0.17.2
[1/4] 🔍  Resolving packages...
...

# this does not
$ yarn add flat
yarn add v0.17.2
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

# what is this doing?
$ yarn add flat flat
yarn add v0.17.2
[1/4] 🔍  Resolving packages...
info Unable to find a suitable version for "debug", please choose one by typing one of the numbers below:
  1) "debug@^2.2.0, debug@^2.1.1, debug@*" which resolved to "2.3.3"
  2) "debug@2.2.0, debug@~2.2.0" which resolved to "2.2.0"
  3) "debug@0.7.4" which resolved to "0.7.4"
```
**What is the expected behavior?**

```bash
$ yarn add flat
yarn add v0.17.2
[1/4] 🔍  Resolving packages...
...
```

**Please mention your node.js, yarn and operating system version.**

This happened locally (OSX El Capitan 10.11.6)
```sh
# node -v
v7.2.0
# npm -v
3.10.9
# yarn --version
0.17.2
```

and inside an alpine-node Docker container (`FROM mhart/alpine-node:6.9.1`)
```sh
# node -v
v6.9.1
# npm -v
3.10.8
# yarn --version
0.17.10
```

**Comment by tuures** [comment] 2016-12-13 20:40
workaround: https://github.com/yarnpkg/yarn/issues/2220#issuecomment-266847731

**Comment by iredchuk** [comment] 2016-12-13 22:52
Duplicate of #2112

**Comment by torifat** [comment] 2016-12-18 17:10
@glifchits Follow #2112 please. Same issue.

**Closed by torifat** 2016-12-18 17:10 UTC
Labels: duplicate
