### ISSUE TITLE
Installation Problem: [Windows Powershell run the global command of yarn]

### ISSUE THREAD

**Issue by xieccc** [yarnpkg/yarn#6913] opened 2019-01-12 15:19 UTC
**Which operating system are you using:**
win10 ver:17134.523

**Please describe the steps you took when trying to install Yarn and what went wrong:**
After yarn add the global command,such as create-react-app.When I use it in windows powershell.There are a lot of mistakes like:

```
所在位置 C:\Users\xc\AppData\Local\Yarn\bin\create-react-app.ps1:5 字符: 13
+     *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
+             ~
表达式或语句中包含意外的标记“)”。
所在位置 C:\Users\xc\AppData\Local\Yarn\bin\create-react-app.ps1:8 字符: 3
+ if [ -x "$basedir/pwsh" ]; then
+   ~
if 语句中的“if”后面缺少“(”。
所在位置 C:\Users\xc\AppData\Local\Yarn\bin\create-react-app.ps1:8 字符: 5
+ if [ -x "$basedir/pwsh" ]; then
+     ~
"[" 后面缺少类型名称。
所在位置 C:\Users\xc\AppData\Local\Yarn\bin\create-react-app.ps1:9 字符: 20
+ ... edir/pwsh"  "$basedir/../Data/global/node_modules/.bin/create-react-a ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
表达式或语句中包含意外的标记“"$basedir/../Data/global/node_modules/.bin/create-react-app.ps1"”。
所在位置 C:\Users\xc\AppData\Local\Yarn\bin\create-react-app.ps1:9 字符: 85
+ ... "$basedir/../Data/global/node_modules/.bin/create-react-app.ps1" "$@"
+                                                                      ~~~~
表达式或语句中包含意外的标记“"$@"”。
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : UnexpectedToken
```

what can I do to resolve it?

**Comment by VdustR** [comment] 2019-01-14 08:03
I got the same problem. I downgraded to `1.12.3` to make it works again. It's seems a bug of powershell script with `1.13.0`

**Comment by xc135** [comment] 2019-01-14 08:39
> I got the same problem. I downgraded to `1.12.3` to make it works again. It's seems a bug of powershell script with `1.13.0`

I just tested it and found that it can work normally in 1.12.3. It's seems a bug of powershell .Thank you.

**Comment by vkrol** [comment] 2019-01-14 14:58
I think that this is the duplicate of https://github.com/yarnpkg/yarn/issues/6902.

**Comment by tats-u** [comment] 2019-01-16 16:49
@vkrol Me, too.

**Comment by sainthkh** [comment] 2019-01-29 08:44
Workaround:

Go to AppData\Local\Yarn\bin.
Copy the content of .cmd.ps1 file to .ps1 file. (For example, parcel.cmd.ps1 -> parcel.ps1)

**Closed** 2019-08-21 09:06 UTC
Labels: triaged
