### ISSUE TITLE
Gulp v4 dependency installation fails with: error An unexpected error occurred: ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by emveeoh** [yarnpkg/yarn#1880] opened 2016-11-16 07:12 UTC
**Ran '_yarn_' and got the following error:**

```javascript
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/home/mvo/.cache/yarn/npm-gulp-4.0.0-alpha.2-013259583212bf693d991846c62eb36b8a8e5971'".
```

**Yarn-error.log:**

```javascript
Arguments: 
  /usr/bin/nodejs /usr/bin/yarn

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Yarn version: 
  0.17.2

Node version: 
  7.1.0

Platform: 
  linux x64

npm manifest: 
  {
    "bin": {
      "clientnamehere": "www.js"
    },
    "dependencies": {
      "animate.css": "3.5.2",
      "body-parser": "1.15.2",
      "bootstrap": "3.3.7",
      "cookie-parser": "1.4.3",
      "debug": "2.3.2",
      "express": "4.14.0",
      "font-awesome": "4.7.0",
      "hamburgers": "0.5.0",
      "http-auth": "3.1.0",
      "jquery": "2.x.x",
      "jquery-countto": "1.2.0",
      "jquery-inview": "1.1.2",
      "jquery-match-height": "^0.7.0",
      "jquery-sticky": "1.0.4",
      "jquery.easing": "1.4.1",
      "morgan": "1.7.0",
      "normalize.css": "5.0.0",
      "pug": "2.0.0-beta6",
      "simplelightbox": "1.10.3",
      "tether": "1.3.7"
    },
    "devDependencies": {
      "autoprefixer": "6.5.3",
      "babel-cli": "6.18.0",
      "babel-preset-es2015": "6.18.0",
      "browser-sync": "2.17.6",
      "del": "2.2.2",
      "eslint": "3.10.1",
      "eslint-config-airbnb": "13.0.0",
      "eslint-plugin-import": "2.1.0",
      "eslint-plugin-jsx-a11y": "2.2.3",
      "eslint-plugin-react": "6.7.1",
      "gulp": "github:gulpjs/gulp#4.0",
      "gulp-cached": "1.1.1",
      "gulp-clean-css": "2.0.13",
      "gulp-concat": "2.6.1",
      "gulp-depcheck": "1.1.1",
      "gulp-ignore": "2.0.2",
      "gulp-nodemon": "2.2.1",
      "gulp-nsp": "2.4.2",
      "gulp-plumber": "1.1.0",
      "gulp-postcss": "6.2.0",
      "gulp-pug": "3.1.0",
      "gulp-rename": "1.2.2",
      "gulp-sass": "2.3.2",
      "gulp-sourcemaps": "2.2.0",
      "gulp-uglify": "2.0.0",
      "node-sass": "3.12.3",
      "npm-autoinit": "0.2.0",
      "npm-check-updates": "2.8.6",
      "sass-lint": "1.10.2"
    },
    "engines": {
      "node": "7.0.0"
    },
    "license": "ISC",
    "main": "app.js",
    "name": "clientnamehere",
    "private": true,
    "scripts": {
      "start": "node ./bin/www.js"
    },
    "version": "1.0.0"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: ENOENT: no such file or directory, lstat '/home/mvo/.cache/yarn/npm-gulp-4.0.0-alpha.2-013259583212bf693d991846c62eb36b8a8e5971'
```

Please note that gulp v4 is linked to **GITHUB** as follows:
```javascript
 "gulp": "github:gulpjs/gulp#4.0"
```

**Comment by thomaschaaf** [comment] 2016-11-16 08:06
Duplicate of https://github.com/yarnpkg/yarn/issues/1834

**Closed** 2016-11-16 13:22 UTC
