### ISSUE TITLE
Neither workspace or install link top-level bins into projects

### ISSUE THREAD

**Issue by Tapppi** [yarnpkg/yarn#4596] opened 2017-09-30 13:39 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug report.

**What is the current behavior?**

Installing dependencies in workspace root does not link bins from root package.json into projects'  `packages/*/node_modules/.bin`. You cannot install e.g. a linter or babel in workspace root and then use that bin in each projects scripts with `yarn workspace project lint` (script) or `yarn workspace project xo` (use bin directly).

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/Tapppi/yarn-bug-report-workspaces-transitive-bin-link

Includes both a transitive dependency and normal dependencies for testing. Also includes lerna commands to see desired behavior.

**What is the expected behavior?**
To be able to use bins in workspace root package.json in individual projects. Workaround is to use lerna with `--scope` for this.

**Please mention your node.js, yarn and operating system version.**
node: v6.11.2
yarn: v1.1.0
macos: 10.12.6

**Comment by AviVahl** [comment] 2017-10-31 13:00
https://github.com/yarnpkg/yarn/issues/4543

**Comment by rally25rs** [comment] 2017-11-01 18:57
Closing as duplicate of #4543

**Closed by rally25rs** 2017-11-01 18:57 UTC
