### ISSUE TITLE
Migrate away from SHA-1

### ISSUE THREAD

**Issue by koops76** [yarnpkg/yarn#4593] opened 2017-09-30 10:14 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install any package.
2. yarn.lock contains:
```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


acorn-jsx@^3.0.0:
  version "3.0.1"
  resolved "https://registry.yarnpkg.com/acorn-jsx/-/acorn-jsx-3.0.1.tgz#afdf9488fb1ecefc8348f6fb22f464e32a58b36b"
  dependencies:
    acorn "^3.0.4"
```
3. Yarn uses SHA-1, which is [broken](https://shattered.io).

**What is the expected behavior?**
yarn.lock should use SHA-512 or SHA-384 (faster than SHA-256 on 64-bit systems).

**Please mention your node.js, yarn and operating system version.**
Yarn v1.1.0, Node.js v8.5.0, Windows 10.

**Comment by Daniel15** [comment] 2017-10-04 11:39
Duplicate of #816.

**Closed by Daniel15** 2017-10-04 11:39 UTC
