### ISSUE TITLE
prepublish is run on `yarn add package`

### ISSUE THREAD

**Issue by whitecolor** [yarnpkg/yarn#3209] opened 2017-04-20 15:38 UTC
0.23.2
`prepublish` script is run on `yarn add package`
I wonder why is it so? NPM does this only when `npm install` not `npm install package`

**Comment by whitecolor** [comment] 2017-04-27 23:35
@bestander have you seen this? really annoying and strange.

**Comment by deecewan** [comment] 2017-04-28 22:47
also note that `npm@5` is going to run `prepublish` solely for pre-publish.

**Comment by bestander** [comment] 2017-04-28 22:55
Honestly, those lifecycle phases stopped making sense to me quite a long time ago.
I think we should just break legacy and do the same as npm 5 when it is released.
Feel free to send and RFC.

**Comment by whitecolor** [comment] 2017-04-29 10:10
@bestander 
> lifecycle phases stopped making sense to me quite a long time ago

in simple cases this hooks may prevent errors, when don't use other tools to automate lifecycle besides package manager.

Btw how is `workspaces` feature going? I didn't find a place where it can be tracked or read about.

**Comment by bestander** [comment] 2017-05-01 16:30
It would be great for Yarn to have a richer API that allows hooking up to
lifecycle events or even provide implementation for some phases, i.e.
resolving, fetching or linking.

As for Workspaces we are starting to actively working on solutions starting
this week.
I've created an issue that will link all the RFC and PRs related to it
https://github.com/yarnpkg/yarn/issues/3294.

**Comment by CraigglesO** [comment] 2017-06-07 23:00
Hey, just want to add my frustration. Slows yarn dramatically for `yarn add` or `yarn install`. Theres no point IMO. I'm not ready to publish, I just want to add a dependency. The major shift to yarn for me was speed, but if I have a pre-publish script I'm not going to see that efficiency anymore.

**Comment by bestander** [comment] 2017-06-15 01:51
Anyone wants to champion this change?

We need to build a chart which scripts and when they should run.
If npm@5 does not run prepublish on install anymore makes sense for Yarn to do the same

**Comment by deecewan** [comment] 2017-06-15 01:53
Yeah, I'm happy to give this a shot.

So we need a list of what hooks to run and when, and then update the code to run the hooks at the right time?

**Comment by bestander** [comment] 2017-06-15 01:55
Thanks for volunteering, @deecewan.

Yeah, are you up to create an RFC https://github.com/yarnpkg/rfcs? 
There might be some arguments about this or that hook change.

**Comment by deecewan** [comment] 2017-06-15 01:57
sure thing. i'll have a crack over the next couple of days. exam on saturday, but free after that.
I think this'd be a good first crack at the yarn codebase.

**Comment by andreineculau** [comment] 2017-07-22 23:35
FYI a programmatic comparison of which hooks run and in what order, along with the toold can now be found at https://github.com/andreineculau/package-json-scripts

**Comment by bestander** [comment] 2017-07-24 18:20
@andreineculau, that is quite cool, thanks for categorizing all this, I am sure many people are confused about the state of install scripts.

Do you want to send a PR to https://yarnpkg.com/en/docs and link to the spreadsheet?
That would be a great start.

**Comment by bestander** [comment] 2017-07-24 18:21
To answer the question in your repo, @andreineculau, Yarn tries to match npm@5 where it is applicable.

**Comment by andreineculau** [comment] 2017-07-24 19:01
@bestander would https://github.com/yarnpkg/website/blob/master/lang/en/docs/cli/run.md be a good place to have a footnote?

**Comment by bestander** [comment] 2017-07-24 19:55
I think a section in https://github.com/yarnpkg/website/blob/master/lang/en/docs/cli/install.md would be more appropriate because it is more related to install command lifecycle

**Comment by BYK** [comment] 2017-10-30 13:20
Closing this due to lack of activity. I also think this is no longer a problem on the latest versions of Yarn.

**Closed by BYK** 2017-10-30 13:20 UTC
Labels: bug-install-scripts, help wanted, needs-discussion, triaged

**Comment by MeirionHughes** [comment] 2017-11-09 10:00
@BYK this still is a problem.. yarn 1.3.2 is still running `prepublish` when you add a package. 

Now, given I have `"prepublish": "npm run build"` in order to ensure I always have the latest build when I publish I end up with the annoying case whereby if my build fails due to a needed dependency (or update) then `yarn add` will also fail.

**Comment by ryami333** [comment] 2018-01-15 01:22
I am experiencing this on 1.3.2 also!

**Comment by kaylieEB** [comment] 2018-01-15 02:04
Looks like running `prepublish` script has been added for npm compatibility
https://github.com/yarnpkg/yarn/issues/1323

But you should be able to set `disablePrepublish` option to true in config https://github.com/yarnpkg/yarn/blob/19c8cd5b85b837278e74b42a94c4b5bb1b28fc35/src/cli/commands/install.js#L993

**Comment by DrSensor** [comment] 2018-01-26 05:59
I still experience this quirk for v1.3.2.

Is there any reasonable explanation why `prepublish` need to be executed although we have `preinstall` there? :confused:

**Comment by Rudloff** [comment] 2018-02-05 11:48
@kaylieEB I tried to do `yarn config set disablePrepublish true` but Yarn still tries to run the prepublish scripts for my dependencies.

(I'm using Yarn 1.3.2.)

**Comment by Vadorequest** [comment] 2019-01-25 15:15
Encountering this issue as well, which generate an infinite loop of commands, using yarn 1.13.0

Is there a way to disable prepublish when adding a package, but still running it when actually publishing? If not, any workaround?

**Comment by runfaj** [comment] 2019-11-27 15:33
Still an issue over two years later :(

**Comment by PCASME** [comment] 2020-02-11 18:02
+1

**Comment by bkotrys** [comment] 2020-04-07 08:32
+1

**Comment by dulowski-marek** [comment] 2020-04-07 10:41
What is the recommended solution to this problem? As far I see that one option is enabling `prepublishOnly` as per https://github.com/yarnpkg/yarn/issues/3209#issuecomment-343105283.

However I would like to see anyone accountable for decision tell us it is either the only way, or that the community is free to contribute to resolve this issue.

**Comment by lopugit** [comment] 2022-05-07 01:54
Sorry but why the fuck does prepublish run after installing? Huh?

**Comment by ryami333** [comment] 2022-05-09 09:35
@BYK please reopen.

**Comment by lukaskj** [comment] 2022-06-01 03:04
Still an issue...

**Comment by CraigglesO** [comment] 2022-06-02 02:12
For anyone coming here, I strongly urge you to consider using PNPM rather than NPM or Yarn.

Since the switch literally everything just.. works. No hassle, no issues, all dependencies live in one place not hogging memory.

**Comment by sunboshan** [comment] 2022-06-03 23:02
As of 2022 this bug still there...

**Comment by kiosion** [comment] 2022-07-28 22:10
This should be reopened, it's still an issue, and incredibly annoying given my 'prepublish' script runs tests. Why is 'prepublish' even run after 'add'?

**Comment by jonluca** [comment] 2022-08-02 02:51
I agree that this should be reopened. Seems very odd that the `prepublish` script runs after adding a package or even just running `yarn`.

Also as a sidenote, I came here expecting to find that this was intended behavior, and to be given reason that I disagreed with but would accept due to yarns general ideologies. I didn't think a bug like this was just unfixed lol

**Comment by ronny1020** [comment] 2022-10-27 10:24
I agree this should be reopened. I was so confused until I found this issue. no idea why this will happen after the install script.
