### ISSUE TITLE
Yarn install failing

### ISSUE THREAD

**Issue by kamlekar** [yarnpkg/yarn#1311] opened 2016-10-20 17:10 UTC
I want to report a bug.

`yarn install` fails on a new project.

I downloaded [`springboot-angular2-tutorial`](https://github.com/springboot-angular2-tutorial/angular2-app) and run `yarn install` through CLI. First it prompted me that that there is internet issue and it is retrying. After very long time and no movement in progress bar,  I pressed Ctrl + C to stop the process. It stopped. And after that when I did `yarn install` again, it said me to open a issue here with the error log. Here is the trace:

> Trace: 
>   SyntaxError: C:\Users\kamle\AppData\Local\Yarn\cache\npm-source-list-map-0.1.6.yarn-metadata.json: Unexpected end of JSON input
>       at Object.parse (native)
>       at C:\Program Files (x86)\Yarn\lib\util\fs.js:271:57
>       at next (native)
>       at step (C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
>       at C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20

Nodejs version is 6.8.1
Yarn version is 0.16.0
Windows 10

**Comment by torifat** [comment] 2016-10-20 18:06
Can you try `yarn cache clean` and then `yarn install again`? It seems you `Ctrl + C` and corrupted the cache.

**Comment by kchiragowni** [comment] 2016-10-24 20:20
I'm having same issue quite often, by running yarn cache clean, re-run console and yarn (install) did worked for me.

**Comment by Nopik** [comment] 2016-11-29 11:54
For me the issue is persistent, cleaning yarn cache (and all ~/.yarn* stuff) doesn't help.

**Comment by Nopik** [comment] 2016-11-29 12:41
So, I'm actually seeing the problem with `git+https` links in my `package.json`. Here is some sample session with empty app, first yarn invocation takes forever (in this example I ctrl-c it after like 10 seconds), second is ok:

```
7862 13:35:58 MacBook-Pro ~$ cd tmp
7863 13:35:59 MacBook-Pro ~/tmp$ mkdir yarntest
7864 13:36:03 MacBook-Pro ~/tmp$ cd yarntest
7865 13:36:07 MacBook-Pro ~/tmp/yarntest$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (yarntest)
version: (1.0.0)
description:
entry point: (index.js)
test command:
git repository:
keywords:
author:
license: (ISC)
About to write to /Users/nopik/tmp/yarntest/package.json:

{
  "name": "yarntest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this ok? (yes)
7866 13:36:12 MacBook-Pro ~/tmp/yarntest$ npm install --save "git+https://github.com/rebeccahughes/react-native-device-info"
yarntest@1.0.0 /Users/nopik/tmp/yarntest
└── react-native-device-info@0.9.6  (git+https://github.com/rebeccahughes/react-native-device-info.git#82e585a515a4169b71a4d57ccd713e65f3c732ec)

npm WARN yarntest@1.0.0 No description
npm WARN yarntest@1.0.0 No repository field.
7867 13:37:21 MacBook-Pro ~/tmp/yarntest$ cat package.json
{
  "name": "yarntest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native-device-info": "git+https://github.com/rebeccahughes/react-native-device-info.git"
  }
}
7868 13:37:24 MacBook-Pro ~/tmp/yarntest$ rm -rf node_modules/
7869 13:37:28 MacBook-Pro ~/tmp/yarntest$ yarn
yarn install v0.17.9
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
░ 0/1^C
7870 13:37:37 MacBook-Pro ~/tmp/yarntest$ vi package.json
7871 13:38:01 MacBook-Pro ~/tmp/yarntest$ cat package.json
{
  "name": "yarntest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react-native-device-info": "rebeccahughes/react-native-device-info"
  }
}
7872 13:38:04 MacBook-Pro ~/tmp/yarntest$ yarn
yarn install v0.17.9
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1.59s.
7873 13:38:09 MacBook-Pro ~/tmp/yarntest$
```

For me, this is very repeatable. Interestingly, in my package.json I have few other git+https links and they work fine.

**Comment by mitsuhiko** [comment] 2017-05-16 12:53
For what it's worth I see the same behavior with local file references.

**Comment by tje3d** [comment] 2018-07-26 07:57
My OS (fedora) crashed during `yarn install`, and after restart caught by the same issue.
thanks to @torifat, `yarn cache clean` solved my issue.

**Comment by jcubic** [comment] 2019-02-04 15:39
My internet got disconnected while yarn was fetching the files and now it shows `[2/4] Fetching packages...` and progress and stops, cleaning cache didn't help (after clean I have `0/1114k` progress and it stops instantly) . I'm using Windows 10 and Ubuntu (WSL).

**Comment by jcubic** [comment] 2019-02-05 09:04
I'm not sure but maybe this happen on VPN because next day I've run `yarn install` and it was fine (I've got some error about internet connection but I've change my WiFi to mobile and it was installed successfully).

**Comment by wolfdev1991** [comment] 2020-11-17 12:44
> Can you try `yarn cache clean` and then `yarn install again`? It seems you `Ctrl + C` and corrupted the cache.

Thank you this helped me a lot

**Comment by paul-soporan** [comment] 2021-01-03 20:05
Closing as fixed in v2 where the cache has been revamped to prevent such issues.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-03 20:05 UTC
Labels: cat-bug, triaged
