### ISSUE TITLE
linking dependencies hangs

### ISSUE THREAD

**Issue by dhakehurst** [yarnpkg/yarn#6172] opened 2018-07-28 12:00 UTC
yarn global add angular

hangs at 

[3/4] 🔗  Linking dependencies...
[------------------------------------------------------------------------------------------------------------------------------------------------] 0/1088

**Comment by rally25rs** [comment] 2018-07-30 13:01
could you run with the `--verbose` flag and see what the last couple lines of the output are?

**Comment by amwill04** [comment] 2018-08-01 14:33
Having the same issues - running it under `--verbose` shows it is taking ~55 seconds

Getting a lot of these lines printed out
```
verbose 54.421 Skipping copying of file "/Users/awilliams/Library/Caches/Yarn/v1/npm-fsevents-1.2.4-f41dcb1af2582af3692da36fc55cbd8e1041c426/build/Release/.deps/Release/obj.target/fse/fsevents.o.d" as the file at "/Users/awilliams/git/kori/node_modules/fsevents/build/Release/.deps/Release/obj.target/fse/fsevents.o.d" is the same size (4017) and has the same content.
verbose 54.422 Skipping copying of file "/Users/awilliams/Library/Caches/Yarn/v1/npm-fsevents-1.2.4-f41dcb1af2582af3692da36fc55cbd8e1041c426/build/Release/.deps/Users/eshanker/Code/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node.d" as the file at "/Users/awilliams/git/kori/node_modules/fsevents/build/Release/.deps/Users/eshanker/Code/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node.d" is the same size (284) and has the same content.
```

And quite a few of these
```
verbose 54.423 File "/Users/awilliams/git/kori/node_modules/phantomjs-prebuilt/lib/location.js" would be marked as extraneous but has been removed as it's listed as a phantom file.
verbose 54.423 File "/Users/awilliams/git/kori/node_modules/phantomjs-prebuilt/lib/phantom" would be marked as extraneous but has been removed as it's listed as a phantom file.

```


Running lates `yarn v1.9.2`

**Comment by arcanis** [comment] 2018-08-01 15:53
Yep, duplicate of #6177 - please follow the other issue, I'm going to close this one.

**Closed by arcanis** 2018-08-01 15:53 UTC
Labels: triaged
