### ISSUE TITLE
`yarn --no-emoji help` does not display help

### ISSUE THREAD

**Issue by ithinkihaveacat** [yarnpkg/yarn#1399] opened 2016-10-24 11:06 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The `--no-emoji` flag seems to put `yarn` into a different mode/command, instead of merely suppressing emoji in the output:

```sh
$ yarn --no-emoji help
yarn install v0.16.1
error `install` has been replaced with `add` to add new dependencies. Run "yarn add help" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

`yarn --no-emoji help` is equivalent to `yarn help`, except without displaying any emoji.

**Please mention your node.js, yarn and operating system version.**

```sh
$ yarn -V
0.16.1
$  node --version
v6.9.1
$ uname -v
Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64
```

**Comment by kittens** [comment] 2016-10-24 14:23
Dupe of #716.

**Closed by kittens** 2016-10-24 14:23 UTC
