### ISSUE TITLE
unexpected version resolution (bug or feature?)

### ISSUE THREAD

**Issue by tony-kerz** [yarnpkg/yarn#4587] opened 2017-09-29 13:10 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

top level `package.json` contains:
```
dependencies: {
  //...
  "react": "^15.6.1"
  //...
}
```
react `16.0.0` is resolved into top-level `node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**

`https://github.com/tony-kerz/react-redux-scratch/tree/fde9c817457fc68db8da002c55ab95527a7d26ee`

**What is the expected behavior?**
react `15.6.1` (or version compatible with provided semver) is resolved into top-level `node_modules`

**Please mention your node.js, yarn and operating system version.**
node: `8.6`
yarn: `1.1.0`
os: `osx 10.11.6`

**Comment by BYK** [comment] 2017-09-29 13:34
Most probably a duplicate of #4550 if it doesn't happen in 1.0.2. Fix on the way. Reopen if you think this is different.

**Closed by BYK** 2017-09-29 13:34 UTC
