### ISSUE TITLE
Running `yarn link` multiple times returns error

### ISSUE THREAD

**Issue by TheLarkInn** [yarnpkg/yarn#955] opened 2016-10-13 02:27 UTC
**Do you want to request a _feature_ or report a _bug_?**
Could be bug? Or maybe its intentional?

**What is the current behavior?**
When running our local tests for webpack, we have to run:
`npm install`
`npm link`
`npm link webpack`
`npm test`

So I converted this for yarn to:
`yarn install`
`yarn link`
`yarn link webpack`
`npm test`

This originally worked fine until I implemented module directory caching on travis. Now when tests run they exit on following: 

```
yarn install v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning lodash@1.0.2: The engine "rhino" appears to be invalid.
[3/4] Linking dependencies...
warning Unmet peer dependency "webpack@^2.1.0-beta.19".
warning Unmet peer dependency "webpack@>=0.10 <2 || ^2.1.0-beta".
warning Unmet peer dependency "webpack@1 || ^2.1.0-beta".
warning Unmet peer dependency "webpack@>=0.9 <2 || ^2.1.0-beta".
[4/4] Building fresh packages...
success Saved lockfile.
0.51s$ yarn link
yarn link v0.15.1
error There's already a module called "webpack" registered.
info Visit http://yarnpkg.com/en/docs/cli/link for documentation about this command.
The command "yarn link" failed and exited with 1 during .
Your build has been stopped.
```

I'm not sure if this is a bug, or a problem with the way we have set up our tests. The original behavior is that npm link will run and ignore additional `npm link` if directory is cached etc. 

**What is the expected behavior?**
Additional calls to `yarn link` don't result in error? 

**Please mention your node.js, yarn and operating system version.**
node 6.7 running on travis builds. Here is the PR for reference: https://github.com/webpack/webpack/pull/3129

I wasn't sure if this is an issue or not but figured I would report this anyways 👍

**Comment by jdalton** [comment] 2016-10-13 06:53
I addressed it in #3129.

**Comment by busches** [comment] 2016-12-01 21:59
@TheLarkInn does @jdalton's fix work for you?

**Comment by jdalton** [comment] 2016-12-01 22:13
@busches
The patch I did to the travis.yml was really just working around this issue.
The issue is still in yarn.

**Comment by hpurmann** [comment] 2017-02-18 20:09
For me, the second `yarn link` now still reports the error but the exit code is 0. So it's more like a warning. Is this sufficient for you, @TheLarkInn, @jdalton?
```
➜  yarn-bug yarn link
yarn link v0.20.3
success Registered "yarn-bug".
info You can now run `yarn link "yarn-bug"` in the projects where you want to use this module and it will be used instead.
✨  Done in 0.05s.
➜  yarn-bug yarn link
yarn link v0.20.3
warning There's already a module called "yarn-bug" registered.
✨  Done in 0.05s.
➜  yarn-bug echo $?
0
```

**Comment by bestander** [comment] 2017-05-24 15:12
Seems to be fixed now

**Closed by bestander** 2017-05-24 15:12 UTC
Labels: bug
