### ISSUE TITLE
Dependencies not installed

### ISSUE THREAD

**Issue by byoigres** [yarnpkg/yarn#2974] opened 2017-03-22 23:43 UTC
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**

```
C:\sergio
λ git clone https://github.com/byoigres/byoigres.github.io.git site
Cloning into 'site'...
remote: Counting objects: 133, done.
remote: Compressing objects: 100% (94/94), done.
Receiving objects:  90% (120/133), 260.00 KiB | 438.00 KiB/s
Receiving objects: 100% (133/133), 342.11 KiB | 438.00 KiB/s, done.
Resolving deltas: 100% (41/41), done.

C:\sergio
λ cd site\

C:\sergio\site
λ yarn cache clean
yarn cache v0.21.3
success Cleared cache.
Done in 15.60s.

C:\sergio\site
λ yarn
yarn install v0.21.3
[1/4] Resolving packages...
success Nothing to install.
success Saved lockfile.
Done in 0.84s.

C:\sergio\site
λ ls -a node_modules\
./  ../  .yarn-integrity
```

`node_modules` folder is empty.

**What is the expected behavior?**

I'm running this using:

- Windows 7 64 Bits Professional Edition
- node v6.9.4
- yarn 0.21.3

I expect my dependencies been installed.

**Comment by byoigres** [comment] 2017-03-22 23:49
This is weird, I'm running `npm install` and also does nothing.

**Comment by darrencrossley** [comment] 2017-04-06 14:07
I have this same problem but only in our build system, locally it works flawlessly (which is weird as they're both running the same docker image).

On building we just get:

```
$ yarn install --prod --verbose --force
yarn install v0.21.3
verbose 0.284 current time: 2017-04-06T13:52:28.162Z
[1/4] Resolving packages...
success Nothing to install.
success Saved lockfile.
Done in 0.08s.
$ ls ./node_modules -R
./node_modules:
(nada)
```

I've tried --force, --prod and other options with no change, regenerating the lock file, running without a lock file and even stripping our package.json right back to a basic install:

```
{
  "name": "magic",
  "private": true,
  "dependencies": {
    "js-yaml": "^3.8.2"
  }
}
```

With no change in the result. :(

**Comment by darrencrossley** [comment] 2017-04-06 14:36
Ok so after an hour of debugging I found a tiny typo in our repo: Package.json =/= package.json. Obviously osx doesn't mind this but linux for the mostpart treats these very different.

I guess the only takeaway here is that npm is a little more verbose about saying there's a missing package.json whereas even with --verbose yarn gave no indication that there was anything missing.

For reference with npm you get:
`
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
`

**Comment by arcanis** [comment] 2017-04-27 16:30
I'm going to close this issue, since we unfortunately cannot reproduce it :(

@byoigres Feel free to reopen it with repro steps if you still experience this bug!

**Closed by arcanis** 2017-04-27 16:30 UTC
