### ISSUE TITLE
yarn upgrade not possible

### ISSUE THREAD

**Issue by dr4c4rys** [yarnpkg/yarn#8613] opened 2021-04-12 09:35 UTC
Hello,

I want to upgrade yarn, but it is not possible.
What is the problem here? Is this a general Bug?

Also the message does not make any sense:
<img width="866" alt="Bildschirmfoto 2021-04-12 um 11 28 26" src="https://user-images.githubusercontent.com/23642715/114373578-08777680-9b83-11eb-833a-96af7ace7048.png">

The yarn-error.log shows:

Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js -V

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.5

Node version: 
  10.24.1

Platform: 
  linux x64

Trace: 
  Error: https://npm.fontawesome.com/@fortawesome/fontawesome-pro/-/5.13.0/fontawesome-pro-5.13.0.tgz: Request failed "401 Unauthorized"
      at ResponseError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:696:66)
      at new ResponseError (/usr/share/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:67058:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:141626:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
      at TLSSocket.socketOnData (_http_client.js:451:20)
      at TLSSocket.emit (events.js:198:13)

**Comment by merceyz** [comment] 2021-04-12 09:42
Duplicate of https://github.com/yarnpkg/yarn/issues/8612

**Closed by merceyz** 2021-04-12 09:42 UTC

**Comment by dr4c4rys** [comment] 2021-04-12 10:03
Hi again

I wanted to uninstall yarn with "npm uninstall yarn", but  I get this error-screen:

<img width="594" alt="Bildschirmfoto 2021-04-12 um 11 58 15" src="https://user-images.githubusercontent.com/23642715/114377330-d6681380-9b86-11eb-929e-b94bd994a523.png">



Here is the package-lock.json:

{
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "closure-compiler": {
      "version": "0.2.12",
      "resolved": "https://registry.npmjs.org/closure-compiler/-/closure-compiler-0.2.12.tgz",
      "integrity": "sha1-bDCHytEnQseeR/DOUOh6+Rz44XE=",
      "requires": {
        "google-closure-compiler": "20150901.x"
      }
    },
    "commander": {
      "version": "2.20.0",
      "resolved": "https://registry.npmjs.org/commander/-/commander-2.20.0.tgz",
      "integrity": "sha512-7j2y+40w61zy6YC2iRNpUe/NwhNyoXrYpHMrSunaMG64nRnaf96zO/KMQR4OyN/UnE5KLyEBnKHd4aG3rskjpQ=="
    },
    "google-closure-compiler": {
      "version": "20150901.0.0",
      "resolved": "https://registry.npmjs.org/google-closure-compiler/-/google-closure-compiler-20150901.0.0.tgz",
      "integrity": "sha1-PQHGyt5leQqb+04wshWLdjWsut4="
    },
    "source-map": {
      "version": "0.6.1",
      "resolved": "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz",
      "integrity": "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g=="
    },
    "uglify-js": {
      "version": "3.6.0",
      "resolved": "https://registry.npmjs.org/uglify-js/-/uglify-js-3.6.0.tgz",
      "integrity": "sha512-W+jrUHJr3DXKhrsS7NUVxn3zqMOFn0hL/Ei6v0anCIMoKC93TjcflTagwIHLW7SfMFfiQuktQyFVCFHGUE0+yg==",
      "requires": {
        "commander": "~2.20.0",
        "source-map": "~0.6.1"
      }
    },
    "yuicompressor": {
      "version": "2.4.8",
      "resolved": "https://registry.npmjs.org/yuicompressor/-/yuicompressor-2.4.8.tgz",
      "integrity": "sha1-mNJnUfFm49uRmy/j6nz2Qt6ZjYs="
    }
  }
}

**Comment by merceyz** [comment] 2021-04-12 10:04
That belongs in https://github.com/npm/cli
