### ISSUE TITLE
`yarn help init` doesn't output any help

### ISSUE THREAD

**Issue by Qix-** [yarnpkg/yarn#4935] opened 2017-11-15 11:40 UTC
```console
$ yarn --version
1.3.2

$ yarn --help
...
  Commands:
...
    - init
...
  Run `yarn help COMMAND` for more information on specific commands.

$ yarn help init

  Usage: yarn [command] [flags]

  Options:

    -h, --help                          output usage information
    -v, --version                       output the version number
...
```

It doesn't appear `init` has any help text - it'd be nice to know if there were any CLI options for it.

**Comment by rally25rs** [comment] 2017-11-16 19:42
It appears that `yarn help {any_command}` outputs the full yarn command usage, but nothing specific to that command.

**Comment by rally25rs** [comment] 2017-11-16 19:58
Actually, looking at this again, it looks like all the "global" flags get printed out in the help along with the command-specific help.

For example:

```
$ yarn help init

  Usage: yarn [command] [flags]

  Options:

    -h, --help                          output usage information
    -v, --version                       output the version number
    --verbose                           output verbose messages on internal operations
    --offline                           trigger an error if any required dependencies are not available in local cache
    --prefer-offline                    use network only if dependencies are not available in local cache
    --strict-semver
    --json
    --ignore-scripts                    don't run lifecycle scripts
    --har                               save HAR output of network traffic
    --ignore-platform                   ignore platform checks
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --force                             install and build packages even if they were built before, overwrite lockfile
    --skip-integrity-check              run install without checking if node_modules is installed
    --check-files                       install will verify file tree of packages for consistency
    --no-bin-links                      don't generate bin links when setting up packages
    --flat                              only allow one version of a package
    --prod, --production [prod]
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --global-folder <path>              specify a custom folder to store global packages
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --emoji [bool]                      enable emoji in output
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --cwd <cwd>                         working directory to use
    --proxy <host>
    --https-proxy <host>
    --registry <url>                    override configuration registry
    --no-progress                       disable progress bar
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --non-interactive                   do not show interactive prompts
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --no-node-version-check             do not warn when using a potentially unsupported Node version
    -y, --yes                           use default options
    -p, --private                       use default options and private true

  Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

```
$ yarn help run

  Usage: yarn [command] [flags]

  Options:

    -h, --help                          output usage information
    -v, --version                       output the version number
    --verbose                           output verbose messages on internal operations
    --offline                           trigger an error if any required dependencies are not available in local cache
    --prefer-offline                    use network only if dependencies are not available in local cache
    --strict-semver
    --json
    --ignore-scripts                    don't run lifecycle scripts
    --har                               save HAR output of network traffic
    --ignore-platform                   ignore platform checks
    --ignore-engines                    ignore engines check
    --ignore-optional                   ignore optional dependencies
    --force                             install and build packages even if they were built before, overwrite lockfile
    --skip-integrity-check              run install without checking if node_modules is installed
    --check-files                       install will verify file tree of packages for consistency
    --no-bin-links                      don't generate bin links when setting up packages
    --flat                              only allow one version of a package
    --prod, --production [prod]
    --no-lockfile                       don't read or generate a lockfile
    --pure-lockfile                     don't generate a lockfile
    --frozen-lockfile                   don't generate a lockfile and fail if an update is needed
    --link-duplicates                   create hardlinks to the repeated modules in node_modules
    --link-folder <path>                specify a custom folder to store global links
    --global-folder <path>              specify a custom folder to store global packages
    --modules-folder <path>             rather than installing modules into the node_modules folder relative to the cwd, output them here
    --preferred-cache-folder <path>     specify a custom folder to store the yarn cache if possible
    --cache-folder <path>               specify a custom folder that must be used to store the yarn cache
    --mutex <type>[:specifier]          use a mutex to ensure only one yarn instance is executing
    --emoji [bool]                      enable emoji in output
    -s, --silent                        skip Yarn console logs, other types of logs (script output) will be printed
    --cwd <cwd>                         working directory to use
    --proxy <host>
    --https-proxy <host>
    --registry <url>                    override configuration registry
    --no-progress                       disable progress bar
    --network-concurrency <number>      maximum number of concurrent network requests
    --network-timeout <milliseconds>    TCP timeout for network requests
    --non-interactive                   do not show interactive prompts
    --scripts-prepend-node-path [bool]  prepend the node executable dir to the PATH in scripts
    --no-node-version-check             do not warn when using a potentially unsupported Node version

  Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

If you look at the very end, the `init` command has the `-y` and `-p` flags which the `run` command goes not.

The whole big bunch of flags that are the same are defined as "global" flags that generally work across all commands (even though some of them may not make sense for some commands). These help docs are generated by https://github.com/tj/commander.js/ and are pretty much working "as designed" as far as that goes.

I do agree that some actual text in the help output would be nice, like "what is this command even used for?" I'm going to mark this as a feature request to improve the command line help.

**Comment by Qix-** [comment] 2017-11-17 05:32
If it makes any difference, our team has generally decided to forego such 'complete' argument parsers because they make it incredibly hard to control help output - especially since we like to show examples or include links or whatever. We made `arg` to get out of the way of argument parsing, do manual validation because it makes intent 100% clear, and generate our own help messages using chalk and template literals.

It makes the code only slightly more 'verbose' but improves maintainability and gives us complete control over the output of help text, which we find is generally a major win.

We're also pushing to move to Yarn pretty extensively, so if this is the route you want to take I'd be more than happy to start endeavoring into a PR to sort of re-vamp help docs if you'd like.

**Comment by rally25rs** [comment] 2017-11-17 13:43
@Qix- it's probably worth some discussion. Feel free to hop into the development channel on Discord and garner input from others. I remember someone else expressing frustration with Commander.js too so this might not be a bad area to spend some time making things better.

**Comment by merceyz** [comment] 2021-01-02 14:56
Closing as fixed in v2 where every command supports a `--help` flag

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 14:56 UTC
Labels: cat-feature, good first issue, help wanted, triaged
