### ISSUE TITLE
Yarn complains of peer unmet dependency but npm doesn't 

### ISSUE THREAD

**Issue by awebdeveloper** [yarnpkg/yarn#2889] opened 2017-03-10 16:04 UTC
```
/home/ui $ yarn install
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@ionic/app-scripts@1.1.4" has unmet peer dependency "@angular/tsc-wrapped@*".
[4/4] 📃  Building fresh packages...
✨  Done in 31.49s.
/home/ui $   npm install
/home/ui $ 
```

**Please mention your node.js, yarn and operating system version.**
Mac OS X Yosemite 
yarn : 0.21.3
node : 7.7.2

**Comment by jknight12882** [comment] 2017-03-13 23:25
+1 on this

**Comment by arcanis** [comment] 2017-04-28 17:06
Why should we not warn about unmet peer dependencies? That feels like a pretty important issue, something that most users might want to know.

**Comment by awebdeveloper** [comment] 2017-04-28 17:51
But npm didn't that's where the confusion was

**Comment by CrabDude** [comment] 2017-07-13 20:35
Dupe: #2886

**Comment by BYK** [comment] 2017-09-15 23:29
Closing due to lack of reproduction steps. Please reopen with reproduction steps that include at least a `package.json` file if you need this to be fixed.

**Comment by BYK** [comment] 2017-09-15 23:29
@CrabDude did you mean #2688?

**Closed by BYK** 2017-09-15 23:29 UTC
Labels: cat-discussion, triaged

**Comment by CrabDude** [comment] 2017-09-18 17:28
Yes.
