### ISSUE TITLE
Windows 10 v1709, node_modules/.bin losing permissions

### ISSUE THREAD

**Issue by bradrice** [yarnpkg/yarn#5211] opened 2018-01-13 18:29 UTC
When running yarn add webpack -D the first time, everything installs correctly. But then if I want to run the command again, the node_modules/.bin folder will not allow install.

window-size "0.1.0"

Trace: 
  Error: EPERM: operation not permitted, lstat 'C:\Users\brice\Source\dashboards-react\node_modules\.bin'

If I try to click read only off on the .bin folder it will not allow me to unless I restart Windows. Then I can delete or change permissions on the folder.

Also if I try to do yarn remove webpack:

 An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\brice\\Source\\dashboards-react\
_modules\\acorn-dynamic-import\\node_modules\\.bin'".

**Comment by BYK** [comment] 2018-01-15 12:18
Please share your package.json file along with your Node and Yarn versions please.

**Comment by bradrice** [comment] 2018-01-15 13:08
yarn is 1.3.2
node is 8.9.4

This only happens on Windows 10 version 1709 Fall Creators edition. I didn't have the problem on 1703.

Below is my package.json. Nothing is installed yet. When I try I get the EPERM error. the .bin folder is created, but I can't delete or change permissions on it. If I restart the machine the .bin folder is not there.

{
  "name": "dashboards-react",
  "version": "0.1.0",
  "description": "Dashboards for Tooling u-SME screen play",
  "main": "index.js",
  "repository": "https://github.com/toolingudev/dashboards-react.git",
  "author": "Brad Rice <bradrice1@gmail.com>",
  "license": "MIT",
  "dependencies": {}
}

**Comment by BYK** [comment] 2018-01-15 13:53
>When I try I get the EPERM error. the .bin folder is created, but I can't delete or change permissions on it. If I restart the machine the .bin folder is not there.

This implies something in the background (like an anti-virus app) getting a lock on this folder or some other issue with your file system or setup. I'm also running on 1709 Fall Creators Edition and not experiencing any issues similar to this.

Gonna close this since it doesn't sound related to Yarn. If you can come up with a reproducible case for us, feel free to reopen.

**Closed by BYK** 2018-01-15 13:53 UTC
Labels: needs-repro-script, triaged

**Comment by bradrice** [comment] 2018-01-15 14:23
OK, thanks for looking into it byk

**Comment by martinmckenna** [comment] 2018-08-22 19:55
@bradrice Did you ever solve this issue? Having the same exact problem

**Comment by bradrice** [comment] 2018-08-29 13:02
I'm pretty sure if I remember back, it did have something to do with my anti-virus settings. I was using webroot.

**Comment by jaguth** [comment] 2019-02-12 13:00
I'm also experiencing this issue. I'm on the latest version of Windows 10:  10.0.17134.523 .  But I can't do anything about it, apparently.  I do not even have permissions to reset permissions, and i'm an admin.  I'd like to add I've never experience this kind of thing on my Mac dev workstation.  Sigh... come on Microsoft

**Comment by pwrnrd** [comment] 2019-03-18 15:25
@jaguth Did you find a solution to this problem? I'm also experiencing this issue and i'm also running Windows 10.0.17134.
