### ISSUE TITLE
https://yarnpkg.com/install.sh gives 522

### ISSUE THREAD

**Issue by realalexhomer** [yarnpkg/yarn#3550] opened 2017-05-31 16:05 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Currently when our circleCI tries to install yarn using https://yarnpkg.com/install.sh the endpoint give a 522 causing our circelCI to fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
wget https://yarnpkg.com/install.sh 
--2017-05-31 11:40:41--  https://yarnpkg.com/install.sh
Resolving yarnpkg.com... 104.16.59.173, 104.16.60.173, 104.16.61.173, ...
Connecting to yarnpkg.com|104.16.59.173|:443... connected.
HTTP request sent, awaiting response... 522 Origin Connection Time-out
```

**What is the expected behavior?**

`https://yarnpkg.com/install.sh` should return the bash script to install yarn

**Please mention your node.js, yarn and operating system version.**

Node  6.5.0, latest yarn

**Comment by johnsudaar** [comment] 2017-05-31 16:06
It should be related to #3549

**Comment by destroyerofbuilds** [comment] 2017-05-31 16:15
Duplicate of yarnpkg/website/issues/519

**Comment by Dakuan** [comment] 2017-05-31 16:39
also breaking heroku deploys

**Comment by mathewjordan** [comment] 2017-05-31 16:42
Back online now with a _brew install yarn_

**Closed** 2017-06-06 16:16 UTC
