### ISSUE TITLE
'yarn install' bombs on bcrypt installation on Windows

### ISSUE THREAD

**Issue by bleggett** [yarnpkg/yarn#2315] opened 2016-12-21 12:29 UTC
**What is the current behavior?**
Currently, installing bcrypt with Yarn fails for me. I am aware of the problematic nature of native-compiled bcrypt, but I have all the correct build tools and npm is able to compile the package correctly on the same machine, so I would expect yarn to do the same. 

```
C:\Source\MyApp>yarn install
yarn install v0.18.1
info No lockfile found.
warning npm-shrinkwrap.json found. This will not be updated or respected. See https://yarnpkg.com/en/docs/migrating-from-npm for more information.
[1/4] Resolving packages...
warning good-squeeze > fast-safe-stringify@1.0.9: use 1.1.0+ see https://github.com/davidmarkclements/fast-safe-stringify/issues/4
warning babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning cross-env > cross-spawn-async@2.0.0: cross-spawn no longer requires a build toolchain, use it instead!
warning library_devtesttools > tools_codecoveragefacade > babel-istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠈ bcrypt: ValueError: Variable expansion in this context permits str and int only, found long for lastUpd
[2/2] ⠈ bcrypt: gyp info spawn args   '-Goutput_dir=.' ]
[-/2] ⠈ waiting...
[-/2] ⠈ waiting...
error C:\Source\MyApp\node_modules\bcrypt: Command failed.
Exit code: 1
Command: C:\WINDOWS\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: C:\Source\MyApp\node_modules\bcrypt
Output:
C:\Source\MyApp\node_modules\bcrypt>if not defined npm_config_node_gyp (node "C:\Program Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@7.3.0 | win32 | x64
gyp info spawn C:\tools\python2\python.EXE
gyp info spawn args [ 'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Source\\MyApp\\node_modules\\bcrypt\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\ben.leggett\\.node-gyp\\7.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\ben.leggett\\.node-gyp\\7.3.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Source\\MyApp\\node_modules\\bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Source\\MyApp\\node_modules\\bcrypt\\build',
gyp info spawn args   '-Goutput_dir=.' ]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2775, in Load
    variables, includes, depth, check, True)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 417, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1214, in ProcessVariablesAndConditionsInDict
    variables, build_file, 'variables')
  File "C:\Program Files (x86)\Yarn\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1225, in ProcessVariablesAndConditionsInDict
    'only, found ' + expanded.__class__.__name__ + ' for ' + key)
ValueError: Variable expansion in this context permits str and int only, found long for lastUpdateCheck while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\Yarn\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Source\MyApp\node_modules\bcrypt
gyp ERR! node -v v7.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
**What is the expected behavior?**
That yarn would successfully compile bcrypt like npm does.

**Please mention your node.js, yarn and operating system version.**

Node: 7.3.0, yarn: 0.18.1, OS: Windows 10 64.

**Comment by v12** [comment] 2016-12-21 19:45
See #2286, it's about the same issue.

**Comment by Daniel15** [comment] 2016-12-21 23:11
Yeah this looks like a duplicate of #2286, so I'm going to close it in favour of that issue.

**Closed by Daniel15** 2016-12-21 23:11 UTC
