### ISSUE TITLE
yarn equivalent of npx ?

### ISSUE THREAD

**Issue by sandys** [yarnpkg/yarn#3937] opened 2017-07-15 08:46 UTC
how is yarn recommending we use npx (that is now core part of npm - https://github.com/npm/npm/pull/17685).

Basically, it acts somewhat like ruby's "bundle exec", other than that it launches the package manager if dependencies are missing. This will sidestep yarn and switch back to npm.

Is there a plan to create a "ypx" equivalent that leverages yarn to do this ?

**Comment by Daniel15** [comment] 2017-07-15 18:57
For what it's worth, I think npx was inspired by "yarn create" which is similar but only works for packages prefixed with "create-". Not sure what the plans are here.

**Comment by arcanis** [comment] 2017-07-17 17:01
Yup, we currently have `yarn create` (try using `yarn create react-app`, for example). We might open it to others verbs in the future, but that's not on the roadmap yet.

**Comment by zkat** [comment] 2017-07-17 18:33
I'm working on library-ifying npx. It's not a huge task to grab the existing npx code and just replace the npm-related guts with the yarn-equivalent commands.

I won't add that directly to npx itself, since it's _meant_ to be agnostic: npx performs no operations which clash with people using other package managers. It doesn't even require npm to be on the system, so you can `npm rm -g npm` and npx will work just fine. So you could say npx _is_ `ypx`, unless you feel really strongly about cache-sharing, which is a pretty thing.

(in re inspiration: npx is primarily inspired by this long-standing feature request: https://github.com/npm/npm/issues/6053. Most of its functionality centers around fulfilling _this_ need. The auto-install feature _was_ added post-yarn-create, and is definitely intended to be an actual generalized solution to that particular thing -- but it does _way more_ than that)

**Comment by BYK** [comment] 2017-07-17 22:47
@sandys - The issue @zkat referenced (npm/npm#6053) is not an issue on `yarn` since you can just do `yarn x` (or `yarn run x` if you want to be explicit) if `x` is in your `./node_modules/.bin` directory. So I don't think there's a pressing need for `npx` equivalency.

If you think there's a strong need, can you explain why you need it? Eg. what problem will it solve for you?

**Comment by MarkBennett** [comment] 2017-10-27 15:28
Does anyone know if `yarn exec` is similar to `bundle exec`? I see it on the CLI but not in the docs on the website. A quick play with `yarn exec` on the command line seems like it runs installed binaries so it might solve your problem @sandys.

**Comment by pygy** [comment] 2017-11-08 20:07
FWIW, [npm-run](https://www.npmjs.com/package/npm-run) is an older utility that allows one to run local `node_modules` binaries, and it doesn't depend on `npm`. It doesn't have any options though, whereas `npx` is full of knobs.

**Comment by SimenB** [comment] 2017-12-14 15:00
@BYK Use case is running e.g. `ypx greenkeeper-lockfile@1` or `ypx danger@2` on CI without adding those as deps to the project itself

**Comment by tdmalone** [comment] 2017-12-14 21:47
@SimenB CI usually wouldn't commit the project back to version control though, so it doesn't matter if it adds the dependencies in the process, right?

**Comment by dcorking** [comment] 2018-01-08 13:37
@MarkBennett Since `yarn exec` doesn't run scripts from `package.json` I don't think it is the right place to add this feature.

**Comment by dcorking** [comment] 2018-01-08 13:39
@BYK I am not the OP, but I came to this feature request because I had a package on my local machine but not in my package.json. Therefore my app would run for me, but not for anyone who did a clean install of my app. This is a feature of ruby bundler's `bundle exec` that I like - it won't run unless all the deps are in the manifest.

**Comment by freddi301** [comment] 2018-05-22 11:02
something like [gist](https://gist.github.com/freddi301/b959deeb9a07cd81e69828b3d3ad4442)
```bash
#!/usr/bin/env bash

package_name=$1
temp_dir="/tmp/ypx/$package_name/$(date +%s%N)"
mkdir -p $temp_dir
(cd $temp_dir; yarn add $package_name) && (PATH="$temp_dir/node_modules/.bin":$PATH; "$@")
rm -rf $temp_dir
```

**Comment by phra** [comment] 2018-05-23 09:05
@BYK another use case is running a _binary_ of a package that is not installed locally yet and i want to run it one time, without bothering to delete it on my own after. `npx` function is an extension of the behavior of `yarn x` because you can:

1. run a command of a local package in the `./node_modules/.bin/` in the current directory
2. if the package is not present locally OR the `./node_modules` directory doesn't exist, download the package in a temporary directory with its dependencies and invoke the command

this is done transparently to the user.

a hypothetic `ypx` can also offer a third point that is:

3. if the package is not present locally AND it's present in the yarn cache AND it matches the latest version, invoke the command using the cache instead of download all the packages

**Comment by alireza-mh** [comment] 2018-09-26 14:45
@BYK as far as i know npx will look for your command on `node_module/.bin/` on local machine and if it didn't find proper command it will get package from web if there is any and you can be always up to date. 
yarn do not get package from web while it's not installed on local machine.

**Comment by light24bulbs** [comment] 2018-11-01 19:11
Can we get a `yarnx` ?

**Comment by arcanis** [comment] 2018-11-03 15:18
@light24bulbs why in particular?

Frankly I think `npx` is a good tool even if a bit too `npm`-centric (as most of npm's tools, to be fair). A `yarnx` wouldn't solve this problem, so I'm not too sure it would be a good idea.

Ideally, I would prefer `npx` to automatically detect the package manager to use, or at least to allow configuring it inside an rc file. I'd suggest to bring this issue to them and see what they say. Depending on their answer we'll then be able to have an informed discussion 🙂

**Comment by sospedra** [comment] 2019-06-05 15:11
Does the new `yarn dlx` solve this issue?

cc @sandys @arcanis 

https://yarnpkg.github.io/berry/cli/dlx

**Comment by arcanis** [comment] 2019-06-05 16:23
Yep! Closing this issue for now, I haven't figured out yet whether we'll want to backport the feature to the v1 (probably not?).

**Closed** 2019-06-05 16:23 UTC
Labels: cat-feature

**Comment by silverwind** [comment] 2019-06-29 22:57
I'm not sure it's a worthy replacement. `yarn dlx eslint --help` takes 2.7 seconds on my machine while `npx eslint --help` finishes in 0.2s. If one calls a lot of bin scripts, this will quickly add up to unacceptable values.

Also, I think stdout/stderr should not be written to by yarn unless there is an error, to allow parsing the script's output.

**Comment by BYK** [comment] 2019-07-03 11:45
@silverwind the timing difference seems quite stark. Is this reproducible in multiple runs consistently? If yes, I'd file a new issue for investigation as we surely don't want it to be slow.

Regarding stdout/stderr from Yarn, I _think_ you can use `yarn --silend dlx eslint` to suppress all non-critical Yarn output. @arcanis can you confirm this last one?

**Comment by rulatir** [comment] 2020-01-20 04:07
> @light24bulbs why in particular?

For all people who find some package on the web, see that installation instructions involve `npx something something`, but want to remain in the yarn world.

**Comment by rulatir** [comment] 2020-01-20 04:12
> Does the new `yarn dlx` solve this issue?

Is `yarn dlx` an exact `s/npx/yarn dlx/` drop-in replacement for `npx`? If not, then it doesn't solve this issue.

**Comment by bluelovers** [comment] 2020-01-28 19:39
try this
https://www.npmjs.com/package/ynpx

**Comment by xgqfrms** [comment] 2020-03-22 10:47
# yarn create & npx & npm init

> demo

https://www.npmjs.com/package/create-react-app
https://www.npmtrends.com/npm-vs-npx-vs-yarn

```sh
$ yarn create react-app

$ npx create-react-app

$ npm init react-app

```

**Comment by codekiln** [comment] 2020-08-05 10:20
@light24bulbs - to echo @rulatir, I got here because [Storybook's quick start guide says to use `npx` to install it](https://storybook.js.org/docs/guides/quick-start-guide/), and I didn't have an easy recipe for how to incant the equivalent spell with `yarn`. If there is an equivalent set of commands for yarn, we should post them on the yarn website, so that page (instead of this thread) is at the top of google search results for "yarn version of npx".

**Comment by pdfrod** [comment] 2020-09-23 18:04
I'm also on the same boat as @codekiln. Whenever I'm following some instructions that say run `npx ...`, I have no idea what's the `yarn` equivalent. An example is [npx tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config).

**Comment by kuworking** [comment] 2020-10-24 06:46
> @light24bulbs - to echo @rulatir, I got here because [Storybook's quick start guide says to use `npx` to install it](https://storybook.js.org/docs/guides/quick-start-guide/), and I didn't have an easy recipe for how to incant the equivalent spell with `yarn`. If there is an equivalent set of commands for yarn, we should post them on the yarn website, so that page (instead of this thread) is at the top of google search results for "yarn version of npx".

Same here, with capacitorjs installation guide https://capacitorjs.com/docs/getting-started, the feeling is that this persuades the user to abandon yarn and go back to npm

**Comment by delanym** [comment] 2020-11-05 14:49
https://yarnpkg.com/en/docs/cli/exec

**Comment by bluelovers** [comment] 2020-11-05 20:57
> https://yarnpkg.com/en/docs/cli/exec

404: Page Not Found

**Comment by karlhorky** [comment] 2020-11-07 17:36
I guess @delanym meant this page (but I don't think this replicates `npx`): https://yarnpkg.com/cli/exec

**Comment by htfy96** [comment] 2020-12-25 20:44
For anyone reading this trying to find a quick alternative to `npx -p @storybook/cli sb init`, you can use:
```
yarn global add @storybook/cli
yarn exec sb init
```

**Comment by somethingelseentirely** [comment] 2021-01-01 18:02
So once you want to use `babel`, you have to also use `npm`, to get npx?

**Comment by megawebmaster** [comment] 2021-01-06 14:16
If anyone else is wondering: you can use `npx`  to run immediately with `yarn` too, i.e. `npx sb init` calls `yarn install` after packages are added to `package.json` :+1:

**Comment by merceyz** [comment] 2021-01-06 14:40
If you use `npx` to run a local binary then you can just use `yarn <bin name>`. In Yarn v2 there is the [yarn dlx](https://yarnpkg.com/cli/dlx)` command to download and execute a package once

**Comment by bluelovers** [comment] 2021-01-06 19:16
nobody care about this?
https://www.npmjs.com/package/ynpx

**Comment by koszonetdoktor** [comment] 2021-02-08 10:40
> @light24bulbs - to echo @rulatir, I got here because [Storybook's quick start guide says to use `npx` to install it](https://storybook.js.org/docs/guides/quick-start-guide/), and I didn't have an easy recipe for how to incant the equivalent spell with `yarn`. If there is an equivalent set of commands for yarn, we should post them on the yarn website, so that page (instead of this thread) is at the top of google search results for "yarn version of npx".

One command:
```npx ynpx sb init```
