### ISSUE TITLE
ui-router-ng2@1.0.0-beta.4 can't be installed withour --ignore-engines

### ISSUE THREAD

**Issue by bypotatoes** [yarnpkg/yarn#2977] opened 2017-03-23 11:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I'm trying to switch to yarn, but `yarn install` raises `The engine "node" is incompatible with this module` error

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn install
```
```
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error ui-router-ng2@1.0.0-beta.4: The engine "node" is incompatible with this module. Expected version ">6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**What is the expected behavior?**
It shouldn't raise an error, since `npm show ui-router-ng2@1.0.0-beta.4 engines` => `{ node: '>6' }` and I have no idea how to resolve it except `--ignore-engines`

**Please mention your node.js, yarn and operating system version.**
`node -v` => `6.9.1`
`yarn -V` => `0.21.3`
macOS Sierra

**Comment by sjelfull** [comment] 2017-06-13 15:37
I'm getting this error on any package I'm trying to install globally.

**Comment by rally25rs** [comment] 2017-06-13 17:29
Confirmed on Yarn v0.24.6, OSX Sierra:

```
$ nvm use v6.3.0
Now using node v6.3.0 (npm v3.10.3)

$ yarn add ui-router-ng2@1.0.0-beta.4
yarn add v0.24.6
[1/4] 🔍  Resolving packages...
warning ui-router-ng2 > ui-router-rx@0.2.1: This npm package 'ui-router-rx' has been renamed to '@uirouter/rx'
[2/4] 🚚  Fetching packages...
warning 7zip-bin-linux@1.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-linux@1.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
warning 7zip-bin-win@2.1.0: The platform "darwin" is incompatible with this module.
info "7zip-bin-win@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
error ui-router-ng2@1.0.0-beta.4: The engine "node" is incompatible with this module. Expected version ">6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

This seems to be an issue with NPM's `semver` package:

```
$ node
> const s = require('semver')
undefined
> s.satisfies('6.3.0', '>6', false);
false
> s.satisfies('6.3.0', '>6.0', false);
true
```

So 6.3.0 does not satisfy >6, but does satisfy >6.0.

IIRC I think I read somewhere that NPM stopped erroring on engines mismatches, only a warning. Yarn stops the install. This may explain the difference in functionality.

[I opened an issue on npm-semver](https://github.com/npm/node-semver/issues/198) to see if this is intentional or a bug:

**Comment by rally25rs** [comment] 2017-06-13 17:41
Ah, here we go:

```
$ node
> const s = require('semver')
undefined
> s.validRange('>6.0')
'>=6.1.0'
> s.validRange('>6')
'>=7.0.0'
```

So `>6` actually means `7.0.0 or higher`. Makes sense 😉 
So according to NPM semver, Yarn is correct in reporting that the engine does not match.

We can wait and see what the NPM folks say, but I think this is because by this rule on https://docs.npmjs.com/misc/semver:

> 1 := 1.x.x := >=1.0.0 <2.0.0

so if `1` is equivelant to `>=1.0.0 <2.0.0` then `>1` has to be `> (>=1.0.0 <2.0.0)` which would be the same as `>=2.0.0`

I'm going to mark this issue closed for now, but if the issue I opened on npm-semver gets marked as a bug, then I'll re-open it.

**Closed by rally25rs** 2017-06-13 17:41 UTC
Labels: triaged
