### ISSUE TITLE
Yarn upgrade-interactive --latest freezes

### ISSUE THREAD

**Issue by alexdevero** [yarnpkg/yarn#6592] opened 2018-10-29 09:01 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Yarn freezes after running `upgrade-interactive --latest` and selecting dependencies  to upgrade. Updating `package.json` manually and running `yarn install` works.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run `upgrade-interactive --latest`.
2. Select dependencies to upgrade and confirm.

**What is the expected behavior?**
Yarn should download the latest version of selected dependencies.

**Please mention your node.js, yarn and operating system version.**
Node: v11.0.0
NPM: 6.4.1
OS: Win 10 (1803)
CLI: tried on Windows native CMD, ConEmu and Cmder.

**Videos**
Running `yarn upgrade-interactive --latest`:
![yarn-upgrade-01](https://user-images.githubusercontent.com/4237724/47639049-a5cfc300-db60-11e8-99bc-a99e5f48841b.gif)

Updating `package.json` manually and running `yarn install`:
![ezgif-1-f14f7e9ffc73](https://user-images.githubusercontent.com/4237724/47639840-8174e600-db62-11e8-8b03-e22979664ab8.gif)

**Comment by rally25rs** [comment] 2018-10-29 18:46
It seems to work fine for me. Might be something with your specific packages and options? Could you try adding `--verbose` flag too and see if that gives any indication of what it's doing?

**Comment by dbusacca** [comment] 2018-10-30 08:00
I've got the same issue (even without --latest) in three different Windows 10 pc. I think it's a node 10 incompatibility issue.

It's has been already reported in https://github.com/yarnpkg/yarn/issues/6367

**Comment by alexdevero** [comment] 2018-10-30 08:03
@rally25rs what version of node do you have on your computer?

**Comment by IlCallo** [comment] 2018-11-05 11:15
Same here.
Running on Node 10.13

**Comment by rally25rs** [comment] 2018-11-05 13:10
I tried node 10.1 and 10.13 on OSX and didn't have any problems. Might just be a Windows + node 10 specific issue? Unfortunately I don't have my Windows machine with me today to try that out. If someone who can consistently reproduce this could help debug, that would be awesome!

**Comment by rally25rs** [comment] 2018-11-05 13:15
Closing as duplicate of #5949 
Let's continue the discussion there.

**Closed by rally25rs** 2018-11-05 13:15 UTC
Labels: help wanted, os-windows

**Comment by AliMD** [comment] 2022-03-11 19:37
same issue with OSX and node v16.13.2

**Comment by wouter-leistra** [comment] 2023-02-08 08:21
experiencing the same issue with OSX and node v16.16.0 in a yarn (v3.3.1) workspace monorepo. I can select the packages but then the Resolution step freezes and the terminal (fish) becomes unresponsive.
