### ISSUE TITLE
Cannot execute globally installed packages (Windows)

### ISSUE THREAD

**Issue by jeffrson** [yarnpkg/yarn#3685] opened 2017-06-21 12:41 UTC
On Windows,
"yarn global add typescript" installs to %LOCALAPPDATA%\Yarn\config\global\node_modules (actually expanded to "c:\users\<user>\AppData\Local\Yarn\...) - executable scripts go that folder's subfolder .bin

However, "yarn global bin" shows %LOCALAPPDATA%\Yarn\bin, or "c:\users\<user>\AppData\Local\Yarn\bin", respectively. This folder doesn't exist at all.

**What is the expected behavior?**
I don't know where you really want to put the global modules. However, since "c:\users\<user>\AppData\Local\Yarn\bin" is appended to the user's PATH environment variable I would suppose this is the right folder.

Strangely enough, since "yarn config get prefix" yields "undefined", I tried "yarn config set prefix "c:\users\<user>\AppData\Local\Yarn\bin"" (which obviously is the above listed global bin). Then global modules are indeed installed there.

**Please mention your node.js, yarn and operating system version.**
Behaviour is the same for yarn 0.24.6 and 0.26.1, node 8.1.2, Windows 10 1703 - yarn had been installed first by chocolatey, but I tried the msi as well.

**Comment by ujaroe** [comment] 2017-06-22 14:40
For the records - since I've been playing around with the prefix config, I cannot reproduce this bug anymore. I removed the prefix config and it still installs fine.

For me it looks like yarn hadn't been able to write to "c:\users\<user>\AppData\Local\Yarn\bin", but now it is. I cannot tell, however, where the difference is :-(

**Comment by BYK** [comment] 2017-10-27 11:30
>I cannot reproduce this bug anymore. I removed the prefix config and it still installs fine.

Closing then :)

**Closed by BYK** 2017-10-27 11:30 UTC
Labels: bug-configuration, os-windows, triaged

**Comment by TomasHubelbauer** [comment] 2018-07-15 11:16
I fixed this by adding the result of `yarn global bin` to my environment variables for the system (not the user, where it already was, but didn't work).

**Comment by katlimruiz** [comment] 2018-12-14 15:35
> I fixed this by adding the result of `yarn global bin` to my environment variables for the system (not the user, where it already was, but didn't work).

this worked perfectly

**Comment by spences10** [comment] 2020-05-20 07:23
I know this issue is very old but leaving this here for the next Google search that leads someone here:

I added this to my `.bashrc` file:

```
# add this if yarn global packages don't work
export PATH="$(yarn global bin):$PATH"
```

Then reload the file with:

```
# path to .bashrc file
. /home/my_username/.bashrc
```

**Comment by xDKevz** [comment] 2020-05-28 03:11
> I know this issue is very old but leaving this here for the next Google search that leads someone here:
> 
> I added this to my `.bashrc` file:
> 
> ```
> # add this if yarn global packages don't work
> export PATH="$(yarn global bin):$PATH"
> ```
> 
> Then reload the file with:
> 
> ```
> # path to .bashrc file
> . /home/my_username/.bashrc
> ```

thanks this worked perfectly!
