### ISSUE TITLE
Yarn install on a different folder using --modules-folder clears the default node_modules folder

### ISSUE THREAD

**Issue by njlr** [yarnpkg/yarn#5289] opened 2018-01-29 10:42 UTC
Yarn install on a different folder using --modules-folder clears the default node_modules folder. 

Full description in this repo: https://github.com/njlr/yarn-is-weird

**Comment by bestander** [comment] 2018-01-29 17:01
Duplicate of https://github.com/yarnpkg/yarn/issues/1684, this is not on the hi priority list right now but should be relatively easy to fix.
Would be great if someone sent a PR with a fix

**Closed by bestander** 2018-01-29 17:01 UTC
Labels: triaged
