### ISSUE TITLE
yarn init working directory issue

### ISSUE THREAD

**Issue by chrisblossom** [yarnpkg/yarn#4437] opened 2017-09-13 17:26 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I was creating a new example repository for a different issue and ran into something very strange. It seems yarn is not running in the correct directory.

```
➜  github mkdir yarn-issue-temp1
➜  github cd yarn-issue-temp1
➜  yarn-issue-temp1 yarn init
yarn init v1.0.1
warning package.json: No license field
question name (chris):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
✨  Done in 2.15s.
➜  yarn-issue-temp1 ls
➜  yarn-issue-temp1 yarn add gzip-size@3.0.0
yarn add v1.0.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-safe-universal-inputs@1.0.3" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-safe-universal-inputs@1.0.3" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
├─ duplexer@0.1.1
└─ gzip-size@3.0.0
✨  Done in 0.46s.
➜  yarn-issue-temp1 ls
➜  yarn-issue-temp1 ls
➜  yarn-issue-temp1 ls -alh
total 0
drwxr-xr-x   2 chris  staff    68B Sep 13 10:19 .
drwxr-xr-x  69 chris  staff   2.5K Sep 13 10:19 ..
➜  yarn-issue-temp1 pwd
/Users/chris/github/yarn-issue-temp1
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**What is the expected behavior?**
yarn inits into correct directory

**Please mention your node.js, yarn and operating system version.**
```
yarn 1.0.1
node 6.11.3
osx 10.12.6
```

**Comment by BYK** [comment] 2017-09-13 22:11
Duplicate of #4441.

**Closed by BYK** 2017-09-13 22:11 UTC
