### ISSUE TITLE
Know from which dependency the "unmet peer dep" message comes from

### ISSUE THREAD

**Issue by tleunen** [yarnpkg/yarn#2297] opened 2016-12-19 19:25 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
We don't know from what packages we have the unmet peer dependencies.

**What is the expected behavior?**
It would be great to know from what packages these peer dependencies come from.

-- 

We only see messages like this:
```
warning Unmet peer dependency "cheerio@0.19.x || 0.20.x || 0.22.x".
```
I believe it might be helpful to know from which dependency they actually come from, especially when the version range is not the latest so we know in which package we must upgrade them.

**Comment by OmgImAlexis** [comment] 2016-12-20 02:10
It'd also be great to see a link to their repo, etc. from the associated `package.json`.

**Comment by pablolmiranda** [comment] 2016-12-21 03:06
The strings already support that: https://github.com/yarnpkg/yarn/blob/546c970551f47ae4ced2e4d90386ec434607009c/src/reporters/lang/en.js#L148
But for some reason, that change didn't go out on 0.18.1.

**Comment by graingert** [comment] 2016-12-21 10:21
duplicate of https://github.com/yarnpkg/yarn/issues/1556

**Closed** 2016-12-21 13:29 UTC
