### ISSUE TITLE
Cannot add "progress" module

### ISSUE THREAD

**Issue by KenanSulayman** [yarnpkg/yarn#2220] opened 2016-12-10 20:33 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

```
$ yarn add progress
yarn add v0.17.10
error Missing list of packages to add to your project.
```

Works for all other modules; a workaround is `npm i --save progress` and then `yarn`.

**What is the expected behavior?**

install and add the module

**Environment**

yarn v0.17.10
node 7.2.1
OS information is classified, sorry.

**Comment by mlcdf** [comment] 2016-12-11 15:29
Same problem here. My environment:
yarn v0.17.10
node 6.9.1
Ubuntu 16.10

Thanks for the workaround @KenanSulayman. :+1:

**Comment by iredchuk** [comment] 2016-12-11 23:33
The issue is in [src/cli/index.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L181), when commander parses args and **progress** becomes the first argument besides startArgs (node yarn), it is parsed as an option since **--no-progress** option is defined [above](https://github.com/yarnpkg/yarn/blob/master/src/cli/index.js#L81).

A quick fix would be to add **commandName** back when parsing args, but that looks like a workaround: https://gist.github.com/iredchuk/689e7cf949e22c708b68befb7662855d

**Comment by iredchuk** [comment] 2016-12-11 23:52
Didn't work with commander before, but this behaviour looks weird to me: the last case is what's happening here when the arg is lost due to the name collision with an option: https://gist.github.com/iredchuk/ab253c68a880d45e0ab99d853fc56ddc

Wonder if it's possible to change this via some commander settings, e.g. do not parse arg as option when it's not preceded with '--'?

**Comment by tuures** [comment] 2016-12-13 20:10
workaround: `yarn add -- progress`, note space between `--` and package name, the doubledash instructs yarn not to parse options after that point

**Comment by iredchuk** [comment] 2016-12-14 07:51
Duplicate of #2112

**Closed** 2016-12-14 13:41 UTC
