### ISSUE TITLE
puny code problem

### ISSUE THREAD

**Issue by Samillionaire** [yarnpkg/yarn#9026] opened 2024-01-13 09:42 UTC
![Screenshot (199)](https://github.com/yarnpkg/yarn/assets/98183896/4a648412-044f-444c-9987-82d7f8c2dfe4)

i am getting this error ---  The `punycode` module is deprecated. Please use a userland alternative instead.     at node:punycode:3:9
server is unable to listen the changes but just keeps giving this warning how to fix it , what the alternative of this and how to install it.. in this successfully so the project doesent get affected by this.

**Comment by MikeMcC399** [comment] 2024-01-13 11:36
@Samillionaire 

What is the result of running the following as suggested by the deprecation warning?

```shell
node --trace-deprecation server.js
```

**Comment by Samillionaire** [comment] 2024-01-13 11:43
here it is
also attaching my folder structure for reference 😊
________________________________

**Comment by MikeMcC399** [comment] 2024-01-13 11:54
@Samillionaire 
> here it is 

I cannot see any log in your reply which comes from running

```shell
node --trace-deprecation server.js
```

**Comment by Samillionaire** [comment] 2024-01-13 12:02
actually no reply is coming ,its just the warning .
if i try to update something in my server.js file , it is shown in cmd everytime , but now its not showing the update on cmd but this warning only.

________________________________

**Comment by Samillionaire** [comment] 2024-01-13 12:03
actually no reply is coming ,its just the warning
if i try to update something in my server.js file , it is shown in cmd everytime , but now its not showing the update on cmd but this warning only.

________________________________

**Comment by MikeMcC399** [comment] 2024-01-13 12:10
@Samillionaire 

- Without the output from the `trace-deprecation` it is not possible to judge exactly what the cause of your issue is.
- You can follow the open issue https://github.com/yarnpkg/yarn/issues/9013 which may be the same problem that you are seeing.

**Comment by Samillionaire** [comment] 2024-01-13 12:11
ok Thank you very much
________________________________

**Comment by RDIL** [comment] 2024-01-23 14:19
Duplicate of #9013

**Closed by RDIL** 2024-01-23 14:19 UTC

**Comment by IgorGanapolsky** [comment] 2024-06-07 20:29
> @Samillionaire
> 
> What is the result of running the following as suggested by the deprecation warning?
> 
> ```shell
> node --trace-deprecation server.js
> ```

How do we use this with React Native?

**Comment by MikeMcC399** [comment] 2024-06-07 21:00
@IgorGanapolsky 

You can also set the environment variable `NODE_OPTIONS`, then run the command which was showing a deprecation warning. For instance:

```shell
export NODE_OPTIONS='--trace-deprecation' 
```

**Comment by IgorGanapolsky** [comment] 2024-06-07 21:08
> @IgorGanapolsky 
> 
> You can also set the environment variable `NODE_OPTIONS`, then run the command which was showing a deprecation warning. For instance:
> 
> ```shell
> export NODE_OPTIONS='--trace-deprecation' 
> ```

Thanks, but where would I see the punycode reference from yarn build output?

**Comment by MikeMcC399** [comment] 2024-06-08 04:18
> > @IgorGanapolsky

> Thanks, but where would I see the punycode reference from yarn build output?

Which version of Yarn are you using?

**Comment by IgorGanapolsky** [comment] 2024-06-18 16:27
v1.22.22
