### ISSUE TITLE
yarn outdated does not show URLs

### ISSUE THREAD

**Issue by raido** [yarnpkg/yarn#4650] opened 2017-10-06 13:15 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Running "yarn outdated" displays a lists of dependencies with no URLs

**If the current behavior is a bug, please provide the steps to reproduce.**

Not sure, yarn is installed with "brew install yarn", version is v1.1.0. Same v1.1.0 version on another machine works fine.

**What is the expected behavior?**

URLs would be visible.

**Please mention your node.js, yarn and operating system version.**

macOS 10.13, Node.js v6.11., Yarn: v1.1.0

**Comment by devoto13** [comment] 2017-10-07 14:06
Possible duplicate of https://github.com/yarnpkg/yarn/issues/3444. This issues seems to be related to misconfiguration of particular CDN nodes.

**Comment by raido** [comment] 2017-10-07 16:13
Hmm, actually on the machine that it is not working as expected I have local registry running on - https://github.com/verdaccio/verdaccio - I’ll first check if I am running the latest version and check then if the issue persists.

**Comment by raido** [comment] 2017-10-09 11:22
I updated my Verdaccio based registry, no change. Looking through "npm-registry.js" it seems it should work fine. First trying to get "homepage" value with fallback to "repository.url".

**Closed** 2017-11-07 10:39 UTC
Labels: cat-bug, good first issue, help wanted, triaged
