### ISSUE TITLE
PostCSS binary is executed after running script named `css`

### ISSUE THREAD

**Issue by dan-lee** [yarnpkg/yarn#3051] opened 2017-04-06 07:21 UTC
**Do you want to request a *feature* or report a *bug*?**
_Bug_

**What is the current behavior?**
A script called `css` will trigger executing the binary of the package `postcss` in `node_modules`.

⚠️ NPM won't execute `postcss`

**If the current behavior is a bug, please provide the steps to reproduce.**
* `yarn add postcss`
* Add an entry with the key `css` into the scripts section of a `package.json`:
```json
"scripts": {
  "css": "echo 1"
}
```
* `yarn css`

**What is the expected behavior?**
Do not trigger the binary `node_modules/.bin/postcss` after `css` script is done.

**Please mention your node.js, yarn and operating system version.**
node.js: v6.10.0
yarn: v0.21.3
OS: macOS Sierra 10.12.4

**Comment by tobiastom** [comment] 2017-05-23 17:14
This seems to be a duplicate of #2442.

**Closed** 2020-07-15 21:17 UTC
