### ISSUE TITLE
Lockfile sorting is different on different platforms

### ISSUE THREAD

**Issue by yunxing** [yarnpkg/yarn#1177] opened 2016-10-18 00:19 UTC
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**
When calling yarn install on Linux, it changes the order of the dependencies in the lock file thus create a diff which is unnecessary. 
![image](https://cloud.githubusercontent.com/assets/1017689/19459990/4be8d132-948c-11e6-8346-faf0420270c2.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
On linux:
```
git clone https://github.com/facebook/infer; cd infer
yarn install
git diff
```
Notice how the lockfile got changed

**What is the expected behavior?**
lockfile shouldn't change

**Please mention your node.js, yarn and operating system version.**
Linux 
node v4.3.2
yarn v0.15.0

**Comment by vinnymac** [comment] 2016-10-18 04:06
Dupe of #1168

**Comment by rjmunro** [comment] 2016-10-25 15:06
Does this still happen if you use `--pure-lockfile`? If #570 was fixed, this might become much less of an issue.

**Closed** 2016-10-25 15:57 UTC
