### ISSUE TITLE
Why does `yarn ls <package>` not show the tree?

### ISSUE THREAD

**Issue by adamreisnz** [yarnpkg/yarn#2278] opened 2016-12-17 00:22 UTC
Yarn v0.17.10, Node v7.2.1, OS X;

NPM output:
```shell
> npm ls fsevents
my-package@1.3.3 /some/where
└─┬ babel-cli@6.18.0
  └─┬ chokidar@1.6.1
    └── fsevents@1.0.15 
```

Yarn output:
```shell
> yarn ls fsevents
yarn ls v0.17.10
└─ fsevents@1.0.15
✨  Done in 1.75s.
```

Is this discrepancy intentional? I like seeing the tree view to show me where a package is coming from.

When I do `yarn why fsevents`, I get the info I need, but the output is more limited and not organised in a nice dependency tree view;

```shell
info This module exists because "babel-cli#chokidar" depends on it.
```

I can imagine this can get quite cluttered for a deep dependency. Plus, it doesn't show the versions of `babel-cli` and `chokidar`, which means if I'm trying to analyse an issue I won't know what version package is involved.

**Comment by SimenB** [comment] 2016-12-17 10:52
Dupe of #1845

**Closed** 2016-12-17 14:35 UTC
