### ISSUE TITLE
yarn init does not write package.json if one exists up the tree

### ISSUE THREAD

**Issue by SimenB** [yarnpkg/yarn#4671] opened 2017-10-10 08:39 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
With this structure
```sh-session
$ tree .
.
├── nested
└── package.json

1 directory, 1 file
```

Calling `yarn init -y` in `nested` make yarn output that a new package.json was created, while it was actually not.

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh-session
$ tree .
.
├── nested
└── package.json

1 directory, 1 file
$ cd nested
$ yarn init -y
yarn init v1.2.0
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
✨  Done in 0.03s.
$ cd ..
$ tree .
.
├── nested
└── package.json

1 directory, 1 file
```

**What is the expected behavior?**
Either actually create the file, or throw a useful error that a package.json exists up the tree already.

FWIW `npm init -y` worked perfectly (it created a new file).

"Fun" bonus is that `yarn add some-package` in `nested` results in it adding the dependency to the parent directory, package.json and yarn.lock, without warning that it's not modifying a `package.json` in CWD.

**Please mention your node.js, yarn and operating system version.**
node@8.6.0, yarn@1.2.0, macOS

**Comment by BYK** [comment] 2017-10-10 17:23
Duplicate of #4441.

**Closed by BYK** 2017-10-10 17:23 UTC
