### ISSUE TITLE
Error: Could not authenticate deployment

### ISSUE THREAD

**Issue by yorch** [yarnpkg/yarn#1952] opened 2016-11-19 15:41 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Getting an error when trying to run `yarn install` on an Angular 2 project that works fine with `npm install`

```
yarn install v0.17.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular%2fcommon: Could not authenticate deployment".
info If you think this is a bug, please open a bug report with the information provided in "/Users/user/Project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a project using angular-cli
- Delete `node_modules`
- Run `yarn install`

**What is the expected behavior?**
To yarn to run successfully and to have all the dependencies installed in `node_modules`

**Please mention your node.js, yarn and operating system version.**
node 7.1.0, installed with nvm
MacOS 10.11.6
yarn 0.17.6

**Comment by hpurmann** [comment] 2016-11-19 16:11
Hey @yorch! Maybe `/Users/user/Project/yarn-error.log` contains some helpful debug information. Can you post it here?

**Comment by olingern** [comment] 2016-11-19 16:12
Indeed. I'm unable to reproduce given your description.

**Comment by Daniel15** [comment] 2016-11-19 18:33
I have no idea where that error message is coming from, I don't see it anywhere on GitHub at all :P https://github.com/search?q=%22could+not+authenticate+deployment%22&type=Code&utf8=%E2%9C%93

**Comment by yorch** [comment] 2016-11-20 06:54
So I tried to replicate the problem on another mac, and couldn't. Went back to the original mac where I had the problem, and seems like the problem is related to the `~/.npmrc` file. It contains something like:

```
init.author.name = My Name
init.author.email = myemail@company.com
init.author.url = http://profile
#registry = http://internal-url/
email = myemail@company.com
_auth = SOMEAUTHCODE
```

The last line is the one causing troubles, not sure why considering that npm works fine with it. Not sure if this is a bug or expected behaviour.

In any case, thanks for your help!

**Comment by klaemo** [comment] 2016-11-22 16:18
I had the same issue:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@kadira%2fstorybook: Could not authenticate klaemo".
```

When I commented out the `_auth` line from `.npmrc` it started working.

**Comment by therealklanni** [comment] 2017-04-20 22:35
This also affects `yarn install`

**Comment by bestander** [comment] 2017-05-25 15:22
This should be quite easy to fix, as the code that reads those .npmrc settings is easy to find, a PR is welcome.

**Comment by mapsam** [comment] 2017-06-02 23:17
I hit this as well - can confirm commenting out the `_auth` line in the `~/.npmrc` file does the trick.

**Comment by BYK** [comment] 2017-06-05 23:26
Working on this

**Comment by BYK** [comment] 2017-06-08 01:19
Okay, I realized this only happened if you had an old `_auth` entry which did not contain your current, valid login information (hence why it was hard to track it down). Also I noticed this was fixed on master so I started bisecting. Looks like https://github.com/yarnpkg/yarn/commit/33820719e2c049ff93e86d29251b96d496f2b6e8 solved it which made it into the `v0.26.x` releases so upgrading your yarn should resolve the issue.

**Comment by Daniel15** [comment] 2017-06-08 01:40
0.26.x is still an RC release though, so only upgrade to it if you're comfortable testing an RC 😃

**Comment by mapsam** [comment] 2017-06-08 05:36
Thanks for investigating @BYK!

**Comment by arcanis** [comment] 2017-06-13 15:52
Apparently fixed, so I'm going to close this issue for now 👍

**Closed by arcanis** 2017-06-13 15:52 UTC
Labels: bug, bug-configuration, bug-high-priority, good-first-contribution, triaged

**Comment by szarouski** [comment] 2017-07-01 19:45
@arcanis just came back after update to 0.27.5 from 0.26.1

**Comment by arcanis** [comment] 2017-07-01 20:10
The commit that fixed this issue was breaking installing private package :/ @BYK I kinda remember you worked a bit on this, what do you think would be the best way to solve this issue? If I understand correctly:

- When fetching a private package from the NPM registry, the auth token must be sent (logic)
- When fetching a public package from the NPM registry, the auth token must NOT be sent (weird?)
- Afaik there's no way to know if a package is public/private without trying

So it seems the only course of action here would be to try without the token, then try again with a token if it fails with a 404 status. Wdyt?

**Comment by BYK** [comment] 2017-07-03 13:15
I think NPM allows you to make authenticated requests for public packages without a problem provided that your tokens are valid. May be we can retry with/without a token if the first request fails?

We can also probably save the token/no-token preference per package to somewhere for future requests?

**Comment by arcanis** [comment] 2017-07-03 20:04
I was probably tired, I can't reproduce this issue on the computer I thought it failed... Just tried with 0.27.5, and it worked just fine with both public & private scopped packages 😶

**Comment by pensierinmusica** [comment] 2017-07-06 13:26
@szarouski yep I confirm it comes back to me as well in `v0.27.5`. @arcanis @lumaxis @bestander any idea what is causing it?

relates #2507

**Comment by arcanis** [comment] 2017-07-06 13:30
@pensierinmusica Can you try to check inside your ~/.npmrc or ~/.yarnrc file? Is there an `_auth=` key, or `_authToken=`?

**Comment by pensierinmusica** [comment] 2017-07-06 13:51
Ok, I've solved it. It looks like I had changed the password in the meantime and the `.npmrc` file was not updated accordingly. For future reference in case other users hit the same problem, you just need to run `npm login` and authenticate.

@arcanis maybe this could be suggested right there in the error message?
