### ISSUE TITLE
Unable to resolve es-abstract 1.14.0

### ISSUE THREAD

**Issue by meowsus** [yarnpkg/yarn#7828] opened 2020-01-21 21:03 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Running `yarn` in my project produces the following error:

```sh
$ yarn
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/meowsus/Work/workarea-blog/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The quickest way to reproduce that I can think of:

```sh
$ cd /tmp
$ git clone https://github.com/workarea-commerce/workarea-blog.git
$ cd workarea-blog
$ yarn
```

**What is the expected behavior?**

Yarn should properly resolve the dependencies of the following `package.json`:

```json
{
  "devDependencies": {
    "eslint": "~5.16.0",
    "eslint-config-recommended": "~4.0.0",
    "stylelint": "~10.1.0",
    "stylelint-config-recommended-scss": "~3.3.0",
    "stylelint-scss": "~3.9.2"
  }
}
```

as `es-abstract 1.14.0` is listed in the registry here: https://yarnpkg.com/en/package/es-abstract

**Please mention your node.js, yarn and operating system version.**

That information should be able to be groked from my [yarn-error.log](https://gist.github.com/meowsus/35fe47f3374683a5ea5f38c80323b3c9).

**Comment by ninio** [comment] 2020-01-22 09:54
Seems like there is general problem with serving `.tgz` files from registry.yarnpkg.com.

Trying to use yarn to create react app (`yarn create react-app test-app`) fails with:
```
"https://registry.yarnpkg.com/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
```

Also running `yarn add @material-ui/icons` fails too with the following error (that might be related):
```
Error: https://registry.yarnpkg.com/@material-ui/icons/-/icons-4.5.1.tgz: ESOCKETTIMEDOUT
```

**Comment by olingern** [comment] 2020-01-27 03:00
I pasted your dependencies into a `package.json` and tested. Currently working for me on `1.21.1`

I'm also able to run `yarn add es-abstract` without issue. This could be a problem with that package and not yarn.

Will close if cannot reproduce

**Comment by paul-soporan** [comment] 2021-01-03 16:25
Closing as unactionable and unreproducible, likely just a registry issue at that time.

**Closed by paul-soporan** 2021-01-03 16:25 UTC
Labels: triaged, will-close
