### ISSUE TITLE
401 error when using yarn with VSTS; works with 0.27.5 and NPM

### ISSUE THREAD

**Issue by SuhairZain** [yarnpkg/yarn#4873] opened 2017-11-07 15:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The latest version of `yarn` fails with 401 error when fetching packages from our private Visual Studio Team Services channel. It works when I fall back to 0.27.5 or when I use npm. The failing package seems to change on each try.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The following is the console output:
```
yarn install v1.3.2
[1/5] Resolving packages...
[2/5] Fetching packages...
error An unexpected error occurred: "https://xxxxxx.pkgs.visualstudio.com/_packaging/8cc7db9e-2c6c-4bac-b0e4-14010c159200/npm/registry
/husky/-/husky-0.14.3.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\xxxxxx\\xxxxxx-cms\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
The following is the error log: https://pastebin.com/jMaNS55Q

**Please mention your node.js, yarn and operating system version.**
Node: v8.5.0
Yarn:  v1.3.2

**Comment by torifat** [comment] 2017-11-08 13:55
Are you using `HTTP_PROXY` or `HTTPS_PROXY` `env` variable?

**Comment by SuhairZain** [comment] 2017-11-09 06:19
@torifat I don't have either of them set.

**Comment by BYK** [comment] 2017-11-09 11:48
Can this be a duplicate of #4672?

**Comment by torifat** [comment] 2017-11-09 12:05
Duplicate of #4672

**Closed by torifat** 2017-11-09 12:05 UTC
Labels: triaged
