### ISSUE TITLE
[BUG] Does not install git dependencies correctly, does not run "prepare" script.

### ISSUE THREAD

**Issue by trusktr** [yarnpkg/yarn#7910] opened 2020-02-15 22:58 UTC
Will this be fixed in Yarn 2?

### Bug description

**Command**

```sh
yarn add "code-vue@trusktr/live-code#6085bf5ca1a7faa5ea021a0fc61f6ba08e08030d"
```

**What is the current behavior?**

when you look in `node_modules/code-vue/` you will see it does not have a `dist` folder. 

**What is the expected behavior?**

However when running

```
npm i "code-vue@trusktr/live-code#6085bf5ca1a7faa5ea021a0fc61f6ba08e08030d"
```

then you will see that `node_modules/code-vue/dist` exists, as expected.

**Steps to Reproduce**

Just run that above yarn command to add that package to a project, then see `node_modules/code-vue/dist` does not exist.

**Environment**

- Node Version: `13.8`
- Yarn v1 Version: `1.22.0` 
- OS and version: Manjaro Linux

**Comment by gnprice** [comment] 2022-05-25 21:37
It looks like this is the same issue as #5235. Unfortunately, the outcome there is: https://github.com/yarnpkg/yarn/issues/5235#issuecomment-754993583
> This issue is fixed in Yarn 2+, and the fix will not be backported in 1.x. Please check the [Migration guide](https://yarnpkg.com/getting-started/migration#step-by-step) and continue from there.

**Comment by merceyz** [comment] 2022-05-25 22:03
Duplicate of https://github.com/yarnpkg/yarn/issues/5235

**Closed by merceyz** 2022-05-25 22:03 UTC
