### ISSUE TITLE
Upgrade single package

### ISSUE THREAD

**Issue by tomitrescak** [yarnpkg/yarn#1034] opened 2016-10-14 00:28 UTC
Hi, I really tried to find this before posting here, but I cannot find a way of upgrading a single package. I can only upgrade all of them, Is it possible? Something like:

```
yarn upgrade mypackage
```

**Comment by Daniel15** [comment] 2016-10-14 06:10
Using `yarn add mypackage` should update the package to the latest one.

**Comment by kennydee** [comment] 2016-10-14 06:29
Hmm, this is not the way i understand the documentation ? https://yarnpkg.com/en/docs/usage

It says use the syntax `yarn upgrade [package]` to upgrade a dependency, or if i do `yarn upgrade color` for exemple, i got : 
```bash
yarn upgrade color
yarn upgrade v0.15.1
error This command doesn't require any arguments.
info Visit http://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

And this page is not telling the same thing : https://yarnpkg.com/en/docs/cli/upgrade

So i think this documentation page `https://yarnpkg.com/en/docs/usage` is not uptodate  :)

**Comment by kennydee** [comment] 2016-10-14 06:31
Ok, i think it is a duplicate of #598

**Comment by Daniel15** [comment] 2016-10-14 06:32
Yeah I think the docs are out-of-date.

Sorry my comment was vague, I should have clarified. `yarn upgrade` upgrades all packages to the latest version that matches the version range specified in the `package.json`. It does **not** edit the package.json file though. Using `yarn add` on an existing package **will** update the `package.json` to reference the latest version number, and also install that version.

**Comment by kennydee** [comment] 2016-10-14 06:36
Yes, you're right. Thanks for clarification.

But as @cpojer say in #598, it seems that the correct behavior was the one on the main doc (upgrade should be able to upgrade one dependancy)

So i don't know if the main doc should be updated or if the ability to upgrade one dependency should be added :)

But right now, this is a little bit confusion :)

**Comment by kittens** [comment] 2016-10-14 18:02
Merging into #598.

**Closed by kittens** 2016-10-14 18:02 UTC
Labels: needs triage

**Comment by shaunc** [comment] 2017-10-07 05:39
NB `yarn add package` by itself won't upgrade package to a new version if its from a private repo -- rather it will give you an error (Couldn't find package ...). Would be nice to have a way simply to upgrade a package not re-add....

**Comment by cluis13915** [comment] 2019-01-21 18:48
I have a private Ember addon with a blueprint which install some dependencies.

```
module.exports = {
  description: 'Bla bla bla',
  normalizeEntityName() {},
  afterInstall: function() {
    return this.addAddonsToProject({
      packages: [
        {name: 'ember-changeset', target: '1.3.0'},
        {name: 'ember-changeset-validations', target: '1.2.8'},
        {name: 'ember-form-for', target: '2.0.0-alpha.14'},
        {name: 'ember-truth-helpers'},
        {name: 'ember-power-select'}
    });
  }
}
```

**Comment by Daniel15** [comment] 2019-01-21 20:32
@cluis13915  Please create a separate issue rather than commenting on a closed one.
