### ISSUE TITLE
An unexpected error occurred: "https://registry.yarnpkg.com/<package>: Not found"

### ISSUE THREAD

**Issue by IlCallo** [yarnpkg/yarn#5865] opened 2018-05-24 08:56 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I cannot install some packages globally when in Windows and using Git Bash.
For example, for `@nrwl/schematics` (but also for `@angular/cli`) I get
```
$ yarn global add @nrwl/schematics
yarn global v1.7.0
[1/4] Resolving packages...
error An unexpected error occurred: "https://https://registry.yarnpkg.com/@nrwl/schematics: Not found".
```

Error log:
```
  Error: https://registry.yarnpkg.com/@nrwl/schematics: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:65656:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:134675:22)
      at Request.emit (events.js:159:13)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:135658:10)
      at Request.emit (events.js:159:13)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:135578:12)
      at Object.onceWrapper (events.js:254:19)
      at IncomingMessage.emit (events.js:164:20)
      at endReadableNT (_stream_readable.js:1062:12)
      at process._tickCallback (internal/process/next_tick.js:152:19)
```

In Ubuntu it seems to work just fine.
Same if I use the Windows PowerShell instead of Git Bash.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
That packages are installed

**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v9.3.0

$ yarn config list
yarn config v1.7.0
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.7.0 npm/? node/v9.3.0 win32 x64',
  lastUpdateCheck: 1527149439512 }
info npm config
{}

Windows 10
```

**Comment by bkad** [comment] 2018-05-31 18:54
Getting the same error message, but maybe a different cause?

```
$ docker run --rm node:10 yarn global add @types/graphql@0.12.4

yarn global v1.7.0
[1/4] Resolving packages...
(node:1) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@types/graphql/-/graphql-0.12.4.tgz: Request failed \"404 Not Found\"".
```

**Comment by IlCallo** [comment] 2018-05-31 19:04
Yeah, seems a different one. Mine seems to be triggered by the usage of Git Bash and it's strange behaviour around the "/" character on Windows.

Today I noticed that now it doesn't install any package with a namespace, probably because it converts "/" to "\" for some obscure reasons...

**Comment by Jasu** [comment] 2018-06-04 10:55
This seems to happen randomly - if I run curl repeatedly, the following works around 10% of the time:

```
curl 'https://registry.yarnpkg.com/@types/node/-/node-9.4.2.tgz'
```

**Comment by chiel** [comment] 2018-06-06 09:22
Getting the same issue during our CI build, always fails on the same url @Jasu posted. Indeed it seems to happen randomly so I don't think changing yarn client version or anything will happen. Almost seems like there's a caching layer in place that has cached a 404 on some of its nodes or something.

**Comment by sgraham785** [comment] 2018-06-06 22:05
yep upgrading my @types/node dep to 9.6.0 worked. not ideal but worked. 

i think it's important to mention that this is not a yarn only issue as I found the same issue using npm only and discovered that the @types/9.4.2 & 9.4.3 tarballs missing from the interwebs which could be something to do with removal of those packages by DefinitelyTyped or storage issue on npmjs.org, I wasn't able to find much other info regarding this issue which is why i am adding the context

**Comment by anied** [comment] 2018-06-12 15:28
Hey all, heads up-- Had this same issue on mac and was able to resolve this with the following steps:

- Upgraded to latest yarn version (**might not actually be necessary, but wanted to note it was a step I took**)
- remove `node_modules`
- remove `yarn.lock`
- `yarn install`

And everything worked/installed as expected.

**Comment by vinujosef** [comment] 2018-06-13 06:17
@anied I also have the similar issue, but when I remove `yarn.lock` -> it shows "No lockfile found" and quits the process.

**Comment by Ranhiru** [comment] 2018-06-20 07:14
After upgrading from Yarn 1.6.0 to 1.7.0 I just deleted the lock file and ran `yarn install`. Then my `yarn add` commands started running again without any issue

**Comment by jamsheedpk** [comment] 2018-10-16 08:05
Arguments: 
  /usr/local/bin/node /usr/bin/yarn add react-native-modelbox

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

Yarn version: 
  1.7.0

Node version: 
  10.4.1

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/react-native-modelbox: Not found
      at Request.params.callback [as _callback] (/usr/lib/node_modules/yarn/lib/cli.js:65656:18)
      at Request.self.callback (/usr/lib/node_modules/yarn/lib/cli.js:134675:22)
      at Request.emit (events.js:182:13)
      at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:135658:10)
      at Request.emit (events.js:182:13)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:135578:12)
      at Object.onceWrapper (events.js:273:13)
      at IncomingMessage.emit (events.js:187:15)
      at endReadableNT (_stream_readable.js:1081:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by jimklo** [comment] 2019-05-02 22:41
Similar issue:

```
> npx create-react-app --info

Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    react: Not Found
    react-dom: Not Found
    react-scripts: Not Found
  npmGlobalPackages:
    create-react-app: Not Found
```

```
> npx create-react-app my-app

Creating a new React app in /Users/jklo/projects/jnwc/source/my-app.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts...

yarn add v1.15.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@csstools/normalize.css/-/normalize.css-9.0.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/jklo/projects/jnwc/source/my-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts --cwd /Users/jklo/projects/jnwc/source/my-app has failed.

Deleting generated file... package.json
Deleting generated file... yarn.lock
Done.
```

[yarn-error.log](https://github.com/yarnpkg/yarn/files/3140185/yarn-error.log)

Curl can download the package without any problems.  Cannot seem to figure out how to even work around this.

**Comment by jaapaurelio** [comment] 2019-05-10 06:16
Had the same problem. I changed my `~/.npmrc` to add `always-auth = false`. It's working now.

**Comment by MartinYounghoonKim** [comment] 2019-05-20 02:20
@jaapaurelio 
I add it, but doesnt' work. Do u have any solution?

**Comment by Stoobaart** [comment] 2019-06-05 10:03
Running the below command in terminal fixed my issue:

yarn config set strict-ssl false

**Comment by IlCallo** [comment] 2019-06-10 08:16
I don't know what that config option does, but given the name it doesn't seem a good idea to set it to false randomly...
Can you explain why you did it and what is it supposed to do?

**Comment by Stoobaart** [comment] 2019-06-10 08:38
Hiya, for me it was causing problems due to my strict secure corporate network. It just allowed me to bypass that. I'd just make sure you know what packages you're installing first, and then flip it back to true afterwards. But I'm far from an expert in this, so if anyone has any insights as to any possible dangers here, I'd love to read about them. Cheers everyone.

**Comment by vabole** [comment] 2019-08-15 09:58
Had this error with sinon:

from packge.json:
    "sinon": "^7.0.0",

error An unexpected error occurred: "https://registry.yarnpkg.com/sinon/-/sinon-7.4.0.tgz: Request failed \"404 Not Found\"".

I was able to resolve it with:
yarn upgrade --latest sinon

Which made yarn look for sinon-7.4.1.tgz instead.

**Comment by gilmoreorless** [comment] 2019-10-01 07:00
Our builds have been failing intermittently with this same error for the last couple of days. The first failure we noticed was at 2019-09-30T00:01 UTC.

The failures are happening fairly frequently (but not every time, more like 80-90% of the time). It's always the same error, but for 4 different packages so far:

* https://registry.yarnpkg.com/@reach/router/-/router-1.2.1.tgz
* https://registry.yarnpkg.com/@storybook/react-stubber/-/react-stubber-1.0.1.tgz
* https://registry.yarnpkg.com/@xtuc/ieee754/-/ieee754-1.2.0.tgz
* https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.2.tgz

Each of these packages is public, and each version that's failing is the latest one published, so upgrading to a newer version isn't an option. Doing a `curl` request directly from one of the build machines returns a `200 OK` response.

The various suggestions above (and in many other issues) to delete `yarn.lock` and re-install the modules aren't going to work, because that completely defeats the point of using a lockfile in the first place. Doing so will upgrade every single transitive dependency, instead of actually fixing what is clearly an intermittent problem with the registry itself.

**Comment by knoxcard** [comment] 2019-10-02 20:20
```
root@TRON:/mnt/c/indospace.io/services# yarn upgrade --latest
yarn upgrade v1.19.0
warning package.json: No license field
error No lockfile in this directory. Run `yarn install` to generate one.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
root@TRON:/mnt/c/indospace.io/services# yarn install
yarn install v1.19.0
warning package.json: No license field
info No lockfile found.
warning No license field
[1/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/binlookup: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/indospace.io/services/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
root@TRON:/mnt/c/indospace.io/services#

```

**Comment by knoxcard** [comment] 2019-10-02 20:56
Problem Solved!  Not a yarn problem, but rather a Windows Subsystem for Linux (WSL): connectivity issue.

**Comment by RyanPWalker** [comment] 2019-10-07 23:01
Oddly enough, I just needed to restart my computer.  The good ol' turn it off and on again.  I tried several different things including the above solutions, but restarting did the trick.

**Comment by bobysf12** [comment] 2019-12-05 00:13
> Problem Solved! Not a yarn problem, but rather a Windows Subsystem for Linux (WSL): connectivity issue.

I'm having the same problem. I'm using WSL too. Could you share how did you solve it? 😄

**Comment by lirbank** [comment] 2019-12-20 17:40
I'm on macOS, and like @RyanPWalker I just rebooted and the error was gone.

**Comment by coYms** [comment] 2019-12-30 09:38
I just delete the yarn.lock file and try yarn add again, It worked !

**Comment by doug31415** [comment] 2020-02-12 15:39
Getting this: 
```
error An unexpected error occurred: "https://registry.yarnpkg.com/7zip-bin: Not found".
```

deleting yarn.lock and node_modules and then reinstalling hasnt worked, we dont use WSL. Might be related to 
https://stackoverflow.com/questions/60185963/error-when-i-run-npm-install-error-404-not-found-7zip-bin4-1-0, 
but the post claims the issues there are fixed

This looks like a problem with yarn. Any thoughts?

**Comment by kaitlynbrown** [comment] 2020-02-12 18:39
I'm seeing this error now when trying to run builds on CodeBuild:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/error-ex/-/error-ex-1.3.2.tgz: Request failed \"404 Not Found\"".
```

**Comment by jsbroks** [comment] 2020-02-12 18:41
@kaitlynbrown Check the npm status website https://status.npmjs.org/ they are having 404 error problems

**Comment by giovangonzalez** [comment] 2020-02-13 00:38
I can confirm this is still happening in Canada region.

**Comment by nicolacdnll** [comment] 2020-04-22 13:37
Happening in Europe right now.

**Comment by htd-tstepien** [comment] 2020-04-24 07:13
if it's an issue with some kind of your package (or your project/company), the issue can be with `NPM_TOKEN` check if it's the right one and it didn't change

**Comment by am-firnas** [comment] 2020-05-10 19:21
for me this issues when I perform building a Docker image, this bug got fixed by deleting **node-modules** and **`lock.yarn`** and `**lock.json`** files and then by following these steps in order to install yarn and build project using `yarn`.

1) `curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo`

2) `sudo rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg>`

3) `sudo rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg>`

4) `sudo yum install yarn`

and finally,

5) `yarn`
That process succeeded, but still I am unable to successfully create a Docker image.

**Comment by dhaileytaha** [comment] 2020-05-11 03:31
For MacOS specifically:
In your terminal
`yarn config set cafile <path-to-certificate.pem>` (that is : ~/.config/yarn/global)
and then `rm .yarnrc`

**Comment by hungvu193** [comment] 2020-06-11 09:04
> Running the below command in terminal fixed my issue:
> 
> yarn config set strict-ssl false

works like a charm

**Comment by ievgennaida** [comment] 2020-07-20 07:05
same problem 
error An unexpected error occurred: "https://registry.yarnpkg.com/grid-styled/-/grid-styled-4.1.0.tgz: unexpected end of file

**Comment by jamespottsSAFC** [comment] 2020-07-28 14:45
I seem to also be having this issue when I am using WSL. Also happens when I try to use npm too. When I switch to a repo in my Windows filesystem and run yarn install, it is ok.

**Comment by norainnoi** [comment] 2020-08-04 14:58
the error can be caused by a misnamed dependency in your package.json. i don't know why but it seems like both yarn and npm check all of your dependencies on every install.

**Comment by marcoValkyriweb** [comment] 2020-08-06 08:06
> PS C:\Projects\dakota> yarn outdated
yarn outdated v1.22.4
error An unexpected error occurred: "https://registry.yarnpkg.com/@bugsnag%2fjs: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Projects\\MyProject\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.

Going to go wipe my yarn lock file and node modules and report back. Normal yarn and yarn start work fine, just the audit messing up. This occurred after upgrading my vue-cli-plugin-mdb@2.0.4 to vue-cli-plugin-mdb@2.1.0.

**Comment by dbousamra** [comment] 2020-08-06 08:13
I'm getting this for the last 1hr. Anyone else?

**Comment by macrozone** [comment] 2020-08-06 08:14
> I'm getting this for the last 1hr. Anyone else?

me2

**Comment by shruti-ahuja** [comment] 2020-08-06 08:16
same here!

**Comment by marcoValkyriweb** [comment] 2020-08-06 08:17
https://www.npmjs.com/package/bugsnag
![image](https://user-images.githubusercontent.com/34270069/89508311-0aa45c80-d7ce-11ea-8a13-504f9ca08640.png)
I think the npm registry might be having issues?

**Comment by shruti-ahuja** [comment] 2020-08-06 08:19
How long would it take to fix this?

**Comment by Diyorbek** [comment] 2020-08-06 08:19
> I'm getting this for the last 1hr. Anyone else?

Same here

**Comment by macrozone** [comment] 2020-08-06 08:22
> How long would it take to fix this?

time to do a coffee break

**Comment by demkovych** [comment] 2020-08-06 08:22
the same

**Comment by Diyorbek** [comment] 2020-08-06 08:26
> https://www.npmjs.com/package/bugsnag
> ![image](https://user-images.githubusercontent.com/34270069/89508311-0aa45c80-d7ce-11ea-8a13-504f9ca08640.png)
> I think the npm registry might be having issues?

Agree. Something is going on with npm
https://www.npmjs.com/package/@mapbox/fusspot
<img width="1440" alt="Screen Shot 2020-08-06 at 10 25 31" src="https://user-images.githubusercontent.com/29589560/89509197-4ab80f00-d7cf-11ea-8d99-0f46718d9995.png">

**Comment by TomasBarry** [comment] 2020-08-06 08:42
We have had the same issue with `@vimeo/player` and have resolved the issue by updating that dependency to the latest version.

**Comment by anil-sequoia** [comment] 2020-08-06 08:44
Not able to install packages are scoped: https://www.npmjs.com/package/@simbathesailor/use-what-changed

**Comment by demkovych** [comment] 2020-08-06 08:46
keep calm. They working on it: https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282

**Comment by AnatoleLucet** [comment] 2020-08-06 09:14
At least this time the issue isn't full of memes :upside_down_face:

**Comment by Cebri63** [comment] 2020-08-06 09:18
Being a teacher and having this problem on the day of the students' technical test ... Bad day ! 😢

**Comment by KoenLippe** [comment] 2020-08-06 09:32
Glad I kept scrolling and found these last messages. Was about to flip my desk :smile:

**Comment by DanielCytiva** [comment] 2020-08-06 09:45
So it's coffee time :)

**Comment by Cebri63** [comment] 2020-08-06 09:48
[UPDATE]
https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282

**Comment by RabeeAbuBaker** [comment] 2020-08-06 09:48
I should've scrolled down long time ago!

**Comment by yosifeldman** [comment] 2020-08-06 10:03
Still happens even it says on that page "Update: The issue with the npm website was resolved...."

**Comment by dipeshkoirala21** [comment] 2020-08-06 10:08
i am getting this error too, i am trying to install react-native-image-crop-picker and  i am getting this error.
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@react-native-community/async-storage/-/async-storage-1.11.0.tgz: Request failed \"404 Not Found\"".

**Comment by justsolarry** [comment] 2020-08-06 10:08
Still no luck installing packages on my side.

**Comment by nvtin** [comment] 2020-08-06 10:09
Same for me now.

**Comment by hungvu193** [comment] 2020-08-06 10:10
Same for me now :(

**Comment by agoodea** [comment] 2020-08-06 10:10
I have the same problem with @react-native-community/<packages>

**Comment by from74** [comment] 2020-08-06 10:11
Oh, thank you that I am not alone. I already thought I was crazy...

**Comment by RabeeAbuBaker** [comment] 2020-08-06 10:11
Still facing the issue... Glad I kept a copy of my node_modules.

**Comment by ImadBoumzaoued** [comment] 2020-08-06 10:11
it's an npm issue https://status.npmjs.org/

**Comment by NabeelZanabeet** [comment] 2020-08-06 10:16
A smart ass argument why a developer shouldn't work many consecutive hrs 🙃

**Comment by VasylenckoSlava** [comment] 2020-08-06 10:23
It works!!

**Comment by pokidovea** [comment] 2020-08-06 10:28
[Update - Errors are decreasing while we re-populate a faulty cache. We are working to speed up that process to fully resolve the remaining issues quickly.](https://status.npmjs.org/)

**Comment by devsangwoo** [comment] 2020-08-06 10:36
how to fix it TT

**Comment by cyclops24** [comment] 2020-08-06 10:37
Never delete your `node_modules` folder :man_facepalming: :man_facepalming:

**Comment by einnor** [comment] 2020-08-06 10:38
They are working on it. This is their update a few minutes ago: https://twitter.com/npmstatus/status/1291318846205210624

**Comment by saadelsabahy** [comment] 2020-08-06 10:48
Couldn't find package "@typescript-eslint/eslint-plugin@^1.5.0" required by "@react-native-community/eslint-config@^0.0.7" on the "npm" registry

**Comment by osamaeshtiaq** [comment] 2020-08-06 10:51
I am getting similar type of error while building a docker image. I have literally tried everything, but still it shows:
`Sending build context to Docker daemon  258.8MB
Step 1/6 : FROM mhart/alpine-node
 ---> 5e6dbbca4cab
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> 480d384dc9f0
Step 3/6 : COPY /build .
 ---> Using cache
 ---> 7ef150a69ac5
Step 4/6 : COPY /buildenv .
 ---> Using cache
 ---> 2ce3c6384603
Step 5/6 : RUN yarn
 ---> Running in 3acf4706c177
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@zeit/schemas/-/schemas-2.6.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1`

**Comment by osamaeshtiaq** [comment] 2020-08-06 10:52
I am getting similar type of error while building a docker image. I have literally tried everything, but still it shows:
```
Sending build context to Docker daemon  258.8MB
Step 1/6 : FROM mhart/alpine-node
 ---> 5e6dbbca4cab
Step 2/6 : WORKDIR /app
 ---> Using cache
 ---> 480d384dc9f0
Step 3/6 : COPY /build .
 ---> Using cache
 ---> 7ef150a69ac5
Step 4/6 : COPY /buildenv .
 ---> Using cache
 ---> 2ce3c6384603
Step 5/6 : RUN yarn
 ---> Running in 3acf4706c177
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@zeit/schemas/-/schemas-2.6.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1
```

**Comment by janakg** [comment] 2020-08-06 10:53
npm === software && npm.registry.status === 'down'

**Comment by nero2009** [comment] 2020-08-06 10:53
+1 having the same problem

**Comment by conradjonp** [comment] 2020-08-06 10:59
> Never delete your `node_modules` folder 🤦‍♂️ 🤦‍♂️

I did this now I'm stuck. I guess I end my work today.

**Comment by ollydixon** [comment] 2020-08-06 11:00
@einnor all 31 projects across are company are now failing. This has really shaken our confidence in Google Cloud for future projects. We some production level apps with requests now failing; terrible.

**Comment by gulaandrij** [comment] 2020-08-06 11:01
https://status.npmjs.org/

**Comment by osamaeshtiaq** [comment] 2020-08-06 11:01
> > Never delete your `node_modules` folder 🤦‍♂️ 🤦‍♂️
> 
> I did this now I'm stuck. I guess I end my work today.

If you have repo for your project, clone it and run yarn install. Your project will still work locally

**Comment by Obsiye** [comment] 2020-08-06 11:01
I'm having this issue 
"https://registry.yarnpkg.com/@tokenizer/token/-/token-0.1.1.tgz: Request failed \"404 Not Found

I tried: removing yarn.lock and upgrading but it doesn't work.

I run curl  https://registry.yarnpkg.com/@tokenizer/token/-/token-0.1.1.tgz  in the command line and it sometimes works but mostly fails with the 404 not found

**Comment by cis-zeeshan** [comment] 2020-08-06 11:02
Guys, Its still working after 'npm login' until they are fixing.

**Comment by LCostaN** [comment] 2020-08-06 11:03
![image](https://user-images.githubusercontent.com/33222832/89524647-9974a180-d7ed-11ea-9035-4fa6837b0074.png)

**Comment by losewayman** [comment] 2020-08-06 11:06
Request failed \"404 Not Found\""
下午4点左右试了各种方法都不行

**Comment by mehaknasir** [comment] 2020-08-06 11:07
[91merror An unexpected error occurred: "https://registry.yarnpkg.com/@zeit/next-css/-/next-css-1.0.1.tgz: Request failed \"404 Not Found\"".
[0minfo If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command

**Comment by osamaeshtiaq** [comment] 2020-08-06 11:08
> �[91merror An unexpected error occurred: "https://registry.yarnpkg.com/@zeit/next-css/-/next-css-1.0.1.tgz: Request failed "404 Not Found"".
> �[0minfo If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command

I'm getting the same error

**Comment by osamaeshtiaq** [comment] 2020-08-06 11:09
![screencapture-twitter-npmstatus-status-1291318846205210624-2020-08-06-15_46_51](https://user-images.githubusercontent.com/33973766/89525104-21af7280-d7ff-11ea-874c-179d4495e19e.png)

**Comment by CechTech** [comment] 2020-08-06 11:12
![image](https://user-images.githubusercontent.com/21101177/89525378-5f53d180-d7e6-11ea-9714-0661ab99e0ac.png)

**Comment by ilKhr** [comment] 2020-08-06 11:16
I want write code
But npm thinks differently

**Comment by kamranblueeast** [comment] 2020-08-06 11:17
facing same issue...
yarn install v1.19.1
[1/4] Resolving packages...
error Couldn't find package "@sendgrid/mail@7.2.2" required by "@anchan828/nest-sendgrid@^0.3.8" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by Vadi** [comment] 2020-08-06 11:18
`rm -rf ~/.yarn` did the magic for me.

**Comment by bipindubey-technoark** [comment] 2020-08-06 11:20
> `rm -rf ~/.yarn` did the magic for me.

Is it safe to run this command??

**Comment by CechTech** [comment] 2020-08-06 11:22
> > `rm -rf ~/.yarn` did the magic for me.
> 
> Is it safe to run this command??

I have only ~/.yarnrc on OS X.

**Comment by Hayk-Zohrabyan** [comment] 2020-08-06 11:22
@Vadi this does not solve the problem. please check carefully ))

**Comment by bipindubey-technoark** [comment] 2020-08-06 11:23
Please guys give solution to this as soon as possible

**Comment by kamranblueeast** [comment] 2020-08-06 11:23
@Vadi I tried but issue is still there.

**Comment by obiwanken0bi** [comment] 2020-08-06 11:24
> > `rm -rf ~/.yarn` did the magic for me.
> 
> Is it safe to run this command??

![try_it](https://user-images.githubusercontent.com/38909547/89526439-48f24980-d7d7-11ea-8a2e-961223eebf41.png)

**Comment by ilKhr** [comment] 2020-08-06 11:25
![image](https://user-images.githubusercontent.com/58560537/89526584-a646c480-d7f0-11ea-8d68-12601c469c00.png)

**Comment by rodilo** [comment] 2020-08-06 11:25
> Never delete your `node_modules` folder 🤦‍♂️ 🤦‍♂️

Never delete your yarn cache 🤦‍♂️

**Comment by cleitonper** [comment] 2020-08-06 11:26
> `rm -rf ~/.yarn` did the magic for me.

guys, it only remove `yarn` binary. it's not a solution.

**Comment by frogThanos** [comment] 2020-08-06 11:28
<img src="https://media.giphy.com/media/Zd1BUb0qs6nwjeMUBu/giphy.gif" width="480" height="360" />

**Comment by northout-muzammil** [comment] 2020-08-06 11:28
```
Yarn version: 
  1.22.4

Node version: 
  10.16.3

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@react-native-firebase/app-types/-/app-types-6.7.2.tgz: Request failed "503 Service Unavailable"
      at ResponseError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:696:66)
      at new ResponseError (/usr/local/lib/node_modules/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:67057:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/usr/local/lib/node_modules/yarn/lib/cli.js:141625:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:198:13)
```

Anyone any luck ?

**Comment by Cebri63** [comment] 2020-08-06 11:30
Unless we work at NPM, we just have to wait...

**Comment by alubeck** [comment] 2020-08-06 11:31
`npx react-native init ILoveNPM` is now working ... 👏    (installing all dependencies via NPM and so on)

**Comment by justsolarry** [comment] 2020-08-06 11:32
All working :D

**Comment by Hayk-Zohrabyan** [comment] 2020-08-06 11:34
Really :D

**Comment by anil-sequoia** [comment] 2020-08-06 11:35
Not working

**Comment by RabeeAbuBaker** [comment] 2020-08-06 11:35
After breaking the build on production level... it's back working now

**Comment by bipindubey-technoark** [comment] 2020-08-06 11:35
Any solution using yarn???

**Comment by RabeeAbuBaker** [comment] 2020-08-06 11:39
Another update:

> Update - We replaced the faulty cache and our telemetry indicates a significant improvement in error rates. We'll continue to monitor the situation and make sure all issues are fully resolved.
> Aug 6, 11:36 UTC

[NPM Status](https://status.npmjs.org/)

**Comment by bipindubey-technoark** [comment] 2020-08-06 11:39
Its working now Thanks

**Comment by LevanSanadiradze** [comment] 2020-08-06 11:39
It worked for me, even though the npm status page still shows partial outage.

**Comment by khurram-wasim** [comment] 2020-08-06 11:40
<img width="174" alt="Screenshot 2020-08-06 at 16 39 44" src="https://user-images.githubusercontent.com/20108204/89527876-84a30880-d803-11ea-9067-532253765fff.png">
A sight of relief !

**Comment by anthonyminyungi** [comment] 2020-08-06 11:41
![스크린샷 2020-08-06 오후 8 40 50](https://user-images.githubusercontent.com/14817195/89527929-1ff8a580-d825-11ea-8995-0064a1d959e1.png)

**Comment by RabeeAbuBaker** [comment] 2020-08-06 11:41
![image](https://user-images.githubusercontent.com/14871906/89527938-ddb67080-d7f2-11ea-9ea3-1ebae7f0e2ab.png)
🎉🎉🎉🎉

**Comment by shinjiber** [comment] 2020-08-06 11:42
thank you npm always

**Comment by shubhamsapra97** [comment] 2020-08-06 11:54
y'all, get back to work now 😄

**Comment by osamaeshtiaq** [comment] 2020-08-06 12:14
Working fine now!

**Comment by nvtin** [comment] 2020-08-06 12:34
Working now.

**Comment by kamranblueeast** [comment] 2020-08-06 12:46
Working now...:)

**Comment by minhhy2801** [comment] 2020-08-07 02:41
```
Yarn version: 
  1.22.4

Node version: 
  12.16.2

Platform: 
  win32 x64

Trace: 
  Error: https://registry.npmjs.org/@material-ui%2fcore/i18next: Request "https://registry.npmjs.org/@material-ui%2fcore/i18next" returned a 405
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\cli.js:66105:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\lib\cli.js:140748:22)
      at Request.emit (events.js:310:20)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141720:10)
      at Request.emit (events.js:310:20)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:141642:12)
      at Object.onceWrapper (events.js:416:28)
      at IncomingMessage.emit (events.js:322:22)
      at endReadableNT (_stream_readable.js:1187:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
Still happens with me

**Comment by wadamomo** [comment] 2020-08-15 01:15
`yarn config set registry https://registry.npmjs.org
rm yarn.lock
yarn`

worked for me

**Comment by Pintot** [comment] 2020-08-16 18:27
Had the same issue here, and working none of the solutions! My goshi

**Comment by Pintot** [comment] 2020-08-16 18:30
Is not working guys!

$ yarn add react-route-dom
yarn add v1.22.4
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/react-route-dom: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\wamp64\\www\\myapp\\y
arn-error.log".

**Comment by yael-screenovate** [comment] 2020-08-23 19:13
same issue by me:(
error An unexpected error occurred: "https://registry.yarnpkg.com/jspfd: Not found".
nothing from above helped.

**Comment by GitHubAjit** [comment] 2020-09-06 08:07
run 
`yarn config set registry https://registry.npmjs.org
`
will do the job

**Comment by andreapiras** [comment] 2020-09-15 14:30
I was using my phone as hotspot. Restarting the phone fixed the issue 🤷

**Comment by pak11273** [comment] 2020-09-22 15:13
> run
> `yarn config set registry https://registry.npmjs.org `
> will do the job

Doesn't work for me

**Comment by mayooresan** [comment] 2020-09-28 02:18
If you are inside an intranet, check which registry you are connecting to. You may have been blocked from the npmjs.org registry.

**Comment by fabiosleal** [comment] 2020-10-30 21:55
> $ yarn global add @nrwl/schematics
> yarn global v1.7.0
> [1/4] Resolving packages...
> error An unexpected error occurred: "https://https://registry.yarnpkg.com/@nrwl/schematics: Not found".

More info:
This error happen not only in macOS, but in Linux (Ubuntu, CentOS) too.

In my case, this error was related to some misfunction in docker, probably after some change on iptables rules.

After restart docker service, everything works fine for me.
`$ sudo systemctl restart docker`

**Comment by psoniat** [comment] 2020-12-07 14:11
yarn config set "strict-ssl" false -g Worked for me

**Comment by alihassan143** [comment] 2021-01-16 06:07
yarn global v1.22.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/strapi: error:0909006C:PEM routines:get_name:no start line".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\aliha\\AppData\\Local\\Yarn\\Data\\global\\info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by merceyz** [comment] 2021-01-16 12:13
Closing as there is nothing actionable for us to do here

**Closed by merceyz** 2021-01-16 12:13 UTC
Labels: triaged

**Comment by fast-and-curious-1910** [comment] 2021-01-19 13:00
I got the same error. 

Error:
```
PS E:\Coding Projects\BLUEIT\blueit> yarn add -D @types/node typescript nodemon ts-node
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.npmjs.org/typescript/-/typescript-4.1.3.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "E:\\Coding Projects\\BLUEIT\\blueit\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Node Version: ``14.15.2``
Yarn Version: ``1.22.5``
Platform: ``Windows 10``

**Comment by birthdaycorp** [comment] 2021-02-16 05:43
> Never delete your `node_modules` folder 🤦‍♂️ 🤦‍♂️

yeah i saw that suggestion and i was like UM NO☠️☠️

**Comment by dadoadk** [comment] 2021-03-10 15:01
This worked for me:
`yarn config set strict-ssl false`

**Comment by hitfm00** [comment] 2021-05-13 17:16
> run
> `yarn config set registry https://registry.npmjs.org `
> will do the job

work for me!
