### ISSUE TITLE
node-gyp bug - yarn, as included in official docker node image, fails to install get-cursor-position

### ISSUE THREAD

**Issue by mattkime** [yarnpkg/yarn#2828] opened 2017-03-02 20:57 UTC
https://github.com/mattkime/get-cursor-position-fail/

Running `docker build .` from the repo directory results in -
```
[4/4] Building fresh packages...
error /home/mup/node_modules/get-cursor-position: Command failed.
Exit code: 127
Command: sh
Arguments: -c node-gyp rebuild
Directory: /home/mup/node_modules/get-cursor-position
Output:
sh: 1: node-gyp: not found
```

Modify Dockerfile to use npm instead and it works fine.

**Please mention your node.js, yarn and operating system version.**

The official docker images, verified in both v7.6 and v7.7.1. Both use yarn v0.21.3

**Comment by valeryq** [comment] 2017-03-03 12:39
I have the same bug.
```

**Comment by Daniel15** [comment] 2017-03-04 21:10
Duplicate of #2266. A workaround for now is to run `yarn global add node-gyp` to your Docker image.

**Closed by Daniel15** 2017-03-04 21:10 UTC

**Comment by houssem-yahiaoui** [comment] 2017-06-21 12:24
Even though sometimes this approach won't going to fully work, i've tested the solution over yarn 0.24.6 my solution was to replace **bcrypt** for **bcryptjs** same package, same methods and behaviour last one is more js compatible without any dependencies, and it works flawlessly over **docker** !

Hope this helps people with same issue.

**Comment by NeoLegends** [comment] 2017-11-22 21:43
> my solution was to replace bcrypt for bcryptjs same package, same methods and behaviour 
This is often not desirable as the version using native code can use dedicated threads to calculate the bcrypt hash whereas the JS version cannot.
