### ISSUE TITLE
Download link is invalid

### ISSUE THREAD

**Issue by mallycrip** [yarnpkg/yarn#8774] opened 2022-01-19 11:47 UTC
I tried to download it from the official website, but the link was broken.
![image](https://user-images.githubusercontent.com/44916755/150123056-52d14b4a-dfeb-41e6-830a-63a4e90ccb41.png)

I think the problem is that the link is redirected [here](https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn-1.22.17.msi), but this version does not support msi extensions.

I hope it will be resolved

**Comment by merceyz** [comment] 2022-01-19 13:58
Duplicate of https://github.com/yarnpkg/yarn/issues/8766

**Closed by merceyz** 2022-01-19 13:58 UTC
