### ISSUE TITLE
JavaScript Heap out of Memory on all Yarn commands

### ISSUE THREAD

**Issue by jmeberst** [yarnpkg/yarn#4239] opened 2017-08-23 14:02 UTC
Yarn version 0.27.5
node version 6.10.2

After installing the happypack package from an offline repository, all yarn commands (including yarn help) except for
yarn --version
result in JavaScript heap out of memory.

I've tried uninstalling and reinstalling both yarn and node.js. Increasing the memory limit just extends the amount of time to hit the error.

> 46156 ms: Mark-sweep 1388.9 (1434.2) -> 1388.9 (1434.2) MB, 1367.0 / 0.0 ms [
allocation failure] [GC in old space requested].
   47582 ms: Mark-sweep 1388.9 (1434.2) -> 1390.0 (1418.2) MB, 1426.5 / 0.0 ms [
last resort gc].
   49009 ms: Mark-sweep 1390.0 (1418.2) -> 1391.1 (1418.2) MB, 1427.0 / 0.0 ms [
last resort gc].
JS stacktrace 
==== JS stack trace =========================================
2: arguments adaptor frame: 1->2
Security context: 0000034721DCFB49 <JS Object>
    3: insert(aka insert) [timers.js:135] [pc=00000161ADC3D869] (this=0000034721
D04381 <undefined>,item=000000AE8ED55C11 <a Timeout with map 0000002073C81D49>,u
nrefed=0000034721D04271 <false>)
    4: /* anonymous */(aka /* anonymous */) [timers.js:104] [pc=00000161ADC3D3A1
] (this=0000034721D04381 <undefined>,item=000000AE8ED55C11 <a Timeout with map 0
00000...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memo
ry <---

**Comment by BYK** [comment] 2017-09-22 16:04
Is this still happening to you?

**Comment by jmeberst** [comment] 2017-09-22 16:20
Yes, I was able to get it to stop at some point by uninstalling everything, but once I started using yarn on my current project one of the modules made it start again. I'm not positive that it's happypack though.

**Comment by BYK** [comment] 2017-09-26 11:24
@jmeberst the best way to deal with this is to post a minimal reproduction case here so someone can investigate. Alternatively, you can investigate it yourself and submit a PR. LMK if you are interested in any of those.

**Comment by mrbarletta** [comment] 2017-11-14 20:09
I had the same issue, a regular react app . To be honest I don't know if it will happen again, I did yarn start 3 days ago and it just happened. Leaving the trace in case there is something usefull. thanks
```
Compiling...

<--- Last few GCs --->

136744844 ms: Mark-sweep 1378.3 (1434.7) -> 1363.1 (1434.7) MB, 247.2 / 0.0 ms [allocation failure] [GC in old space requested].
136745117 ms: Mark-sweep 1363.1 (1434.7) -> 1362.6 (1434.7) MB, 272.8 / 0.0 ms [allocation failure] [GC in old space requested].
136745398 ms: Mark-sweep 1362.6 (1434.7) -> 1363.3 (1402.7) MB, 281.7 / 0.0 ms [last resort gc].
136745718 ms: Mark-sweep 1363.3 (1402.7) -> 1363.1 (1402.7) MB, 319.3 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a7a80fcfb51 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=0x351630273fc2] (this=0x1a7a80f04381 <undefined>,w=0x3f5ef92fd0b1 <JS Array[2]>,x=2,N=0x1a7a80f043c1 <true>,J=0x1a7a80f04411 <String[0]: >,I=0x1a7a80fb46e1 <JS Function ConvertToString (SharedFunctionInfo 0x1a7a80f52dc9)>)
    2: Join(aka Join) [native array.js:180] [pc=0x351630d55552] (this=0x1a7a80f04381 <undefined>,w=0x3f5ef92fd0b1 <JS Arr...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x109624c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0x35161f6092a7
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by shuvigoss** [comment] 2018-10-31 06:32
> I had the same issue, a regular react app . To be honest I don't know if it will happen again, I did yarn start 3 days ago and it just happened. Leaving the trace in case there is something usefull. thanks
> 
> ```
> Compiling...
> 
> <--- Last few GCs --->
> 
> 136744844 ms: Mark-sweep 1378.3 (1434.7) -> 1363.1 (1434.7) MB, 247.2 / 0.0 ms [allocation failure] [GC in old space requested].
> 136745117 ms: Mark-sweep 1363.1 (1434.7) -> 1362.6 (1434.7) MB, 272.8 / 0.0 ms [allocation failure] [GC in old space requested].
> 136745398 ms: Mark-sweep 1362.6 (1434.7) -> 1363.3 (1402.7) MB, 281.7 / 0.0 ms [last resort gc].
> 136745718 ms: Mark-sweep 1363.3 (1402.7) -> 1363.1 (1402.7) MB, 319.3 / 0.0 ms [last resort gc].
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x1a7a80fcfb51 <JS Object>
>     1: DoJoin(aka DoJoin) [native array.js:~129] [pc=0x351630273fc2] (this=0x1a7a80f04381 <undefined>,w=0x3f5ef92fd0b1 <JS Array[2]>,x=2,N=0x1a7a80f043c1 <true>,J=0x1a7a80f04411 <String[0]: >,I=0x1a7a80fb46e1 <JS Function ConvertToString (SharedFunctionInfo 0x1a7a80f52dc9)>)
>     2: Join(aka Join) [native array.js:180] [pc=0x351630d55552] (this=0x1a7a80f04381 <undefined>,w=0x3f5ef92fd0b1 <JS Arr...
> 
> FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
>  1: node::Abort() [node]
>  2: 0x109624c [node]
>  3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
>  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
>  5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [node]
>  6: v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [node]
>  7: 0x35161f6092a7
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

u can use "NODE_OPTIONS=--max_old_space_size=4096 DEBUG=v8:* npm run dev:pwa" to run npm

**Comment by mdeknowis** [comment] 2020-07-21 07:23
```txt
[4/5] Linking dependencies...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Writing Node.js report to file: report.20200720.140543.10.0.001.json
<--- Last few GCs --->
[10:0x55582cc19ba0]    27744 ms: Mark-sweep 2050.4 (2068.2) -> 2048.9 (2060.0) MB, 1540.6 / 0.0 ms  (+ 477.1 ms in 128 steps since start of marking, biggest step 11.7 ms, walltime since start of marking 2044 ms) (average mu = 0.106, current mu = 0.022) al[10:0x55582cc19ba0]    30470 ms: Mark-sweep 2052.4 (2060.5) -> 2051.1 (2061.7) MB, 2486.6 / 0.0 ms  (+ 228.3 ms in 53 steps since start of marking, biggest step 16.3 ms, walltime since start of marking 2726 ms) (average mu = 0.046, current mu = 0.004) all
<--- JS stacktrace --->
==== JS stack trace =========================================
    0: ExitFrame [pc: 0x55582b1e5d19]
Security context: 0x06864f6008d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [0x301a6b15d681] [/opt/yarn-v1.22.4/lib/cli.js:~1024] [pc=0x143c27946203](this=0x1c33bbec04b1 <undefined>)
    2: next [0x6864f623139](this=0x1d71d8ec4479 <JSGenerator>,0x20f0d21756f9 <String[168]: /project/node_modules/@svgr/webpack/node_modules/@babel/plugin-proposal-dynamic-import/node_module...
Node.js report completed
Aborted (core dumped)
```

Also 10 GB does not solve that issue.

**Comment by merceyz** [comment] 2021-01-04 01:33
Closing as I can't reproduce this

**Closed by merceyz** 2021-01-04 01:33 UTC

**Comment by ianks** [comment] 2021-01-21 00:31
Same issue here. Happens in `PackageHoister` for me:

```
<--- Last few GCs --->
start of marking 911 ms) (average mu = 0.160, current mu = 0.027) alloca[454868:0x40b3bd0]    60791 ms: Mark-sweep 2039.6 (2053.0) -> 2036.4 (2053.0) MB, 338.6 / 0.0 ms  (+ 331.6 ms in 72 steps since start of marking, biggest step 8.5 ms, walltime since start of marking 692 ms) (average mu = 0.104, current mu = 0.031) allocat[454868:0x40b3bd0]    61755 ms: Mark-sweep 2040.0 (2053.0) -> 2036.7 (2052.0) MB, 954.4 / 0.0 ms  (average mu = 0.053, current mu = 0.010) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13c5b79]
    1: StubFrame [pc: 0x13714d1]
Security context: 0x319115e408d1 <JSObject>
    2: slice [0x319115e4ebc1](this=0x3aa5bb79cfb1 <JSArray[27]>,0,1)
    3: declareRename [0xd25b85e4621] [/home/ianks/.asdf/installs/yarn/1.22.5/lib/cli.js:~94556] [pc=0x161f994fe189](this=0x017fd1b41909 <PackageHoister map = 0x2b9542b25879>,0x3aa5bb79a201 <HoistManifest map = 0x2b9542b0a1b9>,0x3aa5bb79a031 <JSArray[28]>,0x3aa5bb...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210120.193024.454868.0.001.json
Node.js report completed
 1: 0xa09830 node::Abort() [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 2: 0xa09c55 node::OnFatalError(char const*, char const*) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 3: 0xb7d71e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 4: 0xb7da99 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 5: 0xd2a1f5  [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 6: 0xd2a886 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 7: 0xd37105 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 8: 0xd37fb5 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
 9: 0xd3aa6c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
10: 0xd0163b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
11: 0x104300e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
12: 0x13c5b79  [/home/ianks/.asdf/installs/nodejs/12.16.3/bin/node]
[2]    454868 abort (core dumped)  yarn
```
@merceyz

**Comment by ZeldOcarina** [comment] 2022-10-10 15:26
Same here

**Comment by radiorz** [comment] 2025-05-24 14:14
Same in 2025
