### ISSUE TITLE
global remove my-package & global add my-package, new files of new version will not added.

### ISSUE THREAD

**Issue by hugojing** [yarnpkg/yarn#2925] opened 2017-03-15 09:04 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After I publish new version of my package, 

I run `yarn global remove my-package` and `yarn global add my-package`.

Install successfully, package content changed.

But some new files are NOT added!

Only changed, no added.

Finally I used `npm i -g my-package`, resolved.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Publish your test package & install this package globally.
2. Added new file & publish new version of this package.
3. `yarn global remove test-package` & `yarn global add test-package`.
4. `ls ~/.yarn-config/global/node_modules/test-package` & and watch if changed.

**What is the expected behavior?**

New files added.

**Please mention your node.js, yarn and operating system version.**

node.js v7.0.0

yarn v0.16.1

OSX 10.11.3

**Comment by arcanis** [comment] 2017-04-28 17:26
Can you please write a repro test script? It would help us :)

**Comment by rally25rs** [comment] 2017-12-28 04:15
Closing due to lack of confirmation and old Yarn version. If you can reproduce this on Yarn v1.3 please let us know and we can reopen it.

**Closed by rally25rs** 2017-12-28 04:15 UTC
Labels: needs-confirmation, triaged
