### ISSUE TITLE
ubuntu emoji support has bug ?

### ISSUE THREAD

**Issue by ifzm** [yarnpkg/yarn#3464] opened 2017-05-21 10:31 UTC
![2017-05-21 18-18-41](https://cloud.githubusercontent.com/assets/12740295/26283101/bfee534c-3e53-11e7-8a0d-04798b2d493c.png)
OS：Ubuntu 16.04

**Comment by rally25rs** [comment] 2017-05-22 13:10
Duplicate of #3399

**Comment by bestander** [comment] 2017-05-23 12:34
Emoji is enabled on mac by default, on other systems you can enable it with `--emoji` flag

**Closed by bestander** 2017-05-23 12:34 UTC

**Comment by ifzm** [comment] 2017-05-23 13:48
@bestander  I used the order, still no effect, did you read my screenshot?
 Is this feasible `yarn --emoji`?

**Comment by bestander** [comment] 2017-05-23 14:01
Sorry, this was added just in https://github.com/yarnpkg/yarn/commit/10b82bb063c2e2feee669ddb9dfaf4126b74c7a7.
It will be released in 0.26

**Comment by ifzm** [comment] 2017-05-23 14:06
@bestander  Oh! I am looking forward.  thank you :D

**Comment by rizvified** [comment] 2017-09-08 07:42
@bestander but we'll have to put the '--emoji' flag everytime right? Is there a way to enable it permanently?

**Comment by bestander** [comment] 2017-09-08 16:15
Yes, you can put CLI args into .yarnrc file and it will be added to all
commands automatically: https://yarnpkg.com/en/docs/yarnrc#toc-cli-arguments
