### ISSUE TITLE
"Unmet peer dependency" with peer dependency already installed as transitive dep

### ISSUE THREAD

**Issue by guigrpa** [yarnpkg/yarn#2688] opened 2017-02-13 07:27 UTC
Bug

**What is the current behavior?**

1. Install dependency **A** (with transitive dependency **AB**)
2. **Later** (contrary to #2132), install dependency **C** (with has **AB** as peer dep) -- an *unmet peer dependency* warning appears, even though **AB** was installed in the first step.

**Repro**

**Step 1** output (notice that `storyboard-core` is installed as a normal dependency of `storyboard`):

```sh
$ yarn init -y
$ yarn add storyboard@3.0.0-rc.1
yarn add v0.19.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 13 new dependencies.
...
├─ storyboard-core@3.0.0-rc.0
├─ storyboard@3.0.0-rc.1
...
Done in 4.25s.
```

**Step 2** output (with `storyboard-core` in its `peerDependencies`; notice the warning):

```sh
>yarn add storyboard-listener-console@3.0.0-rc.1
yarn add v0.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "storyboard-listener-console@3.0.0-rc.1" has unmet peer dependency "storyboard-core@^3.0.0-rc.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ storyboard-listener-console@3.0.0-rc.1
Done in 1.36s.
```

Despite the warning, the installation is successful. Also note that no peer-dep warning appears with `npm install`.

**What is the expected behavior?** No warning, since the peer dependency is already installed (with exactly the required version).

**Please mention your node.js, yarn and operating system version.**

Node v7.3.0
yarn v0.19.1
Windows 7 (also observed in OS X Sierra)

**Comment by CrabDude** [comment] 2017-07-13 20:33
Still seeing in `yarn@0.28.1`:

```
// empty directory
$ yarn add webpack@3
```

**Comment by BYK** [comment] 2017-09-15 23:32
@guigrpa your issue seems to be fixed on latest master.
@CrabDude your issue seems to be fixed with #4478.

**Closed** 2017-09-16 10:16 UTC

**Comment by javonclarke** [comment] 2017-09-17 00:13
@BYK I updated yarn based and the still persists for me when installing `create-react-app` globally.

```
~|⇒ yarn global add  create-react-app
yarn global v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "graphcool-styles@0.1.42" has incorrect peer dependency "react@^0.15.0".
warning "graphiql@0.11.3" has incorrect peer dependency "graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0".
warning "graphiql@0.11.3" has incorrect peer dependency "prop-types@>=15.5.0".
warning "graphiql@0.11.3" has incorrect peer dependency "react@^15.6.0".
warning "graphiql@0.11.3" has incorrect peer dependency "react-dom@^15.6.0".
warning "react-dom@15.6.1" has incorrect peer dependency "react@^15.6.1".
warning "react-modal@1.9.7" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-modal@1.9.7" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "react-redux@5.0.6" has incorrect peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
warning "react-redux@5.0.6" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
warning "react-transition-group@1.2.0" has incorrect peer dependency "react@^15.0.0".
warning "react-transition-group@1.2.0" has incorrect peer dependency "react-dom@^15.0.0".
warning "react-virtualized@8.11.4" has incorrect peer dependency "react@^0.14.0 || ^15.0.0".
warning "react-virtualized@8.11.4" has incorrect peer dependency "react-addons-shallow-compare@^0.14.0 || ^15.0.0".
warning "react-virtualized@8.11.4" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning "svgo-loader@1.2.1" has unmet peer dependency "svgo@>=0.4.0".
warning "html-webpack-plugin@2.30.1" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc || ^3".
warning "webpack-dev-server@1.16.5" has unmet peer dependency "webpack@>=1.3.0 <3".
warning "codemirror-graphql@0.6.11" has incorrect peer dependency "codemirror@^5.26.0".
warning "codemirror-graphql@0.6.11" has incorrect peer dependency "graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.8.0 || ^0.9.0 || ^0.10.0".
warning "graphql-subscriptions@0.4.4" has incorrect peer dependency "graphql@^0.7.0 || ^0.8.0 || ^0.9.0 || ^0.10.1".
warning "graphql-tag@2.4.2" has incorrect peer dependency "graphql@^0.9.0 || ^0.10.0".
warning "webpack-dev-middleware@1.12.0" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
[4/4] 📃  Building fresh packages...
success Installed "create-react-app@1.4.0" with binaries:
      - create-react-app
✨  Done in 5.32s.
```

Any help would be appreciated.

**Comment by BYK** [comment] 2017-09-17 00:25
@javonclarke this issue is not fixed in 1.0.2, only on nightlies right now: https://yarnpkg.com/en/docs/nightly

**Comment by javonclarke** [comment] 2017-09-17 00:27
@BYK Ah thank you.

**Comment by guigrpa** [comment] 2017-09-18 09:55
@BYK Thanks for the effort!

**Comment by Hypnosphi** [comment] 2017-11-16 16:39
I can reproduce the issue using OP's instructions in `1.3.2`:
```
warning " > storyboard-listener-console@3.0.0-rc.1" has unmet peer dependency "storyboard-core@^3.0.0-rc.0".
```

**Comment by greggb** [comment] 2017-11-17 16:14
Is there anything I can do to help with a repro case? The [Storybook issue](https://github.com/storybooks/storybook/issues/2303) is pretty much exactly what I'm seeing in my project as well on the latest release.

**Comment by BYK** [comment] 2017-11-20 12:11
@Hypnosphi @greggb I think this is a separate issue. Sounds a bit like #4850 so feel free to comment there and follow it.

**Comment by Hypnosphi** [comment] 2017-11-20 12:26
@BYK Do yo mean the one in storybook? Yeah, probably. But note that this one is also reproduceable right now

**Comment by BYK** [comment] 2017-11-20 14:16
@Hypnosphi commenting under a closed issue won't get us any visibility, that's why I'm promoting an already open issue which seems like what you are reporting here :)

**Comment by Hypnosphi** [comment] 2017-11-20 14:23
> commenting under a closed issue won't get us any visibility

Should I rather open a new one instead? I just followed instructions from  https://github.com/yarnpkg/yarn/issues/2688#issue-207140699 and got the same failure as OP

**Comment by BYK** [comment] 2017-11-20 14:25
@Hypnosphi yes, with a repro repo so we can reproduce locally without any other context of information and then fix it.

**Comment by greggb** [comment] 2017-11-20 14:44
Thanks BYK
