### ISSUE TITLE
yarn --pnp fails to install node-sass because of missing mkdirp

### ISSUE THREAD

**Issue by tbassetto** [yarnpkg/yarn#6613] opened 2018-11-01 07:35 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Trying to use PnP on a repo already using yarn and workspaces. It fails because of sass and mkdipr:
```
yarn --pnp
yarn install v1.12.1
[1/5] 🔍  Resolving packages...
[2/5] 🚚  Fetching packages...
[3/5] 🔗  Linking dependencies...
warning " > babel-loader@7.1.5" has unmet peer dependency "babel-core@6".
warning " > babel-loader@7.1.5" has unmet peer dependency "webpack@2 || 3 || 4".
warning "workspace-aggregator-24aceb9d-ff70-4cde-91dd-fbde71f45ea7 > [REDACTED_NAME]> redux-devtools@3.4.1" has incorrect peer dependency "redux@^3.5.2".
warning "workspace-aggregator-24aceb9d-ff70-4cde-91dd-fbde71f45ea7 > [REDACTED_NAME] > connected-react-router@4.5.0" has unmet peer dependency "react-router@^4.3.1".
[5/5] 📃  Building fresh packages...
[1/4] ⡀ fsevents
[2/4] ⡀ node-sass
[3/4] ⡀ dtrace-provider
error [REDACTED_ABSOLUTE_PATH]/js/.pnp/unplugged/npm-node-sass-4.9.2-5e63fe6bd0f2ae3ac9d6c14ede8620e2b8bdb437/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: [REDACTED_ABSOLUTE_PATH]/js/.pnp/unplugged/npm-node-sass-4.9.2-5e63fe6bd0f2ae3ac9d6c14ede8620e2b8bdb437/node_modules/node-sass
Output:
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> ([REDACTED_ABSOLUTE_PATH]/js/.pnp/unplugged/npm-node-sass-4.9.2-5e63fe6bd0f2ae3ac9d6c14ede8620e2b8bdb437/node_modules/node-sass/scripts/install.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
It's unclear to me who is at fault, yarn --pnp, node-sass or mkdirp.

**What is the expected behavior?**
yarn pnp set up correctly for the root repo and all its workspaces.

**Please mention your node.js, yarn and operating system version.**
* Node.js LTS v10.13.0
* yarn 1.12.1
* macOS 10.14

**Comment by marvinhagemeister** [comment] 2018-11-02 12:41
Can confirm. Sometimes a second run will succeed the installation process, but I haven't found why that's the case.

**Comment by rally25rs** [comment] 2018-11-05 13:02
ping @arcanis ?

**Comment by arcanis** [comment] 2018-11-05 13:16
Thanks! Duplicate of #6626 - will be fixed with #6629, currently pending review 👍

**Comment by vielhuber** [comment] 2018-11-15 22:59
Just wanted to add when using yarn 1.13.0 with windows WSL using browserify with babelify:
Error: Cannot find module 'babelify'

This should be the same error, am I right?

**Comment by merceyz** [comment] 2021-01-02 16:33
Closing as fixed by https://github.com/yarnpkg/yarn/pull/6629

**Closed by merceyz** 2021-01-02 16:33 UTC
Labels: plugnplay, triaged
