### ISSUE TITLE
Yarn install never ends with (complex ?) workspaces 

### ISSUE THREAD

**Issue by no-more** [yarnpkg/yarn#5726] opened 2018-04-25 05:18 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When launching `yarn install` in workspace directory it never ends(waited all night). But if I rollback to v1.3.2 it completes in 42s.

**If the current behavior is a bug, please provide the steps to reproduce.**
The project is on a private repo so I can't provide a link.

**What is the expected behavior?**
Should end within minutes.

**Please mention your node.js, yarn and operating system version.**
node: v9.11.1
Yarn: 1.6.0, 1.5.1, 1.3.2
Os: Ubuntu v9.11.1 or windows 10

I'm not sure if it could be related but the packages are referenced as `
    "package-a": "git+ssh://git@bitbucket.org/companyname/package-a.git#0.1.1-beta.81",`

**Comment by no-more** [comment] 2018-04-25 06:48
I created a similar public repo on github:

[nomore-test-workspace.zip](https://github.com/yarnpkg/yarn/files/1945711/nomore-test-workspace.zip)

I have the same issue, with version 1.3.2 installation completes in less than 30s (cache empty).
But with version 1.6.0 it does not seems to end.

**Comment by rally25rs** [comment] 2018-04-30 14:49
Trying to dig into this a bit but debugging all the recursion is tricky. The change that causes this to slow is somewhere between v1.3.2 and v1.4.0.

The code seems to just be cycling between `package-request` and `pacakge-resolver` recursively building up the entire tree, which gets very deep by the time you build `test-m` in the attached repro example. If you remove `test-g` through `test-m` then the install will finish, but you can also see it print out that it is resolving `zone.js` 3 or 4 times. It seems to be exponentially worse as you add back in the packages (`test-f` depends on `test-e` so all the resolves that happened for `test-e` happen again).

Just thinking through it, I suspect this might have something to do with `resolutions` because yarn always has to build the entire tree, just incase you had a resolution that said `test-m/**/test-g/test-f/**/test-b/test-a: "v1.2.3"` so the entire resolution tree building recursive thing can't be exited just because a lib has been resolved before. Just a thought anyway... no concrete evidence yet...

**Comment by rally25rs** [comment] 2018-04-30 14:59
I bisected the performance change back to [this commit] (https://github.com/yarnpkg/yarn/commit/6adbd472129b5410436ddefbd92093868bd98e49) which strangely is mine, yet I don't remember making these specific code changes when fixing peerDep warnings 😕 

I'll... uh... guess I'l try to figure out what I did here...

**Comment by rally25rs** [comment] 2018-04-30 15:17
Oh, yeah, based on my comments in the original PR https://github.com/yarnpkg/yarn/pull/5088

The code used to `return` when it had already resolved a package, and only build a partial dependency tree, so finding peerDeps wouldnt work if that part of the dep tree wasn't filled out.

If we put that logic back, then it's going to break peerDep resolution and I'm pretty sure will break `resolutions` in the way I mentioned above.

We might need to find some more efficient way to build the entire dep tree...

**Comment by no-more** [comment] 2018-04-30 16:05
Hi, thanks for your investigation.

This example is only representing a portion of the project I'm working with which contains much more dependencies between packages (but no cycling). I submitted this one because it's the smallest case which reproduce the issue.

Do you think that removing `resolution` section would change something ? I'm not sure but I think I've tried this case with no more success. But maybe I'm wrong. Could you please confirm if you think that's related I could create another test case without `resolution` sections.

Thanks.

**Comment by rally25rs** [comment] 2018-04-30 17:33
> Do you think that removing resolution section would change something?

I don't think the resolutions would matter.

**Comment by rally25rs** [comment] 2018-04-30 17:34
oops, clicked wrong button, accidental close :embarrassed:

**Comment by hulkish** [comment] 2018-06-11 00:08
@rally25rs resolutions definitely DO matter. The same behavior occurs for workspaces and/pr using resolutions.

**Comment by rally25rs** [comment] 2018-06-11 18:40
@no-more I opened PR #5970 if you want to give it a try in your actual project.

**Comment by no-more** [comment] 2018-06-12 05:20
@rally25rs Hi, thanks a lot but could you tell me how to install the PR for testing ?

**Comment by peter-mouland** [comment] 2018-06-13 09:08
@rally25rs hey - thanks for the PR!
I've just pulled and built `yarn-local`, unfortunately, my repo using workspace still hangs.  I can confirm it did not hang on 1.3.2, but does on 1.4.0+

**Comment by peter-mouland** [comment] 2018-06-13 09:34
hey @rally25rs , I'd say my mono-repo using workspaces could be said to be and the larger side (over 200 packages).  I just tried your pr locally, so thanks for that! 

*workspaces*
<img width="248" alt="workspaces" src="https://user-images.githubusercontent.com/1727939/41342896-2f7b6b50-6ef5-11e8-8dd6-8ea5a71d2f62.png">

# test results

*yarn-local*
<img width="383" alt="yarn-local" src="https://user-images.githubusercontent.com/1727939/41342780-f9605ac6-6ef4-11e8-98d6-a3fa9d71d245.png">

*yarn-1.7.0*
<img width="337" alt="yarn-1 7 0" src="https://user-images.githubusercontent.com/1727939/41342815-0a510178-6ef5-11e8-8427-490874cd7da2.png">

*yarn-1.3.2*
<img width="329" alt="yarn-1 3 2" src="https://user-images.githubusercontent.com/1727939/41342779-f9486510-6ef4-11e8-90b7-0f6311e81748.png">

**Comment by rally25rs** [comment] 2018-06-13 11:33
@peter-mouland @no-more sorry to waste your time. I discovered last night that my PR appeared fast to me because I had a yarn.lock in place from a previous run, and the lockfile makes it fast.

@hulkish and I are continuing to look into this and think we have a couple ideas on what's still not working.

**Comment by peter-mouland** [comment] 2018-06-13 12:32
no worries, happy to try and help. fyi: the above runs all had a yarnlock file - i just made sure i removed the node_modules before each install.

**Comment by rally25rs** [comment] 2018-06-16 00:45
@no-more while debugging some yarn code today I noticed a couple things about your example;

1) your workspace deps are specified as github repos:

```
"dependencies": {
    ...
    "nomore-test-l": "git+https://git@github.com/no-more/nomore-test-l.git#master",
    "nomore-test-j": "git+https://git@github.com/no-more/nomore-test-j.git#master",
    "nomore-test-i": "git+https://git@github.com/no-more/nomore-test-i.git#master",
    "nomore-test-h": "git+https://git@github.com/no-more/nomore-test-h.git#master",
    "nomore-test-g": "git+https://git@github.com/no-more/nomore-test-g.git#master",
    "nomore-test-f": "git+https://git@github.com/no-more/nomore-test-f.git#master",
    "nomore-test-e": "git+https://git@github.com/no-more/nomore-test-e.git#master",
    "nomore-test-d": "git+https://git@github.com/no-more/nomore-test-d.git#master",
    "nomore-test-c": "git+https://git@github.com/no-more/nomore-test-c.git#master",
    "nomore-test-b": "git+https://git@github.com/no-more/nomore-test-b.git#master",
    "nomore-test-a": "git+https://git@github.com/no-more/nomore-test-a.git#master",
```

This is causing a major issue as yarn decides if a project in your workspace matches a dependency request not just by checking the name ('nomore-test-a' for example) but also checks that the version specified in `packages/nomore-test-a/package.json` matches the requested semver range.

Since your semver range is a github url, it always returns `false`, which tells yarn that this `nomore-test-a` is not part of the workspace, so it goes and fetches it from github instead.

You should stick to a semver range, or `"*"`.

2) You have resolutions to the same thing as the depenency

```
  "dependencies": {
    "nomore-test-a": "git+https://git@github.com/no-more/nomore-test-a.git#master",
    ...
  },
  "resolutions": {
    "nomore-test-a": "git+https://git@github.com/no-more/nomore-test-a.git#master",
    ...
  }
```

As far as I can tell, this would serve no purpose. I don't think it is hurting performance, except for them being github urls so it falls into the same problem as above.

-----

If I change your example and make all the dependencies "*", and remove the resolutions, for example:

```
    "nomore-test-l": "*",
    "nomore-test-j": "*",
    "nomore-test-i": "*",
    "nomore-test-h": "*",
    "nomore-test-g": "*",
    "nomore-test-f": "*",
    "nomore-test-e": "*",
    "nomore-test-d": "*",
    "nomore-test-c": "*",
    "nomore-test-b": "*",
    "nomore-test-a": "*",
    ...
  },
  "resolutions": {},
```

then it takes yarn 1.7.0 about 11 seconds for me:

```
~/Projects/nomore-test-workspace 🐒   rm -rf node_modules/ yarn.lock && yarn
yarn install v1.7.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-c > @types/uglify-js > @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-c > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-d > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-e > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-f > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-g > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-i > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-j > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-k > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-l > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
warning workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-m > typings@2.1.1: Typings is deprecated in favor of NPM @types -- see README for more information
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > ng2-translate@5.0.0" has incorrect peer dependency "@angular/core@^2.0.0".
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > ng2-translate@5.0.0" has incorrect peer dependency "@angular/http@^2.0.0".
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > @angular/platform-server@4.4.6" has unmet peer dependency "@angular/animations@4.4.6".
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > ng2lint@0.0.10" has incorrect peer dependency "tslint@^3.5.0".
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > ng2lint@0.0.10" has incorrect peer dependency "typescript@~1.8.0".
warning "workspace-aggregator-1413c862-3062-445e-a792-bb3bfad6f0dc > nomore-test-h > nes@6.5.1" has unmet peer dependency "hapi@>=13.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 10.05s.
```

-----

That said, there are a few other performance issues that we've uncovered over days of digging through this. There is some duplication of work going on in a few places that we're working on a PR for, but I thought I would at least point these things out since they seem to make your example at least run in a fairly quick amount of time.

**Comment by no-more** [comment] 2018-06-16 04:19
Hi, thanks for your response but I can't switch to semver only because I'm using this on private repos hosted at bitbucket. That's why I have to use "git+https" syntax. It's only for this example that I was able to create public repos and publish them on npm.

I used to use "nomore-test-a": "git+https://git@github.com/no-more/nomore-test-a.git#0.1.5"  syntax before but this does not seems to change the installation time.

Isn't there another solution ?

Thanks

**Comment by rally25rs** [comment] 2018-06-22 19:46
@no-more I opened a PR above that should let yarn resolve the workspace packages correctly.

**Comment by spoldman** [comment] 2018-07-13 09:46
I have been having a similar issue where yarn install never completes. I have spent a lot of time trying to figure out what I did wrong and could be causing this as it just seemed to hang indefinitely without any messaging in the console. I tried running it over night and I got "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory". 

We are not using any resolutions or any packages straight from github. We use our own NPM server and using "latest" version for all our internal workspace packages. 

I was able to get it to run when I took all but 11 packages out of the workspace project. But as soon as I added more I ran into issues.

**Comment by peter-mouland** [comment] 2018-09-15 10:03
For anyone who is interested, I think this issue can probably be closed.  Our repo which uses yarn workspaces now has 500+ packages and no longer hangs on the latest version of yarn.

Assuming no regressions, Yarn 1.10.x seems to be

Here is the latest comparisons:
<img width="358" alt="yarn132" src="https://user-images.githubusercontent.com/1727939/45585024-5cd7ee00-b8d5-11e8-879c-c6a17e371761.png">
<img width="338" alt="yarn194" src="https://user-images.githubusercontent.com/1727939/45585025-5cd7ee00-b8d5-11e8-8c2a-bbf6d26e557b.png">
<img width="341" alt="yarn1100" src="https://user-images.githubusercontent.com/1727939/45585114-eb00a400-b8d6-11e8-8639-a0437fb259e4.png">

<img width="339" alt="yarn1110" src="https://user-images.githubusercontent.com/1727939/45585069-44b49e80-b8d6-11e8-8360-e939c8ad3b70.png">

and to complete the story, compared to npm:
<img width="601" alt="npm641" src="https://user-images.githubusercontent.com/1727939/45585029-6d886400-b8d5-11e8-9cc9-889cacb8fadd.png">

**Comment by peter-mouland** [comment] 2018-09-15 10:16
confusingly, I tried yarn 1.7.0 again and didn't have speed problems either...
<img width="340" alt="yarn170" src="https://user-images.githubusercontent.com/1727939/45585217-cad1e480-b8d8-11e8-9466-2fd22cb95c33.png">

**Comment by mschipperheyn** [comment] 2019-04-18 13:34
I still have this issue.

**Comment by peter-mouland** [comment] 2019-04-18 13:40
@mschipperheyn could you leave the yarn version number, maybe give an idea of if you use workspaces, how packages are being installed and how long it takes?
the version number also the same timings compared with a previous, fast, version which demonstrates a possible regression like I have done above?

**Comment by mschipperheyn** [comment] 2019-04-18 13:48
Hey @peter-mouland I use yarn workspaces which includes react-native, web and 2 common packages.
yarn 1.15.2
node 10.15.1

I can't install packages without running into the out of memory error. I use yarn --ignore-scripts to get everything installed (which creates other issues)

**Comment by mschipperheyn** [comment] 2019-08-06 10:56
A workaround that works for me is `yarn install --ignore-scripts && npm rebuild`
I'm wondering what parts I'm inadvertently skipping using this scenario?

**Comment by merceyz** [comment] 2021-01-03 03:20
Closing as fixed in v2 where the hoisting algorithm has been greatly improved

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-03 03:20 UTC
Labels: cat-performance, help wanted, high-priority

**Comment by airtonix** [comment] 2022-05-20 03:12
oh well sucks to those people who can't move to yarn 2

**Comment by peter-mouland** [comment] 2022-05-20 06:00
@airtonix Move to yarn 3.  You can keep your node_modules intact and the only major change is the move from an npmrc file to a yarnrc.yml.  Here's what i use while i get my dependencies in order for pnp

```yml
changesetIgnorePatterns:
  - "**/*.{test,spec}.{js,jsx,ts,tsx}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

npmRegistries:
  "your-registry-url-goes-here":
    npmAuthToken: ${NPM_AUTH_TOKEN}

```
