### ISSUE TITLE
Cannot install yarn without node (Brew)

### ISSUE THREAD

**Issue by joelpierre** [yarnpkg/yarn#6991] opened 2019-02-02 18:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot install yarn via brew using the --without-node flag (not sure if this is a yarn issue or brew issue

**If the current behavior is a bug, please provide the steps to reproduce.**
I uninstalled yarn and then tried to re-install yarn

**What is the expected behavior?**
Install yarn without node

**Please mention your node.js, yarn and operating system version.**
Node LTS 10.15.1

**Comment by datadaveshin** [comment] 2019-02-03 17:39
Happened to me too.
Looks like there was discussion on this in issue [6946](https://github.com/yarnpkg/yarn/issues/6946)

**Comment by arcanis** [comment] 2019-02-08 18:00
Duplicate of #6946

**Closed by arcanis** 2019-02-08 18:00 UTC
Labels: triaged
