### ISSUE TITLE
Installed devDependencies in --production

### ISSUE THREAD

**Issue by vchrm** [yarnpkg/yarn#3439] opened 2017-05-17 16:46 UTC
Hi, although there are no production dependencies at all, using `yarn install --production`  yarn still installs four packages (164 kB) to `node_modules/` with the following package.json:

```
{
  "devDependencies": {
    "webpack": "2.5.1"
  }
}
```

Shouldn't be `node_modules/` empty? Am I missing something? With our full package.json with 26 devDependencies (still no production dependencies) yarn goes to 21 MB.

I am using:
- yarn 0.24.4
- node 6.10.3
- Gentoo Linux

Thank you!

**Comment by jvhoven** [comment] 2017-05-17 20:57
This is indeed pretty weird. 

**Test case**

Installing with `yarn install --production`.

*Input*
```{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "webpack": "2.5.1"
  }
}
```
*Output* 
Modules inside the resulting `node_modules`.
```
238B May 17 22:40 assert-plus
204B May 17 22:40 camelcase
238B May 17 22:40 inherits
204B May 17 22:40 punycode
```

What makes it even stranger is that these four packages, are not directly related to the dependencies that webpack 2.5.1 [requires](https://pastebin.com/tMXVp0g7). Thankfully we can identify where they come from using `yarn why`.

### So where do these modules come from?

**assert-plus**
- "webpack#watchpack#chokidar#fsevents#node-pre-gyp#request#http-signature#jsprim" depends on it
- "webpack#watchpack#chokidar#fsevents#node-pre-gyp#request#http-signature#sshpk" depends on it

**camelcase**
- This module exists because "webpack#yargs" depends on it.

**inherits**
   - "webpack#memory-fs#readable-stream" depends on it
   - "webpack#node-libs-browser#crypto-browserify" depends on it
   - "webpack#watchpack#chokidar#fsevents#node-pre-gyp#tar" depends on it
   - "webpack#watchpack#chokidar#fsevents#node-pre-gyp#tar#block-stream" depends on it

**punycode**
   - "webpack#node-libs-browser" depends on it
   - "webpack#watchpack#chokidar#fsevents#node-pre-gyp#request#tough-cookie" depends on it

**Comment by jvhoven** [comment] 2017-05-17 22:13
After some digging in the source code I've found that [this part](https://github.com/yarnpkg/yarn/blob/master/src/package-linker.js#L126) contains the faulty(?) data which enables the modules to pass through the installation process.

`console.log` gives the following information:

```[ [ '/private/tmp/yarn/bin/node_modules/assert-plus',
    HoistManifest {
      isRequired: true,
      isIncompatible: false,
      loc: '...',
      pkg: [Object],
      key: 'assert-plus',
      parts: [Object],
      originalKey: 'assert-plus',
      previousKeys: [],
      history: [Object] } ],
  [ '/private/tmp/yarn/bin/node_modules/camelcase',
    HoistManifest {
      isRequired: true,
      isIncompatible: false,
      loc: '...',
      pkg: [Object],
      key: 'camelcase',
      parts: [Object],
      originalKey: 'camelcase',
      previousKeys: [],
      history: [Object] } ],
  [ '/private/tmp/yarn/bin/node_modules/inherits',
    HoistManifest {
      isRequired: true,
      isIncompatible: false,
      loc: '...',
      pkg: [Object],
      key: 'inherits',
      parts: [Object],
      originalKey: 'inherits',
      previousKeys: [],
      history: [Object] } ],
  [ '/private/tmp/yarn/bin/node_modules/punycode',
    HoistManifest {
      isRequired: true,
      isIncompatible: false,
      loc: '...',
      pkg: [Object],
      key: 'punycode',
      parts: [Object],
      originalKey: 'punycode',
      previousKeys: [],
      history: [Object] } ] ]

**Comment by digiwano** [comment] 2017-05-18 00:15
I'm experiencing the same issue. I wrote a little script (https://gist.github.com/digiwano/1df204da60eb628beb4c6146b8a58ec4) which does a bunch of various install types (with or without a devDependencies field, with either npm or yarn, with or without the --production flag) to compare what's getting installed.

The script creates package.jsons which include the production dependency `json-stringify-safe` and the development dependencies `ava`, `aws-sdk`, `nyc`, `sequelize-cli`, `serverless`, and `sinon`.

After attempting each install, it looks at the `yarn why` output of each dependency that got installed during `yarn install --production` and filters the output down to just the list of dependencies that are causing it to be included.

Output of running this script:
```
======= npm install (./test.npm.dev.withdevdeps/) :
Size of node_modules: 152M	node_modules
Number of folders in node_modules:      495
Number of folders in node_modules (recursively):     2402


======= npm install (./test.npm.dev.nodevdeps/) :
Size of node_modules:  40K	node_modules
Number of folders in node_modules:        1
Number of folders in node_modules (recursively):        3


======= yarn install (./test.yarn.dev.withdevdeps/) :
Size of node_modules: 124M	node_modules
Number of folders in node_modules:      635
Number of folders in node_modules (recursively):     2528


======= yarn install (./test.yarn.dev.nodevdeps/) :
Size of node_modules:  44K	node_modules
Number of folders in node_modules:        1
Number of folders in node_modules (recursively):        3


======= npm install --production (./test.npm.prod.withdevdeps/) :
Size of node_modules:  40K	node_modules
Number of folders in node_modules:        1
Number of folders in node_modules (recursively):        3


======= npm install --production (./test.npm.prod.nodevdeps/) :
Size of node_modules:  40K	node_modules
Number of folders in node_modules:        1
Number of folders in node_modules (recursively):        3


======= yarn install --production (./test.yarn.prod.withdevdeps/) :
Size of node_modules: 9.0M	node_modules
Number of folders in node_modules:       98
Number of folders in node_modules (recursively):      151


======= yarn install --production (./test.yarn.prod.nodevdeps/) :
Size of node_modules:  44K	node_modules
Number of folders in node_modules:        1
Number of folders in node_modules (recursively):        3


##### ansi-regex
"ava#strip-ansi" depends on it
"sequelize-cli#cli-color" depends on it

##### ansi-styles
"ava#@ava/pretty-format" depends on it.

##### assert-plus
"ava#chokidar#fsevents#node-pre-gyp#request#http-signature#jsprim" depends on it
"ava#chokidar#fsevents#node-pre-gyp#request#http-signature#sshpk" depends on it

##### async
"serverless" depends on it
"nyc#istanbul-reports#handlebars" depends on it

##### balanced-match
"ava#babel-core#minimatch#brace-expansion" depends on it.

##### brace-expansion
"ava#babel-core#minimatch" depends on it
"sequelize-cli#gulp#vinyl-fs#glob-stream#minimatch" depends on it

##### buffer-shims
"serverless#archiver#readable-stream" depends on it.

##### builtin-modules
"ava#meow#normalize-package-data#is-builtin-module" depends on it.

##### camelcase
"nyc#yargs" depends on it.

##### chalk
"ava" depends on it
"serverless" depends on it
"ava#babel-code-frame" depends on it
"ava#jest-diff" depends on it

##### cliui
"nyc#yargs" depends on it.

##### clone
"sequelize-cli#gulp#gulp-util#vinyl" depends on it
"sequelize-cli#gulp#vinyl-fs#defaults" depends on it

##### code-point-at
"nyc#yargs#string-width" depends on it.

##### commander
"serverless#json-refs" depends on it.

##### concat-map
"ava#babel-core#minimatch#brace-expansion" depends on it.

##### core-util-is
"serverless#archiver#readable-stream" depends on it.

##### decamelize
"ava#meow" depends on it
"nyc#yargs" depends on it
"nyc#istanbul-reports#handlebars#uglify-js#yargs" depends on it

##### error-ex
"ava#pkg-conf#load-json-file#parse-json" depends on it.

##### es6-error
"ava#hullabaloo-config-manager" depends on it
"ava#package-hash#release-zalgo" depends on it

##### escape-string-regexp
"ava#chalk" depends on it
"ava#figures" depends on it
"ava#matcher" depends on it

##### find-up
"nyc" depends on it
"ava#find-cache-dir#pkg-dir" depends on it

##### fs.realpath
"nyc#glob" depends on it.

##### get-caller-file
"nyc#yargs" depends on it.

##### get-stream
"ava#ava-init#execa" depends on it.

##### glob
"nyc" depends on it
"ava#globby" depends on it
"nyc#rimraf" depends on it
"serverless#archiver" depends on it

##### graceful-fs
"ava#hullabaloo-config-manager" depends on it
"sequelize-cli#fs-extra" depends on it
"ava#jest-snapshot#jest-util" depends on it
"serverless#archiver#archiver-utils" depends on it
"serverless#download#decompress" depends on it
"serverless#fs-extra#klaw" depends on it

##### graceful-readlink
"serverless#json-refs#commander" depends on it.

##### has-ansi
"ava#chalk" depends on it.

##### has-flag
"ava#supports-color" depends on it.

##### hosted-git-info
"ava#meow#normalize-package-data" depends on it.

##### imurmurhash
"ava#caching-transform#write-file-atomic" depends on it.

##### indent-string
"ava" depends on it
"ava#hullabaloo-config-manager" depends on it

##### inflight
"nyc#glob" depends on it.

##### inherits
"ava#chokidar" depends on it
"nyc#glob" depends on it
"serverless#archiver#readable-stream" depends on it
"ava#chokidar#fsevents#node-pre-gyp#tar#block-stream" depends on it

##### invert-kv
"nyc#yargs#os-locale#lcid" depends on it.

##### is-arrayish
"ava#pkg-conf#load-json-file#parse-json#error-ex" depends on it.

##### is-builtin-module
"ava#meow#normalize-package-data" depends on it.

##### is-fullwidth-code-point
"nyc#yargs#string-width" depends on it.

##### is-utf8
"ava#strip-bom-buf" depends on it
"nyc#default-require-extensions#strip-bom" depends on it

##### isarray
"sinon#path-to-regexp" depends on it.

##### json-stringify-safe
"ava#chokidar#fsevents#node-pre-gyp#request" depends on it

##### lcid
"nyc#yargs#os-locale" depends on it.

##### load-json-file
"ava#pkg-conf" depends on it.

##### lodash
"sequelize-cli" depends on it
"serverless" depends on it
"ava#babel-core" depends on it
"aws-sdk#xmlbuilder" depends on it
"sequelize-cli#umzug" depends on it
"serverless#archiver" depends on it
"serverless#archiver#async" depends on it
"serverless#json-refs#graphlib" depends on it

##### lodash.flattendeep
"ava#package-hash" depends on it.

##### lru-cache
"nyc#foreground-child#cross-spawn" depends on it
"ava#update-notifier#boxen#term-size#execa#cross-spawn-async" depends on it

##### md5-hex
"nyc" depends on it
"ava#@ava/babel-preset-stage-4#package-hash" depends on it

##### md5-o-matic
"ava#md5-hex" depends on it.

##### minimatch
"ava#babel-core" depends on it
"ava#multimatch" depends on it

##### minimist
"serverless" depends on it
"ava#meow" depends on it
"sequelize-cli#gulp" depends on it

##### normalize-package-data
"ava#meow" depends on it
"ava#ava-init#read-pkg-up#read-pkg" depends on it

##### number-is-nan
"ava#pretty-ms#is-finite" depends on it.

##### object-assign
"ava#globby" depends on it
"nyc#test-exclude" depends on it

##### once
"nyc#glob" depends on it
"serverless#archiver#tar-stream#end-of-stream" depends on it
"ava#chokidar#fsevents#node-pre-gyp#tar-pack" depends on it

##### os-locale
"nyc#yargs" depends on it.

##### package-hash
"ava" depends on it.

##### parse-json
"ava#pkg-conf#load-json-file" depends on it.

##### path-exists
"nyc#find-up" depends on it.

##### path-is-absolute
"ava#babel-core" depends on it.

##### path-key
"ava#update-notifier#boxen#term-size#execa" depends on it.

##### path-type
"ava#meow#read-pkg-up#read-pkg" depends on it.

##### pify
"ava#globby" depends on it
"serverless#download" depends on it

##### pinkie
"ava#globby#pinkie-promise" depends on it.

##### pinkie-promise
"ava#globby" depends on it.

##### process-nextick-args
"serverless#archiver#readable-stream" depends on it.

##### pseudomap
"nyc#foreground-child#cross-spawn#lru-cache" depends on it.

##### read-pkg
"ava#meow#read-pkg-up" depends on it.

##### read-pkg-up
"ava#meow" depends on it.

##### readable-stream
"serverless#archiver" depends on it
"ava#chokidar#readdirp" depends on it
"ava#last-line-stream#through2" depends on it
"serverless#archiver#archiver-utils#lazystream" depends on it
"ava#chokidar#fsevents#node-pre-gyp#tar-pack" depends on it
"ava#chokidar#fsevents#node-pre-gyp#npmlog#are-we-there-yet" depends on it

##### release-zalgo
"ava#package-hash" depends on it.

##### require-directory
"nyc#yargs" depends on it.

##### require-main-filename
"nyc#test-exclude" depends on it.

##### semver
"serverless" depends on it
"nyc#istanbul-lib-instrument" depends on it
"ava#meow#normalize-package-data" depends on it
"ava#update-notifier#latest-version#package-json" depends on it

##### set-blocking
"nyc#yargs" depends on it
"ava#chokidar#fsevents#node-pre-gyp#npmlog" depends on it

##### signal-exit
"nyc" depends on it
"ava#loud-rejection" depends on it
"ava#cli-cursor#restore-cursor" depends on it

##### slide
"ava#caching-transform#write-file-atomic" depends on it.

##### source-map
"ava#babel-core" depends on it
"ava#source-map-support" depends on it
"nyc#istanbul-lib-source-maps" depends on it
"nyc#istanbul-reports#handlebars#uglify-js" depends on it

##### spdx-correct
"ava#meow#normalize-package-data#validate-npm-package-license" depends on it.

##### spdx-expression-parse
"ava#meow#normalize-package-data#validate-npm-package-license" depends on it.

##### spdx-license-ids
"ava#meow#normalize-package-data#validate-npm-package-license#spdx-correct" depends on it.

##### string-width
"nyc#yargs" depends on it
"nyc#yargs#cliui" depends on it

##### string_decoder
"sequelize-cli#gulp#vinyl-fs#through2#readable-stream" depends on it.

##### strip-ansi
"ava" depends on it
"ava#chalk" depends on it

##### strip-bom
"nyc#default-require-extensions" depends on it.

##### supports-color
"ava" depends on it
"nyc#istanbul-lib-report" depends on it

##### through2
"sequelize-cli#gulp#vinyl-fs" depends on it.

##### util-deprecate
"serverless#archiver#readable-stream" depends on it.

##### uuid
"aws-sdk" depends on it
"ava#chokidar#fsevents#node-pre-gyp#request" depends on it

##### validate-npm-package-license
"ava#meow#normalize-package-data" depends on it.

##### which-module
"nyc#yargs" depends on it.

##### wrap-ansi
"nyc#yargs#cliui" depends on it.

##### wrappy
"nyc#glob#inflight" depends on it.

##### write-file-atomic
"ava#update-notifier#configstore" depends on it.

##### xtend
"ava#last-line-stream#through2" depends on it
"serverless#archiver#tar-stream" depends on it
"sequelize-cli#gulp#vinyl-fs#through2" depends on it

##### y18n
"nyc#yargs" depends on it.

##### yallist
"nyc#foreground-child#cross-spawn#lru-cache" depends on it.

##### yargs
"nyc" depends on it
"sequelize-cli" depends on it

##### yargs-parser
"nyc" depends on it.


MD5 (test.yarn.dev.nodevdeps/yarn.lock) = b48cde713cfcb0eba139891969a67ee3
MD5 (test.yarn.dev.withdevdeps/yarn.lock) = 2bf902d95fc802b253f5bf7abe9497e5
MD5 (test.yarn.prod.nodevdeps/yarn.lock) = b48cde713cfcb0eba139891969a67ee3
MD5 (test.yarn.prod.withdevdeps/yarn.lock) = 2bf902d95fc802b253f5bf7abe9497e5
```

Digging through all of this just confuses me more, though:

* none of the direct devDependencies are installed. All of the packages that **DO** get installed are dependencies of devDependencies or further. This begs the question: when --production is passed, why does yarn look at the devDependencies field at all in the first place? Shouldn't --production be functionally equivalent to deleting the devDependencies entry from package.json entirely? 
* perhaps related to the above, `yarn.lock` seems to have no idea whether or not a package listed within it is a devDependency of another package rather than a regular dependency, and is exactly the same file contents whether or not --production is passed. I would also expect `yarn.lock` to be identical when generated through `yarn install --production` as it would when `yarn install` is run after deleting the devDependencies field -- why would devDependency information be needed at all for a production install?
* despite the fact that there's a lot of extra dependencies included, it is by far not **all** dev dependencies. My numbers above show that, for this set of dependencies, by fs size usage, `yarn install --production` installs roughly 7% of what `yarn install` does -- while `npm install --production` installs roughly 0.02% of what `npm install` does. 

I'm not sure what's actually causing all these packages to install, but I can't understand why they're even being **checked** during `--production`.

**Comment by juanca** [comment] 2017-05-18 21:14
devDependencies need to be considered when installing with `--production` because they could impose semver restrictions on actual production dependencies -- theoretically, dependencies should use the same versions in production and development. However, this data is only needed to determine which versions to install (and not actually install devDependencies trees).

Note: I've only read the hoisting code a bit (to try to fix this particular bug) and don't deeply understand it (yet). 

I've been trying to finish a PR which adds test cases (such as these). I'll bring in this example as well.

**Comment by digiwano** [comment] 2017-05-18 21:50
> devDependencies need to be considered when installing with --production because they could impose semver restrictions on actual production dependencies -- theoretically, dependencies should use the same versions in production and development.

That feels weird too -- why would a dev dependency change the semver requirements of a production dependency? I'd rather have devDependencies be entirely unhoisted/unflattened than have them interfering with production dependency versions. 

And if that's an issue, if we've followed best practices advice and checked in our yarn.lock, shouldn't `yarn install --production` just be able to ignore devDependencies in the "what packages do i need to install/consider" logic, but look up the to-be-installed version from the lock file?

**Comment by blexrob** [comment] 2017-05-21 20:26
This bug is caused by the package hoister. In `_seed`, an initial assessment is done if a package is required. Packages that are not compatible are always ignored. Packages without a parent are marked required if the package reference `ignore` flag is not set (which is done for ignored devDependencies). Packages with a parent copy their parent's required status.

This process assumes that packages without a parent are referenced directly from the package.json - by the following line.

```
let isRequired = !parent && !ref.ignore && !isIncompatible;
```
But, the prepass phase that runs before the actual hoisting seeds the packages with the highest occurence counts first - but does so without prodiving a parent to `_seed`. `_seed` then assumes they are direct, non-ignored dependencies from package.json because of the missing parent parameter.

**Closed** 2017-05-23 10:13 UTC
