### ISSUE TITLE
Yarn ignore included files at package.json

### ISSUE THREAD

**Issue by rx-837** [yarnpkg/yarn#6403] opened 2018-09-19 12:48 UTC
**Do you want to request a *feature* or report a *bug*?**
I wanna to report a bug.

**What is the current behavior?**
Yarn doesn'n copy folders described at files-section of package.json
https://docs.npmjs.com/files/package.json#files
https://yarnpkg.com/lang/en/docs/package-json/#toc-files

Steps to reproduce:
1) create folders "a", "b"
2) initialize a git repository at "a" folder
3) initialize a package at "a" folder
4) add to `a/package.json` `"files": [".git"]`
5) commit all changes at "a" folder
6) goto "b" folder
7) initialize a package at "b" folder
8) add to `package.json` `"dependecies": {"a", "git+file:///full_path/a"}`
9) run yarn install
10) run `ls -la node_modules/a`

Result:
```
total 12
drwxrwxr-x 2 rtt rtt 4096 сен 19 15:42 .
drwxrwxr-x 3 rtt rtt 4096 сен 19 15:42 ..
-rw-rw-r-- 1 rtt rtt  218 сен 19 15:27 package.json
```

**What is the expected behavior?**
Yarn copy folders described at files-section of package.json like npm
Expected result:
```
total 16
drwxrwxr-x 3 rtt rtt 4096 сен 19 15:43 .
drwxrwxr-x 3 rtt rtt 4096 сен 19 15:43 ..
drwxrwxr-x 8 rtt rtt 4096 сен 19 15:43 .git
-rw-rw-r-- 1 rtt rtt  197 сен 19 15:32 package.json
```

**Please mention your node.js, yarn and operating system version.**
node v8.10.0
yarn version v1.9.4

**Comment by rally25rs** [comment] 2018-09-20 12:58
Pretty sure this is a duplicate of #2822
Basically yarn is only using `files` at `yarn publish` time, but not when installing packages that haven't been "published" in the traditional way.

**Closed by rally25rs** 2018-09-20 12:58 UTC
Labels: triaged
