### ISSUE TITLE
Yarn keeps telling me to remove devDependencies

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#5463] opened 2018-03-06 11:07 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
$ yarn upgrade electron

warning "electron" is already in "devDependencies". Please remove existing entry first before adding it to "dependencies".
```

Woot?

**If the current behavior is a bug, please provide the steps to reproduce.**

Upgrade any devDependency

**What is the expected behavior?**

Should update without whining.

**Please mention your node.js, yarn and operating system version.**
1.5.1

**Comment by rally25rs** [comment] 2018-03-06 16:56
duplicate of #4840

this happens because internally `upgrade` utilizes `add` by collecting up all the outdated deps and passing them to `yarn add`, but it does not distinguish between deps and devDeps like `add` expects. The upgrade is performed correctly, but the warning is a known issue at the moment.

**Closed by rally25rs** 2018-03-06 16:56 UTC
Labels: triaged

**Comment by kaylieEB** [comment] 2018-03-06 17:07
Yup i think there's an existing PR for this https://github.com/yarnpkg/yarn/pull/4900/files
