### ISSUE TITLE
While initializing with "yarn init" within gitbash it throws an error

### ISSUE THREAD

**Issue by Juni4567** [yarnpkg/yarn#1325] opened 2016-10-21 04:49 UTC
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug. It's whenever I want to install/init with yarn init while using git bash command line it won't work as expected.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Users\junai\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js init

PATH: 
  C:\Users\junai\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\junai\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Skype\Phone;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Users\junai\AppData\Local\Microsoft\WindowsApps;C:\Users\junai\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl

Yarn version: 
  0.16.1

Node version: 
  6.5.0

Platform: 
  win32 x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Can't answer a question unless a user TTY
      at ConsoleReporter.question (C:\Users\junai\AppData\Roaming\npm\node_modules\yarn\lib\reporters\console\console-reporter.js:186:29)
      at Object.<anonymous> (C:\Users\junai\AppData\Roaming\npm\node_modules\yarn\lib\cli\commands\init.js:95:34)
      at next (native)
      at step (C:\Users\junai\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at C:\Users\junai\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20

```

**Comment by Daniel15** [comment] 2016-10-21 04:59
This is a duplicate of #743, so I'm going to close this issue. Please subscribe to that issue for updates. Thank you for trying Yarn! 😄

**Closed by Daniel15** 2016-10-21 04:59 UTC
