### ISSUE TITLE
node-zopfli not found by CompressionPlugin (optional dependency linking?)

### ISSUE THREAD

**Issue by yisding** [yarnpkg/yarn#2644] opened 2017-02-06 18:17 UTC
yarn 0.20 on nodejs 7 on MacOS.

06 02 2017 10:13:11.072:ERROR [config]: Invalid config file!
  Error: node-zopfli not found
    at new CompressionPlugin

In devDependencies, I have:

"node-zopfli": "^2.0.2",

In my yarn.lock:

compression-webpack-plugin@^0.3.2:
  version "0.3.2"
  resolved ****
  dependencies:
    async "0.2.x"
    webpack-sources "^0.1.0"
  optionalDependencies:
    node-zopfli "^2.0.0"

node-zopfli@^2.0.0, node-zopfli@^2.0.2:
  version "2.0.2"
  resolved ****
  dependencies:
    commander "^2.8.1"
    defaults "^1.0.2"
    nan "^2.0.0"
    node-pre-gyp "^0.6.4"

It doesn't always give me problems, but I've definitely seen this a few times.

**Comment by Eightyplus** [comment] 2017-03-30 09:10
It is giving me problem, eventhough i have node-zopfli installed in node_modules :/
```
/usr/src/app/node_modules/compression-webpack-plugin/index.js:20
				throw new Error("node-zopfli not found");
				^

Error: node-zopfli not found
    at new CompressionPlugin (/usr/src/app/node_modules/compression-webpack-plugin/index.js:20:11)
    at getPluginsConfig (/usr/src/app/webpack.config.js:262:5)
    at Object.<anonymous> (/usr/src/app/webpack.config.js:335:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
error Command failed with exit code 1.
```

**Comment by Eightyplus** [comment] 2017-03-30 09:28
Actually I'm having the same problem with NPM, so I think the problem is due to 'compression-webpack-plugin'

**Comment by zjh65204** [comment] 2017-07-26 02:14
same question here ! It troubles me in this week !!!

**Comment by BYK** [comment] 2017-07-26 10:58
This doesn't seem to be a Yarn-specific issue so closing. I'd suggest contacting the package authors or checking your `package.json` in case they listed a package as `peerDependency` and your `package.json` is missing it.

Feel free to mention if you have a reproducible test case tying this back to Yarn and I'm happy to reopen.

**Closed by BYK** 2017-07-26 10:58 UTC
