### ISSUE TITLE
Yarn run leads to different result than npm run

### ISSUE THREAD

**Issue by dimitrioskarvounaris** [yarnpkg/yarn#8319] opened 2020-08-25 12:02 UTC
### Bug description
In combination with webpack and laravel mix, running `yarn run dev` gives different results than `npm run dev`. 

The issue: One additional file is extracted with npm, as the webpack/mix configuration asks to and is correct. This file is missing and not extracted, when executed with yarn. The result is correct with npm though.

**Command**

```sh
yarn run dev
```

in regard to
https://github.com/Nothing-Works/mix/blob/master/webpack.mix.js line 8
and any other repo running this task with the specific extract option.

**What is the current behavior?**
The file is not being extracted, when executed with yarn. Yarn's output:

```
 DONE  Compiled successfully in 7878ms                                                                                     13:50:31

       Asset      Size   Chunks             Chunk Names
/css/app.css   0 bytes  /js/app  [emitted]  /js/app
  /js/app.js  2.59 MiB  /js/app  [emitted]  /js/app
Done in 9.82s.
```

**What is the expected behavior?**
The file to be extracted as the configuration asks and as it happens when run with `npm run dev`. NPM gives the following output:
```
<s> [webpack.Progress] 100%

                     Asset      Size   Chunks             Chunk Names
              /css/app.css   0 bytes  /js/app  [emitted]  /js/app
                /js/app.js  1.77 MiB  /js/app  [emitted]  /js/app
css/vuetify-components.css   617 KiB  /js/app  [emitted]  /js/app
```

**Steps to Reproduce**
Reproducing it is very easy, and is possible with the simplest of configuration. 

1. Clone the repo https://github.com/Nothing-Works/mix  (contains the line 8 with the extract option in webpack.mix.js, which is ignored with yarn)
2. Run `yarn install`
3. Run `yarn dev`
4. Compare the result with running next `npm run dev`. 
5. As the last output shows, one extra file is generated in the public folder, as it should, which is previously ignored with yarn. 

**Environment**

- Node Version: `v12.18.2`
- Yarn v1 Version: `1.22.4` 
- OS and version: Windows 10 + Git Bash cmd

**Comment by rally25rs** [comment] 2020-08-30 11:47
Unable to reproduce.

My output when running `yarn run dev` is
```
 DONE  Compiled successfully in 19799ms

                     Asset      Size   Chunks             Chunk Names
              /css/app.css   0 bytes  /js/app  [emitted]  /js/app
                /js/app.js  1.77 MiB  /js/app  [emitted]  /js/app
css/vuetify-components.css   617 KiB  /js/app  [emitted]  /js/app
✨  Done in 21.55s.
```

```
~/Projects/mix (master *) 🐒   yarn -v
1.22.5

~/Projects/mix (master *) 🐒   node -v
v12.13.1
```

**Comment by paul-soporan** [comment] 2021-01-03 18:04
Closing as unreproducible.

**Closed by paul-soporan** 2021-01-03 18:04 UTC
