### ISSUE TITLE
yarn install got Internal Server Error for request: http://registry.npmjs.org/compression/-/compression-1.7.2.tgz

### ISSUE THREAD

**Issue by jairusd** [yarnpkg/yarn#5901] opened 2018-05-29 05:09 UTC
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
getting error message:
error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: Request failed \"500 Internal Server Error\"".
**If the current behavior is a bug, please provide the steps to reproduce.**

got an existing project, decided to migrate to yarn from npm, removed modules and ran yarn
**What is the expected behavior?**
should install properly
**Please mention your node.js, yarn and operating system version.**

node 10.2.1

**Comment by jairusd** [comment] 2018-05-29 05:13
[yarn-error.log](https://github.com/yarnpkg/yarn/files/2046815/yarn-error.log)

**Comment by NLincoln** [comment] 2018-05-29 21:58
We are also experiencing this issue, here's a bit of info about our environment:

- `yarn` is running inside of a docker container. This docker container is a bit behind on yarn versions, at 1.5.1
- Running yarn outside of the docker container works, which makes this weird to debug. It fairly consistently errors inside the docker environment though. 
- Node is v8.9.4

I'll spend some time later getting an example repo up and running.

**Comment by NLincoln** [comment] 2018-05-29 22:00
Alright I just tried to re-run using the bundled version of yarn found [here](https://github.com/yarnpkg/yarn/releases/tag/v1.5.1), it worked fine. I am going to guess that this is a docker related issue? @jairusd are you also running yarn inside of a docker container?

**Comment by jairusd** [comment] 2018-05-30 03:02
no i am not, and this error is consistent if i try to install with npm. I cant install anything at all :(

**Comment by NLincoln** [comment] 2018-05-30 13:27
We're back up and running normally, this is probably related to the npm service outage that occurred last night related to proxies https://github.com/npm/npm/issues/20791

**Comment by jensschulze** [comment] 2018-05-30 14:19
We're still having issues, it's not always the same error here.
Most current example:
```
Status: Downloaded newer image for node:9
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/chalk/-/chalk-1.1.3.tgz: Request failed \"503 Service Unavailable\"".
```
Node 9 (Docker image); Yarn 1.5.1; OS: unknown Linux (Docker in Docker on a Gitlab instance i have no direct access to)

**Comment by BYK** [comment] 2018-05-30 15:23
Duplicate of #5908.

**Closed by BYK** 2018-05-30 15:23 UTC
Labels: triaged

**Comment by Sliim** [comment] 2018-06-06 15:47
@BYK  Why it is a duplicate? You linked an issue about 429 error, not 503.

**Comment by BYK** [comment] 2018-06-06 16:20
@Sliim they were different manifestations of the same underlying issue which has been resolved.

**Comment by imad-mn** [comment] 2019-05-30 17:27
Guys, I got into similar problem.

info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: read ECONNRESET".
info If you think this is a bug, please open a bug report with the information provided in "C:\gitprojects\react-oidc-client-js\src\yarn-error.log".

I ran yarn into other projects without issues. Also, I could download that compression.1.7.2.tgz without issues if I put that url in the browser.

Any help fixing this issue is appreciated.
I'm running the latest version of each: node v10.16.0 and yarn v1.16.0
[yarn-error.log](https://github.com/yarnpkg/yarn/files/3238046/yarn-error.log)

**Comment by imad-mn** [comment] 2019-05-30 17:34
[yarn-error.log](https://github.com/yarnpkg/yarn/files/3238071/yarn-error.log)
hello guys,
I got the error mentioned in the title when running yarn.

info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "http://registry.npmjs.org/compression/-/compression-1.7.2.tgz: read ECONNRESET".

I ran yarn into other projects without issues. Also, I could download that compression.1.7.2.tgz without issues if I put that url in the browser.

Please, let me know if someone know how to fix this issue.
I'm running the latest version of each: node v10.16.0 and yarn v1.16.0
