### ISSUE TITLE
--registry argument

### ISSUE THREAD

**Issue by kittens** [yarnpkg/yarn#879] opened 2016-10-12 13:24 UTC

**Comment by wyze** [comment] 2016-10-12 13:25
Duplicate of #792.

**Comment by addyosmani** [comment] 2016-10-12 20:07
@kittens happy to help with closing issues if my privs could be bumped.. 😄 This is indeed a dupe. I'd also support opting for `publishConfig` instead of the arg, but there may be good reasons to support this otherwise.

**Comment by wyze** [comment] 2016-10-24 18:00
I have some power now to close this as a duplicate of #792.

**Closed by wyze** 2016-10-24 18:00 UTC
Labels: needs triage
