### ISSUE TITLE
Yarn clones entire git+ssh repo instead of including only folders defined in package.json files: [] field.

### ISSUE THREAD

**Issue by i-prashant** [yarnpkg/yarn#3385] opened 2017-05-12 13:38 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug/feature ??

**What is the current behavior?**
yarn installs private git repo node_module by cloning it entirely

**What is the expected behavior?**
npm installs private git repo's only relevant files and folders by reading files: [] field in package.json
It would be great if yarn could do the same.

**Please mention your node.js, yarn and operating system version.**
node: v6.9.4
yarn: v0.24.2
os: win 7

**Comment by rally25rs** [comment] 2017-05-15 12:40
Duplicate of #2822 @bestander

**Closed** 2017-05-15 12:40 UTC
