### ISSUE TITLE
yarn linking dependencies on windows painfully long

### ISSUE THREAD

**Issue by DanielLuu** [yarnpkg/yarn#2270] opened 2016-12-16 00:54 UTC
Is the amount of time yarn takes to link dependencies supposed to be extremely long?  Doesn't seem to be the case on mac.

**Comment by lednhatkhanh** [comment] 2016-12-17 13:28
Me too, it takes me over 100s to link my newly created `create react app` when I add react semantic package

**Comment by torifat** [comment] 2016-12-18 17:31
Duplicate of #990

**Closed by torifat** 2016-12-18 17:31 UTC
Labels: duplicate
