### ISSUE TITLE
`yarn` not respecting the local `.npmrc` if `~/.npmrc` is present.

### ISSUE THREAD

**Issue by sarbbottam** [yarnpkg/yarn#3411] opened 2017-05-15 15:51 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
`yarn` in the presence of `~/.npmrc` does not respect the `~/local/.npmrc`.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is to do with scoped internal packages.
You can only reproduce it if you are dealing with scoped internal (non-npm hosted packages).
- create `~/.npmrc` file with the following content.
`//registry.npmjs.org/`
- create `~/local/.npmrc` file with the `registry` information for the scoped internal (non-npm hosted packages).
- create `package.json` listing the scoped internal (non-npm hosted packages) as dependencies.
- execute `yarn`
- `yarn` errors out with `error Couldn't find package "@organization/scoped-internal-package" on the "npm" registry.`
- `yarn`  is still trying to look for the dependency at `npm`
- however, if the `~/.npmrc` is removed or renamed, `yarn` works as desired.
- looks like while looking for `.npmrc`, `yarn` is giving higher precedence to the top most `.npmrc`. It should be the reverse. While looking for `.npmrc` yarn should look at the current directory `.npmrc` and traverse up if not found.

**What is the expected behavior?**
`yarn` should give the highest precedence to the local `.npmrc` file.

**Please mention your node.js, yarn and operating system version.**
- `OS - macOS Sierra 10.12.4`
- `node - 7.9.0`
- `yarn 0.24.4`

**Comment by sarbbottam** [comment] 2017-05-15 19:23
Possibly related issues:
- #521
- #606
- #2118
- #2193
- #2541

**Comment by sarbbottam** [comment] 2017-05-15 19:24
Please note `yarn` does not respect the `~/local/.npmrc` only if there is a `~/.npmrc`.
If there is no `~/.npmrc`, `yarn` works as expected.

**Comment by marian-r** [comment] 2017-05-17 11:54
I can confirm that `repository` config works fine for me as also mentioned in https://github.com/yarnpkg/yarn/issues/2193#issuecomment-265802472.

**Comment by bestander** [comment] 2017-05-23 17:45
duplicate of https://github.com/yarnpkg/yarn/issues/2118

**Closed by bestander** 2017-05-23 17:45 UTC
