### ISSUE TITLE
-v eaten by yarn arguments parser when running a command

### ISSUE THREAD

**Issue by bnjbvr** [yarnpkg/yarn#5571] opened 2018-03-25 16:22 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a bug!

**What is the current behavior?**

- install `onchange` first: `yarn add onchange`
- `touch /tmp/hello`
- add a command in package.json: `"onchange": "onchange"`
- run the following command: `yarn run onchange /tmp/hello -v -- cp /tmp/hello /tmp/copy`

Note that `-v` is the verbose option for `onchange` here.

This command prints the version of `yarn`, because the `-v` is probably interpreted by yarn argument parser.

**What is the expected behavior?**

This should be equivalent to just running `onchange /tmp/hello -v -- cp /tmp/hello /tmp/copy`, that is, all the arguments after the command name should be passed to the subcommand.

A workaround is to insert `--` just after run, but yarn complains about it:

```
$ yarn run -- onchange /tmp/hello -v -- cp /tmp/hello /tmp/copy             
yarn run v1.5.1          
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ onchange /tmp/hello -v -- cp /tmp/hello /tmp/copy                                                  
onchange: watching /tmp/hello                     

```

**Please mention your node.js, yarn and operating system version.**

- nodejs: v8.9.1
- yarn: v1.5.1
- ubuntu 17.10

**Comment by rally25rs** [comment] 2018-03-25 23:36
This happens specifically because of the `--` which is an indicator to yarn that parameters that follow the `--` are to be passed to the command and params to the left are for yarn. Hence the printed warning

> warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.

your "workaround" is the correct way to handle this. The warning is just there to notify people of a future deprecation so you can ignore it for now. (this is pretty much working as designed at the moment.)

**Comment by paul-soporan** [comment] 2021-01-02 21:33
Closing this as fixed in the v2, the CLI framework we use now properly handles `yarn run onchange /tmp/hello -v -- cp /tmp/hello /tmp/copy`.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-02 21:33 UTC
Labels: triaged
