### ISSUE TITLE
Slow `yarn global` commands: bug?

### ISSUE THREAD

**Issue by mrkishi** [yarnpkg/yarn#2633] opened 2017-02-04 21:22 UTC
**Do you want to request a *feature* or report a *bug*?**
It's possibly a bug.

**What is the current behavior?**
Several `yarn global` commands seem to trigger all of the globally installed packages' scripts.

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
> # install packages with "heavy" scripts:
> yarn global add polymer-cli electron
Done in 156.01s.

> # all of these now take a long time because they execute polymer-cli's and electron's scripts:
> yarn global ls
Done in 36.34s.

> yarn global add left-pad
Done in 36.34s.

> yarn global remove left-pad
Done in 42.70s.

> yarn global upgrade
Done in 94.08s.
```

**What is the expected behavior?**
I didn't expect `yarn` to run every globally installed packages' scripts for those commands. `yarn global ls`, for instance, seems highly unrelated. There may be a reason for it, but it feels like a bug from the outside.

**Please mention your node.js, yarn and operating system version.**

```bash
> node --version
v7.4.0

> yarn --version # note: this has happened since at least v0.17
0.20.0

> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      15014  0
```

**Comment by bestander** [comment] 2017-06-26 19:38
Can repro in 0.27.0

**Comment by aarohmankad** [comment] 2017-07-19 18:32
Still reproducible in 0.27.5.

`yarn global list` takes 214.57 seconds
![screenshot from 2017-07-19 11-26-00](https://user-images.githubusercontent.com/3311321/28383289-d2b80950-6c75-11e7-80b7-175a5501a4cc.png)

**Comment by jamiestraw** [comment] 2017-10-26 16:05
Still reproducible in `1.2.1`

**Comment by BYK** [comment] 2017-10-27 10:58
I think this is a manifestation of #932, just with the global command so closing this as a duplicate of #932.

**Closed by BYK** 2017-10-27 10:58 UTC
Labels: bug-configuration, cat-bug, help wanted, triaged

**Comment by dsifford** [comment] 2018-05-07 22:38
`yarn global list` is still in the order of ~4 times slower than `npm -g ls` for me. Is this expected?

Of note, `yarn global list` is so slow that it renders a progress bar. Is there a technical reason for this?

**Yarn:** `time yarn global list`
```
real    0m0.715s
user    0m0.779s
sys     0m0.126s
```

**npm:** `time npm -g ls`
```
real    0m0.195s
user    0m0.174s
sys     0m0.024s
```

**Comment by bestander** [comment] 2018-05-07 22:59
Yes there is a bug, it runs install to verify integrity unnecessarily
