### ISSUE TITLE
Upgrade-interactive does not work for Node.js above v10.2.0

### ISSUE THREAD

**Issue by negezor** [yarnpkg/yarn#5949] opened 2018-06-07 17:00 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
After the packages are selected, the installation hangs in place without further output

**If the current behavior is a bug, please provide the steps to reproduce.**

I updated my version of Node.js from v10.0.0 to v10.4.0, this behavior started from v10.2.0
Steps:
```shell
$ yarn upgrade-interactive --latest
```
I select packages for updating, I press enter and all

**What is the expected behavior?**
Updating packages

**Please mention your node.js, yarn and operating system version.**
Node.js: v10.4.0
Yarn: 1.7.0
Windows: 10

**Comment by gluons** [comment] 2018-07-25 06:20
Me too. It hangs. Can't stop it with <kbd>Ctrl</kbd> + <kbd>C</kbd>.

Node: `v10.7.0`
Yarn: `1.7.0`
OS: Windows 10

**Comment by rally25rs** [comment] 2018-11-05 13:14
Going to close several other issues as duplicates of this one, since this seems to be the oldest issue that reports this.

From what I can tell it's specific to Windows + Node 10.

If someone who can consistently reproduce this can help debug, it would be appreciated!

**Comment by rally25rs** [comment] 2018-11-05 13:16
The best lead on tracking this down seems to be https://github.com/yarnpkg/yarn/issues/6198#issuecomment-433551126

**Comment by heyimalex** [comment] 2018-11-05 22:44
I know this has been merged, but just confirming that running upgrade-interactive off head works for me now!

**Comment by kallaspriit** [comment] 2018-11-06 08:39
Had the same issue with the latest stable of 1.12.1, works with nightly 1.13.0 version.

**Comment by krnlde** [comment] 2019-02-07 11:27
@contributors: Close?

**Comment by rolbr** [comment] 2019-11-22 16:14
Just want to confirm:

I'm on Windows 10. With Node v10.15.3 + Yarn 1.10.1 `yarn upgrade-interactive` would show me the table of dependencies to upgrade but would then freeze. Downloading the latest stable installer from https://yarnpkg.com/lang/en/docs/install/#windows-stable (1.19.1) fixed the issue.

Thanks! (I think this can be closed)

**Closed** 2020-01-27 19:56 UTC
Labels: cat-bug, help wanted
