### ISSUE TITLE
[BUG] GPG error: http://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C2130DFD2497F5

### ISSUE THREAD

**Issue by abkrim** [yarnpkg/yarn#2029] opened 2016-11-25 06:59 UTC
Ubuntu 16.04 on Homestead Vagrant 0.6.0

try sudo apt update and get ->

```
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C2130DFD2497F5
W: Failed to fetch http://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C2130DFD2497F5
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Daniel15** [comment] 2016-11-25 10:41
Did you add the public key?

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

**Comment by Kyr** [comment] 2016-11-26 14:02
Adding public key solve issue

**Comment by Daniel15** [comment] 2016-11-26 20:33
Thanks for the info! Adding the public key is part of the installation instructions at https://yarnpkg.com/en/docs/install#linux-tab, so I'm going to close this issue.

**Closed by Daniel15** 2016-11-26 20:33 UTC
Labels: needs clarification, needs confirmation

**Comment by Kyr** [comment] 2016-11-29 06:42
not so @Daniel15, I install yarn before following the instructions without any problems, but there was a issue with the key a few days ago during an update via apt.

**Comment by Daniel15** [comment] 2016-11-29 06:44
Hmm strange. We've always used the same GPG key for releases so I'm not sure why it didn't work.

**Comment by michaelbaudino** [comment] 2016-12-01 15:46
@Daniel15 I can confirm that I previously successfully installed Yarn via `apt` (like around 20th~25th of October, it was version `0.16.1`) and I'm now seeing the exact same error when running `apt-get update`.

Is there anything we can do to provide more information?

**Comment by terotil** [comment] 2016-12-01 20:21
@Daniel15 I'm also able to confirm

```
tero@fasaani:~$ sudo apt-key list
[sudo] password for tero: 
/etc/apt/trusted.gpg
--------------------
[...]
pub   4096R/86E50310 2016-10-05
uid                  Yarn Packaging <yarn@dan.cx>
sub   4096R/D50AF136 2016-10-05
sub   4096R/9D41F3C3 2016-10-05 [expires: 2017-10-05]
[...]
tero@fasaani:~$ sudo LC_ALL=C apt-get update
[...]
Fetched 37.4 kB in 4s (8949 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.yarnpkg.com stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C2130DFD2497F5

W: Failed to fetch http://dl.yarnpkg.com/debian/dists/stable/InRelease  

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

I did a bit of investigative work.  This is what I have in my apt repo keyring

```
tero@fasaani:~$ sudo gpg --list-packets /etc/apt/trusted.gpg
[...]
:public key packet:
	version 4, algo 1, created 1475645338, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 1646B01B86E50310
:user ID packet: "Yarn Packaging <yarn@dan.cx>"
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645338, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 79 d9
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	data: [4093 bits]
:trust packet: flag=00 sigcache=03
:public sub key packet:
	version 4, algo 1, created 1475645338, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 02820C39D50AF136
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645338, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 14 51
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	data: [4095 bits]
:trust packet: flag=00 sigcache=03
:public sub key packet:
	version 4, algo 1, created 1475645400, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: D101F7899D41F3C3
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645400, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 06 57
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 02)
	hashed subpkt 9 len 4 (key expires after 1y0d0h0m)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	subpkt 32 len 540 (signature: v4, class 0x19, algo 1, digest algo 8)
	data: [4096 bits]
:trust packet: flag=00 sigcache=03
```

And this is what I got when I downloaded the pubkey just a minute ago

```
tero@fasaani:~$ gpg --list-packets pubkey.gpg
:public key packet:
	version 4, algo 1, created 1475645338, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 1646B01B86E50310
:user ID packet: "Yarn Packaging <yarn@dan.cx>"
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645338, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 79 d9
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 6 (pref-sym-algos: 9 8 7 3 2 1)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	data: [4093 bits]
:public sub key packet:
	version 4, algo 1, created 1475645338, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 02820C39D50AF136
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645338, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 14 51
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	data: [4095 bits]
:public sub key packet:
	version 4, algo 1, created 1475645400, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: D101F7899D41F3C3
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1475645400, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 06 57
	hashed subpkt 2 len 4 (sig created 2016-10-05)
	hashed subpkt 27 len 1 (key flags: 02)
	hashed subpkt 9 len 4 (key expires after 1y0d0h0m)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	subpkt 32 len 540 (signature: v4, class 0x19, algo 1, digest algo 8)
	data: [4096 bits]
:public sub key packet:
	version 4, algo 1, created 1477786487, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: 46C2130DFD2497F5
:signature packet: algo 1, keyid 1646B01B86E50310
	version 4, created 1477786487, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 04 2a
	hashed subpkt 2 len 4 (sig created 2016-10-30)
	hashed subpkt 27 len 1 (key flags: 02)
	subpkt 16 len 8 (issuer key ID 1646B01B86E50310)
	subpkt 32 len 540 (signature: v4, class 0x19, algo 1, digest algo 8)
	data: [4095 bits]
```

Issuer key ID matches, but sub key packet keyids don't. I don't have sufficient understanding to tell exactly what's wrong here, but clearly apt is expecting key with id `46C2130DFD2497F5`, which appears to be missing from my `/etc/apt/trusted.gpg` but exists in the currently distributed `pubkey.gpg`.  (and yes, I did `sudo gpg --list-packets /etc/apt/trusted.gpg | grep 46C2130DFD2497F5` which didn't match anything)

**Comment by terotil** [comment] 2017-01-15 15:13
I'm still getting `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C2130DFD2497F5`. I have previously successfully added Yarn key and `apt-get update` used to work (and not complain). Assuming what @Daniel15 says 

> We've always used the same GPG key for releases

is correct, the question remains: Which one was signed by somebody else: the yarn I originally installed, or the one my apt currently tries to pull in?

This seems pretty serious. Or have I somehow understood something royally wrong here?

**Comment by Daniel15** [comment] 2017-01-16 02:48
Thanks @terotil, I see what's happening now. I just don't know **why** it's happening. 9D41F3C3 is the subkey for stable releases, while FD2497F5 is the subkey for nightly releases. The key for nightly releases was added after the initial release of Yarn.

In theory that shouldn't matter as you're not using nightly builds, but in reality It looks like stable releases are now being signed with the key used for nightly releases. I don't know why that's happening, as it's not configured that way (see https://github.com/yarnpkg/releases/blob/gh-pages/debian-source/add-deb.sh#L25). It might have happened when we switched from Reprepro to Aptly.

**Comment by terotil** [comment] 2017-01-16 05:30
That explains why I don't have FD2497F5, since it was not in `/debian/pubkey.gpg` originally, but was added later on.  Thanks for the clarification!

ps. Just shooting in the dark with lots of ifs here, but could it be that for some odd reason (don't know why) aptly does not see that `-gpg-key` flag and uses default key, which happens to be nightly (don't know if it is)?

**Comment by shashankKeshava** [comment] 2017-01-27 10:47
I'm facing the same issue. How do I install yarn on my Ubuntu PC can any one share the steps?

**Comment by Daniel15** [comment] 2017-01-30 06:18
> How do I install yarn on my Ubuntu PC can any one share the steps?

Did you try the instructions at https://yarnpkg.com/en/docs/install#linux-tab?

**Comment by shashankKeshava** [comment] 2017-01-30 06:23
@Daniel15 I've followed all the instructions when I try to run `sudo apt-get update && sudo apt-get install yarn` thats when I face `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY `error

**Comment by Daniel15** [comment] 2017-01-30 06:28
@shashankKeshava Did you add the public key?

```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
```

**Comment by shashankKeshava** [comment] 2017-01-30 06:50
Yes @Daniel15  I've added the public key.
After executing 
`sudo apt-get update && sudo apt-get install yarn`

I get the following error:
`W: Failed to fetch http://ppa.launchpad.net/upubuntu-com/office/ubuntu/dists/trusty/main/source/Sources  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/upubuntu-com/office/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://ppa.launchpad.net/upubuntu-com/office/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

**Comment by Daniel15** [comment] 2017-01-30 06:51
@shashankKeshava That's related to whatever `http://ppa.launchpad.net/upubuntu-com/office/` is, not Yarn. You should remove that repo if it doesn't work properly - It'll be somewhere in `/etc/apt/sources.list` or `/etc/apt/sources.list.d/`.

**Comment by shashankKeshava** [comment] 2017-01-30 07:04
@Daniel15 you where right yarn is successfully installed after I removed upubuntu. Thank You

**Comment by staabm** [comment] 2017-04-24 14:40
same here...

```
mstaab@mst16:/usr$ sudo apt-get update && sudo apt-get install yarn
Ign:1 https://dl.yarnpkg.com/debian stable InRelease
Ign:2 https://dl.yarnpkg.com/debian stable Release
Ign:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
Ign:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
Ign:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
Ign:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
Ign:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
Fehl:3 https://dl.yarnpkg.com/debian stable/main amd64 Packages
  Received HTTP code 403 from proxy after CONNECT
Ign:4 https://dl.yarnpkg.com/debian stable/main i386 Packages
Ign:5 https://dl.yarnpkg.com/debian stable/main all Packages
Ign:6 https://dl.yarnpkg.com/debian stable/main Translation-de_DE
Ign:7 https://dl.yarnpkg.com/debian stable/main Translation-de
Ign:8 https://dl.yarnpkg.com/debian stable/main Translation-en
OK:9 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
OK:10 http://de.archive.ubuntu.com/ubuntu xenial InRelease
OK:11 http://security.ubuntu.com/ubuntu xenial-security InRelease
OK:12 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
OK:13 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
OK:14 http://packages.blackfire.io/debian any InRelease
Paketlisten werden gelesen... Fertig
W: The repository 'https://dl.yarnpkg.com/debian stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Fehlschlag beim Holen von https://dl.yarnpkg.com/debian/dists/stable/main/binary-amd64/Packages  Received HTTP code 403 from proxy after CONNECT
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.
```

**Comment by Daniel15** [comment] 2017-05-07 04:38
@staabm, that sounds like an issue with whatever proxy you're using:

> Received HTTP code 403 from proxy after CONNECT

**Comment by hammer65** [comment] 2017-10-06 14:15
I'm getting this too. My cert is fine and if it was the cert wouldn't it fail for all the the Yarn urls? The only one which seems to have an issue is `https://dl.yarnpkg.com/debian stable Release`. I followed the instructions to install yarn and this isn't a problem with the software. I'm now trying to install something with RVM and can't do it because apt-get update errors out.

**Comment by staabm** [comment] 2017-10-06 14:53
in my setup it was a problem with whitelisting of certain urls in a apt-mirror we use internally.

**Comment by terotil** [comment] 2019-01-31 09:50
> https to http solve issue

That's like "fixing" broken test by removing it. Or "fixing" uncomfortable seat belt by not using it at all.
