### ISSUE TITLE
error while running 'yarn install

### ISSUE THREAD

**Issue by pdeva** [yarnpkg/yarn#1547] opened 2016-10-29 06:29 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
see error msg when running `yarn install`, goes away when run it second time.

**If the current behavior is a bug, please provide the steps to reproduce.**

do yarn install with info in log file.

**What is the expected behavior?**
should complete without error

**Please mention your node.js, yarn and operating system version.**
windows 10. yarn 0.16.1

```
F:\code\apmfrontend2>yarn install
yarn install v0.16.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occured, please open a bug report with the information provided in "F:\\code\\apmfrontend2\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
[yarn-error.zip](https://github.com/yarnpkg/yarn/files/559791/yarn-error.zip)

**Comment by joemcbride** [comment] 2016-10-29 07:53
I believe duplicate of #1285

**Comment by wyze** [comment] 2016-10-29 23:53
Duplicate of #1285. Thanks @joemcbride.

**Closed by wyze** 2016-10-29 23:53 UTC
