### ISSUE TITLE
yarn didn't remove tmp dir after process done

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/yarn#8863] opened 2022-07-30 22:34 UTC
https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/util/fs.js#L809

https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/util/execute-lifecycle-script.js#L41

`makeTempDir`

when run a yarn cmd it will create a tmp dir name like this

`yarn--1659219565508-0.33457343204584866`

and has follow file

```
node.cmd
yarn.cmd
```

but it didn't remove this tmp dir after done

this make we have super many old tmp dir exists in os temp
(for me is 4000+ )

should auto clean it after cmd is done

**Comment by RDIL** [comment] 2022-09-07 16:35
Duplicate of #8414

**Closed by RDIL** 2022-09-07 16:35 UTC
