### ISSUE TITLE
yarn --silent produces output on non-zero exit code

### ISSUE THREAD

**Issue by Wilfred** [yarnpkg/yarn#5440] opened 2018-03-02 11:39 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug: `--silent` behaves differently to `npm run`, and there does not seem to be a way of getting the `npm run --silent` behaviour with yarn.

**What is the current behavior?**
If the script specified in package.json errors, `yarn` summarises the exit code, and it doesn't seem to be possible to suppress this output.

**If the current behavior is a bug, please provide the steps to reproduce.**
Given the following command in my `package.json`:

```json
  "scripts": {
    "start": "node ./bin/www",
    "lint": "eslint ."
  },
```

```
$ yarn run -s lint

/Users/whughes/workspace/example_project/routes/cr.js
  88:7  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c eslint .
Directory: /Users/whughes/workspace/example_project
Output:
".
```

**What is the expected behavior?**

`npm` does not report the exit code when using `-s`:

```
$ npm run lint -s

/Users/whughes/workspace/example_project/routes/cr.js
  88:7  error  Unexpected console statement  no-console

✖ 1 problem (1 error, 0 warnings)
```

This is important for test runners and linters, where a non-zero exit code does not indicate an issue with the package.json, but that the developer needs to take some action.

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v8.9.4
$ yarn --version
1.5.1
$ uname -v
Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
```

**Comment by rally25rs** [comment] 2018-03-05 15:18
duplicate of #5359

**Closed by rally25rs** 2018-03-05 15:18 UTC
Labels: triaged
