### ISSUE TITLE
yarn.lock changes dependent on the existence of node_modules

### ISSUE THREAD

**Issue by kans** [yarnpkg/yarn#5391] opened 2018-02-22 01:40 UTC
To reproduce, run `yarn` twice with the following package.json:

```json
{
  "dependencies": {
    "mapbox-gl": "0.22.1"
  }
}
```

The diff:
```
@@ -468,13 +468,13 @@
   version "1.3.0"
   resolved "https://registry.yarnpkg.com/mapbox-gl-function/-/mapbox-gl-function-1.3.0.tgz#cee3d95750c189d45e83ab41a0a57fc2a8a509bc"

-mapbox-gl-shaders@mapbox/mapbox-gl-shaders#de2ab007455aa2587c552694c68583f94c9f2747:
+"mapbox-gl-shaders@github:mapbox/mapbox-gl-shaders#de2ab007455aa2587c552694c68583f94c9f2747":
   version "1.0.0"
   resolved "https://codeload.github.com/mapbox/mapbox-gl-shaders/tar.gz/de2ab007455aa2587c552694c68583f94c9f2747"
   dependencies:
     brfs "^1.4.0"

-mapbox-gl-style-spec@mapbox/mapbox-gl-style-spec#83b1a3e5837d785af582efd5ed1a212f2df6a4ae:
+"mapbox-gl-style-spec@github:mapbox/mapbox-gl-style-spec#83b1a3e5837d785af582efd5ed1a212f2df6a4ae":
   version "8.8.0"
   resolved "https://codeload.github.com/mapbox/mapbox-gl-style-spec/tar.gz/83b1a3e5837d785af582efd5ed1a212f2df6a4ae"
   dependencies:
```

node: 9.5
yarn: 1.3.2

**Comment by ggreer** [comment] 2018-02-22 01:49
Just fyi, the first run of `yarn install` will output a `yarn.lock` with `"mapbox-gl-shaders@github:mapbox/mapbox-gl-shaders#de2ab007455aa2587c552694c68583f94c9f2747":`. The second run will change that line to `mapbox-gl-shaders@mapbox/mapbox-gl-shaders#de2ab007455aa2587c552694c68583f94c9f2747:` (removes quotes and the github protocol).

**Comment by rally25rs** [comment] 2018-02-22 14:53
This looks familiar. I think this was reported once before, but I forget what came of it.. I'll see if I can find it...

**Comment by ggreer** [comment] 2018-02-22 17:36
Yes. That looks like the exact same issue. Feel free to close this one as a duplicate.

**Comment by rally25rs** [comment] 2018-02-23 13:49
Closing as duplicate of #4953

**Closed by rally25rs** 2018-02-23 13:49 UTC
Labels: triaged
