### ISSUE TITLE
Why yarn build node-gyp deps at each install?

### ISSUE THREAD

**Issue by sc0rp10** [yarnpkg/yarn#2916] opened 2017-03-14 15:55 UTC
Now yarn rebuild binary deps at each install that stole my time and heat my CPU.
Why yarn doing it?
```
$ yarn --version
0.21.3
$ cat package.json
{
  "name": "test",
  "dependencies": {
    "bcrypt": "^0.8.7"
  }
}
```
**What is the current behavior?**
Binary deps builds at each install.
**If the current behavior is a bug, please provide the steps to reproduce.**
```
rm -rf node_modules
yarn install # first node-gyp compilation. it's ok
rm -rf node_modules
yarn install # why does it run compilation again?
```
**What is the expected behavior?**
Cache built `.o` files at shared cache directory

**Comment by Daniel15** [comment] 2017-03-14 16:53
This is probably a duplicate of #932

**Comment by arcanis** [comment] 2017-04-28 17:21
Closing this as a duplicate of #932

**Closed by arcanis** 2017-04-28 17:21 UTC
