### ISSUE TITLE
Global binaries don't install on Fedora 24 

### ISSUE THREAD

**Issue by joseluisq** [yarnpkg/yarn#1371] opened 2016-10-22 17:21 UTC
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Global packages installation doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

I installed `yarn` package via `sudo dnf install yarn`

``` sh
~> echo $PATH
/usr/local/bin /usr/local/sbin /usr/bin /usr/sbin /home/joseluis/.composer/vendor/bin /home/joseluis/.composer/vendor/bin /home/joseluis/.node/bin /home/joseluis/.yarn/bin

~> yarn global add surge
yarn global v0.16.0
warning No license field
[1/4] Resolving packages...
warning surge > fstream-ignore > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed surge@0.18.0 with binaries:
      - surge
error An unexpected error occured, please open a bug report with the information provided in "/home/joseluis/.yarn-config/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

~> tail -n 4 /home/joseluis/.yarn-config/global/yarn-error.log

Trace: 
  Error: EACCES: permission denied, unlink '/usr/bin/surge'
      at Error (native)

```

**What is the expected behavior?**
Global binaries sould be executable.

**Please mention your node.js, yarn and operating system version.**

``` sh
~> yarn version
yarn version v0.16.0
~> node -v
v4.6.0
~> npm -v
2.15.9
~> cat /etc/fedora-release
Fedora release 24 (Twenty Four)
~> fish -v
fish, version 2.3.1
```

**Comment by frodri** [comment] 2016-10-22 23:09
Can confirm similar behavior in Windows 10, version 1607. I'm using node 4.5.0, along with yarn 0.16.0.

````
~> "yarn global add typescript" output

yarn global v0.16.0
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed typescript@2.0.3 with binaries:
      - tsc
      - tsserver
error An unexpected error occured, please open a bug report with the information
 provided in "C:\\Users\\USERNAME\\AppData\\Local\\Yarn\\config\\global\\yarn-e
rror.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this c
ommand.


~> last 4 lines of yarn-error.log

Trace: 
  Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\tsc'
      at Error (native)
````

**Comment by Daniel15** [comment] 2016-10-23 08:06
Interesting... Two issues I see here:
1. Yarn should not be putting files in `/usr/bin`, only `/usr/local/bin`. `/usr/bin` is **only** for packages managed by the system (apt-get, yum, dnf, etc.)
2. Yarn should not try putting files in `/usr/bin` or  `/usr/local/bin` when the user doesn't have permission to write there. It should probably just use `~/.yarn/bin` or something similar.

I think running `sudo yarn global add` should work though.

Does "dnf install yarn" use our package repo? I'm not very familiar with Fedora, but it looks like `dnf` is an updated version of `yum`?

**Comment by paulriddle** [comment] 2016-10-23 12:47
> I think running sudo yarn global add should work though.I think running sudo yarn global add should work though.

Does not. I'm not using Fedora though, I'm using ArchLinux and installed `yarn` from the [AUR](https://aur.archlinux.org/packages/yarn/) and added `$HOME/.yarn/bin` to the `$PATH`. I also had to manually create these directories to stop my shell from complaining that such directory doesn't exist. The shell is `fish 2.3.1`, as @joseluisq's. the Now I'm doing:
```
> sudo yarn global add create-react-app
yarn global v0.16.1
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "linux" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed create-react-app@0.6.0 with binaries:
      - create-react-app
Done in 12.43s.

> which create-react-app
which: no create-react-app in (bin/:/home/fixnum/.rbenv/bin/:/home/fixnum/gocode/bin:/home/fixnum/bin/:/home/fixnum/.yarn/bin:/home/fixnum/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```
Naturally, the first time I tried to install without `sudo` and I got the following error (which wasn't displayed in the terminal by the way, only in the log file):
```
Trace: 
  Error: EACCES: permission denied, symlink '../../home/fixnum/.yarn-config/global/node_modules/.bin/create-react-app' -> '/usr/bin/create-react-app'
      at Error (native)
```
Why `../../` at the beginning?

`node` is `6.9.1`, I don't have `npm` yet.

> Yarn should not try putting files in `/usr/bin` or `/usr/local/bin` when the user doesn't have permission to write there. It should probably just use `~/.yarn/bin` or something similar.

I'm wondering why not simply use `~/.yarn/bin` for all global binaries and never even try to use `/usr/local/bin`?

**Comment by paulriddle** [comment] 2016-10-23 12:50
Relevant issue https://github.com/yarnpkg/yarn/issues/648

**Comment by onemen** [comment] 2016-10-23 13:23
I get the same permission error In Window 10 when '''yarn global add''' try to link bins to
```yarn global bin''' which is '''C:\Program Files\nodejs```
I reported #1226

**Comment by joseluisq** [comment] 2016-10-24 02:10
> Interesting... Two issues I see here:
> 1. Yarn should not be putting files in /usr/bin, only /usr/local/bin. /usr/bin is only for packages managed by the system (apt-get, yum, dnf, etc.)
> 2. Yarn should not try putting files in /usr/bin or /usr/local/bin when the user doesn't have permission to write there. It should probably just use ~/.yarn/bin or something similar.
> 
> I think running sudo yarn global add should work though.
> 
> Does "dnf install yarn" use our package repo? I'm not very familiar with Fedora, but it looks like dnf is an updated version of yum?

@Daniel15 
Yep, `dnf` is the next version of `yum` it operates similarly. (Compatible with `rpm` packages too)

In any case, `yarn` should allow to set a custom binary path somehow. Maybe similar to npm: 
```sh
~> cat ~/.npmrc
prefix = /home/my-local-user/.node/bin
```

**Comment by tonico** [comment] 2016-10-24 09:10
Adding `export PREFIX=~/.local` to my .bash_profile (followed by `source ~/.bash_profile`) fixed it for me. Yarn now links binaries to .local/bin, which is in my PATH.

**Comment by paulriddle** [comment] 2016-10-25 15:14
I briefly went over the issues and found some of the related ones: https://github.com/yarnpkg/yarn/issues/1389, https://github.com/yarnpkg/yarn/issues/1388, https://github.com/yarnpkg/yarn/issues/1321, https://github.com/yarnpkg/yarn/issues/1226, https://github.com/yarnpkg/yarn/issues/1194, https://github.com/yarnpkg/yarn/issues/1151, https://github.com/yarnpkg/yarn/issues/1060, https://github.com/yarnpkg/yarn/issues/1029, https://github.com/yarnpkg/yarn/issues/927#issuecomment-253422378, https://github.com/yarnpkg/yarn/issues/630.

**Comment by andyyou** [comment] 2016-11-04 00:54
I use nvm for my node environment. When I install a new version of node then `yarn global` does't install pkg correctly

btw I use `brew` to install yarn.

The information as follow

```
System Software Overview:

      System Version: macOS 10.12.1 (16B2555)
      Kernel Version: Darwin 16.1.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

![](http://i.imgur.com/9qgTdJU.png)

**Comment by balthild** [comment] 2016-11-15 17:20
Same issue. I use macOS. I use homebrew to install node and yarn.

```
$ yarn global add vue-cli
yarn global v0.16.1
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Installed vue-cli@2.5.0 with binaries:
      - vue
      - vue-init
      - vue-list
✨  Done in 1.75s.

$ vue
zsh: command not found: vue

$ yarn global bin                     
/usr/local/Cellar/node/7.1.0/bin

$ /usr/local/Cellar/node/7.1.0/bin/vue

  Usage: vue <command> [options]


  Commands:

    init        generate a new project from a template
    list        list available official templates
    help [cmd]  display help for [cmd]

  Options:

    -h, --help     output usage information
    -V, --version  output the version number
```

**Comment by indolering** [comment] 2017-01-21 03:48
Shouldn't this be marked as dupe of #1194?

**Comment by joseluisq** [comment] 2017-02-10 15:32
This issue is solved now in `v0.19.1`

For example I have achieved to install `surge` globally. 
Here log (I have `~/.npmrc` prefix cofigured with my local path):
```sh
~> sudo dnf install yarn
~> yarn version  
0.19.1
~> cat ~/.npmrc
prefix=/home/joseluis/.node
~> yarn config get prefix
/home/joseluis/.node
~> yarn global bin
/home/joseluis/.node/bin
~> yarn global add surge
yarn global v0.19.1
warning No license field
[1/4] Resolving packages...
warning surge > fstream-ignore > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning surge > request > node-uuid@1.4.7: use uuid module instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "surge@0.18.0" with binaries:
      - surge
warning No license field
Done in 3.04s.
~> surge --version
0.18.0
```

__Yarn__ reads the prefix path in `~/.npmrc` file:

```sh
~> npm config get prefix
/home/joseluis/.node
~> yarn config get prefix
/home/joseluis/.node
```

Deleting prefix...

```sh
~> sed -i '/prefix=/d' ~/.npmrc
~> npm config get prefix
/usr
~> yarn config get prefix
undefined
```

**Closed** 2017-02-10 15:34 UTC
Labels: bug
