### ISSUE TITLE
"yarn add optional" won't install the package

### ISSUE THREAD

**Issue by dceddia** [yarnpkg/yarn#1662] opened 2016-11-03 17:00 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`yarn add optional` complains with this error:

    error Missing list of packages to add to your project.

It seems to be short-circuiting the "add" process, because of the package name maybe? If I manually add this line to package.json and run `yarn` it installs the package:

    "optional": "*"

And yep, this is actually a library: https://github.com/tony-o/node-optional

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn add optional` inside a project with a package.json.

**What is the expected behavior?**
It should install the package.

**Please mention your node.js, yarn and operating system version.**

node: v6.9.1
yarn: 0.16.1
OS:  macOS Sierra (also happens on Alpine Linux inside a Docker container)

**Comment by wyze** [comment] 2016-11-03 17:19
Duplicate of #1609.

**Closed by wyze** 2016-11-03 17:19 UTC
