### ISSUE TITLE
`yarn -h` is  freeze when cache dir is not exists or write-able

### ISSUE THREAD

**Issue by bluelovers** [yarnpkg/yarn#8261] opened 2020-07-28 05:55 UTC
### Bug description

**Command**

```sh
yarn -h
```

npm will show error message
but yarn will freeze

**What is the current behavior?**

**What is the expected behavior?**

**Steps to Reproduce**

1. set `cache` / `cache-folder` to a invalid path
2. run `yarn -h`

**Environment**

- Node Version: `v14.6.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: windows 10

**Comment by paul-soporan** [comment] 2021-01-03 17:55
Closing as I can't reproduce this, Yarn also shows an error message.

**Closed by paul-soporan** 2021-01-03 17:55 UTC
