### ISSUE TITLE
yarn keep asking to install package that was first typed with wrong version

### ISSUE THREAD

**Issue by bogdancar** [yarnpkg/yarn#4101] opened 2017-08-04 22:21 UTC
**Do you want to request a *feature* or report a *bug*?**

Report bug.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Tried adding version 3.5.3 of ionic with `yarn global add ionic@3.5.3` which does not exist. Yarn prompts that version does not exist and give me the list of available version to choose. I choose one, it install, then at each command after, like `yarn global list` will prompt me to choose from the list. This is always happening until you remove ionic.

**What is the expected behavior?**
Looks like the wrong version is added to the `yarn.lock` and so the process keep repeating. The expected behavior will be to install the chosen version from the list, save that version on `yarn.lock` and not ask each time for reinstalling.

**Please mention your node.js, yarn and operating system version.**
node 7.9.0
yarn 0.27.5
windows 10

**Comment by Ionaru** [comment] 2017-08-07 12:41
Duplicate of #3817, will be fixed in Yarn 1.0

**Comment by BYK** [comment] 2017-08-07 12:49
Duplicate of #3817 as @Ionaru mentioned.

**Comment by BYK** [comment] 2017-08-07 12:49
Weird that GitHub not marking this as a duplicate even after the comments.

**Closed** 2017-08-07 12:48 UTC
