### ISSUE TITLE
yarn outdated can't find @types/* packages

### ISSUE THREAD

**Issue by antage** [yarnpkg/yarn#983] opened 2016-10-13 09:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`yarn outdated` can't find `@types/react` package (or any `@types/*` package).

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ yarn add @types/react
$ yard outdated
yarn outdated v0.15.1
error https://registry.yarnpkg.com/@types/react: Not found
    at Request.params.callback [as _callback] (/usr/lib/node_modules/yarn/lib/util/request-manager.js:273:18)
    at Request.self.callback (/usr/lib/node_modules/yarn/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/yarn/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
info Visit http://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**What is the expected behavior?**
Yarn must check version for all packages and for `@types/*` too.

**Please mention your node.js, yarn and operating system version.**
Linux/Debian 8 amd64
Node 6.7
Yarn 0.15.1

**Comment by tallaxes** [comment] 2016-10-13 20:08
Same with e.g. @angular/core, @angular/forms, etc.  Something about the @ sign?

**Comment by truckingsim** [comment] 2016-10-13 20:35
@antage @tallaxes this has been reported already: https://github.com/yarnpkg/yarn/issues/620

**Comment by kittens** [comment] 2016-10-15 19:17
Dupe of #620.

**Closed by kittens** 2016-10-15 19:17 UTC
Labels: bug
