### ISSUE TITLE
The documentation for cli command `yarn workspace` is missing

### ISSUE THREAD

**Issue by chengjianhua** [yarnpkg/yarn#4714] opened 2017-10-15 10:04 UTC
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
```bash
yarn workspace
```

Output

```
yarn workspace v0.28.4
error Missing workspace name.
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

But the documentation link https://yarnpkg.com/en/docs/cli/workspace for this command is not existing.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

There should be a detailed documentation for cli command `yarn workspace` while the introduction for feature `workspace` (https://yarnpkg.com/en/docs/workspaces#search) is existing.

**Please mention your node.js, yarn and operating system version.**

node | yarn | operating system
------ | ------ | -------
8.5.0  | 0.28.4 | macOS Sierra 10.12.6

**Comment by BYK** [comment] 2017-10-16 09:59
Duplicate of https://github.com/yarnpkg/website/issues/563

**Closed by BYK** 2017-10-16 09:59 UTC

**Comment by yyynnn** [comment] 2020-07-21 21:23
Still getting this error in giltab ci runner 

```bash
 @scope/package: Done in 0.06s.
 @scope/package: yarn workspace v1.22.4
 @scope/package: error Missing command name.
 @scope/package: info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```
