### ISSUE TITLE
`yarn info . version` not working as expected

### ISSUE THREAD

**Issue by timm-gs** [yarnpkg/yarn#4800] opened 2017-10-30 08:44 UTC
Tested with `yarn` `1.1.0` and `1.2.1`

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
```sh

$ yarn init
yarn init v1.1.0
question name (test):
question version (1.0.0): 1.0.0-test
[...]
success Saved package.json
✨  Done in 15.41s.

$ yarn info . name
yarn info v1.1.0
test
✨  Done in 0.16s.


$ yarn info . version
yarn info v1.1.0
0.6.0
✨  Done in 0.17s.


$ yarn version -s --no-git-tag-version --new-version prerelease
$ yarn info . version
yarn info v1.1.0
0.6.0
✨  Done in 0.17s.

$ cat package.json
{
  "name": "test",
  "version": "1.0.0-test.0",
  "main": "index.js",
  "license": "MIT"
}
```

**What is the expected behavior?**

I would expect `yarn` to report the version actually specified in `package.json`, just as it did for the name. So first `1.0.0-test` and then `1.0.0-test.0` instead of `0.6.0` both times.

**Please mention your node.js, yarn and operating system version.**

$ uname -a
Darwin MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ node -v
v6.11.5
$ yarn -v
1.2.1

**Comment by timm-gs** [comment] 2017-10-30 10:14
Ah, after some investigating I found that it returns the version info from NPM registry, i.e. https://www.npmjs.com/package/test in this case.

So it seems this is a duplicate of https://github.com/yarnpkg/yarn/issues/1873 then.

**Comment by timm-gs** [comment] 2017-10-30 10:16
But maybe it should still be tracked separately, because I think there is a difference in expectation when using `.` as a parameter, that it should _really_ be using the local file.

(As `yarn info . version` would only work in the package's directory, whereas `yarn info test version` works in every directory)

**Comment by timm-gs** [comment] 2017-10-30 10:18
Or is there any other way to retrieve the current version with yarn?

I was looking for to do this in a shell script an fell back to using the following for now:

```sh
node -e "console.log(require('./package.json').version);"
```

Which I guess is also fine. Why would one expect `yarn` to be a general `package.json` manipulation utility.

**Comment by langri-sha** [comment] 2017-10-30 11:12
I'm guessing this isn't the right way to do things and it can only help with your immediate dependencies, but using `-E` to pin everything to an exact version works for me at the moment 🤷‍♂️.

**Comment by BYK** [comment] 2017-10-31 10:09
`node -p "require('./package.json').version"` is even shorter :)

I'm closing this in as a duplicate of #1873 but feel free to reopen if you think they are different.

**Closed by BYK** 2017-10-31 10:09 UTC
