### ISSUE TITLE
Its again and again and again: rror: EACCES: permission denied

### ISSUE THREAD

**Issue by sergey-koretsky** [yarnpkg/yarn#2756] opened 2017-02-22 18:15 UTC
> yarn --version
0.20.3

>vue --version
2.8.1

> vue init

`
fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/usr/local/share/.config/yarn/global/node_modules/arr-flatten/index.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/arr-diff/index.js:10:15)
    at Module._compile (module.js:571:32)
`

yarn is ***** just back to npm

**Comment by fizzvr** [comment] 2017-02-23 07:40
Fix your folder permissions /usr/local/share

**Comment by japsu** [comment] 2017-03-08 09:07
Duplicate of #1143 perhaps?

**Comment by rally25rs** [comment] 2017-11-11 02:11
This is a pretty old version of Yarn now. Going to close it for now assuming it is a duplicate of #1143 and should be fixed in latest. If this is not the case and still not working in Yarn 1.3 please let us know and we will reopen this issue.

**Closed by rally25rs** 2017-11-11 02:11 UTC
