### ISSUE TITLE
Yarn fails to install namespaced package

### ISSUE THREAD

**Issue by mririgoyen** [yarnpkg/yarn#5913] opened 2018-05-30 14:06 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Yarn fails to install a namespaced package in Node 10.3.0.

**If the current behavior is a bug, please provide the steps to reproduce.**

On Node 10.3, running yarn blows up on a specific namespaced package that I can manually install with NPM. This problem does not occur in Node 10.2.1.

```
verbose 19.197 Request "https://registry.yarnpkg.com/@babel%2fcode-frame" finished with status code 503.
verbose 19.199 Error: Received malformed response from registry for undefined. The registry may be down.
at MessageError.ExtendableBuiltin (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:272:123)
    at Function.<anonymous> (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:116:14
    at new Promise (<anonymous>)
    at new F (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:23451:28)
    at Function.<anonymous> (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:95:12)
    at Function.findVersionInRegistryResponse (/Users/mirigoyen/.nvm/versions/node/v10.3.0/lib/node_modules/yarn/lib/cli.js:52217:19)
```

When going to that URL above, it takes a few moments and then says "No frontdoor hosts available".

**What is the expected behavior?** All packages install correctly.

**Please mention your node.js, yarn and operating system version.**

Node 10.3.0
Yarn 1.7.0
macOS

**Comment by BYK** [comment] 2018-05-30 15:24
I think this is a duplicate of #5908.

**Closed as completed** 2018-05-30 15:25 UTC
Labels: triaged
