### ISSUE TITLE
registry.yarnpg.com is down, but status.yarnpkg.com is green

### ISSUE THREAD

**Issue by georgesequeira** [yarnpkg/yarn#5932] opened 2018-06-05 17:20 UTC
At 2018-06-05 17:19 UTC

Running 

`while curl -I https://registry.yarnpkg.com/ ; do :; done`

Shows intermittent 503s:

```
HTTP/2 200
date: Tue, 05 Jun 2018 17:13:51 GMT
content-type: text/plain
content-length: 4
set-cookie: __cfduid=dc18ec800fc64ed09ef1d844d6946fee61528218830; expires=Wed, 05-Jun-19 17:13:50 GMT; path=/; domain=.registry.yarnpkg.com; HttpOnly
cache-control: must-revalidate
cf-ray: 426445abfe7c2180-EWR
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare


HTTP/2 503
date: Tue, 05 Jun 2018 17:14:04 GMT
content-type: text/plain;charset=UTF-8
content-length: 28
set-cookie: __cfduid=d1ef1d891ac86c43ea1d759b1891cf9801528218831; expires=Wed, 05-Jun-19 17:13:51 GMT; path=/; domain=.registry.yarnpkg.com; HttpOnly
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 426445b129e421ce-EWR
...
....

```

But status.yarnpkg.com lists the registry as operational.

Currently https://status.npmjs.org/ shows a healthy status.

**Comment by stringbeans** [comment] 2018-06-05 17:29
i am also running into 503 errors occassionally when installing packages... for example: 

```
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/node-pre-gyp/-/node-pre-gyp-0.6.36.tgz: Request failed \"503 Service Unavailable\"".
```

**Comment by BYK** [comment] 2018-06-05 17:53
Works for me here from London. CloudFlare shows some reroutes but says things are fine in general: https://www.cloudflarestatus.com/

Don't really know what might be happening.

**Comment by stringbeans** [comment] 2018-06-05 18:56
strangely enough we are not experiencing the issues locally (we're in Vancouver Canada) but in our circleCI builds we're run into the 503 errors about 50% of the time

**Comment by Dog** [comment] 2018-06-05 19:17
I'm having the same experience with BuildKite in Seattle.

**Comment by Dog** [comment] 2018-06-05 19:18
I'm having the same experience in Seattle.

**Comment by brianleach** [comment] 2018-06-05 19:42
Getting 503 service unavailable on CircleCI.

```
#!/bin/bash -eo pipefail
cd www && yarn install
yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/spdy/-/spdy-3.4.7.tgz: Request failed \"503 Service Unavailable\"".
```

**Comment by anthonyroach** [comment] 2018-06-05 19:54
I'm seeing the same problem on a Jenkins slave running in us-east-1 of AWS. Interestingly, I do not see it when running locally from Indianapolis, IN:

```
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/regl-error2d/-/regl-error2d-2.0.4.tgz: Request failed \"503 Service
```

**Comment by arist0tl3** [comment] 2018-06-05 20:11
Confirmed on our CircleCI. Seems random, though I haven't seen the same package fail twice. Here are the latest three:

```
yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-plugin-syntax-exponentiation-operator/-/babel-plugin-syntax-exponentiation-operator-6.13.0.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1

yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/pinkie-promise/-/pinkie-promise-2.0.1.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1

yarn install v0.24.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/map-keys-deep-lodash/-/map-keys-deep-lodash-1.2.0.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/circleci/repo/server/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
Exited with code 1
```

**Comment by ahunter-pythian** [comment] 2018-06-05 20:37
Same issue here:
```
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/debug/-/debug-2.6.1.tgz: Request failed \"503 Service Unavailable\"".
```
```
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
merror An unexpected error occurred: "https://registry.yarnpkg.com/raw-body/-/raw-body-2.2.0.tgz: Request failed \"503 Service Unavailable\"".
```
and so on intermittently

**Comment by BYK** [comment] 2018-06-05 20:43
Reached out to CloudFlare, awaiting response.

**Comment by bluepichu** [comment] 2018-06-05 20:48
I've been having a similar issue in a BitBucket Pipeline, but interestingly, with the `--verbose` flag set `yarn install` _always_ succeeds.  It seems like the added delay from all of the printing is preventing whatever the issue is from occurring.

**Comment by anthonyroach** [comment] 2018-06-05 20:50
I was able to work around the problem and get rid of the 503s by changing `https://registry.yarnpkg.com` to `https://registry.npmjs.org/` in `yarn.lock`. This suggests that the problem is not the npmjs registry, but rather the yarnpkg registry.

**Comment by BYK** [comment] 2018-06-05 20:58
>I was able to work around the problem and get rid of the 503s by changing https://registry.yarnpkg.com to https://registry.npmjs.org/ in yarn.lock. This suggests that the problem is not the npmjs registry, but rather the yarnpkg registry.

@anthonyroach that is very unlikely since they are both behind CloudFlare and point to the same servers. I'd say this is just coincidence.

**Comment by Dog** [comment] 2018-06-05 21:04
I'm starting to see the failed builds resolving.

**Comment by DanielJoyce** [comment] 2018-06-05 21:11
We currently have codeship builds failing due to this

```
2018-06-05 21:06:23
yarn install v1.5.1
2018-06-05 21:06:23
[1/4] Resolving packages...
2018-06-05 21:06:23
[2/4] Fetching packages...
2018-06-05 21:06:38
error An unexpected error occurred: "https://registry.yarnpkg.com/balanced-match/-/balanced-match-1.0.0.tgz: Request failed \"503 Service Unavailable\"".
```

**Comment by Dog** [comment] 2018-06-05 21:16
FWIW I am no longer experiencing this.

All failed builds have passed, and no new failed builds yet.

**Comment by Gianfranco97** [comment] 2018-06-05 22:20
I also have the same problem in my CircleCI integration, everything worked yesterday but today I let it work.

![captura de pantalla 2018-06-05 a la s 6 17 30 p m](https://user-images.githubusercontent.com/19965590/41005793-ea2aab14-68ec-11e8-80c2-a160f1dc31e4.png)

```
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@sonarwhal/rule-http-compression/-/rule-http-compression-4.0.2.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/repo/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1
```

**Comment by benjyblack** [comment] 2018-06-06 01:53
We are experiencing this still.

```bash
error An unexpected error occurred: "https://registry.yarnpkg.com/pug-lexer/-/pug-lexer-4.0.0.tgz: Request failed \"503 Service Unavailable\"".
```

**Comment by luislezcair** [comment] 2018-06-06 13:35
I'm experiencing the same problem when deploying to Heroku. It fails with random packages. 

It works fine locally.

**Comment by geropl** [comment] 2018-06-06 13:36
We experience the same issue every other day, always around 3-5pm CET, in our own Jenkins-on-Docker build pipeline.
Any robust work around?

**Comment by wichert** [comment] 2018-06-06 13:54
We're seeing this happen 100% of the time as of today with requests coming from CircleCI.

**Comment by zwade** [comment] 2018-06-06 13:58
Following up on this, we've been having the same issue running both locally (under Docker) and on Bitbucket's pipelines. Solving the local issue, we found that the error only occurred when performing multiple parallel installs and that building them in sequence was sufficient to prevent 503's. I'm not sure this helps, but it backs up what @bluepichu was saying about needing to slow the install down.

**Comment by lookapanda** [comment] 2018-06-06 14:05
Same issue, our GitLab runner runs on AWS.

**Comment by ganglio** [comment] 2018-06-06 14:14
I'm experiencing the same issue in London. Building from the Docker container fails while building locally works.

**Comment by WebMex** [comment] 2018-06-06 14:15
The same issue for our Gitlab runner in Frankfurt. Verbose didn't help

**Comment by yv3s** [comment] 2018-06-06 14:17
Having the same issue in Paris

`[2/4] Fetching packages...
remote:        error An unexpected error occurred: "https://registry.yarnpkg.com/uglifyjs-webpack-plugin/-/uglifyjs-webpack-plugin-1.2.3.tgz: Request failed \"503 Service Unavailable\"".
remote:        info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_3466b5d056c6bb38c5e354a0a5942555/yarn-error.log".
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`

**Comment by tjbrez** [comment] 2018-06-06 14:21
Seeing the same issue in Cleveland. Works locally, but CircleCI fails 90% of the time.

![image](https://user-images.githubusercontent.com/8741744/41044024-400499f6-6973-11e8-8997-727ac1d39716.png)

**Comment by HoughIO** [comment] 2018-06-06 15:00
```
An unexpected error occurred: \"https://registry.yarnpkg.com/css-select/-/css-select-1.2.0.tgz: Request failed \\\"503 Service Unavailable
```

As of 11:00AM EST 6/6/2018

**Comment by rvirani1** [comment] 2018-06-06 15:02
We're getting this same error most of the time running in Amazon CodeBuild in us-east-1

**Comment by DanielJoyce** [comment] 2018-06-06 15:11
Outage resolved for us for now.

**Comment by jayschwa** [comment] 2018-06-06 15:12
We're still getting this error in Amazon's us-west-2.

**Comment by efournival** [comment] 2018-06-06 15:34
Still not resolved under CircleCI:
```yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/chalk/-/chalk-2.4.1.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/root/moonapp/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exited with code 1```

**Comment by rufushonour** [comment] 2018-06-06 15:58
npm are now publicly acknowledging the issue: https://status.npmjs.org/incidents/qxj3kdzw4jrg

**Comment by draconteus** [comment] 2018-06-06 16:02
Temporarily hanging to NPM and https://registry.npmjs.org/ can solve the problem.

**Comment by wcmonty** [comment] 2018-06-06 16:44
We added some retry logic in our build processes:
```bash
for i in {1..4}; do yarn install && break; done && yarn install
```
We try to install up to 4 times, then install a final time to make sure that we return the right status code.

**Comment by leff** [comment] 2018-06-06 17:28
NPM says they fixed it but we're still seeing 503 errors from registry.yarnpkg.com

**Comment by rvirani1** [comment] 2018-06-06 17:35
We're still seeing issues as well.

**Comment by leff** [comment] 2018-06-06 17:39
I tried replacing `registry.yarnpkg.com` with `registry.npmjs.org` in my yarn.lock file. The build has gotten past the yarn install step. I suspect `registry.yarnpkg.com` is caching the error responses.

**Comment by hemp** [comment] 2018-06-06 21:01
npmjs incident has been updated to resolved: https://status.npmjs.org/incidents/qxj3kdzw4jrg

**Closed** 2018-06-12 14:57 UTC
Labels: cat-backend, needs-confirmation, triaged

**Comment by synalysis** [comment] 2018-09-01 13:41
I was able to resolve the issue locally by leaving the VPN connection (IPVanish).

But when deploying to zeit.co I had it again. Annoying.

**Comment by johnnyreilly** [comment] 2018-09-01 19:56
I'm completely out of action due to this.  So frustrating

**Comment by andrjuha01** [comment] 2018-09-02 14:11
Same in Ukraine right now.

**Comment by jimitpatel** [comment] 2018-09-27 10:46
> I was able to work around the problem and get rid of the 503s by changing `https://registry.yarnpkg.com` to `https://registry.npmjs.org/` in `yarn.lock`. This suggests that the problem is not the npmjs registry, but rather the yarnpkg registry.

Worked for me like a charm... I am behind proxy. I replaced those link with proxy links... I had to change it eventhough I have changed it via `npm config set registry`
