### ISSUE TITLE
Version constraint issue (~)

### ISSUE THREAD

**Issue by strarsis** [yarnpkg/yarn#4766] opened 2017-10-24 01:57 UTC
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Repository with code: 
https://github.com/svg/svgo/blob/645908923bb163e177023ca21fe04a380fade126/package.json

````
$ git clone https://github.com/svg/svgo
$ cd svgo
$ git checkout 645908923bb163e177023ca21fe04a380fade126
$ yarn install
$ yarn test
````
Tests fail (error messages).

The resaon is that package `css-tree` version `1.0.0-alpha9` has been installed by yarn instead 
`1.0.0-alpha25`. 

When changing the version constraint in `package.json` from [`"~1.0.0-alpha25"`](https://github.com/svg/svgo/blob/645908923bb163e177023ca21fe04a380fade126/package.json#L58) to `"1.0.0-alpha25"` and installing the packages anew with yarn, 
the correct version `1.0.0-alpha25` is installed and the subsequent tests pass.

`npm` will correctly install package `css-tree` version `1.0.0-alpha25` 
even with the original version constraint `"~1.0.0-alpha25"`.

**What is the expected behavior?**
That `yarn` installs package `css-tree` version `1.0.0-alpha25`, replicating the 
(probably correct, hence authoritative?) behaviour of `npm`.

**Please mention your node.js, yarn and operating system version.**
node v6.11.3
yarn 1.2.1
Windows Subsystem for Linux (4.4.0-43-Microsoft)

**Comment by rally25rs** [comment] 2017-10-24 14:36
This issue seems familiar... I think we looked into this a while back...

```
npm install css-tree@~1.0.0-alpha25
```

installs `alpha25`

```
yarn add css-tree@~1.0.0-alpha25
```

installs `alpha9`

-----

IIRC in the semver specification the part after the `-` is interpreted as alpha, so `alpha9` > `alpha25` in alphabetical order. In fact NPM's own `semver` library confirms this:

```
$ npm install semver

$ node
> const semver = require('semver');
undefined
> semver.gt('1.0.0-alpha9', '1.0.0-alpha25');
true
```

NPM seems to have some kind of magical handling for this that we never quite figured out.

-----

I'll see if I can dig up the old issue...

**Comment by rally25rs** [comment] 2017-10-26 13:41
Closing as duplicate of #3560

**Closed by rally25rs** 2017-10-26 13:41 UTC
Labels: cat-compatibility, triaged
