### ISSUE TITLE
Debian package repository key changed to 4F77679369475BAA

### ISSUE THREAD

**Issue by sth** [yarnpkg/yarn#6916] opened 2019-01-12 23:23 UTC
Just recently the key used to sign Debian packages [was changed][1] to a new key with id 23E7166788B63E1E. Now that key seems to have changed again:

> W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4F77679369475BAA

That new key seems to have been created  on 2019-01-11 after the previous change on 2019-01-02.
Is this change intentional?

Are key changes announced somewhere? The signatures are completely pointless if I'm supposed to just redownload a new key whenever there is a signature error. If someone manages to upload a changed package to https://dl.yarnpkg.com/debian they most likely can also upload a new key to that location.

 [1]: https://github.com/yarnpkg/yarn/issues/6885

**Comment by cwitteveen** [comment] 2019-01-12 23:47
@sth  https://github.com/yarnpkg/yarn/issues/6903#issuecomment-453354332

**Comment by Daniel15** [comment] 2019-01-14 18:56
Sorry about that! This was totally unexpected. On 11th January, I added a new subkey (4F77679369475BAA) for the nightly repo, as a response to this comment: https://github.com/yarnpkg/yarn/issues/6865#issuecomment-453336987
> Still have the warning with nightly repo

The reason the stable and nightly repos use separate keys is so the build environments can be isolated, and the nightly key being compromised won't affect the stable key. The environment used to sign the nightly repo only contains the nightly subkey, not the stable subkey, and the nightly one can be revoked separately.

This key was **only** supposed to be used for the nightly repo. However, there appears to be a bug with Aptly. We're explicitly signing the stable repo with `23E7166788B63E1E`: https://github.com/yarnpkg/releases/blob/gh-pages/debian-source/add-deb.sh#L26-L27
```
aptly -config=./.aptly.conf publish update -gpg-key=23E7166788B63E1E stable
aptly -config=./.aptly.conf publish update -gpg-key=23E7166788B63E1E rc
```

However, it appears to be ignoring this and using the wrong subkey (4F77679369475BAA). I want to investigate whether this happens in an isolated test case (new GPG key with two subkeys, and two new Aptly repos) and report it upstream if so.

Also, apologies for the delay in replying... I was on vacation.

**Comment by Daniel15** [comment] 2019-01-14 20:31
Bug filed upstream: https://github.com/aptly-dev/aptly/issues/805

**Comment by ianrandmckenzie** [comment] 2019-01-15 09:40
Hi there. Dev ops newbie here. I can't seem to `apt update` until the key can be properly read. Is there a workaround until a fix is in place?

**Comment by patros** [comment] 2019-01-15 10:47
@ianrandmckenzie that will add that key as a trusted package key. Pretty low risk in this scenario. But you could always remove it after the issue is resolved.

**Comment by jonathanmeier5** [comment] 2019-01-15 18:06
Is there any timeline as to when this will be fixed, or will it depend on the `aptly` bugfix?

**Comment by Daniel15** [comment] 2019-01-15 18:20
@jonathanmeier5 - Nothing should be broken at the moment. The only issue is that the stable repo is being signed with the nightly repo's key, however **both** public keys are included in the public key published at https://dl.yarnpkg.com/debian/pubkey.gpg so it shouldn't be an issue.

**Comment by jonathanmeier5** [comment] 2019-01-15 18:38
I guess to rephrase my question: do you have any idea when you will return to signing the stable yarn release with only the most recent stable sub-key? Ideally, we would prefer to not accept signatures from the nightly key in our builds long term.

**Comment by Daniel15** [comment] 2019-01-15 19:05
Yeah, it mainly depends on the aptly bug. Unfortunately I don't really have time to look into it myself right now :(

**Comment by jonathanmeier5** [comment] 2019-01-15 19:08
No problem, thanks for the updates 👍

**Comment by Daniel15** [comment] 2019-01-20 00:36
Thank you so much @sth! I've just re-signed the repo using the proper subkey, thanks to your advice.

**Closed by Daniel15** 2019-01-20 00:36 UTC
Labels: triaged
