### ISSUE TITLE
Homebrew cannot install latest version of yarn

### ISSUE THREAD

**Issue by AlvinYuXT** [yarnpkg/yarn#6681] opened 2018-11-14 12:37 UTC
**Do you want to request a *feature* or report a *bug*?**

It's a bug.

**What is the current behavior?**
The stable version of yarn is 1.12.3 now, but When I run `brew info yarn` I got this:
> yarn: stable 1.9.4
JavaScript package manager
https://yarnpkg.com/
Conflicts with:
  hadoop (because both install `yarn` binaries)
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Recommended: node ✘
==> Options
--without-node
	Build without node support
==> Analytics
install: 147,652 (30 days), 363,206 (90 days), 1,198,647 (365 days)
install_on_request: 145,936 (30 days), 359,008 (90 days), 1,180,163 (365 days)
build_error: 0 (30 days)

And when I open the this link https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb I found this:

> url "https://yarnpkg.com/downloads/1.12.3/yarn-v1.12.3.tar.gz"

**What is the expected behavior?**
Install the latest version of yarn

**Please mention your node.js, yarn and operating system version.**
node v10.13.0
macOS High Sierra 10.13.6

**Comment by rally25rs** [comment] 2018-11-14 13:18
duplicate of #2337
As stated in the Brew output, Hadoop also has a `yarn` binary that they install, so there is a conflict and it halts the install so that your hadoop yarn binary is not overwritten.

**Closed by rally25rs** 2018-11-14 13:18 UTC
Labels: triaged

**Comment by AlvinYuXT** [comment] 2018-11-15 02:31
@rally25rs There is no Hadoop in my Mac. When I run `brew install yarn` the version I installed is 1.9.4 which the latest version is 1.12.3.

**Comment by cakasuma** [comment] 2019-02-01 09:15
im also having the same issue

**Comment by AlvinYuXT** [comment] 2019-02-01 09:55
@cakasuma  I fix this problem by installing yarn by npm
