### ISSUE TITLE
yarn upgrade-interactive currently doesn't work correctly for typescript

### ISSUE THREAD

**Issue by donaldpipowitch** [yarnpkg/yarn#2668] opened 2017-02-08 13:34 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

```
{
  "name": "yarn-test",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "typescript": "^2.1.5"
  }
}
```

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


typescript@^2.1.5:
  version "2.1.5"
  resolved "https://registry.yarnpkg.com/typescript/-/typescript-2.1.5.tgz#6fe9479e00e01855247cea216e7561bafcdbcd4a"
```

```
$ yarn upgrade-interactive
yarn upgrade-interactive v0.20.0-0
? Choose which packages to update. (Press <space> to select, <a> to toggle all, <i> to inverse selection)
 dependencies
❯◯ typescript  2.1.5  ❯  2.1.5.  http://typescriptlang.org/
```

**What is the expected behavior?**

Do not show `typescript` as an upgradeable package.

Note: I've seen this before for other packages as well.

**Please mention your node.js, yarn and operating system version.**

Node v6.9.1, yarn v0.21.0-20170205.0124

**Comment by karfau** [comment] 2017-08-19 04:54
same problem with Node 8.1.4, yarn 0.28.4 and typescript version 2.4.2

**Comment by rally25rs** [comment] 2017-12-28 04:14
This seems to work on Yarn 1.3.2. Closing this issue since this is from a very old version of Yarn. If you can reproduce it on yarn 1.3 please let us know and we can reopen this.

**Closed by rally25rs** 2017-12-28 04:14 UTC
Labels: needs-confirmation
