### ISSUE TITLE
yarn doesn't respect TMP or TEMP environment variables

### ISSUE THREAD

**Issue by yurivict** [yarnpkg/yarn#8600] opened 2021-03-22 18:03 UTC
It seems to just use the hardcoded ```/tmp```.

Sometimes tmpdir needs to be changed.

**Comment by rally25rs** [comment] 2021-04-02 21:26
Yarn v1 or v2?
What is yarn writing to `/tmp`?
In the v1 source I only see `/tmp` in unit test code.

**Comment by yurivict** [comment] 2021-04-02 21:37
yarn-1.22.10

It wrote some temp data into /tmp. I don't have the testcase any more because I used pre-built directory for the port in question (authelia).

**Comment by rally25rs** [comment] 2021-04-02 21:53
if you come up with a way to reproduce the issue, please let us know and I could take a look. An example `package.json` would help. Also which OS. 

As a quick test I did a `yarn install` of `jest` and saw no change to `/tmp` on OSX, so it could be something specific to an install script in whatever packages you are installing.

```
~/Projects/tst 🐒   ls /tmp
AlTest1.err                  aws-toolkit-vscode           com.apple.launchd.g8nUa9h8uK
AlTest1.out                  com.apple.launchd.Z3pkRLIcHV

~/Projects/tst 🐒   yarn install --force
yarn install v1.22.5
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Rebuilding all packages...
success Saved lockfile.
✨  Done in 6.68s.

~/Projects/tst 🐒   ls /tmp
AlTest1.err                  aws-toolkit-vscode           com.apple.launchd.g8nUa9h8uK
AlTest1.out                  com.apple.launchd.Z3pkRLIcHV
```

**Comment by RDIL** [comment] 2022-09-07 16:31
Closing due to lack of reproduction.

**Closed by RDIL** 2022-09-07 16:31 UTC
