### ISSUE TITLE
official debian packages

### ISSUE THREAD

**Issue by marado** [yarnpkg/yarn#1305] opened 2016-10-20 15:06 UTC
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
No package on official Debian repositories.

**What is the expected behavior?**
Package on official Debian repositories.

**Description**

At #275 debian packages were created, and there are yarn-maintained repositories to allow users to install yarn via apt. However, it would be better still if people could install yarn directly from debian repositories.

For that to happen, an [ITP](https://www.debian.org/devel/wnpp/) should be created. I believe this will end up happening anyway, but it would be advantageous if the debian package was actually maintained by someone from upstream (I mean, whomever is currently maintaining the yarn debian repository).

This issue is not being submitted simply as a "feature request", but also to know if this is something yarn people are willing to do in the future, or if someone else should work on it.

**Comment by Daniel15** [comment] 2016-10-21 01:08
Hi @marado! 

> whomever is currently maintaining the yarn debian repository)

That's me! 😄 

Getting it into Debian would require some more work. The current Debian package is "good enough" for people to use and works well, but I don't think it's quite ready for inclusion in Debian as they have pretty strict quality requirements for packages. For one, the current package bundles all dependencies into the package itself. Debian requires dependencies to be in their own separate packages (for example, see the [npm package in Ubuntu](http://packages.ubuntu.com/xenial/npm)). Additionally, we currently don't have manpages/docs or a proper changelog for Yarn.

It's not something we'll do in the short term, but maybe in the long term!

Thanks for your interest.

**Comment by simevo** [comment] 2016-11-03 15:05
Here is the RFP https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843021

**Comment by simevo** [comment] 2016-12-16 17:51
We're making progress on this one !

The introduction with [this commit](https://github.com/yarnpkg/yarn/commit/c6bd30b4b01c2e5422d82b2568ab5f45f79350bc) of the new dependency on the inquirer module makes the matter harder because we need to package that first...

Next there's waiting for gulp to get into debian and finally implement the actual build in the curiously named makefile [debian/rules](https://anonscm.debian.org/git/pkg-javascript/node-yarnpkg.git/tree/debian/rules).

For detailed a status update see https://bugs.debian.org/843021.

**Comment by Daniel15** [comment] 2016-12-19 09:35
@simevo - Why `node-yarnpkg` rather than just `yarnpkg`? npm's package is just `npm` rather than `node-npm`, right?

**Comment by simevo** [comment] 2016-12-19 09:57
The normal [JS maintainers team best practice](https://wiki.debian.org/Javascript/Nodejs/Manual) is that "_binary and the source package should be called node-foo_". But since `node-yarnpkg` also installs a binary in `/usr/bin` called `yarnpkg`, as I have currently set it up (see the [control file](https://anonscm.debian.org/git/pkg-javascript/node-yarnpkg.git/tree/debian/control)), the binary in this case is called just `yarnpkg`. So users will happily install it with:
```
apt install yarnpkg
```

**Comment by Daniel15** [comment] 2016-12-19 10:18
Oh cool, thanks for the info! 😃

**Comment by simevo** [comment] 2016-12-25 16:13
Status update: we've all dependencies and main build dependencies (gulp-if and gulp-watch we avoided)in the archive with the exception of babel and gulp-babel. 
ATM just for testing I'm patching the gulpfile to skip the babel step:
https://anonscm.debian.org/git/pkg-javascript/node-yarnpkg.git/tree/debian/patches/07-gulp-babel.diff
The resulting package passes the lintian tests and can be installed but on launching the CLI of course the [nodejs interpreter version 4.6.1](https://packages.debian.org/sid/nodejs) cannot cope with the javascript which has not been processed with babel:
```
# yarnpkg 
/usr/lib/nodejs/yarn/lib-legacy/constants.js:5
let userHome = os.homedir();
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/nodejs/yarn/bin/yarn.js:29:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

We face the risk of missing the stretch freeze. I wonder if there is any other transpiler or I-dont-kno-what-trick to make it run in node 4.6.1 ?

**Comment by Daniel15** [comment] 2016-12-26 14:04
>  I wonder if there is any other transpiler or I-dont-kno-what-trick to make it run in node 4.6.1 ?

@simevo - Unfortunately there's no other trick to make it run in Node.js 4.6.1, the code must be transpiled. I think Babel is only a build-time dependency and not a runtime dependency, so it just has to be available at build time. Does that help at all? Could the build script install Babel via npm?

It looks like Node.js 6.9.2 is available in Debian experimental, do you know if it will be migrated to unstable/testing?

**Comment by simevo** [comment] 2016-12-29 12:49
Alright we just missed the stretch freeze window so let's relax !

The good news is that since all dependencies required to run are in the archive (but for the versions of diff, ini, mkdirp and request which are bit behind), if anybody wants to provide a `.deb` for yarnpkg as it is now (0.18.1) they don't need to ship a `node_modules` dir with the dependencies inside. Until the yarn developers add some new dependency...

@Daniel15 as you know the Debian project is quite strict in requiring consistency of the build environment (that's for reproducible builds, for long term support and for free software guidelines compliance) but you're right we could still build with npm and target the contrib archive. I'm not too interested in that personally; my new goal is to finish the build deps and target the next Debian release (testing i..e buster). I hope nodejs 6.9.x we'll soon land from experimental so that should make it easier.

Creating a version for stretch-backports is also a possibility.

**Comment by Daniel15** [comment] 2018-04-25 13:56
Glad to hear that it's going well! 😃

**Comment by simevo** [comment] 2019-01-09 21:50
Hi, FYI the official Debian package for yarnpkg is almost ready, see:
https://alioth-lists.debian.net/pipermail/pkg-javascript-devel/2019-January/030431.html

Once it's been tested and reviewed, I'd like to try to contribute upstream two of [the patches I created](https://salsa.debian.org/js-team/node-yarnpkg/tree/master/debian/patches), in particular:
- 02-leven.diff: use `fast-levenshtein` instead of `leven`
- 10-babel-plugin-inline-import.diff: do not depend on `babel-plugin-inline-import` as this plugin is not used: there are no `.text`, `.raw` or `.graphql` files, besides there is a single `.tpl.js` file in the repo, but there is no matching import

**Comment by Daniel15** [comment] 2019-01-11 02:49
> Once it's been tested and reviewed, I'd like to try to contribute upstream two of the patches I created

This sounds fine to me! Feel free to send pull requesst on Github with your changes.

**Comment by Daniel15** [comment] 2019-07-08 16:29
This landed in Buster, so I think we can close this out now.

**Closed by Daniel15** 2019-07-08 16:29 UTC
Labels: os-linux

**Comment by reeaosirjustsir** [comment] 2024-06-07 11:25
Hello there! reeao here!

You have to go this termux github issue link!:
https://github.com/termux/proot-distro/issues/416
