### ISSUE TITLE
adding yarn to debian 10 jailkit

### ISSUE THREAD

**Issue by broros** [yarnpkg/yarn#7814] opened 2020-01-11 11:24 UTC
I am getting an error when checking yarn on jailed user
```
yarn --version
/usr/bin/yarn: line 3: readlink: command not found
/usr/bin/yarn: line 5: uname: command not found
node: ../deps/uv/src/unix/core.c:556: uv__close_nocheckstdio: Assertion `fd > -1' failed.
Aborted
```

In my file ( /etc/jailkit/jk_init.ini ) I have the following: 
```
[node]
comment = NodeJS
executables = /usr/bin/npm, /usr/bin/node, /usr/bin/nodejs, /usr/bin/yarn
directories = /usr/lib/node_modules
```

Debian 10
yarn -v
1.21.1

**Comment by olingern** [comment] 2020-01-26 14:34
I don't think this is an issue with yarn. This looks to be a permissions issue on your system

**Comment by olingern** [comment] 2020-01-27 20:26
Closing. Happy to reopen if you can demonstrate an issue with yarn

**Closed by olingern** 2020-01-27 20:26 UTC

**Comment by chriscroome** [comment] 2020-02-01 20:11
For what it is worth I had the same error in a Debian Buster chroot after upgrading Node.js from version 11 to 12 and then trying to install Bower:

```bash
npm install -g bower
node: ../deps/uv/src/unix/core.c:556: uv__close_nocheckstdio: Assertion `fd > -1' failed.
Aborted
```
I'm posting this here in case it serves as a clue to the cause of the problem...
