### ISSUE TITLE
postinstall for local dependencies not being invoked.

### ISSUE THREAD

**Issue by jordwalke** [yarnpkg/yarn#2853] opened 2017-03-07 09:35 UTC
### BUG

Inside a directory with `package.json`:
```
{
  "name": "testtop",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "echo 'in testtop'"
  },
  "dependencies": {
    "test": "file:../test"
  }
}
```

Then another project at `../test/package.json`
```
{
  "name": "test",
  "version": "1.0.0",
  "scripts": {
    "postinstall": "echo 'in dep'"
  },
  "dependencies": {
    "testdep": "file:../testdep"
  }
}

```

Then another dependency at `../testdep/packages.json`:

```
{
  "name": "testdep",
  "scripts": {
    "postinstall": "echo 'in testdep'"
  }
}
```

- From within the original directory, `rm -rf node_modules && yarn install`
- Yarn only fires postinstall for the top level package, not the dependencies.
- `Npm` fires postinstall for all dependencies, and then finally your own top level package.

Yarn version 21.3.  Node version 6.9.5. Last issues to claim fixes to `postinstall` were around version 16 it seems, and I can't find any other issues about this surprisingly.

**Comment by rhys-e** [comment] 2017-03-09 22:54
So, I've got a similar setup locally, and I think this is just a case of the `echo` getting lost. As a proof, `echo 'test' > test` produces a `test` file for me.

**Comment by jordwalke** [comment] 2017-03-12 09:03
I actually think it's a real serious problem. I just created a similar setup and in the preinstall/postinstall/install steps, I didn't just log the output but appended to a file inside the script that was invoked. I made sure to output the lifecycle name and package name, and I see very different things for npm and yarn.

NPM
```
testtop.preinstall
testdep.preinstall
test.preinstall
testdep.install
test.install
testdep.postinstall
test.postinstall
testtop.install
testtop.postinstall

```

Yarn
```
testtop.preinstall
testtop.install
testtop.postinstall
```

**Comment by jordwalke** [comment] 2017-03-12 09:06
As one more datapoint (if Yarn is attempting to comply with the npm lifecycle order, I thought I'd introduce an extra dependency from `testtop` to `testdep` so that it's not such a simple linear list.

Here's what I got for NPM:

```
testtop.preinstall
testdep.preinstall
test.preinstall
testdep.install
test.install
testdep.postinstall
test.postinstall
testtop.install
testtop.postinstall
```
The same.

**Comment by rhys-e** [comment] 2017-03-13 14:37
Are you sure you're not being led down a path by `https://github.com/yarnpkg/yarn/issues/2165`? Can you try a `yarn cache clean` and try again?

**Comment by jesstelford** [comment] 2017-03-26 22:09
I was able to reproduce @jordwalke's results with yarn `0.21.3`.

I created a couple repos, and popped the results of the tests on Github: https://github.com/jesstelford/npm-scripts-test

Here are the results for posterity:

## Local modules

### From root of project (no deps)

<details><summary>Click to expand</summary><p>

See [`package.json@v2.0.0`](https://github.com/jesstelford/npm-scripts-test/blob/v2.0.0/package.json)

#### `npm`

```shell
git clone --branch v2.0.0 https://github.com/jesstelford/npm-scripts-test.git
cd npm-scripts-test
npm install
```

#### `yarn`

```shell
git clone --branch v2.0.0 https://github.com/jesstelford/npm-scripts-test.git
cd npm-scripts-test
yarn
```

#### Output

```shell
cat node_modules/npm-scripts-test/scripts
```

##### `npm`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepare
```

##### `yarn`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
```

##### The diff

```diff
--- a/yarn-scripts
+++ b/npm-scripts
@@ -2,4 +2,3 @@ npm-scripts-test.preinstall
 npm-scripts-test.install
 npm-scripts-test.postinstall
 npm-scripts-test.prepublish
+npm-scripts-test.prepare
```

</p></details>

### Single level dep

<details><summary>Click to expand</summary><p>

See [`package.json@v2.0.0`](https://github.com/jesstelford/npm-scripts-test/blob/v2.0.0/package.json)

#### `npm`

```shell
git clone --branch v2.0.0 https://github.com/jesstelford/npm-scripts-test.git
mkdir test-single-level-npm
cd test-single-level-npm
npm init -y .
npm install --save ../npm-scripts-test
```

#### `yarn`

```shell
git clone --branch v2.0.0 https://github.com/jesstelford/npm-scripts-test.git
mkdir test-single-level-yarn
cd test-single-level-yarn
yarn init -y .
yarn add file:../npm-scripts-test
```

#### Output

```shell
cat node_modules/npm-scripts-test/scripts
```

##### `npm`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

##### `yarn`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

##### The diff

```diff
--- a/npm-scripts
+++ b/yarn-scripts
@@ -1,9 +1,3 @@
 npm-scripts-test.preinstall
 npm-scripts-test.install
 npm-scripts-test.postinstall
-npm-scripts-test.prepublish
-npm-scripts-test.prepublish
-npm-scripts-test.prepare
-npm-scripts-test.preinstall
-npm-scripts-test.install
-npm-scripts-test.postinstall
```

</p></details>

### Dep local, but dep of a dep from registry

<details><summary>Click to expand</summary><p>

See [`npm-scripts-test-parent/package.json@v1.0.0`](https://github.com/jesstelford/npm-scripts-test-parent/blob/v1.0.0/package.json)

#### `npm`

```shell
git clone --branch v1.0.0 https://github.com/jesstelford/npm-scripts-test-parent.git
mkdir test-dep-of-dep-npm
cd test-dep-of-dep-npm
npm init -y .
npm install --save ../npm-scripts-test-parent
```

#### `yarn`

```shell
git clone --branch v1.0.0 https://github.com/jesstelford/npm-scripts-test-parent.git
mkdir test-dep-of-dep-yarn
cd test-dep-of-dep-yarn
yarn init -y .
yarn add file:../npm-scripts-test-parent
```

#### Output

_(output is the same for both `npm` & `yarn`)_

```shell
cat node_modules/npm-scripts-test/scripts
```

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

</p></details>

### Non-linear Dep local, but dep of a dep from registry

<details><summary>Click to expand</summary><p>

See [`npm-scripts-test-parent/package.json@v1.0.0`](https://github.com/jesstelford/npm-scripts-test-parent/blob/v1.0.0/package.json)

#### `npm`

```shell
git clone --branch v1.0.0 https://github.com/jesstelford/npm-scripts-test-parent.git
mkdir test-dep-of-dep-npm
cd test-dep-of-dep-npm
npm init -y .
npm install --save ../npm-scripts-test-parent
npm install --save ../npm-scripts-test
rm -rf node_modules
npm install
```

#### `yarn`

```shell
git clone --branch v1.0.0 https://github.com/jesstelford/npm-scripts-test-parent.git
mkdir test-dep-of-dep-yarn
cd test-dep-of-dep-yarn
yarn init -y .
yarn add file:../npm-scripts-test-parent
yarn add file:../npm-scripts-test
rm -rf node_modules yarn.lock
yarn
```

#### Output

```shell
cat node_modules/npm-scripts-test/scripts
```

##### `npm`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

##### `yarn`

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

##### The diff

```diff
--- a/npm-scripts
+++ b/yarn-scripts
@@ -1,9 +1,3 @@
 npm-scripts-test.preinstall
 npm-scripts-test.install
 npm-scripts-test.postinstall
-npm-scripts-test.prepublish
-npm-scripts-test.prepublish
-npm-scripts-test.prepare
-npm-scripts-test.preinstall
-npm-scripts-test.install
-npm-scripts-test.postinstall
```

</p></details>

## From registry

### As a dependency

<details><summary>Click to expand</summary><p>

See [`package.json@v2.0.0`](https://github.com/jesstelford/npm-scripts-test/blob/v2.0.0/package.json)

#### `npm`

```shell
npm init -y .
npm install --save npm-scripts-test@2.0.0
```

#### `yarn`

```shell
yarn init -y .
yarn add npm-scripts-test@2.0.0
```

#### Output

_(output is the same for both `npm` & `yarn`)_

```shell
cat node_modules/npm-scripts-test/scripts
```

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

</p></details>

### As a dependency of a dependency

<details><summary>Click to expand</summary><p>

See [`npm-scripts-test-parent/package.json@v1.0.0`](https://github.com/jesstelford/npm-scripts-test-parent/blob/v1.0.0/package.json)

#### `npm`

```shell
npm init -y .
npm install --save npm-scripts-test-parent@1.0.0
```

#### `yarn`

```shell
yarn init -y .
yarn add npm-scripts-test-parent@1.0.0
```

#### Output

_(output is the same for both `npm` & `yarn`)_

```shell
cat node_modules/npm-scripts-test/scripts
```

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

</p></details>

### Non-linear dep of dep

<details><summary>Click to expand</summary><p>

See [`npm-scripts-test-parent/package.json@v1.0.0`](https://github.com/jesstelford/npm-scripts-test-parent/blob/v1.0.0/package.json)

#### `npm`

```shell
npm init -y .
npm install --save npm-scripts-test-parent@1.0.0
npm install --save npm-scripts-test@2.0.0
rm -rf node_modules
npm install
```

#### `yarn`

```shell
yarn init -y .
yarn add npm-scripts-test-parent@1.0.0
yarn add npm-scripts-test@2.0.0
rm -rf node_modules yarn.lock
yarn
```

#### Output

_(output is the same for both `npm` & `yarn`)_

```shell
cat node_modules/npm-scripts-test/scripts
```

```plain
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.prepublish
npm-scripts-test.prepare
npm-scripts-test.preinstall
npm-scripts-test.install
npm-scripts-test.postinstall
```

</p></details>

---

Note: I didn't test a dep of a dep being a local file too, but you could easily do that.

**Comment by montogeek** [comment] 2017-04-04 20:50
Reported in https://github.com/yarnpkg/yarn/issues/1671

**Comment by arcanis** [comment] 2017-04-28 16:44
I'll close this one as a duplicate of #1671 - thanks for reporting it!

**Closed by arcanis** 2017-04-28 16:44 UTC
