### ISSUE TITLE
Request failed \"404 Not Found\"".

### ISSUE THREAD

**Issue by pavinthan** [yarnpkg/yarn#3622] opened 2017-06-11 20:25 UTC
>yarn add babel-preset-stage-2
yarn add v0.23.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-helpers.js/-/babel-helpers.js-6.24.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "D:\\movies\\mnhdp\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

error An unexpected error occurred: "https://registry.yarnpkg.com/babel-helpers.js/-/babel-helpers.js-6.24.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "D:\\movies\\mnhdp\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by zaknuces** [comment] 2017-06-16 07:03
Any updates on this issue. I faced the same issue with "wrench-js" package. It is not available and i tried upgrading but face the similar 404 issue. Very annoying.

**Comment by jhabdas** [comment] 2017-06-18 18:58
@pavinthan @zaknuces are you both using windows? if so, are you using cmder?

**Comment by Daniel15** [comment] 2017-06-28 04:16
`babel-helpers.js` doesn't look like a valid package name. I think you're looking for `babel-helpers` without the `.js`.

**Comment by jhabdas** [comment] 2017-06-28 06:51
@Daniel15 good eyes sir. good eyes <<

**Comment by shousper** [comment] 2017-09-10 23:44
I'm on macOS and have been getting this error for a while.
See my comments [here](https://github.com/yarnpkg/yarn/issues/4335#issuecomment-327978352) and [here](https://github.com/yarnpkg/yarn/issues/4335#issuecomment-328381679) (possibly wrong issue to comment on..)

**Comment by BYK** [comment] 2017-09-11 15:45
@shousper I think it is better to track your issue in the tickets you've mentioned. I'm going to close this one since the author did not respond to the request for clarification, ws using a very old version of `yarn` and I was unable to reproduce this.

**Closed by BYK** 2017-09-11 15:45 UTC
Labels: bug-fetching, needs confirmation, needs-repro-script, os-windows, triaged

**Comment by Berkmann18** [comment] 2019-12-15 18:31
This is still an issue.
```
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/es-abstract/-/es-abstract-1.14.0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/maxie/Projects/json-fixer/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Daniel15** [comment] 2019-12-15 23:48
@Berkmann18 I think that's an issue with the package. The npm registry is throwing the same error, which means it's not specific to Yarn. 

https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz

**Comment by Berkmann18** [comment] 2019-12-16 00:27
@Daniel15 That's possibly the case, however, when using NPM on the same project, I don't get this error.

I suppose it might be due to something in the yarn lock file :question:
