### ISSUE TITLE
Yarn installation is freezing with the package of "semantic-ui"

### ISSUE THREAD

**Issue by bulletinmybeard** [yarnpkg/yarn#2361] opened 2016-12-31 11:38 UTC
It's a *bug* and I'm using yarn in version **0.18.1**.

**If the current behavior is a bug, please provide the steps to reproduce.**
Every time I'm going to install the semantic-ui package, the installation process halts and runs like forever (no kidding!). I have to run *yarn* or *yarn install* twice to finish the installation process of the *semantic-ui* package. Just try to install *semantic-ui* with `yarn add semantic-ui` and you will see that the installation process halts when yarn is building everything:

```
rschulz@MacBook-Pro:~/dev/prv/angular2/notifier$ yarn
yarn install v0.17.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "reflect-metadata@^0.1.3".
warning Unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning Incorrect peer dependency "@angular/core@~2.0.0".
warning Incorrect peer dependency "@angular/common@~2.0.0".
warning Incorrect peer dependency "@angular/compiler@~2.0.0".
warning Incorrect peer dependency "@angular/platform-browser@~2.0.0".
warning Incorrect peer dependency "@angular/http@~2.0.0".
warning Incorrect peer dependency "@angular/compiler-cli@2.2.1".
warning Incorrect peer dependency "@angular/core@2.2.1".
warning Unmet peer dependency "reflect-metadata@^0.1.8".
[4/4] 📃  Building fresh packages...
[-/6] ⢀ waiting...
[6/6] ⠠ semantic-ui:     at AnonymousObservable.tryCatcher (/Users/rschulz/dev/prv/angular2/notifier/node_modules/rx-lite/rx.
[-/6] ⠠ waiting...
[-/6] ⠠ waiting...
**^C/6]** ⠠ node-sass: Binary is fine
```

Here I'm stopping the process manually and start it again which works fine then:

```
rschulz@MacBook-Pro:~/dev/prv/angular2/notifier$ yarn
yarn install v0.17.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "reflect-metadata@^0.1.3".
warning Unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning Incorrect peer dependency "@angular/core@~2.0.0".
warning Incorrect peer dependency "@angular/common@~2.0.0".
warning Incorrect peer dependency "@angular/compiler@~2.0.0".
warning Incorrect peer dependency "@angular/platform-browser@~2.0.0".
warning Incorrect peer dependency "@angular/http@~2.0.0".
warning Incorrect peer dependency "@angular/compiler-cli@2.2.1".
warning Incorrect peer dependency "@angular/core@2.2.1".
warning Unmet peer dependency "reflect-metadata@^0.1.8".
[4/4] 📃  Building fresh packages...
✨  Done in 39.62s.
```

I'm using Node.js *v7.2.1* on my Mac with macOS Sierra *10.12.2 (16C67)*

I don't think it's a bug with yarn itself but something is obviously not okay because the same behaviour I can reproduce with NPM. Maybe you guys could have a look at the provided package information from *semantic-ui* and can see why everything behaves like I described above.

**Comment by daaain** [comment] 2017-02-06 18:41
Looks like a duplicate of #976?

**Comment by bestander** [comment] 2017-05-15 19:30
Commented in the linked package

**Closed** 2017-05-15 19:29 UTC
