### ISSUE TITLE
Yarn inconsistency

### ISSUE THREAD

**Issue by skeggse** [yarnpkg/yarn#3663] opened 2017-06-18 20:21 UTC
Running yarn@`0.24.6`

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

After running `yarn` in a directory with this `package.json`, and a clean cache, `yarn check` reports errors.

`package.json`:

```json
{
  "name": "test-app",
  "version": "0.0.1",
  "engines": {
    "node": "6.9.1"
  },
  "devDependencies": {
    "erik": "^1.2.1",
    "handlebars": "4.0.6",
    "jasmine": "2.3.1",
    "main-bower-files": "2.9.0",
    "merge-stream": "0.1.8",
    "minimatch": "3.0.3",
    "resolve-vars": "1.0.0",
    "rewire": "2.5.1",
    "rollup-plugin-babel": "2.6.1",
    "rollup-plugin-bower-resolve": "0.2.0",
    "rollup-plugin-commonjs": "5.0.5",
    "rollup-plugin-handlebars-plus": "0.2.0",
    "rollup-plugin-multi-entry": "2.0.0",
    "rollup-plugin-node-resolve": "2.0.0",
    "rollup-plugin-root-import": "0.2.0",
    "run-sequence": "1.1.4"
  }
}
```

output from `yarn check`

```
yarn check v0.24.6
warning test-app@0.0.1: No license field
error "erik#jasmine-core" is wrong version: expected "2.6.4", got "2.3.4"
error "jasmine#jasmine-core" not installed
warning "chokidar#fsevents#node-pre-gyp@^0.6.36" could be deduped from "0.6.36" to "node-pre-gyp@0.6.36"
error "jasmine#minimatch#lru-cache" is wrong version: expected "2.2.4", got "2.7.3"
error Found 3 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

output from `yarn check` on a separate run of the repro steps

```
yarn check v0.24.6
warning test-app@0.0.1: No license field
warning "chokidar#fsevents#node-pre-gyp@^0.6.36" could be deduped from "0.6.36" to "node-pre-gyp@0.6.36"
error "jasmine#minimatch#lru-cache" is wrong version: expected "2.2.4", got "2.7.3"
error Found 1 errors.
info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Place the above `package.json` in a clean directory, run `yarn && yarn check`. Note that we can reproduce this on a much larger `package.json` with many more `error`s, and this is just one of many smaller `package.json` files that reproduces this issue.

**What is the expected behavior?**

`yarn check` passes (and that it fails consistently)

**Please mention your node.js, yarn and operating system version.**

`node v6.9.1`, `npm 3.10.8`
`node v7.6.0`, `npm 4.1.2`
`node v8.1.2`, `npm 5.0.3`
`macOS 10.11.6`

**Comment by rally25rs** [comment] 2017-06-20 13:05
Confirmed on 0.24.6.
Seems to be a bug in the `check` command reporting incorrect "errors".

```
$ yarn check
yarn check v0.24.6
warning test-app@0.0.1: No license field
error "erik#jasmine-core" is wrong version: expected "2.6.4", got "2.3.4"
...

$ grep version node_modules/erik/node_modules/jasmine-core/package.json
  "version": "2.6.4",

$ grep version node_modules/jasmine-core/package.json
  "version": "2.3.4",
```

so it seems like `check` thinks the `erik` package is going to use the hoisted `jasmine-core@2.3.4` instead of the unhoisted `jasmine-core@2.6.4` that is in its own subdir.

**Comment by skeggse** [comment] 2017-06-22 08:10
Hmm, interesting. The bug I was hoping to demonstrate was actually an issue with `yarn`, but it seems this reproduction only showed an issue with `yarn check`. I'll try to follow up with an issue that demonstrates the more important issue.

Just a little more background: I was able to run `yarn`, and have a module reference a dependency that it could not resolve with node's module resolution algorithm.

**Comment by BYK** [comment] 2017-10-30 14:26
No longer happening on master so closing.

**Closed by BYK** 2017-10-30 14:26 UTC
Labels: cat-bug, triaged
