### ISSUE TITLE
` yarn outdated` crashes with @typopro/web-montserrat

### ISSUE THREAD

**Issue by graingert** [yarnpkg/yarn#1655] opened 2016-11-03 14:38 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
yarn outdated fails to work with @typopro/web-montserrat

**If the current behavior is a bug, please provide the steps to reproduce.**
```shell
git clone https://github.com/graingert/web-montserrat-failure.git
cd web-montserrat-failure
yarn install
yarn outdated
yarn outdated v0.15.1
error https://registry.yarnpkg.com/@typopro/web-montserrat: Not found
    at Request.params.callback [as _callback] (/home/graingert/.npm-packages/lib/node_modules/yarn/lib/util/request-manager.js:273:18)
    at Request.self.callback (/home/graingert/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/graingert/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/graingert/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
info Visit http://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**What is the expected behavior?**
should print nothing, as no package is outdated.

**Please mention your node.js, yarn and operating system version.**
node.js: v7.0.0
yarn: v0.15.1
operating system:
```shell
$ uname -a
Linux logophobia 4.8.0-26-generic #28-Ubuntu SMP Tue Oct 18 14:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```
```

**Comment by wyze** [comment] 2016-11-03 14:42
Duplicate of #620 and fixed by #1276. Works on master and will be in the next release.

**Closed by wyze** 2016-11-03 14:42 UTC

**Comment by camjc** [comment] 2016-11-06 23:10
@wyze Any idea when that'll be? Where/whats the release policy? Thanks :)

**Comment by wyze** [comment] 2016-11-06 23:45
I can't say for sure, but if we are on a 2 week release cycle, then one should be out this week.

**Comment by graingert** [comment] 2016-11-06 23:50
What if you're on like a monthly release cycle?

**Comment by wyze** [comment] 2016-11-07 00:03
There will be nightly builds coming soon so people can live on the bleeding edge.

/cc @Daniel15

**Comment by Daniel15** [comment] 2016-11-07 00:05
Yeah :) https://github.com/yarnpkg/website/pull/245 adds the documentation for nightly builds. See http://nightly.yarnpkg.com/ also.

Since you're on Ubuntu, you can try our nightly build repo if you want the very latest version of Yarn:
```
echo "deb http://nightly.yarnpkg.com/debian/ nightly main" | sudo tee /etc/apt/sources.list.d/yarn-nightly.list
```

Or you can grab a `.deb` directly: `https://nightly.yarnpkg.com/latest.deb` then use `dpkg -i` to install it.
