### ISSUE TITLE
Bug: --frozen-lockfile doesn't throw when a pattern is removed

### ISSUE THREAD

**Issue by NameFILIP** [yarnpkg/yarn#4440] opened 2017-09-13 18:43 UTC
In my project, a major version of a private module dependency in the `package.json` has changed from `^5.1.0` to `^6.1.14`. The `yarn.lock` file was not updated (the change was made either though npm or manually). At this point, `package.json` and `yarn.lock` should be out of sync and I expect `yarn install --frozen-lockfile` to fail, but it doesn't.

Here is my Terminal log
```
➜  my-repo git:(master) node -v
v6.10.0
➜  my-repo git:(master) yarn -v
1.0.2
➜  my-repo git:(master) sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29

➜  my-repo git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

➜  my-repo git:(master) yarn install
yarn install v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 14.38s.

➜  my-repo git:(master) ✗ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")

➜  my-repo git:(master) ✗ git checkout yarn.lock
➜  my-repo git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean

➜  my-repo git:(master) yarn install --frozen-lockfile
yarn install v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
...
[4/4] 📃  Building fresh packages...
✨  Done in 14.09s.
➜  my-repo git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
```

On `yarn@1.0.1` the result of the last step was different, the `yarn.lock` file was generated with `yarn install --frozen-lockfile` (might be related to https://github.com/yarnpkg/yarn/issues/4344).

I tried simplifying the problem, but then it works fine.

**Comment by NameFILIP** [comment] 2017-09-13 18:56
More details on this:
Looks like the newer version `^6.1.14` was already in the lock file (due to some other dependencies), so running `yarn install` generates a new file which simply removes unneeded `^5.1.0`, but doesn't add anything new. Is not failing with `--frozen-lockfile` in this case an expected behavior?

**Comment by BYK** [comment] 2017-09-13 20:52
@NameFILIP thanks a lot for the report and especially for digging into the potential cause! I think not detecting removed patterns is a bug. Would you like to try fixing it with a PR? The code that throws the error on a mismatch is here: https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L359-L363

It looks like it only looks for missing patterns in the lockfile but not for extraneous ones.

**Comment by BorntraegerMarc** [comment] 2017-09-15 13:49
@BYK could this issue also be the root cause for https://github.com/yarnpkg/yarn/issues/4454 ?

**Comment by BYK** [comment] 2017-09-16 18:08
@BorntraegerMarc I don't think so. #4454 looks more like a lack of accounting for the new `resolutions` field and the `flat` mode when checking for the lockfile.

**Comment by kaylieEB** [comment] 2017-10-28 19:34
@NameFILIP @BYK I can't repro this on latest master. Am I missing something?
<img width="713" alt="screen shot 2017-10-28 at 12 33 23 pm" src="https://user-images.githubusercontent.com/18429494/32137829-47c253ee-bbdc-11e7-8b62-a2eb2bfe4f3d.png">

**Comment by BYK** [comment] 2017-10-30 14:38
Closing since I cannot reproduce this locally. @NameFLIP - feel free to reopen with repro steps if this is still an issue.

**Comment by NameFILIP** [comment] 2017-11-24 16:01
The issue still exists. Here is a simple configuration to reproduce it. I tried adding a test, but it's kind of complicated and not clear how to specify custom `package.json` and `yarn.lock` files.

Clone the repo:
```
git clone https://github.com/NameFILIP/yarn-issue-4440
```

And then:
```
➜  yarn-issue-4440 git:(master) yarn install --frozen-lockfile
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 0.23s.
➜  yarn-issue-4440 git:(master) git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
➜  yarn-issue-4440 git:(master) yarn install
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 0.23s.
➜  yarn-issue-4440 git:(master) ✗ git status  
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by Gudahtt** [comment] 2018-08-24 02:43
This looks like the same problem as #5840

**Comment by paul-soporan** [comment] 2021-01-02 22:24
Closing as this has been fixed in the v2.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-02 22:24 UTC
Labels: cat-bug, help wanted, needs-confirmation, triaged
