### ISSUE TITLE
Command failed with exit code 1.

### ISSUE THREAD

**Issue by arora01gunjan** [yarnpkg/yarn#5101] opened 2017-12-18 00:41 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I am trying to run my nightwatch tests on Mac OS. It goes through all the tests , says "finished" but the action is not performed.( No browsers open etc).
And in the end it gives me:
Command failed with exit code 1.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

Yarn is 1.3.2
Node is 8.9.3

**Comment by arora01gunjan** [comment] 2017-12-18 00:44
I am trying to run my nightwatch tests  on Mac OS. It goes through all the tests , says "finished" but the action is not performed.( No browsers open etc).
And in the end it gives me:
Command failed with exit code 1.
Yarn is 1.3.2
Node is 8.9.3

**Comment by rally25rs** [comment] 2017-12-18 00:52
Yarn should just spawn a shell and run the command. Can you make a small reproducible example that we can debug?

**Comment by rally25rs** [comment] 2017-12-28 03:57
Closing due to 10 days without activity. If you can provide an example, we can re-open this.

**Closed by rally25rs** 2017-12-28 03:57 UTC
Labels: needs-repro-script, triaged

**Comment by Safouene-Crow** [comment] 2018-02-27 14:41
i just got the same problem when trying to run my gateway and the probleme got fixed with yarn autoclean then yarn init you set it then yarn start went well without error and got my gateway back
