### ISSUE TITLE
`yarn version` this should act same as `npm version`

### ISSUE THREAD

**Issue by FDiskas** [yarnpkg/yarn#2638] opened 2017-02-05 17:36 UTC
**Do you want to request a *feature* or report a *bug*?**
**BUG**

**What is the current behavior?**
`yarn version` returns current version of yarn cli

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install yarn `v0.19.1`. 
1. Run `npm init -y`
1. Run `yarn version`

**What is the expected behavior?**
After executing a command `yarn version` - it should ask a version number then update the current package.json file, commit the new tag and so on. See the docs https://yarnpkg.com/docs/cli/version/

**Please mention your node.js, yarn and operating system version.**
Node: v7.3.0
NPM: 4.1.1
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64

**Comment by jacobmischka** [comment] 2017-02-06 00:07
The [docs](https://yarnpkg.com/docs/cli/version) suggest it's supposed to work like npm, but it just spits out the version of yarn as mentioned above.

**Comment by markstos** [comment] 2017-02-06 12:56
Duplicate of #2491.

 Fix will be released in 0.20.1.

This issue can be closed.

**Comment by FDiskas** [comment] 2017-02-06 13:15
:dash: Please add some tests or something - and do not broke the main API for "yarn". In some cases this issue is the critical

**Comment by markstos** [comment] 2017-02-06 13:35
@FDiskas rather than complaining about the lack of test coverage here, you could contribute some. [Another volunteer](https://github.com/yarnpkg/yarn/pull/2510#issuecomment-276730118) is already planning to look at some test coverage, but it's not too late for you to help.

**Closed** 2017-02-14 12:02 UTC
