### ISSUE TITLE
Question: how are git packages resolved?

### ISSUE THREAD

**Issue by fabien** [yarnpkg/yarn#1453] opened 2016-10-25 18:27 UTC
With `npm` any `git+ssh://` url-based package was downloaded with every `npm install` regardless of using tags, commits - if you updated you pushed your dependency to github, `npm` would fetch it on the next install. 

This was of course rarely desirable - they were fetched even if you 'locked' them to a specific commit, contributing to very long install times.

With Yarn, and it's offline caching mechanism, I am not sure how these situations are handled. From what I've seen, the cache will indeed be used. I wonder how these package versions are resolved. 

Is the `package.json` of the git-based consulted for a semver version number, for instance? In other words, how should I go about, using git(hub) hosted packages optimally with Yarn?

In order to use the cache, but also install updated versions when needed? I think `yarn upgrade` does indeed fetch the latest versions from github, though. EDIT: not quite, I'm having trouble installing an updated version of such a dependency - I had to remove my `~/.yarn*` stuff first.

**Comment by fabien** [comment] 2016-10-25 19:20
Update: it seems I cannot re-install a github hosted package that I just updated:

```
$ rm -Rf ~/.yarn
$ rm -Rf node_modules/
$ rm yarn.lock
$ yarn install
```

The file was clearly updated on github, yet the package installed is still from a previous revision, even though I haven't specified any tag or commit.

**Comment by fabien** [comment] 2016-10-25 19:33
Another update: it does indeed seem to work when I increment the version number of the `package.json` of the dependency itself. When I rand `yarn upgrade` it was picked up, whereas before, it just didn't work, no matter what I tried (above).

Question remains: can I force-install and force-fetch dependencies from git(hub)?

**Comment by VojtechBartos** [comment] 2016-10-27 09:02
@fabien just came into same issue and incrementing the version number worked. Thanks!

**Comment by panrafal** [comment] 2016-10-28 06:14
This is probably a duplicate of #1278

**Comment by voxsim** [comment] 2017-04-28 16:59
@bestander we can close it

**Closed** 2017-04-28 18:28 UTC
Labels: needs triage
