### ISSUE TITLE
yarn init with existing package.json

### ISSUE THREAD

**Issue by dragosbulugean** [yarnpkg/yarn#2402] opened 2017-01-06 11:36 UTC
Node v.6.9.1 yarn v0.18.1

I have a package json that contains a complex object as a "repository" value like this:
```
{ 
    ...
    "repository": {
        "type": "git",
        "url": "mygitrepourl"
    }
    ...
}
```

Running yarn init outputs the following:
```error An unexpected error occurred: "Cannot convert object to primitive value".```

I can make a pull request for this if I'm allowed.

Cheers,
Dragos

**Comment by torifat** [comment] 2017-01-08 06:14
Duplicate of #1924

**Closed by torifat** 2017-01-08 06:14 UTC
