### ISSUE TITLE
Yarn init fails on Windows under Git bash / MinGW / Cygwin

### ISSUE THREAD

**Issue by lewiswalsh** [yarnpkg/yarn#743] opened 2016-10-11 21:24 UTC
Under Git Bash on Windows when entering 'yarn init' I get the following error:

 error Can't answer a question unless a user TTY
    at ConsoleReporter.question (C:\Program Files (x86)\Yarn\lib\reporters\console\console-reporter.js:189:29)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli\commands\init.js:91:38)
    at next (native)
    at step (C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at run (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Other yarn commands seem to work as expected.

Yarn v0.15.1
Node v6.0.0
Windows 10 Pro 1607

**Comment by Daniel15** [comment] 2016-10-11 22:30
Seems like this is an issue with Cygwin and MinGW in that they're not 'proper' TTYs: https://github.com/nodejs/node/issues/3006

**Comment by oliversalzburg** [comment] 2016-10-12 17:27
Well, one thing you could do would be to remove the check ;)

In all seriousness though. It is my understanding that the check is in place because you're trying to make sure that the I/O scenario that is about to happen will work. Does that check actually achieve this? Will the scenario actually fail in MinGW? If not, then a different check should be performed or it should be omitted completely IMHO.

**Comment by Daniel15** [comment] 2016-10-12 18:34
My understanding is that the check is to stop the process hanging indefinitely when not using a TTY (for example, if running as part of a build process). In theory, if there's no TTY, there's no way to accept input. May be the check should "if it's a TTY **or** if it's MinGW" to handle this case specifically?

**Comment by jdalton** [comment] 2016-10-13 23:09
FWIW `npm init` works in WSL but `yarn init` errors.

**Comment by Daniel15** [comment] 2016-10-16 05:45
Yeah, I just noticed that `npm init` is fine. Sounds like we should take a look at how npm is handling it 😄

**Comment by oliversalzburg** [comment] 2016-10-19 09:02
> Sounds like we should take a look at how npm is handling it
They're simply [not enforcing `isTTY`](https://github.com/npm/npm/search?utf8=%E2%9C%93&q=isTTY&type=Code).

**Comment by Daniel15** [comment] 2016-10-21 05:01
Ahh, that's an interesting approach @oliversalzburg. I guess it means trying to run it in a script would result in the script "freezing" as it sits waiting for user input. Not ideal 😕 

Maybe we could do that just for Git Bash and Cygwin - Only check isTTY on platforms that properly support it

**Comment by maybeec** [comment] 2016-11-03 07:57
I also face this issue, so I run `node -p -e "Boolean(process.stdout.isTTY)"` on git-bash as well as on windows cmd. Both return `true`, which does not fit to the behavior of git-bash and cmd as discussed here, right? Or is there anything I misunderstood regarding the isTTY discussion?

Yarn version: 
  0.16.1
Node version: 
  4.4.5
Platform: 
  win32 x64

**Comment by maybeec** [comment] 2016-11-03 08:00
btw. same for nodejs 6.9.1

**Comment by ShailynOrtiz** [comment] 2016-11-16 03:44
How is this going ?
Still working on this ? I'm facing this issue at the moment.

**Comment by karlpatrickespiritu** [comment] 2016-11-21 12:18
Hope this will be fixed soon.

**Comment by thetrompf** [comment] 2016-12-12 18:03
I really don't get why it fails, yarn uses the "proper" way for testing this in https://github.com/yarnpkg/yarn/blob/7fe2e53a59d5c5d256459854dd7ad4d4ff874682/src/reporters/console/console-reporter.js#L173

by testing for `process.stdout.isTTY`

I'm using `minTTY` which is bundled in `Git for Windows` along side with `Git bash` as well.

```
Node: v7.2.1
Yarn: v0.17.10
```

```bash
bkc@DESKTOP-NNSLT74 ~ $ node
> process.stdout.isTTY
true
>
(To exit, press ^C again or type .exit)
>
bkc@DESKTOP-NNSLT74 ~ $ cd workspace/ts-test/
bkc@DESKTOP-NNSLT74 ~/workspace/ts-test (master) $ yarn init
yarn init v0.17.10
error An unexpected error occurred: "Can't answer a question unless a user TTY".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\bkc\\workspace\\ts-test\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
bkc@DESKTOP-NNSLT74 ~/workspace/ts-test (master) $
```

**Comment by thetrompf** [comment] 2016-12-12 18:20
Interestingly enough if I install yarn as a dependency, to a project
```
yarn add yarn
```

and in invoke yarn via node and yarn.js it works fine.

```
node ./node_modules/yarn/bin/yarn.js init
yarn init v0.17.10
question name (yarn-test):
```
So it must have something to do with the native windows version?

**Comment by thetrompf** [comment] 2016-12-12 18:25
Now it gets really weird, if I omit the `node` part, and try to invoke

```
./node_modules/yarn/bin/yarn.js init
```

as an executable, it fails.

**Comment by Daniel15** [comment] 2016-12-13 02:26
@thetrompf 

> So it must have something to do with the native windows version?

It's possible - Running "yarn" on Windows actually goes through either a batch file (when using a regular terminal like cmd.exe, Cmder, etc) or a shell script (when using something Bash-based like MinGW, Cygwin, etc). If you installed to the default location, it's at `C:\Program Files (x86)\Yarn\bin\yarn.bat`.

**Closed** 2016-12-13 02:30 UTC
Labels: windows

**Comment by ArtistsTechGuy** [comment] 2017-01-20 07:01
I fixed this by updating my git for windows to the latest version, it looks to be a problem with winpty.exe I also updated to the latest nightly version of yarn v0.20.0 as there was a patch concerning this applied in version 0.19.

node.js - v6.9.4 | yarn - v0.20.0-20170117.1018 | git for windows - 2.11.0.3 with MinGW teminal

**Comment by JaysQubeXon** [comment] 2017-02-27 08:52
I second with ArtistsTechGuy, upgrading to latest versions solved the issue.

**Comment by astudio8** [comment] 2017-05-20 23:45
Even upgrading Git to the latest version, it fails for me:

yarn init (yarn 0.24.5)
error An unexpected error occurred: "Can't answer a question unless a user TTY".

**Comment by ilatypov** [comment] 2017-05-26 15:43
Cygwin's mintty returns false to ``node -p -e "Boolean(process.stdout.isTTY)"``.

**Comment by rofrol** [comment] 2017-05-30 20:10
I got the same error as @astudio8

```
$ yarn init
yarn init v0.24.5
error An unexpected error occurred: "Can't answer a question unless a user TTY".
info If you think this is a bug, please open a bug report with the information provided in "C:\\projects_personal\\react\\hyperscript-helpers-elm-like\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

```
$ git version
git version 2.13.0.windows.1
```

Windows 10

**Comment by lvlirko** [comment] 2017-06-28 21:25
Git Bash error ..
```$ yarn init
yarn init v0.24.6  
error An unexpected error occurred: "Can't answer a question unless a user TTY".
```
`$ git --version 2.13.1.windows.2`

-----

Good thing is, Windows PowerShell works without errors.

**Comment by aimergenge** [comment] 2017-07-06 02:09
Is there any solution now?
I has been waiting for this to fix since a long time ago.

**Comment by ScottyFillups** [comment] 2017-07-26 02:23
I think I have a solution. Add the following to your .bashrc file:

`alias yarn='node "C:\Program Files (x86)\Yarn\bin\yarn.js"'`

Running `yarn init` should work now, maybe, hopefully... It works on my PC, at least.

**Comment by andreysobal** [comment] 2017-07-26 14:20
I had the same problem.
When use Git Bash under console emulator ConEmu, this problem don't arise.

**Comment by jmathew** [comment] 2017-09-18 20:18
I don't think `process.stdout.isTTY` is the command you want to test if yarn is being executed interactively.

The 'yarn' command under git bash executes a script that in turn `exec`s node with an arg for yarnjs. Unfortunately that means that _every_ yarn command is executed in a script (non-tty) environment from the perspective of `process.stdout.isTTY`.

```
$ bash -c "node -p -e \"Boolean(process.stdout.isTTY)\";"
false

$ node -p -e "Boolean(process.stdout.isTTY)"
true
```

Perhaps this is a node bug because if you check for a tty with shell commands you get the expected output:

somescript.sh
```
    #!/bin/sh
    if [ -t 1 ] ; then echo terminal; else echo "not a terminal"; fi
    tty
    node -p -e "Boolean(process.stdout.isTTY)"
```

```
$ ./somescript.sh
terminal
/dev/pty0
false
$ ./somescript.sh | cat
not a terminal
/dev/pty0
false
```

Notice in both cases node returns false however, in the first case the output is clearly a terminal. 

This kind of checking seems a bit complicated. At least according to [How to detect if my shell script is running through a pipe?](https://stackoverflow.com/a/30520299/730326). 

IMO I would remove the check. More trouble than its worth. Currently I'm bypassing the script using the alias provided by @ScottyFillups.

**Comment by lsvidal** [comment] 2017-09-27 19:11
As previously stated in this thread, the problem is TTY handling in git-bash. So successfully ran 'yarn upgrade-interactive' using 'winpty yarn.CMD upgrade-interactive' and latter aliased yarn to 'winpty yarn.CMD' in .bashrc

**Comment by jmathew** [comment] 2017-09-28 17:22
I think it's worth noting that sometimes you want winpty and sometimes you dont. Though in 90% cases you're safe with it prefixed.

From what I can tell it boils down to:

Action | Such as? | Prefix with winpty? 
--------|----------------------| ----
Using `yarn` inside a pipe? | `yarn.cmd --version \| cat` | No 
Using an interactive `yarn` command? | `yarn.cmd init` | Yes 
Doing something outside a pipe and not interactive? | `yarn.cmd install` `yarn.cmd add` | Doesn't matter 


```
$ winpty yarn.cmd init
yarn init v1.0.2
error An unexpected error occurred: "canceled".
info If you think this is a bug, please open a bug report with the information provided in 

$ yarn.cmd init
yarn init v1.0.2
error An unexpected error occurred: "Can't answer a question unless a user TTY".
info If you think this is a bug, please open a bug report with the information provided in 

$ winpty yarn.cmd --version
1.0.2

$ winpty yarn.cmd --version |cat
stdout is not a tty

$ yarn.cmd --version | cat
1.0.2

```

**Comment by thetrompf** [comment] 2017-09-28 18:39
@jmathew see my pull request, which tries to fix this #4577

**Comment by jmathew** [comment] 2017-09-28 19:58
@thetrompf  I haven't tested it but the script change makes sense. Thanks!

**Comment by naguibihab** [comment] 2018-01-16 01:38
To me this was a pretty silly issue, `yarn init` or `yarn login` wouldn't work on git bash that gets installed with git for windows but they'd work on standard cmd
