### ISSUE TITLE
Yarn Install Error: TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kabirsikand** [yarnpkg/yarn#1085] opened 2016-10-15 00:31 UTC
**Do you want to request a _feature_ or report a _bug_?**
_Bug_

**What is the current behavior?**
When running `yarn` a second (or third or fourth, etc...) time in a repo:

```
$ yarn
yarn install v0.15.1
[1/4] 🔍  Resolving packages...
error TypeError: Cannot read property 'split' of undefined
    at Object.explodeHashedUrl (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/lib/util/version.js:8:20)
    at PackageRequest.getLocked (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/lib/package-request.js:133:59)
    at /Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/lib/resolvers/exotics/git-resolver.js:170:36
    at next (native)
    at step (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at /Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at GitResolver.resolve (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/lib/resolvers/exotics/git-resolver.js:195:7)
    at GitHubResolver.fork (/Users/blah/.nvm/v5.2.0/lib/node_modules/yarn/lib/resolvers/base-resolver.js:24:21)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
run `yarn upgrade` with a package.json like:

```
{
  "name": "foo",
  "version": "0.0.1",
  "description": "Settings for foo customers",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "postinstall": "bower install",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 5.0.0"
  },
  "author": "foo",
  "license": "UNLICENSED",
  "dependencies": {
    "foo-gooey": "file:../foo-gooey",
    "foo-tables": "file:../foo-tables"
  },
  "devDependencies": {
    "broccoli-asset-rev": "~2.4.2",
    "ember-ajax": "~2.0.1",
    "ember-cli": "~2.8.0",
    "ember-cli-app-version": "~1.0.0",
    "ember-cli-babel": "~5.1.6",
    "ember-cli-dependency-checker": "~1.2.0",
    "ember-cli-htmlbars": "~1.0.3",
    "ember-cli-htmlbars-inline-precompile": "~0.3.1",
    "ember-cli-inject-live-reload": "~1.4.0",
    "ember-cli-jshint": "~1.0.0",
    "ember-cli-mocha": "~0.10.4",
    "ember-cli-release": "~0.2.9",
    "ember-cli-sass": "~5.5.2",
    "ember-cli-sri": "~2.1.0",
    "ember-cli-test-loader": "~1.1.0",
    "ember-cli-uglify": "~1.2.0",
    "ember-data": "~2.8.0",
    "ember-data-hal-9000": "201-created/ember-data-hal-9000",
    "ember-export-application-global": "~1.0.5",
    "ember-load-initializers": "~0.5.1",
    "ember-resolver": "~2.0.3",
    "ember-simple-auth": "~1.1.0",
    "ember-sinon": "~0.5.1",
    "loader.js": "~4.0.1",
    "torii": "~0.8.0"
  }
}
```

Run `yarn` again.

**What is the expected behavior?**
It should install all packages.

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v5.2.0

$ npm --version
3.3.12

$ yarn --version
0.15.1
```

**Comment by wyze** [comment] 2016-10-15 13:38
I've tried to reproduce this but was unsuccessful. I noticed you are using `file:` dependencies. What do those look like? When I emulated those with just one dependency, everything is working fine. I am wondering if it is something in one of those packages that is causing yarn to trip up.

**Comment by bsr203** [comment] 2016-10-15 22:33
same issue. I too have it started after having `file:` in deps

**Comment by kabirsikand** [comment] 2016-10-17 17:19
This issue seems to be isolated to the `file:` dependencies. Removing them allowed the install to run without a hitch.

That being said, we do need those dependencies.

**Comment by wyze** [comment] 2016-10-17 17:34
@kabirsikand It might be something to do with the `yarn.lock` file. Are you able to share that here so I can look at it further?

**Comment by serhalp** [comment] 2016-10-22 16:45
I've identified reduced repro steps:
```
$ mkdir yarn-1085 && cd yarn-1085 && yarn init -y && yarn add Nikku/node-browserify.git#local-fix
yarn add Nikku/node-browserify.git#local-fix
yarn add v0.16.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred, please open a bug report with the information provided in "/Users/serhalp/Projects/yarn-1085/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Works as expected with npm:
```
$ mkdir yarn-1085-npm && cd yarn-1085-npm && npm init -y && npm install --save Nikku/node-browserify.git#local-fix && jq .dependencies package.sjon
{
  "browserify": "github:nikku/node-browserify#local-fix"
}
```

Here are the contents of `yarn-error.log`:
```
Arguments: 
  /usr/local/opt/nvm/versions/node/v4.6.1/bin/node /usr/local/opt/nvm/versions/node/v4.6.1/bin/yarn add Nikku/node-browserify.git#local-fix

PATH: 
  /usr/local/opt/nvm/versions/node/v4.6.1/bin:./node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  0.16.0

Node version: 
  4.6.1

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "yarn-1085",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT"
  }

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Cannot read property 'split' of undefined
      at Function.parseRefs (/Users/serhalp/Projects/yarn/lib-legacy/util/git.js:445:20)
      at /Users/serhalp/Projects/yarn/lib-legacy/resolvers/exotics/hosted-git-resolver.js:144:50
      at next (native)
      at step (/Users/serhalp/Projects/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/serhalp/Projects/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at run (/Users/serhalp/Projects/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
      at /Users/serhalp/Projects/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (/Users/serhalp/Projects/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
      at nextTickCallbackWith0Args (node.js:420:9)
      at process._tickCallback (node.js:349:13)
```

I've identified the root cause and a fix, and I'm working on a PR.

**Comment by serhalp** [comment] 2016-10-22 17:19
So there are a few different things going on here, some of which are obscuring others.

First, yarn makes [this request](https://github.com/yarnpkg/yarn/blob/0c5bd61b5b50c376ffe37a3bb951d2b3bbe19ed1/src/resolvers/exotics/hosted-git-resolver.js#L84-L87) to hosted git repos to resolve the ref specified in the URL:
```
${url}/info/refs?service=git-upload-pack
```

and yarn's request manager handles 400s, 403s, and 404s by returning `false` but does not handle 401s. GitHub appears to respond with a 401 and a response body of "Repository not found" when attempting to hit the above path for a repo that does not exist:

```
curl -v https://github.com/Nikku/foofoodoesnotexist123.git/info/refs?service=git-upload-pack
*   Trying 192.30.253.112...
* Connected to github.com (192.30.253.112) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /Nikku/foofoodoesnotexist123.git/info/refs?service=git-upload-pack HTTP/1.1
> Host: github.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 21
< WWW-Authenticate: Basic realm="GitHub"
< X-GitHub-Request-Id: 49E7878C:24241:3A5E384:580B9B32
< X-Frame-Options: DENY
< 
* Connection #0 to host github.com left intact
Repository not found.
```

which then [is of course truthy](https://github.com/yarnpkg/yarn/blob/0c5bd61b5b50c376ffe37a3bb951d2b3bbe19ed1/src/resolvers/exotics/hosted-git-resolver.js#L89) and gets parsed in all sorts of incorrect ways then [passed through to `Git.parseRefs`](https://github.com/yarnpkg/yarn/blob/0c5bd61b5b50c376ffe37a3bb951d2b3bbe19ed1/src/resolvers/exotics/hosted-git-resolver.js#L107) which parses this in still more incorrect ways, until finally we get a `line` [here](https://github.com/yarnpkg/yarn/blob/0c5bd61b5b50c376ffe37a3bb951d2b3bbe19ed1/src/util/git.js#L346) which is an empty string, and thus `sha` is `''` and `id` is `undefined`.

Finally, in the test case I provided, this all occurs (unrelatedly) because the `user/repo.git#optional-commitish` format is not handled correctly, leading to a request to `https://github.com/Nikku/node-browserify.git.git/info/refs?service=git-upload-pack` (notice **.git.git**).

I'll get started on two PRs. Should I split this out into separate issues?

**Comment by wyze** [comment] 2016-11-03 15:29
Followed the steps to reproduce https://github.com/yarnpkg/yarn/issues/1085#issuecomment-255539369 and confirmed it is broken on `0.16.1`. Tested against the latest `master` version and it is installing successfully and no longer erroring. Going to close this out and it will be available in the next release!

**Closed by wyze** 2016-11-03 15:29 UTC

**Comment by bojars** [comment] 2016-11-21 11:33
With latest version to date 0.17.6 I get another error - `error An unexpected error occurred: "TODO".`

**Comment by asynchrony-ringo** [comment] 2017-01-25 18:36
We are having this very same issue in our repository after adding file:/ dependencies. We're using version 0.19.1 of yarn.

```
  TypeError: Cannot read property 'split' of undefined
      at Object.explodeHashedUrl (/Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/lib/util/version.js:8:20)
      at PackageRequest.getLocked (/Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/lib/package-request.js:127:59)
      at /Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:200:37
      at Generator.next (<anonymous>)
      at step (/Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at F (/Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/node_modules/core-js/library/modules/_export.js:35:28)
      at /Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
      at NpmResolver.resolve (/Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/lib/resolvers/registries/npm-resolver.js:235:7)
      at /Users/ringo/.nvm/versions/node/v7.4.0/lib/node_modules/yarn/lib/package-request.js:182:23
```

**Comment by joe307bad** [comment] 2019-09-27 18:22
For me this was an issue of trying to install a package from a git URL and the repository was empty.

**Comment by blikblum** [comment] 2019-09-30 01:33
> For me this was an issue of trying to install a package from a git URL and the repository was empty.

The same here. I had forgotten to push to the repository. 
A better error message would be helpful saving a ton of time

**Comment by kumavis** [comment] 2020-12-09 09:25
same here. forgot to push the repository to github
