### ISSUE TITLE
Why we should not use Bower but Yarn, while both download different codes for the same package?

### ISSUE THREAD

**Issue by notalentgeek** [yarnpkg/yarn#4795] opened 2017-10-28 22:31 UTC
For example:

    yarn add babel
    bower install babel

I have application running without server (I don't plan to use NodeJS as my back-end). It is now pure-front-end double-click HTML file.

I tried to import browser.js into my HTML file to be able to process JSX.

* Import with `<script src="node_modules/babel-core/lib/api/browser.js">` does not work.
* But, import with `<script src="bower_components/babel/browser.js">` __works__.

I do not want to download JavaScript manually from CDN. Because with Bower, it was not even a thing to do.

Apparently, the codes are different. Since, Bower is dead and it suggests its users to use Yarn, how can the codes be different?

How can I use Yarn like I use Bower?

**Comment by Daniel15** [comment] 2017-10-30 17:03
`browser.js` doesn't exist any more, you need to use babel-standalone. That's why it's not working. The only reason the Bower one is working is because it's installing a very old version of Babel (5.x) before `browser.js` was deprecated.

**Comment by BYK** [comment] 2017-11-01 13:16
I am closing this since this is not a bug or feature request :)

**Closed by BYK** 2017-11-01 13:16 UTC
