### ISSUE TITLE
Check on yarn cache size

### ISSUE THREAD

**Issue by karangoel16** [yarnpkg/yarn#7078] opened 2019-03-01 15:37 UTC
1.12.3
**Do you want to request a *feature* or report a *bug*?**

It is bug
**What is the current behavior?**
if the package to be installed on yarn is local ( yarn add ../local-module ) it treats everytime we install the package as separate package and then the size of the folder increases on windows machine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Keep installing the local folder again and again, the cache size of the yarn keeps growing

**What is the expected behavior?**
We should limit the cache size of yarn, thereby removing folder which have not been used for long time.

**Please mention your node.js, yarn and operating system version.**
Windows Operating System, I have not faced this issue of mac machine
11.4.0 (node)

**Comment by tobek** [comment] 2019-06-05 03:34
I ran into this issue on Linux too. Running `yarn add file:/path/to/module` created a new folder in yarn cache every time; it eventually grew to over 30gb, 90% of which was this one package I'd been installing locally:

```
$ ls ~/.cache/yarn/v4/ | grep civil-sdk                     
npm-@joincivil-civil-sdk-1.0.0
npm-@joincivil-civil-sdk-1.0.0-17adc120-356f-4b82-8364-6c1313f3ea3a-1559687187641
npm-@joincivil-civil-sdk-1.0.0-1ee82b45-4a4e-433f-87bf-311a6f3c20fc-1559670218240
npm-@joincivil-civil-sdk-1.0.0-33e2dacb74b1a69b7a8a77de2b29fb8a1cd71ad5
npm-@joincivil-civil-sdk-1.0.0-4cb32503-4763-48f4-98bd-8fe3767a2e33-1559694150483
npm-@joincivil-civil-sdk-1.0.0-51971086-ec69-45a8-9241-18b6aa87a296-1559692795786
npm-@joincivil-civil-sdk-1.0.0-5a9f0788-90ba-4326-afa2-b421e8203664-1559685861523
npm-@joincivil-civil-sdk-1.0.0-6147379a-1a3b-4cd1-9b11-9e481c241881-1559685437962
npm-@joincivil-civil-sdk-1.0.0-8c3aa978-e637-4b97-bc52-d00900511e69-1559686786074
npm-@joincivil-civil-sdk-1.0.0-a0688dde-bbb4-4cb8-a996-6b88d62d5b44-1559681305466
npm-@joincivil-civil-sdk-1.0.0-a64ed231-20bf-4085-aef8-1c5d1d616f15-1559668653680
npm-@joincivil-civil-sdk-1.0.0-b1f644c9-08ad-45fd-a931-01d2b97eea74-1559679996197
npm-@joincivil-civil-sdk-1.0.0-c6e64a43-5843-4bf6-8481-b393ba2f4b3e-1559688224986
npm-@joincivil-civil-sdk-1.0.0-d202aa72-e968-45b5-9c76-7253ad94aa74-1559672743846
npm-@joincivil-civil-sdk-1.0.0-ee2b32d0-7075-4341-8101-7287d753503b-1559689319849
npm-@joincivil-civil-sdk-1.4.0-298574272e3d73ff8fc807ce432024a2a0eb488d
```

**Comment by tobek** [comment] 2019-06-21 14:39
I think this is a duplicate of #6037

**Closed** 2021-07-25 04:34 UTC
