### ISSUE TITLE
'yarn outdated' doesn't look for registry.npmjs.org

### ISSUE THREAD

**Issue by wukann** [yarnpkg/yarn#1126] opened 2016-10-16 14:56 UTC
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**
When I used `yarn outdated` to confirm whether I could update `@angular/router`, `@angular/router` wasn't at `https://registry.yarnpkg.com`.
But, I tried to use `yarn info` to search `@angular/router`, it was at `https://registry.npmjs.org`.

`yarn outdated` doesn't look for registry.npmjs.org...

**If the current behavior is a bug, please provide the steps to reproduce.**
I tried to update `@angular/router`, using `yarn outdated`.
```
PS > yarn outdated

yarn outdated v0.15.1
error https://registry.yarnpkg.com/@angular/router: Not found
    at Request.params.callback [as _callback] (C:\Program Files (x86)\Nodist\bin\node_modules\yarn\lib\util\request-manager.js:273:18)
    at Request.self.callback (C:\Program Files (x86)\Nodist\bin\node_modules\yarn\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\yarn\node_modules\request\request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\yarn\node_modules\request\request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
info Visit http://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```
next, I tried to use `yarn info` to search `@angular/router`.
```
PS > yarn info @angular/router dist

yarn info v0.15.1
{ shasum: '14a496411142d29744b85996b4c4dd7e0eb76029',
  tarball: 'https://registry.npmjs.org/@angular/router/-/router-3.1.0.tgz' }
Done in 3.23s.
```

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
OS: Windows 10
node.js: 6.5.0
yarn: 0.15.1

**Comment by wyze** [comment] 2016-10-16 15:25
I think this is a duplicate of #620 and has the fix waiting to be merged in https://github.com/yarnpkg/yarn/pull/1071.

**Closed** 2016-10-16 17:15 UTC
