### ISSUE TITLE
yarn install hangs during "Linking dependencies"

### ISSUE THREAD

**Issue by haggholm** [yarnpkg/yarn#4029] opened 2017-07-26 22:05 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

yarn freezes during phase 3, "Linking dependencies". `strace` suggests that it’s getting stuck on mutex acquisition…?

**If the current behavior is a bug, please provide the steps to reproduce.**

Just `yarn` (or `yarn install`).

Unfortunately, I can’t provide a `package.json` that allows reproduction, as the project includes a slew of private packages. If it’s helpful I can provide an npm 5 `package-lock.json`.

**What is the expected behavior?**

Yarn should install packages.

**Please mention your node.js, yarn and operating system version.**

Node 8.2.1
Yarn 0.27.5
Fedora 25, kernel 4.11.8-200.fc25.x86_64

------

strace output:

```
write(9, "\33[2m[3/4]\33[22m Linking dependenc"..., 39) = 39
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30c4270, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
write(11, "\33[2K", 4)                  = 4
write(11, "\33[1G", 4)                  = 4
write(11, "\33[33mwarning\33[39m \"eslint-plugin"..., 104) = 104
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30c4270, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30c4270, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x308c248, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30853a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x308c248, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=106150000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
mmap(0x1020de8d2000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x1020de8d2000
munmap(0x1020de8d2000, 188416)          = 0
munmap(0x1020de980000, 335872)          = 0
mmap(0x1020de900000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x1020de900000
mmap(0x247bedc50000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x247bedc50000
munmap(0x247bedc50000, 196608)          = 0
munmap(0x247bedd00000, 327680)          = 0
mmap(0x247bedc80000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x247bedc80000
mmap(0x106296e42000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x106296e42000
munmap(0x106296e42000, 253952)          = 0
munmap(0x106296f00000, 270336)          = 0
mmap(0x106296e80000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x106296e80000
getpid()                                = 15195
futex(0x3085380, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=211749000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=314291000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
mmap(0x22a284f12000, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x22a284f12000
munmap(0x22a284f12000, 450560)          = 0
munmap(0x22a285000000, 73728)           = 0
mmap(0x22a284f80000, 524288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x22a284f80000
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=424220000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=528056000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=633616000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=736531000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=836422000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106051, tv_nsec=938597000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
futex(0x30ce068, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, {tv_sec=1501106052, tv_nsec=38382000}, 0xffffffff) = -1 ETIMEDOUT (Connection timed out)
getpid()                                = 15195
```

Then it continues with `futex`…`ETIMEDOUT`; I killed the Yarn process after 20 minutes or so (in the longest run I attempted).

**Comment by vinogradov** [comment] 2017-07-27 09:10
For me it hangs on `[1/4] 🔍  Resolving packages...` for a couple of minutes. After that goes normal.

**Comment by BYK** [comment] 2017-07-27 14:23
>For me it hangs on [1/4] 🔍 Resolving packages... for a couple of minutes. After that goes normal.

That means it doesn't hang at all? :D

**Comment by BYK** [comment] 2017-07-27 14:24
>Just yarn (or yarn install).

This obviously doesn't help since things are fine on many people's machines and on our CI machines. Can you please provide us a reproducible test script so this can be debugged and fixed if it is not a specific problem to your machine?

**Comment by haggholm** [comment] 2017-07-27 16:27
> Can you please provide us a reproducible test script so this can be debugged and fixed if it is not a specific problem to your machine?

Well…I’m frankly not sure how. As I said above, it happens with the `package.json` for a particular in-house package. Perhaps I wasn’t clear, but it doesn’t happen with *all* packages—it’s not that `yarn` doesn’t work for any package; it’s that it hangs when I try to install the dependencies for a particular one; but that particular package has a ton of private dependencies.

**Comment by BYK** [comment] 2017-07-27 16:34
@haggholm I understand that but without means of reproduction, we really cannot fix the issue. At least with as little information as you provide here.

I'd suggest trying the latest yarn from master or 0.28.4 to see if your problem is already fixed. If none works, I'd suggest creating a Docker container to try replicating the issue in an isolated environment. Also would help narrowing it down to see if all your colleagues and machines have the problem or not.

**Comment by AlainD-** [comment] 2017-08-22 08:12
Hi, I have the same kind of issue on Windows 7 using yarn `0.27.5` and node `8.4.0` in `nvm`:

```bash
$ yarn
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1129.56s.
```
(the console output above is not a from a fresh install, only one package's version has been updated in my package.json)

and here is my package.json if you want to reproduce (this is angular cli 1.3.1 project):

```json
{
  "name": "toolsuite",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --build-optimizer --aot",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.3.5",
    "@angular/cdk": "2.0.0-beta.8",
    "@angular/common": "4.3.5",
    "@angular/compiler": "4.3.5",
    "@angular/core": "4.3.5",
    "@angular/flex-layout": "2.0.0-beta.8",
    "@angular/forms": "4.3.5",
    "@angular/http": "4.3.5",
    "@angular/material": "2.0.0-beta.8",
    "@angular/platform-browser": "4.3.5",
    "@angular/platform-browser-dynamic": "4.3.5",
    "@angular/router": "4.3.5",
    "angularfire2": "4.0.0-rc.2",
    "core-js": "2.5.0",
    "css-element-queries": "0.4.0",
    "firebase": "4.3.0",
    "hammerjs": "2.0.8",
    "lodash": "4.17.4",
    "material-design-icons": "3.0.1",
    "ngx-perfect-scrollbar": "4.5.6",
    "normalize.css": "7.0.0",
    "rxjs": "5.4.3",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "@angular/cli": "1.3.1",
    "@angular/compiler-cli": "4.3.5",
    "@angular/language-service": "4.3.5",
    "@angular/platform-server": "4.3.5",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.2",
    "@types/lodash": "4.14.74",
    "@types/node": "8.0.24",
    "codelyzer": "3.1.2",
    "jasmine-core": "2.7.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.3.0",
    "tslint": "5.6.0",
    "typescript": "2.4.2"
  },
  "engines": {
    "node": "8.4.0",
    "npm": "5.3.0"
  }
}
```

Thank you.

**Comment by gorangajic** [comment] 2017-08-22 20:32
@haggholm does it freeze machine or just yarn process hangs? I am having issue where yarn freeze machine

**Comment by cyril-sf** [comment] 2017-09-29 17:11
We're seeing performance issues during the `Linking dependencies` phase too, but it's not consistent.

This happens in our internal Jenkins environment running Ubuntu 14.04.
Sometimes it works quickly
```

**Comment by cyril-sf** [comment] 2017-10-02 18:52
So I used the verbose mode to get a bit more details. The `Creating directory` phase is somewhat equivalent, the slowness appears when `copying` files.

**Comment by gorangajic** [comment] 2017-10-03 09:00
My issue was related to machine having low memory

**Comment by lanoxx** [comment] 2017-11-02 11:40
I just added these two dependencies and pushed to our CI server which runs on Linux:

    "karma-phantomjs-launcher": "^1.0.4",
    "phantomjs-prebuilt": "^2.1.15",

As a result yarn took 9 minutes just to install these two additional dependencies. Previously on my windows machine with npm installation of these packages was much faster.

yarn install v1.2.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "license-webpack-plugin@1.1.1" has unmet peer dependency "webpack-sources@>=1.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 532.79s.

**Comment by lanoxx** [comment] 2017-11-02 12:16
Just now it seemed to hang again. I killed it after almost 7minutes. When I restarted yarn it completed in 2 seconds.

**Comment by lanoxx** [comment] 2017-11-09 13:43
I just upgraded to v1.3.2 (node:9.1) and I still see this issue. It took 6 minutes and 30 seconds to install a bunch of packages (see [my dependencies](https://gist.github.com/lanoxx/c3791eeb305812f77e5ee7b00a27799f)). Most of that time was spend in the linking dependencies step.

**Comment by maplion** [comment] 2017-12-11 22:27
I am experiencing this on my work PC along with my colleagues.  Using the same project at home, I do not have any issues and yarn is very fast.  When at work, even with Anti-Virus off, white-listing, etc., it takes a really long time (upwards of 7 minutes) to link dependencies [3/4].  Is there something linking dependencies is doing network-wise that scanners would be slowing it down?  If so, is there a way to white-list what it is doing?

**Comment by rally25rs** [comment] 2017-12-28 04:03
For anyone who is having this issue, please run with `--verbose` and post the log. You might have to also pipe it to a file as the output can be quite large. The verbose log has some timestamps in it, so it might help find the issue.

**Comment by lanoxx** [comment] 2018-01-12 13:44
I have activated the verbose option. Currently it takes around 643 seconds to complete  for me. It seems that during the "Linking dependencies..." step yarn goes through every file of every package and determines if it needs to be copied from the cache folder to the node_modules folder. This takes about 638 seconds of the total 643 seconds

During that time there are thousands of lines that start with either one of the following:

> verbose 32.85 Skipping copying of file ... as the file at ... is the same size ... and mtime ... .
> verbose 620.005 Copying ... to ...
> verbose 627.832 Removing extraneous file ... 

I have mounted the yarn cache folder from the host into my docker container via `-v /mnt/jenkins/caches/yarn:/home/node/.cache/yarn`. Is this a problem of docker and how I mounted the cache into the build container, or is that an issue of yarn?

**Comment by lanoxx** [comment] 2018-01-15 11:59
One more thing. I observed the above behavior also with `--frozen-lockfile` enabled and in situations where the lock file did not change.

**Comment by BYK** [comment] 2018-01-15 12:05
>I have mounted the yarn cache folder from the host into my docker container via -v /mnt/jenkins/caches/yarn:/home/node/.cache/yarn. Is this a problem of docker and how I mounted the cache into the build container, or is that an issue of yarn?

This is because of the indirect file system as far as I can tell. All those `stat` operations over the network causes the slowdown.

>One more thing. I observed the above behavior also with --frozen-lockfile enabled and in situations where the lock file did not change.

`--frozen-lockfile` or having the same lockfile does not affect the linking phase, they only affect the resolution phase. Linking phase is "controlled" via `./node_modules/.yarn-integrity` file.

**Comment by BYK** [comment] 2018-01-15 12:08
@lanoxx if you want to reuse some package cache across the network, I'd recommend placing the cache folder on the same file-system and use the offline cache for the part that is on a different file system or over the network.

**Comment by lanoxx** [comment] 2018-01-15 18:25
I am not sure why there would be network traffic involved. I am running under Linux and mounting a volume into a docker container on the same host should yield speed close to native access. See also [here](https://docs.docker.com/docker-for-mac/osxfs-caching/):

> The current implementations of mounts on Linux provide a consistent view of a host directory tree inside a container: reads and writes performed either on the host or in the container are immediately reflected in the other environment, and file system events (inotify, FSEvents) are consistently propagated in both directions.

I am using Jenkins with a dedicated docker build container that is destroyed and recreated during every build. The yarn cache folder is on the same host and bind mounted into the container, to avoid having to redownload files again during each build. I would not know how that can be further optimized.

Note that I am not seeing the 10minutes+  build times during every build, often its as fast as 2 seconds. But then again for some reason the 10minutes+ build times are back.

**Comment by BYK** [comment] 2018-01-15 18:53
>I am not sure why there would be network traffic involved. I am running under Linux and mounting a volume into a docker container on the same host should yield speed close to native access. See also here:

Ah, sorry. For some reason I thought you were running Docker from Windows which would require a VM and network to mount the file system.

>I am using Jenkins with a dedicated docker build container that is destroyed and recreated during every build. The yarn cache folder is on the same host and bind mounted into the container, to avoid having to redownload files again during each build. I would not know how that can be further optimized.

Again, offline cache is a better way to do this. Give a read to https://yarnpkg.com/blog/2016/11/24/offline-mirror/

>Note that I am not seeing the 10minutes+ build times during every build, often its as fast as 2 seconds. But then again for some reason the 10minutes+ build times are back.

If you can trace this a bit more to see which parts are tacking the most time on the file system, this may really help. That phase is just stats on the file system which should not be _that_ slow.

**Comment by djbingham** [comment] 2018-02-19 12:22
Hey guys, I was getting this issue running `yarn add secure-password` but @gorangajic's comment reminded me that I have seen this issue several times in the past because of low memory. I run yarn in a Docker container on my dev machine so I increased the memory allocated to Docker from 2GB to 3GB and that resolved the issue - it took 96 seconds to run but I was running several other containers at the same time. I don't want to mess around too much now testing how fast it runs with more memory or stopping other containers but hope the info helps anyway.

If you're getting this problem and can't increase the memory available to yarn, I recommend posting how much memory you have available and how much is being used by yarn when it hangs so the folks can see whether its always a memory issue or if something else is going on.

**Comment by kevin-brown** [comment] 2018-02-28 04:04
We're running into this issue locally on our Jenkins build servers with Docker, fairly consistently too.

If we have 4 builds (on a 2 core machine) running `yarn install` at the same time, it appears to exhaust resources and hang, not doing anything. Eventually Docker will time out - the process won't die - which will leave the 4 install processes hanging around, and from that point on Docker will refuse to create/start any containers and run any image builds.

I haven't yet been able to get the output from running it with `--verbose` set or the output from `strace`.

**Comment by lanoxx** [comment] 2018-03-15 19:57
@BYK The solution using offline-mirrors worked very well for cases where the package.json and package-lock.json have not changed, but when there is a change then linking dependencies is still very slow.

**Comment by paul-soporan** [comment] 2021-01-02 14:58
Closing as fixed in v2 where the linking process has been revamped and is much more stable (and where no hangs have been reported so far, if it happens to you please open an issue in https://github.com/yarnpkg/berry).

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-02 14:58 UTC
Labels: needs-repro-script

**Comment by PayBas** [comment] 2023-04-20 11:56
Preliminary tests on my end show significant reduction of frozen `yarn install` occurrences on CI systems (without direct internet access) when using:
```
yarn config set disable-self-update-check true
```

**Comment by nethershaw** [comment] 2024-11-11 08:55
@paul-soporan Thank you for leaving this unfixed in yarn@1.22.22, which, naturally, virtually every project in the world is still pinned to.
