### ISSUE TITLE
Feature request: Only install devDependencies

### ISSUE THREAD

**Issue by peterjuras** [yarnpkg/yarn#998] opened 2016-10-13 13:42 UTC
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

`dependencies` are always installed and there is no command to prevent that.

**What is the expected behavior?**

Similar to `npm install --only=dev` a CLI option to only install devDependencies.

(My) usecase: Compile only environments where the resulting build will be used in a docker container (with a separate `yarn install`)

**Comment by coreyc** [comment] 2016-11-18 02:30
Is this still an open request?  If so, I was going to take a swing at it.

**Comment by wyze** [comment] 2016-11-18 13:31
Go ahead @coreyc.

**Comment by steebchen** [comment] 2016-11-18 19:14
@coreyc This would be incredibly cool.

**Comment by SharpEdgeMarshall** [comment] 2016-11-23 11:33
Actually we are having an issue that could be solved by this feature.
We are using docker-compose with 2 services one to compile (webpack) and one to run the server (web) and a shared volume for the build output.
Actually we are using a `.env` file to pass `NODE_ENV` var to both services

if we set `NODE_ENV=production` to test production behaviour the webpack service isn't able to compile because yarn will install only dependencies.

So the solution we are adopting is this in the webpack service: `command: bash -c "NODE_ENV=development yarn && NODE_ENV=development npm run build"`

It would be cool if we could specify to force install devDependencies even if `NODE_ENV=production`

**Comment by coreyc** [comment] 2016-11-23 15:54
@SharpEdgeMarshall I think this feature is slightly different than what you're talking about, but will take a look at it.  

Due to holiday week, been slightly delayed but I am working on this.

**Comment by SharpEdgeMarshall** [comment] 2016-11-24 16:46
I noticed after commenting that the feature requested by @peterjuras could completely solve our issue, exactly as him we have a build container and we could use ONLY devDepencies.
With --dev flag our cmd could became `command: bash -c "yarn --dev && npm run build"`

**Comment by joeyespo** [comment] 2016-11-24 19:22
@SharpEdgeMarshall I ran into something similar on Heroku, which sets both `NODE_ENV` and `NPM_CONFIG_PRODUCTION` variables. I think #1975 would help your case too.

In npm, `NPM_CONFIG_PRODUCTION` takes precedence over `NODE_ENV` for whether to install devDependencies. In Yarn, it's currently the opposite.

**Comment by nsgundy** [comment] 2017-02-06 13:45
@coreyc Thanks for the PR. Will you have time to finish it or would it be best to have someone else give it a try?

**Comment by coreyc** [comment] 2017-02-07 03:40
@nsgundy I had some open questions that weren't answered in the PR comments.  Re-familiarizing myself with the code now. Will update the PR soon.

**Comment by coreyc** [comment] 2017-02-10 03:13
@nsgundy thought i could spare some time to finish this, but can't make the time. you can look at the PR, it's close to being finished anyway.

**Comment by mirague** [comment] 2017-02-28 11:21
+1 would love to see this!

**Comment by bestander** [comment] 2017-04-28 15:39
duplicate of https://github.com/yarnpkg/yarn/issues/3254.

**Closed by bestander** 2017-04-28 15:39 UTC
Labels: enhancement
