### ISSUE TITLE
bundledDependencies are not handled properly causing issues and warnings

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3751] opened 2017-06-29 05:44 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```json
{
  "dependencies": {
    "npm": "^3.10.5"
  }
}
```
```bash
$ yarn
yarn install v0.27.0
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] Resolving packages...
warning npm > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
[3/4] Linking dependencies...
error An unexpected error occurred: "The same file /Users/bestander/work/temp/3202/node_modules/npm/node_modules can't be copied twice in one bulk copy".
info If you think this is a bug, please open a bug report with the information provided in "/Users/bestander/work/temp/3202/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Check introduced in #3712

Another example
```
yarn add nyc@11.0.3
```

**Comment by bestander** [comment] 2017-06-29 05:45
Scheduled to be released in 0.28 - either revert the check or find out why a folder is copied twice

**Comment by cibernox** [comment] 2017-06-30 20:12
FWIW, I've also experienced this using `--nightly` with the install script

**Comment by bestander** [comment] 2017-06-30 20:14
Thanks, I'll investigate + convert the check into a warning

**Comment by cibernox** [comment] 2017-06-30 20:17
Pinning to 0.27.3 works for me.

**Comment by bestander** [comment] 2017-06-30 20:18
Yeah, it is only in master right now

**Comment by bestander** [comment] 2017-07-04 07:03
The problem is in bundledDependencies.
Sending a PR to make the issues non breaking installation

**Comment by bestander** [comment] 2017-07-04 07:10
The bug is mitigated, the PRI can be lowered

**Comment by BYK** [comment] 2017-07-05 11:19
>The bug is mitigated, the PRI can be lowered

I think we should keep this high-prio and fix the underlying issue in 1.0

**Comment by silverwind** [comment] 2017-08-06 09:39
Still seeing these warnings on `yarn install npm` using v0.28.4.

**Comment by clintmod** [comment] 2017-09-10 03:52
@byk why no longer high priority? and why no longer in backlog?

**Comment by artlogic** [comment] 2017-09-10 16:19
Still happening in v1.0.1.

**Comment by BYK** [comment] 2017-09-10 16:29
@artlogic yup, aware. Will look into this.

**Comment by Howard-HS** [comment] 2017-09-13 08:16
not sure it it's a proper solution, remove yarn.lock then re-run yarn worked for me :)

**Comment by bestander** [comment] 2017-09-14 16:33
@sudo-suhas, that is a separate bug.
Afaik `yarn global list` actually runs install command :(

**Comment by sudo-suhas** [comment] 2017-09-15 03:15
@bestander I have created a separate issue for this - #4465

**Comment by fefoweb** [comment] 2017-09-15 13:14
Still happening in v1.0.2
----
node v6.11.2
yarn v1.0.2
mac osx 10.12.6

**Comment by mrG0bliN** [comment] 2017-09-16 11:42
NOT fixed 
λ yarn -v
1.0.2
λ node -v
v8.1.2

win10 x64

**Comment by BYK** [comment] 2017-09-16 11:46
@fefoweb @mrG0bliN the issue is still open and nowhere it says it is fixed so I'd appreciate not stating the obvious and keep the signal to noise ratio of the issue high.

**Comment by fefoweb** [comment] 2017-09-18 07:38
@BYK I just reported facts that could be helpful. it was not my intention to hurry up...

**Comment by BYK** [comment] 2017-09-18 13:45
@fefoweb thank you. Didn't mean to offend you or anything. Just saying, as long as the issue is open, it is not fixed so no need to repeat the existing and assumed information 😉 Sorry if I came as harsh or anything ❤️

**Comment by kriswill** [comment] 2017-09-18 17:46
@BYK Hi, I'm experiencing this issue also.  Perhaps, we could have a roll-up message for each immediate dependency that has duplicate file copies, something like:

> "warning The module "npm@4.5.1" has case-insensitive files that shouldn't be copied twice.  Please run yarn with `--verbose` for a complete listing."

At least this would reduce the amount of warning text that hits the screen during install.  The warning comes from:

https://github.com/yarnpkg/yarn/blob/0ee1c55fd55f3863a7544e40a774162764d29536/src/util/fs.js#L225

Maybe an approach would be to keep a `Map` of each module that encounters this issue, and report the above message only when it's first seen.  

Thanks for your time and attention on this matter!

**Comment by bestander** [comment] 2017-09-18 17:56
There is a flaw in the logic how folders are copied, probably because it all happens recursively.
It should not affect end users very much (files won't be copied twice) but I did not want the developers to loose this issue out of sight because this flaw may cause unexpected behavior in the future.

If anyone has some time to go deep into the reasons why it is happening and provide a fix that would be so awesome.

**Comment by BYK** [comment] 2017-09-18 19:07
@bestander I briefly looked at this a few days ago. Looks like it is due to us neglecting `bundledDependencies` completely. I think this is related to #4417

**Comment by adamreisnz** [comment] 2017-09-22 23:28
Why is this warning showing up at all if I may ask? Is this something package developers can do anything about? Let alone consumers of packages?

I'm literally being spammed with this error message with one particular repository generating about 150 of these warnings during a single install.

**Comment by BYK** [comment] 2017-09-23 13:36
I hear you @adamreisnz, thanks for sharing the frustration. I'll try to look into it this week but at the very least, we should just remove the warning.

**Comment by BYK** [comment] 2017-09-23 13:39
@adamreisnz can you share the package you are experiencing this issue with?

**Comment by BYK** [comment] 2017-09-23 13:40
I know this is 99% related to how bundledDependencies are handled but just want to make sure your case is also covered by that.

**Comment by clintmod** [comment] 2017-09-23 13:52
@BYK an example repo to reproduce is here: https://github.com/clintmod/koa-neo4j-secure-rest-api
the fsevents package (refd by nodemon) is causing the warnings via node-pre-gyp that look like:

The case-insensitive file /Users/clint/code/github/clintmod/koa-neo4j-secure-rest-api/node_modules/fsevents/node_modules/node-pre-gyp/lib/reveal.js shouldn't be copied twice in one bulk copy

**Comment by adamreisnz** [comment] 2017-09-23 20:55
@BYK thanks for looking into it. The following package.json was what was causing so many warnings about bulk copies for us (but in reality, since upgrading to yarn 1.x.x, any package/site I work on generates these warnings);

```
{
  "name": "foo",
  "description": "",
  "version": "1.0.0",
  "homepage": "foo",
  "author": {},
  "contributors": [],
  "license": "SEE LICENSE IN LICENSE.md",
  "private": false,
  "repository": {},
  "keywords": [],
  "engines": {
    "node": "^7"
  },
  "main": "scripts/server.js",
  "dependencies": {
    "aws-sdk": "^2.6.7",
    "bcrypt": "^1.0.2",
    "bluebird": "^3.5.0",
    "body-parser": "^1.17.1",
    "chalk": "^1.1.3",
    "compression": "^1.6.2",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.1",
    "express": "^4.15.2",
    "glob": "^7.1.1",
    "handlebars": "^4.0.6",
    "http-as-promised": "^1.1.0",
    "i18n": "^0.8.3",
    "md5": "^2.2.1",
    "meanie-express-error-handling": "^2.1.0",
    "meanie-express-jwt-service": "^2.0.2",
    "meanie-express-raven-service": "^1.2.0",
    "meanie-mail-composer": "^1.0.0",
    "meanie-mongoose-only-id": "^1.0.1",
    "meanie-mongoose-set-properties": "^2.0.2",
    "meanie-mongoose-to-json": "^1.0.6",
    "meanie-multer-mime-types-filter": "^1.0.1",
    "meanie-passport-refresh-strategy": "^1.2.0",
    "moment": "^2.18.1",
    "mongoose": "^4.9.1",
    "morgan": "^1.8.1",
    "multer": "^1.3.0",
    "passport": "^0.3.2",
    "passport-http-bearer": "^1.0.1",
    "passport-local": "^1.0.0",
    "sendgrid": "^4.8.4",
    "sendgrid-mailer": "^1.0.5",
    "yargs": "^8.0.1"
  },
  "devDependencies": {
    "babel-cli": "^6.23.0",
    "babel-preset-es2015": "^6.24.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "dirty-chai": "^1.2.2",
    "eslint": "^3.11.1",
    "express-simulate-latency": "0.0.2",
    "istanbul": "^1.0.0-alpha.2",
    "mocha": "^3.2.0",
    "mocha-clean": "^1.0.0",
    "nodemon": "^1.11.0",
    "sinon": "^2.2.0",
    "sinon-as-promised": "^4.0.0",
    "sinon-mongoose": "^2.0.1"
  }
}
```

**Comment by loopmode** [comment] 2017-09-24 14:43
Just my two cents here..not sure whether it's helpful. I started seeing this too today, but in my case, it's a module I installed from filesystem (`yarn add file:...`) and: I'm on Windows.
Have you guys replicated the issue on non-windows systems? Because.. I usually rest assured such issues are just because of Windows :)

**Comment by franzliedke** [comment] 2017-09-24 14:48
Happens on Linux as well.

**Comment by adamreisnz** [comment] 2017-09-24 19:40
And OSX

**Comment by tim-soft** [comment] 2017-09-25 05:33
I also see this error with the yargs lib. Doing a `yarn list yargs` reveals that my project actually has four different versions (and the same version twice?)

```
├─ browser-sync@2.18.13
│  └─ yargs@6.4.0
├─ localtunnel@1.8.3
│  └─ yargs@3.29.0
├─ nyc@11.2.1
│  └─ yargs@8.0.2
├─ webpack@3.6.0
│  └─ yargs@8.0.2
└─ yargs@3.10.0
```

I'm not sure how relevant this is to solving the problem but thought I'd share

**Comment by loopmode** [comment] 2017-09-25 06:07
@tim-soft I guess it's correct to see the same version twice because apparently, the main dependency is `@3.10.0` and any package that requires a version different from that has to include it in its own `./node_modules`. Happens to be twice.

**Comment by DarthFowla** [comment] 2017-09-25 19:26
Did a yarn install today and this showed up. It also indicated I should upgrade yarn to 1.1.0, but I get the same output.

warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/ansi-regex shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/camelcase shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/is-fullwidth-code-point shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/os-locale shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/path-type shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg-up shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/resolve-from shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/string-width shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/strip-ansi shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/ansi-regex/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/ansi-regex/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/ansi-regex/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/ansi-regex/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/camelcase/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/camelcase/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/camelcase/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/camelcase/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/is-fullwidth-code-point/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/is-fullwidth-code-point/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/is-fullwidth-code-point/package.json shouldn't be copied twice in one bulkcopy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/is-fullwidth-code-point/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex/browser.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/md5-hex/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/os-locale/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/os-locale/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/os-locale/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/os-locale/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/path-type/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/path-type/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/path-type/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/path-type/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg-up/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg-up/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg-up/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg-up/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/read-pkg/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/resolve-from/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/resolve-from/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/resolve-from/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/resolve-from/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/strip-ansi/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/strip-ansi/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/strip-ansi/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/strip-ansi/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/string-width/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/string-width/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/string-width/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/string-width/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module/CHANGELOG.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/which-module/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/CHANGELOG.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/completion.sh.hbs shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/yargs.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/apply-extends.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/argsert.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/assign.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/command.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/completion.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/levenshtein.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/obj-filter.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/usage.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/validation.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/lib/yerror.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/be.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/de.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/en.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/es.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/fr.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/hi.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/hu.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/id.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/it.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/ja.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/ko.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/nb.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/nl.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/pirate.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/pl.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/pt.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/pt_BR.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/ru.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/th.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/tr.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/zh_CN.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/locales/zh_TW.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/CHANGELOG.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/LICENSE.txt shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/README.md shouldn't be copied twice in onebulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/rosnet/stafflinq-ignite/node_modules/nyc/node_modules/yargs/node_modules/yargs-parser/lib/tokenize-arg-string.js shouldn't be copied twice in one bulk copy
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.1.0" while you're on "1.0.2".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash
✨  Done in 23.02s.

**Comment by BYK** [comment] 2017-09-26 11:18
Hi everyone! No need for more "happens to me" comments since we have a fairly good understanding of why and how this happens. We'll try to get at this ASAP, and at least suppress the warning since it is not useful to you, as the users.

Apologies for the trouble. In the meantime, if anyone is interested in giving this a shot until we do, feel free to ping me here or on Discord and I'd be happy to guide you!

**Comment by hulkish** [comment] 2017-10-05 23:47
Related: https://github.com/yarnpkg/yarn/issues/4275

I'd just like to point out that this is still very much an issue. Every yarn version thereafter `yarn@0.27.5` seems to barf when there is a dependency that specifies any `bundledDependencies`.

I'm a bit concerned with why `yarn@1.x.x` was released with this issue outstanding.

**Comment by iarna** [comment] 2017-12-06 22:34
There's a possibly related issue (or perhaps root cause):

As of 1.3.2 bundled dependencies are double installed. Once from the bundle, in the bundling module's `node_modules` and again into the top level project's `node_modules`. The latter are the only parts referenced in the lock file.

If the resolver ends up deciding one of those deps currently being installed at the top level has to be hoisted, I think that would cause the problems described here (with multiple of the same destination).

npm, fwiw, records all of the bundled modules in its lockfile, with annotations so it knows that they're sourced from the bundling tarball, not from stand alone downloads.

**Comment by bestander** [comment] 2017-12-07 00:31
Thanks for looking into this for us, @iarna, very much appreciated!

**Comment by BYK** [comment] 2017-12-07 11:20
@iarna the issue is the complete neglect of `bundledDependencies` in Yarn right now. Since they are already shipped inside the tarball they get "installed" when we extract the tarball. They get "reinstalled" when yarn simply carries on normal operations by resolving and installing the package's dependencies.

I think blacklisting any `node_modules` during linking would at least make the behavior sane and we can safely say "we do not support bundledDependencies at the moment". After that, we can start devising a proper solution which may include marking bundledDependencies and excluding them from global resolution.

**Comment by wangmeijian** [comment] 2018-05-23 09:58
m

**Comment by paul-soporan** [comment] 2021-01-03 20:43
Closing as we've completely removed support for `bundleDependencies` in v2, for the reasons stated here https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies. We aren't going to spend more time fixing them in v1.

**Closed by paul-soporan** 2021-01-03 20:43 UTC
Labels: cat-bug, help wanted, high-priority, triaged
