### ISSUE TITLE
Installation Problem: SyntaxError: Unexpected token | Fresh Install

### ISSUE THREAD

**Issue by ghost** [yarnpkg/yarn#7218] opened 2019-04-21 20:16 UTC
**Which operating system are you using:**
MacOS High Sierra

**Please describe the steps you took when trying to install Yarn and what went wrong:**

$ brew install yarn 

$ yarn --version 

Encountering SyntaxError from fresh install of Yarn via Homebrew.

`Mikes-MBP:~ mike$ yarn --version
/Users/mike/.nvm/versions/node/v5.12.0/lib/node_modules/yarn/lib/cli.js:45699
  let {
      ^

SyntaxError: Unexpected token {
    at NativeCompileCache._moduleCompile (/Users/mike/.nvm/versions/node/v5.12.0/lib/node_modules/yarn/lib/v8-compile-cache.js:226:18)
    at Module._compile (/Users/mike/.nvm/versions/node/v5.12.0/lib/node_modules/yarn/lib/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mike/.nvm/versions/node/v5.12.0/lib/node_modules/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)`

**Comment by andi1984** [comment] 2019-04-26 10:25
Same problem here on an Ubunut machine with stable version. Does not happen for example in 1.13. Must be something in 1.15 or 1.15.2.

**Comment by FabioMen10** [comment] 2019-05-02 08:11
Same here, but in Chrome OS.
`~$ yarn --version
/usr/share/yarn/lib/cli.js:45699
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)`

**Comment by FabioMen10** [comment] 2019-05-02 08:33
Solved! Reinstall Nodejs.
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by tomprogers** [comment] 2019-09-14 21:11
Reinstall does not fix the problem.

I'm using nvm to manage my node installs. I was using node v12.6.0. I reinstalled it and the problem remains.

The error occurs every time I open a new terminal. (So, it's in bashrc or bash_profile.)

**Comment by patsplat** [comment] 2019-11-15 00:45
To elaborate on @FabioMen10 's answers:

> Same here, but in Chrome OS.
> `~$ yarn --version

> Solved! Install or reinstall (in my case) the Nodejs.
> https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

The error is caused by the old 4.x.x version of nodejs in the debian distribution.  First install a more recent nodejs:

https://github.com/nodesource/distributions/blob/master/README.md

Then install yarn:

https://yarnpkg.com/en/docs/install#debian-stable

And it worked for me.

**Comment by AStoker** [comment] 2020-03-23 20:48
Updating node worked for me too. Was apparently running v5 of Node. Uninstalled Yarn completely with Brew, then reinstalled, saw the issue, found this post, updated node, and bam, everything works fine now.

**Comment by paul-soporan** [comment] 2021-01-03 16:43
Closing as you need to update Node.

**Closed by paul-soporan** 2021-01-03 16:43 UTC
