### ISSUE TITLE
`yarn add bunyan` does not install the package propelly

### ISSUE THREAD

**Issue by jhonore** [yarnpkg/yarn#2324] opened 2016-12-22 18:21 UTC
When I installed **bunyan** package with 
> yarn add bunyan

I got an error at runtime execution

```
{ Error: Cannot find module './build/Release/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jha/Workspace/personal/Services/web-services/express-service-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12) code: 'MODULE_NOT_FOUND' }
```

I deleted the package then install it with the conventional **NPM package manager** and all thing works perfectly.

**Comment by timlar** [comment] 2016-12-27 16:05
I have the same issue with `assets` module. 😞

**Comment by hpurmann** [comment] 2017-02-25 01:26
I cannot reproduce this. Is this still present for you in current `yarn 0.20.3`? If so, can you tell us your operating system and node version?

**Comment by timlar** [comment] 2017-02-25 11:58
@hpurmann I've found the solution. Just need to remove `.yarnclean` file, remove `node_modules` directory and execute `yarn install`.

**Comment by elyscape** [comment] 2017-05-30 21:03
That doesn't help for me with `yarn v0.24.6`. It looks like the issue is that the install script for dtrace-provider [makes some assumptions about the presence of and location of `node-gyp`][install], and those aren't true when invoked via `yarn`.

[install]: https://github.com/chrisa/node-dtrace-provider/blob/dbc47c8/scripts/install.js#L19-L33

**Comment by pi0** [comment] 2017-09-03 19:01
Another workaround:

Create a `.yarnclean` file and add this line:
```
dtrace-provider
```

**Comment by BYK** [comment] 2017-09-05 10:48
Closing since this looks like an issue with node-dtrace-provider and not yarn.

**Closed by BYK** 2017-09-05 10:48 UTC
