### ISSUE TITLE
`upgrade-interactive` on Yarn 1.0 not working properly.

### ISSUE THREAD

**Issue by retrixe** [yarnpkg/yarn#4259] opened 2017-08-25 12:04 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Run `upgrade-interactive` on a project which has no updates needed and it works except it doesn't show packages at all and keeps erroring until you `Ctrl+C` or whatever to force kill it.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Try `yarn global upgrade-interactive` and check if you have any updates. If you do, install them. Else, you will see the behaviour I expected.
- If you installed updates, then try `yarn global upgrade-interactive`.

You can also remove the `global` and try this on a test project.

**What is the expected behavior?**
It errors saying no package updates are available.

**Please mention your node.js, yarn and operating system version.**
Node v8.4.0 with tj/n
Yarn v1.0.0-20170824.2019
Ubuntu 17.04 x64

**Comment by rally25rs** [comment] 2017-08-25 13:14
Thanks for reporting this! I'll get it fixed up...

**Comment by BYK** [comment] 2017-08-25 13:24
@rally25rs do you this is a duplicate of #4116?

**Comment by rally25rs** [comment] 2017-08-25 13:46
Yep, duplicate. I hadn't noticed 4116 before seeing this. I marked my PR as closing both issues.

**Comment by BYK** [comment] 2017-08-25 13:55
Duplicate of #4116.

**Closed by BYK** 2017-08-25 13:55 UTC
Labels: bug
