### ISSUE TITLE
yarn upgrade scoped package doesnt seem to work

### ISSUE THREAD

**Issue by mbriggs** [yarnpkg/yarn#1518] opened 2016-10-27 16:46 UTC
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
`yarn upgrade @scope/package` on a package pinned with ^ syntax results in no packages getting upgraded, even when an upgrade is available. `yarn upgrade` however detects the available new version, and does the upgrade.

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn upgrade @scope/package`

**What is the expected behavior?**
that `yarn upgrade <package>` works the same as `yarn upgrade`, only restricting the attempted upgrade to the specified package.

**Please mention your node.js, yarn and operating system version.**

```
❯ yarn --version
0.16.1

❯ node --version
v6.6.0

❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

**Comment by evocateur** [comment] 2016-10-27 19:12
With this setup:
```
$ yarn --version
0.16.1
$ yarn init -y
$ yarn add @financial-times/n-bottle@1.0.0
$ yarn add async@2.0.0
```

`yarn upgrade` with no arguments does not upgrade either out-of-date dependency:
```
$ yarn upgrade
yarn upgrade v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 9 new dependencies.
├─ @financial-times/n-bottle@1.0.0
├─ async@2.0.0
├─ colors@1.1.2
├─ commander@2.9.0
├─ denodeify@1.2.1
├─ graceful-readlink@1.0.1
├─ lodash@4.16.4
├─ semver@5.3.0
└─ shellpromise@1.4.0
✨  Done in 0.81s.
```

This seems to contravene the docs on [`yarn upgrade`](https://yarnpkg.com/en/docs/cli/upgrade#toc-yarn-upgrade).

However, `yarn upgrade <package>` _does_ upgrade to the latest matching semver for the given package, even with scoped packages:
```
$ yarn upgrade @financial-times/n-bottle
yarn upgrade v0.16.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency
└─ @financial-times/n-bottle@1.1.1
✨  Done in 0.45s.
```

**Comment by mbriggs** [comment] 2016-10-27 19:14
@evocateur thats really weird, im seeing literally the opposite behaviour. mine is an npm private package, maybe that is part of the puzzle?

**Comment by evocateur** [comment] 2016-10-27 20:29
@mbriggs Indeed, I did not test any private packages! I wonder if the `upgrade` command is sending the same authentication as `install`/`add`?

**Comment by jeffbcross** [comment] 2016-10-28 23:45
I'm seeing the same behavior, yarn 0.14.0, `yarn upgrade @angular/core` gives me the message:
> error This command doesn't require any arguments.

**Comment by TheLudd** [comment] 2016-11-06 14:56
I just want to confirm that I experience the same error with private packages
`yarn upgrade @myscope/my-package` - no upgrade made even though upgrades are available
`yarn upgrade @myscope/my-package@newly-released-version` - the command finds the new version and works as expected

**Comment by maybeec** [comment] 2016-11-07 11:43
Maybe related: `yarn outdated` seems to have problems with scoped packages as well:

```
Trace: 
  Error: https://registry.yarnpkg.com/@angular/platform-browser: Not found
      at Request.params.callback [as _callback] (C:\Program Files (x86)\Yarn\lib\util\request-manager.js:294:18)
      at Request.self.callback (C:\Program Files (x86)\Yarn\node_modules\request\request.js:187:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\request\request.js:1048:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (C:\Program Files (x86)\Yarn\node_modules\request\request.js:969:12)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:185:7)
```

**Comment by wyze** [comment] 2016-11-07 14:24
@maybeec, It is not related, that bug is fixed on master.

**Comment by TheLudd** [comment] 2016-11-07 14:29
@wyze I don't know if it is related or not but the outdated bug is also present in `0.16.1` which is not necessarily the same as `master`. There seems to have been many commits since the latest release.

**Comment by wyze** [comment] 2016-11-07 14:55
@mbriggs I've tested this against the latest master and it is upgrading scoped packages for me. Could you give it another shot against master?

**Comment by torifat** [comment] 2016-11-24 13:50
Couldn't reproduce this with the latest release. Feel free to ping back if you face this again.

**Closed by torifat** 2016-11-24 13:50 UTC
Labels: bug
