### ISSUE TITLE
strict-ssl=false in .npmrc file is not use by yarn

### ISSUE THREAD

**Issue by francisoud** [yarnpkg/yarn#1333] opened 2016-10-21 08:46 UTC
As decribe in #841:
adding a .yarnrc file in project directory with:

```
cafile null
strict-ssl false
```

works.

But I already have such settings in my .npmrc file in the same project directory:
`strict-ssl=false`

I was expecting it to be picked-up, but it's not...

```
>yarn --version
0.16.0
>node --version
v6.7.0
>ver
Microsoft Windows [version 6.1.7601]
```

**Comment by pascalpp** [comment] 2016-10-23 16:53
Looks like a duplicate of https://github.com/yarnpkg/yarn/issues/1237

**Comment by pascalpp** [comment] 2016-10-23 16:56
Oh, sorry, this is about the location of the setting (in .npmrc vs .yarnrc)

**Comment by kittens** [comment] 2016-11-01 12:04
Created #1590 to fix this, pending approval.

**Closed by kittens** 2016-11-01 12:04 UTC

**Comment by donaldpipowitch** [comment] 2016-11-25 08:35
This doesn't seem to be fixed for me. I use a `.npmrc` containing `strict-ssl=false` in my project root:

```
$ yarn config list
yarn config v0.17.8
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.17.8 npm/? node/v6.9.1 darwin x64' }
info npm config
{ 'strict-ssl': false,
  progress: true}
✨  Done in 0.04s.
```

**Comment by krtek** [comment] 2017-02-02 09:07
Confirm. This is not fixed in yarn 0.20.0.

**Comment by francisoud** [comment] 2017-03-24 16:07
Still exist in yarn@0.21.3

**Comment by DeGuitard** [comment] 2017-04-19 14:18
And in yarn@0.23.2 as well.

**Comment by francisoud** [comment] 2017-04-20 09:57
@kittens Can you re-open it pls
You said it was [pending approval](https://github.com/yarnpkg/yarn/issues/1333#issuecomment-257550421) and I see the fix has been merged but the bug still exist...

**Comment by rally25rs** [comment] 2017-04-25 17:39
Also if the location for this setting is going to be in `.yarnrc` then it should be documented at: [https://yarnpkg.com/en/docs/yarnrc](https://yarnpkg.com/en/docs/yarnrc)

**Comment by rfgamaral** [comment] 2019-01-15 16:52
> @kittens Can you re-open it pls
> You said it was [pending approval](https://github.com/yarnpkg/yarn/issues/1333#issuecomment-257550421) and I see the fix has been merged but the bug still exist...

Can confirm, just bumped into this issue today... Surprised to see it as "fixed".

**Comment by balrogthane** [comment] 2019-12-18 23:05
Still not fixed in yarn@1.21.1

**Comment by rfgamaral** [comment] 2019-12-19 09:48
Can we please get this reopened?

**Comment by poppinlp** [comment] 2020-07-13 08:50
Seems still happened in 1.22.4. :)

**Comment by morigs** [comment] 2021-02-11 16:22
The issue is still causes problems in our ci/cd pipeline 😞 

This happens because yarn [defaults](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/registries/yarn-registry.js#L30) have preference over all other options. It merges into config [here](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/registries/yarn-registry.js#L120) and then used with the first priority [here](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/registries/yarn-registry.js#L66).

Possible solution is just removing [this line](https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/registries/yarn-registry.js#L120) but I need an advice from contributors about how this change can affect other modules

@sebmck what do you think?
