### ISSUE TITLE
The command: Yarn run  does not work like npm ?

### ISSUE THREAD

**Issue by kevincaradant** [yarnpkg/yarn#1402] opened 2016-10-24 14:02 UTC
Hi

**Do you want to request a *feature* or report a *bug*?**
Feature / Bug

**What is the current behavior?**
`It does not purpose the different tasks available in the package.json `

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn run TABULATION_KEY`
Any script showed

**What is the expected behavior?**
`yarn run TABULATION KEY` should purpose to me the different tasks 'dev', 'prod', 'build', 'serve' etc of my project like `npm run TABULATION_KEY`

**Please mention your node.js, yarn and operating system version.**
OS: Ubuntu 16.10 64 bits
YARN: 0.16.1
NODEJS: 6.9.1

Thank you

**Comment by kittens** [comment] 2016-10-24 14:16
Duplicate of #609.

**Closed by kittens** 2016-10-24 14:16 UTC
