### ISSUE TITLE
yarn add postcss@5.2.8 error

### ISSUE THREAD

**Issue by souse** [yarnpkg/yarn#2389] opened 2017-01-05 02:59 UTC
Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add postcss@5.2.8

PATH: 
  /opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

Yarn version: 
  0.18.1

Node version: 
  5.9.1

Platform: 
  darwin x64

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: ENOENT: no such file or directory, open '/Users/drank/Downloads/cpx-study/redux-devtools-example/node_modules/babel-core/node_modules/ms/LICENSE.md'
      at Error (native)

**Comment by bestander** [comment] 2017-02-27 14:54
Can't repro
```
yarn add v0.22.0-0
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
├─ has-flag@1.0.0
├─ js-base64@2.1.9
├─ postcss@5.2.8
└─ source-map@0.5.6
warning No license field
✨  Done in 3.13s.
```

**Comment by rally25rs** [comment] 2017-12-28 04:13
Closing because unable to reproduce, and old Yarn version.

**Closed by rally25rs** 2017-12-28 04:13 UTC
Labels: needs-confirmation
