### ISSUE TITLE
Angular 2 project : need separate `typings install`

### ISSUE THREAD

**Issue by PeterKassenaar** [yarnpkg/yarn#818] opened 2016-10-12 07:02 UTC
### Current behavior

After using `yarn install`  in an Angular 2 final (2.0.0) project with default settings (as described in Angular 2 Quickstart tutorial), subsequent `npm start` command fails. Apparently because typings haven't been executed/installed.
### expected behavior

`npm start` should run the the project without issues.
### Workaround

After executing `yarn install`, if you manually execute `typings install`, everything runs fine after executing `npm start`

**Please mention your node.js, yarn and operating system version.**-
- Mac OSX El Capitan 10.11.6
- NodeJS version 6.1.0
- Yarn version 0.15.1

**Comment by StephanBijzitter** [comment] 2016-10-12 07:16
Hmm, I have always had to do `typings install` after `npm install`. I would very much welcome this improvement, though.

**Comment by PeterKassenaar** [comment] 2016-10-12 08:19
Yes, Angular documentation says so (I believe something like 'if your typings folder doesn't show up, do a `typings install`). I however have never faced this issue, typings always automagically appeared after running `npm install`. 

With Yarn however I *always* have to do a `typings install`. It should save a step if this was executed automatically.

**Comment by br1anchen** [comment] 2016-10-12 08:21
I think it is related to #721 , usually Angular 2.0 project uses `postinstall` npm script to run `typings install`

**Comment by busches** [comment] 2016-12-01 21:00
Can you reproduce this with `yarn@latest`? I'm not able to recreate the issue using the latest [Angular QuickStart](https://github.com/angular/quickstart.git) and Yarn `v0.17.10`.

**Comment by br1anchen** [comment] 2016-12-01 22:04
@busches , I do not think you can reproduce this `postinstall` issue by using [Angular QuickStart](https://github.com/angular/quickstart), since it does not use `postinstall` to install typings, it uses `@types` npm packages.
I think tried Yarn `0.17.9` with `postinstall` task, it works fine. I think it was fixed in #721

**Comment by busches** [comment] 2016-12-01 22:07
@br1anchen if you have a use case that can replicate the issue and confirm it's closed, that would be ideal.

**Comment by PeterKassenaar** [comment] 2016-12-02 07:39
Yes, I can confirm it works with newer versions of Angular Quickstart. It worked since the @types versioning was introduced (I'm not sure in which version this was). So I feel the issue is correctly closed.

**Closed** 2016-12-02 13:42 UTC
Labels: needs triage
