### ISSUE TITLE
Install from a branch gets cached

### ISSUE THREAD

**Issue by redgenie** [yarnpkg/yarn#2280] opened 2016-12-17 05:47 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn is getting the same package from cache when using a branch even if the branch has new commits. Event after running `npm install <package>` and getting the new package, running `yarn` after will bring back the old cached package.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try installing a branch from a repository:
`"<package>": "git+ssh://git@github.com/<user>/<package>.git#<branch>",`
`yarn`, add new commits to `<branch>`, then `yarn` again. You will get a cached version without the new commits.

**What is the expected behavior?**
Since we are not specifying a version in `dependencies` but a branch, `yarn` should get the latest commit from the branch. `npm` works well.

**Please mention your node.js, yarn and operating system version.**
Node 7.2.1, yarn 0.17.10, macOS Sierra.

**Comment by bestander** [comment] 2017-01-14 19:14
Should be fixed now #2074.
Please reopen if the issue is still there

**Closed by bestander** 2017-01-14 19:14 UTC
Labels: needs triage

**Comment by Dmitra** [comment] 2017-08-10 12:42
can reproduce on node 8.3.0 yarn 0.27.5 Ubuntu 16.04

**Comment by Dmitra** [comment] 2017-08-10 14:43
@BYK can't reproduce on yarn 1.0.0-20170809.1554

**Comment by BYK** [comment] 2017-08-11 15:20
@Dmitra that means it is fixed on master, yay! And thanks :)

**Comment by xomaczar** [comment] 2017-10-11 03:46
Yarn@1.1.0 exhibits similar behavior.

node@6.11.1
yarn@1.1.0

**Comment by xomaczar** [comment] 2017-10-11 03:52
Same thing in yarn@1.2.0. The only way to force fetching is with ```yarn upgrade <package-name>```

**Comment by askielboe** [comment] 2017-10-13 13:57
Having the same issue. Have to run `yarn upgrade` after every `yarn install` to get the upgraded packages.

`yarn install`always picks some random old version. :(

**Comment by valorize** [comment] 2017-10-17 12:23
I vote for reopening this issue.

**Comment by xomaczar** [comment] 2017-10-17 12:52
Yes same here, this can cause an incorrect release being bundled in our production code...

**Comment by xomaczar** [comment] 2017-10-18 01:25
cc @bestander

**Comment by bestander** [comment] 2017-10-18 01:39
@xomaczar, could you open a new issue with a repro step please?

**Comment by askielboe** [comment] 2017-10-18 13:12
I've created a new issue with steps to reproduce: #4734
