### ISSUE TITLE
yarn add <package> automatically removes another dependencies

### ISSUE THREAD

**Issue by KangZiRu** [yarnpkg/yarn#4054] opened 2017-07-31 11:45 UTC
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
After I run `yarn add`, it's automatically removes another packages installed on my local node_modules

for example, I have installed `babel-cli`, `babel-core`, `gulp`, `gulp-livereload`, `gulp-stylus`, and `gulp-babel` via `yarn add`
and then I add `eslint` by running `yarn add eslint`, and it's automatically removed all packages I mentioned before.

yarn v0.27.5 on Windows 7 SP1

**Comment by roddypratt** [comment] 2017-08-03 13:24
I see very similar behaviour with 0.28.4 on Windows 10. Every time I install or remove a package it may - sometimes - leave the node_modules folder either partially or completely empty.

**Comment by roddypratt** [comment] 2017-08-03 15:36
Have a look at issue #4087 which I've just created (and the related video) - Is this the same problem you're seeing?

**Comment by KangZiRu** [comment] 2017-08-03 15:46
Yes, indeed. It's the same issue. Everything just gone after I install a package.

**Comment by roddypratt** [comment] 2017-08-04 12:24
Suggest this is closed/linked to #4095?

**Comment by roddypratt** [comment] 2017-08-05 11:55
@bestander dupe of #4087 resolved by #4095

(I'm new here. Is this the right way to assist with triage, etc?)

**Comment by bestander** [comment] 2017-08-07 18:51
Thanks for helping to triage, @roddypratt

**Closed by bestander** 2017-08-07 18:51 UTC
