### ISSUE TITLE
Yarn install is including tests and docs folder

### ISSUE THREAD

**Issue by Sunyang730** [yarnpkg/yarn#3261] opened 2017-04-26 22:05 UTC
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**
I only tried this on a private repo, where yarn is including tests and docs folder when yarn install

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To not include tests and docs folder

**Please mention your node.js, yarn and operating system version.**
node.js v7.9.0, OSX 10.11.6

**Comment by rally25rs** [comment] 2017-04-28 13:53
I'm pretty sure there is a duplicate bug around here somewhere but I'm having a hard time finding it...

IIRC, Yarn only filters the `files` listed in `package.json` when it publishes a package. On extraction, or copy from a local repo, it does not clean up files that are not in the `files` listing.

NPM on the other hand, seems to filter the files both on publish and when copying the files into node_modules during install.

**Comment by rally25rs** [comment] 2017-04-28 13:55
Ah, found it: duplicate of #2822

**Comment by voxsim** [comment] 2017-05-02 06:58
I close this issue because it is a duplicate, thanks @rally25rs ;)
@Sunyang730 if you have additional comments, please report it in the original issue!

**Closed by voxsim** 2017-05-02 06:58 UTC
Labels: duplicate
