### ISSUE TITLE
yarn pack crashes internally when provided a bundledDependencies value

### ISSUE THREAD

**Issue by DusterTheFirst** [yarnpkg/yarn#7227] opened 2019-04-25 20:49 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn pack` crashes with the stack-trace 
```
  Error: Cannot find module "."
      at webpackMissingModule (/usr/local/lib/node_modules/yarn/lib/cli.js:109772:64)
      at pkg (/usr/local/lib/node_modules/yarn/lib/cli.js:109772:142)
      at again (/usr/local/lib/node_modules/yarn/lib/cli.js:109727:22)
      at depsFor (/usr/local/lib/node_modules/yarn/lib/cli.js:109741:4)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:42211:30
      at Generator.next (<anonymous>)
      at step (/usr/local/lib/node_modules/yarn/lib/cli.js:304:30)
      at /usr/local/lib/node_modules/yarn/lib/cli.js:315:13
```
[Full logfile](https://gist.github.com/DusterTheFirst/ff28ebabe6c0e63a3a32b214eb4c5406)

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps to reproduce on your own:
- add a `bundledDependencies` field to your `package.json` with at least one dependency in it. ex `"bundledDependencies": [ "cors" ]`
- run `yarn pack` in the directory

Steps to reproduce in [my repostitory](https://github.com/DusterTheFirst/bicbacboe):
- `yarn`
- `yarn workspace server updatedeps`
- `yarn workspace server pack`

**What is the expected behavior?**
Yarn creates a packed tarball with all of the dependencies listed in the `package.json#bundledDependencies` field

**Please mention your node.js, yarn and operating system version.**
nvm: 0.34.0
node: v11.11.0
yarn: v1.15.2

**Comment by GusGold** [comment] 2019-08-22 01:07
Still an issue in `yarn -v` -> `1.17.3`

Seems like a duplicate of #6794

**Comment by rally25rs** [comment] 2020-02-20 13:57
Closing as duplicate of #6794

**Closed by rally25rs** 2020-02-20 13:57 UTC
