### ISSUE TITLE
yarn outdated fails with @types/core-js package

### ISSUE THREAD

**Issue by akaegi** [yarnpkg/yarn#1475] opened 2016-10-26 09:46 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn outdated fails with an unexpected error

**If the current behavior is a bug, please provide the steps to reproduce.**
1. yarn install
2. yarn outdated

error log states that:
Error: https://registry.yarnpkg.com/@types/core-js: Not found

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/552904/yarn-error.log.txt)

**Comment by wyze** [comment] 2016-10-26 15:08
This is fixed on master. Duplicate of #620 and fixed by #1276.

**Closed by wyze** 2016-10-26 15:08 UTC
