### ISSUE TITLE
yarn run with bin in local node_modules

### ISSUE THREAD

**Issue by billxinli** [yarnpkg/yarn#733] opened 2016-10-11 20:46 UTC
**Do you want to request a *feature* or report a *bug*?** 
Report a bug

**What is the current behavior?**
From npm with respect to `npm run`: `In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix.`

**If the current behavior is a bug, please provide the steps to reproduce.**

Add additional entry to the `scripts` section of the `package.json` without installing the dependency globally (in this case mocha).

```
  "scripts": {
    "test-api": "mocha test/api"
  },
```

**What is the expected behavior?**

If I run `npm run test-api` it will resolve `mocha` to the local copy. However `yarn run test-api` will produce:

```
$ "mocha test/api" 
sh: 1: mocha test/api: not found
```

**Please mention your node.js, yarn and operating system version.**
node: 6.7.0
yarn: 0.15
os: Ubuntu 16.04

**Comment by Daniel15** [comment] 2016-10-11 20:51
Thanks for the bug report! This is pretty important. I'll try to take a look tonight.

**Comment by notahat** [comment] 2016-10-12 00:24
Duplicate with more info here: https://github.com/yarnpkg/yarn/issues/735

**Comment by Daniel15** [comment] 2016-10-12 00:26
@notahat - That's actually a separate issue. This issue is saying that `yarn run` is not running executables in the `node_modules/.bin` directory (eg. `mocha test/api` in a script should essentially run `node_modules/.bin/mocha test/api` if `mocha` is an npm dependency of the app), whereas your issue #735 is about running shell commands (I think?)

**Comment by notahat** [comment] 2016-10-12 00:31
@Daniel15 I think it's the same thing.

It's not that yarn isn't finding stuff in `node_modules/.bin`, it's that yarn is shelling out in such a way that the command is `mocha test/api`, rather than `mocha` with an argument of `test/api`. Not surprisingly, the shell can't find an executable called `mocha test/api`.

**Comment by Daniel15** [comment] 2016-10-12 00:32
Ohh I see! That might be it. I'll take a look tonight 😄

**Comment by slmgc** [comment] 2016-10-12 03:12
@Daniel15 @notahat I think it's the root of the issue:
```bash
echo `npm bin` #path_to_the_project/node_modules/.bin
echo `yarn bin` #path_to_the_project/node_modules/.bin/node_modules/.bin
```
`yarn` duplicates `/node_modules/.bin` part.

**Comment by notahat** [comment] 2016-10-12 03:18
@slmgc I don't see that when I try it.

```
$ cd /path/to/project
$ yarn bin
/path/to/project/node_modules/.bin
```

BUT, if I do this:

```
$ cd /path/to/project/node_modules/.bin
$ yarn bin
/path/to/project/node_modules/.bin/node_modules/.bin
```

That definitely isn't right, but I don't think it's the source of the problem as I'm seeing it.

**Comment by f0rr0** [comment] 2016-10-12 03:19
@slmgc I don't see that either.

**Comment by nodesocket** [comment] 2016-10-12 03:23
Both look identical for me as well.

````
➜  js git:(master) npm bin
/Users/justin/Sites/my-project/js/node_modules/.bin
➜  js git:(master) yarn bin
/Users/justin/Sites/my-project/js/node_modules/.bin
````

Though I am encountering this error _(see [782](https://github.com/yarnpkg/yarn/issues/782#issuecomment-253101876))_.

**Comment by slmgc** [comment] 2016-10-12 03:28
@notahat @f0rr0 sorry guys, you are correct: I was trying to figure out the difference and indeed `pwd` was `path_to_the_project/node_modules/.bin`. But, nevertheless, there is a difference between `npm bin` & `yarn bin` when you are `inside node_modules/.bin`.

**Comment by f0rr0** [comment] 2016-10-12 03:35
@notahat is correct https://github.com/yarnpkg/yarn/issues/733#issuecomment-253086168. Running commands with no arguments works like `pwd` or `ls`.

**Comment by lynxluna** [comment] 2016-10-12 04:12
As long as your command script has no arguments, it runs fine. With arguments it will fail to find the files.

```json
"scripts": {
    "start": "node app.js",
    "test": "./node_modules/.bin/mocha",
    "bdd":  "./node_modules/.bin/cucumberjs test"
  },
```
- `yarn test` runs fine
- `yarn start` and `yarn run bdd` fail.

If I remove the arguments for `start` and `bdd` script, it runs fine.

**Comment by nodesocket** [comment] 2016-10-12 05:03
This line looks like perhaps a culprit.

https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/run.js#L64

**Comment by calvinl** [comment] 2016-10-12 05:11
I came across this issue as well, and I did a bit of digging. It looks like [this line](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/run.js#L64) encases `cmd` in double quotes, eventually sending it to `child.spawn()` [here](https://github.com/yarnpkg/yarn/blob/master/src/util/child.js#L25) with the quotes intact, which causes the error.

My test script is as follows:

```
  "scripts": {
    "start": "echo 'start'"
  }
```

In [child.js](https://github.com/yarnpkg/yarn/blob/master/src/util/child.js#L25):
```
const proc = child.spawn(program, args, opts);
console.log('program:', program, 'args:', args);
```

Outputs:
```
program: sh args: [ '-c', '"echo \'hello\'" ' ]
```

Where it should be:
```
program: sh args: [ '-c', 'echo \'hello\'' ]
```

Removing the double quotes in [run.js](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/run.js#L64) seems to make it work fine.

**Comment by nodesocket** [comment] 2016-10-12 05:14
@AlicanC. Seems like it was intentional adding the double quotes. Found the commit using `git blame`.

https://github.com/yarnpkg/yarn/commit/e16953540bebbd42fe4a495ff2f6314568c972c1

**Comment by ticky** [comment] 2016-10-12 05:28
It appears that npm doesn’t do the quoting e169535 introduced; seems like this feature should work the same as npm’s

**Comment by Daniel15** [comment] 2016-10-12 06:21
Sorry I didn't get a chance to look into this more fully tonight. It looks like @ticky submitted a PR though - Thanks!

**Comment by AlicanC** [comment] 2016-10-12 11:05
Yes, it's my mess. The only tested commands are currently "add", "install" and "self-update". I will add tests for "run" (and others if I have time) so this doesn't happen again.

Thanks to @billxinli for reporting and @ticky for fixing it 👍

**Comment by kittens** [comment] 2016-10-13 09:21
Fixed via #809.

**Closed by kittens** 2016-10-13 09:21 UTC
Labels: bug

**Comment by f0rr0** [comment] 2016-10-13 12:39
New release soon @kittens ?

**Comment by mathieutu** [comment] 2017-01-18 15:20
I can confirm that it's still not fixed in yarn 0.19.1.. 😞
@Daniel15 @kittens any news ?

**Comment by ticky** [comment] 2017-01-18 16:25
@mattieutu, the fix for this was released in 0.16.0, hope it hasn't regressed :(

**Comment by mathieutu** [comment] 2017-01-18 16:35
I don't know, but I can reproduce exactly the same problem now with the last version.

With a`yarn add laravel-mix` which install webpack, cross-env, and others,  there is no .bin folder, and I can't launch them with package.json scripts.

I had to remove the node_modules folder and reinstall it with npm :-/

**Comment by dbpolito** [comment] 2017-04-04 19:12
Same here with `laravel-mix`

**Comment by ticky** [comment] 2017-04-05 01:07
@mathieutu @dbpolito I suspect this is in fact an entirely separate issue where binstubs are not created for any dependency which isn’t top-level. Looks like #2758 might be your ticket?

**Comment by mathieutu** [comment] 2017-04-05 08:08
Yeah, it seems to be exactly that thing.
I'm wondering why I thought it was this issue... I'll continue on the #2758.
