### ISSUE TITLE
[BUG] Yarn doesn't install devDependecies

### ISSUE THREAD

**Issue by Mamoru1234** [yarnpkg/yarn#3346] opened 2017-05-08 11:45 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
yarn doesn't install devDependencies
**If the current behavior is a bug, please provide the steps to reproduce.**
STR:
1. `yarn add eslint -D`
2. `yarn run lint` -> it works
3. `yarn cache clean && rm -rf node_modules/` -> make some clean-up
4. `yarn install` -> install everything
5. `yarn run lint` -> fails *"eslint not found"* :(

Here is minimal package for reproducing(sorry for name)
https://github.com/Mamoru1234/yarn-bug

Also interesting detail: if eslint would be a dependency(not dev) it will work. But I didn't find such behavior as expected, don't you? 

**What is the expected behavior?**
I think that step 5 should work.

**Please mention your node.js, yarn and operating system version.**
yarn v0.23.4
node v7.5.0
npm v4.1.2
Ubuntu v16.10

**Comment by rally25rs** [comment] 2017-05-08 12:50
I was unable to reproduce this on OSX:

```
~/Projects/yarn-bug (master) : yarn --version
0.23.4

~/Projects/yarn-bug (master) : yarn install
yarn install v0.23.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 2.03s.

~/Projects/yarn-bug (master) : grep version node_modules/eslint/package.json
  "version": "3.19.0",

~/Projects/yarn-bug (master) : ls node_modules/.bin/
eslint

~/Projects/yarn-bug (master) : yarn run lint
yarn run v0.23.4
$ eslint
eslint [options] file.js [file.js] [dir]
```

Could you provide any additional info? The message "eslint not found" sounds like maybe the symlink wasn't created in `node_modules/.bin/eslint`.

**Comment by Mamoru1234** [comment] 2017-05-08 13:10
@rally25rs Thank you for your comment.

Here what I do in repo dir.
```
rm -rf node_modules/

yarn cache clean
yarn cache v0.23.4
success Cleared cache.
Done in 0.36s.

yarn install
yarn install v0.23.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.99s.

grep version node_modules/eslint/package.json
grep: node_modules/eslint/package.json: No such file or directory
```
Maybe cache cleaning is the problem?

**Comment by rally25rs** [comment] 2017-05-08 13:51
```
~/Projects/yarn-bug (master) : rm -rf node_modules/

~/Projects/yarn-bug (master) : yarn cache clean
yarn cache v0.23.4
success Cleared cache.
✨  Done in 7.55s.

~/Projects/yarn-bug (master) : yarn install
yarn install v0.23.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
✨  Done in 3.86s.

~/Projects/yarn-bug (master) : grep version node_modules/eslint/package.json
  "version": "3.19.0",
```

that is really weird. I'm not sure what would be causing the issue you are seeing.

Could you try running the install with the `--verbose` flag?

```
rm -rf node_modules
yarn install --verbose
```

You should be able to search the output and see where it is putting the eslint files. For example, from my output:

> verbose 2.075 Copying "/Users/me/Library/Caches/Yarn/v1/npm-eslint-3.19.0-c8fc6201c7f40dd08941b87c085767386a679acc/bin/eslint.js" to "/Users/me/Projects/yarn-bug/node_modules/eslint/bin/eslint.js".

**Comment by Mamoru1234** [comment] 2017-05-08 14:56
Hm... really strange, at some point STR becomes not valid :(
I need to investigate problem more...

**Comment by rally25rs** [comment] 2017-05-08 15:03
@bestander could you add labels [ triaged | needs clarification ]

**Comment by Mamoru1234** [comment] 2017-05-08 15:08
@rally25rs Actually... I can't

**Comment by rally25rs** [comment] 2017-05-08 15:10
@Mamoru1234 sorry for any confusion, I was asking @bestander to add those labels, because I can't either 😄

**Comment by rally25rs** [comment] 2017-12-28 04:17
Closing due to lack of confirmation, and old Yarn version.

**Closed by rally25rs** 2017-12-28 04:17 UTC
Labels: needs-confirmation, triaged
