### ISSUE TITLE
yarn breaks the convention of npm-scripts and package.json

### ISSUE THREAD

**Issue by dexteryy** [yarnpkg/yarn#1189] opened 2016-10-18 10:54 UTC
https://docs.npmjs.com/files/folders#executables

> When in local mode, executables are linked into ./node_modules/.bin so that they can be made available to scripts run through npm. (For example, so that a test runner will be in the path when you run npm test.)

http://www.2ality.com/2016/01/locally-installed-npm-executables.html

https://docs.npmjs.com/cli/run-script

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write:

> `"scripts": {"test": "tap test/\*.js"}`

> instead of "scripts": {"test": "node_modules/.bin/tap test/\*.js"} to run your tests.

But after I reinstalled all dependencies ([application's package.json includes `webcube`](https://github.com/dexteryy/webcube-example/blob/3093cb56c3643ca2f2a8a389ca20c509abaca502/package.json#L50), and [`webcube`'s package.json includes `gulp` and `plop`](https://github.com/dexteryy/webcube/blob/0.5.8/package.json#L75)) with yarn, the `node_modules/.bin/` is empty.

So for [this package.json](https://github.com/dexteryy/webcube-example/blob/3093cb56c3643ca2f2a8a389ca20c509abaca502/package.json#L15):

```json
  "scripts": {
    "lint": "gulp --gulpfile node_modules/webcube/configs/gulpfile.babel.js check:all",
    "new": "plop --plopfile=node_modules/webcube/configs/plopfile.babel.js",
```

`npm run lint`,  `yarn run lint`, `npm run new` and `yarn run new` fails if gulp and plop aren't installed in global mode

**Comment by bitfrost** [comment] 2016-10-18 11:26
This looks like a duplicate of https://github.com/yarnpkg/yarn/issues/760

**Comment by wyze** [comment] 2016-10-24 18:55
Closing in favor of #760. Feel free to make a comment over there with this information @dexteryy.

**Closed by wyze** 2016-10-24 18:55 UTC
