### ISSUE TITLE
tmp directory filled by yarn (and not cleaned)

### ISSUE THREAD

**Issue by nicolas-lecab** [yarnpkg/yarn#6685] opened 2018-11-15 17:56 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Each "yarn run" will create a directory under "/tmp" directory which looks like 
> /tmp/yarn--1542302743598-0.6454897498245407

**If the current behavior is a bug, please provide the steps to reproduce.**
Let's say we have a script in package.json as follow:
```
    "scripts": {
        "dummy": "echo 'dummy'"
    }
```
If we play this dummy script and we check number of directories before and after in /tmp:
```
$> ls -dla /tmp/yarn* | grep $USER | wc -l
0

$> yarn run dummy
yarn run v1.12.3
$ echo 'dummy'
dummy
Done in 0.12s.

$> ls -dla /tmp/yarn* | grep $USER | wc -l
1
```
Running the dummy script will increment the result each time.
FYI:
 - yarn is installed globally
 - bug seems to appear somewhere between v1.10.0 and v1.11.0 (I can't reproduce with 1.10.0)

**What is the expected behavior?**
Tmp directory should not be filled indefinitely: it should reuse the already created temporary files (if tmp is really needed) or it should have some kind of cleaning mechanism to avoid overwhelmingly the tmp directory.

**Please mention your node.js, yarn and operating system version.**
node: v8.9.4
nvm: 0.33.2
yarn: 1.12.3
os: Debian 3.16.51-3

**Comment by arcanis** [comment] 2018-11-28 01:51
Yarn creates a temporary directory each time a script is executed, in order to setup "fake" Node and "fake" Yarn binaries that point towards the exact same Yarn/Node than those currently being executed.

The problem is that they never get removed at the moment:
https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L31-L48

**Comment by tomq42** [comment] 2019-02-07 13:59
Yep, also see this.

**Comment by BookOfGreg** [comment] 2019-03-11 15:59
My `/tmp` is 24gb.
```
me@me:~$ sudo du -hs /tmp
24G     /tmp
me@me:~$ uptime
 15:58:04 up 52 days,  5:30,  1 user,  load average: 0.97, 0.87, 0.50
```

Was this a regression? I don't remember my CI agents being filled by this in the past.

**Comment by lexaurin** [comment] 2019-06-06 10:45
The same problem with `yarn 1.15.2`

**Comment by ZLima12** [comment] 2019-06-06 15:40
Still happening for me with `yarn 1.16.0`.

**Comment by xmontero** [comment] 2019-06-17 19:33
In the meantime.... Is it sure to manually remove all of them? Or removal could break anything?

**Comment by JLarky** [comment] 2019-06-17 21:51
I wrote crontab that does "mkdir -p /tmp/yarn & mv /tmp/yarn-* /tmp/yarn/"
(typing by memory, don't have my laptop to check). In Linux if you rename
directory it still can be used by program that already has file descriptor,
same goes for deletion I think. Never had issues with renaming via cron,
never had issues removing them manually, I would assume it's probably safe
to delete it from cron as well. Worst case scenario I would assume your
currently running "yarn run something" will crash.

**Comment by nicolas-lecab** [comment] 2019-06-18 09:34
@xmontero We removed files older than 1 day on our dev server.
Never had issue since then.
`10 4    * * *           find /tmp/ -name "yarn*" -type d -mtime +1 -exec rm -rf {} \; > /dev/null`

**Comment by arcanis** [comment] 2019-06-18 09:37
There is no risk removing those files when Yarn isn't running. Even when running, it should be relatively safe as they're usually only used when the program boots.

Fwiw this problem will be fixed from the v2 onward; the artifacts will be properly discarded right after the commands return.

**Comment by lexaurin** [comment] 2019-06-18 15:52
Running build in Docker image is also a good workaround. It protects you
from such leaks to CI workers system, by design.

**Comment by dvdknaap** [comment] 2019-10-10 13:23
Still getting this at the current version

**Comment by ClementNerma** [comment] 2020-02-20 13:42
It's still not fixed at this time, even on latest `1.21.1` version :/

**Comment by djsiddz** [comment] 2020-05-07 09:34
Is this issue persistent with yarn `v2`? If anyone has tried this, please let me know. I am giving it a shot today with `v2` on one of our apps to check this in the mean time.

**Comment by ivanixgames** [comment] 2020-05-26 13:01
after removing the trash that yarn leaves in /tmp/ I now get these errors:

$ yarn install
bash: /tmp/yarn--1590486433942-0.3935430674616345/yarn: No such file or directory
$ yarn cache clean
bash: /tmp/yarn--1590486433942-0.3935430674616345/yarn: No such file or directory
$ yarn cache clear
bash: /tmp/yarn--1590486433942-0.3935430674616345/yarn: No such file or directory
$ which yarn
/Work/Projects/Phase/node_modules/.bin/yarn
$ yarn --help
bash: /tmp/yarn--1590486433942-0.3935430674616345/yarn: No such file or directory
$

**Comment by snowl** [comment] 2020-06-09 02:51
@djsiddz Did v2 fix it for you?

**Comment by dvdknaap** [comment] 2020-06-11 12:22
De issue still exists in the latest version

```sh yarn -version ```
1.22.4

```sh ls -alF```
> drwxr-xr-x   2 username              username                4096 Jun  9 11:57 yarn--1591696641892-0.05204308679429248/
> drwxr-xr-x   2 username              username                4096 Jun 10 14:55 yarn--1591793724850-0.4196722332063454/
> drwxr-xr-x   2 username              username                4096 Jun 10 15:15 yarn--1591794953501-0.3040314059514666/
> drwxr-xr-x   2 username              username                4096 Jun 10 15:26 yarn--1591795571216-0.8222359319740244/
> drwxr-xr-x   2 username              username                4096 Jun 11 09:33 yarn--1591860782625-0.15962323877699136/
> drwxr-xr-x   2 username              username                4096 Jun 11 09:36 yarn--1591860987612-0.0746955607161679/
> drwxr-xr-x   2 username              username                4096 Jun 11 11:03 yarn--1591866191467-0.6557044172705777/
> drwxr-xr-x   2 username              username                4096 Jun 11 11:04 yarn--1591866263355-0.7429486092878892/
> drwxr-xr-x   2 username              username                4096 Jun 11 11:07 yarn--1591866427043-0.3962468811805635/
> drwxr-xr-x   2 username              username                4096 Jun 11 12:50 yarn--1591872605318-0.8161204330414475/
> drwxr-xr-x   2 username              username                4096 Jun 11 12:50 yarn--1591872605322-0.48513192538032124/
> drwxr-xr-x   2 username              username                4096 Jun 11 12:50 yarn--1591872622244-0.4583333405082548/
> drwxr-xr-x   2 username              username                4096 Jun 11 13:59 yarn--1591876762200-0.05283671445181093/
> drwxr-xr-x   2 username              username                4096 Jun 11 14:09 yarn--1591877355444-0.7000002370403433/
>

**Comment by ClementNerma** [comment] 2020-06-11 12:37
I can confirm this still happens on the very same version (`1.22.4`).
Platform: WSL on Windows 10 x64 ver 19041 (2004).

**Comment by ezeqd** [comment] 2020-10-01 16:59
Any update on this? we still have several problems with hard disk and "no left space" on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-38-generic x86_64) with
`yarn -v`
1.13.0

**Comment by mohux** [comment] 2020-10-28 13:22
still not fixed? :/ my server is filled with tmp yarn files

**Comment by namnm** [comment] 2020-12-10 23:24
Yarn was so good, until this. And no collaborator care about fixing this, even there is an existing PR #7207 to review.

**Comment by NobodysNightmare** [comment] 2021-03-03 15:18
@arcanis wrote:
> Fwiw this problem will be fixed from the v2 onward; the artifacts will be properly discarded right after the commands return.

Just for clarification (even if it will hurt), I guess this means version 1.x will not receive a fix, but 2.x has the issue fixed? In this case the issue could IMO be closed, but it would be nice to have clarity on that.

Comparing to the description of this repository itself:

> The 1.x line is frozen - features and bugfixes now happen on https://github.com/yarnpkg/berry

**Comment by arcanis** [comment] 2021-03-03 15:26
> Just for clarification (even if it will hurt), I guess this means version 1.x will not receive a fix, but 2.x has the issue fixed? In this case the issue could IMO be closed, but it would be nice to have clarity on that.

Indeed. Note that the migration should be fairly painless if you follow the [migration guide](https://yarnpkg.com/getting-started/migration#step-by-step), since it explains how to stay on the typical `node_modules` install strategy even with 2+.

**Comment by danielmarschall** [comment] 2021-12-06 14:53
Please fix your stuff. This bug is 3 years old, and it is probably only a single line of code that deletes the temporary files. Filling the tmp/ directory until it's full is a major defect, and I hate being forced to upgrade to a newer version just because of this.

**Comment by vanowm** [comment] 2021-12-14 03:39
Is there a "manual" script we could run that would clean up after yarn finished?

**Comment by ClementNerma** [comment] 2021-12-14 07:43
> Is there a "manual" script we could run that would clean up after yarn finished?

On Unix-based systems (Linux & co):

```shell
rm /tmp/yarn--*
```

**Comment by vanowm** [comment] 2022-04-16 22:00
> Is there a "manual" script we could run that would clean up after yarn finished?

on Windows OS this can be used:
```
for /d /r "%temp%" %i in (yarn--*) do @rmdir /s /q "%i"
```

**Comment by kunwoo-choi** [comment] 2022-08-09 05:32
I clear tmp directory in every hour by crontab, but sometimes server dies because of this(even at dawn!!)
I cannot figure out why server died suddenly at 11:28(not an exact 11:00 or 12:00).

But if I do not clear this regulary, our server instance is filled by yarn! I'm in a dilemma.


<img width="1920" alt="스크린샷 2022-08-09 오전 11 28 08" src="https://user-images.githubusercontent.com/110218184/183571534-fe518c38-99a2-4283-b9e5-569a74d0f193.png">
.

**Comment by minured** [comment] 2023-01-25 11:33
version 1.22.19 still exsits,

**Comment by jcruz97** [comment] 2023-04-06 13:05
Instead of marking comment as "abusive" you can fix this up?

**Comment by arcanis** [comment] 2023-04-06 13:11
@jcruz97 No, because it's [already fixed](https://github.com/yarnpkg/yarn/issues/6685#issuecomment-503028465). As for your post, it's quite unprofessional and doesn't really worth visibility.

**Closed by arcanis** 2023-04-06 13:11 UTC
Labels: triaged
