### ISSUE TITLE
json-server not responding/connection refused when started with Yarn

### ISSUE THREAD

**Issue by reuben-bradley** [yarnpkg/yarn#4149] opened 2017-08-11 11:01 UTC
**What is the current behavior?**
On Windows 7, installed `json-server` which spins up and loads fine when started with Yarn, but server refuses connection requests.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install `json-server` (globally or locally).
1. Starting directly from the command line or through `npm` allows the server to behave as expected
1. However, starting through yarn ("`yarn run`", etc.) starts the server, but requests are ignored

**What is the expected behavior?**
There should be no deviation of the server behaviour between the command line/npm and yarn.

**Please mention your node.js, yarn and operating system version.**
node.js - v6.11.0
yarn - 0.27.5
OS: Windows 7

**Comment by BYK** [comment] 2017-08-11 13:31
Works for me. Can you share the exact replication steps?

**Comment by reuben-bradley** [comment] 2017-08-15 14:04
To replicate (Windows 7):

1. Open **Git Bash**
2. Use `yarn`/`npm` to install `json-server`
3. Start the process using `yarn run json-server [options]`

Worth noting that this issue doesn't seem to happen with Command Prompt or PowerShell.

I'm also behind a corporate firewall, which means my `npm` has the `proxy` config set; would this come into play at all?

**Comment by BYK** [comment] 2017-10-26 15:22
Sorry, still cannot reproduce. Guessing this is something that was fixed post 1.0 so closing.

**Closed by BYK** 2017-10-26 15:22 UTC
Labels: needs-confirmation, needs-repro-script
