### ISSUE TITLE
outdated - package: @google-cloud not found

### ISSUE THREAD

**Issue by hjanuschka** [yarnpkg/yarn#709] opened 2016-10-11 19:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
trying to use `yarn outdated`

**If the current behavior is a bug, please provide the steps to reproduce.**

```
 "dependencies": {
    "@google-cloud/vision": "^0.3.0"
 }
```

```
yarn outdated
error https://registry.yarnpkg.com/@google-cloud/vision: Not found
    at Request.params.callback [as _callback] (/usr/local/lib/node_modules/yarn/lib/util/request-manager.js:273:18)
    at Request.self.callback (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
info Visit http://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**What is the expected behavior?**

Show Version Table

**Please mention your node.js, yarn and operating system version.**
 * MacOS 10.12
 * node 6.3.1
 * yarn 0.15.1

**Comment by AndrewIngram** [comment] 2016-10-11 19:31
I get the same thing with @kadira/storybook, so i'm guessing that Yarn isn't proxying any packages with scoped names. Hopefully this'll be resolved quickly.

**Comment by ssreekanth** [comment] 2016-10-11 21:01
When I run `yarn outdated` in my project workspace, I get the similar error with `@ionic/app-scripts`.

```
yarn outdated
yarn outdated v0.15.1
error https://registry.yarnpkg.com/@ionic/app-scripts: Not found
    at Request.params.callback [as _callback] (/usr/local/lib/node_modules/yarn/lib/util/request-manager.js:273:18)
    at Request.self.callback (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yarn/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
info Visit http://yarnpkg.com/en/docs/cli/outdated for documentation about this command.
```

**Comment by ssreekanth** [comment] 2016-10-11 21:04
Duplicate of #620

**Comment by hjanuschka** [comment] 2016-10-11 21:16
@AndrewIngram seems to be right about hte scoped names i guess

**Comment by wyze** [comment] 2016-10-24 16:12
Closing as duplicate of #620.

**Closed by wyze** 2016-10-24 16:12 UTC
Labels: needs triage
