### ISSUE TITLE
Seeing 500s from yarnpkg.com

### ISSUE THREAD

**Issue by glasser** [yarnpkg/yarn#3353] opened 2017-05-08 20:45 UTC
I'm seeing sporadic errors like

```
error An unexpected error occurred: "https://registry.yarnpkg.com/react-apollo/-/react-apollo-0.7.1.tgz: Request failed \"500 Internal Server Error\"".
```

They are occurring at a high enough rate to prevent me from working or deploying.

Is there a status page somewhere for issues with registry.yarnpkg.com?

**Comment by SEAPUNK** [comment] 2017-05-08 20:51
Confirmed; our CI builds are failing because of this error.

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@kadira/storybook-addons/-/storybook-addons-1.6.1.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by devony** [comment] 2017-05-08 21:04
It also looks like this can corrupt packages that are concurrently being installed. On clean caches we saw these instances. If a later version of yarn resolves this, apologies:

```
20:50:24 WARNING:retry.api:local() encountered an error (return code 1) while executing 'yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7', retrying in 10 seconds...
20:50:34 [STATS_MARKER] starting yarn
20:50:34 yarn install v0.21.3
20:50:35 [1/4] Resolving packages...
20:50:35 [2/4] Fetching packages...
20:50:36 error An unexpected error occurred: "https://registry.yarnpkg.com/@types/lodash/-/lodash-4.14.61.tgz: Request failed \"500 Internal Server Error\"".
20:50:36 info If you think this is a bug, please open a bug report with the information provided in "/mnt/jenkins-slave/workspace/mmcd-prod-ping-email/backend/yarn-error.log".
20:50:36 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
20:50:36 
20:50:36 Fatal error: local() encountered an error (return code 1) while executing 'yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7'
20:50:36 
20:50:36 Aborting.
20:50:36 [localhost] local: yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7
20:50:36 [localhost] local: git rev-parse HEAD
20:50:36 [STATS_MARKER] finished yarn
20:50:36 WARNING:retry.api:local() encountered an error (return code 1) while executing 'yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7', retrying in 20 seconds...
20:50:56 [STATS_MARKER] starting yarn
20:50:56 yarn install v0.21.3
20:50:57 [1/4] Resolving packages...
20:50:58 [2/4] Fetching packages...
20:51:00 error Error parsing JSON at "/mnt/npm-caches/yarn/executor-7/npm-once-1.3.3-b2e261557ce4c314ec8304f3fa82663e4297ca20/.yarn-metadata.json", "/mnt/npm-caches/yarn/executor-7/npm-once-1.3.3-b2e261557ce4c314ec8304f3fa82663e4297ca20/.yarn-metadata.json: Unexpected end of JSON input".
20:51:00 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
20:51:00 
20:51:00 Fatal error: local() encountered an error (return code 1) while executing 'yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7'
20:51:00 
20:51:00 Aborting.
20:51:00 [localhost] local: yarn --no-progress --cache-folder /mnt/npm-caches/yarn/executor-7
20:51:00 [localhost] local: git rev-parse HEAD
20:51:00 [STATS_MARKER] finished yarn
```

**Comment by glasser** [comment] 2017-05-09 03:01
This seems to have cleared up, but it would really be great if there was a status page and a documented place to report outages.

**Comment by Daniel15** [comment] 2017-05-10 03:34
I'm considering setting up a status page using Cachet (https://cachethq.io/), but I'll need to see whether the rest of the team think it's a good idea.

Apart from that, there's an open GitHub issue around having some optional logging for request failures so we can see how often they happen. I suspect the numbers that CloudFlare give us in their reports aren't capturing all the failures, so having our own data would be useful to see how often this occurs.

You can either use the `--registry` flag or run `yarn config set registry` to set a different registry mirror, for example CloudFlare's one:
```
yarn config set registry https://registry.npmjs.cf/
```

**Comment by bestander** [comment] 2017-05-12 14:15
I agree with you @Daniel15

**Comment by blackholegalaxy** [comment] 2017-05-30 12:39
Bug is still occuring.

**Comment by export-mike** [comment] 2017-06-19 05:07
It seems to be happening right now.

> yarn install v0.21.3
[1/4] Resolving packages...
⠁ [2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/markdown-it-emoji/-/markdown-it-emoji-1.3.0.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/ubuntu/jerrick-media-magazine/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
>yarn returned exit code 1
>Action failed: yarn

this is via Circle CI. circleci.com

**Comment by export-mike** [comment] 2017-06-19 05:08
Whats strange is I request https://registry.yarnpkg.com/markdown-it-emoji/-/markdown-it-emoji-1.3.0.tgz manually and it works fine

**Comment by bestander** [comment] 2017-06-19 16:56
Should be fixed via https://github.com/yarnpkg/yarn/issues/2849, feel free to send a PR

**Comment by SEAPUNK** [comment] 2017-06-19 17:14
@bestander This will only partially fix this issue. The second half of the solution should be to implement a status page for the Yarn registry for the times it really starts having problems, and the 500s don't go away on next request (which is what was happening at the time the OP was posted).

**Comment by bestander** [comment] 2017-06-19 17:18
@SEAPUNK, that is a good idea, we already expose stats for the downloads per day https://stats.yarnpkg.com/.

According to the CDN logs we only have 100s of `500` responses a day out of 100s of millions, hopefully that fix should be good enough.
But we can take it one step further if the issue still affects people.

**Comment by glasser** [comment] 2017-06-19 23:04
It is pretty easy to set up a status page with something like statuspage.io or status.io.

**Comment by export-mike** [comment] 2017-06-20 00:58
As a work around use the npm registry with Yarn. https://registry.npmjs.org/

**Comment by Daniel15** [comment] 2017-06-20 02:57
> it would really be great if there was a status page

I added a status page at https://status.yarnpkg.com/ that we can use to report any major issues.

**Comment by Vanuan** [comment] 2017-06-21 17:18
Happened approximately one hour (58-59 minutes) ago
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@storybook/addon-links/-/addon-links-3.0.0.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by BYK** [comment] 2017-10-30 11:20
This is no longer an issue so closing.

**Closed by BYK** 2017-10-30 11:20 UTC
Labels: cat-bug, cat-cdn, triaged

**Comment by kylemh** [comment] 2018-01-16 03:19
@BYK I'm still receiving the same issue, even from the same package as @Vanuan 

It's happened 5 times in the past month.

![screen shot 2018-01-15 at 7 11 08 pm](https://user-images.githubusercontent.com/9523719/34970372-ecbf282e-fa28-11e7-98ed-bf7b3772c6c9.png)

**Comment by vancouverwill** [comment] 2018-05-16 11:34
@BYK seeing this multiple time today

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/923939/40114595-653cce7e-5905-11e8-94cb-87c2ba67c58b.png">

**Comment by sortigoza** [comment] 2018-07-26 21:52
Same issue here: `error An unexpected error occurred: "https://registry.yarnpkg.com/node-gyp/-/node-gyp-3.7.0.tgz: Request failed \"500 Internal Server Error\"".` :(

**Comment by OmgImAlexis** [comment] 2018-07-27 11:37
Seeing this as well but we're also getting an issue about the signature a little further down the logs.

```
> Verifying integrity...
gpg: key 86E50310: public key "Yarn Packaging <yarn@dan.cx>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made Wed 23 May 2018 09:02:50 PM UTC using RSA key ID B6FF4DE3
gpg: BAD signature from "Yarn Packaging <yarn@dan.cx>"
> GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.
```

**Comment by matt-blanchette** [comment] 2018-08-06 15:33
Same issue as well: `[ERROR] error An unexpected error occurred: "https://registry.yarnpkg.com/read-pkg/-/read-pkg-1.1.0.tgz: Request failed \"500 Internal Server Error\"".`

**Comment by justindra** [comment] 2018-08-07 00:50
Yep, just started receiving this in our CI

```
 An unexpected error occurred: "https://registry.yarnpkg.com/mkdirp/-/mkdirp-0.5.1.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by darrendahl** [comment] 2018-08-15 16:51
Also receiving in our CI -
`error An unexpected error occurred: "https://registry.yarnpkg.com/browser-resolve/-/browser-resolve-1.11.2.tgz: Request failed \"500 Internal Server Error\""`

**Comment by cice** [comment] 2018-08-16 13:27
happening to us intermittently as well:
`error An unexpected error occurred: "https://registry.yarnpkg.com/async-each-series/-/async-each-series-1.1.0.tgz: Request failed \"500 Internal Server Error\"".`

**Comment by veksen** [comment] 2018-09-05 17:47
This happens several times a day for us. On CircleCI. I assume it's some kind of rate limiting.

**Comment by tsuna** [comment] 2018-09-06 16:09
We started seeing those in our CI system as soon as we switching to yarn as well.  If it was rate limiting then I wouldn't expect a 500 response as those are for internal errors.
