### ISSUE TITLE
Yarn does not completely respect nested lock-files

### ISSUE THREAD

**Issue by Ionaru** [yarnpkg/yarn#4110] opened 2017-08-07 13:13 UTC
I'm not sure if this behaviour was intended, already fixed or is actually a bug. A quick search through the issues for something similar did not yield any resolution.

**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
Yarn does not completely respect nested lock-files, instead upgrading packages sometimes.

**If the current behavior is a bug, please provide the steps to reproduce.**
I came across [this blog](https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf) and I ran the test described.

[This repository](https://github.com/boennemann/yarn-test-module) has a dependency on [semver-fail-module](https://github.com/boennemann/semver-fail-module), the package.json lists the dependency as `^1.0.0`, while the yarn.lock file says `version "1.0.0"`.

1. Create a new project
2. Type `yarn add @boennemann/yarn-test-module`
3. Yarn will say a depencency for `@boennemann/semver-fail-module@1.0.1` was saved??
4. Create an `index.js` file and paste 
```js
var test = require('@boennemann/yarn-test-module');
test();
```
5. Run `node index.js`
6. Node will throw an error because yarn-test-module has the wrong version.

The difference from other issues mentioning this, is that I have no need for `semver-fail-module` in my project. Is it only used by `yarn-test-module` so it should not be listed as a peer-dependency.

**What is the expected behavior?**
Yarn respects nested lock-files of dependencies.

**Please mention your node.js, yarn and operating system version.**
Node v8.2.1
Yarn 0.27.5
Linux Kubuntu 17.04 - 4.10.0-30-generic

**Comment by BYK** [comment] 2017-08-07 15:42
Duplicate of #3322.

**Closed by BYK** 2017-08-07 15:42 UTC

**Comment by rich-newman** [comment] 2017-08-20 18:19
The short answer, for those confused by this as I was, is that yarn is NOT intended to lock versions for packages that you release.  It's only intended to lock dependencies in development environments for a package or application that a developer is working on.  To do this you check a yarn.lock file into source control, and use it to install dependencies when you check out.

The problem this is trying to deal with is a dependent package being released that claims it is backwards-compatible and is within your semver version range, but actually breaks your dev environment.  If you lock your dev environment with yarn this can't happen.  Of course if your released package has the same dependency you may well find that your dev env is fine but all your users are broken (and you didn't even notice), but there's a [blog article](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) arguing that this is actually a good way to do things.
