### ISSUE TITLE
Non-deterministic behavior of 'yarn install' with multiple dependencies of a package

### ISSUE THREAD

**Issue by reacthacker** [yarnpkg/yarn#3201] opened 2017-04-20 07:34 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
'yarn install' doesn't resolve the dependencies deterministically when the package react-scripts and an extaneous eslint-package are included. Yarn might use either the built-in eslint of react-scripts or the extraneous eslint when 'yarn eslint .' is run. 

**If the current behavior is a bug, please provide the steps to reproduce.**

When both packages are included and the extraneous eslint-version is higher than the one in react-scripts, a 'yarn install' command after either removing or adding a caret will lead to this bug.
The result are "Definition for rule '...' not found"-errors when the command 'yarn eslint .' is executed.

**What is the expected behavior?**
The extraneous eslint-version should be used by yarn.

**Please mention your node.js, yarn and operating system version.**
node: v7.9.0
yarn: v0.22.0
OS: Windows 7 (64-bit)

**Comment by gauthierm** [comment] 2017-04-20 14:55
Both versions of eslint are installed but the version linked in `node_modules/.bin` is different between `npm` and `yarn`.

**Comment by reacthacker** [comment] 2017-04-21 07:50
Bug description edited.
Yes, both versions are installed, but when I run 'yarn eslint .' I either get these errors or after another 'yarn install' and a prior change in the package.json the dependency of eslint by removing or adding a caret.

**Comment by torifat** [comment] 2017-04-22 13:33
Can you provide your `package.json`? You can strip other info except the dependencies.

**Comment by reacthacker** [comment] 2017-04-24 11:32
{
  },
  "devDependencies": {
    "eslint": "3.19.0",
    "eslint-config-airbnb": "^14.1.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^4.0.0",
    "eslint-plugin-react": "^6.9.0",
    "react-scripts": "0.9.5"
  }
}

**Comment by rally25rs** [comment] 2017-05-02 14:06
I believe that the way Yarn currently works, this should result in a /.bin/eslint link to the 3.19.0 version of eslint because that is the one your project actually depends on.

See some discussion in #2874 - bin symlinks are sort of an open issue.

@bestander triage; duplicate of #2874

**Closed** 2017-05-02 14:14 UTC
Labels: triaged
