### ISSUE TITLE
ECONNREFUSED when installing autoprefixer-7.1.3

### ISSUE THREAD

**Issue by nottrobin** [yarnpkg/yarn#5041] opened 2017-12-05 15:26 UTC
We've recently started getting this error a lot:

``` bash
error An unexpected error occurred: "https://registry.yarnpkg.com/autoprefixer/-/autoprefixer-7.1.3.tgz: connect ECONNREFUSED
```

We first got it in Travis ([here](https://travis-ci.org/canonical-websites/snapcraft.io/builds/309427166)).

Although it doesn't seem to happen in Travis any more, and we've never seen it when running Yarn locally, it's now happening consistently in our Jenkins jobs.

Do you have any idea what  might be causing it?

**Comment by rally25rs** [comment] 2017-12-05 18:56
Possibly related to #5015 ??? I can't reproduce this anywhere, and clearly if the entire Yarn registry were down there would be a huge flood of issues. I'm installing Yarn packages daily as I triage and try to reproduce these bugs and never had an issue.

Maybe you can compare notes with @alienlebarge and see if one of you can narrow down what is causing this? Might be some kind of regional networking outage or occasional hiccup?

**Comment by nottrobin** [comment] 2017-12-06 16:17
You're right, this is very similar to #5015 in that the problem turned out to be the proxy server.

The `HTTP_PROXY` and `HTTPS_PROXY` environment variables were set, and for the most part Yarn appears to pick up on them. But for some reason in some contexts, it doesn't.

Explicitly setting the Yarn proxy fixes this. I'm pretty sure that shouldn't be the case - setting `HTTP_PROXY` should be the same. I'm afraid I don't have time to debug this further to provide the exact scenarios.

**Comment by rally25rs** [comment] 2017-12-06 16:29
I've tweaked that code a few times, but IIRC those env vars get picked up the the `request` library https://github.com/request/request/blob/b12a6245d9acdb1e13c6486d427801e123fdafae/lib/getProxyFromURI.js#L61-L71

**Comment by rally25rs** [comment] 2017-12-06 16:38
Going to close this for now as it sounds like you figured out how to make it work. If you ever get a chance to find where some scenarios work but others don't, please let us know and we can re-open it. Thanks!

**Closed by rally25rs** 2017-12-06 16:38 UTC
Labels: triaged
