### ISSUE TITLE
Can not execute yarn shell script via a symlink

### ISSUE THREAD

**Issue by nicoschoenmaker** [yarnpkg/yarn#1678] opened 2016-11-04 07:26 UTC
**Do you want to request a *feature* or report a *bug*?**
A Bug.

**What is the current behavior?**
When executing a symlink pointing to the yarn shell script, this error occurs:
```module.js:474
    throw err;
    ^

Error: Cannot find module '/home/nschoenmaker/projects/tools/node/bin/yarn.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
wget https://yarnpkg.com/latest.tar.gz
tar zvxf latest.tar.gz
ln -s dist/bin/yarn yarn
./yarn --version
```
This gives the error noted earlier.

**What is the expected behavior?**
```
./dist/bin/yarn --version
0.16.1
```
**Please mention your node.js, yarn and operating system version.**
node.js: v7.0.0
yarn: 0.16.1
os: Ubuntu 14.04 LTS

**Comment by Daniel15** [comment] 2016-11-04 16:43
Good catch, we might need to adjust the executable to handle symlinks.

For Ubuntu I'd suggest installing the package via our repository rather than the install script. Then `apt-get upgrade` will always give you the newest version of Yarn. :)

**Comment by SamMousa** [comment] 2016-12-28 14:23
Duplicate of  #1941
And fixed in: https://github.com/yarnpkg/yarn/commit/7fe2e53a59d5c5d256459854dd7ad4d4ff874682

**Closed** 2016-12-28 14:41 UTC
Labels: duplicate
