### ISSUE TITLE
Behaviour of --dev flag for installed dependencies

### ISSUE THREAD

**Issue by gunnx** [yarnpkg/yarn#2448] opened 2017-01-14 16:20 UTC
**Do you want to request a *feature* or report a *bug*?**

Possible Bug

**What is the current behavior?**
I add a package e.g. `yarn add eslint`
Appears in dependencies 
I run `yarn add eslint --dev`
No change in package.json

**What is the expected behaviour?**
Either it adds package to devDependencies and removes it from dependencies or just adds to devDependencies

**Please mention your node.js, yarn and operating system version.**
Node v7.1.0
Yarn 0.18.1
Mac El Capitan 10.11.6

**Comment by fvgs** [comment] 2017-01-17 00:23
I just ran into this same issue. I forgot to use the `-D` flag with `yarn add` when adding a new package. I had to first use `yarn remove <pkg>` and then `yarn add -D <pkg>` to fix it. The behavior proposed above would make this process more convenient.

Keep in mind the behavior of `yarn add` should be mirrored by `yarn remove`. So if it is possible for `yarn add` to be used in a way that it inserts a package into multiple dependency types, `yarn remove` should be able to selectively remove just one of those listings instead of forcing removal of all.

I'm personally fine with just removing it from the existing dependency type and adding it to the new dependency type.

**Comment by rally25rs** [comment] 2017-06-20 13:18
Confirmed this is still an issue in 0.24.6.

NPM5 behavior is to replace the previous dep type with the newly specified one.

```
$ npm i eslint

$ more package.json
...
  "dependencies": {
    "eslint": "^4.0.0"
  }
...

$ npm i eslint --save-dev

$ more package.json
...
  "devDependencies": {
    "eslint": "^4.0.0"
  },
  "dependencies": {
  }
...
```

**Comment by rally25rs** [comment] 2017-06-20 14:05
Closing as a duplicate of #2479

**Closed by rally25rs** 2017-06-20 14:05 UTC
Labels: bug-resolution, triaged
