### ISSUE TITLE
Error: Cannot find module when using --ignore-optional

### ISSUE THREAD

**Issue by cout** [yarnpkg/yarn#4340] opened 2017-09-07 19:21 UTC
Using latest Yarn 1.0.0 release candidate, I get an error when running "yarn install --ignore-optional" and dependencies "sqlite3" and "karma".  Installation succeeds with Yarn 0.28.4.

I am using node 6.10.2 on ubuntu linux 14.04.

Here is package.json:

    {
      "name": "test", "version": "0.0.1", "private": true,
      "dependencies": { "sqlite3": "latest" },
      "devDependencies": { "karma": "latest" }
    }

And the output from `yarn install --no-optional`:

    yarn install v1.0.0
    info No lockfile found.
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@1.1.2: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    [1/1] ⠂ sqlite3
    [-/1] ⠂ waiting...
    [-/1] ⠂ waiting...
    [-/1] ⠂ waiting...
    error /home/pbrannan/tmp/test/node_modules/sqlite3: Command failed.
    Exit code: 1
    Command: node-pre-gyp install --fallback-to-build
    Arguments: 
    Directory: /home/pbrannan/tmp/test/node_modules/sqlite3
    Output:
    module.js:471
        throw err;
        ^
    
    Error: Cannot find module 'process-nextick-args'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/pbrannan/tmp/test/node_modules/readable-stream/lib/_stream_readable.js:26:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)

Under yarn 0.28.4, and yarn 1.0.0 rc without --no-optional, process-nextick-args exists under node_modules:

    pbrannan@telx-sb-dev2:tmp/test $ find . -name '*nextick*'
    ./node_modules/process-nextick-args
    ./node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/process-nextick-args
    ./node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/process-nextick-args

Using --no-optional with yarn 1.0.0 rc, process-nextick-args is missing from the toplevel node_modules, but is present under readable-stream/node_modules:

    pbrannan@telx-sb-dev2:tmp/test $ find . -name '*nextick*'                                      
    ./node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/are-we-there-yet/node_modules/readable-stream/node_modules/process-nextick-args
    ./node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack/node_modules/readable-stream/node_modules/process-nextick-args

As far as I can tell, process-nextick-args is not an optional dependency.

**Comment by PandaWood** [comment] 2017-09-08 04:31
I think this issue is possibly much more widely spread.
I upgrade from 0.27 to 1.0 today, getting many failure to find modules 'require' and 'arial-styles' etc
Removing --ignore-optional fixes everything
I'm no Node 8.2.1 on Windows 10

**Comment by Frugality** [comment] 2017-09-13 16:31
I'm having an issue with --ignore-optional as well. My dependency listed in dependencies is not being installed, causing my build to fail.

**Comment by BYK** [comment] 2017-09-13 16:40
Looks like something was relying on certain hoisting mechanics that changed in the latest versions of yarn. I'd refer you to this discussion to see if it is relevant: https://github.com/yarnpkg/yarn/issues/4420#issuecomment-328912665

**Comment by Frugality** [comment] 2017-09-13 17:32
It isn't a hoisting issue for me. The package listed in my main package.json file in dependencies isn't being installed. I'll need to investigate, but it likely appears as a peer dependency or dev dependency for some other dependencies, but it is definitely a listed dependency of the main package.

**Comment by BYK** [comment] 2017-09-13 21:01
@Frugality - please share your findings with us! Btw. if you share your `package.json` file, others can try replicating and investigating too.

**Comment by PandaWood** [comment] 2017-09-14 01:17
my package.json file if it helps

`{
  "name": "website",
  "version": "0.0.0",
  "private": true,
  "devDependencies": {
    "@types/amplify": "^1.1.17",
    "@types/chai": "^4.0.0",
    "@types/datejs": "0.0.29",
    "@types/es6-promise": "^0.0.32",
    "@types/jquery": "2.0.48",
    "@types/jquery.cookie": "^1.4.28",
    "@types/jqueryui": "^1.11.32",
    "@types/jsuri": "^1.3.29",
    "@types/mocha": "^2.2.37",
    "@types/modernizr": "^3.5.0",
    "@types/tooltipster": "^0.0.28",
    "@types/underscore": "^1.7.33",
    "chai": "^4.0.2",
    "grunt": "^1.0.1",
    "grunt-contrib-coffee": "~0.13.0",
    "grunt-contrib-connect": "^1.0.2",
    "grunt-contrib-sass": "^1.0.0",
    "grunt-contrib-uglify": "^2.0.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-gitinfo": "^0.1.8",
    "grunt-newer": "^1.1.0",
    "grunt-open": "^0.2.3",
    "grunt-ts": "^6.0.0-beta.3",
    "gulp": "^3.9.1",
    "gulp-mocha": "^3.0.1",
    "gulp-typescript": "^3.1.4",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-requirejs": "^1.1.0",
    "karma-spec-reporter": "0.0.26",
    "mocha": "^3.4.2",
    "requirejs": "^2.3.2",
    "sass": "^0.5.0",
    "should": "^11.1.2",
    "typescript": "2.5.2",
    "underscore": "^1.8.3"
  },
  "dependencies": {}
}
`

**Comment by BYK** [comment] 2017-09-14 01:32
I think this is a duplicate of #4445 and should be fixed by #4448.

**Comment by cout** [comment] 2017-09-14 13:49
Agreed; the error is no longer present with #4448.

**Comment by BYK** [comment] 2017-09-14 17:32
Thanks for confirming @cout!

**Closed by BYK** 2017-09-14 17:32 UTC
Labels: bug-resolution, triaged
