### ISSUE TITLE
The absolute path adding not working in nested dependencies

### ISSUE THREAD

**Issue by Antherkiv** [yarnpkg/yarn#2662] opened 2017-02-08 04:05 UTC
Hello yarn is handling incorrectly the absolute path, when you have flat structure of local modules all working perfectly e.g. :

main_module
|
|_local_module1
|_local_module2
|_local_module3

But when you have nested local modules, yarn is trying to resolve as relative:
main_module
|
|_local_module1
              |
              |_nestes_local_module

And for example local module is /home/user/proyect/module1 and nested_local_module is /home/user/proyect/nested_local_module, yarn try to resolve file:/home/user/proyect/nested_local_module as /home/user/proyect/module1/home/user/proyect/nested_local_module

(I'm really on macOS Sierra and I have yarn v0.19.1)

This pull request fix the problem:

https://github.com/yarnpkg/yarn/pull/2444

Thanks, great job, yarn is really good.

/home/user/proyect/module1

**Comment by bestander** [comment] 2017-05-12 20:27
@Antherkiv could you provide a package.json with an example how to reproduce the bug?
I'll close it for now as I can't reproduce it this way

**Closed by bestander** 2017-05-12 20:27 UTC
