### ISSUE TITLE
Can i save changes in node_modules? (我能够保存我对node_modules下的更改吗？)

### ISSUE THREAD

**Issue by xks19943** [yarnpkg/yarn#3826] opened 2017-07-05 03:25 UTC
当我修改node_modules 里面的 一些东西 但是当我yarn add 或者 yarn remove一个新package的时候 会把以前修改的东西又还原？我希望它不还原我对node_modules的更改 我应该怎么做？谢谢！

When i modify some of the things in node_modules but when I yarn add or yarn remove a new package when the previously modified things will be restored?   

Can i save changes in node_modules? what should i do？ Thank you！

**Comment by bingzheyuan** [comment] 2017-07-05 08:42
No you can't and I don't think you should do that at all.

**Comment by BYK** [comment] 2017-07-05 12:37
Hi @xks19943, the purpose of yarn is to create and maintain your `node_modules` folder based on your `package.json` and `yarn.lock` files. So any manual changes in your `node_modules` folder are likely to disappear when you run a `yarn` command.

I'm closing this since this is not a bug nor a feature request. I'd suggest you to ask your question on StackOverflow to get alternative approaches to your problem.

Feel free to repopen if you have a more concrete feature request or you think there's a bug in yarn.

**Closed by BYK** 2017-07-05 12:37 UTC

**Comment by xks19943** [comment] 2017-07-06 01:16
@BYK  Ok thank you
