### ISSUE TITLE
Yarn install fails silently while fetching packages with @angular/cli dependency on Windows.

### ISSUE THREAD

**Issue by cjbturin** [yarnpkg/yarn#5512] opened 2018-03-13 17:38 UTC
Related issue: https://github.com/yarnpkg/yarn/issues/5491

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
While running `yarn install` in project with `package.json` containing `@angular/cli` versions `1.7.1` - `1.7.3` or `1.6.8` process fails silently upon reaching last package while fetching packages.

```
PS C:\Users\turin\yarntest> yarn install
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[#############################################################################################################] 822/823
PS C:\Users\turin\yarntest>
```

`npm install` executes correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn install` in a project with `@angular/cli` versions `1.7.1` - `1.7.3` or `1.6.8` as dependencies on Windows environment.

**What is the expected behavior?**
Package installs correctly or error feedback is provided.

**Please mention your node.js, yarn and operating system version.**
Node: 8.10, 9.8
Yarn: 1.5.1
OS: Windows 10.0.16299 x64, Powershell

**Comment by merceyz** [comment] 2021-01-02 14:47
Unable to reproduce, closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 14:47 UTC
Labels: triaged
