### ISSUE TITLE
Npm organization prefixed packages not mirrored

### ISSUE THREAD

**Issue by raix** [yarnpkg/yarn#1121] opened 2016-10-16 07:11 UTC
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When using `yarn-offline-mirror` and adding eg. `yarn add @types/lodash` the package is not stored in the shared mirror folder. _it's stored fine in `~/.yarn-cache/npm-@types/`_

**If the current behavior is a bug, please provide the steps to reproduce.**

``` bash
# Use a project shared npm mirror
echo "yarn-offline-mirror=my/mirror/folder" > .npmrc

# Add regular package
yarn add lodash

# Add organization prefixed package
yarn add @types/lodash
```

**What is the expected behavior?**
There should exist a `lodash-x.x.x.tgz` and a folder `types` containing `lodash-x.x.x.tgz` all in `my/mirror/folder`

_How are non semver versions handled in mirror eg. git urls? should there be a "resolved-versions" file in the mirror for offline usage? (are these related to "exotic" - we use gitlab internally)_

**Please mention your node.js, yarn and operating system version.**
yarn 0.15.1
node 5.10.1
mac os sierra

**Comment by marvinhagemeister** [comment] 2016-10-16 07:18
Duplicate of https://github.com/yarnpkg/yarn/issues/825

**Comment by raix** [comment] 2016-10-16 07:25
@marvinhagemeister are you sure? this issue is related to the `yarn-offline-mirror` not the `yarn-cache`

**Comment by bestander** [comment] 2017-05-24 15:01
Should be fixed now

**Closed by bestander** 2017-05-24 15:01 UTC
