### ISSUE TITLE
"invalid argument, chown" when running yarn install

### ISSUE THREAD

**Issue by mythmon** [yarnpkg/yarn#1485] opened 2016-10-26 17:51 UTC
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

When running `yarn install` in `docker build`, in CircleCI, fails after `[2/4] Fetching packages...`. This doesn't happen when running `docker build` locally.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://circleci.com/gh/mozilla/normandy/1098#ssh-info/containers/0

**What is the expected behavior?**

Install to succeed

**Please mention your node.js, yarn and operating system version.**

Yarn version: 
  0.16.1

Node version: 
  4.6.1

Platform: 
  Circle CI

**`yarn-error.log`**

```
Arguments: 
  /usr/bin/nodejs /usr/bin/yarn install

PATH: 
  /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  0.16.1

Node version: 
  4.6.1

Platform: 
  linux x64

npm manifest: 
  <SNIP> https://ptpb.pw/WpPb

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

```

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1

<SNIP> https://ptpb.pw/WpPb

Trace: 
  Error: https://registry.yarnpkg.com/react-addons-css-transition-group/-/react-addons-css-transition-group-15.3.1.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-react-addons-css-transition-group-15.3.1/package.json'
      at Error (native)

```
```

**Comment by paflopes** [comment] 2016-10-27 18:46
Same problem here

**Comment by Daniel15** [comment] 2016-12-01 23:01
This looks like a duplicate of #918. Feel free to reopen this issue if that's incorrect. Thanks for trying Yarn! :)

**Closed by Daniel15** 2016-12-01 23:01 UTC
Labels: needs triage
