### ISSUE TITLE
yarn does not symlink metadeps with binaries into the topmost node_modules .bin folder

### ISSUE THREAD

**Issue by probablyup** [yarnpkg/yarn#3059] opened 2017-04-07 04:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running `yarn install` on a dependency tree where a hard dependency that exposes a CLI binary exists one+ level down, that CLI bin is not symlinked into `node_modules/.bin` as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
Repro project: https://github.com/probablyup/sample_repo_a

**What is the expected behavior?**
A symlink to `node_modules/eslint/bin/eslint.js` should be created in `node_modules/.bin`. This is npm's behavior.

**Please mention your node.js, yarn and operating system version.**
node 7.5
yarn 0.21.3
macOS latest

**Comment by rally25rs** [comment] 2017-05-02 14:02
@bestander triage; duplicate of #2874

**Closed** 2017-05-02 14:13 UTC
Labels: triaged
