### ISSUE TITLE
Received malformed response from registry for undefined when private repository is specified.

### ISSUE THREAD

**Issue by Johnz86** [yarnpkg/yarn#5948] opened 2018-06-07 13:52 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If I specify the registry to our private nexus, then yarn will fail on install. Npm install with private registry works. If I specify the registry to public registry, then yarn works.
```
verbose 1.127 Error: Received malformed response from registry for undefined. The registry may be down.
    at MessageError.ExtendableBuiltin (C:\Program Files (x86)\Yarn\lib\cli.js:243:66)
    at new MessageError (C:\Program Files (x86)\Yarn\lib\cli.js:272:123)
    at Function.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:52175:15)
    at Generator.next (<anonymous>)
    at step (C:\Program Files (x86)\Yarn\lib\cli.js:98:30)
    at C:\Program Files (x86)\Yarn\lib\cli.js:116:14
    at new Promise (<anonymous>)
    at new F (C:\Program Files (x86)\Yarn\lib\cli.js:23451:28)
    at Function.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:95:12)
    at Function.findVersionInRegistryResponse (C:\Program Files (x86)\Yarn\lib\cli.js:52217:19)
error Received malformed response from registry for undefined. The registry may be down.
```
This config will fail on yarn install and works on npm install
```
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.7.0 npm/? node/v8.11.2 win32 x64',
  lastUpdateCheck: 1528355987683 }
info npm config
{ registry: 'http://erlh2aca.ad005.onehc.net:8081/repository/dicom-repo-group/',
  '//erlh2aca.ad005.onehc.net:8081/repository/dicom-repo-group/:_authToken': '50814eb9-b7a2-3581-9f0a-472ac625f53e',
  'strict-ssl': false,
  loglevel: 'warn',
  python: 'C:\\Python\\Python27-14',
  proxy: 'http://194.138.0.62:9400/',
  'https-proxy': 'http://194.138.0.62:9400/' }
```
This configuration works yarn install:
```
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/1.7.0 npm/? node/v8.11.2 win32 x64',
  lastUpdateCheck: 1528355987683 }
info npm config
{ registry: 'http://registry.npmjs.com',
  'strict-ssl': false,
  loglevel: 'warn',
  python: 'C:\\Python\\Python27-14',
  proxy: 'http://194.138.0.62:9400/',
  'https-proxy': 'http://194.138.0.62:9400/' }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Set a private repository registry (like Nexus)
Set a connection details with auth token in ```.npmrc``` file
```
registry=http://registry.npmjs.com
strict-ssl=false
loglevel=warn
python=C:\Python\Python27-14
proxy=http://194.138.0.62:9400/
https-proxy=http://194.138.0.62:9400/
```
Execute ```yarn install``` which will fail

**What is the expected behavior?**
```yarn install``` will work when custom repository is configured

**Please mention your node.js, yarn and operating system version.**
Node: v8.11.2
Windows 7 64bit
Yarn: 1.7.0

**Comment by rally25rs** [comment] 2018-06-09 15:28
I suspect this is a duplicate of #5427 (I don't think yarn is picking up the authToken from npmrc. if you don't think this is a duplicate let me know and I can re-open it.)

**Closed by rally25rs** 2018-06-09 15:28 UTC
Labels: triaged

**Comment by Johnz86** [comment] 2018-06-11 07:28
This is not resolved for me. I did as the thread suggested. And tried to config use following configs:
```
npm config set registry http://erlh2aca.ad005.onehc.net:8081/repository/dicom-repo-group/
npm login --registry=http://erlh2aca.ad005.onehc.net:8081/repository/dicom-repo-group/ --always-auth
npm config set always-auth true
yarn config set registry http://erlh2aca.ad005.onehc.net:8081/repository/dicom-repo-group/ \
    && yarn config set always-auth true \
    && yarn login
```
This did not help, and I still was not able to install. I tried to set up _auth token manually that did not help.
Both issues are closed and no suggestion helped me to resolve it. Only related issue that is still open in these thread is #5683 . And that is not related to install.
