### ISSUE TITLE
1.8.0 builds failing

### ISSUE THREAD

**Issue by edqwerty1** [yarnpkg/yarn#5968] opened 2018-06-11 15:15 UTC
Using VSTS and YARN installer task, just migrated to using pre release 1.8.0 (separate issue) and gulp builds started failing with:

` Error: ENOENT: no such file or directory, scandir 'D:\a\1\s\node_modules\node-sass\vendor'`

Forcing back to 1.7.0 fixed the issue, so this is a bug in the 1.8.0 pre release.  Logs from yarn install show it skipping [4/4] Building fresh packages...

This is running on the VSTS Windows 10 Hosted Agent
Node  8.11.2
NPM 5.6.0

1.7.0
```
2018-06-11T09:03:53.4851160Z ==============================================================================
2018-06-11T09:03:53.9943103Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\yarn\1.7.0\x64\yarn-v1.7.0\bin\yarn.cmd --production"
2018-06-11T09:04:14.9326892Z yarn install v1.7.0
2018-06-11T09:04:15.3067893Z info No lockfile found.
2018-06-11T09:04:15.3157616Z [1/4] Resolving packages...
2018-06-11T09:04:17.4714472Z warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T09:04:17.6243758Z warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2018-06-11T09:04:17.8490985Z warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T09:04:17.8492197Z warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T09:04:17.9879794Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T09:04:17.9928265Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T09:04:17.9928706Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2018-06-11T09:04:18.6333163Z warning gulp-notify > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T09:04:18.6900161Z warning gulp-sass > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T09:04:19.2507095Z warning run-sequence > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T09:04:19.6939452Z warning browser-sync > socket.io > engine.io > uws@9.14.0: stop using this version
2018-06-11T09:04:19.8313976Z [2/4] Fetching packages...
2018-06-11T09:06:06.7777122Z info fsevents@1.2.4: The platform "win32" is incompatible with this module.
2018-06-11T09:06:06.7778070Z info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
2018-06-11T09:06:06.7798055Z [3/4] Linking dependencies...
2018-06-11T09:06:10.5265341Z [4/4] Building fresh packages...
2018-06-11T09:06:16.8505437Z success Saved lockfile.
2018-06-11T09:06:16.8533179Z Done in 122.05s.
2018-06-11T09:06:16.8845998Z ##[section]Finishing: Yarn 

```

1.8.0 
```
2018-06-11T14:11:44.7380897Z ==============================================================================
2018-06-11T14:11:45.4074390Z [command]C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\yarn\1.8.0\x64\yarn-v1.8.0\bin\yarn.cmd --production"
2018-06-11T14:12:03.4345319Z yarn install v1.8.0
2018-06-11T14:12:03.7802190Z info No lockfile found.
2018-06-11T14:12:03.7857606Z warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
2018-06-11T14:12:03.7903354Z [1/4] Resolving packages...
2018-06-11T14:12:06.0916465Z warning gulp > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T14:12:06.2776693Z warning gulp > vinyl-fs > graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2018-06-11T14:12:06.6244353Z warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T14:12:06.6244746Z warning gulp > vinyl-fs > glob-stream > glob > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T14:12:06.7413958Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T14:12:06.7451594Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
2018-06-11T14:12:06.7451842Z warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
2018-06-11T14:12:07.0483632Z warning gulp-notify > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T14:12:07.1165720Z warning gulp-sass > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T14:12:07.6133170Z warning run-sequence > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
2018-06-11T14:12:08.0246086Z warning browser-sync > socket.io > engine.io > uws@9.14.0: stop using this version
2018-06-11T14:12:08.1394958Z [2/4] Fetching packages...
2018-06-11T14:13:50.6202334Z info fsevents@1.2.4: The platform "win32" is incompatible with this module.
2018-06-11T14:13:50.6202950Z info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
2018-06-11T14:13:50.6256667Z [3/4] Linking dependencies...
2018-06-11T14:13:55.1056290Z ##[section]Finishing: Yarn 
```

**Comment by BYK** [comment] 2018-06-11 15:49
Sorry but this is not enough information to do any debugging. There is no official or a single "1.8.0 pre-release". We have nightly builds but your logs don't show a version number we'd see in our nightly builds.

Moreover, there's no information for us to reproduce or debug the issue. The logs are also insufficient.

I'm going to close this issue since it is not actionable. If you'd like someone to help you, please use a nightly build at least and then follow the issue template and provide all requested information.

**Closed by BYK** 2018-06-11 15:49 UTC
Labels: triaged
