### ISSUE TITLE
PackageHoister seed takes a very long time (stuck) on complex / monorepo / workspaces projects

### ISSUE THREAD

**Issue by lxe** [yarnpkg/yarn#5628] opened 2018-04-06 20:32 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Installing large, complex projects (10k total transitive and non-transitive dependencies) spend most of their time in getFlatHoistedTree:

<img width="1073" alt="screen shot 2018-04-06 at 1 27 09 pm" src="https://user-images.githubusercontent.com/1486609/38442855-85e84558-399e-11e8-837d-17416fba7774.png">

I'm working on a generic reproducible case, but to summarize, I have 542 workspaces in one yarn project, and generating the lockfile is pretty much stuck in the getFlatHoistedTree / package-hoister seed. 

I think the `queue` contains around 12 million objects, and I think repeatedly iterating and copying the objects is causing the degradation. 

Is there a way to optimize this? 

Node Version: **9+**
Yarn: **1.6.1+**

**Comment by lxe** [comment] 2018-04-06 20:58
Looks like it's just loop iteration and/or splicing the array (16 million elements):

<img width="475" alt="screen shot 2018-04-06 at 1 55 24 pm" src="https://user-images.githubusercontent.com/1486609/38443919-3917fce2-39a2-11e8-917e-6dcc4137e2ed.png">

The actual `availableSet.add(pattern);` and `getStrictResolvedPattern` are quick, with long gaps of unprofiled code in between:

<img width="586" alt="screen shot 2018-04-06 at 1 55 31 pm" src="https://user-images.githubusercontent.com/1486609/38444016-95d9e7e2-39a2-11e8-94ee-ed4121b814fc.png">





```js
        for (let t = 0; t < queue.length; ++t) {
          const pattern = queue[t][0];
          const pkg = this.resolver.getStrictResolvedPattern(pattern);

          const peerDependencies = Object.keys(pkg.peerDependencies || {});
          const areDependenciesFulfilled = peerDependencies.every(peerDependency => availableSet.has(peerDependency));

          if (areDependenciesFulfilled) {
            // Move the package inside our sorted queue
            sortedQueue.push(queue[t]);
            queue.splice(t--, 1);

            // Add it to our set, so that we know it is available
            availableSet.add(pattern);

            // Schedule a next pass, in case other packages had peer dependencies on this one
            hasChanged = true;
          }
        }
      }
```

**Comment by bestander** [comment] 2018-04-06 21:51
This is a nice analysis, finally we are getting bottlenecked not on IO :)

Any suggestions/PR on data structures/caches?

**Comment by rally25rs** [comment] 2018-04-12 15:56
Linking #5648 to this, which indicates that this problem also exists when using resolutions.

**Comment by hulkish** [comment] 2018-04-12 17:32
@rally25rs I feel like this seed method is obviously attempting far more work than what is necessary... What is the goal with this seed step?

**Comment by hulkish** [comment] 2018-04-14 19:35
@rally25rs I'd like to make a pr for this... But I would first like to understand what the goal is for this function - so i can better determine what redundant work is occuring in this logic - and so that i can safely refactor without breaking the use case

**Comment by rally25rs** [comment] 2018-04-17 00:31
Sorry for the slow reply @hulkish it's been a busy week... 
I didn't write the original function, and it's been a while since I looked at it, but IIRC that function basically builds the entire resolved dependency tree and all transitive dependencies, and determines hoisting and deduplication when needed. It's pretty complicated...

Hopefully the unit tests around that class are good enough to indicate any problems with logic changes.

**Comment by rally25rs** [comment] 2018-04-17 01:01
@hulkish do you have a package.json to reproduce #5648? I'd like to help dig into this further.

**Comment by hulkish** [comment] 2018-04-17 01:10
@rally25rs I see. Well, what I would like to do is refactor this method a bit beginning at the seed method. This method really should start out as a generator, as opposed to generators being processed within a synchronous loop (which I believe is the root cause of our problem).

**Comment by hulkish** [comment] 2018-04-17 01:13
@rally25rs The one I have is under proprietary circumstances - private deps etc. Although, the Memory leak issue is visible by even just defining 2, resolutions of any dependency. It's a small increase to loop for - but it's there.

I'll put together a package.json in a gist to demonstrate the issue.

**Comment by no-more** [comment] 2018-04-25 09:36
Hi,

I have just opened a new issue(#5726) before finding this one, I'm not sure if it's the exact same problem but I have include a zip file which can reproduce the issue. Maybe it could help.

**Comment by hulkish** [comment] 2018-06-12 17:32
@no-more that zip is very helpful. Demonstrates the issue accurately. Thanks!

**Comment by hulkish** [comment] 2018-06-13 22:40
> and I think repeatedly iterating and copying the objects is causing the degradation
@lxe can you elaborate on this?

**Comment by sibelius** [comment] 2019-12-10 21:39
any workaround for this?

**Comment by sibelius** [comment] 2019-12-10 21:52
I've made a repro for this https://github.com/sibelius/yarn-workspaces-slow

**Comment by merceyz** [comment] 2021-01-03 03:18
Closing as fixed in v2 where the hoisting algorithm has been greatly improved

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-03 03:18 UTC
Labels: triaged
