### ISSUE TITLE
Error: https://registry.yarnpkg.com/@angular/common/-/common-6.0.2.tgz: unexpected end of file

### ISSUE THREAD

**Issue by rbatllet** [yarnpkg/yarn#5828] opened 2018-05-16 10:21 UTC
Arguments: 
  /usr/local/Cellar/node/10.1.0/bin/node /usr/local/Cellar/yarn/1.6.0/libexec/bin/yarn.js

PATH: 
  /Users/user/.sdkman/candidates/grails/current/bin:/Users/user/.sdkman/candidates/gradle/current/bin:/usr/local/opt/curl/bin:/Users/user/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/user/opt/apache-tomcat/bin:/Users/user/opt/apache-maven/bin:/Users/user/opt/android-sdk/platform-tools:/Users/user/.yarn/bin

Yarn version: 
  1.6.0

Node version: 
  10.1.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/@angular/common/-/common-6.0.2.tgz: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:153:17)

npm manifest: 
  {
    "name": "client",
    "version": "1.0.0",
    "license": "private",
    "scripts": {
      "ng": "ng",
      "start": "ng serve --aot --open",
      "build": "ng build",
      "buildProd": "ng build --prod --source-map",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular/animations": "^6.0.0",
      "@angular/common": "^6.0.0",
      "@angular/compiler": "^6.0.0",
      "@angular/core": "^6.0.0",
      "@angular/forms": "^6.0.0",
      "@angular/http": "^6.0.0",
      "@angular/platform-browser": "^6.0.0",
      "@angular/platform-browser-dynamic": "^6.0.0",
      "@angular/router": "^6.0.0",
      "core-js": "^2.5.4",
      "lodash": "^4.17.5",
      "primeng": "^5.2.3",
      "rxjs": "^6.0.0",
      "rxjs-compat": "^6.1.0",
      "zone.js": "^0.8.26"
    },
    "devDependencies": {
      "@angular-devkit/build-angular": "~0.6.1",
      "@angular/cli": "~6.0.1",
      "@angular/compiler-cli": "^6.0.0",
      "@angular/language-service": "^6.0.0",
      "@types/jasmine": "~2.8.6",
      "@types/jasminewd2": "~2.0.3",
      "@types/lodash": "^4.14.105",
      "@types/node": "~8.9.4",
      "codelyzer": "~4.2.1",
      "jasmine-core": "~2.99.1",
      "jasmine-spec-reporter": "~4.2.1",
      "karma": "~1.7.1",
      "karma-chrome-launcher": "~2.2.0",
      "karma-coverage-istanbul-reporter": "~1.4.2",
      "karma-jasmine": "~1.1.1",
      "karma-jasmine-html-reporter": "^0.2.2",
      "protractor": "~5.3.0",
      "ts-node": "~5.0.1",
      "tslint": "~5.9.1",
      "typescript": "~2.7.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

**Comment by rbatllet** [comment] 2018-05-16 10:28
The same with Angular 6.0.1 version:

Error: https://registry.yarnpkg.com/@angular/common/-/common-6.0.1.tgz: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:153:17)

**Comment by pxgamer** [comment] 2018-05-16 10:41
Getting this with `@fortawesome/fontawesome-free-regular` too. 👍

```
Yarn version: 
  1.6.0

Node version: 
  10.1.0

Platform: 
  win32 x64

Trace: 
  Error: https://registry.yarnpkg.com/@fortawesome/fontawesome-free-regular/-/fontawesome-free-regular-5.0.13.tgz: unexpected end of file
      at Zlib.zlibOnError [as onerror] (zlib.js:153:17)
```

**Comment by zerocewl** [comment] 2018-05-16 10:42
same here for
yarn add @angular/material @angular/cdk

**Comment by jerguslejko** [comment] 2018-05-16 10:46
same here

**Comment by taijuten** [comment] 2018-05-16 10:58
Also getting this for multiple from the `@fortawesome` repos

**Comment by rally25rs** [comment] 2018-05-16 10:58
These seem to be working for me:

```
~/Projects/yarn-test2 🐒   yarn init -y
yarn init v1.6.0
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.03s.

~/Projects/yarn-test2 🐒   yarn add @fortawesome/fontawesome-free-solid
yarn add v1.6.0
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ @fortawesome/fontawesome-free-solid@5.0.13
info All dependencies
├─ @fortawesome/fontawesome-common-types@0.1.7
└─ @fortawesome/fontawesome-free-solid@5.0.13
✨  Done in 1.99s.

~/Projects/yarn-test2 🐒   yarn add @angular/material @angular/cdk
yarn add v1.6.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @angular/material@6.0.2" has unmet peer dependency "@angular/core@>=6.0.0-beta.0 <7.0.0".
warning " > @angular/material@6.0.2" has unmet peer dependency "@angular/common@>=6.0.0-beta.0 <7.0.0".
warning " > @angular/cdk@6.0.2" has unmet peer dependency "@angular/core@>=6.0.0-beta.0 <7.0.0".
warning " > @angular/cdk@6.0.2" has unmet peer dependency "@angular/common@>=6.0.0-beta.0 <7.0.0".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
├─ @angular/cdk@6.0.2
└─ @angular/material@6.0.2
info All dependencies
├─ @angular/cdk@6.0.2
└─ @angular/material@6.0.2
✨  Done in 5.15s.
```

but maybe the problem is regional? 🤷‍♂️

**Comment by jneves** [comment] 2018-05-16 10:59
The registry has some problems, but I have at least 10 installs of yarn fail with exit code 0:

```
$ ../node_modules/yarn/bin/yarn install --verbose --network-timeout 1000000 && date
yarn install v1.6.0
verbose 0.443 Checking for configuration file "/home/app/.npmrc".
verbose 0.446 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.446 Checking for configuration file "/usr/local/etc/npmrc".
verbose 0.448 Checking for configuration file "/root/.npmrc".
verbose 0.449 Checking for configuration file "/home/app/.npmrc".
verbose 0.45 Checking for configuration file "/home/.npmrc".
verbose 0.452 Checking for configuration file "/home/app/.yarnrc".
verbose 0.454 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.455 Found configuration file "/usr/local/share/.yarnrc".
verbose 0.457 Checking for configuration file "/usr/local/etc/yarnrc".
verbose 0.458 Checking for configuration file "/root/.yarnrc".
verbose 0.459 Checking for configuration file "/home/app/.yarnrc".
verbose 0.46 Checking for configuration file "/home/.yarnrc".
verbose 0.476 current time: 2018-05-16T10:49:53.366Z
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
(... clipped ...)
[3/5] Fetching packages...
verbose 77.919 Performing "GET" request to "https://registry.yarnpkg.com/@webcomponents/webcomponentsjs/-/webcomponentsjs-1.0.22.tgz".
[############################################################################] 1431/1432Wed May 16 10:49:42 UTC 2018
```

You'll notice the date call at the end. Noticed first when it happened on a CI build.

**Comment by Clowting** [comment] 2018-05-16 11:14
I'm experiencing the same problems, the [status website](https://status.yarnpkg.com/) doesn't show any issues at the moment though.

**Comment by alexanderleipzig** [comment] 2018-05-16 11:18
We also having this issue. Region: Germany.

**Comment by pxgamer** [comment] 2018-05-16 11:19
Seems to be working for me now. 🤔

**Comment by benjdlambert** [comment] 2018-05-16 11:25
Me too getting some fastly error.

```
Fastly error: unknown domain: registry.yarnpkg.com. Please check that this domain has been added to a service.

Details: cache-bma7031-BMA
```

**Comment by atkinchris** [comment] 2018-05-16 11:25
Same issue in the UK here:

```
Fastly error: unknown domain: registry.yarnpkg.com. Please check that this domain has been added to a service.

Details: cache-lcy19244-LCY
```

**Comment by tristanbes** [comment] 2018-05-16 11:39
Same in France: 

```
error An unexpected error occurred: "https://registry.yarnpkg.com/algoliasearch/-/algoliasearch-3.25.1.tgz: Request failed \"500 Internal Server Error\"".
```

**Comment by zerocewl** [comment] 2018-05-16 11:40
Seems to be working for me now too. thinking thinking

**Comment by rbatllet** [comment] 2018-05-16 12:09
Working again!

**Comment by selem1** [comment] 2018-05-16 14:00
Same here in Tunisia :tunisia:

**Comment by pxgamer** [comment] 2018-05-25 14:41
This can probably be closed as it seems like it was a temporary issue? Unless other people are still experiencing this.

**Comment by ahmadrasyidsalim** [comment] 2018-09-18 22:27
Same! In Indonesia!

```bash
node:22293) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/common/-/common-6.1.0-rc.3.tgz: ESOCKETTIMEDOUT".
```

**Comment by hron84** [comment] 2019-09-11 08:42
@rbatllet could you reopen this? It's still happening from Hungary right now, even with npmjs.org registry. I think it's not a Yarn registry issue anymore.

```
error An unexpected error occurred: "https://registry.npmjs.org/@angular/common/-/common-8.2.5.tgz: unexpected end of file".
info If you think this is a bug, please open a bug report with the information provided in "/mnt/c/Users/20150/Projects/ng-test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by hron84** [comment] 2019-09-17 14:41
@rbatllet thank you very much!

**Comment by merceyz** [comment] 2021-01-02 14:50
Closing as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 14:50 UTC
Labels: triaged
