### ISSUE TITLE
Could not find a copy of {pkg.name} to link in {location}

### ISSUE THREAD

**Issue by tquetano-r7** [yarnpkg/yarn#6285] opened 2018-08-20 13:35 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When doing `yarn install`, I get an linking error at the very end when `yarn` attempts to link packages under the hood, causing the overall install to fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is consistently reproducible when running a simple `yarn install`. This was also present in version `1.9.2`, but I waited to see if `1.9.4` would fix it, as it was a fast-follow.

Here is the (sanitized) error in trace in my `yarn-error.log` => 

```
Invariant Violation: could not find a copy of uuid to link in /home/tquetano/git/{repository}/node_modules/{package}/node_modules
      at invariant (/usr/lib/node_modules/yarn/lib/cli.js:1745:15)
      at PackageLinker.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:49512:7)
      at Generator.next (<anonymous>)
      at step (/usr/lib/node_modules/yarn/lib/cli.js:92:30)
      at /usr/lib/node_modules/yarn/lib/cli.js:103:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**What is the expected behavior?**

To install properly!

**Please mention your node.js, yarn and operating system version.**

Node => 8.11.4
Yarn => 1.9.4
OS => Manjaro Linux (Arch-based)

If there is more specific information I can provide to help, please let me know.

**Comment by fenduru** [comment] 2018-08-27 19:17
I'm also running into this - started happening randomly today (not related to upgrading yarn. previous `yarn` runs in the same folder had been successful).

Tried wiping the yarn cache manually to no avail

**Comment by brunolemos** [comment] 2018-09-28 22:47
I have this error every time I run `yarn`. I use workspaces and have used `yarn link` on the package `react-scripts`.

Part of the log:

<details>
<summary>yarn-error.log</summary>

```bash
Arguments: 
  /usr/local/bin/node /Users/brunolemos/.yarn/bin/yarn.js add apollo-server graphql

PATH: 
  /Users/brunolemos/.rbenv/shims:/Users/brunolemos/.rbenv/bin:/Users/brunolemos/.fastlane/bin:/Users/brunolemos/.yarn/bin:/Users/brunolemos/.config/yarn/global/node_modules/.bin:/usr/local/bin/mongo/bin:/usr/local/bin:/Users/brunolemos/.npm-global/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/brunolemos/Library/Android/sdk//bin:/Users/brunolemos/Library/Android/sdk/platform-tools/

Yarn version: 
  1.10.1

Node version: 
  8.11.4

Platform: 
  darwin x64

Trace: 
  Invariant Violation: could not find a copy of eslint to link in /Users/brunolemos/Projects/workstories/node_modules/web/node_modules/react-scripts/node_modules
      at invariant (/Users/brunolemos/.yarn/lib/cli.js:1736:15)
      at PackageLinker.<anonymous> (/Users/brunolemos/.yarn/lib/cli.js:45555:7)
      at Generator.next (<anonymous>)
      at step (/Users/brunolemos/.yarn/lib/cli.js:98:30)
      at /Users/brunolemos/.yarn/lib/cli.js:109:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

npm manifest: 
  {
    "name": "server",
    "version": "0.0.1",
    "dependencies": {
      "shared": "0.0.1"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
  
  
  "@babel/code-frame@7.0.0", "@babel/code-frame@^7.0.0", "@babel/code-frame@^7.0.0-beta.35":
    version "7.0.0"
    resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8"
    integrity sha512-OfC2uemaknXr87bdLUkWog7nYuliM9Ij5HUcajsVcMCpQrcLmtxRbVFTIqmcSkSeYRBFBRxs2FiUqFJDLdiebA==
    dependencies:
      "@babel/highlight" "^7.0.0"
  
  "@babel/code-frame@7.0.0-beta.44":
    version "7.0.0-beta.44"
    resolved "http://registry.npmjs.org/@babel/code-frame/-/code-frame-7.0.0-beta.44.tgz#2a02643368de80916162be70865c97774f3adbd9"
    integrity sha512-cuAuTTIQ9RqcFRJ/Y8PvTh+paepNcaGxwQwjIDRWPXmzzyAeCO4KqS9ikMvq0MCbRk6GlYKwfzStrcP3/jSL8g==
    dependencies:
      "@babel/highlight" "7.0.0-beta.44"
  
  "@babel/code-frame@7.0.0-beta.47":
    version "7.0.0-beta.47"
    resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0-beta.47.tgz#d18c2f4c4ba8d093a2bcfab5616593bfe2441a27"
    integrity sha512-W7IeG4MoVf4oUvWfHUx9VG9if3E0xSUDf1urrnNYtC2ow1dz2ptvQ6YsJfyVXDuPTFXz66jkHhzMW7a5Eld7TA==
    dependencies:
      "@babel/highlight" "7.0.0-beta.47"
  
  "@babel/core@7.0.0-beta.47":
    version "7.0.0-beta.47"
    resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.0.0-beta.47.tgz#b9c164fb9a1e1083f067c236a9da1d7a7d759271"
    integrity sha512-7EIuAX0UVnCgZ0E9tz9rFK0gd+aovwMA9bul+dnkmBQYLrJdas2EHMUSmaK67i1cyZpvgVvXhHtXJxC7wo3rlQ==
    dependencies:
      "@babel/code-frame" "7.0.0-beta.47"
      "@babel/generator" "7.0.0-beta.47"
      "@babel/helpers" "7.0.0-beta.47"
      "@babel/template" "7.0.0-beta.47"
      "@babel/traverse" "7.0.0-beta.47"
      "@babel/types" "7.0.0-beta.47"
      babylon "7.0.0-beta.47"
      convert-source-map "^1.1.0"
      debug "^3.1.0"
      json5 "^0.5.0"
      lodash "^4.17.5"
      micromatch "^2.3.11"
      resolve "^1.3.2"
      semver "^5.4.1"
      source-map "^0.5.0"
  
  "@babel/core@7.1.0", "@babel/core@^7.0.1", "@babel/core@^7.1.0":
    version "7.1.0"
    resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.1.0.tgz#08958f1371179f62df6966d8a614003d11faeb04"
    integrity sha512-9EWmD0cQAbcXSc+31RIoYgEHx3KQ2CCSMDBhnXrShWvo45TMw+3/55KVxlhkG53kw9tl87DqINgHDgFVhZJV/Q==
    dependencies:
      "@babel/code-frame" "^7.0.0"
      "@babel/generator" "^7.0.0"
      "@babel/helpers" "^7.1.0"
      "@babel/parser" "^7.1.0"
      "@babel/template" "^7.1.0"
      "@babel/traverse" "^7.1.0"
      "@babel/types" "^7.0.0"
      convert-source-map "^1.1.0"
      debug "^3.1.0"
      json5 "^0.5.0"
      lodash "^4.17.10"
      resolve "^1.3.2"
      semver "^5.4.1"
      source-map "^0.5.0"
  

  
  react-scripts@2.0.0:
    version "2.0.0"
    resolved "https://registry.yarnpkg.com/react-scripts/-/react-scripts-2.0.0.tgz#baed13bd7e1592f6df8fb19a186671cdb0a92018"
    integrity sha512-lZNltuWfgD44Z+pyMU9iiZiuYhF1zJvXmFnuI5tKwgGuy7NuQpdD/fiO1UEO4VgtHZwFO84VvQoZGGnbm+8+2w==
    dependencies:
      "@babel/core" "7.1.0"
      "@babel/runtime" "7.0.0"
      "@svgr/webpack" "2.4.1"
      babel-core "7.0.0-bridge.0"
      babel-eslint "9.0.0"
      babel-jest "23.6.0"
      babel-loader "8.0.2"
      babel-plugin-named-asset-import "^0.2.0"
      babel-preset-react-app "^4.0.0"
      bfj "6.1.1"
      case-sensitive-paths-webpack-plugin "2.1.2"
      chalk "2.4.1"
      css-loader "1.0.0"
      dotenv "6.0.0"
      dotenv-expand "4.2.0"
      eslint "5.6.0"
      eslint-config-react-app "^3.0.0"
      eslint-loader "2.1.1"
      eslint-plugin-flowtype "2.50.1"
      eslint-plugin-import "2.14.0"
      eslint-plugin-jsx-a11y "6.1.1"
      eslint-plugin-react "7.11.1"
      file-loader "2.0.0"
      fs-extra "7.0.0"
      html-webpack-plugin "4.0.0-alpha.2"
      identity-obj-proxy "3.0.0"
      jest "23.6.0"
      loader-utils "1.1.0"
      mini-css-extract-plugin "0.4.3"
      optimize-css-assets-webpack-plugin "5.0.1"
      postcss-flexbugs-fixes "4.1.0"
      postcss-loader "3.0.0"
      postcss-preset-env "6.0.6"
      postcss-safe-parser "4.0.1"
      react-app-polyfill "^0.1.0"
      react-dev-utils "^6.0.0"
      resolve "1.8.1"
      sass-loader "7.1.0"
      style-loader "0.23.0"
      sw-precache-webpack-plugin "0.11.5"
      terser-webpack-plugin "1.1.0"
      thread-loader "1.2.0"
      url-loader "1.1.1"
      webpack "4.19.1"
      webpack-dev-server "3.1.9"
      webpack-manifest-plugin "2.0.4"
    optionalDependencies:
      fsevents "1.2.4"
```
<details>

**Comment by czycha** [comment] 2018-10-23 20:40
I'm seeing this also. I believe it has to do with peer-dependencies. In my case, I'm trying to install `eslint-config-standard-preact` which has a peer dependency of `eslint >= 3.0.0`. When I have `eslint-config-standard-preact` installed and run `yarn add -D eslint`, I receive errors similar to those above even though the version it is installing (5.7.0) matches that criteria. As pointed out on https://github.com/zouhir/eslint-config-standard-preact/issues/11, you can install a specific version (even if it's effectively the same) and it'll work (ex. `yarn add -D eslint@5.7.0`).

**Comment by sibelius** [comment] 2018-10-29 20:13
any workaround for this?

**Comment by sibelius** [comment] 2018-10-29 20:28
this happened to me, when I have set `eslint` to be `nohoist` but we had different versions of eslint in some lerna packages when using yarn workspaces

**Comment by wangzuo** [comment] 2018-12-05 03:48
Removing `nohoist` help me get rid of this issue.

**Comment by gitowiec** [comment] 2019-01-18 19:22
I am heavly slowed down by this issue, Can't even do any progress (need new packages from npm registry). Our project is in monorepo and we are using workspaces, two of our private packages (packages/*) have nohoist

<details>
  <summary>part of the error log is here</summary>
Arguments: 
  /home/marek/.nvm/versions/node/v8.11.4/bin/node /usr/share/yarn/lib/cli.js add uuid

PATH: 
  /home/marek/.nvm/versions/node/v8.11.4/bin:/home/marek/workspace/secret-project/node_modules/.bin:/home/marek/.yarn/bin:/home/marek/scripts:/home/marek/bin:/home/marek/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/marek/programs:/usr/local/jdk-9.0.4/bin

Yarn version: 
  1.13.0

Node version: 
  8.11.4

Platform: 
  linux x64

Trace: 
  Invariant Violation: could not find a copy of uuid to link in /home/marek/workspace/secret-project/node_modules/@storybook/addon-actions/node_modules
      at invariant (/usr/share/yarn/lib/cli.js:2168:15)
      at PackageLinker.<anonymous> (/usr/share/yarn/lib/cli.js:47979:7)
      at Generator.next (<anonymous>)
      at step (/usr/share/yarn/lib/cli.js:304:30)
      at /usr/share/yarn/lib/cli.js:315:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

npm manifest: 
  {
    "name": "payment-notification-sender",
    "private": true,
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "workspaces": {
      "nohoist": [
        "**"
      ]
    },
    "scripts": {
      "clean": "rimraf dist",
      "copy-func-config": "cp  ./src/function.source.json ./dist/function.json",
      "build:prod": "yarn run clean && tsc && yarn run copy-func-config",
      "build": "yarn run clean && tsc && yarn run copy-func-config",
      "start": "yarn run build && concurrently --names \"WATCH,HTTP\" -k false -r \"tsc -w\" \"sleep 3; yarn run func:start \"",
      "func:start": "func start"
    },
    "devDependencies": {
      "@types/joi": "14.0.1",
      "@types/node": "10.12.18",
      "@types/nodemailer": "4.6.5",
      "@types/react": "16.7.20",
      "@types/react-dom": "16.0.11",
      "concurrently": "4.1.0",
      "rimraf": "2.6.3",
      "tslint": "5.12.1",
      "typescript": "3.2.2"
    },
    "dependencies": {
      "azure-functions-ts-essentials": "1.3.2",
      "bunyan": "1.8.12",
      "bunyan-prettystream": "0.1.3",
      "convict": "4.4.1",
      "email-templates": "0.0.1",
      "joi": "14.3.1",
      "nodemailer": "5.1.1",
      "react": "16.7.0",
      "react-dom": "16.7.0"
    }
  }

yarn manifest: 
  No manifest


</details>

**Comment by gitowiec** [comment] 2019-01-18 19:33
I found a stupid workaround, just specify version like this `yarn add uuid@3.3.2` I did it following the `yarn clean cache uuid` but it could be enough by itself

**Comment by richardsimko** [comment] 2019-03-29 08:51
This started happening to me randomly with webpack in a repo where I've never used link. Yarn is not completely broken for me in that project.

**Comment by baflo** [comment] 2019-09-11 07:19
Was anybody able to tackle this problem eventually?

**Comment by verydanny** [comment] 2019-09-13 16:55
I found out `homebrew` can fix these issues with `brew doctor`. In my case, I was writing a `webpack` library and it symlinked it. Brew found the symlink and purged it.

Woo

**Comment by msendlakowski** [comment] 2019-10-17 21:18
Here is another concrete example:
https://github.com/msendlakowski/workspaces-test

The above will throw the error:  
```
An unexpected error occurred: "could not find a copy of marko to link in /Users/msendlakowski/repos/workspaces-test-2/node_modules/package-a/node_modules".
```

But if I change the peerDependency in `package-a` from `"marko": "^3 || ^4"` to `"marko": "^3"` it works fine.

**Comment by speter9701** [comment] 2019-11-19 18:14
Try "npm install" instead of "yarn add". It solved my problems connected to eslint.

**Comment by jasonk** [comment] 2020-06-11 19:04
I also ran into this in a monorepo, with a workspace that depended on `pino` and I kept getting the `could not find a copy of pino to link to in...`.  What ended up working for me as a workaround was to `yarn add -W pino` in the root.  I guess having that depended on at the top level as well caused it to be put in a place where it could be found for the later step...

**Comment by seeliang** [comment] 2020-07-19 23:51
for my case, my walk-around is moved all `devDependency` to the root with `yarn add -D -W`.

**Comment by zen0822** [comment] 2020-11-05 06:45
for my work, i try to install linked package, and i add version after package, it worked
not work:
yarn add ui -W --dev
worked:
yarn add ui@1.0.0 -W --dev

**Comment by HomyeeKing** [comment] 2020-12-11 02:54
> I found a stupid workaround, just specify version like this `yarn add uuid@3.3.2` I did it following the `yarn clean cache uuid` but it could be enough by itself

what's the theory behind this, it also works for me

**Comment by Andarist** [comment] 2020-12-26 22:30
Just some random findings that maybe would allow somebody to pinpoint the issue. In my case, the problem was somehow caused by the fact that [`findNearestInstalledVersionOfPackage`](https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/package-linker.js#L156) was called for a manifest containing `ts-jest` and `binLoc` equal to `<root>/node_modules/vue-jest/node_modules` **but** [`allLocations`](https://github.com/yarnpkg/yarn/blob/a4708b29ac74df97bac45365cba4f1d62537ceb7/src/package-linker.js#L163) has contained only a path to `<root>/node_modules/tsdx/node_modules/ts-jest`. I have `ts-jest` defined as root's dependency and also as devDependency of most of my monorepo packages - additionally 2 of my dependencies depend on `ts-jest` (`tsdx` and `vue-jest`). After removing the `tsdx` completely from the project the issue has been fixed,

My bet would be that for some reason `findNearestInstalledVersionOfPackage` is called in my scenario before `pkg._reference.locations` has a chance to be fully populated correctly (sorting issue somewhere?) or that for some reason my hoisted dev/dependency (`ts-jest`) is not correctly populating `pkg._reference.locations`

**Comment by hyochan** [comment] 2021-01-03 17:15
> I found a stupid workaround, just specify version like this `yarn add uuid@3.3.2` I did it following the `yarn clean cache uuid` but it could be enough by itself

Confirmed clearing caches work.

**Comment by Pines-Cheng** [comment] 2021-01-13 09:13
Removing nohoist help me get rid of this issue.

**Comment by merceyz** [comment] 2021-01-13 09:20
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-13 09:20 UTC
Labels: triaged

**Comment by jacksteamdev** [comment] 2021-02-26 18:15
This showed up for me when a child package had `typescript` in both `devDependencies` and `peerDependencies`.

I tried upgrading the dev dep, but didn't notice the peer dep and Yarn failed with the helpful error `Could not find a copy...`. Took 30 minutes to notice that peer dependency and bump it too. Then everything works no problem.

So check if the dependency is in multiple lists in the `package.json`.

**Comment by ical10** [comment] 2021-08-30 06:43
> I found a stupid workaround, just specify version like this `yarn add uuid@3.3.2` I did it following the `yarn clean cache uuid` but it could be enough by itself

Confirmed working for `@trivago/prettier-plugin-sort-imports` package, but the order of the command is wrong. 
I ran:
`yarn cache clean @trivago/prettier-plugin-sort-imports`

**Comment by jannikschaper** [comment] 2024-02-12 16:40
> This showed up for me when a child package had `typescript` in both `devDependencies` and `peerDependencies`.
> 
> I tried upgrading the dev dep, but didn't notice the peer dep and Yarn failed with the helpful error `Could not find a copy...`. Took 30 minutes to notice that peer dependency and bump it too. Then everything works no problem.
> 
> So check if the dependency is in multiple lists in the `package.json`.

In my case, the version was the same in both devDependencies and peerDependencies (`"webpack": "^5.89.0"`). What worked was to remove the entry from peerDependencies entirely
