### ISSUE TITLE
Can't start new project

### ISSUE THREAD

**Issue by celicoo** [yarnpkg/yarn#2179] opened 2016-12-07 16:10 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**

When i try to init with the command `yarn init`, the following error occurs after answering the question `question entry point (index.js)`:

`error An unexpected error occurred: "Cannot convert object to primitive value".`

**Please mention your node.js, yarn and operating system version.**

node.js: v6.9.2
yarn: v0.17.10
os:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Trace from the yarn-error.log file:

```json
Arguments: 
  /usr/bin/nodejs /usr/share/yarn/bin/yarn.js init

PATH: 
  /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Yarn version: 
  0.17.10

Node version: 
  6.9.2

Platform: 
  linux x64

npm manifest: 
  {
    "name": "dataextractor",
    "version": "4.7.5",
    "description": "Script to extract data from files",
    "author": "Marcelo Franco Filipe Alves <marcelo.alves@garimpo.io>",
    "private": true,
    "engines": {
      "node": "6.7.0",
      "npm": "3.10.8"
    },
    "repository": {
      "type": "git",
      "url": "https://github.com/Garimpo/DataExtractor"
    },
    "bugs": {
      "url": "https://github.com/Garimpo/DataExtractor/issues"
    },
    "scripts": {
      "start": "node-dev ./index.ls"
    },
    "dependencies": {
      "@extract/textract": "4.1.0",
      "async": "1.5.2",
      "chalk": "1.1.1",
      "debug": "2.2.0",
      "glob": "7.0.3",
      "inquirer": "1.0.2",
      "livescript": "1.5.0",
      "mime": "1.3.4",
      "node-dev": "3.1.3",
      "node-xlsx": "0.7.1"
    },
    "devDependencies": {
      "gulp": "3.9.1",
      "gulp-js-obfuscator": "1.0.0",
      "gulp-livescript": "3.0.1"
    },
    "license": "UNLICENSED"
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  TypeError: Cannot convert object to primitive value
      at Object.<anonymous> (/usr/share/yarn/lib/cli/commands/init.js:93:27)
      at next (native)
      at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by sebn** [comment] 2016-12-22 08:42
Isn't it the same as #1924 ?

**Comment by torifat** [comment] 2016-12-22 11:28
@sebn Yes, thanks 👍

**Comment by gsklee** [comment] 2017-06-14 05:48
@bestander close; dupe of #1924

**Closed** 2017-06-14 11:16 UTC
Labels: bug

**Comment by torifat** [comment] 2017-06-14 11:17
Sorry, my bad. I wrote the comment but missed to close it 😞
