### ISSUE TITLE
Projects with both a `package.json` and `bower.json` will only install `npm` dependencies when `yarn` is invoked

### ISSUE THREAD

**Issue by devinus** [yarnpkg/yarn#898] opened 2016-10-12 15:36 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

`yarn install` in a project with both a `package.json` and `bower.json` will only install `npm` dependencies.

**What is the expected behavior?**

Install both `npm` and `bower` dependencies at once.

**Please mention your node.js, yarn and operating system version.**
Node.js: v6.7.0
Yarn: v0.15.1
macOS: v10.11.6

**Comment by RustyToms** [comment] 2016-10-12 16:07
duplicate of #665

**Comment by sombriks** [comment] 2016-10-13 01:18
have same issue bower got wiped out.

gladly bower install fixes it all

**Comment by Vishal-Isharani** [comment] 2016-10-14 07:03
also same issue here bower_components and also bower.json got wiped out
have to install bower_components manually using `bower`

**Comment by bbak** [comment] 2016-10-19 12:19
Similar here on Win10 (14393), Node 6.6.0 (x64), yarn 0.16.0: `package.json` is processed, `bower.json` is untouched, but `bower_components` is empty after `yarn install`

**Comment by omnisite** [comment] 2016-10-24 06:51
If you add the following to package.json, bower install will be called and it works. It is a workaround though:

    `"scripts": {
        "postinstall": "bower install"
    }`

**Comment by tigerhawkvok** [comment] 2016-10-25 04:41
at a minimum, not wiping the `bower_components` directory would do. (re-running `bower install`, without a lock file, has the same issues as yarn tries to fix vs npm).

**Comment by kittens** [comment] 2016-10-26 15:56
We've removed support for Bower, see #1441.

**Closed by kittens** 2016-10-26 15:56 UTC
Labels: bug, needs triage
