### ISSUE TITLE
error show when canceled init command

### ISSUE THREAD

**Issue by nayzawoo** [yarnpkg/yarn#769] opened 2016-10-11 23:48 UTC
lsb_release: Ubuntu 16.04.1 LTS

```
yarn init v0.15.0
error canceled
    at Interface.<anonymous> (/usr/share/yarn/node_modules/read/lib/read.js:66:13)
    at emitNone (events.js:67:13)
    at Interface.emit (events.js:166:7)
    at Interface._ttyWrite (readline.js:691:16)
    at ReadStream.onkeypress (readline.js:106:10)
    at emitTwo (events.js:87:13)
    at ReadStream.emit (events.js:172:7)
    at emitKeys (readline.js:1252:14)
    at next (native)
    at ReadStream.onData (readline.js:919:36)
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**Comment by kittens** [comment] 2016-10-12 08:06
Duplicate of #661.

**Closed by kittens** 2016-10-12 08:06 UTC
