### ISSUE TITLE
Regression v1.1.0: NODE_ENV=production yarn install --production=false

### ISSUE THREAD

**Issue by andvgal** [yarnpkg/yarn#4619] opened 2017-10-03 17:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug / regression

**What is the current behavior?**
devDependencies are not installed with --production=false when NODE_ENV=production

**What is the expected behavior?**
--production=false must act as NODE_ENV=development

It used to be this way in v1.0.2, it is documented. It's npm behavior as well.

**Please mention your node.js, yarn and operating system version.**
Node: v8.6.0
Yarn: v1.1.0 installed through npm
OS: Linux

**Comment by BYK** [comment] 2017-10-04 14:49
Duplicate of #4557.

**Closed by BYK** 2017-10-04 14:49 UTC
