### ISSUE TITLE
Yarn doesn't fetch correctly dependencies and crashes

### ISSUE THREAD

**Issue by zenopopovici** [yarnpkg/yarn#1860] opened 2016-11-15 16:59 UTC
**What is the current behavior?**
yarn 

```
yarn install v0.17.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://registry.yarnpkg.com/css/-/css-2.2.1.tgz /Users/Zeno/Library/Caches/Yarn/.tmp/3eae315d49571c56be74b3e400a4b1b8
Directory: /Users/Zeno/Sites/Graffino/Projects/RobertKatai
Output:
Cloning into '/Users/Zeno/Library/Caches/Yarn/.tmp/3eae315d49571c56be74b3e400a4b1b8'...
fatal: unable to access 'https://registry.yarnpkg.com/css/-/css-2.2.1.tgz/': The requested URL returned error: 500
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
When installing a package that requries the css package, it adds a `/` after the extension and this results in a `500` server error.
The previous version `0.16.1` worked fine.

**What is the expected behavior?**
All depandencies should install without errors.

**Please mention your node.js, yarn and operating system version.**
node: 7.1.0
yarn: 0.17.0
OS: MacOS 10.12.1

**Comment by markstos** [comment] 2016-11-15 18:36
I could not immediately reproduce this with `yarn` 0.17.0. Please provide a minimal package.json, yarn.lock or command steps which reproduce the issue.

**Comment by zenopopovici** [comment] 2016-11-15 18:50
Here they are:

yarn.lock: "http://s3.zeno.in/yarn"
package.json: http://s3.zeno.in/package

**Comment by lukebussey** [comment] 2016-11-16 00:52
I'm receiving the same error when trying to add a new package: `$ yarn add grunt-svg-sprite --dev`

[yarn.lock](https://dl.dropboxusercontent.com/u/2158176/yarn.lock)
[package.json](https://dl.dropboxusercontent.com/u/2158176/package.json)

**Comment by markstos** [comment] 2016-11-16 02:43
@lukebussey, I could not reproduce the error using your package.json with Node.js 4.4.1 and yarn 0.17.0. I ran `yarn install` then `yarn add grunt-svg-sprite --dev`. Both were successful. I not try with `yarn.lock` repo. See if you can reproduce the issue in a clean repo with the latest release, now 0.17.2.

**Comment by lukebussey** [comment] 2016-11-16 04:01
It seems to be an issue with the lock file. It fails with it in both 0.17.0 and 0.17.2, but works after removing it.

**Comment by lukebussey** [comment] 2016-11-16 16:08
Running `yarn upgrade` followed by `yarn` works...

**Comment by zenopopovici** [comment] 2016-11-16 16:39
I've removed the `node_modules` folder now I get another error. yarn.log:

```
Arguments: 
  /usr/local/Cellar/node/7.1.0/bin/node /usr/local/bin/yarn

PATH: 
  /Users/Zeno/.rbenv/shims:/Users/Zeno/.rbenv/bin:/Users/Zeno/bin:/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/m-cli

Yarn version: 
  0.17.2

Node version: 
  7.1.0

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "robertkatai",
    "version": "1.0.0",
    "title": "Robert Katai",
    "description": "Robert Katai Website.",
    "homepage": "http://robertkatai.dev",
    "devpage": "http://robertkatai.dev",
    "author": {
      "name": "Graffino",
      "url": "http://graffino.com"
    },
    "repository": {
      "type": "Git",
      "url": "https://github.com/Graffino/RobertKatai.git"
    },
    "keywords": [],
    "contributors": [],
    "bugs": "https://github.com/Graffino/RobertKatai.git",
    "license": "All rights reserved",
    "private": true,
    "engines": {},
    "xo": {
      "space": 4,
      "globals": [
        "$",
        "window",
        "document",
        "localStorage",
        "console",
        "FontFaceObserver",
        "PointerEventsPolyfill",
        "nunjucks",
        "screen"
      ],
      "rules": {
        "no-multiple-empty-lines": [
          "error",
          {
            "max": 2
          }
        ],
        "max-lines": 0,
        "one-var": 0,
        "no-warning-comments": 0,
        "max-params": 0,
        "quote-props": [
          0,
          "consistent-as-needed",
          {
            "keywords": true
          }
        ]
      }
    },
    "dependencies": {},
    "devDependencies": {
      "autoprefixer": "^6.5.3",
      "backstopjs": "^2.3.0",
      "critical": "^0.8.0",
      "csswring": "^5.1.0",
      "debounce": "1.0.0",
      "del": "^2.2.2",
      "es6-promise": "^4.0.5",
      "gulp": "github:gulpjs/gulp#4.0",
      "gulp-bump": "~2.5.0",
      "gulp-combine-mq": "~0.4.0",
      "gulp-concat": "2.6.1",
      "gulp-copy": "~0.0.2",
      "gulp-cssmin": "0.1.7",
      "gulp-data": "^1.2.1",
      "gulp-exec": "^2.1.3",
      "gulp-file": "0.3.0",
      "gulp-filter": "~4.0.0",
      "gulp-git": "^1.12.0",
      "gulp-group-concat": "^1.1.5",
      "gulp-htmlhint": "^0.3.1",
      "gulp-htmlmin": "^3.0.0",
      "gulp-if": "^2.0.2",
      "gulp-imagemin": "~3.1.1",
      "gulp-inject": "^4.1.0",
      "gulp-livereload": "^3.8.1",
      "gulp-load-plugins": "~1.4.0",
      "gulp-modernizr": "~1.0.0-alpha",
      "gulp-notify": "^2.2.0",
      "gulp-nunjucks": "^2.3.0",
      "gulp-nunjucks-render": "^2.0.0",
      "gulp-order": "^1.1.1",
      "gulp-plumber": "^1.1.0",
      "gulp-postcss": "~6.2.0",
      "gulp-rename": "~1.2.2",
      "gulp-replace": "^0.5.4",
      "gulp-rimraf": "^0.2.1",
      "gulp-sequence": "~0.4.6",
      "gulp-sourcemaps": "^2.2.0",
      "gulp-stylint": "~4.0.0",
      "gulp-stylus": "~2.6.0",
      "gulp-svg-sprite": "~1.3.6",
      "gulp-ttf2woff": "^1.1.0",
      "gulp-ttf2woff2": "^2.0.2",
      "gulp-uglify": "^2.0.0",
      "gulp-uncss": "^1.0.6",
      "gulp-util": "^3.0.7",
      "gulp-xo": "^0.14.0",
      "htmlhint-stylish": "^1.0.3",
      "imagemin": "^5.2.2",
      "imagemin-mozjpeg": "~6.0.0",
      "imagemin-pngquant": "~5.0.0",
      "imagemin-svgo": "^5.2.0",
      "jeet": "6.1.5",
      "lodash": "^4.17.1",
      "main-bower-files": "~2.13.1",
      "normalize.styl": "3.0.3",
      "npm-check-updates": "^2.8.6",
      "postcss-quantity-queries": "0.4.0",
      "rupture": "0.6.2",
      "stylint": "^1.5.7",
      "stylint-json-reporter": "^0.3.1",
      "stylint-stylish": "^1.4.0",
      "xo": "^0.17.1"
    },
    "scripts": {
      "gulp": "./node_modules/gulp/bin/gulp.js",
      "gulpwp": "./node_modules/gulp/bin/gulp.js serve --wp",
      "production": "./node_modules/gulp/bin/gulp.js build --env production",
      "productionwp": "./node_modules/gulp/bin/gulp.js build --env production --wp",
      "staging": "./node_modules/gulp/bin/gulp.js build --env staging",
      "stagingwp": "./node_modules/gulp/bin/gulp.js build --env staging --wp",
      "development": "./node_modules/gulp/bin/gulp.js build --env development",
      "developmentwp": "./node_modules/gulp/bin/gulp.js build --env development --wp",
      "debug": "./node_modules/gulp/bin/gulp.js build --env development --debug true",
      "debugwp": "./node_modules/gulp/bin/gulp.js build --env development --debug --wp",
      "clean": "./node_modules/gulp/bin/gulp.js clean",
      "cleanwp": "./node_modules/gulp/bin/gulp.js clean --wp",
      "critical": "./node_modules/gulp/bin/gulp.js critical",
      "bump": "./node_modules/gulp/bin/gulp.js bump",
      "regression-config": "backstop genConfig",
      "regression-reference": "backstop reference",
      "regression-bless": "backstop bless",
      "regression-test": "backstop test",
      "regression-report": "backstop openReport",
      "check-npm-updates": "ncu",
      "check-bower-updates": "ncu -m bower",
      "update-npm-modules": "ncu -u && npm install",
      "update-bower-modules": "ncu -m bower -u && bower install"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: ENOENT: no such file or directory, lstat '/Users/Zeno/Library/Caches/Yarn/npm-gulp-4.0.0-alpha.2-013259583212bf693d991846c62eb36b8a8e5971'
```

**Comment by zenopopovici** [comment] 2016-11-16 16:44
Again `yarn 0.16.1` works fine. So the issue is in the last 2 versions. The 2 issues may also be unrelated.

Also gulp is added via URL `"gulp": "github:gulpjs/gulp#4.0"`. This may trigger the new bug.

**Comment by BugsBunny338** [comment] 2017-03-02 15:16
Still hapenning 👎  Workaround is to `yarn cache clean && yarn install`, but this takes speed advantage over npm away :sad:

**Comment by oskarrough** [comment] 2017-05-24 11:43
Also seeing what I think is a form of this bug https://github.com/pocketjoso/penthouse/issues/162

**Comment by mahanhaz** [comment] 2017-11-14 06:31
for me `npm i -g yarn` fixed my problem

**Comment by olingern** [comment] 2020-01-28 10:22
Closing this. If this is is still an issue on 1.21.1, please comment and I'll reopen.

**Closed by olingern** 2020-01-28 10:22 UTC
