### ISSUE TITLE
gatsby-source-contentful "404 Not Found"

### ISSUE THREAD

**Issue by joaomaranhao** [yarnpkg/yarn#8240] opened 2020-07-16 23:52 UTC
### Bug description
When installing this Gatsby plugin for Contentful CMS it returns a 404 error

**Command**

```sh
yarn add gatsby-source-contentful
```

**What is the current behavior?**
Error: https://registry.yarnpkg.com/commondir/-/commondir-1.0.1.tgzvar(--text)800da0c66127393cca5950ea968a3aaf1253b: Request failed "404 Not Found"

**Environment**

- Node Version: `v12.18.2`
- Yarn v1 Version: `1.22.4` 
- OS and version: linux x64

**Comment by paul-soporan** [comment] 2021-01-03 17:45
Closing as I can't reproduce this.

**Closed by paul-soporan** 2021-01-03 17:45 UTC
