### ISSUE TITLE
Optional dependencies not met

### ISSUE THREAD

**Issue by aderaaij** [yarnpkg/yarn#628] opened 2016-10-11 16:17 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When running `yarn` optional dependencies of packages are not met. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Run a package with `optionalDependencies` declared
**What is the expected behavior?**
Since there  is an explicit `--ignore-optional` flag, I expect optional dependencies to be met. 

**Please mention your node.js, yarn and operating system version.**
node: 4.1.2
yarn: 0.15.1
osx: 10.12

**Comment by Kovensky** [comment] 2016-10-11 16:20
`--ignore-optional` is for not even attempting to install them. By default, they should be attempted to be installed, but not complain on failure.

**Comment by kittens** [comment] 2016-10-11 16:23
Do you have any output that would imply that any of these failed to install or is it silent? If you put together a repro that I can run locally that reproduces this then I should definently be able to fix this!

**Comment by aderaaij** [comment] 2016-10-11 16:30
Woah, that's a fast response! 

The package at hand is [gulp-imagemin](https://github.com/sindresorhus/gulp-imagemin) and it seems to have optional dependencies that are not truly optional. The packages are not installed in the `node_modules` folder and running the task gives an error. Could you give it a try with gulp-imagemin or should I make a quick example?

**Comment by rdmurphy** [comment] 2016-10-11 19:19
I'm hitting the same issue via `gulp-imagemin`. It throws this error when I try to run my gulp project that uses that package:

```sh
Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/path/to/project/node_modules/gulp-imagemin/index.js:8:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/path/to/project/gulp/images.js:5:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

I'm not sure if this is a `gulp-imagemin` issue or `imagemin` itself.

**Comment by thasmo** [comment] 2016-10-11 19:57
Same here. Looks like optional dependencies won't get installed.

node 6.7.0
yarn 0.15.1
windows 10 64-bit

**Comment by deepu105** [comment] 2016-10-12 06:51
same here for `gulp-imagemin`
```
module.js:341                                                                                                 
    throw err;                                                                                                
    ^                                                                                                         
                                                                                                              
Error: Cannot find module 'imagemin-gifsicle'                                                                 
    at Function.Module._resolveFilename (module.js:339:15)                                                    
    at Function.Module._load (module.js:290:25)                                                               
    at Module.require (module.js:367:17)                                                                      
    at require (internal/module.js:16:19)                                                                     
    at Object.<anonymous> (D:\Projects\test\angular2test\node_modules\gulp-imagemin\index.js:8:26)            
    at Module._compile (module.js:413:34)                                                                     
    at Object.Module._extensions..js (module.js:422:10)                                                       
    at Module.load (module.js:357:32)                                                                         
    at Function.Module._load (module.js:314:12)                                                               
    at Module.require (module.js:367:17)                                                                      
```

**Comment by jing2si** [comment] 2016-10-12 07:31
@deepu105 https://github.com/yarnpkg/yarn/pull/789/commits/04d2a3d8317dc645fe476a1331722162fff7ea2c

**Comment by sendilkumarn** [comment] 2016-10-12 07:32
@deepu105 if the PR is accepted. It will close the issue

@jing2si 👍

**Comment by deepu105** [comment] 2016-10-12 07:41
@sendilkumarn thats great 👍

**Comment by deepu105** [comment] 2016-10-12 07:52
please note even running `yarn add gulp-imagemin` explicitly doenst work. There is a warning about `fsevents` failed, which is an optional dependency 
```
PS D:\Projects\test\angular2test> yarn add gulp-imagemin
yarn add v0.15.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
warning lodash@2.4.2: The engine "rhino" appears to be invalid.
warning lodash@1.0.2: The engine "rhino" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency
└─ gulp-imagemin@3.0.3
Done in 400.80s.
PS D:\Projects\test\angular2test> gulp install
module.js:341
    throw err;
    ^

Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\Projects\test\angular2test\node_modules\gulp-imagemin\index.js:8:26)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

Installing the optional dependency directly `yarn add imagemin-gifsicle` produces below error
```
yarn add v0.15.1
warning angular-2-test@0.0.0: "dependencies" has dependency "gulp-imagemin" with range "^3.0.3" that collides with a dependency in "devDependencies" of the same name with version "3.0.3"
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.14: The platform "win32" is incompatible with this module.
info "fsevents@1.0.14" is an optional dependency and failed compatibility check. Excluding it from installation.
warning benchmark@1.0.0: The engine "rhino" appears to be invalid.
warning lodash@2.4.2: The engine "rhino" appears to be invalid.
warning lodash@1.0.2: The engine "rhino" appears to be invalid.
[3/4] Linking dependencies...
error ENOENT: no such file or directory, open 'D:\Projects\test\angular2test\node_modules\@types\angular\index.d.ts'
    at Error (native)
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

But when i run the command `yarn add imagemin-gifsicle` again it installed successfully, so this might be a whole new issue as I encountered the same for `imagemin-jpegtran` and `imagemin-optipng` which are all optional dependency of `gulp-imagemin` I will open a new ticket for this

**Closed** 2016-10-12 11:36 UTC
Labels: bug, compatibility
