### ISSUE TITLE
yarn install shows warnings for peer deps when using workspaces

### ISSUE THREAD

**Issue by rolandjitsu** [yarnpkg/yarn#5362] opened 2018-02-14 09:21 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
When using workspaces and one of the workspaces has a peer dependency, it throws a warning. Though, one of the other workspaces that depends on that package actually has the peer dependency as a dependency, so the warning should probably not be there.
The issue goes away if I add the peer dep. at the root of the workspaces.

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone [cra-workspaces](https://github.com/rolandjitsu/cra-workspaces) and run `yarn install` at root.

**What is the expected behavior?**
There should be no warnings.

**Please mention your node.js, yarn and operating system version.**
Node: *8.9.4*
Yarn: *1.3.2*
OS: macOS Sierra

**Comment by andypillip** [comment] 2019-11-22 19:12
Node: v10.16.3
Yarn: 1.19.1
OS: Windows 10

**Comment by paul-soporan** [comment] 2021-01-03 13:26
All peer warning issues have been fixed in v2.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-03 13:26 UTC
Labels: triaged

**Comment by paul-soporan** [comment] 2021-01-03 13:32
Actually, looking more carefully at this it's working as intended. Even though `react` is provided by the package that depends on `package-a` and `package-b`, it also has to be provided as a dev-dev to those workspaces to satisfy the peer requirement when there's no ancestor (such as in the case of running a script directly in that workspace).

> The issue goes away if I add the peer dep. at the root of the workspaces.

It works because peerDependencies are also inherited based on filesystem hierarchy.

**Comment by rolandjitsu** [comment] 2021-01-04 03:22
> Actually, looking more carefully at this it's working as intended. Even though `react` is provided by the package that depends on `package-a` and `package-b`, it also has to be provided as a dev-dev to those workspaces to satisfy the peer requirement when there's no ancestor (such as in the case of running a script directly in that workspace).
> 
> > The issue goes away if I add the peer dep. at the root of the workspaces.
> 
> It works because peerDependencies are also inherited based on filesystem hierarchy.

So what you're saying is the peer dep needs to be a dev dep as well? For each child package?

**Comment by paul-soporan** [comment] 2021-01-04 12:04
Yes - for each workspace, each listed peer dependency should also be listed as a dev dependency.

**Comment by paul-soporan** [comment] 2021-01-04 12:08
But, another solution, just like you discovered, is to list the peers at the root and let Yarn inherit them based on filesystem hierarchy. While less correct from a theoretical point of view (and also unsupported in [PnP](https://yarnpkg.com/features/pnp) if you ever want to migrate to it), it is and will continue being supported by v1 and v2 with the `node-modules` linker.

**Comment by rolandjitsu** [comment] 2021-01-05 02:00
> Yes - for each workspace, each listed peer dependency should also be listed as a dev dependency.

Got it. Thanks.
