### ISSUE TITLE
bug: "yarn run" command quoting is broken on windows

### ISSUE THREAD

**Issue by Spongman** [yarnpkg/yarn#3940] opened 2017-07-16 06:37 UTC
````
> ver
Microsoft Windows [Version 10.0.15063]
> node --version
v8.1.2
> yarn init -y
> yarn add gulp
> yarn run gulp
yarn run v0.27.5
$ "C:\temp\q\node_modules\.bin\gulp"
[23:33:40] No gulpfile found
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> yarn run gulp watch
yarn run v0.27.5
$ "C:\temp\q\node_modules\.bin\gulp" "watch"
'C:\temp\q\node_modules\.bin\gulp" "watch' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>yarn run gulp -- watch
yarn run v0.27.5
$ "C:\temp\q\node_modules\.bin\gulp" "watch"
'C:\temp\q\node_modules\.bin\gulp" "watch' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

the 1st error is expected -- gulp can't find its file.
the 2nd & 3rd are a failure to execute gulp.

**Comment by Volune** [comment] 2017-07-16 12:19
Looks like duplicate of #3773

**Comment by arcanis** [comment] 2017-07-17 16:57
Closing in favor of #3773

**Closed by arcanis** 2017-07-17 16:57 UTC
