### ISSUE TITLE
yarn self-update should update using the same installation method originally used

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1139] opened 2016-10-17 04:19 UTC
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
`yarn self-update` always downloads a tarball.

**What is the expected behavior?**
`yarn self-update` should update using the same installation method used by the user. For example, if Yarn was installed via the Debian/Ubuntu package, `yarn self-update` should run `sudo apt-get update && sudo apt-get install yarn`. On Windows when installed via the installer, it should download `https://yarnpkg.com/latest.msi` and execute it.

This is closely related to #1138 ("add yarn version check on startup") in that both issues need some way of  determining the installation method used by the user.

**Comment by busches** [comment] 2016-12-06 15:04
Do you want to close this since `self-update` was removed with https://github.com/yarnpkg/yarn/pull/1429?

**Comment by Daniel15** [comment] 2016-12-06 21:18
No, the plan is to reinstate a version of self-update that uses the right
installation method.

Sent from my phone.

On Dec 7, 2016 2:04 AM, "Scott Busche" <notifications@github.com> wrote:

Do you want to close this since self-update was removed with #1429
<https://github.com/yarnpkg/yarn/pull/1429>?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/1139#issuecomment-265172525>, or mute
the thread

**Comment by jakearchibald** [comment] 2016-12-20 12:15
https://yarnpkg.com/en/docs/cli/self-update should probably be removed/updated

**Comment by meta-meta** [comment] 2016-12-21 18:26
If I'm on 0.18.1, how do I update to the next version?

**Comment by Daniel15** [comment] 2016-12-21 23:12
@meta-meta Currently, you need to manually upgrade.

**Comment by octopitus** [comment] 2017-01-17 10:50
how about `yarn global add yarn`?

**Comment by dancoates** [comment] 2017-01-18 01:48
I'm a big fan of Yarn but am a little concerned at how self-update was removed with no deprecation notice, no [mention in the release notes](https://github.com/yarnpkg/yarn/releases), and that it was bundled in with a [PR](https://github.com/yarnpkg/yarn/pull/1429) that is largely unrelated and where there was no discussion about removing self-update.

I understand that it is early days for Yarn and that API changes are to be expected but it would be good if there was a process for removing core functionality. 

(sorry if this isn't the right place to discuss, but this PR is where the [docs](https://yarnpkg.com/en/docs/cli/self-update) link to)

**Comment by Daniel15** [comment] 2017-01-18 01:51
> how about yarn global add yarn?

Installing Yarn via Yarn is not a supported use case at the moment, and can cause several issues. We don't recommend it at the moment.

@dancoates  - The self-update command never really worked 100% correctly, that PR just removed the remnants of the existing command while adding some framework stuff for the new self-update (which will come in the future, as per this issue)

**Comment by CatinhoCR** [comment] 2017-01-26 17:11
How can I manually update yarn? Not sure about that one, I used brew on my mac to get it working but not sure what "manual" means here... any tips appreciated.

**Comment by Daniel15** [comment] 2017-01-26 17:35
Upgrade it the same way you upgrade any other app installed using Homebrew.
I assume it has an "upgrade" command.

Sent from my phone.

On Jan 26, 2017 9:11 AM, "Cato" <notifications@github.com> wrote:

How can I manually update yarn? Not sure about that one, I used brew on my
mac to get it working but not sure what "manual" means here... any tips
appreciated.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/yarn/issues/1139#issuecomment-275447861>, or mute
the thread

**Comment by andreafalzetti** [comment] 2017-01-27 00:53
@CatinhoCR I initially installed yarn using npm, so I did `npm uninstall -g yarn` and then `brew install yarn` - And now I've got the latest version. It would also work using the brew upgrade command as @Daniel15 mentioned.

**Comment by slootzky** [comment] 2017-01-30 20:27
`npm update yarn -g`

**Comment by BeHappyF** [comment] 2017-02-09 02:36
You might install yarn width homebrew.So `brew uninstall yarn`.And it's not a good choose to install yarn with homebrew when you need to across the wall.Everytime you need to brew update.It's always time out.....

**Comment by wardbell** [comment] 2017-03-02 18:06
Sadly, `npm update yarn -g` does not always do the trick. For example, it did not update from v.0.20.3 to v.0.21.3 on my OS/X machine. But the following did work:
```
npm uninstall yarn -g
npm install yarn -g
```

**Comment by Daniel15** [comment] 2017-03-02 20:00
npm sometimes has weird issues which is why we don't recommend using it to install Yarn.

**Comment by jeff-kilbride** [comment] 2017-03-03 06:16
@wardbell  Simply running install works, too:
```
npm install yarn -g
```
No need to uninstall first.

**Comment by kristojorg** [comment] 2017-03-10 16:10
I have tried updating manually through homebrew, but when I type `yarn --version` it is still showing 19.0. I am now trying to uninstall, but seemingly also cannot do that... `yarn --version` still shows 19.0 after a `brew uninstall yarn`.  I also tried `npm uninstall yarn` with no luck either.

Can you tell me what I need to delete in order to have yarn completely uninstalled so I can reinstall with the newer version?

**Comment by adrianmcli** [comment] 2017-03-12 10:15
@kristojorg I had the same problem. I (think I) fixed it by doing a bunch of things:

1. Removing yarn binaries manually:
```
rm -f /usr/local/bin/yarnpkg
rm -f /usr/local/bin/yarn
```
2. Remove yarn cache:
```
rm -rf /Users/adrianmcli/.yarn
```
3. If you have the following in your `.zshrc` or `.bash_profile`, remove it: 
```
export PATH="$PATH:`yarn global bin`"
```
4. Install via `curl`:
```
curl -o- -L https://yarnpkg.com/install.sh | bash
```
5. Make sure there is the following line in your `.zshrc` or `.bash_profile`:
```
export PATH="$HOME/.yarn/bin:$PATH"
```

Now if you try to run `yarn -v`, you should get the latest stable version.

**Comment by kristojorg** [comment] 2017-03-12 22:26
Thank you!

**Comment by NameFILIP** [comment] 2017-03-13 23:34
@kristojorg Can you also change 2. to have `${HOME}` instead of `/Users/adrianmcli`

**Comment by obkalu** [comment] 2017-04-11 02:58
*Just adding this for the benefit of those on Microsoft Windows.
If you originally installed Yarn using Chocolatey (the package manager for Windows), then to update it to the latest release, simply do the following:
1. Launch open the Windows command shell (cmd.exe) as an administrator.
2. Run the command: c:\>**choco upgrade yarn**
3. Run, c:\>yarn --version, and confirm that it's been upgraded to the latest version. Voila!

**Comment by aitchkhan** [comment] 2017-06-01 08:02
On Ubuntu 16.04, yarn automatically updates via Software & Updates.

**Comment by M-D-M** [comment] 2017-06-16 14:36
I had a similar problem, and the problem wasn't that npm wasn't updating yarn (it was), but that there were apparently two links in my environment: 

One for /usr/bin/yarn that was pointing to /usr/lib/node_modules/yarn/bin/yarn.js (this was the most recent version installed by npm)

And one for /usr/local/bin/yarn that was pointing to /usr/local/lib/node_modules/yarn/bin/yarn.js (this was an old version)

I don't know where the /usr/local/bin/yarn link was coming from, but it was the one being used by my shell when I just typed "yarn".  I removed the link and now all is good.

**Comment by skube** [comment] 2017-06-22 15:46
@M-D-M How did you remove the `/usr/local/bin/yarn` link if you didn't know where it was coming from?

**Comment by M-D-M** [comment] 2017-06-22 19:14
```sudo unlink /usr/local/bin/yarn```

**Comment by skube** [comment] 2017-06-24 13:56
@M-D-M Thanks. So I did `unlink /usr/local/bin/yarn` which seemed to work.
and then in order to update to the latest, ran `npm i -g yarn` which seemed to just link up again
```
❯ npm i -g yarn
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
```
And yet I'm still not updated to the latest 0.24.6
```
❯ yarn -v
yarn install v0.24.5
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.51s.
```

**Comment by M-D-M** [comment] 2017-06-24 18:44
Interestingly enough, when I do ```sudo npm install --global yarn```, the /usr/local/bin links aren't being created, so there's some difference in our environments I can't account for.  As for 0.24.5 being the available version, that seems maybe be an npm problem -- 0.24.6 isn't being installed, for some reason.

**Comment by jeff-kilbride** [comment] 2017-06-24 18:51
I can confirm that 0.24.6 is not being installed. I have 0.24.5 and when I run `npm outdated -g`, npm doesn't recognize there's an update available. I don't know if this is an npm issue or an issue with the yarn package. 

I am using nvm to manage my node installations, so I don't really have a choice. I need to use npm to install yarn.

**Comment by skube** [comment] 2017-06-26 21:49
Interestingly, on another machine I was able to...
```
warning Your current version of Yarn is out of date. The latest version is "0.24.6" while you're on "0.21.3".
info To upgrade, run the following command:
$ curl -o- -L https://yarnpkg.com/install.sh | bash
```
So I did
```
❯ curl -o- -L https://yarnpkg.com/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6746    0  6746    0     0  22490      0 --:--:-- --:--:-- --:--:-- 22561
Installing Yarn!
/usr/local/bin/yarn
> Downloading tarball...

> We've added the following to your .zshrc
> If this isn't the profile of your current shell then please add the following to your correct profile:

export PATH="$HOME/.yarn/bin:$PATH"

> Successfully installed Yarn 0.24.6! Please open another terminal where the `yarn` command will now be available.
```

**Comment by nextlevelshit** [comment] 2017-06-29 08:55
@octopitus In my case I had to add permissions with `sudo yarn add global yarn`.

**Comment by localredhead** [comment] 2017-07-02 03:13
`brew upgrade yarn` and `brew link --overwrite node` worked for me.

**Comment by pencilcheck** [comment] 2017-07-07 04:16
You mean `brew link --overwrite yarn` for the second command right?

**Comment by rrotteveel** [comment] 2017-09-08 11:12
I believe @localredhead has installed yarn with node. I installed yarn as follows:
`brew install yarn --without-node`, because I manage node by using `nvm`.

Probably he is overwriting the link to node, so that he's using the right version instead of the one coming with/from yarn.

**Comment by mikechamberlain** [comment] 2017-09-12 11:43
It might seem obvious, but on Windows mine was installed from the MSI in `Program Files (x86)`. No matter what upgrade method `yarn version` wouldn't budge. I eventually discovered the cause with `which yarn` which pointed to the offending location. This meant that I had to use "Change or Remove a program" first to remove it, then simple `npm install -g yarn` to reinstall the latest version. Now I can just use npm to control the version which is much better.

**Comment by maplion** [comment] 2017-09-19 21:20
@mikechamberlain This worked for me, thanks!

**Comment by BYK** [comment] 2017-10-27 10:45
Latest state: we need to reimplement the `self-update` command that uses the original installation method.

**Comment by onurtemizkan** [comment] 2017-10-28 10:43
Working on the reimplementation.

**Comment by Daniel15** [comment] 2017-10-28 18:50
@onurtemizkan It should be relatively straightforward. We already have information on the command that needs to be ran (as Yarn prints out a notice with the command), Yarn just needs to actually run it. A slightly different case is on Windows when the installer was used, as we'd have to download the installer then msiexec it.

**Comment by smotaal** [comment] 2018-03-06 18:30
Sorry to interrupt 😉 

Have you considered simply delegating this to npm (assuming of course yarn runs if npm exists in the first place).

```
» npm update -g yarn
```

The nice thing is that if it does not work out you can always:

```
So we tried to get npm to handle the update...

Here are your options:
…

Now, aren't u glad to be using yarn for your other packages!
```

**Comment by Daniel15** [comment] 2018-03-06 18:32
@smotaal There's a few issues with that:

 - If you installed Yarn via another method, you'll now have two versions of Yarn installed (one via the system package manager, and one via npm)
 - Not everyone has npm installed. Yarn does not require npm installed to run

**Comment by Resen4983** [comment] 2018-03-07 06:02
if your system is Windows and had installed npm ,you can use `npm install yarn@latest -g` to update to top version.

**Comment by smotaal** [comment] 2018-03-07 11:33
I can't remember how I set it up on this mac roughly a year ago, I know I was using something other than NPM at one point, but when I lost my thread I simply NPMed and I have no issues other than yarn complaining when I'm fairly behind which reminds me to update and I simply `npm update -g yarn` and forget about it till next reminder.

From a user's perspective, I think yarn can recommend "supported" and "unofficial" where if "unofficial" and it does not "work as intended" please use "supported" to install and here is "recommended" if you need to undo "unofficial"

Honestly, it is important for a package manager to have a clear path for itself to be well-managed.

**Comment by Stanzilla** [comment] 2018-03-12 11:01
@onurtemizkan are you still working on this?

**Comment by WhoAteDaCake** [comment] 2018-04-18 16:02
Are there any updates?

**Comment by GabrielDuarteM** [comment] 2018-04-19 20:10
For those just wanting to update yarn automatically on windows, without having to download the binary, I've been using [`choco`](https://chocolatey.org/) for a while to do that, and it is doing this job flawlessly. It's a cmd line tool to install programs (just like `apt-get`). You just run `choco install yarn`, and yarn is installed. To update, the command is `choco upgrade yarn`.

**Comment by Stanzilla** [comment] 2018-04-19 20:24
No sorry, chocolatey is just horrible.

**Comment by Daniel15** [comment] 2018-04-19 20:33
If you don't like Chocolatey, don't use it.

I think it's pretty good though. At work we have a lot of internal
Chocolatey packages for various software packages. Seems to work well.

In any case, this issue is specifically for reimplementing self update in
Yarn. It'll only use Chocolatey if that's what you originally used! If you
used the installer directly, upgrades would also use the installer
directly. So it won't force you to use Chocolatey.

**Comment by begin-again** [comment] 2018-05-08 17:43
[Scoop](http://scoop.sh/) is an alternative to choclatey and works a lot like brew.

**Comment by pikeas** [comment] 2018-10-30 23:21
This is a pretty poor experience for new users:

1) Pull a recent official Node Docker image, which includes Yarn 1.10.1.
2) `yarn import`
3) `yarn install` says the version of yarn is out-of-date and recommends a `curl | bash` command, which is generally considered a bad idea by sysadmins and devops teams.
4) Find and run `yarn self-update` at https://yarnpkg.com/en/docs/cli/self-update, which links to this Github issue.
5) Forget which problem with npm made me try yarn in the first place.

**Comment by adrianmcli** [comment] 2018-10-31 00:52
It's kinda crazy how this still isn't fixed. After more than a year, I think my solution ([here](https://github.com/yarnpkg/yarn/issues/1139#issuecomment-285935082)) is still the cleanest there is (even though it's tedious and annoying).

**Comment by tchalvak** [comment] 2018-10-31 11:33
We should collaborate to get a command in place for this!  The hard work of the installer is already done, it's a matter of packaging up the replace and run into a yarn command.

**Comment by Alecto** [comment] 2018-11-01 16:04
still not working?

**Comment by adrianmcli** [comment] 2018-11-23 07:09
I'll summarize my solution [above](https://github.com/yarnpkg/yarn/issues/1139#issuecomment-285935082) again here:

1. Remove Yarn manually

   ```bash
   # remove binaries
   rm -f /usr/local/bin/yarnpkg
   rm -f /usr/local/bin/yarn

   # remove cache
   rm -rf ${HOME}/.yarn
   ```

   If you have the following in your .zshrc or .bash_profile, remove it:

   ```bash
   export PATH="$PATH:`yarn global bin`"
   ```

2. Install latest Yarn (via curl)

   ```bash
   curl -o- -L https://yarnpkg.com/install.sh | bash
   ```

   Make sure there is the following line in your .zshrc or .bash_profile:

   ```
   export PATH="$HOME/.yarn/bin:$PATH"
   ```

Finally, run `yarn -v` to check your new version number.

**Comment by Daniel15** [comment] 2018-11-23 07:13
If anyone wants to work on this... We actually already have code that determines the command that needs to be ran to upgrade Yarn:
https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/install.js#L86-L129

You'd just need to add a "self-upgrade" command that runs the correct command.

**Comment by rafael-vitor** [comment] 2018-11-29 05:01
@Daniel15 I've submitted a pull request for this, looking forward for some feedback. Thanks.

**Comment by jose920405** [comment] 2018-12-07 13:55
This works for me:

`brew upgrade yarn `
`npm update yarn -g`

**Comment by crmpicco** [comment] 2019-01-17 02:52
Any news on this? `npm update yarn -g` works in the meantime I suppose.

**Comment by Daniel15** [comment] 2019-01-17 08:19
> Any news on this?

@crmpicco  For now, you still need to update manually.

**Comment by ilias-t** [comment] 2019-02-06 20:09
https://yarnpkg.com/en/docs/install

**Comment by olingern** [comment] 2019-02-07 05:32
@ilias-t this is not about updating, but rather using the same installation method.

**Comment by MiroslavPetrik** [comment] 2019-02-07 13:53
This issue is over 2yrs old, seems like you don't care. Just remove the command, it's not working & misleading.

**Comment by arcanis** [comment] 2019-02-07 13:59
This command doesn't exist so it'll be hard to remove 🙂 

As far as I'm concerned, I believe the original intent of this issue is fixed with [`yarn policies set-version`](https://yarnpkg.com/lang/en/docs/cli/policies/#toc-policies-set-version). In case it doesn't work as expected, please feel free to open a new issue.

**Closed by arcanis** 2019-02-07 13:59 UTC
Labels: cat-feature, good first issue, help wanted, high-priority, triaged
