### ISSUE TITLE
yarn global silently installs binaries for dependencies

### ISSUE THREAD

**Issue by akalin** [yarnpkg/yarn#4198] opened 2017-08-17 21:02 UTC
**What is the current behavior?**

On macOS with yarn installed via homebrew, `yarn global add pkg` installs binaries not only for the given package, but its dependencies (silently).

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$ which which
/usr/bin/which

$ yarn global add create-react-app
yarn global v0.27.5
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "create-react-app@1.4.0" with binaries:
      - create-react-app
warning No license field
Done in 1.41s.

$ which which
/usr/local/bin/which
```

**What is the expected behavior?**
It shouldn't symlink binaries for dependencies, or at least mention that it's symlinking those binaries.

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v8.4.0

$ yarn --version
0.27.5

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.6 (16G29)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Root
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

**Comment by BYK** [comment] 2017-08-18 10:12
Duplicate of #3824.

**Closed by BYK** 2017-08-18 10:12 UTC
