### ISSUE TITLE
Yarn upgrade does not properly update `package.json` for dev dependencies

### ISSUE THREAD

**Issue by SaladFork** [yarnpkg/yarn#1458] opened 2016-10-25 21:51 UTC
**Do you want to request a _feature_ or report a _bug_?**

_bug_

**What is the current behavior?**

Running `yarn upgrade` to upgrade a dev dependency, even with the `--dev` flag, will add the upgraded version of the dependency to the `dependencies` hash in `package.json` rather than `devDependencies`.

This might also be an issue with other dependency types (like peer), but I have not tested.

**If the current behavior is a bug, please provide the steps to reproduce.**

``` bash
$ mkdir foo && cd foo
$ yarn init
<snip>
$ yarn add lodash@3 --dev
<snip>

$ grep lodash package.json -C 1
  "devDependencies": {
    "lodash": "3"
  }

$ yarn outdated
yarn outdated v0.16.1
Package Current Wanted Latest
lodash  3.10.1  3.10.1 4.16.4

$ yarn upgrade lodash --dev
<snip>
success Saved 1 new dependency
└─ lodash@4.16.4

$ grep lodash package.json -C 1
  "devDependencies": {
    "lodash": "3"
  },
--
--
  "dependencies": {
    "lodash": "^4.16.4"
  }
```

**What is the expected behavior?**

`yarn upgrade` should update the version string of the entry in the `devDependencies` hash.

It would be nice if this could be done without `--dev` using the current location of the dependency (upgrading a dev dep would modify `devDependencies`, upgrading a normal dep would modify `dependencies`).

**Please mention your node.js, yarn and operating system version.**

``` bash
$ node --version
v6.9.1
$ yarn --version
0.16.1
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

**Comment by Vheissu** [comment] 2016-10-26 10:46
I can confirm that I am seeing this happen on the exact same version of Yarn. Instead of updating the existing development dependency, it adds a new entry to "dependencies" and leaves the existing development dependency there.

**Comment by peschee** [comment] 2016-10-26 13:28
Confirmed bug here as well.

**Comment by skellock** [comment] 2016-10-26 14:37
Same here.  `standard` keeps getting inserted into `dependencies` even though it lives in `devDependencies`.

I've tried both `yarn upgrade standard` and `yarn upgrade standard -D`.  Same thing.

Lovely program though!  Thank you for building it!

**Comment by VladShcherbin** [comment] 2016-10-29 13:53
Here is the same issue, a bit before - #1262

**Comment by hannupekka** [comment] 2016-10-30 11:02
Same here.

**Comment by jabbrwcky** [comment] 2016-11-02 08:52
Same here. Every module updated via `yarn update` gets added to `dependencies`.
`--dev` or other options are not documented for`yarn update` and apparently ignored.

IMO update should either accept the same opts as `install` - or even better update the dependency in the category it is found in in package.json 

```
node --version
v6.9.0
yarn --version
0.16.1
```

**Comment by kittens** [comment] 2016-11-03 11:26
#1620 fixes this so I'm going to close this and move discussion there.

**Closed by kittens** 2016-11-03 11:26 UTC
Labels: bug

**Comment by kube** [comment] 2016-11-14 16:59
Still not fixed, I'm using latest Yarn installed via Homebrew.

**Comment by wyze** [comment] 2016-11-14 19:05
@kube Could you please add more details if it is still an issue? Versions for OS, Node, Yarn? A `package.json` that can be used to reproduce?

**Comment by kube** [comment] 2016-11-14 20:28
```
λ yarn --version
0.16.1
```

I'm on macOS 10.12.1, installed Yarn with Homebrew.

And here is the [`package.json`](https://github.com/black-monolith/LightCycle/blob/228a8e150ba55b06755e9bb3372e597942ea9062/package.json 
) on which I tried :

`ts-loader` and `webpack-merge` are outdated, upgrading them with yarn added them to dependencies, leaving devDependencies outdated.

**Comment by wyze** [comment] 2016-11-14 20:30
@kube Please try on `0.17.0` that was just released today, this fix was included in that release, but not in `0.16.1`.

**Comment by kube** [comment] 2016-11-14 20:31
Sure, but Homebrew still has 0.16.1
```
λ brew upgrade yarn
Error: yarn 0.16.1 already installed
```

Tried installing with NPM and just had the latest version, but seems strange to install Yarn with NPM.

**Comment by kube** [comment] 2016-11-14 20:40
Ok everything works fine when using 0.17.0, but maybe you should update Brew version.
Which is the preferred package manager or way to install Yarn ?

**Comment by wyze** [comment] 2016-11-14 20:45
Brew is the preferred method of installation for OSX. It is still a manual process for getting it updated on Homebrew, so someone will have to request it being updated like they did here: https://github.com/Homebrew/homebrew-core/pull/6060

**Comment by milesj** [comment] 2016-11-17 06:08
When I run `yarn upgrade`, it doesn't update any versions in `package.json`. This is quite annoying coming from NPM, in which it would automatically update the numbers.

**Comment by wyze** [comment] 2016-11-17 14:41
@milesj, this should probably be a separate issue and please provide steps to reproduce along with a `package.json` that we could use to reproduce.

**Comment by milesj** [comment] 2016-11-17 21:18
I'll create a new issue.

**Comment by jayands** [comment] 2016-11-20 08:06
On Debian Stable, yarn 0.17.4, this issue seems to be fixed at least. It upgraded `lodash@3` to `lodash@4` properly, so it could just be a matter of going to the latest version.

**Comment by ibbatta** [comment] 2016-12-13 11:36
I'm trying to upgrade grunt-sass from `1.1.0` to `2.0.0` (in my __dev-dependencies__)
I execute `yarn upgrade grunt-sass@2.0.0` but add grunt-sass in my __dependencies__ and not upgrade the one in __dev-dependencies__

**Comment by wagenet** [comment] 2016-12-20 22:52
Using yarn v0.18.1 I'm still unable to force an upgrade of a sub-dependency. `yarn upgrade` only adds a new entry to the package.json and doesn't update the sub-dependency.

**Comment by wrcx** [comment] 2017-01-17 07:44
Issue still exists in 0.19.1,  yarn upgrade did not update package.json.

**Comment by wagenet** [comment] 2017-01-18 00:56
@kittens this is not fixed by #1620

**Comment by alexdevero** [comment] 2017-01-20 08:31
I can confirm this issue in 0.19.1 as well.

**Comment by jkoontz2010** [comment] 2017-01-26 18:41
everyone--using `yarn add <package-name>` will update your desired package for now.

`yarn upgrade` isn't working for me either

**Comment by halfcrazy** [comment] 2017-02-13 02:45
yarn upgrade currently  only update yarn.lock, not update package.json.

**Comment by jgliner** [comment] 2017-02-22 01:23
Can confirm issue in v0.20.3

**Comment by alaadahmed** [comment] 2017-02-25 06:24
I have the same issue, when use yarn upgrade, it upgrade all packages, but doesn't reflect in package.json file. v0.20.3 .. really annoying. I noticed also when use "yarn install", it install latest versions of all list packages in package.json and doesn't stick with versions mentioned in it, so it is like yarn upgraded them to latest version and also doesn't reflect that in package.json but it shows in yarn.lock current versions that installed

**Comment by gaui** [comment] 2017-02-25 14:45
@kittens v0.20.3 @ Windows and still doesn't update package.json - only yarn.lock file. You should reopen this.

**Comment by Babazon** [comment] 2017-02-27 01:11
I'm dropping yarn and switching back to npm because of this bug. No matter how I try to upgrade my packages, yarn will fetch the newest ones into the cache, and keep the old versions in my package.json and in the node_modules folder. What's the point?..

**Comment by alexdevero** [comment] 2017-02-28 08:04
Yes! I can confirm that Yarn v0.21.3 finally updates package.json, at least ```yarn upgrade-interactive``` command.

**Comment by Sharlaan** [comment] 2017-02-28 19:06
@alexdevero i just tried `yarn upgrade` on 3 projects of mine: it didnot update any package.json ....

but i confirm  `yarn upgrade-interactive` works

**Comment by diegovilar** [comment] 2017-03-06 14:30
As of today, on version 0.21.3, `yarn upgrade` still behaves wrongly.

I'm using `yarn add package@version --dev` instead, and it upgrades the package as desired and updates package.json correctly.

**Comment by quanglam2807** [comment] 2017-03-11 17:40
Same for me. Somebody needs to re-open this issue.

**Comment by skellock** [comment] 2017-03-11 17:47
Fwiw, i've been using `upgrade-interactive` which for some reason seems to yield better luck.

🍒 🍒 🍒

**Comment by alexdevero** [comment] 2017-03-12 07:37
It would be good to know, what is the expected behavior of yarn in this case. Can any of the yarn developers say if yarn should update package.json or not?

**Comment by EricLambrecht** [comment] 2017-03-13 21:50
I just did a `yarn upgrade babel-cli` which was in my `devDependencies` and it was added as a production dependency (to `dependencies`)... something is still completely broken. Oh, and I use yarn v**0.22.0** btw!

**Comment by skellock** [comment] 2017-03-13 23:48
Just realized this:
![image](https://cloud.githubusercontent.com/assets/68273/23879793/c81123e2-0825-11e7-9ea4-969ced4ee02c.png)

I'm not an apologist or anything, I think this should be reopened... but holy balls. 720 issues is enough to drown a cruise ship full of yarn developers.

**Comment by bstaruk** [comment] 2017-03-16 12:54
+1 issue is still present in Yarn v0.21.3 on Windows.

**Comment by benface** [comment] 2017-03-28 17:24
This is not fixed. I am getting it on macOS Sierra 10.12.4. I have some `devDependencies` which are private git repos and one standard `dependency` (`"jquery": "^3.1.1"`). The latest version of jQuery is 3.2.1, and `yarn upgrade` sees that (`├─ jquery@3.2.1`) but it doesn't update `package.json`.

```
yarn --version
0.21.3
node --version
v7.7.4
```

**Comment by gaui** [comment] 2017-03-29 00:13
Reopen.

**Comment by virgofx** [comment] 2017-04-01 14:59
Windows - v0.21.3 fails with `yarn upgrade` ... when specifying a package after it will update both package.json and lock file.

**Comment by LaughingBubba** [comment] 2017-04-14 09:45
Windows - v0.22 - <yarn upgrade> still doesn't update package.json but does update the lock file. 
<yarn upgrade-interactive> worked of sorts but didn't identify all the packages that should have updated and thus broke various peer dependencies.

Thankfully I've only used it on one project and was able to revert the mess. I love the idea behind Yarn but I won't be bothering with it until this is sorted.

**Comment by ZitRos** [comment] 2017-04-14 09:47
Windows, Yarn v0.22 - doesn't update `package.json` when using `yarn upgrade` as @LaughingBubba mentioned. The `node_modules` folder is updated, but `package.json` is not, which creates a mess in package versions.

**Comment by wagenet** [comment] 2017-04-18 21:00
@kittens it doesn't appear that this has been fixed.

**Comment by shakefu** [comment] 2017-04-21 19:17
I just saw this again in 0.23.2. 

In my case it seems that if at least 1 of the dependencies upgraded in a list is NOT a devDep, then it puts all the upgrades into dependencies in package.json.

**Comment by fab1an** [comment] 2017-04-26 12:30
This is definitely not fixed. Lost an hour now on this.

**Comment by diegovilar** [comment] 2017-04-26 18:10
@fab1an, for the moment use `yarn add package-name@latest [--dev]` to update a package. It behaves as `upgrade` is expected to, updating package.json correctly.

**Comment by fab1an** [comment] 2017-04-26 22:29
@diegovilar Thanks for the tipp, but that's too cumbersome for 25+ dev-dependencies. I just went back to using `npm-check -u` for upgrading them.

**Comment by virgofx** [comment] 2017-04-27 03:08
Still broken in Windows x64 , Yarn 0.23.2

**Comment by milesj** [comment] 2017-04-27 03:21
For everyone commenting here, I suggest using `yarn upgrade-interactive` in the mean time. Has been working rather well here.

**Comment by mtpultz** [comment] 2017-04-27 05:10
Still broken and if you use `yarn upgrade-iteractive` and don't know what version of tslint, codelyzer, typescript, etc that packages depend on like Angular or the Angular CLI you can and will cause a bunch of errors that will haunt you even after you roll it all back.  Has this issue been re-posted?

**Comment by fab1an** [comment] 2017-04-27 06:37
@milesj NO. I'm here and I've been using ONLY `upgrade-interactive` with the exact same problems.

**Comment by mtpultz** [comment] 2017-04-27 07:25
Wasn't sure if this was getting any face time since it has been closed for months so created a new issue - #3266

**Comment by milesj** [comment] 2017-04-27 17:04
@fab1an That's unfortunate. I've had no issues with it updating package.json :/

**Comment by valnub** [comment] 2017-05-06 22:36
Bug still not fixed.

This is unusable. 781 open tickets are nuts.

**Comment by iamfreee** [comment] 2017-05-20 17:42
Windows 10, yarn v0.23.4 still does not update the package.json when doing `yarn upgrade`

**Comment by leosco** [comment] 2017-05-24 16:15
@iamfreee I'm running Yarn v0.24.5 and running `yarn upgrade` doesn't update package.json, only yarn.lock. This can't (or at least shouldn't) be intentional, because first of all, the versioning in package.json is to set the actual version of the package first, and then dictate upgrade constraints, i.e. `^` or `~`. Second of all, running `yarn upgrade` on an individual package changes the package.json so why is the behavior when upgrading all packages different? Why should there be a discrepancy in the behavior between running `yarn upgrade` and `yarn upgrade-interactive` it makes no sense?

**Comment by iamfreee** [comment] 2017-05-24 16:52
@leosco In my case `npm update` didn't update the `package.json` too and also `yarn upgrade [package]` didn't did the trick. That's why i think the issue is related to version constraint `^`, or is the expected behavior.

**Comment by leosco** [comment] 2017-05-24 16:55
@iamfreee Nope, you've gotta do `npm update --save` which is supposed to be Yarn's default behavior.

**Comment by valnub** [comment] 2017-05-24 16:55
`yarn upgrade-interactive` does the trick for me https://yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

**Comment by leosco** [comment] 2017-05-24 16:58
I posted a new issue detailing all this, see here https://github.com/yarnpkg/yarn/issues/3492 and perhaps continue the discussion there.

**Comment by paxperscientiam** [comment] 2017-07-09 19:42
I would also like to echo that I've had success with `yarn interactive-upgrade` whereas `yarn upgrade --latest` has not worked for me.
Using yarn v0.24.6 with node v7.10.0.

**Comment by joseluisq** [comment] 2017-09-11 14:06
`yarn upgrade --latest` works fine  :+1:

```sh
~> yarn -v
1.0.0
~> yarn upgrade --help | grep "\-\-latest" | head -n 1

  --latest       list the latest version of packages, ignoring version ranges in package.json
```

**Comment by milesj** [comment] 2017-09-11 18:43
`yarn interactive-upgrade` seems to be having issues now in v1.

**Comment by kaylieEB** [comment] 2017-09-11 18:47
@milesj Can you try the nightly builds? https://yarnpkg.com/en/docs/nightly This PR may have fixed it https://github.com/yarnpkg/yarn/commit/da2b9096057301273aa27336f70622dda09b6c33

**Comment by lehni** [comment] 2017-09-21 07:34
@kaylieEB I am not certain but I think `yarn interactive-upgrade` behaves differently now. I just ran it in a project with lots of minor upgrades, and `package.json` wasn't modified, just `yarn.lock`. Before 1.0.2, I think `package.json` would have been kept in sync with the upgraded versions, but I may be wrong about this... The latest nightly build didn't change that behavior for me.

**Comment by milesj** [comment] 2017-09-21 16:57
@lehni There's also `yarn interactive-upgrade --latest`.

**Comment by milesj** [comment] 2017-09-27 03:31
Err yeah, brain fart. Thanks.

**Comment by iwinux** [comment] 2017-11-22 05:35
same here with yarn 1.3.2

**Comment by brneto** [comment] 2018-03-26 11:24
same here with yarn 1.5.1

**Comment by arrygoo** [comment] 2018-03-28 16:06
Broken in 1.5.1 again

**Comment by asapzacy** [comment] 2018-04-14 21:15
broken with -

```
$ node --version
v9.0.0
$ yarn --version
1.5.1
```

**Comment by aljones15** [comment] 2018-04-17 09:39
same issue node v8.9.4
yarn 1.5.1

**Comment by octref** [comment] 2018-04-24 20:47
One workaround: use `yarn add` instead of `yarn upgrade`.

In short:

- `yarn upgrade`: upgrade packages to latest possible range specified by `pacakge.json`, but do not overwrite
- `yarn add`: upgrade packages to latest possible range **and** rewrite `package.json`
- `yarn update`, like [`npm update`](https://docs.npmjs.com/cli/update): doesn't exist

However npm update's doc says:

> As of npm@5.0.0, the npm update will change package.json to save the new version as the minimum required dependency. To get the old behavior, use npm update --no-save.

But in fact...

```
 y > npm -v
5.7.0
 y > cat package.json
{
  "dependencies": {
    "lodash": "^4.17.5"
  }
}
 y > npm update lodash
npm WARN y No description
npm WARN y No repository field.
npm WARN y No license field.

+ lodash@4.17.10
added 1 package from 2 contributors in 1.004s
 y > cat package.json
{
  "dependencies": {
    "lodash": "^4.17.5"
  }
} 
```

Don't know which one to use :( Yarn added this behavior sometime in 2017 and then broke it silently. npm claims to have it when it doesn't work either.

@kittens Please reopen this issue.

**Comment by aprilmintacpineda** [comment] 2018-06-12 06:10
as said by @octref `yarn upgrade` upgrades the dependencies to their latest version but does not overwrite the `package.json`. `yarn add <package>` will update the package to it's latest version if it's already install and overwrite the `package.json`. Is there a reason for `yarn upgrade` not to overwrite the `package.json`? If so, then maybe that can be added as a flag to `yarn upgrade`.

```
yarn@1.7.0
node@v10.4.0
os: MacOS
```

**Comment by guylepage3** [comment] 2018-06-13 21:42
>One workaround: use `yarn add` instead of `yarn upgrade`.

Works like a charm. Need to update these two Docs pages to use `yarn add` instead of `yarn upgrade`.
- https://yarnpkg.com/lang/en/docs/cli/upgrade/
- https://yarnpkg.com/lang/en/docs/managing-dependencies/

**Comment by lehni** [comment] 2018-06-13 22:02
I've been using `yarn upgrade-interactive --latest` for quite a while now without any hiccups...

**Comment by guylepage3** [comment] 2018-06-13 22:09
>I've been using yarn upgrade-interactive --latest for quite a while now without any hiccups...

Seems a bit redundant.. Why not just use the easiest of all of these commands, `yarn add`? Super simple.

**Comment by lehni** [comment] 2018-06-14 07:59
@guylepage3 because I get to see what upgrades are available in what versions, pick the ones I want to upgrade, and perform multiple upgrades at once that way.

**Comment by guylepage3** [comment] 2018-06-14 13:39
@lehni then the documentation on the website should reflect this and the following two pages should state to use the `yarn upgrade-interactive --latest` method.

- https://yarnpkg.com/lang/en/docs/cli/upgrade/
- https://yarnpkg.com/lang/en/docs/managing-dependencies/

**Comment by alexdevero** [comment] 2018-06-14 13:55
@guylepage3 this conversation is leading nowhere nor does it helps. If you want to suggest update of docs, it might be better to create new issue specifically for that.

**Comment by guylepage3** [comment] 2018-06-14 13:59
Sorry if you feel that way @alexdevero. And yep already did if you look above.. https://github.com/yarnpkg/yarn/issues/1458#ref-issue-332178362

**Comment by lehni** [comment] 2018-06-14 14:21
@guylepage3 I'm not part of yarn. I just wanted to post what has been working well for me.

**Comment by homerjam** [comment] 2018-10-15 11:27
This helped me: https://www.npmjs.com/package/syncyarnlock

```
$ yarn upgrade-interactive && syncyarnlock
```

**Comment by igbopie** [comment] 2019-02-07 19:14
This does not work for me for yarn workspaces. Can someone take a look?

**Comment by alexkuc** [comment] 2023-09-18 20:21
@igbopie perhaps this should be raised as a separate issue since this issue is closed?
