### ISSUE TITLE
How can @webpack team help?

### ISSUE THREAD

**Issue by TheLarkInn** [yarnpkg/yarn#603] opened 2016-10-11 15:31 UTC
According to @wycats it seems like things for webpack users should "just work" out of the box. 

If there are any specific needs, or awesome things that we can do to help make yarn, an even cooler experience, please let us know. Awesome work guys.

**Comment by darcyadams** [comment] 2016-10-13 17:19
[Issue 1009](https://github.com/yarnpkg/yarn/issues/1009) may be related to webpack in some way. Is currently blocking me and my team from adopting yarn.

**Comment by SpaceK33z** [comment] 2016-10-26 22:26
I think this can now be closed, the issue in #1009 (which was a dupe of #629), has been fixed. Yarn is working perfectly fine with webpack. Tried this on macOS and Linux :).

**Closed** 2016-10-26 23:43 UTC
Labels: discussion

**Comment by TheLarkInn** [comment] 2016-10-27 00:03
👏👏👏👏
