### ISSUE TITLE
outdated unexpected error

### ISSUE THREAD

**Issue by sylvainbannier** [yarnpkg/yarn#2026] opened 2016-11-24 23:03 UTC
`yarn outdated` crashes where `npm outdated` works fine.

An issue with `@something` packages ?

```
Trace: 
  Error: https://registry.npmjs.org/@kadira/storybook: Not found
      at Request.params.callback [as _callback] (/home/user/.npm-packages/lib/node_modules/yarn/lib/util/request-manager.js:294:18)
      at Request.self.callback (/home/user/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:186:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/home/user/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:1081:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/home/user/.npm-packages/lib/node_modules/yarn/node_modules/request/request.js:1001:12)
      at IncomingMessage.g (events.js:286:16)
      at emitNone (events.js:91:20)
```

**Comment by torifat** [comment] 2016-11-24 23:17
I believe `@kadira/storybook` is private and you are not logged in. If you have permission then try `yarn login`

**Comment by jsynowiec** [comment] 2016-11-25 06:33
`yarn outdated` for scoped packages was fixed prior to the v.0.17 release and should work. I can't reproduce on v0.17.8.

```
$ yarn why @kadira/storybook
yarn why v0.17.8
[1/4] 🤔  Why do we have the module "@kadira/storybook"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "@kadira/storybook"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "544kB"
info Disk size with unique dependencies: "10.33MB"
info Disk size with transitive dependencies: "71.39MB"
info Amount of shared dependencies: 72
✨  Done in 1.05s.

$ yarn outdated             
yarn outdated v0.17.8
✨  Done in 3.06s.
```

**Comment by wyze** [comment] 2016-11-25 15:35
@sylvainbannier, since you didn't mention the version of Yarn you are using and @jsynowiec shows that it works on latest version. I am going to close this. Let me know if it is still an issue for you on the latest version.

**Closed by wyze** 2016-11-25 15:35 UTC
Labels: needs triage

**Comment by sylvainbannier** [comment] 2016-11-26 09:13
@wyze  you're right it's fixed with the latest version. Thanks all
