### ISSUE TITLE
Yarn Using Cache for file: entries

### ISSUE THREAD

**Issue by aikar** [yarnpkg/yarn#2559] opened 2017-01-26 15:58 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you yarn add file:some/dir, yarn will still use a cache for this package

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn add a file: path to the project, such as a git submodule
Wipe out node_modules/your_module_linked_to_other_folder
git pull a new submodule ref that did not change version number.
yarn install

When developing internal projects, bumping the version number every single commit is unreasonable. 
Not everyone even uses semver for ongoing internal development.

It is unnecessary for Yarn to use its cache for file: URL's. The file reference is a cache itself.

This works fine on NPM.

**What is the expected behavior?**
Yarn should not use a cache at all for file: URL's, ensuring all installs use what ever is latest in the referenced directory.

**Please mention your node.js, yarn and operating system version.**
Node 6.9.4, Yarn v.019.1, OS independent.

**Comment by simonbuchan** [comment] 2017-01-27 04:57
Dupes #2165

**Comment by Daniel15** [comment] 2017-01-27 07:02
Closing as duplicate of #2165 (thanks @simonbuchan!)

**Closed by Daniel15** 2017-01-27 07:02 UTC
