### ISSUE TITLE
install --focus should respect dependency listings and private flags

### ISSUE THREAD

**Issue by uncleramsay** [yarnpkg/yarn#6715] opened 2018-11-22 11:55 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Spinning out this issue from https://github.com/yarnpkg/yarn/issues/5864#issuecomment-393389950 orginally reported by @mrm007

There appear to be two problems:

- Focused installs attempt to install ALL workspace packages, instead of traversing the dependency tree of the focused package
- Focused installs ignore `private` flags and look for all packages on the registry

**If the current behavior is a bug, please provide the steps to reproduce.**
Example provided by @mrm007:

> I don't think the issue is solved. I've hit the same problem in our monorepo, where the structure looks like this:
> 
> ```
> thorium/
> - package.json
> - packages/
>   - thorium-client/
>     - package.json (scoped, published on npm)
>   - thorium-server/
>     - package.json (scoped, private: true, not published on npm)
> ```
> Going to `thorium-server` and running `yarn install --focus` I expect Yarn would install all of **its** dependencies, but it complains about not finding `thorium-server` (itself) on the registry:
> 
> ```
> ⌚ 13:20:48 thorium/packages/thorium-server on  master [$!] 📦 v0.5.0 ⬢ v9.11.1
> ➜ yarn install --focus
> yarn install v1.7.0
> [1/4] 🔍  Resolving packages...
> error Couldn't find package "@myscope/thorium-server@0.5.0" required by "workspace-aggregator-cf24a6bc-8006-421a-bf0b-a98e9fc0f9e8@1.0.0" on the "npm" registry.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> There is no dependency in `thorium-server` on `thorium-client` or vice versa.

**What is the expected behavior?**

Focused installs should only install packages actually required by the focused package (preferred) OR should respect the `private` flag and not look for private packages on the registry.

**Please mention your node.js, yarn and operating system version.**
Windows 10, Yarn 1.12.3, Node 8.12.0

**Comment by SpencerSharkey** [comment] 2018-11-26 07:10
I’m also looking for this behavior when installing an individual workspace.

CI builds of individual workspaces would be much faster if we could fetch and link only the dependencies of a single workspace, rather than all workspaces within the project. 

I thought a focused install would solve for this use-case, but after attempting the install and reading the docs/purpose of focused installs I see why it does not work. That being said, I think the proposed functionality would be really useful for a number of situations.

**Comment by uncleramsay** [comment] 2018-12-03 16:40
@msokk that issue is different. You shouldn't be running `yarn --focus` at the root of a workspace. Please read up on the [blog](https://yarnpkg.com/blog/2018/05/18/focused-workspaces/), it's very helpful in understanding what's going on.

**Comment by msokk** [comment] 2018-12-03 17:12
@uncleramsay worded first comment it badly. What I mean't is that invalid usage error message hints that focused install shouldn't affect other packages.

**Comment by booninite** [comment] 2018-12-06 00:07
The current implementation is half-baked, at best.  Why would you want to install the world to an individual workspace?  I've read the original issue thread multiple times and I can't understand any use cases for this behavior, vs the plentiful use cases of having it behave as expected intuitively based on the documentation.

**Comment by johanblumenberg** [comment] 2018-12-08 12:14
I don't think the problem is about private packages. I think it is a generic problem about what is fetched from a repository when doing a focused install.

I created a minimal project to reproduce the problem: https://github.com/johanblumenberg/yarn-install-focus.git

It's a monorepo containing two packages, `a` and `b`. They have no dependencies. Neither to each other nor to any external package. None of the packages are published.

## yarn install

`yarn install` in the root folder is supposed to create symlinks in the root `node_modules` folder to packages `a` and `b`. This is also exactly what happens.

## yarn install --focus

`yarn install --focus` in the workspace for package `a` is supposed to do the same thing, create symlinks in the root `node_modules` folder to the packages `a` and `b`. But it is also supposed to download and install all the dependencies of `a` in the `node_modules` folder of `a`.

Here is the problem.

```bash
git clone https://github.com/johanblumenberg/yarn-install-focus.git
cd yarn-install-focus/packages/a
yarn install --focus
```

The error I get is this:
```
[1/4] 🔍  Resolving packages...
error Couldn't find package "yarn-install-focus-b@1.0.0" required by "workspace-aggregator-cbdd5932-0dec-4311-b762-fa87df5c84c5@1.0.0" on the "npm" registry.
```

Why is `yarn` trying to download `b` from the repository?
It is supposed to create symlinks for all packages locally, and download all dependencies of `a`. Why is it trying to download `b`?

**Comment by booninite** [comment] 2018-12-08 18:08
I agree that the core of the issue is not private packages, but if `--focus` respected private packages, it would at least be workable.  You'd have bloated node_modules folders (that could be pruned), but you'd actually be able to run the command to completion...

**Comment by johanblumenberg** [comment] 2018-12-10 13:50
How would `--focus` respect private packages?

`yarn install` is supposed to create links between all packages in a repo. You still have to build all packages locally.
`yarn install --focus` is supposed to install dependencies for a single package within a repo, and download all dependencies instead of building them.

What should `yarn` do if it encounters a private package, that cannot be downloaded, because it is private?

Should it symlink the package instead? Then it also has to be built, because otherwise it breaks the rule that all dependencies are downloaded instead of requiring you to build them. My feeling is that it's getting complicated if you start to symlink and build all packages.

If you don't expect `yarn` to build it, then there is no difference between between `yarn install` and `yarn install --focus`.

If you expect `yarn` to build it, then you have a command that generates completely different results for private and public packages.


So, I think the problem of downloading things that are not referenced by the package being installed has to be fixed (https://github.com/yarnpkg/yarn/issues/6715#issuecomment-445454745)

**Comment by mbeaudru** [comment] 2019-04-24 13:02
> So, I think the problem of downloading things that are not referenced by the package being installed has to be fixed

Absolutely, I'm stucked with this as well. Yarn is trying to get all my packages in the workspace from the registry, while they are not declared in the package I'm trying to focus install 😅.

**Comment by Santinell** [comment] 2019-10-09 12:49
> > So, I think the problem of downloading things that are not referenced by the package being installed has to be fixed
> 
> Absolutely, I'm stucked with this as well. Yarn is trying to get all my packages in the workspace from the registry, while they are not declared in the package I'm trying to focus install .

You can try scoped install `yarn install --scope @scope/pkg`

**Comment by tehOPEologist** [comment] 2019-12-20 05:27
has there been any progress on coming to some resolution to this?  i had to publish an empty package with the same name as the private repos to my private registry with ```"files": []``` in the package.json to get this to actually run the command to completion.  would really love it if it respected the ```private``` key in a workspace's package.json to not have to do this workaround!

**Comment by RXminuS** [comment] 2020-01-27 11:16
I'm also looking for this feature. Specific use case it to build a set of local packages in a workspace without installing all node_modules for all packages not used in that particular build.

**Comment by vlastoun** [comment] 2020-01-28 07:26
I tried almost everything and nothing is working...

**Comment by AkshitSahani** [comment] 2020-04-14 19:14
Any update on this? Would love for the --focus flag to install ONLY the dependencies within that particular workspace from the (npm) registry

**Comment by zbigg** [comment] 2020-04-20 13:40
I've been hit by this month or two ago when making monorepo out of few internal packages and services also trying `--focus` flag.

Found this [copy-node-modules](https://github.com/arloliu/copy-node-modules#readme), but it doesn't support `yarn workspace`s.

So &lt;shamelessPlug> i've finally cleaned up my internal scripts and published [this tool](https://github.com/zbigg/copy-production-deps)  that resolves packages from node_modules around your target packages and copies them target dist folder. This just fits my use case, where i build nodejs app from by transpilers into `dist/` folder. &lt;/shamelessPlug>

**Comment by ProLoser** [comment] 2020-07-22 23:53
I'd love to get this fixed, this is the Commit that introduced the `--focus` feature: https://github.com/yarnpkg/yarn/commit/cde75661fcc6eef152f5884565ddb16924c98430

I've been pouring over it to try and identify where it picks up the root package.json and tries to resolve those dependencies. My thought is that would be where to start.

I don't think it's important to pay attention to `private` flag of sibling packages, I think the command should just use the focused package as the only reference for packages it attempts to install.

Has anyone else dug into this? Is this working on yarn2?

**Comment by AnthonyDugarte** [comment] 2021-07-07 15:57
Is this being worked on?

**Comment by JohannesBe** [comment] 2021-07-31 05:43
I think this bug is situated somewhere over [here](https://github.com/yarnpkg/yarn/blob/1.22-stable/src/package-request.js#L186): there is a check to see whether a package is a workspace package, and if it is it is automatically resolved. I think some `if (focused)` + `if (private)` magic might do the trick, but currently I do not have time to investigate further.

**Comment by merceyz** [comment] 2021-07-31 08:16
Closing as fixed in v2 where the `workspaces focus` command does what the issue requests https://yarnpkg.com/cli/workspaces/focus

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-07-31 08:16 UTC

**Comment by JohannesBe** [comment] 2021-08-18 10:04
@merceyz well, this is not really a solution, since not all node packages support yarn v2. For instance [angular](https://github.com/angular/angular-cli/issues/16980) and by extension [nx](https://github.com/nrwl/nx/issues/2386) are both not ready for yarn 2. And yes, I know the existence of the `nodeLinker: node_modules`-option, but even that one runs into issues for me.

**Comment by gbiryukov** [comment] 2022-06-17 06:14
We were struggling as many other people in this thread until gave a try to yarn@3 with node linker (no pnp so far). Honestly there is no reason to use v1 in 2022 anymore. 
Yes, you have to commit 2-3 files in `.yarn` directory. 
At expense of this you receive perfectly working focus mode, way faster installation time, significantly more efficient disk usage, much better cache system (that even let you send it to docker context), guaranteed matching version of yarn across the team and many other benefits
