### ISSUE TITLE
[0.17.0] Cannot add module from github

### ISSUE THREAD

**Issue by ElvisChiang** [yarnpkg/yarn#1831] opened 2016-11-15 02:54 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/elvis/Library/Caches/Yarn/npm-@remobile/react-native-toast-1.0.5-9eb744c751fe94b745a38fa4ae8f2de2d5ff4100'".
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn add github:elvischiang/react-native-toast
```
**What is the expected behavior?**
There should be  a folder named
```
~/Library/Caches/Yarn/npm-@remobile/react-native-toast-1.0.5-<HASH>/
```
But yarn has only
```
~/Library/Caches/Yarn/npm-\@remobile/react-native-toast-1.0.5/
```

**Please mention your node.js, yarn and operating system version.**
node: v4.6.0
yarn: 0.17.0
macOS: 10.11.6

**Comment by Kimleang** [comment] 2016-11-15 03:43
same issue here
try running yarn on fresh Laravel project and it trying to install a package from
```
github:jeroennoten/webpack-stream#patch-1
```
and I got the follwing error
```
"ENOENT: no such file or directory, lstat '/Users/kimleang/Library/Caches/Yarn/npm-webpack-stream-3.2.0-d679c2f1f964b5abae4c1f29d5cb695115deec7b'"
```
![screen shot 2016-11-15 at 9 57 46 am](https://cloud.githubusercontent.com/assets/2344413/20292406/e69ae55e-ab1f-11e6-82b9-5a3b0e502c54.png)

and here is my Yarn cache directory
![screen shot 2016-11-15 at 9 58 31 am](https://cloud.githubusercontent.com/assets/2344413/20292415/f646b6cc-ab1f-11e6-83df-1a90e46f01f7.png)

node: v6.9.1
npm: 3.10.8
yarn: 0.17.0
macOS: 10.12.1

**Comment by bjeanes** [comment] 2016-11-15 03:43
I'm also getting this with all my GitHub packages. E.g.:

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/bjeanes/Library/Caches/Yarn/npm-ExpandingTextareas-0.2.0-c8b5f4a63b99818343fd90653182da17e944236f'".
```

If I `mv ~/Library/Caches/Yarn/npm-ExpandingTextareas-0.2.0{,-c8b5f4a63b99818343fd90653182da17e944236f}`, then I can proceed. If I don't have the dependency of a new or changed git dependency in my cache already (with the sha in name) I get this error 100% of the time when it tries to link these dependencies.

**Comment by FredyC** [comment] 2016-11-15 12:32
I would say duplicate of my already reported #1829

**Comment by bjeanes** [comment] 2016-11-15 21:43
Not necessarily. It seems likely that the bug in this issue is due to not interpolating the git sha into the directory and so probably git clone specific. That issue is referencing a non-git dependency (`node-sass`). Maybe they share an underlying issue but I don't think there's much to indicate that yet.

**Comment by FredyC** [comment] 2016-11-15 21:49
Sorry, my bad, I meant #1818

**Comment by bjeanes** [comment] 2016-11-15 22:11
Ah yes, probably

**Comment by bestander** [comment] 2016-11-16 00:10
Closing in favor #1818 then

**Closed by bestander** 2016-11-16 00:10 UTC
Labels: needs triage

**Comment by tanx** [comment] 2016-11-16 13:51
I'm still getting this error with yarn 0.17.2 :(

**Comment by FredyC** [comment] 2016-11-16 13:55
@tanx Apparently [changelog for 0.17.2](https://github.com/yarnpkg/yarn/releases/tag/v0.17.2) did not mention this to be fixed, so I am not even trying it.

**Comment by tanx** [comment] 2016-11-17 08:37
@FredyC I tested again with 0.17.3 and the issue seems to be resolved now. Thanks everyone for your quick help!
