### ISSUE TITLE
Does not even come close to doing what it claims it can do.

### ISSUE THREAD

**Issue by Jtech42** [yarnpkg/yarn#4827] opened 2017-11-01 19:45 UTC
When run it won't get the dependencies on it's list. Just says it's "done" and then it turns off. Yarn is a completely worthless waste of time please stop releasing garbage.

**Comment by kaylieEB** [comment] 2017-11-02 00:43
Hi @Jtech42 thanks for trying out yarn. Here's our [usage guide](https://yarnpkg.com/en/docs/usage) and [code of conduct](https://github.com/yarnpkg/yarn/blob/master/CODE_OF_CONDUCT.md). I'm going to go ahead and close this issue since there aren't steps to reproduce, but feel free to file another one following the format. Thanks!

**Closed by kaylieEB** 2017-11-02 00:43 UTC
