### ISSUE TITLE
Allow generating a lock file from an existing node_modules

### ISSUE THREAD

**Issue by jerel** [yarnpkg/yarn#682] opened 2016-10-11 18:07 UTC
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
When converting an existing project, running `yarn` appears to read package.json and download dependencies again based on declared dependency versions. This may not result in a working build if dependencies used `~` or `^` versions to declare their dependencies.

**What is the expected behavior?**
It would be nice if running a command like `yarn freeze` (from python's `pip freeze`) could determine the exact version of installed dependencies in `node_modules` in an existing project. This would allow an aged project with dependency drift but an intact `node_modules` to be locked by yarn.

**Please mention your node.js, yarn and operating system version.**
yarn v0.15.1

**Comment by FraserKillip** [comment] 2016-10-11 19:05
Does this solve your issue? https://yarnpkg.com/en/docs/cli/generate-lock-entry

**Comment by tomdale** [comment] 2016-10-11 20:24
@FraserKillip I don't believe that command solves the requested use case, because it works by examining the contents of `package.json` rather than the concrete versions that appear in the actual `node_modules` tree.

**Comment by thejameskyle** [comment] 2016-10-11 20:38
I doubt this would be possible as the whole point of the lock file is to power the deterministic algorithm yarn uses. If something isn't matching that algorithm then it's not gonna lead to the same result consistently

**Comment by ljharb** [comment] 2016-10-11 23:04
@thejameskyle could perhaps yarn take an existing node_modules folder, compare it to the deterministic hierarchy yarn would have used from package.json, and walk the user through some of the diffs? Most of the time the deltas would probably be insignificant.

**Comment by mwmdev** [comment] 2016-10-12 17:14
This feature is very interesting and important for a dev that has lots of existing projects each with its node_modules/ filled from a npm install in a specific point in time.

yarn would generate a lock file based on the node_modules to simulate a yarn install at the time of the npm install.

**Comment by bryanlarsen** [comment] 2016-11-02 12:14
@thejameskyle, I don't care if yarn can't reproduce the node_modules exactly, npm can't do that either.   It's just that it would be really nice to generate a lock file that pulled the version numbers out of node_modules or npm-shrinkwrap.json.   Our npm-shrinkwrap.json is our source of truth for version numbers, not package.json.

**Comment by bstro** [comment] 2016-11-28 19:12
My company could be using Yarn today if only it had this feature. :) Any chance this is possible?

**Comment by bstro** [comment] 2016-11-28 20:21
My company could be using Yarn today if only it had this feature. :) Any chance this is possible? @thejameskyle any chance this will be looked at again?

**Comment by thejameskyle** [comment] 2016-11-30 00:58
It seems to me that in order to implement the requested feature we would have to generate a _complete_ tree from the `package.json`'s that exist in the file system (which does not represent a complete tree). Then we would have to take that tree and use it to look up potential resolutions when building a new tree with Yarn almost like it is a lockfile.

All of that is entirely new complexity that would have to be added to Yarn, we wouldn't be able to take advantage of much that exists already and I'm not sure that technical debt is worth adding.

Someone could attempt to build a separate tool that can:

```
mv node_modules npm_node_modules
yarn install
```

And then diff the generated `yarn.lock` against things it can find in `npm_node_modules` to tell you which packages may have resolved to different versions.

That could be built as a separate tool which may be useful to some people. I don't think it's something that we should do though.

**Comment by TimvdLippe** [comment] 2017-02-20 14:03
I think this issue can be closed as #2580 has been merged.

**Closed** 2017-02-23 18:47 UTC
Labels: new feature
