### ISSUE TITLE
@yarnpkg/lockfile@1.1.0' is not in the npm registry

### ISSUE THREAD

**Issue by danieletas** [yarnpkg/yarn#8283] opened 2020-08-06 11:25 UTC
Reproduce steps:
npm i @yarnpkg/lockfile

Log details:
```javascript
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   '@yarnpkg/lockfile'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose npm-session 8c7926b781b87a18
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@yarnpkg%2flockfile 988ms
8 http fetch GET 404 https://registry.npmjs.org/@yarnpkg%2flockfile 750ms
9 silly fetchPackageMetaData error for @yarnpkg/lockfile@latest 404 Not Found - GET https://registry.npmjs.org/@yarnpkg%2flockfile - Not found
10 timing stage:rollbackFailedOptional Completed in 1ms
11 timing stage:runTopLevelLifecycles Completed in 3893ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@yarnpkg%2flockfile - Not found
12 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13 verbose statusCode 404
14 verbose pkgid @yarnpkg/lockfile@latest
15 verbose cwd D:\Commesse\........... bla bla
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@yarnpkg/lockfile"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/@yarnpkg%2flockfile - Not found
22 error 404
23 error 404 '@yarnpkg/lockfile@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]
```
```javascript
$ npm --version
6.14.5

```

**Comment by inyono** [comment] 2020-08-06 11:34
Most likely duplicate of #8279 (NPM Registry is having issues right now)

**Comment by danieletas** [comment] 2020-08-06 16:39
repository workgin now

**Closed** 2020-08-06 16:38 UTC
