### ISSUE TITLE
Yarn Plug'n'Play" is 

### ISSUE THREAD

**Issue by pgonzal** [yarnpkg/yarn#6636] opened 2018-11-05 18:37 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

**Comment by arcanis** [comment] 2018-11-05 19:10
Closing, I think it's a duplicate of #6637

**Closed by arcanis** 2018-11-05 19:10 UTC
Labels: triaged

**Comment by pgonzal** [comment] 2018-11-05 19:22
Weird... that was unintentional.
