### ISSUE TITLE
Yarn doesn't work with private packages

### ISSUE THREAD

**Issue by bernardoatworkpop** [yarnpkg/yarn#1007] opened 2016-10-13 16:14 UTC
When trying out yarn:

```
[1/4] 🔍  Resolving packages...
error https://registry.yarnpkg.com/@workpop%2feslint-config-workpop: Not found
    at Request.params.callback [as _callback] (/usr/local/lib/node_modules/yarnpkg/lib/util/request-manager.js:273:18)
    at Request.self.callback (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yarnpkg/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Can't use yarn with private packages

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Should just work, as NPM install works just fine.

**Please mention your node.js, yarn and operating system version.**
➜  pop git:(master) node --version
v6.5.0
➜  pop git:(master) npm --version
3.10.3
➜  pop git:(master) yarn --version
0.15.1
➜  pop git:(master)

**Comment by joshmanders** [comment] 2016-10-13 16:27
duplicate of https://github.com/yarnpkg/yarn/issues/521

**Comment by Daniel15** [comment] 2016-10-13 17:44
Closing this as a duplicate of #521. Thank you for trying Yarn! 😄

**Closed by Daniel15** 2016-10-13 17:44 UTC
