### ISSUE TITLE
Yarn run doesn't work as expected

### ISSUE THREAD

**Issue by tigranavetis** [yarnpkg/yarn#970] opened 2016-10-13 07:24 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I run `yarn run <script>`, where is script is specified in 'scripts' part of package.json, I get an error:
`error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to the folder of your project and `yarn run`, after choose one the commands.

**What is the expected behavior?**
Expected behaviour is executing scripts without any problems

**Please mention your node.js, yarn and operating system version.**
Node.js version - 6.8.0, yarn 0.15.1, operating system version - OS X EL Capitan Version 10.11.5

**Comment by jayS-de** [comment] 2016-10-13 07:49
Have the same issue. Arises cause most scripts make use executables found in node_modules/.bin 

Seems that the run command is not setting correctly the PATH environment for the run shell

**Comment by jayS-de** [comment] 2016-10-13 08:05
Btw seems to be a duplicate of #733

**Comment by kittens** [comment] 2016-10-13 09:21
Fixed via #809.

**Closed by kittens** 2016-10-13 09:21 UTC
