### ISSUE TITLE
while updating Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by rajacyber** [yarnpkg/yarn#8872] opened 2022-08-18 18:34 UTC
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\adobereader_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
2022-08-17 21:13:40,337 5284 [WARN ] - WARNING: Exit code '1603' was considered valid by script, but not as a Chocolatey success code. Returning '0'.

**Comment by merceyz** [comment] 2022-08-18 18:37
Duplicate of https://github.com/yarnpkg/yarn/issues/8871

**Closed by merceyz** 2022-08-18 18:37 UTC
