### ISSUE TITLE
Invalid package version installed if other package dependes on other version

### ISSUE THREAD

**Issue by Strate** [yarnpkg/yarn#4556] opened 2017-09-27 13:18 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can't install `react-draggable@1.3.7` and `read-grid-layout@0.13.9` together

**If the current behavior is a bug, please provide the steps to reproduce.**

Use this package.json:

```json
{
  "name": "yarn-test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "react-draggable": "1.3.7",
    "react-grid-layout": "0.13.9"
  }
}
```

do `yarn install`.

Check `react-draggable` packages installed:

```
% yarn list react-draggable                                                                                                                                                                                
yarn list v1.1.0
warning Lockfile has incorrect entry for "react-draggable@1.3.7". Ignoring it.
warning Lockfile has incorrect entry for "react-draggable@^2.1.1". Ignoring it.
├─ react-draggable@1.3.7
├─ react-grid-layout@0.13.9
│  └─ react-draggable@2.2.6
└─ react-resizable@1.7.5
   └─ react-draggable@3.0.3
Done in 0.33s.
```

And test *actually* installed version of react-draggable at the root:

```
% grep version ./node_modules/react-draggable/package.json                                                                                                                                                 
  "version": "3.0.3",
```

**What is the expected behavior?**
3.0.3 should be installed inside react-resizable, not at the root, because at root I need 1.3.7, as specified in package.json file

NPM handle this situation as expected.

**Please mention your node.js, yarn and operating system version.**
```
% node -v                                                                                                                                                                                                  
v6.10.0

% yarn -v                                                                                                                                                                                                  
1.1.0
```

**Comment by arcanis** [comment] 2017-09-27 13:22
Woops, that seems to be a pretty bad regression 😨 

It only affects the 1.1.0 release, the 1.0.2 is fine. I suspect it comes from this commit:
4020ccd0a3304239877562b776f2aff27ebf2ede

cc @mxmul @BYK

**Comment by arcanis** [comment] 2017-09-27 13:42
I'll close this as duplicate of #4547 to make things easier, subscribe there if you want to be kept in the loop. Thanks for your report!

**Closed by arcanis** 2017-09-27 13:42 UTC
Labels: bug-high-priority, bug-resolution
