### ISSUE TITLE
yarn upgrade ruins peerDependencies approach

### ISSUE THREAD

**Issue by andvgal** [yarnpkg/yarn#4314] opened 2017-09-05 11:24 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yarn creates "dependencies" entry when upgrading "peerDependencies". The peerDep itself is left as is.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. yarn init
2. yarn add --peer futoin-asyncsteps@1.7.0
3. Observe package.json:
```json
{
  "name": "yarn-peer-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "peerDependencies": {
    "futoin-asyncsteps": "1.7.0"
  }
}
```
4. yarn upgrade --latest
5. Observe broken package.json:
```json
{
  "name": "yarn-peer-bug",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "peerDependencies": {
    "futoin-asyncsteps": "1.7.0"
  },
  "dependencies": {
    "futoin-asyncsteps": "^1.7.1"
  }
}
```

**What is the expected behavior?**
1. Yarn must upgrade dependency in each section it is located: "dependencies", "devDependencies", "peerDependencies", "optionalDependencies".
2. If the same dep is in multiple sections, it must be correctly updated in all of them
3. Yarn must never add deps in sections where they were not present before upgrade command.

**Please mention your node.js, yarn and operating system version.**
Yarn: v0.27.5 & v0.28.4
Node: v8.4.0
Debian Jessie

Related #2127

**Comment by BYK** [comment] 2017-09-07 09:09
Can't replicate this on latest master. On master `yarn upgrade` doesn't touch `peerDependencies` at all.

**Comment by andvgal** [comment] 2017-09-07 09:58
@BYK, yes it does not touch "peerDependencies", but adds not previously existing "dependencies" with upgrade version instead.

**Comment by BYK** [comment] 2017-09-07 12:40
@andvgal no, I mean it doesn't do anything at all :D

**Comment by BYK** [comment] 2017-09-15 23:15
@andvgal I'm going to close this one since you haven't followed up in more than a week and this may be an issue with an older version of Yarn.

Feel free to reopen the ticket if you can reproduce this with the latest version of yarn.

**Closed by BYK** 2017-09-15 23:15 UTC
Labels: needs-investigation
