### ISSUE TITLE
Yarn doesn't read from .npmrc Files for custom registry settings

### ISSUE THREAD

**Issue by raybooysen** [yarnpkg/yarn#606] opened 2016-10-11 15:38 UTC
With an .npmrc file like below:

```
registry=http://local-npm-install:8080
```

It seems yarn will not respect this and try the normal NPM upstream.

**Comment by tyrsius** [comment] 2016-10-11 15:44
We use custom registries for a lot of private modules, this is must-have functionality.

**Comment by maniator** [comment] 2016-10-11 15:45
Cannot use yarn until this issue is resolved.

**Comment by nkabardin** [comment] 2016-10-11 15:57
I wonder, so Facebook doesn't have internal registry for private stuff? Or it's just not yet implemented for open source?

**Comment by jkrems** [comment] 2016-10-11 16:07
Even worse - it uses the yarn registry config when asked to fetch from npm:

```diff
 class NpmRegistry extends (_baseRegistry || _load_baseRegistry()).default {
   /* ... */

   request(pathname) {
     // ...
-    const registry = (0, (_misc || _load_misc()).removeSuffix)(String(this.registries.yarn.getOption('registry')), '/');
+    const registry = (0, (_misc || _load_misc()).removeSuffix)(String(this.registries.npm.getOption('registry')), '/');
```

**Comment by thejameskyle** [comment] 2016-10-11 16:10
Hey everyone, please use the upvote button on GitHub so we can keep this issue from turning into 1000 comments

**Comment by jkrems** [comment] 2016-10-11 16:18
Workaround - put the following into a `.yarnrc` file in the project root:

```
registry "https://my-registry.corp"
```

**Comment by tyrsius** [comment] 2016-10-11 16:23
@jkrems What is the syntax for scoped registries?

```
@scope:registry "http://place.com"
```

throws an `unknown token` error

**Comment by jkrems** [comment] 2016-10-11 16:24
@tyrsius It's a custom file format (`src/lockfile/parse.js`). I reverse engineered just enough to make my example above work. ;)

**Comment by andypham** [comment] 2016-10-11 16:39
Would be awesome if yarn can address this issue as I work with internal registry daily.

**Comment by alexgorbatchev** [comment] 2016-10-11 16:50
possible list of supported `.yarnrc` defaults is here https://github.com/yarnpkg/yarn/blob/0f1db96846badbbe3b43c470c05196eb29437fb4/src/registries/yarn-registry.js#L16

**Comment by alexgorbatchev** [comment] 2016-10-11 16:56
Anyone figured out yet how to configure `ca` values?

**Comment by tomccabe** [comment] 2016-10-11 17:16
Complete blocker to using this tool. Changed the registry in yarn config (because "drop in replacement for npm"!! 🤔), `yarn login`'d, no dice.

**Comment by ljharb** [comment] 2016-10-11 17:21
This is a blocker to Airbnb using yarn - just like yarn uses package.json, it should also use every other npm configuration method (`.npmrc`, as well as all the case-insensitive environment variables `npm` respects).

**Comment by bbatha** [comment] 2016-10-11 17:29
I tested putting:
```
"@mycorp:registry" "https://my-registry.corp"

```

in my projects yarnrc, it does not appear to work

**Comment by devongovett** [comment] 2016-10-11 17:52
For registries requiring auth, some work might be needed as well. For example, our `.npmrc` file looks like this:

```
registry=https://my-registry.com
_auth=some_auth_token
email=test@example.com
always-auth=true
```

Couldn't find a way to make a `.yarnrc` file that did the same thing.

**Comment by benmonro** [comment] 2016-10-11 17:58
I have the same issue

**Comment by ljharb** [comment] 2016-10-11 19:20
If a yarnrc is required for anything, then yarn is not a drop in replacement for npm

**Comment by majgis** [comment] 2016-10-11 20:14
I'm trying to use with npm support on Sonatype Nexus  2.11.3-01, I just get this, with a .yarnrc file as first described above:

```
$ yarn install
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "express" on the "npm" registry.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by arcticShadow** [comment] 2016-10-11 22:51
If your custom registry requires a trailing slash, yarn is stripping it. rectify this by appending your registry url with a double slash i.e..
`yarn config set registry http://registry.com/registry/endpoint//`

**Comment by tyrsius** [comment] 2016-10-11 22:56
@arcticShadow that fixed both issues for me, scoped registry is working now

**Comment by arcticShadow** [comment] 2016-10-11 23:21
Indeed it does. Couple of options:

1. `echo "registry \"http://registry.com/registry/endpoint//\"" > .yarnrc` as mentioned earlier
2. Theoretically, appending your .npmrc registry URL with a double slash would work for both npm and yarn, although I havn't tested that

I'd like to point out, though, given that the .yarnrc file was already mentioned, and the double slash trick has been mentioned, I thought you would have been able to connect the dots on that one your-self. Perhaps bleeding edge tech is not your thing?

**Comment by tyrsius** [comment] 2016-10-11 23:26
@arcticShadow You misunderstand: putting it in the `.yarnrc` file does _nothing_. If your global yarn registry is set to npm, and you put a custom registry in `.yarnrc`, installation will still go to the globally defined registry. 

There is no need to be rude.

**Comment by arcticShadow** [comment] 2016-10-11 23:32
My apologies - I missed your edit clarifying the behaviour.

**Comment by arcticShadow** [comment] 2016-10-11 23:43
Further digging in the registry code shows that the global `.yarnrc`, the home `.yarnrc` and the cwd `.yarnrc` are read (in that order) and stored in an array, where they build out a 'config' object using 'defaults' i.e. only consume a value if it does not already exist. This would appear to merge all the `.yarnrc` files together in a sane way. 

If your local .yarnrc is being ignored, perhaps try checking the syntax? it can be copied out of the `~/.yarnrc` which is written by `yarn config set...` if you wanted to double check.

**Comment by tyrsius** [comment] 2016-10-11 23:46
I tried that, it didn't work. Does it work for you?

**Comment by tyrsius** [comment] 2016-10-11 23:55
You can see here that the `cwd` has a `.yarnrc`, but the error shows that it is resolving to the global registry

![image](https://cloud.githubusercontent.com/assets/1187432/19292751/4b716b0a-8fd3-11e6-9201-52a4aecd351a.png)

**Comment by arcticShadow** [comment] 2016-10-12 00:02
Not sure what to say - Works on my machine (tm)

I've tested this by putting a completely fake URL in my `~/.yarnrc` and my real registry in my local.

I've also tested with no registry in `~/.yarnrc`

```
 $ cat ~/.yarnrc
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
registry "http://fakeserver.com//"
$ cat ./.yarnrc
registry "http://artifactory/artifactory/api/npm/orion-virtual-npm//"

```

I have not tested this with scoped packages though...

**Comment by tyrsius** [comment] 2016-10-12 00:08
I figured it out. The global setting will work for scopes, but the cwd one doesn't. `.npmrc` uses this format for scopes:
```
@nike:registry=http://server.com
```

`.yarnrc` needs this format (including the `@` was causing the error earlier)

```
```
nike:registry "http://server.com"
```

The local `.yarnrc` is working correctly now

**Comment by tyrsius** [comment] 2016-10-12 00:16
Yea, it looks like the scoped package resolution is not working. Perhaps I am just not specifying it correctly. 
I've tried these
```
@nike:registry "http://server.com" #throws token error
nike registry "http://server.com" #throws value error
nike:registry "http://server.com" #does nothing
```

**Comment by mocheng** [comment] 2016-10-12 02:44
In my case, I keep `.npmrc` file side by side with `.yarnrc`.

`.npmrc` file:
```
_auth = xxxxxxx
registry = http://xxx.com
ca = null
email = xxx@xxx.com
always-auth = true
```

·.yarnrc` file:
```
registry " http://xxx.com"
```

Keep registry field in both file same and it works.

**Comment by arcticShadow** [comment] 2016-10-12 03:06
is that an intentional space preceding your registry? Any reason for that?

**Comment by mocheng** [comment] 2016-10-12 03:39
@arcticShadow No. It's a typo. I have fixed that.

**Comment by bripkens** [comment] 2016-10-12 04:43
> In my case, I keep .npmrc file side by side with .yarnrc.

This only works for me with Nexus and HTTP basic auth by specifying user and password as part of the URL:

```
https://user:password@myrepo.example.com//
```

Doesn't seem like the `_auth` directive is picked up from the `.npmrc`.

**Comment by matheusrocha89** [comment] 2016-10-12 06:03
@bripkens I think my problem is the same as yours

**Comment by OlegZee** [comment] 2016-10-12 06:06
I tried all kind of setting the custom repo and it keeps failing with ECONNRESET:
```
yarn install v0.15.1                                                                                                                  
info No lockfile found.                                                                                                               
[1/4] Resolving packages...                                                                                                           
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade                   
error read ECONNRESET                                                                                                                 
    at exports._errnoException (util.js:1026:11)                                                                                      
    at TCP.onread (net.js:563:26) 
```

My current .yarnrc is
```
registry "http://npm.ncgc.local//"
```

Btw yarn hangs if there's no '\n' in the end.

**Comment by carmelone** [comment] 2016-10-12 08:20
I can confirm `.yarnrc` file with `registry "https://xxx.com"` works.

Now I need to know how to do with `.npmrc`: `strict_ssl=false` and auth with token (for using it with sinopia or something like that.

News?

**Comment by kittens** [comment] 2016-10-12 08:29
Thank everyone for the comments. I'll have a patch out later today to fix this 😄

**Comment by kittens** [comment] 2016-10-12 12:34
Created #871 to fix this, pending approval.

**Closed by kittens** 2016-10-12 12:34 UTC
