### ISSUE TITLE
Fetching packages aborts silently on external dependencies by git+https & login credentials.

### ISSUE THREAD

**Issue by ChristophAtAdlos** [yarnpkg/yarn#4506] opened 2017-09-20 10:35 UTC
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
`yarn upgrade` fetches all packages until there is a package fetched by `git+https`, using username and password. It waits some seconds and aborts then, without any message.

**If the current behavior is a bug, please provide the steps to reproduce.**
 * Add a dependency to a private git repo by using username and password in the url:  
    In packages.json:
    `"myPackage": "git+https://{user}:{password}@git.{myOwnGit}.com/path/myProject.git#develop",`

 * Then launch `yarn upgrade`.

**What is the expected behavior?**
 1. Yarn installs all dependencies, also from the own git repo.
 2. If it does not, it gives at least a message, explaining the reason why it aborts.

**Annotation:** The problem is NOT on the repo. NPM installs without troubles.

**Please mention your node.js, yarn and operating system version.**
nodejs 6.1.0
yarn 1.0.2
Windows 10 Pro x64

**Comment by BYK** [comment] 2017-09-26 11:33
I think this is a duplicate of #4282. I strongly urge you to upgrade to a newer Node version to get these fixed.

**Closed by BYK** 2017-09-26 11:33 UTC

**Comment by ChristophAtAdlos** [comment] 2017-09-26 12:13
We updated to the LTS version 6.11.3. This version is fixed by the company. With other words: in the meantime, npm has learned from yarn. It's time to switch back to npm.

**Comment by BYK** [comment] 2017-09-27 23:50
>We updated to the LTS version 6.11.3.

You should not be experiencing the issue with Node 6.11.3

>With other words: in the meantime, npm has learned from yarn. It's time to switch back to npm.

Not sure if I follow. You are of course free to switch back to npm if it satisfies your needs. I'm just curious why regarding this particular issue since the more recent Node version you mentioned should solve the issue already.

**Comment by ChristophAtAdlos** [comment] 2017-10-02 09:47
For the project I work on, npm is defined as standard. I was an exotic with yarn to work around the problems with linked projects. But in the meantime, this works well with npm too. The only thing I miss is the speed of yarn. But mixing npm and yarn together is no good idea. Personally I would prefer yarn.
