### ISSUE TITLE
some issues related to deep dependencies

### ISSUE THREAD

**Issue by undoZen** [yarnpkg/yarn#4025] opened 2017-07-26 08:57 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
not installing right deep dependencies

**If the current behavior is a bug, please provide the steps to reproduce.**
Use vue webpack template to init a project, set dependencies `vue@~2.2` `vue-template-compiler@~2.2` in package.json, then `yarn` and `npm run dev`, fails and report vue vue-template-compiler version not match. but if I use `npm i`, version solved well.

**What is the expected behavior?**
works well as use npm

**Please mention your node.js, yarn and operating system version.**
node v7.9.0 npm v4.2.0
yarn v0.27.5

**Comment by BYK** [comment] 2017-07-26 10:56
Can you please provide us with a `package.json` and your installed versions so we can reproduce this reliably and try to fix it?

**Comment by undoZen** [comment] 2017-07-27 03:42
@BYK here https://github.com/undoZen/yarn-bug-demo

**Comment by BYK** [comment] 2017-07-27 14:48
Looks like `vue-loader` is at fault here. It is listing `vue-template-loader` as a dependency whereas it should list it as a `peerDependency`. Seems to be fixed on latest master: https://github.com/vuejs/vue-loader/blob/master/package.json#L48

**Comment by BYK** [comment] 2017-07-27 14:48
Also, next time, please make sure your `yarn.lock` file does not have links to a private repository ;) I had to remove it to test your repo.

**Closed by BYK** 2017-07-27 14:48 UTC
