### ISSUE TITLE
Incorrect functioning by add -D

### ISSUE THREAD

**Issue by iMasterAle** [yarnpkg/yarn#1769] opened 2016-11-10 10:13 UTC
When I add a package with -D shortcut, yarn adds the package in the dependencies, not in devDependencies if I add with --dev, yarn works correctly.

Node: v7.0.0,
Yarn: v0.16.1,
Npm: v3.10.9

**Comment by CodeJjang** [comment] 2016-11-10 11:35
Although you opened the bug before me, I think [my issue](https://github.com/yarnpkg/yarn/issues/1770) is more descriptive... Seems like a recent bug in yarn.

**Comment by iMasterAle** [comment] 2016-11-10 11:39
Yes thanks @CodeJjang !

**Comment by kittens** [comment] 2016-11-10 13:30
Dupe of #1770.

**Closed by kittens** 2016-11-10 13:30 UTC
