### ISSUE TITLE
error An unexpected error occurred: "https://registry.yarnpkg.com/faker/-/faker-3.1.0.tgz: unexpected end of file"

### ISSUE THREAD

**Issue by imrrahul** [yarnpkg/yarn#6969] opened 2019-01-27 06:07 UTC
**you want to report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I am getting this error whenever I am using the **docker-compose up** command and then it goes to resolving issues and then gives out some warning and this error. please help
![screenshot from 2019-01-27 11-34-51](https://user-images.githubusercontent.com/37583853/51797373-5d3fa880-2228-11e9-96b5-dfc0041b9cf2.png)

**Please mention your node.js, yarn and operating system version.**
ubuntu 18.04
yarn 1.13.0
node v8.15.0

**Comment by colbyfayock** [comment] 2019-09-06 12:26
i see this often with https://github.com/fabiospampinato/bump from within our Jenkins pipeline

![image](https://user-images.githubusercontent.com/1045274/64427678-cb323500-d07f-11e9-816c-34a75970eec4.png)

looks like !4412 was related but the OP closed

when i see this occur, i've tried to load it directly in my browser. when i do, i'm able to start a download of the file, but it eventually gets a "Failed Network" error in Chrome, which I'm guessing is a result of the EOF error

the issue seems intermittent, usually shortly after it works again, but its frustrating when builds fail due to it

**Comment by Alonski** [comment] 2019-09-09 08:34
Also having this issue in CI
Any updates?

**Comment by jpreynat** [comment] 2019-09-11 14:33
Same here using the latest yarn 1.17.3 in CI.

**Comment by leidegre** [comment] 2019-09-21 05:54
This is happening to me to, it's always the same package and it's a package with a larger binary inside about 4 MB.

This is happening intermittently in our Azure DevOps piplines (running Windows). But I just ran into this running yarn from a Debian 9 installation. Would like to know what would cause this, how to root cause the issue?

**Comment by vandamm** [comment] 2019-09-27 09:55
Also happens for us frequently in GitLab CI pipelines

**Comment by colbyfayock** [comment] 2019-09-30 17:20
@arcanis any chance we can get a little attention here?

**Comment by colbyfayock** [comment] 2019-10-01 02:25
it's not an ideal solution but for the time being, I was able to patch my npm dependency directly to the github source. 
```
"@fabiospampinato/bump": "https://github.com/fabiospampinato/bump.git",
```
Replacing the above pattern with your dependency of course.

**Please be warned**, this could be a huge tradeoff and might depend on the dependency for being able to do this, as you may lose some abilities to maintain the right version of the dependency and other npm/yarn features.

**Comment by tobinus** [comment] 2020-01-23 07:57
I encountered this error today. Failed when I retried right after, but worked again when I retried after a couple minutes. Bug in the server running at registry.yarnpkg.com I suppose?

**Comment by paul-soporan** [comment] 2021-01-03 16:31
Closing as the v2 is a lot less susceptible to such issues because we've greatly improved the timeout and retry logic.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-03 16:31 UTC
Labels: triaged

**Comment by OPSTime** [comment] 2021-08-13 12:05
This is happening to me too, it's always the same package.
https://nexus.wisers.com.cn/repository/devops-npm-group/@material-ui/icons/-/icons-4.9.1.tg
