### ISSUE TITLE
Binaries from dependencies of dependencies are not added to ".bin" folder as symlinks

### ISSUE THREAD

**Issue by swernerx** [yarnpkg/yarn#1613] opened 2016-11-02 09:16 UTC
Compared to "npm", yarn currently does not add symlinks for binaries in deep dependencies to the ".bin" folder. I heavily rely on this for the [advanced boilerplate](https://github.com/sebastian-software/advanced-boilerplate) which is basically a dependency for all my react project. I try to keep dependencies central in this one repository instead of listing everything in my application projects. 

BTW: Yarn also complains a lot on these non direct dependencies. This also differs from npm which, based on the "new" flat "node_modules" folder, just works. With the exceptions of the binary symlinks yarn works here as well - the question is only if these warnings are really needed when the dependencies are fully fulfilled after the installation.

Example:
```
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "estraverse@*".
warning Unmet peer dependency "react@^15.0.0".
warning Unmet peer dependency "react-dom@^15.0.0".
warning Unmet peer dependency "react@^15.3.2".
warning Unmet peer dependency "react@^15.3.2".
warning Unmet peer dependency "react@^15.3.2".
warning Unmet peer dependency "react@^15.3.2".
warning Unmet peer dependency "react@^15.3.2".
warning Unmet peer dependency "react@0.14.x || 15.* || ^15.0.0".
warning Unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
warning Unmet peer dependency "react-dom@^0.14.0 || ^15.0.0-0".
warning Unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
warning Unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning Unmet peer dependency "react-dom@^0.14.0 || ^15.0.0".
warning Unmet peer dependency "react@^15.0.0-0".
warning Unmet peer dependency "react@^0.14.0 || ^15.0.0".
warning Unmet peer dependency "react@^15.0.0".
```

React 15, eslint and stylelint are all installed through the "advanced boilerplate" which is listed in the "dependencies" in "package.json".

**Comment by kittens** [comment] 2016-11-02 11:58
Duplicate of #760.

**Closed by kittens** 2016-11-02 11:58 UTC
