### ISSUE TITLE
Incompatibility with npm5 when run yarn add file:FolderName

### ISSUE THREAD

**Issue by rodriguesbreno** [yarnpkg/yarn#4212] opened 2017-08-20 00:14 UTC
**Do you want to request a *feature* or report a *bug*?**
_bug_

**What is the current behavior?**
Incompatibility with npm 5.

consider the following package.json (reduced for brevity)

```json
{
  "name": "my-project",
  "description": "my project",
  "main": "index.js",
  "dependencies": {
      "my_local_lib": "file:LocalLib"
   }
}
```

with npm 5 the lib "my_local_lib" is installed as a symlink
but yarn install it as copy of the folder LocalLib

**If the current behavior is a bug, please provide the steps to reproduce.**

1. create a new project
2. create a sub project (folder named FolderX with a package.json)
3. ```yarn add FolderX```
4. ```yarn install```

**What is the expected behavior?**
create a symlink of FolderX

**Please mention your node.js, yarn and operating system version.**
node v8.4.0
yarn  v0.27.5
macOS 10.12.6

**Comment by webmobiles** [comment] 2017-08-22 06:46
why yarn need npm? if i do npm install -g npm@4.6.1 to downgrand from npm5 is ok? it's not yarn independent from npm?

**Comment by BYK** [comment] 2017-08-23 14:35
Looks like this was an unannounced change: http://codetunnel.io/npm-5-changes-to-npm-link/

I'm not sure if changing the `file:` protocol's behavior to be `link:` is a good idea. Why do you need it?

**Comment by BYK** [comment] 2017-08-23 14:35
@webmobiles I think your comment is misplaced?

**Comment by arcanis** [comment] 2017-08-23 14:57
Yeah we decided against implementing this change at the time we started working on the `link` protocol. Even now I'm not sure we should follow it; if you actually want to copy the files you would have no way of doing it.

**Comment by arcanis** [comment] 2017-08-23 14:58
The NPM issue: https://github.com/npm/npm/pull/15900

**Comment by briandipalma** [comment] 2017-09-26 10:30
This makes monorepos nicer to work with when using npm. With npm 4 and yarn a change to a local dependency means you have to reinstall. You can link but it's nice to get the same behaviour out of the box with all your dependencies.

**Comment by webmobiles** [comment] 2017-09-26 10:36
@BYK  when i install "yarn global create-react-native-app"  and npm5 installed does not work to create projects, then i downgrade  to v4: 
 `npm install -g npm@4.6.1` , and then:
` npm -g install create-react-native-app`

but when i create  the project:

`create-react-native-app myproj`

yarn is called, yarn works underhood npm version ? that is my question , about yarn and npm5 or npm4 together, thanks

**Comment by BYK** [comment] 2017-10-20 18:04
We do not have plans for implementing this for now so closing the issue.

@webmobiles I cannot figure out what the issue might be from your comment but it doesn't sound related to this issue so feel free to file a new issue with more details about how to reproduce it.

**Closed by BYK** 2017-10-20 18:04 UTC
Labels: cat-compatibility
