### ISSUE TITLE
Yarn workspace doesn't respect uniqueness of peerDependencies

### ISSUE THREAD

**Issue by gavrix** [yarnpkg/yarn#8113] opened 2020-05-11 04:06 UTC
### Bug description
Yarn seems to treat peerDependencies as regular dependencies when workspace mode. This happens for both hoisted and nohoisted modules. 

In simplest workspaces setup with workspaces: ''alpha", "beta", "gamma", "delta"
master package.json
```
{
    "name": "yarn-demo",
    "private": true,
    "workspaces": {
        "packages": [            
            "alpha",
            "beta",
            "gamma",
            "delta"
        ]
    }
}
```

alpha:
```
{
    "name": "alpha",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "react": "~16.13.1",
        "react-native": "~0.61.5"
    }
}
```

beta: 
```
{   
    "name": "beta",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "react": "16.13.1",
        "react-native": "0.61.5"
    }
}
```

gamma: 
```
{
    "name": "gamma",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "react": "^16.13.1",
        "react-native": "^0.62.2",
        "react-native-svg": "^12.1.0"
    }
}
```

delta:
```
{
    "name": "delta",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "react": "16.13.1",
        "react-native": "0.61.5",
        "react-native-svg": "12.1.0"
    }    
}
```

**Command**

```sh
yarn install
```

**What is the current behavior?**
yarn install in this repo installs a copy of react-native _inside_ `react-native-svg`: 

```
➜  yarn-debug find ./ -regex '.*react-native/package.json'
.//beta/node_modules/react-native/package.json
.//delta/node_modules/react-native/package.json
.//delta/node_modules/react-native-svg/node_modules/react-native/package.json
.//gamma/node_modules/react-native/package.json
.//alpha/node_modules/react-native/package.json
```

**What is the expected behavior?**
`react-native` is a peer dependency of react-native-svg (with version match "*" — _any_ version) and isn't supposed to be installed into react-native-svg/node_modules accorrding to https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies

> Having a peer dependency means that your package needs a dependency that is the same exact dependency as the person installing your package.

**Environment**

- Node Version: `v13.2.0`
- Yarn v1 Version: `1.22.4` 
- OS and version: MacOS 10.15.4

**Comment by jayphelps** [comment] 2020-09-22 19:59
Was just bit by this. Are you also using `nohoist` in your root package.json? If so, I believe it's a duplicate of #5520. As soon as I stopped using nohoist this problem went away for me; though the other problems I had that nohoist was avoiding came back of course.

**Comment by merceyz** [comment] 2021-01-02 18:39
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 18:39 UTC
