### ISSUE TITLE
Yarn stuck at upgrade-interactive

### ISSUE THREAD

**Issue by s-bauer** [yarnpkg/yarn#6367] opened 2018-09-07 07:50 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I create a new folder, open a command prompt, run`yarn init` and install an outdated version of a package. E.g.
`yarn add glob@7.1.2`. Then I try to upgrade the package using `yarn upgrade-interactive --latest`. It detects that the `glob` package is outdated, so I select it and hit Enter. Then it shows `? Choose which packages to update. glob@7.1.3` and is stuck. It does not do anything!

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
The `upgrade-interactive` command shall update the packages and package.json.

**Please mention your node.js, yarn and operating system version.**
Windows 10 - 1709 - 16299.611
Yarn v1.11.0-20180905.1625 (tried it with the latest stable release aswell)
Node 10.10.0 (Doesn't work with latest LTS either)

The upgrade-interactive command worked a few weeks ago. I didn't change anything, but it stopped working. Please let me know when you need any additional information. Thanks!

**Comment by yyynnn** [comment] 2018-09-14 10:48
Same here any version form 1.7 on win7

**Comment by s-bauer** [comment] 2018-09-21 09:11
@torifat Did you have to time to take a look at this? It's really annoying!

**Comment by bkniffler** [comment] 2018-10-18 19:00
Hey there, I've just done `npm i -g yarn@1.12.0` and it seems to work.

**Comment by s-bauer** [comment] 2018-10-19 07:30
@bkniffler Nope, does not seem to work for me! I tried yarn@1.12.0 and yarn@1.13.0 and both get stuck at the upgrade-interactive command!

**Comment by alexdevero** [comment] 2018-10-30 08:02
Can confirm that yarn get stuck when running upgrade-interactive.

Yarn: 1.12.1
Node: v11.0.0

**Comment by rally25rs** [comment] 2018-11-05 13:15
Closing as duplicate of #5949 
Let's continue the discussion there.

**Closed by rally25rs** 2018-11-05 13:15 UTC
Labels: triaged
