### ISSUE TITLE
official yarn tarball generates lots of warnings when unpacked with GNU tar

### ISSUE THREAD

**Issue by jokeyrhyme** [yarnpkg/yarn#1140] opened 2016-10-17 04:45 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

1. follow "alternative" installation instructions: https://yarnpkg.com/en/docs/install

2. download the tarball: https://yarnpkg.com/latest.tar.gz

3. extract the tarball with `tar zvxf` on ArchLinux

4. terminal output includes hundreds, maybe thousands, of occurrences of this warning output:

> tar: Ignoring unknown extended header keyword 'SCHILY.dev'
> tar: Ignoring unknown extended header keyword 'SCHILY.ino'
> tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

After some research it appears that the official yarn tarball is produced on macOS with BSD tar, and this results in additional metadata being created that cause GNU tar to output warnings:

- https://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt

As macOS ships with both (BSD) `tar` and `gnutar`, perhaps future tarballs can be made using GNU tar?

**What is the expected behavior?**

The output from `tar zxvf` should be similar between macOS and Linux, at least as far as not generating so many Linux-specific warnings.

**Please mention your node.js, yarn and operating system version.**

`yarn --version`
> 0.15.1

`node --version`
> v6.8.1

`npm --version`
> 3.10.9

`uname -a`
> Linux hellmouth 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux

`tar --version`
> tar (GNU tar) 1.29

**Comment by Daniel15** [comment] 2016-10-17 05:11
Duplicate of #770. This is due to the latest tarball being built on Mac OS, which by default uses BSD `tar` rather than GNU `tar`. It was built on Mac OS due to a last minute change needing to be made to the tarball.

For future releases, they'll all be built on Linux, so we won't encounter this issue.

Closing as a duplicate of #770. Thank you for trying Yarn! 😄

**Closed by Daniel15** 2016-10-17 05:11 UTC
Labels: install issue, linux

**Comment by jokeyrhyme** [comment] 2016-10-17 05:12
Doh! I searched for "macos bsd gnu tar" (without quotes) and didn't find the other issues.

**Comment by Daniel15** [comment] 2016-10-17 05:18
No worries, the title of the other issue wasn't very obvious, I only knew about it because I remembered triaging the issue 😄
