### ISSUE TITLE
*feature* yarn should give useful error message when package.json has a typo/error

### ISSUE THREAD

**Issue by rafidude** [yarnpkg/yarn#1550] opened 2016-10-29 15:40 UTC
Useful error messages will help!

I missed a comma after one of the elements in package.json file. "yarn start" did not point that issue.

$ yarn start
yarn start v0.16.1
error An unexpected error occured, please open a bug report with the information provided in "/Users/es/play/yarn/yarn-error.log".

Where as "npm start" gave the following useful error message:
$ npm start
....
npm ERR! Failed to parse json
npm ERR! Unexpected token 's' at 7:4
npm ERR!   "scripts":{
npm ERR!    ^
npm ERR! File: /Users/es/play/yarn/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
....

**Comment by wyze** [comment] 2016-10-29 23:59
This is duplicate of #1229 and was fixed in #1424. Is available on master and will be in the next release.

**Closed by wyze** 2016-10-29 23:59 UTC
