### ISSUE TITLE
yarn global add @angular/cli fails with error EPERM: operation not permitted on rename ng.cmd.cmd

### ISSUE THREAD

**Issue by saravvij** [yarnpkg/yarn#2924] opened 2017-03-15 05:34 UTC
**Problem Summary:** I am getting below error when I try to install @angular/cli package at global level.
**`Error: error An unexpected error occurred: "EPERM: operation not permitted, rename 'C:\\dev\\nodejs\\ng.cmd.cmd
[yarn_error.txt](https://github.com/yarnpkg/yarn/files/843506/yarn_error.txt)
' -> 'C:\\dev\\nodejs\\ng.cmd'".`**

**Environment:**
c:\>node -v
v7.7.2

c:\>yarn info
yarn info v0.21.3

Operation System: Windows 7 Pro, SP1
Antivirus: McAfee

**Steps to reproduce:**
1. Install @angular/cli 
2. C:\>yarn global add @angular/cli
yarn global v0.21.3
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@angular/tsc-wrapped@4.0.0-rc.2" has unmet peer dependency "typescript@^2.1.5".
warning "@angular/compiler@4.0.0-rc.3" has unmet peer dependency "@angular/core@4.0.0-rc.3".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "@angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "@angular/compiler-cli@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "@angular/core@^2.3.1 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "@angular/tsc-wrapped@^0.5.0 || >=4.0.0-beta <5.0.0".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "typescript@^2.0.2".
warning "@ngtools/webpack@1.2.13" has unmet peer dependency "webpack@^2.2.0".
warning "extract-text-webpack-plugin@2.0.0" has unmet peer dependency "webpack@^2.2.0".
warning "@angular/core@4.0.0-rc.3" has unmet peer dependency "rxjs@^5.0.1".
warning "@angular/core@4.0.0-rc.3" has unmet peer dependency "zone.js@^0.7.2".
warning "@angular/compiler-cli@4.0.0-rc.3" has unmet peer dependency "typescript@^2.0.2".
warning "@angular/compiler-cli@4.0.0-rc.3" has unmet peer dependency "@angular/compiler@4.0.0-rc.3".
warning "@angular/compiler-cli@4.0.0-rc.3" has unmet peer dependency "@angular/core@4.0.0-rc.3".
warning "less-loader@2.2.3" has unmet peer dependency "less@^2.3.1".
warning "karma-webpack@2.0.2" has unmet peer dependency "webpack@^1.1.0 || ^2 || ^2.1.0-beta.0 || ^2.2.0-rc.0".
warning "html-webpack-plugin@2.28.0" has unmet peer dependency "webpack@1 || ^2 || ^2.1.0-beta || ^2.2.0-rc".
warning "sass-loader@4.1.1" has unmet peer dependency "node-sass@^3.4.2 || ^4.0.0".
warning "sass-loader@4.1.1" has unmet peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta || ^1.12.6".
warning "url-loader@0.5.8" has unmet peer dependency "file-loader@*".
warning "stylus-loader@2.5.1" has unmet peer dependency "stylus@>=0.52.4".
warning "webpack-dev-server@2.3.0" has unmet peer dependency "webpack@^2.2.0".
warning "tsickle@0.21.5" has unmet peer dependency "typescript@^2.1.0".
warning "webpack-dev-middleware@1.10.1" has unmet peer dependency "webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0".
[4/4] Building fresh packages...
success Installed "@angular/cli@1.0.0-rc.2" with binaries:
      - ng
error An unexpected error occurred: "EPERM: operation not permitted, rename 'C:\\dev\\nodejs\\ng.cmd.cmd' -> 'C:\\dev\\nodejs\\ng.cmd'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\abcd6oo\\AppData\\Local\\Yarn\\config\\global\\yarn-error
.log".
[yarn_error.txt](https://github.com/yarnpkg/yarn/files/843509/yarn_error.txt)

info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by charpeni** [comment] 2017-03-15 19:50
It seems like an installation/rights issue with your nodejs and not related to yarn.

Does it work with `npm install -g @angular/cli` ?

Everything works fine for me for both commands on Windows 10, Node 7.7.1, Yarn 0.21.3.

**Comment by saravvij** [comment] 2017-03-15 20:29
npm install never works on my system unless I kill mcAfee.
npm install -g @angular/cli

**Comment by charpeni** [comment] 2017-03-16 23:18
Does it work with Yarn if you stop McAfee and run the terminal with Administrator rights?

**Comment by claycephas** [comment] 2017-04-04 17:18
I get a permission error when installing globally on Windows 10. Looks like it is trying to write to the install directory instead of 
```
PS C:\> yarn global add tslint                                                                                                                              
yarn global v0.21.3                                                                                                                                         
warning No license field                                                                                                                                    
[1/4] Resolving packages...                                                                                                                                 
[2/4] Fetching packages...                                                                                                                                  
[3/4] Linking dependencies...                                                                                                                               
warning "tsutils@1.4.0" has unmet peer dependency "typescript@>=2.0.0 || >=2.0.0-dev || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev".                         
warning "tslint@5.0.0" has unmet peer dependency "typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev".                          
[4/4] Building fresh packages...                                                                                                                            
success Installed "tslint@5.0.0" with binaries:                                                                                                             
      - tslint                                                                                                                                              
warning No license field                                                                                                                                    
error An unexpected error occurred: "EPERM: operation not permitted, open 'C:\\Program Files (x86)\\nodejs\\tslint.cmd'".                                   
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\canders2\\AppData\\Local\\Yarn\\config\\global\\yarn-
error.log".                                                                                                                                                 
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.                                                                     
PS C:\>                                                                                                                                                     
```

Shouldn't these files be written to `C:\Users\<username>\AppData\Local\Yarn\.bin` since that is configured in the windows PATH user variable?

**Comment by saravvij** [comment] 2017-04-04 17:29
I retried few times, and it works fine now. I didn't kill mcAfee.

**Comment by arcanis** [comment] 2017-04-28 17:24
This issue does seem like related to your environment rather than to Yarn itself, so I'm going to close it for triage.

**Closed by arcanis** 2017-04-28 17:24 UTC

**Comment by claycephas** [comment] 2017-04-29 23:26
@arcanis are you saying that yarn will still require admin prompt when installing global packages on windows? If it writes to `C:\Users\<username>\AppData\Local\Yarn\.bin`, it shouldn't require an elevated admin prompt.

**Comment by arcanis** [comment] 2017-05-04 09:17
No, we shouldn't be requiring elevated rights when installing global packages, but this issue seems to have been caused by McAfee, right?

**Comment by saravvij** [comment] 2017-05-04 16:46
That's right. I had to disable McAfee to successfully install it.

**Comment by kingsleykbc** [comment] 2018-04-28 05:47
Run as Administrator
