### ISSUE TITLE
Using 2 versions of the same package gives an error for scoped packages

### ISSUE THREAD

**Issue by rramaa** [yarnpkg/yarn#5204] opened 2018-01-10 11:26 UTC
#Bug

**Current Behavior**

When using ```yarn add @storybook/react-new@npm:@storybook/react@3.3.7``` yarn gives the following error:

`error Received malformed response from registry for undefined. The registry may be down.`

`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Expected Behavior**

yarn should install the specified version of storybook/react in storybook/react-new folder in `node_modules` as it does with non scoped packages

Node Version: v8.9.0

Yarn Version: v1.3.2

OS Version: MacOS 10.13.2

**Comment by Simek** [comment] 2018-01-10 16:33
I'm not sure what exactly you would like to achieve by running that command. Could you provide working `npm install` version or that mentioned in **Expected Behaviour** `yarn add` for non-scoped packages?

I assume that you expect similar behaviour as executing
`npm i @storybook/react@^3.3.7 --prefix node_modules@storybook/react-new`
command, right?

**Comment by rramaa** [comment] 2018-01-10 18:05
I ran the command ```yarn add react-old@npm:react@15.5.4``` and yarn installed react version 15.5.4 which was accessible by requiring ```react-old```

I guess yarn is splitting the package name by ```@``` and using the first index as the package name. In the case of scoped components its returning undefined for package name

In a way I am trying to issue the specified npm command but that won't solve the problem in my case. Yarn makes an entry in package.json as ```"custom-package-name": "npm:package-name@version"``` and on issuing ```yarn``` command it installs the specified version of the package in the package directory specified. ```npm i @storybook/react@^3.3.7 --prefix node_modules/@storybook/react-new``` won't provide the same functionality for me

**Comment by rally25rs** [comment] 2018-01-15 13:43
Manually adding it to the package.json file also fails:

```
  "dependencies": {
    "@storybook/react-new": "npm:@storybook/react@3.3.7"
  }
```

```
~/Projects/yarn-test 🐒   yarn
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by rally25rs** [comment] 2018-01-15 13:45
Just noticed #4353 is a duplicate of this.

**Closed by rally25rs** 2018-01-15 13:45 UTC
Labels: cat-bug, triaged
