### ISSUE TITLE
Create-react-app not working with yarn

### ISSUE THREAD

**Issue by justinhessdev** [yarnpkg/yarn#3575] opened 2017-06-04 22:02 UTC
yarn version -- v0.24.6
node version - v6.10.1
MacOS Sierra - 10.12.5

From the terminal:

```
JUser-MBP1:Projects juser$ create-react-app todo-app
Creating a new React app in /Users/juser/Desktop/Projects/todo-app.

Installing packages. This might take a couple minutes.
Installing react-scripts...

yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@timer%2fdetect-port: Could not authenticate juser".
info If you think this is a bug, please open a bug report with the information provided in "/Users/juser/Desktop/Projects/todo-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
yarnpkg add --dev --exact react-scripts failed
```

yarn-error.log:

```
Arguments: 
  /Users/juser/.nvm/versions/node/v6.10.1/bin/node /Users/juser/.yarn/bin/yarnpkg add --dev --exact react-scripts

PATH: 
  /Users/juser/.yarn/bin:/Users/juser/.nvm/versions/node/v6.10.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin

Yarn version: 
  0.24.6

Node version: 
  6.10.1

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "todo-app",
    "version": "0.1.0",
    "private": true
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/@timer%2fdetect-port: Could not authenticate juser
      at Request.params.callback [as _callback] (/Users/juser/.yarn/lib/yarn-cli.js:56255:18)
      at Request.self.callback (/Users/juser/.yarn/lib/yarn-cli.js:107854:22)
      at emitTwo (events.js:106:13)
      at Request.emit (events.js:191:7)
      at Request.<anonymous> (/Users/juser/.yarn/lib/yarn-cli.js:108837:10)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:188:7)
      at IncomingMessage.<anonymous> (/Users/juser/.yarn/lib/yarn-cli.js:108757:12)
      at IncomingMessage.g (events.js:291:16)
      at emitNone (events.js:91:20)
      at IncomingMessage.emit (events.js:185:7)
```

I installed yarn via Homebrew-- `brew install yarn` -- did not work
Then uninstalled/reinstalled via `curl -o- -L https://yarnpkg.com/install.sh | bash` -- did not work

When I uninstall Yarn, create react app works via npm/node

**Comment by arcanis** [comment] 2017-06-05 17:40
I can't reproduce this issue - do you also have it if you try to run `yarn add @timer/detect-port`?

**Comment by grahamb** [comment] 2017-06-06 23:41
I can reproduce this as well on macOS 10.12.4, yarn 0.24.6 and both Node 6.10.1 and 8.0.0.

```
 ~/code/sfu > create-react-app cra                                                                                                                                                                                          
Creating a new React app in /Users/grahamb/code/sfu/cra.

Installing packages. This might take a couple minutes.
Installing react, react-dom, and react-scripts...

yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@timer%2fdetect-port: Could not authenticate grahamb".
info If you think this is a bug, please open a bug report with the information provided in "/Users/grahamb/code/sfu/cra/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Aborting installation.
  yarnpkg add --exact react react-dom react-scripts has failed.

Deleting generated file... package.json
Deleting generated file... yarn-error.log
Deleting cra / from /Users/grahamb/code/sfu
Done.


 ~/code/sfu > cd test
 ~/code/sfu/test > yarn add @timer/detect-port
yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@timer%2fdetect-port: Could not authenticate grahamb".
info If you think this is a bug, please open a bug report with the information provided in "/Users/grahamb/code/sfu/test/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by arcanis** [comment] 2017-06-07 10:21
Thinking about it, I think it's a duplicate of #1952. @BYK is working on it, we should ship a fix in the next minor release, possibly patch.

Going to close this one as a duplicate, but thanks for the report :)

**Closed by arcanis** 2017-06-07 10:21 UTC
Labels: needs-repro-script

**Comment by BYK** [comment] 2017-06-07 15:21
@grahamb and @justinhessdev can you tell us whether you have an `auth=` line in your `npmrc` files? (please do not share the value since it contains very sensitive info about your npm account)

**Comment by grahamb** [comment] 2017-06-07 17:28
@BYK Yes, I do have `auth=` in my .npmrc file.

**Comment by aviram83** [comment] 2017-06-14 07:23
@grahamb thanks for the tip, I had same issue and when I have delete the line everything start to flow

**Comment by amerbdx** [comment] 2018-02-28 14:29
I experiences the yarn start error on 4  different laptops running Ubuntu and resolved it using these steps.
The underlying issue was that the yarn path was set incorrectly. 
If you have this error then you will see a yarn-error.log file in you project directory rather then a normal yarn.log file.
But if you reinstall Yarn on Ubuntu, it will also CORRECT Your React * path to yarn and this error. 

Here the steps:

	1- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
	2- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
	3- sudo apt-get update && sudo apt-get install yarn
	4- sudo apt-get upgrade
	- Then Reboot/Restart your System

-- After you did these STEPS, Go To Your Project and BUILD & START Your Yarn:
	1. yarn bulid
	2. yarn start

Now, after you created a new 'React' Project, you should see the (( yarn.lock )) file in your project folder!

			Then start with:
	1.		yarn build
	2.		yarn start

**Comment by Cerebrume** [comment] 2018-05-22 08:46
@amerbdx That worked for me. Thank you so much!
