### ISSUE TITLE
yarn <invalid command> links to 404.

### ISSUE THREAD

**Issue by kitsunde** [yarnpkg/yarn#1125] opened 2016-10-16 14:13 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```bash
$ yarn gloval add phantomjs
yarn gloval v0.15.1
error Command "gloval" not found.
info Visit http://yarnpkg.com/en/docs/cli/gloval for documentation about this command.
```

**What is the expected behavior?**

It shouldn't auto link to the web for commands yarn don't actually have.

**Please mention your node.js, yarn and operating system version.**

```bash
$ yarn --version
0.15.1
$ node --version
v6.3.1
$ sw_vers -productVersion
10.12
```

**Comment by wyze** [comment] 2016-10-16 15:27
Duplicate of #664 and was fixed with https://github.com/yarnpkg/yarn/pull/810. Just need to get a new release cut.

**Closed** 2016-10-16 17:00 UTC
