### ISSUE TITLE
can't find nvm's node

### ISSUE THREAD

**Issue by yyjazsf** [yarnpkg/yarn#1976] opened 2016-11-22 03:06 UTC
**What is the current behavior?**
I has `nvm install v6.9.1` and node is in path
but when  ` brew install yarn` it also execute `brew install node`
**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
nvm install v6.9.1
brew install yarn
```
**What is the expected behavior?**
if node in path,don't install it
**Please mention your node.js, yarn and operating system version.**
node v6.9.1
OSX 10.11.6

**Comment by torifat** [comment] 2016-11-22 06:00
Duplicate of #1116

**Closed by torifat** 2016-11-22 06:00 UTC
