### ISSUE TITLE
Feature request: Scripting api

### ISSUE THREAD

**Issue by doug-wade** [yarnpkg/yarn#1031] opened 2016-10-14 00:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Request a feature!

**What is the current behavior?**
```
» yarn add yarnpkg 
» node
> const yarn = require('yarnpkg');
Error: Cannot find module 'yarnpkg'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:14
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
```
» yarn add yarnpkg 
» node
> const yarn = require('yarnpkg');
> yarn.add('yarnpkg');
// yarnpkg installed (a)synchronously
```

**Please mention your node.js, yarn and operating system version.**
```
doug-UX301LAA packages/kniffiti ‹master*› » node -v                               
v6.8.0
doug-UX301LAA packages/kniffiti ‹master*› » yarn --version
0.15.1
doug-UX301LAA packages/kniffiti ‹master*› » lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**Comment by FLGMwt** [comment] 2016-10-14 02:02
This has been added as an RFC here: https://github.com/yarnpkg/rfcs/issues/6 : )

**Comment by Daniel15** [comment] 2016-10-14 02:13
Closing this as a duplicate of https://github.com/yarnpkg/rfcs/issues/6. Thank you for trying Yarn!

**Closed by Daniel15** 2016-10-14 02:13 UTC

**Comment by doug-wade** [comment] 2016-10-14 09:20
Hooray! Thanks
