### ISSUE TITLE
[Bug] EPERM: operation not permitted, open '%UserProfile%\.yarnrc'

### ISSUE THREAD

**Issue by NatoBoram** [yarnpkg/yarn#8599] opened 2021-03-19 21:46 UTC
- [ ] I'd be willing to implement a fix

**Describe the bug**

> A clear and concise description of what the bug is. A bug is **unintended**. A feature not being
implemented is **not a bug**, and your issue may be closed for misleading labeling.

When the `%UserProfile%\.yarnrc` file is set to "hidden", a permission error is thrown. This happens even if the command is run as administrator, which does not have permission problems.

**To Reproduce**

> The _minimal_ information needed to reproduce your issue (ideally a package.json with a single dep).
Note that bugs without minimal reproductions **will** be closed as non-actionable.
> 
> **IMPORTANT**: We **strongly** prefer reproductions that use Sherlock. Please check our documentation
for more information: https://yarnpkg.com/advanced/sherlock

<details>
  <summary>Reproduction</summary>

1. Set `%UserProfile%\.yarnrc` to "Hidden"
2. Run `yarn` in a project

</details>

**Screenshots**

> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/10495562/111845269-e6b80600-88da-11eb-8c52-e6087816f245.png)

**Environment if relevant (please complete the following information):**

 - Windows 10 Pro [64-bit]
 - v15.6.0
 - 1.22.5

**Additional context**

> Add any other context about the problem here.

**Comment by merceyz** [comment] 2021-03-19 21:49
Duplicate of https://github.com/yarnpkg/yarn/issues/8403

**Closed by merceyz** 2021-03-19 21:49 UTC
