### ISSUE TITLE
yarn add lockfile does not install dependency

### ISSUE THREAD

**Issue by ZachStoltz** [yarnpkg/yarn#2184] opened 2016-12-07 23:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
    `yarn add lockfile`
    `error Missing list of packages to add to your project.`
    `verbose Error: Missing list of packages to add to your project.
    at Object.<anonymous> (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/cli
/commands/add.js:17:13)
    at Generator.next (<anonymous>)
    at step (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-ru
ntime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/babel-runtime/
helpers/asyncToGenerator.js:35:14
    at F (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_modules/core-js/lib
rary/modules/_export.js:35:28)
    at Object.<anonymous> (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/node_mo
dules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/cli/command
s/add.js:29:18)
    at run (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/cli/index.js:263:1
8)
    at config.init.then (/usr/local/Cellar/yarn/0.17.10/libexec/lib/node_modules/yarn/lib/cli/i
ndex.js:409:12)`

**If the current behavior is a bug, please provide the steps to reproduce.**
run `yarn add lockfile` without supplying a specific version

**What is the expected behavior?**
The package should be installed and added to the dependency/ dev dependency object in package.json
**Please mention your node.js, yarn and operating system version.**
nodejs `v7.1.0`
yarn `v0.17.10`
Mac OSX El Capitan `10.11.6`

**Comment by torifat** [comment] 2016-12-08 09:59
Duplicate of #2112

**Closed by torifat** 2016-12-08 09:59 UTC
Labels: duplicate
