### ISSUE TITLE
yarn config set does not allow to set boolean false

### ISSUE THREAD

**Issue by NicBright** [yarnpkg/yarn#2434] opened 2017-01-12 08:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn config set strict-ssl false` sets it to string 'false' instead of boolean false. In consequence, 'false' seems to be treated as truthy and has no effect.

**If the current behavior is a bug, please provide the steps to reproduce.**
see http://stackoverflow.com/questions/41439008/how-do-you-set-boolean-values-with-yarn-config

**Expected behaviour**
The config value should have been set to boolean false.

**Comment by iredchuk** [comment] 2017-01-13 08:03
OK, this could also be a duplicate of #1237

**Closed** 2017-01-14 17:16 UTC
Labels: bug
