### ISSUE TITLE
Unnecessary bin is installed

### ISSUE THREAD

**Issue by keelii** [yarnpkg/yarn#4148] opened 2017-08-11 10:22 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```bash
➜  ~ npm install -g typescript
➜  ~ ls /usr/local/node/bin   
node  npm  npx  tsc  tsserver
npm uninstall -g http-server
➜  ~ yarn global add http-server
➜  ~ ls /usr/local/node/bin      
ecstatic  he  hs  http-server  node  npm  npx  opener
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
global bin `ecstatic`, `he`, `opener` is unnecessary

**Please mention your node.js, yarn and operating system version.**
```bash
# Ubuntu 16.04 LTS
➜  ~ node --version           
v8.1.4
➜  ~ npm --version            
5.3.0
➜  ~ yarn --version
0.27.5
➜  ~ yarn global bin
/usr/local/node/bin
```

**Comment by BYK** [comment] 2017-08-11 10:27
Hi @keelii, thanks for the report. I think this is a duplicate of #3824 so closing. Feel free to reopen if you disagree.

**Closed** 2017-08-11 10:28 UTC
