### ISSUE TITLE
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/xxx/Library/Caches/Yarn/npm-webpack-stream-3.2.0-d679c2f1f964b5abae4c1f29d5cb695115deec7b'".

### ISSUE THREAD

**Issue by jrean** [yarnpkg/yarn#1836] opened 2016-11-15 04:58 UTC
This bug happens now on both Linux and OsX.

- OsX
node v6.0.0
npm 3.8.8
yarn 0.17.0

- Linux
node 6.9.1
npm 3.10.8
yarn 0.17.0

I simply perform a `yarn install`

`package.json`
```
{
  "private": true,
  "scripts": {
    "prod": "gulp --production",
    "dev": "gulp watch"
  },
  "devDependencies": {
    "bootstrap-sass": "^3.3.7",
    "gulp": "^3.9.1",
    "jquery": "^3.1.0",
    "laravel-elixir": "^6.0.0-14",
    "laravel-elixir-webpack-official": "^1.0.2",
    "lodash": "^4.16.2"
  }
}
```

Error trace:
```
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/xxx/Library/Caches/Yarn/npm-webpack-stream-3.2.0-d679c2f1f964b5abae4c1f29d5cb695115deec7b'".
info If you think this is a bug, please open a bug report with the information provided in "/Volumes/data/code/fashion/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by jrean** [comment] 2016-11-15 06:16
Reverting to yarn `0.16.1` fixed my issue.
I hope the trace is helping.

**Comment by kossnocorp** [comment] 2016-11-15 07:36
Locking to `0.16.1` helped me too

**Comment by antongb** [comment] 2016-11-15 08:48
OsX
node v6.6.0
npm 3.10.8
yarn 0.16.1

after running npm uninstall -g yarn and npm i -g yarn@0.16.1 was getting the following error:

```
antons-MBP:yarn anton$ yarn
/Users/anton/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/bin/yarn.js:48
      throw err;
      ^

Error: ENOENT: no such file or directory, open '/Users/anton/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/updates/0.17.0/lib/cli/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.Module._extensions..js (module.js:564:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/anton/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/bin/yarn.js:40:22)

```

fixed by going to `/Users/anton/.nvm/versions/node/v6.6.0/lib/node_modules/yarn/bin/yarn.js` and changing `possibles.push('../updates/current/lib/cli/index.js');` to `possibles.push('../updates/0.16.1/lib/cli/index.js');`

**Comment by juliankrispel** [comment] 2016-11-15 08:57
:+1:  reverting to 0.16.1 fixed it for me thanks

**Comment by kostasmanionis** [comment] 2016-11-15 11:06
Or you could remove the `~/.yarn/.roadrunner.json` file after rollbacking.

**Comment by simonihmig** [comment] 2016-11-15 11:13
I can confirm this. Happens for me with a github dependency. Here is the error.log:
[yarn-error.txt](https://github.com/yarnpkg/yarn/files/591747/yarn-error.txt)

Reverting to 0.16.1 fixed this as well.

**Comment by kuntau** [comment] 2016-11-15 12:02
👍 reverting to 0.16.1 give no error

**Comment by matoilic** [comment] 2016-11-15 15:42
Same issue here with yarn 0.17. Reverting back to 0.16.1 and deleting `~/.yarn/.roadrunner.json` resolved the issue.

[yarn-error.txt](https://github.com/yarnpkg/yarn/files/592428/yarn-error.txt)

**Comment by derkjn** [comment] 2016-11-15 22:49
Same issue with yarn 0.17.2

**Comment by thomaschaaf** [comment] 2016-11-15 23:09
This is a duplicate of https://github.com/yarnpkg/yarn/issues/1834

**Closed** 2016-11-16 00:00 UTC
Labels: needs triage

**Comment by johannesschobel** [comment] 2019-07-18 09:03
this issue still occurs from time to time in the 16.x and 17.x version of yarn.. haven't found a reliable and reproducible way to demonstrate it. And even worse - haven't found a proper solution to fix / address this issue..

**Comment by zlocate** [comment] 2019-08-22 11:18
Use yarn at wsl debian and 2/3 installs had this error v1.17.3.
Sometimes helps purge yarn cache folder or run yarn as root (sudo)

**Comment by jomiojeda** [comment] 2019-10-09 07:54
Same happened here on v1.19.1
fixed after
`yarn cache clean`

**Comment by gitowiec** [comment] 2019-11-05 08:13
I tried @jomiojeda advice but to no avail :( 
I'm using Yarn 1.19.1 on Ubuntu 18.04.
@bestander This bug should be opened.

**Comment by kennethlynne** [comment] 2019-11-09 12:54
I'm having this issue, and `yarn cache clean` did not improve anything. Using yarn 1.19.1, node 10.15.3

**Comment by cyptus** [comment] 2019-12-10 12:23
got this issue when multiple agents were running builds at once and the cache directory was shared (AppData). Solved by changing the cache directory into the agents working directory.

**Comment by BlueRaja** [comment] 2020-01-07 21:04
It was a permissions issue for me.  Doing
```
sudo chown -R myUserName . ~/.config/
```
in the root of the project fixed it for me

**Comment by BlueRaja** [comment] 2020-01-07 22:21
`yarn cache clean` + deleting `node_modules` fixed it for me.  Importantly, note that in a monorepo doing `yarn install` seems to install _all_ the repos, so you need to delete _all_ the `node_module` directories (including the root)

**Comment by M4FFS** [comment] 2022-06-23 07:23
having this now

**Comment by 3h4x** [comment] 2023-06-09 07:15
hitting this very often on our gh runner
yarn 1.22.19
node v20.0.0

**Comment by malmo-east** [comment] 2023-10-15 21:04
Still have this issue. Using yarn 1.22.19 with node v18.17.1 on Mac

**Comment by sorenwacker** [comment] 2023-11-02 13:24
Same on `5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` yarn 1.22.19
