### ISSUE TITLE
"yarn version" prints Yarn's version

### ISSUE THREAD

**Issue by mouchtaris** [yarnpkg/yarn#2547] opened 2017-01-24 17:51 UTC
**Do you want to request a *feature* or report a *bug*?**
According to the docs, this is a bug.

**What is the current behavior?**
`yarn version` prints `0.19.1`

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn version`

**What is the expected behavior?**
According to the published documentation ( https://yarnpkg.com/en/docs/cli/version ), `yarn version` is supposed to manage the package's version.

**Please mention your node.js, yarn and operating system version.**
`node --version` -> `v7.4.0`
`yarn --version` -> `0.19.1`
System: Archlinux, YARN installed from AUR, built with this script https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yarn

**EDIT 2017-01-25**: Fix typo in node version output

**Comment by markstos** [comment] 2017-01-24 21:16
I confirmed that this behavior does not match the documentation.

**Comment by ljharb** [comment] 2017-01-24 21:38
(quick nit: `node --version` should output `v7.4.0` there, no dot after the "v")

**Comment by mouchtaris** [comment] 2017-01-25 10:12
Thank you @ljharb, I corrected the typo.

**Comment by siebertm** [comment] 2017-01-25 13:43
As a workaround, I used `npm version` for now, since I needed to do a release...

**Comment by jogjayr** [comment] 2017-01-25 20:08
Duplicate of https://github.com/yarnpkg/yarn/issues/2491

**Comment by bestander** [comment] 2017-01-26 15:58
duplicate

**Closed by bestander** 2017-01-26 15:58 UTC
