### ISSUE TITLE
mac

### ISSUE THREAD

**Issue by percylim** [yarnpkg/yarn#8532] opened 2021-01-01 06:19 UTC
**Which operating system are you using:**

**Please describe the steps you took when trying to install Yarn and what went wrong:**

**Comment by percylim** [comment] 2021-01-01 06:23
cannot run yarn command e.g. yarn --version or yarn build etc after brew install -g yarn, a error of "Cannot find module '/Users/fannweilim/.yarn/releases/yarn-1.22.10.cjs" dispaly

**Comment by merceyz** [comment] 2021-01-01 23:36
Duplicate of https://github.com/yarnpkg/yarn/issues/8532

**Closed by merceyz** 2021-01-01 23:36 UTC
