### ISSUE TITLE
Potential bug  - missing node_modules/.bin directory, after yarn add <package>

### ISSUE THREAD

**Issue by ORESoftware** [yarnpkg/yarn#2135] opened 2016-12-04 08:14 UTC
`mkdir foo && cd foo && yarn add <package>`

will create three items in foo:

```
foo/
  package.json
  node_modules/
  yarn.lock
```

however if we cd into node_modules

`cd node_modules && ls -a`

there does not seem to be a .bin directory, which normally houses the command line utilities.

Is this an expected omission or is this a bug?

On the other hand, if we did 

`mkdir foo && cd foo && npm install <package>`

there would be a 

./node_modules/.bin directory present

**Comment by wyze** [comment] 2016-12-04 15:02
If the package doesn't provide an executable, then the directory wouldn't be created until one does. In the issue template it asks to provide steps to reproduce and versions of Node, OS, Yarn. So please do that, and give exact steps to reproduce. Like `yarn add left-pad` instead of `yarn add <package>`.

**Comment by ORESoftware** [comment] 2016-12-04 19:32
Sure will do, try this:

`mkdir foo && cd foo && yard add suman-home`

when I ran this, I did not get a` ./foo/node_modules/.bin` directory

but when I do

`mkdir foo && cd foo && npm install suman-home`

I do get a `./foo/node_modules/.bin` directory

**Comment by wyze** [comment] 2016-12-04 20:16
I see. That package itself doesn't expose an executable but it's dependencies do. You will want to wait for #2053 to land.

Going to close this as duplicate of #760.

**Closed by wyze** 2016-12-04 20:16 UTC
Labels: needs clarification

**Comment by ORESoftware** [comment] 2016-12-04 20:35
Thanks I understand the issue, appreciate your work
