### ISSUE TITLE
yarn version only outputs version of yarn installed

### ISSUE THREAD

**Issue by jogjayr** [yarnpkg/yarn#2539] opened 2017-01-24 02:40 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

    $ yarn version
    0.19.1
    

`yarn version` writes the currently installed version of yarn to standard out

**If the current behavior is a bug, please provide the steps to reproduce.**

  1. Clone https://github.com/jogjayr/yarn-version-bug
  2. `cd yarn-version-bug`
  3. `yarn version`
  4. `yarn version --new-version 5.0.0`

**What is the expected behavior?**

For step 3, it should start an interactive session to set the new version
For step 4, it should set the version in package.json to 5.0.0

These behaviors are documented here: https://yarnpkg.com/en/docs/cli/version

**Please mention your node.js, yarn and operating system version.**

    $node -v
    v7.4.0

    $yarn --version
    0.19.1

MacOS Sierra 10.12.2

**Comment by Daniel15** [comment] 2017-01-24 06:08
Duplicate of #2491.

**Closed by Daniel15** 2017-01-24 06:08 UTC
