### ISSUE TITLE
Workspaces with "nohoist": ["**"] fails with ENOENT error

### ISSUE THREAD

**Issue by ryanashcraft** [yarnpkg/yarn#6988] opened 2019-02-01 20:17 UTC
**What is the current behavior?**

On a large monorepo project with 5+ packages, adding `"nohoist": ["**"]` to the root package.json results in `ENOENT` errors, for example:

```
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/Users/ryanashcraft/Work/javascript/packages/eslint-config-amplitude-base/node_modules/table/node_modules/lodash'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/ryanashcraft/Work/javascript/yarn-error.log".
```

`/Users/ryanashcraft/Work/javascript/packages/eslint-config-amplitude-base/node_modules/table/node_modules` is an empty directory.

**If the current behavior is a bug, please provide the steps to reproduce.**

This project is closed-source, so I can't provide a link. Happy to provide more information about the project if helpful.

**What is the expected behavior?**

The install succeeds, and all packages are not hoisted to the root repo directory.

**Please mention your node.js, yarn and operating system version.**

yarn: v1.13.0
node: v10.15.0
macOS: 10.14.2

**Related issues.**

I decided to make a separate issue for this as it relates specifically to configuring `"nohoist": ["**"]`:

https://github.com/yarnpkg/yarn/issues/6042
https://github.com/yarnpkg/yarn/issues/5421
https://github.com/yarnpkg/yarn/issues/5601
https://github.com/yarnpkg/yarn/issues/4563

**Comment by timini** [comment] 2019-02-04 10:15
Also experiencing this

**Comment by SuaYoo** [comment] 2019-03-18 18:44
I'm running into this issue as well.  I've created a simple reproduction repo here: https://github.com/SuaYoo/yarn-workspace-nohoist-issue

Notes:
- Narrowed down from my real-life dependencies to `css-loader` in package b using half splitting.  However, the actual file/directory that was missing changed throughout the process -- from `/packages/b/node_modules/json5` to `/packages/b/node_modules` to finally `/packages/b/node_modules/css-loader`.
- Cannot reproduce when major versions of `css-loader` are the same (e.g. no issues on install when both package a and b have `"css-loader": "^1.0.0"` specified.)
- Cannot reproduce when package a does not reference package b in `dependencies`/`devDependencies`.
- Cannot reproduce when package a has `"nohoist": ["css-*"]` or `"nohoist": ["css-loader"]`.

**Comment by matthargett** [comment] 2019-04-12 21:17
We have the same issue, but with the acorn package. My main problem here is that the error message is unacceptably obtuse:
```error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/mnt/c/Users/matt/workspace/hub/packages/hub-queries/node_modules/eslint-plugin-react/node_modules/acorn'".```

I was able to work around the problem by deleting my yarn.lock (also unnacceptable), and now I'm going to hand-edit my yarn.lock file. If the CLI could tell me I need to reconcile/remove differing versions of acorn, with line numbers, that would be very helpful.

**Comment by dizel3d** [comment] 2019-05-07 12:52
node 8.6.0, yarn 1.15.2. Got the same error.

**Comment by crubier** [comment] 2019-05-14 17:02
Same here

**Comment by sghoweri** [comment] 2019-05-20 12:16
We're having the exact same issue (already reported [here](https://github.com/bolt-design-system/bolt/issues/1176) -- any ideas on a potential workaround?

**Comment by grebenyuksv-preply** [comment] 2019-07-31 13:15
any updates on this?

**Comment by baflo** [comment] 2019-09-06 10:38
anything?

**Comment by diem98** [comment] 2019-09-09 07:17
same here

**Comment by arcanis** [comment] 2019-09-09 07:24
The `nohoist` setting is a workaround, and not a part of Yarn we plan to improve (it won't be part of the v2, since the hoisting mechanism will be very different due to PnP being used by default).

I'm willing to review and merge a PR that would fix the behaviour described in this issue, but I don't have the bandwidth to work on it myself while we're hard at work on the v2. Thanks for your understanding.

**Comment by paul-soporan** [comment] 2021-01-03 12:17
Closing as this won't happen anymore in the v2 where [installConfig.hoistingLimits](https://yarnpkg.com/configuration/manifest#installConfig.hoistingLimits) should be used instead of `noHoist`.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-03 12:17 UTC
Labels: triaged
