### ISSUE TITLE
Better error message for invalid package.json

### ISSUE THREAD

**Issue by vjeux** [yarnpkg/yarn#4561] opened 2017-09-27 19:38 UTC
Right now it says:

> error An unexpected error occurred: "/Users/vjeux/random/website/package.json: Unexpected token } in JSON at position 52".

But would be nice to display the actual line and `^^^` where the error is.

**Comment by BYK** [comment] 2017-09-27 23:37
Duplicate of #4493  so let's continue the discussion there.

Long story short, this is not easily doable right now because `JSON.parse()` in Node doesn't provide this information for some reason.

**Closed by BYK** 2017-09-27 23:37 UTC
