### ISSUE TITLE
Issue installing npm module firebase offline

### ISSUE THREAD

**Issue by pdot86** [yarnpkg/yarn#1449] opened 2016-10-25 17:34 UTC
**Issue:**
When using yarn install with an existing package.json that has a dependency of `firebase: "^3.5.2"` and passing the `--prefer-offline` or `--offline` flags it returns the error: 

> Couldn't find package "firebase" on the "npm" registry.

**More Info:**
I was trying to see how fast yarn was with cached packages, so I had previously installed the packages normally using the exact same package.json file with no issues. I then attempted to try with each of the offline flags and both get the same error. I confirmed that the package is indeed saved to the disk in the `~/.yarn-cache` directory in `~/.yarn-cache/npm-firebase-3.5.2`. Just to be clear yarn installs the packages just fine when neither of the offline flags are used.

**Environtment Info:**
OSX v10.11.16
nvm v0.32.1
node v6.5.0
npm v3.10.3
yarn v0.16.1

**Commands Used:**
`yarn --prefer-offline`
`yarn --offline`
`yarn install --prefer-offline`
`yarn install --offline`

**Full Output:**
yarn install v0.16.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "firebase" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by hpurmann** [comment] 2016-11-20 21:34
Does your project contain a `yarn.lock` file? That's likely the problem.

**Comment by torifat** [comment] 2016-11-20 22:02
@hpurmann thanks for testing. I have also tested on `0.17.6` (both macOS and Windows) and couldn't reproduce it. I'm closing it now. Please feel free to report back if you find it again. We will be happy to reopen it again.

**Closed by torifat** 2016-11-20 22:02 UTC
Labels: needs triage

**Comment by pdot86** [comment] 2016-12-19 22:18
Sorry I do not check this email often - yes that was the case. totally
goofed on that my bad.

**Comment by torifat** [comment] 2016-12-20 05:12
@pdot86 It's ok 😄
