### ISSUE TITLE
Tried "yarn create react-app neurolab" but installation aborted. Log attached

### ISSUE THREAD

**Issue by StvEsp** [yarnpkg/yarn#7546] opened 2019-09-12 22:18 UTC
node.js version v12.10.0 on Mac OS 10.14.6 (18G95)

[yarn-error.log](https://github.com/yarnpkg/yarn/files/3607623/yarn-error.log)

**Comment by paul-soporan** [comment] 2021-01-03 12:32
Closing as we can't reproduce this.

**Closed by paul-soporan** 2021-01-03 12:32 UTC
