### ISSUE TITLE
Yarn 1.9.2 really slow when adding packages

### ISSUE THREAD

**Issue by dericgw** [yarnpkg/yarn#6210] opened 2018-08-03 12:40 UTC
I believe there is a bug in 1.9.2. Yarn seemed to be working great until I upgraded and now it seems like it takes a few minutes to add any package whereas it used to only take about 30 seconds. Here is a video of a package being added so that you can see the behavior (sorry for the link, Github does not allow video uploads).

https://cl.ly/tS4U

Here is my machine info:
- macOS High Sierra 10.13.6
- 2017 Macbook Pro 2.9 GHz Intel Core i7 6 GB 2133 MHz LPDDR3
- Node 10.5.0
- Yarn 1.9.2

**Comment by oleblaesing** [comment] 2018-08-03 17:22
Yup, can confirm. Killing node_modules and clearing cache is a work around. I've used --verbose and it seems to run through each file in node_modules to check for differences.

**Comment by arcanis** [comment] 2018-08-03 18:08
Thanks for the report!

Duplicate of #6177, fixed by #6204 - it will be in the 1.9.3, which I'm in the process of releasing at the moment. I'll close this issue to avoid having to monitor multiple ones, please suscribe on #6177 🙂

**Closed by arcanis** 2018-08-03 18:08 UTC
Labels: triaged
