### ISSUE TITLE
yarn is not Deterministic

### ISSUE THREAD

**Issue by calidion** [yarnpkg/yarn#5262] opened 2018-01-21 16:59 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
`yarn.lock` updates every time `yarn install` executed.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

yarn.lock is not updated due to `yarn install`

**Please mention your node.js, yarn and operating system version.**

node : v8.9.1
yarn: 1.3.2
Ubuntu: 16.04.2

**Comment by GAumala** [comment] 2018-01-21 17:22
Hello could you please provide an example repo to reproduce this bug?

**Comment by calidion** [comment] 2018-01-21 18:33
@GAumala 

it seems every yarn.lock file is the same,
they updates every time yarn install is execute.

**Comment by GAumala** [comment] 2018-01-21 18:43
How is it updated? Could you please provide a diff?

**Comment by calidion** [comment] 2018-01-21 18:51
[a.txt](https://github.com/yarnpkg/yarn/files/1650061/a.txt)

**Comment by kaylieEB** [comment] 2018-01-29 18:01
hi @calidion this is the intended behavior. Yarn is supposed to update the lockfile when `package.json` changes to sync both files. It looks like `vig": "^1.0.0-rc"` was updated. The easy solution would be to commit the new lockfile if the change was intentional, otherwise remove that line from package.json.

**Comment by calidion** [comment] 2018-01-29 18:03
@kaylieEB 
this happens even when package.json is not changed!
it problem is nothing to do with package.json.

**Comment by kaylieEB** [comment] 2018-01-29 18:09
So i think what's happening is that you have a lockfile committed that is out of sync with package.json. This usually is a result of someone manually changing versions in package.json instead of using the `yarn upgrade` command. Can you try to commit those changes after the initial run of `yarn` and re-run yarn and see if there are any changes left in your working directory? If that's still happening then, that'd be a bug.

**Comment by calidion** [comment] 2018-01-29 18:47
currently

1.  `yarn upgrade` leads to failure:
```
error An unexpected error occurred: "expected manifest".
```

2.  `yarn install` leads to failure:
```
[02:46:21] Using gulpfile ~/Sites/openshift.com/vigor/gulpfile.js
[02:46:21] Starting 'sass'...
/home/eric/Sites/openshift.com/vigor/node_modules/strip-bom/index.js:4
		throw new TypeError('Expected a string, got ' + typeof x);
		^

TypeError: Expected a string, got object
    at module.exports.x (/home/eric/Sites/openshift.com/vigor/node_modules/strip-bom/index.js:4:9)
    at /home/eric/Sites/openshift.com/vigor/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:11:21
    at /home/eric/Sites/openshift.com/vigor/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

while `npm install` works find and it is testable with `npm test`.

**Comment by kaylieEB** [comment] 2018-01-29 19:01
So this is happening after 1) `rm -rf node_modules` 2) `yarn`? Can you post your package.json and lockfile?

**Comment by calidion** [comment] 2018-01-29 19:09
yes.

[yarn.lock.txt](https://github.com/yarnpkg/yarn/files/1674900/yarn.lock.txt)

[package.json.txt](https://github.com/yarnpkg/yarn/files/1674898/package.json.txt)
yes

**Comment by kaylieEB** [comment] 2018-01-29 19:23
Hm I'm not able to repro this with those two files, I was able to install without changing the lockfile. And that error message you posted above doesn't seem related to installation. I'll reopen in case others have better luck reproducing the issue.

**Comment by calidion** [comment] 2018-01-30 12:43
@kaylieEB 
can you successfully execute `yarn upgrade`?

**Comment by aiham** [comment] 2018-02-21 03:44
@kaylieEB I'm experiencing something similar. I've attached `package.json` and the original `yarn.lock` file. The following are my repro steps using a folder with no node_modules:

```sh
[14:22:57][/tmp/yarn-repro](master)$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > html-minifier-loader@1.4.0" has unmet peer dependency "html-minifier@*".
warning " > karma-electron-launcher@0.2.0" has unmet peer dependency "electron@>=1.3.1".
warning " > karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 17.76s.
[14:23:17][/tmp/yarn-repro](master)$ git diff > diff1.txt
[14:23:37][/tmp/yarn-repro](master)$ git add yarn.lock
[14:24:11][/tmp/yarn-repro](master)$ rm -rf node_modules/
[14:24:33][/tmp/yarn-repro](master)$ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
warning karma-jasmine-diff-reporter > karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning karma-jasmine-diff-reporter > karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning " > html-minifier-loader@1.4.0" has unmet peer dependency "html-minifier@*".
warning " > karma-electron-launcher@0.2.0" has unmet peer dependency "electron@>=1.3.1".
warning " > karma-jasmine@1.1.0" has unmet peer dependency "jasmine-core@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 25.05s.
[14:25:48][/tmp/yarn-repro](master)$ git diff > diff2.txt
```

The attached diff1.txt is a minor change to the yarn.lock file and diff2.txt is a major change to the yarn.lock that only happens after node_modules is deleted. I didn't expect the second `yarn` call to result in a different yarn.lock file. Shouldn't the first `yarn` call have made the diff2.txt change?

- [package.json.txt](https://github.com/yarnpkg/yarn/files/1742780/package.json.txt)
- [yarn.lock.txt](https://github.com/yarnpkg/yarn/files/1742781/yarn.lock.txt)
- [diff1.txt](https://github.com/yarnpkg/yarn/files/1742777/diff1.txt)
- [diff2.txt](https://github.com/yarnpkg/yarn/files/1742793/diff2.txt)

Thanks

**Comment by BYK** [comment] 2018-05-03 13:46
I do see the `success Saved lockfile.` message everytime I install even if the file contents don't change. This is a bit worrying. Can this be related to resolutions @kaylieEB?

**Comment by paul-soporan** [comment] 2021-01-02 21:42
Closing this as fixed in the v2 where it's impossible for the lockfile to randomly update.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-02 21:42 UTC
Labels: needs-repro-script, triaged
