### ISSUE TITLE
upgrade-interactive: broken legend

### ISSUE THREAD

**Issue by pronebird** [yarnpkg/yarn#3978] opened 2017-07-20 18:01 UTC
Current color legend is strange, even the color preferences.  

>"red"    : Patch Update Backward-compatible bug fixes 
 >"yellow" : Minor Update backward-compatibles features

1. Red should be breaking change - major. Yellow can be minor. Green - patch. Imagine semaphore.
2. Update from electron-mocha 3.x.x. -> 4.x.x is reported as patch (red), but is a major update.
3. Update from mapbox-gl 0.37.0  ->  0.38.0 is reported as minor, should be major update, versions starting with 0. are exceptional according to semver.
4. Update from eslint-plugin-flowtype  2.34.1  -> 2.35.0 reported as patch update (red), should be minor update.

**Comment by Anahkiasen** [comment] 2017-08-09 08:27
Can confirm I have the same issue, the legend and colors don't seem to make sense in 0.27.5

**Comment by CarlRosell** [comment] 2017-08-10 15:13
Can confirm this as well, duplicate of #3815?

**Comment by BYK** [comment] 2017-08-11 11:07
Closing as duplicate of #3815.

**Closed by BYK** 2017-08-11 11:07 UTC
