### ISSUE TITLE
Yarn GUI glitch on Windows PowerShell

### ISSUE THREAD

**Issue by VladimirDev93** [yarnpkg/yarn#4483] opened 2017-09-16 15:14 UTC
**Yarn version**
`yarn`: `v1.0.2`

**Do you want to request a *feature* or report a *bug*?**
`bug` / `glitch`

**What is the current behavior?**
Well, don't really know how to explain it, it's a **gui glitch** or a **bug**.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Open Windows `PowerShell` on `Windows 10 Pro x64 15063.608`.
2. Try to install a package. `yarn global add create-react-native-app` for example.
3. Then this happens.
![untitled](https://user-images.githubusercontent.com/12301022/30513292-418e34d0-9b01-11e7-8cf9-d2b60294f25b.png)

**What is the expected behavior?**
To not have those weird yellow blocks, but the info should be on one line, like when `npm` is installing modules.
 
**Please mention your node.js, yarn and operating system version.**
**Node.js** : `v8.5.0`,
**Yarn** : `v1.0.2`,
**Windows** : `Windows 10 Pro x64 15063.608`

P.S. When it finishes installing, the end result is ok, this only happens **during** the installation of packages.

**Comment by BYK** [comment] 2017-09-16 17:58
This should be fixed by #4317 looks like a duplicate of #2530 and #1222. Can you try with one of the latest nightlies and see if it is fixed there: https://yarnpkg.com/en/docs/nightly

**Comment by VladimirDev93** [comment] 2017-09-16 18:50
After installing `yarn-1.0.2-20170916.1017-unsigned`, all good. Except that it now shows hashtags instead of blocks. But the progress bar itself is working properly.

**Comment by BYK** [comment] 2017-09-17 01:43
>Except that it now shows hashtags instead of blocks. 

That was the fix 😂

**Closed by BYK** 2017-09-17 01:43 UTC
