### ISSUE TITLE
yarn install won't install history package

### ISSUE THREAD

**Issue by eisisig** [yarnpkg/yarn#840] opened 2016-10-12 08:50 UTC
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
`yarn install` won't install history (@^4.3.0). No error messages. Even if I do `yarn add history` it tells me everything went fine. But in node_modules there is never a history package.

Installing somewhere else is ok. So must be a combination of dependencies that is causing this?

_P.S doing npm install history installs history just fine_

**If the current behavior is a bug, please provide the steps to reproduce.**

Given this package.json and doing yarn install

```
{
  "name": "my-package",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dll": "webpack --config webpack.dll.js",
    "build": "webpack"
  },
  "bin": "server.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack-dashboard": "^0.2.0"
  },
  "dependencies": {
    "babel-core": "^6.14.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-add-module-exports": "~0.2.1",
    "babel-plugin-transform-class-properties": "6.16.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-export-extensions": "^6.8.0",
    "babel-plugin-transform-object-rest-spread": "^6.16.0",
    "babel-polyfill": "6.16.0",
    "babel-preset-latest": "6.14.0",
    "babel-preset-react": "6.11.1",
    "codemirror": "^5.19.0",
    "connect-history-api-fallback": "^1.3.0",
    "css-loader": "^0.25.0",
    "directory-tree": "^1.1.1",
    "docgen-loader": "^1.3.4",
    "express": "^4.14.0",
    "file-loader": "^0.9.0",
    "globby": "^6.0.0",
    "graceful-fs": "^4.1.9",
    "highlight.js": "^9.7.0",
    "history": "^4.3.0",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.22.0",
    "json5": "^0.5.0",
    "json5-loader": "^0.6.0",
    "jsx-control-statements": "^3.1.5",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "lodash.foreach": "^4.5.0",
    "lodash.get": "^4.4.2",
    "lodash.has": "^4.5.2",
    "lodash.isempty": "^4.4.0",
    "lodash.map": "^4.6.0",
    "lodash.merge": "^4.6.0",
    "markdown-it": "^8.0.0",
    "markdown-it-emoji": "^1.3.0",
    "markdown-it-external-links": "0.0.6",
    "markdown-it-loader": "^0.5.0",
    "markdown-it-task-lists": "^1.4.1",
    "raw-loader": "^0.5.1",
    "react": "^15.3.2",
    "react-docgen": "^2.11.0",
    "react-dom": "^15.3.2",
    "react-hot-loader": "^3.0.0-beta.5",
    "react-redux": "^5.0.0-beta.3",
    "redux": "^3.6.0",
    "redux-actions": "^0.12.0",
    "redux-logger": "^2.7.0",
    "redux-mock-store": "^1.2.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.1.0",
    "style-loader": "^0.13.1",
    "svg-inline-loader": "^0.7.1",
    "webpack": "^2.1.0-beta.25",
    "webpack-dev-middleware": "^1.8.4",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1",
    "yargs": "~6.0.0"
  }
}
```

**What is the expected behavior?**

There should be an **history** folder in node_modules

**Please mention your node.js, yarn and operating system version.**
macOS sierra 10.12.1
node v6.7.0
yarn 0.15.1

**Comment by mattstyles** [comment] 2016-10-12 10:58
Similar issue with `graceful-fs` disappearing from `node_modules`, causing `standard` to break, which again seems to be some combination of dependencies (adding `yarn add history`, for example, worked fine in a minimal project I set up, similarly `standard` works fine until I add some other stuff which breaks it). 

**What is the current behaviour**

I've tried to create a minimal reproducible, which isn't super minimal.

```
"devDependencies": {
  "standard": "8.4.0"
}
```

```
yarn add

// All good, node_modules/graceful_fs exists and standard works great
```

```
yarn add less less-plugin-clean-css less-plugin-autoprefix

// Usually still ok, although I think just adding this broke at some point
```

```
yarn add simple-less-middleware

// Dragons have been unleashed, graceful-fs is removed and standard reigns fiery hell down upon projects
```

Only clues I have are that `simple-less-middleware` has `less` and its plugins also as dependencies (same versions), not sure if that has anything to do with it.
 
**What is expected**

Stuff that dependencies need should not be deleted from `node_modules`

**Versions**

node **6.7.0**
yarn **0.15.1**
os **osx 10.11.6**

**Comment by aehrt55** [comment] 2016-10-13 15:35
This issue might related to #785

**Comment by eisisig** [comment] 2016-10-13 20:17
I had problems with `graceful-fs` not installing at first. But doing `yarn add graceful-fs` fixed that. The history thing just won't install no matter what.

I'm going to try investigating this a bit more... As installing with yarn just takes seconds! 👍  #winning

**Comment by wyze** [comment] 2016-11-03 15:54
Are you still able to reproduce this @eisisig? I tested on `master` and was able to `yarn add history` without issue.

**Comment by eisisig** [comment] 2016-11-03 16:28
@wyze I tried 0.16.1 and in this project, yarn still won't install history. I was going to narrow this down but haven't had the time.

If you think there is a fix on master I'll install that and test

**Comment by eisisig** [comment] 2016-11-03 16:47
@wyze 0.16.2 seems to fix this issue! 👍

**Comment by wyze** [comment] 2016-11-03 16:48
Awesome, I'll go ahead and close this out then. Thanks for testing that!

**Closed by wyze** 2016-11-03 16:48 UTC
Labels: needs triage
