### ISSUE TITLE
"yarn init" allows "Name" to contain a space, but if Name contains a space, "yarn add" breaks

### ISSUE THREAD

**Issue by semitrivial** [yarnpkg/yarn#1695] opened 2016-11-05 02:59 UTC
I did "yarn init" and set my project's name to something like "Foo Bar".

Then I did "yarn add webpack".

I got an error about the name containing an illegal character.

Changing the name to "FooBar" allowed me to "yarn add webpack".

If spaces are illegal in Name, then "yarn init" should refuse Name with spaces.

Better yet, allow "yarn add" to work when Name has a space.

Beautiful project, btw, loving it so far 👍

**Comment by wyze** [comment] 2016-11-05 06:00
Duplicate of #1268 and fixed by #1425.

**Closed by wyze** 2016-11-05 06:00 UTC
