### ISSUE TITLE
1.22.10 RPMs not uploaded to releases repository

### ISSUE THREAD

**Issue by njnatale-lm** [yarnpkg/yarn#8482] opened 2020-12-03 00:03 UTC
### Bug description

The latest Yarn release has not made its way into the dedicated repository for packaged versions: https://github.com/yarnpkg/releases.git

We maintain a clone of this repo to help automate updates through ```yum``, and while we can download the RPM manually from the 1.22.10 release page, this is far from ideal.

**What is the current behavior?**

Can only obtain 1.22.5 (or older) RPMs using the repository at https://github.com/yarnpkg/releases.git

**What is the expected behavior?**

Should be able to obtain all releases at https://github.com/yarnpkg/releases.git

**Steps to Reproduce**

1. ``git pull`` to update clone of https://github.com/yarnpkg/releases.git
2. Look for 1.22.10 RPMs (or deb packages), not found...

**Environment**

- Node Version: N/A
- Yarn v1 Version: N/A 
- OS and version: N/A

**Comment by merceyz** [comment] 2021-02-04 00:09
Duplicate of https://github.com/yarnpkg/yarn/issues/8374

**Closed by merceyz** 2021-02-04 00:09 UTC
