### ISSUE TITLE
yarn run <command> doesn't work with custom node_modules location

### ISSUE THREAD

**Issue by pkopac** [yarnpkg/yarn#3900] opened 2017-07-11 11:46 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I install into custom location `node_modules`, because I'm running vagrant linux virtual box VM on windows.
The installed dependencies have problems with long names, symbolic links & compiling, so I decided (as recommended) to move that off the mounted host file system into the VM FS.
But in our workflow we need to execute `yarn run webpack-dev-server <some arguments>`. This seems to look just in the local `.bin`, I couldn't get it to work with either CLI params, nor env. variables. It says not found.
**Workaround:** adding as "scripts" into `package.json` with full path.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install `webpack-dev-server` into custom location `node_modules`.
Try `yarn run webpack-dev-server`.
Result: `error Command "webpack-dev-server" not found.`

**What is the expected behavior?**
I expected if I supply `--modules-folder` it would work. Or setting it with `.yarnrc`. Or with environment variables.

**Please mention your node.js, yarn and operating system version.**
Guest system: `Ubuntu 14.04.5 LTS`
`node.js: v6.11.0`
`yarn: 0.27.5`

**Comment by BYK** [comment] 2017-07-18 11:07
Hey @pkopac, looks like this will be addressed with #3792 and this issue is somewhat a duplicate of #3724 so closing in favor of that. LMK if this doesn't work for you and we'll reopen this one and track it separately.

**Closed by BYK** 2017-07-18 11:07 UTC

**Comment by samuela** [comment] 2019-04-25 01:06
I'm still seeing the same issue as of yarn v1.13.0. I have a `.yarnrc` file:
```
--*.modules-folder /opt/nuvemfs-cli-misc/node_modules
```
`yarn install` operates as expected and installs everything in the custom dir, but `yarn run` refuses to pick up on the `modules-folder` setting:
```
$ yarn apollo
yarn run v1.13.0
error Command "apollo" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ yarn run apollo
yarn run v1.13.0
error Command "apollo" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ yarn --modules-folder /opt/nuvemfs-cli-misc/node_modules/ run apollo
yarn run v1.13.0
error Command "apollo" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mazicky** [comment] 2019-05-15 06:10
Me too.
After `yarn run`, scripts in `.bin` still find `node_modules/` folder.

until it fixes, my solution is
`ln -sf [CUSTOM_MODULE_FOLDER] node_modules`

**Comment by pierreyves-lebrun** [comment] 2019-07-15 04:15
Same issue here, I tried figuring out what flag could be missing in my .yarnrc file but couldn't even find a list of valid options in yarn documentation

**Comment by pharazon** [comment] 2021-05-11 20:46
The problem still persists when running a script through packages.json and a custom module folder. However, if you run: yarn run jest, it works ok.

**Comment by pharazon** [comment] 2021-05-13 06:37
I managed to circumvent the problem by combining:
 ln -sf /opt/myproject/node_modules
 yarn config set -- --modules-folder /opt/myproject/node_modules

**Comment by cdhanna** [comment] 2022-06-18 03:42
doing a `yarn config set` does it globally for all your projects, right? That hardly seems like a solution :(
