### ISSUE TITLE
After `yarn install` version in one of dependency's package.json changed

### ISSUE THREAD

**Issue by maslenkov** [yarnpkg/yarn#3522] opened 2017-05-29 13:38 UTC
**Do you want to request a *feature* or report a *bug*?**
It looks like a bug. But it is more like a question because I'm not sure that it is really a yarn's bug.

**What is the current behavior?**
`yarn install` use another package.json then npm and this behavior creates problems with https://github.com/brunch/brunch
More in next section

**If the current behavior is a bug, please provide the steps to reproduce.**
For example, we use https://github.com/browserstate/history.js/
Latest version - `1.8.0-b2`
When I install packages through npm then it works well.
*When I install packages through yarn then package.json of history.js(node_modules/historyjs/package.json) contains incorrect version _1.8.0b2_ instead of 1.8.0-b2*
then when I run `brunch build` it raises an error:
```
error: Initialization error - Invalid Version: 1.8.0b2 Invalid Version: 1.8.0b2
  at new SemVer (/Users/maslenkov/projects/xmp/check_npm_yarn/node_modules/semver/semver.js:293:11)
```
so steps to reproduce
```
mkdir yarn_test && cd yarn_test
npm install brunch
brunch new
yarn install
yarn add historyjs
brunch build
```

**What is the expected behavior?**

I'm not sure what should I write there. I think version in package.json shouldn't be changed :/

**Please mention your node.js, yarn and operating system version.**

npm/node.js - 4.2.0/7.10.0
yarn - 0.24.5
brunch 2.10.9
OSX 10.12

**Comment by bestander** [comment] 2017-06-22 02:29
I think Yarn does not validate/correct versions in package.json of dependencies.
`historyjs` version contains the incorrect value https://unpkg.com/historyjs@1.8.0-b2/package.json.

**Comment by bestander** [comment] 2017-06-22 02:30
Feel free to send a PR with validation

**Comment by bestander** [comment] 2017-06-22 02:31
Could be related https://github.com/yarnpkg/yarn/issues/3560

**Comment by BYK** [comment] 2017-10-27 13:46
Looks like #3560 is a duplicate of this one but since most of the discussion happened there, I'm closing this as a duplicate of #3560.

**Closed by BYK** 2017-10-27 13:46 UTC
Labels: bug-linking, cat-compatibility, good first issue, help wanted, triaged

**Comment by maslenkov** [comment] 2017-10-27 18:59
Ugh... I'm not arguing about closing but I don't agree that it is a duplication. It can be related. But in my case yarn(or smth else) _changes version's **spelling**_. And it is a cause of trouble with my build.
