### ISSUE TITLE
"yarn add" isn't guaranteed to install all the repo's files

### ISSUE THREAD

**Issue by avi12** [yarnpkg/yarn#8430] opened 2020-11-04 15:40 UTC
**Command**
```sh
yarn add jszip
```

**What is the current behavior?**

Yarn adds most of the files of [jszip](https://github.com/Stuk/jszip), but not all, notably the [nodejs](https://github.com/Stuk/jszip/tree/master/lib/nodejs) directory & the scripts inside.

**What is the expected behavior?**

Yarn should obviously add all the files related to the package.

**Steps to Reproduce**

1. `yarn add package-name`, e.g. `yarn add jszip`

I know this is a bug because I tested adding the exact same module with NPM. and it _did_ add all the files that Yarn did not add.

**Environment**

- Node Version: `12.19.0`
- Yarn v1 Version: `1.22.4 
- OS and version: Windows 10 x64, build 20H2

**Comment by Samantha-uk** [comment] 2020-11-07 13:01
I experienced a similar issues with a different package.
It turned out to be caused by having a .yarnclean file which was causing the "missing" directories to be deleted by https://classic.yarnpkg.com/en/docs/cli/autoclean/
Might be worth checking out ...

**Comment by avi12** [comment] 2020-11-07 20:19
I've never had a `yarnclean` file in any of my projects, so it's not the causer for me.

**Comment by merceyz** [comment] 2021-01-02 13:57
Closing as i'm unable to reproduce

**Closed by merceyz** 2021-01-02 13:57 UTC
