### ISSUE TITLE
Unrecognized command line flags run install by default

### ISSUE THREAD

**Issue by Zajn** [yarnpkg/yarn#693] opened 2016-10-11 18:32 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Supplying an unrecognized flag to yarn results in yarn fetching and installing packages.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install `yarn`
2. Change to directory with a `package.json`
3. run `yarn --vesrion`

yarn will read the `package.json` file and fetch packages as if you had simply run `yarn`.
 
**What is the expected behavior?**
yarn replies that it does not recognize the flag, and returns a non-zero code similar to how `bundle`, `cargo`, or `npm` do.
 ex:
```sh
$ cargo --vesrion
Unknown flag: '--vesrion'. Did you mean '--version'?
```

Note this is not limited to misspelling of certain flags. Any non-recognized flag causes this to happen.

**Please mention your node.js, yarn and operating system version.**
`node`: v6.1.0
`yarn`: 0.15.0
`OS`: Ubuntu 16.04.1 LTS

**Comment by busches** [comment] 2016-10-19 14:31
I'm not able to reproduce this in `yarn 0.16.1` looks like @wyze's fix landed in `0.16.0`.

**Comment by Zajn** [comment] 2016-10-19 14:38
@busches Yes, this was fixed in #777. 

@kittens Is it okay to close this now?

**Comment by wyze** [comment] 2016-10-24 17:48
Closing as it is fixed and released.

**Closed by wyze** 2016-10-24 17:48 UTC
Labels: bug

**Comment by IgorAufricht** [comment] 2017-01-18 10:25
This is now working in the latest version (0.19.1):
```
$ yarn --vesrion
yarn install v0.19.1
warning npm-shrinkwrap.json found. This will not be updated or respected. See https://yarnpkg.com/en/docs/migrating-from-npm for mor
e information.
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.84s.
```

Should I create a new issue for this?
