### ISSUE TITLE
forever building fresh packages :(

### ISSUE THREAD

**Issue by DefinitlyEvil** [yarnpkg/yarn#5268] opened 2018-01-23 13:07 UTC
**What is the current behavior?**
it stuck at: 
```
Building fresh packages...
. electron
. waiting...
. waiting...
. waiting...
. waiting...
. waiting...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn global add electron@1.7.9`

**What is the expected behavior?**
it should install I think

**Please mention your node.js, yarn and operating system version.**
nodejs v9.4.0 on MacOS

**Comment by Xixi20160512** [comment] 2018-01-24 15:25
i have the same problem, yarn just stuck in this status without any logs~~~

**Comment by DefinitlyEvil** [comment] 2018-01-25 05:39
I tried without global option and it worked, then it also worked for global mode. Anyways I am new to yarn....

**Comment by GloriousYellow** [comment] 2018-01-29 22:49
When you install electron, it has to download a copy of chromium, that's what is happening when "building"

**Comment by DefinitlyEvil** [comment] 2018-01-30 10:19
@GloriousYellow ah then i think it was caused by my bad Internet lmfao.

**Comment by allanberry** [comment] 2018-02-27 03:43
same problem here.  Mac OSX

$ yarn global --version
1.0.2

```
$ yarn global upgrade
yarn global v1.0.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "loopback@2.38.3" has incorrect peer dependency "loopback-datasource-juggler@^2.19.0".
warning "grunt-contrib-clean@1.0.0" has incorrect peer dependency "grunt@>= 0.4.5".
warning "grunt-contrib-coffee@1.0.0" has incorrect peer dependency "grunt@>= 0.4.5".
warning "grunt-contrib-concat@1.0.1" has incorrect peer dependency "grunt@>=0.4.0".
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/anchor/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/anchor/node_modules/lodash shouldn't be copied twice in one bulk copy
```

**... snip... about 300 lines of this**

```
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.csr shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.key shouldn't be copied twice in one bulk copy
[4/4] 📃  Rebuilding all packages...
[1/14] ⠂ spawn-sync
[2/14] ⠂ ursa
[1/14] ⠄ spawn-sync
[2/14] ⠄ ursa
[3/14] ⠄ typechecker
[7/14] ⡀ bufferutil
[2/14] ⡀ ursa
[8/14] ⡀ utf-8-validate
[6/14] ⡀ strong-mesh-client
warning Error running install script for optional dependency: "/Users/myuser/.config/yarn/global/node_modules/utf-8-validate: Cannot read property 'config' of undefined"
info This module is OPTIONAL, you can safely ignore this error
error An unexpected error occurred: "/Users/myuser/.config/yarn/global/node_modules/strong-mesh-client: Cannot read pro



warning Error running install script for optional dependency: "/Users/myuser/.config/yarn/global/node_modules/heapdump: Cannot read property 'getOption' of undefined"
info This module is OPTIONAL, you can safely ignore this error
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "loopback@2.38.3" has incorrect peer dependency "loopback-datasource-juggler@^2.19.0".
warning "grunt-contrib-clean@1.0.0" has incorrect peer dependency "grunt@>= 0.4.5".
warning "grunt-contrib-coffee@1.0.0" has incorrect peer dependency "grunt@>= 0.4.5".
warning "grunt-contrib-concat@1.0.1" has incorrect peer dependency "grunt@>=0.4.0".
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/anchor/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/anchor/node_modules/lodash shouldn't be copied twice in one bulk copy
```

**...snip... about 500 lines of this...**

```
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.csr shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/myuser/.config/yarn/global/node_modules/nodefly-register/node_modules/request/tests/ssl/ca/server.key shouldn't be copied twice in one bulk copy
[4/4] 📃  Building fresh packages...
[7/14] ⢀ bufferutil
[2/14] ⢀ ursa
[8/14] ⠠ utf-8-validate
[9/14] ⠠ heapdump
[5/14] ⠠ strong-agent
```

At that point, it just hangs forever.

**Comment by BYK** [comment] 2018-05-03 21:46
This should be fixed with Yarn 1.6.0. Can someone verify?

**Comment by BYK** [comment] 2018-05-03 21:46
Oh wow, @marcelogarbin was using the latest. Sorry.

**Comment by BYK** [comment] 2018-05-03 21:50
Looks like the fix for this isn't released yet. Anyone willing to try the nightly build to see if it is fixed on master(it should)? - http://nightly.yarnpkg.com/

**Comment by blackandcode** [comment] 2018-05-28 10:38
Just tried the nightly and it works with it!

**Comment by milesrichardson** [comment] 2018-06-07 13:28
As an additional datapoint, I was having this problem on 1.3.0 and upgrading to latest stable (1.7.0) solved it.

**Comment by BYK** [comment] 2018-06-07 15:35
Thanks for confirming @milesrichardson!

**Closed** 2018-06-07 15:35 UTC
Labels: triaged

**Comment by inturbidus** [comment] 2018-06-14 01:16
I am having this issue with 1.7.0 stuck on "puppeteer"

**Comment by inturbidus** [comment] 2018-06-14 01:18
Actually it eventually finished

**Comment by DefinitlyEvil** [comment] 2018-07-25 18:06
nice work! 
thanks people!

**Comment by sibelius** [comment] 2018-07-30 19:51
it is happening to me on 1.9.2 on mac

**Comment by kdama** [comment] 2018-08-05 03:48
me too on 1.9.2 on mac and eventually finished AGAIN

**Comment by inturbidus** [comment] 2018-08-06 03:54
So I noticed that if I run npm install instead of yarn, that puppeteer is downloading a 79mb file (Chromium) which is why it takes so long.

**Comment by Xerus2000** [comment] 2018-08-16 19:34
I guess an indicator would be nice. It's been building on electron for about an hour now and I have no idea if it will ever finish since there's no indication of progress...

**Comment by kamira** [comment] 2018-10-30 08:07
I stuck on 1.10.1. all package is done and waiting for phantomjs-prebuilt.

Version:1.10.1
Package: phantomjs-prebuilt

**Comment by Srutherford2407** [comment] 2018-11-09 20:10
I am still having an issue, running yarn v1.12.3. Puppeteer install hangs, only an issue with yarn another project running npm install works.

https://screencast.com/t/AogU8EAVRl

**Comment by Srutherford2407** [comment] 2018-11-09 20:32
@BYK  Can you re-open this issue?

**Comment by gbfeliped** [comment] 2018-11-12 23:00
happening on latest version as well :(

**Comment by zthxxx** [comment] 2018-11-15 07:46
it seems hangs while `puppeteer` downloading `Chromium`，
so you can try this operate below, it works for me.

```bash
yarn add puppeteer --ignore-scripts
yarn install
cd node_modules/puppeteer/
yarn exec node install.js
```

ref: #6663

**Comment by xiaoxiangmoe** [comment] 2019-01-09 15:08
happening on latest version as well, 1.13.0.

@BYK Can you re-open this issue?

**Comment by aztack** [comment] 2019-02-11 11:38
please re-open this issue

**Comment by GloriousYellow** [comment] 2019-02-11 13:11
Can you try on the latest nightly? It works for me on version `v1.15.0-20190205.1914`.

**Comment by good-idea** [comment] 2019-02-14 06:34
doing a full `yarn cache clean && yarn install` got this working for me on 1.13.0

**Comment by nerder** [comment] 2019-02-14 14:50
on `v1.13.0` with `phantomjs-prebuilt`

**Comment by 282159468** [comment] 2019-02-19 02:24
Happening on `v1.13.0` with `puppeteer` 
please re-open this issue

**Comment by kevindra** [comment] 2019-03-05 19:58
I confirm, happening with v1.13.0

**Comment by asapzacy** [comment] 2019-03-12 01:01
Can confirm as well ~

node: `8.11.4`
yarn: `1.13.0`
puppeteer: `1.6.2`

**Comment by DefinitlyEvil** [comment] 2019-03-12 16:30
have you tried using a VPN? maybe it was caused by GFW.

**Comment by bruceCzK** [comment] 2019-03-27 04:53
Same here with `node-sass`
v1.15.2

**Comment by teal-front** [comment] 2019-04-08 07:05
> Same here with `node-sass`
> v1.15.2

same as me

**Comment by zee2E** [comment] 2019-04-28 14:42
if you in GFW
edit .yarnrc and insert below line

ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"

**Comment by kikit0106** [comment] 2019-05-23 09:33
I have the same issue when try `yarn install` on docker (yarn 1.16.*)

**Comment by romariolopezc** [comment] 2019-05-26 03:12
Same for me, just updated to MacOS

Yarn version: `1.16.0`
MacOS: `10.14.5 (18F132)`

**Comment by sujianqingfeng** [comment] 2019-06-01 14:20
.yarnnc file
```
registry "https://registry.npm.taobao.org"

sass_binary_site "https://npm.taobao.org/mirrors/node-sass/"
phantomjs_cdnurl "http://cnpmjs.org/downloads"
electron_mirror "https://npm.taobao.org/mirrors/electron/"
sqlite3_binary_host_mirror "https://foxgis.oss-cn-shanghai.aliyuncs.com/"
profiler_binary_host_mirror "https://npm.taobao.org/mirrors/node-inspector/"
chromedriver_cdnurl "https://cdn.npm.taobao.org/dist/chromedriver"
```

**Comment by lamvh** [comment] 2019-06-12 04:23
> When you install electron, it has to download a copy of chromium, that's what is happening when "building"

Check network, if it is downloading, waiting to finish and download packages you need.

**Comment by LeonSkrilec** [comment] 2019-06-18 07:17
I solved it by switching to different network (hotspot). I guess our office network firewall had some restrictions.

**Comment by AzySir** [comment] 2019-06-20 02:40
Was there any other solutions here? I'm having the same issue

**Comment by wuuhw** [comment] 2019-06-28 04:18
i have same issue, i'ill run `gatsby new project`, select yarn install all packages, but waste a long time here,  no error、no log,  i try again, same question

**Comment by silasabbott** [comment] 2019-06-28 07:13
I'm having the same issue, it hangs on "Building fresh packages..."
This happens for any packages on any network when internet works for other applications just fine.

yarn **1.17.0**
node **10.16.0**
macOS **10.14.5 (Mojave)**

**Comment by BYK** [comment] 2019-06-28 10:27
I am going to lock this issue as I don't see any useful comments coming in and it feels more like a support forum instead of an open source project issue :)

If you are still having this issue, please try to narrow it down a bit, collect some information for reliable reproduction and file a new issue with those specific. Or even better, do all this and then fix the issue and open a PR so we can share your awesome work with the community ;)
