### ISSUE TITLE
tar: Ignoring unknown extended header keyword 'SCHILY.dev'

### ISSUE THREAD

**Issue by noahsw** [yarnpkg/yarn#1110] opened 2016-10-15 22:48 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Tons of tar errors about SCHILY.
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    94  100    94    0     0   1088      0 --:--:-- --:--:-- --:--:--  1093

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3249  100  3249    0     0  16781      0 --:--:-- --:--:-- --:--:-- 31852
Installing Yarn!
> Downloading tarball...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    92  100    92    0     0   1174      0 --:--:-- --:--:-- --:--:--  1179

  0     0    0   595    0     0   1194      0 --:--:-- --:--:-- --:--:--  1194

  0 3202k    0 16384    0     0  17697      0  0:03:05 --:--:--  0:03:05 17697
 75 3202k   75 2413k    0     0  1268k      0  0:00:02  0:00:01  0:00:01 2454k
100 3202k  100 3202k    0     0  1542k      0  0:00:02  0:00:02 --:--:-- 2770k
> Extracting to ~/.yarn...
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'

...ON AND ON AND ON...
```

Yarn does install successfully but there's a crapload of these tar warnings.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `curl -o- -L https://yarnpkg.com/install.sh | bash` on CircleCI's Ubuntu 14.04 image

See https://circleci.com/gh/winsleague/winsleague/873

**What is the expected behavior?**
No warnings in output

**Please mention your node.js, yarn and operating system version.**
Node: 4.5.0
Yarn: 0.15.1
OS: Ubuntu 14.04

**Comment by Daniel15** [comment] 2016-10-16 03:33
Duplicate of #770. This is happening because the 0.15.1 release tarball was built on Mac OS (which uses BSD `tar` by default) rather than Linux (which uses GNU `tar`). This should not happen for future releases.

>  on CircleCI's Ubuntu 14.04 image

Please prefer the Ubuntu packages in that case. You can add this into your `circle.yml`:
```
dependencies:
  pre:
    - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
    - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    - apt-get update -yy
    - apt-get install yarn
```

Closing this as a duplicate of #770. Thank you for using Yarn! 😄

**Closed by Daniel15** 2016-10-16 03:33 UTC
