### ISSUE TITLE
Running tests locally fails on registry InternalError

### ISSUE THREAD

**Issue by TimvdLippe** [yarnpkg/yarn#2869] opened 2017-03-08 10:54 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running `yarn test` locally fails tests with
```
Error: https://registry.yarnpkg.com/hosted-git-info/-/hosted-git-info-2.2.0.tgz: Parse Error
      
      at ReadStream.socketOnData (_http_client.js:411:20)
      at emitOne (events.js:96:13)
      at ReadStream.emit (events.js:191:7)
      at readableAddChunk (_stream_readable.js:176:18)
      at ReadStream.Readable.push (_stream_readable.js:134:10)
      at onread (fs.js:1939:12)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:628:17)
```

Inspecting `https://registry.yarnpkg.com/hosted-git-info/-/hosted-git-info-2.2.0.tgz:` shows

```
{"code":"InternalError","message":"options.uri is a required argument"}
```

The tests that fail are

```
__tests__/commands/add.js (78.864s)
  ● modules resolved multiple times should save to mirror correctly
```

and in the integration test:

```
__tests__/commands/install/integration.js (83.133s)
  ● install incompatible optional dependency should still install shared child dependencies

    Error: ENOENT: no such file or directory, open '/tmp/yarn-install-should-not-skip-required-shared-deps-1488970056339-0.044019625452305755/.yarn-cache/v1/npm-hosted-git-info-2.2.0-7a0d097863d886c0fabbdcd37bf1758d8becf8a5/.yarn-metadata.json' 
    Console output:
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/hosted-git-info/-/hosted-git-info-2.2.0.tgz: Parse Error
warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
      
      
      at __tests__/commands/_helpers.js:132:13
          at Generator.throw (<anonymous>)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone Yarn
2. Run `yarn && yarn run build && yarn test`

**What is the expected behavior?**

The tests do not fail on initial checkout

**Please mention your node.js, yarn and operating system version.**
```
yarn --version 0.21.3 (repository fresh checkout on master)
node -v 7.7.1
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

```

**Comment by arcanis** [comment] 2017-04-28 16:53
I'm going to close this one, since I've not been able to reproduce it. Maybe try to check again?

**Closed by arcanis** 2017-04-28 16:53 UTC

**Comment by TimvdLippe** [comment] 2017-04-29 12:09
Seems to be fixed for now. Maybe it was flakiness introduced earlier and has since been fixed. Let's hope it does not regress :smile:
