### ISSUE TITLE
yarn install --production removes transitive dependencies that are the same as dev dependencies

### ISSUE THREAD

**Issue by rockytang** [yarnpkg/yarn#2946] opened 2017-03-18 00:33 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running yarn install --production, it is removing dev dependencies that are also transitive dependencies to dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn add moduleA -D
yarn add moduleB
// moduleB depends on moduleA
yarn install --production
// moduleA will not be installed
```

**What is the expected behavior?**
moduleA should not be removed since moduleB still depends on it. 

**Please mention your node.js, yarn and operating system version.**
node v4.6.2
yarn v0.21.3
OS: OS X El Capitan 10.11.6

Did not specify module names because they were company modules.

**Comment by janaz** [comment] 2017-03-19 01:15
Is this duplicate of #2819 ?

**Closed** 2017-03-19 09:38 UTC
Labels: duplicate
