### ISSUE TITLE
yarn-error: can not install or add ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [yarnpkg/yarn#1835] opened 2016-11-15 04:53 UTC
**yarn-error: can not install or add ?**

![yarn-error](https://cloud.githubusercontent.com/assets/18028768/20293559/7ad87008-ab32-11e6-8bb0-9300f3be49ea.png)

what's going on with this ?
Anybody can help?

**Comment by xgqfrms-GitHub** [comment] 2016-11-15 09:39
**So, I just give up it!**
@npm
@yarnpkgbot

**Comment by hobofan** [comment] 2016-11-15 09:46
Duplicate of #1268 and fixed by #1425.

Try a newer version of yarn.

**Comment by kittens** [comment] 2016-11-15 11:31
The error message is pretty clear, the `name` value in your own `package.json` is invalid. Remove all the invalid characters from it and it will work.

**Closed by kittens** 2016-11-15 11:31 UTC

**Comment by xgqfrms-GitHub** [comment] 2016-11-15 13:53
which is the invalid characters ?

```json
{
  "name": "yarn test",
  "version": "1.0.1",
  "description": "yarn & chocolatey",
  "main": "index.js",
  "repository": {
    "url": "https://github.com/xgqfrms-GitHub/webgeeker",
    "type": "git"
  },
  "author": "webgeeker",
  "license": "MIT"
}
```

**Comment by wyze** [comment] 2016-11-15 14:11
The space is an invalid character.

**Comment by xgqfrms-GitHub** [comment] 2016-11-15 14:39
where ?
please give a screen shortcut.

**Comment by wyze** [comment] 2016-11-15 14:43
Invalid:

`"name": "yarn test",`

**Comment by xgqfrms-GitHub** [comment] 2016-11-15 15:30
Thanks!

**Comment by xgqfrms-GitHub** [comment] 2016-11-16 01:29
test, OK!
![node yarn msi](https://cloud.githubusercontent.com/assets/18028768/20331238/22a8657a-abdf-11e6-9996-817bd37ffdeb.png)
![yarn add](https://cloud.githubusercontent.com/assets/18028768/20331239/22afa9a2-abdf-11e6-8f85-da1ed2780e29.png)
![yarn-error](https://cloud.githubusercontent.com/assets/18028768/20331240/22b12be2-abdf-11e6-9884-ad9db5efd420.png)
