### ISSUE TITLE
custom node_modules folder breaks .bin since yarn 0.25.4

### ISSUE THREAD

**Issue by pjordaan** [yarnpkg/yarn#3724] opened 2017-06-26 09:18 UTC
In our setting we install all our yarn packages in a different folder then the default node_modules folder with the --modules-folder setting.
e.g.:
```
yarn --modules-folder vendor/node_modules
```

**What is the current behavior?**
The current behaviour (version 0.24.*)  will install them in vendor/node_modules/.bin
After upgrading to version 0.25.4 it installs them incorrectly in node_modules/.bin, the packages are still installed in vendor/node_modules and the symlinks in node_modules/.bin still work.
However it seems some of them are missing, as I can't find uglifyjs binary for example in my project in that folder.

**What is the expected behavior?**
Install the packages as version 0.24.* did by installing them in vendor/node_modules/.bin

node.js v7.10.0
yarn: 0.24.5/0.25.4

**Comment by bestander** [comment] 2017-06-26 17:57
The bug should be somewhere in package-linker.js, PR is welcome

**Comment by twooster** [comment] 2017-07-01 10:42
Seeing this in 0.27.5 as well.

**Comment by twooster** [comment] 2017-07-01 22:01
I'll have a pull-request which kind of fixes this, but it looks like it's a hairier problem than I originally gave it credit for, so I'm not entirely satisfied with my solution. My personal use-case is to get more sanity in Docker dev environments whereby I can use a `node_modules` folder outside of my source path so that there's no files being written thru docker into my local environment. For the most part, with pushed changes, it works.

It looks to me like the most proper fix might be to adjust the `yarn` Registry so that it has its own `modulesFolder` rather than checking for `modulesFolder` everywhere throughout the code, which is what my pull request does. That said, checking `config.modulesFolder` seems to be the common pattern throughout the codebase, even if it's unevenly applied.

What was the original intent of --modules-folder supposed to be? In what circumstances is it supposed to work? With which commands?

**Comment by bestander** [comment] 2017-07-03 17:09
The original --modules-folder idea IIRC is to support other languages, e.g. `python_modules`, `c_modules`.
I agree that it would be better to configure folder in one place

**Comment by schmunk42** [comment] 2017-09-14 19:05
Having the same issue, I see a `.bin` folder created at the current working directory, but not in my custom path. 

node@6.7.0
yarn@1.0.2

**Comment by shouze** [comment] 2017-09-14 19:08
@schmunk42 there's a PR opened by @twooster https://github.com/yarnpkg/yarn/pull/3792 since a while now but no fix merged ATM. I experiment the same issue and it's annoying.

**Comment by vigintas** [comment] 2017-10-20 15:28
Having the same problem. Came up with this to fix the deployment script while it gets fixed:
```
mkdir -p client/node_modules/.bin
for f in node_modules/.bin/*; do
  FILENAME="$(basename $f)"
  OLD_LINK=$(readlink $f)
  NEW_LINK=${OLD_LINK/..\/..\/client\/node_modules\//../}
  NEW_PATH="client/node_modules/.bin/$FILENAME"
  ln -sf $NEW_LINK $NEW_PATH
done
rm -rf node_modules
```

**Comment by BYK** [comment] 2017-10-27 13:42
Possible duplicate of #1684.

**Comment by mnieber** [comment] 2017-11-20 13:13
IGNOREME: I am commenting here so I can easily find this issue again in the future, [since I can't do that by subscribing alone](https://github.com/isaacs/github/issues/283\).

**Comment by EECOLOR** [comment] 2018-04-10 21:44
@BYK no, it's not a duplicate of #1684. It however is related, but this is a more specific problem and solving it would enable a few use cases even without fixing the problems described in #1684.

**Comment by EECOLOR** [comment] 2018-04-10 21:46
By the way, this problem still exists in yarn 1.5.1

**Comment by kilianc** [comment] 2018-06-23 02:44
In case other people need a quick monkey-patch 🌈

```docker
RUN \
  yarn --no-emoji --pure-lockfile && \
  mv ./node_modules $NODE_PATH
```

**Closed** 2018-08-22 19:36 UTC
Labels: cat-bug, good first issue, help wanted, triaged

**Comment by pothibo** [comment] 2019-08-31 13:48
Also ran into this issue trying to set my node modules in an external path. I'd love to help if possible, can someone point me to the right direction? Maybe I can create a PR.

**Comment by BYK** [comment] 2019-09-06 15:23
@pothibo any PRs regarding fixing these issues are always welcome (as long as they do not rewrite too much code, making it risky to merge). Feel free to tag me or @arcanis for reviews if you ever get to submit a PR.
