### ISSUE TITLE
yarn install overwrites linked modules with cached version

### ISSUE THREAD

**Issue by lukebennett** [yarnpkg/yarn#1214] opened 2016-10-18 22:43 UTC
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Running `yarn install` for an app that has linked modules results in yarn copying its cached version of each module to the symlinked directory, overwriting the local copy in the process.

**If the current behavior is a bug, please provide the steps to reproduce.**

I struggled to reproduce this from scratch, it's possible that it's down to a specific combination of factors with my setup. This involves local copies of private/scoped npm modules `yarn link`ed from an application, and referenced in package.json via `file:../xxx`. The version of the modules yarn has in its cache appears to be from when I first installed and ran it a few days ago (there have been numerous changes to the modules since), so it's possible the problem lies with its caching strategy as much as its installation strategy.

One observation I've made is that the problem occurs even when using `yarn install --force` to supposedly bypass the cache.

Happy to answer any questions and/or try anything to help pinpoint the problem.

**What is the expected behavior?**

yarn install should skip linked modules like npm intstall does. Performing the same steps above using npm install does not result in this problem.

**Please mention your node.js, yarn and operating system version.**

node v6.2.2
yarn v0.16.0
Mac OS X v10.10.5

**Comment by bmayen** [comment] 2016-10-20 00:06
This isn't specific to cached packages. I have a published package `foo@1.0.0`. Locally I link an unpublished package `foo@2.0.0`. My project has a package.json dependency for `foo@2.0.0` and I link to that. When I run `yarn` after linking, it tries to install `foo@2.0.0` from the repo instead of using the linked version and it fails because `foo@2.0.0` hasn't been published yet.

**Comment by jimdebeer** [comment] 2016-10-20 16:13
really need this, think its a bug

**Comment by mstdokumaci** [comment] 2016-10-24 15:37
this is breaking

**Comment by haggholm** [comment] 2016-10-27 17:59
This applies even when you `install` *different* packages. E.g.

```bash
cd @my/local-dep
yarn link
cd ../../@my/main-project
yarn link @my/local-dep
yarn add lodash
```

Even though I didn’t even explicitly do anything with `@my/local-dep`, `yarn` still goes through the modules and installs anything not locally installed, even if it’s linked.

This happens even if I specify `--no-lockfile`.

It’s a particularly nasty problem because it overwrites my local *working copy* of `@my/local-dep`, so it will overwrite anything you haven’t committed yet, effectively erasing local work.

```bash
$ yarn --version
0.16.1
```

**Comment by joefiorini** [comment] 2016-10-28 14:07
I've noticed this issue as well. In my testing it seems to be limited to scoped modules, but that may not be true for everyone. My use case:

Our team works in a monorepo. To get shared packages locally, the only way to have an efficient development process is to symlink them. Since we can't save symlinked installs to `package.json`, we use `file:` specifiers with relative paths, followed by a library called `linklocal` that goes finds and symlinks local dependencies.

It's kind of a hack, but it works very well. However, npm shrinkwrap is so painful for us that switching to yarn is extremely advantageous, even if we have to work around a few warts due to early adoption.

This issue is very bad for that above workflow though. Anytime yarn tries to install we run the risk of losing work.

What exactly is the advantage of using the cache for local dependencies? Since they would never hit the network anyway, couldn't yarn just treat anything that's a `file:` reference as a cache miss and either skip copying it entirely (as npm does) or copy it in from the local dir?

**Comment by haggholm** [comment] 2016-10-28 17:33
I’d be much happier if Yarn just left linked dependencies alone—if it’s a symlink, either do nothing on the assumption that I want to work with it as a symlink, or if for some reason that can’t be done, issue an error and refuse to do anything. Even deleting the symlinks and replacing them with normal dependencies would be better—still a nuisance, but at least not as bad as the current behaviour.

1. If I run `yarn link`, I should never have to worry about Yarn *changing* my files.
2. There’s no reason why Yarn should be modifying files outside of `node_modules` (and its own caches).

IMHO, the preferred behaviour would be to leave symlinked directories alone, unless there’s a version mismatch, in which case error out with a descriptive message.

**Comment by bmayen** [comment] 2016-10-28 22:11
> unless there’s a version mismatch, in which case error out with a descriptive message.

What would be the advantage of this? Why not allow linked packages to be any version? I believe that's how NPM currently works.

**Comment by damonmaria** [comment] 2016-11-02 12:46
Having the same issue. It seems like it's replacing the linked module with the published version. As tho it's installing the package into the directory without realising it's a symlinked package. I don't think yarn's cache is the reason.

**Comment by joefiorini** [comment] 2016-11-02 13:53
I was able to get around this issue for time being by using `yarn link` and then not adding the dependencies to my `package.json` at all. The script that starts our dev server & installs deps for CI/production builds also handles running `yarn link` for our shared packages, which ensures it happens everywhere we need to build our code.

**Comment by whitecolor** [comment] 2016-11-12 00:41
This is very confusing problem, a big source of hassle,  have you managed fix the logic behind it?

**Comment by whitecolor** [comment] 2016-11-12 16:59
I've described inconsistent behaviour or yarn that leads to the issue: https://github.com/yarnpkg/yarn/issues/1794

**Comment by whitecolor** [comment] 2016-11-13 14:48
For those who experience this problem I made a [quick fix](https://github.com/whitecolor/my-yarn) that disables getting from cache for local (file:) dependencies, you may look and ad create you version or yarn.

**Comment by whitecolor** [comment] 2016-11-20 07:27
Btw in new 0.17.6 it seems that yarn doesn't replace content of simlinked folder (in node_modules) with version from cache, but installs new dependencies (that changed in linked package.json - which is nice)

Can others confirm that this not an issue anymore?
@lukebennett @joefiorini @haggholm

**Comment by travisbloom** [comment] 2016-11-20 16:55
@whitecolor can confirm that with 0.17.6 the problem still persists. simlinked folder is having code overwritten by yarn.

**Comment by travisbloom** [comment] 2016-11-20 16:58
This is happening with a privately scoped npm repo (`@rocketrip/name-of-package`)

**Comment by whitecolor** [comment] 2016-11-20 20:06
@travisbloom right it seem to be true when you link scoped package, it works ok with not scoped symlinks (doesn't touch it).

**Comment by tgriesser** [comment] 2016-11-21 14:26
Just added a fix for this in #1970

**Comment by DenisVuyka** [comment] 2016-11-29 09:53
Still an issue with 0.17.9 and a huge blocker for most of the scenarios involving npm/yarn link.

**Comment by rbilgil** [comment] 2016-11-30 14:13
+1, This is a big issue that caused us to lose uncommitted work from a linked repo. Would be good to get it fixed.

**Comment by AlastairTaft** [comment] 2017-02-08 03:36
Can confirm I don't get this issue in the latest version 0.19.1.

**Comment by tgriesser** [comment] 2017-02-08 15:27
Yep, this can probably be closed now

**Closed** 2017-02-08 15:30 UTC
Labels: needs triage

**Comment by AlastairTaft** [comment] 2017-04-11 00:02
I am still seeing this issue on yarn@0.22.0. I'm using 'lerna' so if I have packageA depending on packageB via a symlink and then run `yarn upgrade packageB` inside the packageA directory It ends up overwriting my non-commited local changes of packageB.

**Comment by whitecolor** [comment] 2017-04-11 01:20
@AlastairTaft can you make a list of simple steps to reproduce?

**Comment by dbpieter** [comment] 2017-04-27 13:32
@whitecolor 

Simple reproduction with file: protocol.

- Install a package through the registry (for example "lodash")
- Change your package.json so that lodash uses file protocol (eg: "lodash": file:./custom_packages/lodash")
- yarn install
- observe node_modules => lodash version from cache is used instead of the one from custom_packages

yarn v0.22.0

**Comment by whitecolor** [comment] 2017-04-27 14:09
@dalmaer and on the latest stable 23.2?

**Comment by bestander** [comment] 2017-04-27 14:10
We just landed a fix to file: dependencies on master.
Check out in 0.24 next week

**Comment by oliversalzburg** [comment] 2017-05-04 13:10
This is still happening. I just opened #3288 to report the same behavior. Happens with 0.23.4. We're not using file protocol.

**Comment by oliversalzburg** [comment] 2017-05-05 09:47
Is there any workaround for this which I am not aware of? Needless to say, having your working copies constantly overwritten by cached content without you realizing it has a major impact on development.

**Comment by whitecolor** [comment] 2017-05-06 09:17
@oliversalzburg I advice to try this for development with local packages: https://github.com/whitecolor/yalc

**Comment by oliversalzburg** [comment] 2017-05-06 18:11
@whitecolor Awesome. Thanks a lot. I'll check it out.

**Comment by jonschlinkert** [comment] 2017-05-09 02:47
I'm still trying to confirm if this is what happened, but it appears that yarn overwrote local files across multiple files with cached symlinked versions. I'm using yarn `0.23.4`

**Comment by oliversalzburg** [comment] 2017-05-17 13:02
@bestander Can you reopen this issue? It is not solved. I would really appreciate some feedback on this.

**Comment by bestander** [comment] 2017-05-17 13:04
@oliversalzburg please open a new one with a scenario how to reproduce it.
Ideally if you could provide a bash script to make it automated.

**Comment by oliversalzburg** [comment] 2017-05-17 14:26
@bestander I had already opened #3288, but I'm having a really hard time reproducing the issue in isolation. It happens multiple times every day in our main project tree though. It would be really nice to investigate this with someone who is more familiar with the code base and maybe give me some pointers on what to look for.

**Comment by danilo-drs** [comment] 2017-05-24 19:51
I'm getting this issue on version 0.24.5.
I have some packages that i developed and they are not published on any server, they are just linked. 
My projects uses this linked packages and some published packages like express or bluebird.
when I try to run "yarn" to install all or a specific package it returns the error:
> error Couldn't find package "package-name" on the "npm" registry

steps to reproduce:

cd path/to/a-dev-package
yarn link
cd path/to/a/project
yarn link a-dev-package
yarn add bluebird
it returns : 
error Couldn't find package "a-dev-package" on the "npm" registry

**Comment by bestander** [comment] 2017-06-15 22:31
Thanks, @danilo-drs, I've extracted this into a separate issue https://github.com/yarnpkg/yarn/issues/3645

**Comment by stelf** [comment] 2017-07-10 08:42
I believe this issue is not solved in v0.27.5. node here is 6.11 and npm 5.04. 

Steps: 
1. yarn link / npm link module A (a symlink goes into the local $PREFIX/lib/node_modules/)
2. chdir into module B's dir
3. yarn link A (a symlink to A goes into B/node_modules)
3. yarn install => complains about versions from npmjs.com, rather than just using the local one

**Comment by whitecolor** [comment] 2017-07-10 08:58
@stelf yarn takes into account what is in your package.json to keep consistency. So it actually doesn't take into account that you linked the module, there is `link:` dependencies in yarn, but it is more for linking local deps in monorepo. For working with external modules I successfully use [`yalc`](https://github.com/whitecolor/yalc)

**Comment by fcoury** [comment] 2017-10-18 20:53
This is happening again with yarn v1.2.1:

```
> $ yarn link mongodb-promise                                                                                                                                         yarn link v1.2.1
success Using linked module for "mongodb-promise".
✨  Done in 0.07s.

> $ ls -lad node_modules/mongodb-promise                                                                                                                              lrwxr-xr-x  1 fcoury  staff  21 Oct 18 18:52 node_modules/mongodb-promise -> ../../mongodb-promise

fcoury@iMac ~/code/faxing                                                                                                                                              > $ yarn                                                                                                                                                              [±master ●]
yarn install v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 1.99s.

> $ ls -lad node_modules/mongodb-promise                                                                                                                              [±master ●]
drwxr-xr-x  9 fcoury  staff  306 Oct 18 18:52 node_modules/mongodb-promise
```

Should I create a new issue?

**Comment by chaddjohnson** [comment] 2017-10-23 21:37
Still outstanding and needs to be fixed.

When I run `yarn add lodash` (for example) it removes any links I had set up for my project, and I have to manually run `yarn link my-package-name` again.

**Comment by bestander** [comment] 2017-10-24 04:18
Looks like the original issue was fixed but there may be other cases when it is still relevant.
For everyone seeing this please open a new issue with the repro script.
It would be hard to reopen this one as it tracks too many things.

**Comment by chaddjohnson** [comment] 2017-10-24 15:22
Created new issue #4770 as requested.
