### ISSUE TITLE
Error fetching dependencies in node >= 8

### ISSUE THREAD

**Issue by ebitonte** [yarnpkg/yarn#3703] opened 2017-06-22 21:21 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When running `yarn` with a clean cache on node v8.1.2, receive an error during `Fetching packages` with the following message:

```
Cannot read property 'asyncReset' of null"
```

This behavior is inconsistent, and appears to be a [race condition within node 8](https://github.com/nodejs/node/issues/13539).

**If the current behavior is a bug, please provide the steps to reproduce.**

Within a project (with a large number of dependencies so as to increase chances of hitting race condition...)
```
rm -rf node_modules
yarn cache clean
yarn
```

**What is the expected behavior?**
Successful fetching of all packages 😄

**Please mention your node.js, yarn and operating system version.**
node: `8.1.2`
yarn: `0.24.6`, `0.23.4`
MacOS: `10.12.5`

**Comment by ebitonte** [comment] 2017-06-22 21:30
I've made a test repo in which I'm able to very consistently reproduce this error

https://github.com/ebitonte/yarn-test

**Comment by voxsim** [comment] 2017-07-11 05:48
Can I help on this? I also have some other issue related to node 8.. should we build everything for node 8 too? For everything I mean:
- generate an artifact for node8
- add a travis/circleci/appveyor build
- maybe a babel part for node8 too
- everything that I don't know that we already do for node4, node6 :p

**Comment by BYK** [comment] 2017-07-28 14:04
@ebitonte I cannot reproduce with latest master with node `8.1.3`. Can you verify if this is also the case for you.

FYI I had to replace all your internal npm mirror paths with `https://registry.npmjs.org/` in the `yarn.lock` file with the repo you've provided for repro.

**Comment by BYK** [comment] 2017-08-07 17:31
Closing since the author did not respond to our requests for more info.

@ebitonte feel free to reopen this if you can provide more information and can reproduce the issue.

**Closed by BYK** 2017-08-07 17:31 UTC
Labels: bug-fetching, needs-repro-script, triaged

**Comment by MMX13** [comment] 2017-08-08 02:13
I am also having the same issue with a project with a large number of dependencies. I've also reproduced the same issue using @ebitonte's test repo (after removing the yarn.lock)

On three separate runs it failed on different packages.
`error An unexpected error occurred: "http://registry.npmjs.org/accepts: Cannot read property 'asyncReset' of null".`
`error An unexpected error occurred: "http://registry.npmjs.org/on-headers: Cannot read property 'asyncReset' of null".`
`error An unexpected error occurred: "http://registry.npmjs.org/compressible: Can
not read property 'asyncReset' of null".`

yarn v0.27.5
node 8.2.1
Win7
