### ISSUE TITLE
"Invariant Violation: expected manifest" after upgrade to V1.0.1

### ISSUE THREAD

**Issue by adyanced** [yarnpkg/yarn#4382] opened 2017-09-10 14:51 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug report

**What is the current behavior?**
Error info as below while excute 'yarn outdated' after upgraded to V1.0.1

D:\BLEHygrometer>yarn outdated
yarn outdated v1.0.1
error Outdated lockfile. Please run `yarn install` and try again.
info Visit https://yarnpkg.com/en/docs/cli/outdated for documentation about this command.

Error infomation below while 'yarn install'

D:\BLEHygrometer>yarn install
yarn install v1.0.1
[1/4] Resolving packages...
warning Resolution field "regenerator-runtime@0.10.5" is incompatible with requested version "regenerator-runtime@^0.11.0"
warning Resolution field "chalk@2.0.1" is incompatible with requested version "chalk@^1.1.3"
error An unexpected error occurred: "expected manifest".
info If you think this is a bug, please open a bug report with the information provided in "D:\\BLEHygrometer\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Invariant Violation: expected manifest
    at invariant (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1416:15)
    at PackageResolver.getStrictResolvedPattern (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:58977:5)
    at PackageResolver.resolveToResolution (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59186:39)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59073:25
    at Generator.next (<anonymous>)
    at step (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:92:30)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:110:14
    at Promise (<anonymous>)
    at F (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:29335:28)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:89:12
Invariant Violation: expected manifest
    at invariant (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1416:15)
    at PackageResolver.getStrictResolvedPattern (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:58977:5)
    at PackageResolver.resolveToResolution (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59186:39)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59073:25
    at Generator.next (<anonymous>)
    at step (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:92:30)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:110:14
    at Promise (<anonymous>)
    at F (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:29335:28)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:89:12
Invariant Violation: expected manifest
    at invariant (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:1416:15)
    at PackageResolver.getStrictResolvedPattern (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:58977:5)
    at PackageResolver.resolveToResolution (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59186:39)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:59073:25
    at Generator.next (<anonymous>)
    at step (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:92:30)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:110:14
    at Promise (<anonymous>)
    at F (C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:29335:28)
    at C:\Users\Richard\AppData\Roaming\npm\node_modules\yarn\lib\cli.js:89:12

Delete lock file has no effect.

**If the current behavior is a bug, please provide the steps to reproduce.**

package.json

{
  "name": "BLEHygrometer",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "flow": "node_modules/.bin/flow",
    "flow-stop": "node_modules/.bin/flow stop"
  },
  "dependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "buffer": "^5.0.6",
    "d3": "^4.10.0",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.48.2",
    "react-native-ble-manager": "^6.1.0",
    "react-native-elements": "^0.16.0",
    "react-native-material-ui": "^1.13.0",
    "react-native-same-toast": "^1.0.1",
    "react-native-svg": "^5.4.1",
    "react-native-vector-icons": "^4.3.0",
    "react-navigation": "1.0.0-beta.12",
    "realm": "^1.11.1"
  },
  "devDependencies": {
    "babel-jest": "^20.0.3",
    "babel-preset-react-native": "^3.0.1",
    "jest": "^20.0.4",
    "react-test-renderer": "16.0.0-alpha.6"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./fonts"
    ]
  },
  "resolutions": {
    "lodash": "4.17.4",
    "babel-preset-react-native": "2.1.0",
    "core-js": "2.4.1",
    "regenerator-runtime": "0.10.5",
    "debug": "2.6.8",
    "ansi-styles": "3.1.0",
    "supports-color": "3.2.3",
    "ms": "2.0.0",
    "base64-js": "1.2.1",
    "object-assign": "4.1.1",
    "node-fetch": "1.7.1",
    "iconv-lite": "0.4.18",
    "async": "2.5.0",
    "babel-preset-fbjs": "2.1.4",
    "bser": "2.0.0",
    "json5": "0.5.1",
    "mime": "1.3.6",
    "mime-types": "2.1.15",
    "minimist": "1.2.0",
    "mkdirp": "0.5.1",
    "npmlog": "4.1.2",
    "opn": "4.0.2",
    "plist": "2.0.1",
    "pretty-format": "20.0.3",
    "rimraf": "2.6.1",
    "sane": "1.6.0",
    "source-map": "0.5.6",
    "wordwrap": "1.0.0",
    "ws": "2.3.1",
    "yargs": "7.1.0",
    "jsesc": "1.3.0",
    "readable-stream": "2.3.3",
    "isarray": "0.0.1",
    "safe-buffer": "5.1.1",
    "string_decoder": "1.0.3",
    "bytes": "2.4.0",
    "depd": "1.1.0",
    "qs": "6.5.0",
    "accepts": "1.3.3",
    "vary": "1.1.1",
    "negotiator": "0.6.1",
    "mime-db": "1.27.0",
    "uid-safe": "2.1.4",
    "escape-html": "1.0.3",
    "statuses": "1.3.1",
    "string-width": "2.1.1",
    "is-fullwidth-code-point": "2.0.0",
    "fb-watchman": "2.0.0",
    "kind-of": "4.0.0",
    "is-number": "3.0.0",
    "gauge": "2.7.4",
    "xmlbuilder": "8.2.2",
    "ultron": "1.1.0",
    "caseless": "0.12.0",
    "assert-plus": "1.0.0",
    "camelcase": "3.0.0",
    "cliui": "3.2.0",
    "sax": "1.2.4",
    "yargs-parser": "5.0.0",
    "find-up": "2.1.0",
    "path-exists": "3.0.0",
    "strip-bom": "3.0.0",
    "is-arrayish": "0.3.1",
    "hoist-non-react-statics": "2.2.0",
    "esprima": "4.0.0",
    "resolve": "1.3.3",
    "webidl-conversions": "4.0.1",
    "chalk": "2.0.1",
    "strip-ansi": "4.0.0",
    "ansi-regex": "3.0.0",
    "whatwg-fetch": "2.0.3",
    "form-data": "2.2.0",
    "inquirer": "3.2.0",
    "uglify-js": "2.8.29",
    "ansi-escapes": "2.0.0",
    "has-flag": "2.0.0",
    "uuid": "3.1.0"
  }
}

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**

Windows 10 64bit
Node V8.4.0

**Comment by dougludlow** [comment] 2017-09-11 18:12
Dupe of #4357?

**Comment by first87** [comment] 2017-09-11 19:55
I got the same problem after upgraded yarn to v1.0.1

**Comment by BYK** [comment] 2017-09-11 20:07
This indeed looks similar to #4357 which is fixed on master. Can someone confirm that this is resolved with the latest nightly?

**Comment by BYK** [comment] 2017-09-12 13:08
Closing as duplicate. Feel free to reopen if it is not.

**Closed by BYK** 2017-09-12 13:08 UTC

**Comment by first87** [comment] 2017-09-12 14:30
I am experiencing same problem with `yarn v1.0.1`:
![image](https://user-images.githubusercontent.com/20905447/30330940-46615e70-978b-11e7-8c6a-158e766fe568.png)

I tried on Ubuntu 16.04 and Windows 10 and got same error. Downgrading to `yarn v0.27.5` solved the problem.

I did resolve all dependencies by running `yarn install --flat` so my `package.json` contains a lot of dependencies resolved explicitly in the `"resolutions"`.

I am really expecting that new release will fix this issue.

**Comment by BYK** [comment] 2017-09-12 15:37
@first87 we are hoping to get 1.0.2 in a few days. Sorry for the inconvenience.

**Comment by first87** [comment] 2017-09-12 15:39
@BYK Thank you for the update. I will expect your next release. Cheers!

**Comment by qrrock** [comment] 2017-09-28 16:04
actually, I'm seeing this on 1.1.0; is that expected?

```
yarn upgrade-interactive v1.1.0
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
? Choose which packages to update. 
? Choose which packages to update. @privateRegistry/libs-core@0.0.3
info Installing "dependencies"...
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
Done in 22.42s.
Invariant Violation: expected manifest
    at invariant (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:1434:15)
    at PackageResolver.getStrictResolvedPattern (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:60400:5)
    at add (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:85605:33)
    at add (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:85633:9)
    at PackageHoister.prepass (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:85653:7)
    at PackageHoister.seed (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:85188:10)
    at PackageLinker.getFlatHoistedTree (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:47302:13)
    at /home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:47316:29
    at next (native)
    at step (/home/user/.nvm/versions/node/v6.11.0/lib/node_modules/yarn/lib/cli.js:92:30)
➜ /opt/mytestpath/test_pakage 

```

**Comment by maitscha** [comment] 2017-10-03 09:06
Same here, broken in v1.1.0.
