### ISSUE TITLE
Yarn broke build on CI

### ISSUE THREAD

**Issue by neolite** [yarnpkg/yarn#7953] opened 2020-03-05 08:54 UTC
##Bug description
When we build a project using yarn on CI, yarn broke build and cannot finish installing

**Command**

```sh
 npm i yarn -g && \
 yarn import && \
 rm node_modules/.yarn-integrity && \
 yarn install
```

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/576423/75963649-e539bc80-5ed6-11ea-99bc-bb6625f5914e.png)

```
ERROR in ./node_modules/react-popper/lib/esm/Manager.js
Module not found: Error: Can't resolve 'create-react-context' in '/Users/rafkat/Sites/Clover/platform-web/node_modules/react-popper/lib/esm'
 @ ./node_modules/react-popper/lib/esm/Manager.js 5:0-49 6:41-54 7:47-60
 @ ./node_modules/react-popper/lib/esm/index.js
 @ ./node_modules/semantic-ui-react/dist/commonjs/modules/Popup/Popup.js
 @ ./node_modules/semantic-ui-react/dist/commonjs/modules/Popup/index.js
 @ ./node_modules/semantic-ui-react/dist/commonjs/index.js
 @ ./node_modules/clover-chart/src/components/Modals/IncidentsDependencyForm.jsx
 @ ./node_modules/clover-chart/src/components/Modals/IncidentsSettingsModal.jsx
 @ ./node_modules/clover-chart/src/components/Charts.jsx
 @ ./node_modules/clover-chart/src/containers/ChartsContainer.js
 @ ./node_modules/clover-chart/src/components/CloverChart.jsx
 @ ./node_modules/clover-chart/src/containers/CloverChartContainer.js
 @ ./node_modules/clover-chart/src/index.js
 @ ./src/store.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/app.js
```

**What is the expected behavior?**
Should work

**Environment**

- Node Version: `v11.15.0`
- Yarn v1 Version: `1.21.1` 
- OS and version: `OS X Catalina, on CI -  Ubuntu LTS`

I cannot understand why semantic-ui-react package get react-popper from lib instead of dist directory. 
I think, yarn cannot install a some packages needed for project, because after installing i see warnings about missed packages.
When I using npm install, packages installed correct.

**Comment by merceyz** [comment] 2021-01-07 13:06
Closing as unactionable, without a full reproduction there isn't much we can do

> I cannot understand why semantic-ui-react package get react-popper from lib instead of dist directory.

Because that's what their `main`/`module` field points to https://cdn.jsdelivr.net/npm/react-popper@1.3.6/package.json

**Closed by merceyz** 2021-01-07 13:06 UTC
