### ISSUE TITLE
Yarn offline mirror in http server or nexus raw repository

### ISSUE THREAD

**Issue by sagar12861** [yarnpkg/yarn#4236] opened 2017-08-23 12:21 UTC
As I gone through the docs, "The “Offline Mirror” can be shared between build servers or development machines in any way that is convenient " I assume that location on http server as yarn offline mirror or nexus raw hosted repository. Yarn just shows a blank for a long time. Please help me to understand..

**Comment by BYK** [comment] 2017-08-23 14:04
@sagar12861 may I suggest this nice read: https://yarnpkg.com/blog/2016/11/24/offline-mirror/#did-you-know-that-yarn-is-also-distributed-as-a-single-bundle-js-file-in-releaseshttpsgithubcomyarnpkgyarnreleases-that-can-be-used-on-ci-systems-without-internet-access

Offline mirror is a local directory, not anywhere on a server.

**Comment by BYK** [comment] 2017-08-23 14:05
Well, I read your comment again and if you want to store this on a network, you may wanna use network mounts, NFS etc.

Also closing the issue since this is not a bug or a feature request apparently but a question for StackOverflow may be?

**Closed by BYK** 2017-08-23 14:05 UTC

**Comment by sagar12861** [comment] 2017-08-23 22:48
@BYK thank you very much for your answer.

Did it make sense to consider artifact repositories or http servers to store offline mirror. Because that is what most of the devOps and SCM teams do with Maven and other private artifacts as well. Please correct me if I'm wrong.

**Comment by BYK** [comment] 2017-08-24 13:11
@sagar12861 my pleasure! Having things on the file system is a lot easier both for yarn and people who store them. I think you can always define a proxy if you wanna use a "real" server. Or as I suggested earlier, use a network mount for shared assets. Does not solve your issue? 

https://www.gluster.org/ may be an intersting choice for this.
