### ISSUE TITLE
Module "progress" adding/removing error

### ISSUE THREAD

**Issue by zombiQWERTY** [yarnpkg/yarn#2257] opened 2016-12-14 16:04 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a bug, as I think

**What is the current behavior?**
```
yarn add progress
yarn add v0.17.10
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
Latest node, yarn, macos

**Comment by iredchuk** [comment] 2016-12-14 20:25
Duplicate of #2112

**Closed** 2016-12-14 20:39 UTC
