### ISSUE TITLE
Fibers/Node-Gyp Hanging on yarn install

### ISSUE THREAD

**Issue by dheerajbhaskar** [yarnpkg/yarn#3041] opened 2017-04-04 22:02 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Hangs on node-gyp or fibers task

![image](https://cloud.githubusercontent.com/assets/2944909/24680842/19c653c4-19b0-11e7-987e-5ec0470e528f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. New project
2. Yarn add chimp

**What is the expected behavior?**
That it adds chimp successfully in reasonable time

**Please mention your node.js, yarn and operating system version.**
node v7.8.0
yarn  v0.22.0 (reproducible on latest stable v0.21.3 also)

Reference:
[Reference:
http://stackoverflow.com/questions/42862378/fibers-node-gyp-hanging-on-yarn-install](http://stackoverflow.com/questions/42862378/fibers-node-gyp-hanging-on-yarn-install)

**Comment by codingwaysarg** [comment] 2017-04-04 23:34
Same issue here using npm

**Comment by codingwaysarg** [comment] 2017-04-04 23:39
Related?

https://github.com/nodejs/node-gyp/issues/1165

**Comment by dheerajbhaskar** [comment] 2017-06-08 11:06
Wow! I was trying to file an issue because I encountered this issue and found my own issue that I'd filed earlier. 

Is more info required to fix this?
Here's a package.json to reproduce this:

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chimp": "^0.48.0"
  }
}
```

**Comment by marvinhagemeister** [comment] 2017-06-09 12:05
This seems to be related to https://github.com/nodejs/node/issues/13557.

**Comment by dmr** [comment] 2017-06-27 10:37
@dheerajbhaskar did you solve the problem? Same issue here...

**Comment by marvinhagemeister** [comment] 2017-06-27 15:41
Just tried it on my machine and it installs fine with the `package.json` posted above

OS: MacOS Sierra
node `8.1.2`
yarn `0.24.6`

**Comment by dheerajbhaskar** [comment] 2017-06-28 06:05
@marvinhagemeister this is am issue on windows. 

@dmr nope, just using npm for now. Was too much trouble using yarn. Also npm now has lock file feature now and is faster than before I think

**Comment by dmr** [comment] 2017-06-28 07:47
My problem was solved by removing node_modules, uninstalling node, reinstalling everything.

**Comment by dheerajbhaskar** [comment] 2017-06-28 08:02
Thanks for the update @dmr

I think I'm going to sit this one out. This way too many hoops to be worth it. I can just do `npm install`and be done with it. 

I've reported the bug because I care for the project

**Comment by MrHayato** [comment] 2017-07-12 22:05
This is also an issue on our CI servers, using Node 8.1.4, Npm 5.2.0, yarn 0.27.5
We've had to roll back to node v6.3.1 and npm 3.9.5 to get it working again as a workaround...

**Comment by theandrewlane** [comment] 2017-07-14 17:22
I'm running into the same issue on Node 8.1.4 and Yarn 0.27.5 on Win 7 Enterprise. Following @dmr's recommendation, hopefully that resolves the node fibers/gyp issue.

**Comment by kittaakos** [comment] 2017-08-01 09:41
Same problem here on a Win10 VirtualBox. It works on OS X. Also, no issues when using npm on Windows.

Steps to reproduce:
```
mkdir foo && cd foo && yarn init -y && yarn add fibers && yarn
```

Full output:
```
kittaakos@DESKTOP-531EDFN MINGW64 ~/Desktop
$ npm --version && node --version && yarn --version && python --version
4.2.0
v7.9.0
0.27.5
Python 2.7.11

kittaakos@DESKTOP-531EDFN MINGW64 ~/Desktop
$ mkdir foo && cd foo && yarn init -y && yarn add fibers && yarn
yarn init v0.27.5
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
Done in 0.08s.
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠂ fibers: gyp info spawn args   '-Goutput_dir=.' ]
```

Does anyone know what could be the root of the problem? I could try to look into it if someone could give me pointers. Thanks in advance!

**Comment by kittaakos** [comment] 2017-08-01 12:30
I have wiped `yarn`, and installed it (v0.27.5) via `choco` (it comes with Node.js v8.2.1
and npm 5.3.0). After that, I was able to use `yarn` to install `fibers`.

```
kittaakos@DESKTOP-531EDFN MINGW64 ~/Desktop
$ mkdir baz && cd baz && yarn init -y && yarn add fibers && yarn
yarn init v0.27.5
warning The yes flag has been set. This will automatically answer yes to all questions which may have security implications.
success Saved package.json
Done in 0.14s.
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ fibers@2.0.0
Done in 4.73s.
yarn install v0.27.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.39s.
```

**Comment by AlexandreBonneau** [comment] 2018-04-12 08:17
`yarn` still fails to install fibers/node-gyp when using the latest stable node `v9.10.1`.

To fix that, you need to temporarily downgrade node to `v6.11.5` using as root `n 6.11.5`.

This is not great :-1:

**Comment by paul-soporan** [comment] 2021-01-02 15:04
Closing as an external issue, there is nothing actionable on Yarn's side here.

**Closed by paul-soporan** 2021-01-02 15:04 UTC
