### ISSUE TITLE
Yarn install never finished

### ISSUE THREAD

**Issue by georgesben** [yarnpkg/yarn#3028] opened 2017-04-01 11:44 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The installation of the modules never finished. This is the log of yarn:
```
yarn install v0.21.3
info No lockfile found.
[1/4] Resolving packages...
warning gulp-istanbul > istanbul-threshold-checker > istanbul > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠂ fibers: spawn args   '-Goutput_dir=.' ]
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
```
I have waited ~20 minutes but nothing happens

**If the current behavior is a bug, please provide the steps to reproduce.**
I have used the following commands: `yarn` and `yarn install` on a new project (I was using npm before). Same problem in the 2 cases.

**What is the expected behavior?**
I expect the installation finished

**Please mention your node.js, yarn and operating system version.**

- Node v.7.7.2
- Yarn 0.21.3 (installed by the msi of the yarn's website)
- Windows 7 64 bits

**Comment by bestander** [comment] 2017-04-28 18:58
@georgesben, please provide a package.json to reproduce the issue, without it we won't be able to fix it.

**Comment by georgesben** [comment] 2017-05-04 19:01
Hi !

Sorry for the late. This is a minimal JSON for the bug:
```Javascript
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chimp": "^0.48.0"
  }
}
```
This is quite similar with this ticket: #3041

**Comment by santiagoaguiar** [comment] 2017-05-10 14:21
Having the same problem, the provided `package.json` also reproduces the issue for me. This issue probably needs to be re-opened.

**Comment by santiagoaguiar** [comment] 2017-05-10 14:26
Smaller repro case:

```
$ yarn init
$ yarn add fibers
yarn add v0.23.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⢀ fibers: spawn args   '-Goutput_dir=.' ]
```

Waits forever.

Running on windows 10, x64, node-gyp 3.6.1, node 7.9.0

**Comment by bestander** [comment] 2017-05-10 16:45
Thanks a lot.
The issue is obviously in lifecycle scripts execution phase https://github.com/yarnpkg/yarn/blob/master/src/util/execute-lifecycle-script.js#L179 and spawn command is clearly not finishing.
Anyone wants to help out and debug why it fails?

**Comment by santiagoaguiar** [comment] 2017-05-10 19:27
I've spent some time trying to see why it doesn't end, but to no avail. The `spawn` is executed but, from my tests, no callback is called at all after the `updateStdout` call on https://github.com/yarnpkg/yarn/blob/master/src/util/child.js#L48 sends the `⢀ fibers: spawn args   '-Goutput_dir=.' ]`. I tried checking if some callback was throwing, but it doesn't seem to be the case either. I'm not sure 

Strangely enough, most of the times, running a `yarn install` for a second time installs correctly. On my machine, 1 over 10 times the first `yarn install` also works OK.

There's this report: https://github.com/lovell/sharp/issues/775 which is similar but with `npm` and on a different package. However, for me, running `npm install` works OK every time. I've left the `yarn install` running to see if it eventually finishes as reported on that bug, but it hasn't after a couple of hours ;).

Haven't found any issues running `node-gyp` by hand either.

I'll put some more time later to see if I can dig further.

**Comment by bestander** [comment] 2017-05-12 21:13
Thanks for more data.
I'll investigate it a bit more as well, more help is welcome

**Comment by byokota** [comment] 2017-05-23 18:02
I've had the same thing happen to me for one of my projects (not all). Install worked maybe once, and then failed to complete as stated in the ticket. Then somehow I got it to work. Now its failing after trying to install updated versions.

We have local/private packages that we import... wondering if that has to do with it. Not sure which package its failing on though... not sure how to tell.

I'm running MacOS

**Comment by byokota** [comment] 2017-05-23 18:27
I'm not sure if this is just a temporary fix like last time (and it will happen again)...

I deleted `node_modules` and `yarn.lock` and updated from yarn version `0.22.0` to `0.24.5` and now it works.

**Comment by BYK** [comment] 2017-06-06 14:31
I can't reproduce this on latest master neither with Node 6 nor with Node 7. I was able to see this happen with Yarn 0.24 and Node 7 so I'd say close the issue.

>If you wait long enough, the problem goes away

_-Anonymous_

**Comment by bestander** [comment] 2017-06-06 15:36
@BYK, did you check on windows as https://github.com/yarnpkg/yarn/issues/3028#issuecomment-300499214?

**Comment by georgesben** [comment] 2017-06-06 16:07
The problem is not solved for me :'(

Yarn version: 0.24.5
Node: 7.7.2

The command `npm install` works but `yarn` doesn't (waiting forever) :/ 
This is my logs:
```
yarn
yarn install v0.24.5
info No lockfile found.
[1/4] Resolving packages...
warning chimp > phantomjs-prebuilt > request > node-uuid@1.4.8: Use uuid module instead
warning chimp > xolvio-ddp > request > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/3] ⠄ waiting...
[2/3] ⠄ fibers: '-Goutput_dir=.' ]
[-/3] ⠄ waiting...
[-/3] ⠄ waiting...
[-/3] ⡀ waiting...
```

**Comment by BYK** [comment] 2017-06-06 16:55
@bestander - not on Windows yet since I hadn't set it up and then I saw comments claiming this happened on macOS too. Will try and debug on Windows too.

@georgesben - That's great! I mean not the issue still existing but you reproducing and providing all this information. Can you also share your package.json file (or at least the relevant parts)? Looks liek you're on Windows. Which version?

**Comment by georgesben** [comment] 2017-06-06 17:01
I'm on Windows 7 (64 bits) Integral version

The package.json file is the following:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chimp": "^0.48.0"
  }
}
```
The command was executed in the following folder: `C:\Users\USER_NAME\test` 

If you need more informations, please tell me :)

**Comment by BYK** [comment] 2017-06-06 20:15
@georgesben - Alright. I don't have access to Win 7 (have Win 10 at home) but I'll it there. If I can't repro, I'll come back and ask for more :)

**Comment by byokota** [comment] 2017-06-09 19:14
I still see it happen from time to time. I have to delete yarn.lock for it to work

**Comment by georgesben** [comment] 2017-06-10 13:04
There is no lock file when I launched the command (see the third line in the log)

**Comment by BYK** [comment] 2017-06-12 19:01
Hey, apologies for the radio silence. I'm in between computers right now so didn't have chance to try and debug this on Windows yet. Still on my list.

**Comment by BYK** [comment] 2017-07-05 13:12
@georgesben - Is this still happening with `yarn` 0.27.5?

**Comment by georgesben** [comment] 2017-07-05 13:57
Yes, this is still happing with yarn 0.27.5 (and `npm install` works). Sorry ^^'

Maybe this is a problem with my computer and not with yarn ?

**Comment by BYK** [comment] 2017-07-05 14:01
@georgesben no need to apologize! We've just shipped a few updates with 0.27 that might have resolved this issue, that's why I asked again.

You've just confirmed that I still need to debug but eliminated a possible cause so thanks!

**Comment by dbaldon** [comment] 2017-07-16 17:39
FYIW, I was having trouble with yarn hanging at the `Linking dependencies...` step also. I hit CTRL+C and this is what I got;
```
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1/936
Error: Cannot find module '../errors.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (c:\Users\xxx\Documents\GitHub\toolkit-for-ynab\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at _load_errors (c:\Users\xxx\Documents\GitHub\toolkit-for-ynab\node_modules\yarn\lib\cli\index.js:36:20)
    at config.init.then.catch.err (c:\Users\xxx\Documents\GitHub\toolkit-for-ynab\node_modules\yarn\lib\cli\index.js:381:34)
Terminate batch job (Y/N)? y
```

I then went and installed yarn via Chocolately and then reran `yarn install` and this time this is what I got;
```
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 10.81s.
```
Huge difference. I suspect the problem in my case was that `yarn` was not in my path. Installing it with `choco install yarn` put it in my path.

**Comment by BYK** [comment] 2017-08-17 18:18
This seems to be resolved on latest master so closing.

**Closed by BYK** 2017-08-17 18:18 UTC
Labels: bug-high-priority, bug-install-scripts, os-windows, triaged

**Comment by entrptaher** [comment] 2019-09-13 17:12
Came back from 2019 :( 

![image](https://user-images.githubusercontent.com/8284972/64881150-d5ee5a80-d67b-11e9-97c6-5ab32e61e245.png)

**Comment by ediardo** [comment] 2019-10-23 06:44
Have the same problem here...

https://media.giphy.com/media/gIrcPX9xVVQlycBewG/source.mp4

**Comment by MWGriffin** [comment] 2019-11-08 21:38
I'm experiencing the same waiting issue as well. Let me know what info y'all would like to troubleshoot it. This is my first time using yarn so I'm not in the know as to what's occurring..

**Comment by byokota** [comment] 2019-11-08 22:22
One reason why this happens is when you have not authenticated with a package server hosting one of your dependencies.

Save passphrase for ssh key
eval $(ssh-agent) ; ssh-add

**Comment by Shakespeare17** [comment] 2022-07-03 21:00
> One reason why this happens is when you have not authenticated with a package server hosting one of your dependencies.
> 
> Save passphrase for ssh key eval $(ssh-agent) ; ssh-add

Care to elaborate?

**Comment by Domigome** [comment] 2022-10-05 08:07
I confirm that it is happening to me with the latest version as well.

**Comment by neuronarchitecture27** [comment] 2023-05-05 09:29
Still occuring to me with the latest version

**Comment by uctpermanar** [comment] 2023-11-07 12:41
This still hapenning at least with me when I install `grapejs`.

```
{
  "name": "test-dnd-web-builder",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "grapejs": "^2.1.2"
  }
}
```
