### ISSUE TITLE
Commands missing man pages

### ISSUE THREAD

**Issue by chocolateboy** [yarnpkg/yarn#1920] opened 2016-11-17 21:09 UTC
Yarn: 0.17.4
Node.js: v7.1.0
OS: Linux (Arch)
See Also: #1119

`yarn help` says:

> Run `yarn help COMMAND` for more information on specific commands.

\- but this does not work for most (19/32) commands. Running `yarn help <command>` on the following commands produces the same generic output as `yarn help`.

```bash
$ yarn help \
    | ruby -ne 'puts $1 if /^ {4}- (\S+)$/' \
    | xargs -I% sh -c 'yarn help % | grep -q "yarn %" || echo "* %"'
```

* bin
* check
* clean
* generate-lock-entry
* info
* init
* link
* login
* logout
* ls
* pack
* remove
* run
* self-update
* unlink
* upgrade-interactive
* version
* versions
* why

**Comment by markstos** [comment] 2016-11-17 22:03
I recommend closing this as a dupe of #1603-- There is already a goal to make the Markdown docs available in the `website` repo to be available through the CLI as well.

**Closed** 2016-11-17 22:06 UTC
