### ISSUE TITLE
Yarn didn't work on this repo

### ISSUE THREAD

**Issue by atsunaakiya** [yarnpkg/yarn#5669] opened 2018-04-14 22:46 UTC
[This repository](https://github.com/23shiji/open-static-map) was created on my previous computer. I cloned it to my current computer and tried to install the dependencies with yarn.

```bash
yarn install
```

It seemed okay until I realized that the node_modules were not created at all.

The same thing happened when I
```bash
yarn add parse
```

parse didn't even appear in package.json

Meanwhile, npm works fine on this repo, and yarn seems okay on the rest repositories on my computer.

Did I broke the configuration files?
I was confused.

yarn 1.6.0
nodejs 8.11.1
OS: ubuntu 16.04

**Comment by rally25rs** [comment] 2018-04-15 18:46
What is the output from `yarn install`? Maybe try running with `--verbose` too.

**Comment by merceyz** [comment] 2021-01-02 14:26
Can't reproduce and assuming it was a timeout issue i'll close this as fixed in v2 where the timeout logic is less susceptible to this sort of issue

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 14:26 UTC
Labels: triaged
