### ISSUE TITLE
Yarn Install v1.0.1 - Package Does Not Exist

### ISSUE THREAD

**Issue by tim-soft** [yarnpkg/yarn#4368] opened 2017-09-08 17:08 UTC
**What is the current behavior?**
Creating a yarn.lock or running yarn install is met with `node_modules/<package> doesn't exist`

```
yarn install v1.0.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning mimelib@0.2.14: This module is deprecated
error "/srv/node/client-portal/@f/animate@^1.0.1" doesn't exist.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's my package.json
<details>
  <summary>package.json</summary>

```
{
  "name": "client-portal",
  "version": "0.1.0",
  "private": true,
  "engines": {
    "node": ">=6.5",
    "npm": ">=3.10"
  },
  "browserslist": [
    ">1%",
    "last 4 versions",
    "Firefox ESR",
    "not ie < 9"
  ],
  "dependencies": {
    "algoliasearch": "^3.24.3",
    "antd": "^2.13.0",
    "apollo-client": "^1.9.2",
    "apollo-server-express": "^1.1.2",
    "auth0-lock": "^10.20.0",
    "babel-plugin-import": "^1.4.0",
    "babel-polyfill": "^6.23.0",
    "bluebird": "^3.5.0",
    "body-parser": "^1.17.2",
    "classnames": "^2.2.5",
    "compression": "^1.7.0",
    "compression-webpack-plugin": "^1.0.0",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.5.1",
    "cors": "^2.8.4",
    "dotenv": "^4.0.0",
    "draft-js": "^0.10.1",
    "draftjs-to-html": "^0.7.5",
    "emailjs": "^1.0.12",
    "eslint-plugin-flowtype": "^2.35.0",
    "express": "^4.15.4",
    "express-jwt": "^5.3.0",
    "get-countries-info": "^1.2.1",
    "graphql": "0.10.5",
    "graphql-subscriptions": "^0.4.4",
    "graphql-tag": "^2.4.2",
    "graphql-tools": "^1.2.1",
    "graphql-voyager": "^1.0.0-rc.8",
    "handlebars": "^4.0.10",
    "harvest": "^1.0.6",
    "helmet": "^3.8.1",
    "history": "^4.7.2",
    "html-to-draftjs": "^0.1.0-beta15",
    "i18n-zipcodes": "^1.0.1",
    "isomorphic-style-loader": "^4.0.0",
    "jsonwebtoken": "^8.0.0",
    "less-vars-to-js": "^1.2.0",
    "lob": "^4.1.1",
    "localforage": "^1.5.0",
    "moment": "^2.18.1",
    "money-formatter": "^0.1.4",
    "morgan": "^1.8.2",
    "mysql2": "^1.4.2",
    "node-fetch": "^1.7.3",
    "normalize.css": "^7.0.0",
    "passport": "^0.4.0",
    "passport-auth0": "^0.6.0",
    "pretty-error": "^2.1.1",
    "prop-types": "^15.5.10",
    "query-string": "^5.0.0",
    "react": "^15.6.1",
    "react-apollo": "^1.4.15",
    "react-beautiful-dnd": "^2.1.1",
    "react-burger-menu": "^2.1.6",
    "react-color": "^2.13.7",
    "react-custom-scrollbars": "^4.1.2",
    "react-dom": "^15.6.1",
    "react-draft-wysiwyg": "^1.10.8",
    "react-hotkeys": "^0.10.0",
    "react-instantsearch": "^4.0.10",
    "react-instantsearch-theme-algolia": "^4.1.0-beta.5",
    "react-redux": "^5.0.6",
    "react-spinkit": "^3.0.0",
    "react-stripe-elements": "^0.0.8",
    "react-transition-group": "^2.2.0",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.9.1",
    "redux-persist-node-storage": "^1.0.2",
    "redux-thunk": "^2.2.0",
    "rocketchat": "^0.57.3-alpha",
    "semantic-ui-css": "^2.2.12",
    "semantic-ui-react": "^0.72.0",
    "sequelize": "^4.8.2",
    "serialize-javascript": "^1.4.0",
    "source-map-support": "^0.4.17",
    "stripe": "^4.25.0",
    "style-loader": "^0.18.2",
    "subscriptions-transport-ws": "^0.8.2",
    "twilio": "^3.6.5",
    "universal-router": "^3.2.0",
    "whatwg-fetch": "^2.0.3",
    "yargs-parser": "^7.0.0"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "assets-webpack-plugin": "^3.5.1",
    "autoprefixer": "^7.1.4",
    "babel-cli": "^6.24.1",
    "babel-core": "^6.25.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-istanbul": "^4.1.4",
    "babel-plugin-rewire": "^1.1.0",
    "babel-preset-env": "^1.6.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.24.1",
    "babel-template": "^6.25.0",
    "babel-types": "^6.26.0",
    "browser-sync": "^2.18.13",
    "chai": "^4.1.1",
    "chokidar": "^1.7.0",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "enzyme": "^2.9.1",
    "eslint": "^4.6.1",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-import-resolver-node": "^0.3.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-css-modules": "^2.7.5",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-react": "^7.3.0",
    "file-loader": "0.11.2",
    "front-matter": "^2.2.0",
    "glob": "^7.1.2",
    "husky": "^0.14.3",
    "less": "^2.7.2",
    "less-loader": "^4.0.5",
    "lint-staged": "^4.1.3",
    "markdown-it": "^8.4.0",
    "mkdirp": "^0.5.1",
    "mocha": "^3.5.0",
    "null-loader": "^0.1.1",
    "nyc": "^11.2.1",
    "opn-cli": "^3.1.0",
    "pixrem": "^4.0.1",
    "pleeease-filters": "^4.0.0",
    "postcss": "^6.0.11",
    "postcss-calc": "^6.0.0",
    "postcss-color-function": "^4.0.0",
    "postcss-custom-media": "^6.0.0",
    "postcss-custom-properties": "^6.1.0",
    "postcss-custom-selectors": "^4.0.1",
    "postcss-flexbugs-fixes": "^3.2.0",
    "postcss-import": "^10.0.0",
    "postcss-loader": "^2.0.6",
    "postcss-media-minmax": "^3.0.0",
    "postcss-nested": "^2.1.2",
    "postcss-nesting": "^4.1.0",
    "postcss-pseudoelements": "^5.0.0",
    "postcss-selector-matches": "^3.0.1",
    "postcss-selector-not": "^3.0.1",
    "raw-loader": "^0.5.1",
    "react-deep-force-update": "2.1.1",
    "react-error-overlay": "1.0.10",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-test-renderer": "^15.5.4",
    "redux-mock-store": "^1.2.3",
    "rimraf": "^2.6.1",
    "sinon": "^3.2.1",
    "stylelint": "^8.1.1",
    "stylelint-config-standard": "^17.0.0",
    "stylelint-order": "^0.6.0",
    "svg-url-loader": "^2.1.1",
    "url-loader": "^0.5.9",
    "webpack": "^3.5.6",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.19.1",
    "webpack-node-externals": "^1.6.0"
  },
  "babel": {
    "presets": [
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ],
      "stage-2",
      "react"
    ],
    "env": {
      "test": {
        "plugins": [
          "istanbul",
          "rewire"
        ]
      }
    },
    "ignore": [
      "/node_modules/",
      "/build/chunks/",
      "/build/public/",
      "/build/updates/",
      "/build/server.js"
    ]
  },
  "lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "git add"
    ],
    "*.{css,less,scss,sss}": [
      "stylelint --fix",
      "git add"
    ]
  },
  "scripts": {
    "precommit": "lint-staged",
    "lint-js": "eslint --ignore-path .gitignore --ignore-pattern \"!**/.*\" .",
    "lint-css": "stylelint \"src/**/*.{css,less,scss,sss}\"",
    "lint": "yarn run lint-js && yarn run lint-css",
    "fix-js": "yarn run lint-js -- --fix",
    "fix-css": "yarn run lint-css -- --fix",
    "fix": "yarn run fix-js && yarn run fix-css",
    "test": "mocha",
    "test-watch": "yarn run test -- --reporter min --watch",
    "test-cover": "cross-env NODE_ENV=test nyc npm run test",
    "coverage": "yarn run test-cover && nyc report --reporter=html && opn coverage/index.html",
    "clean": "babel-node tools/run clean",
    "copy": "babel-node tools/run copy",
    "bundle": "babel-node tools/run bundle",
    "build": "babel-node tools/run build",
    "build-stats": "yarn run build -- --release --analyse",
    "deploy": "babel-node tools/run deploy",
    "render": "babel-node tools/run render",
    "serve": "babel-node tools/run runServer",
    "start": "babel-node tools/run start",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  }
}
```
</details>
<br />

**What is the expected behavior?**
The previous stable yarn release 0.7.x installed my packages

**Please mention your node.js, yarn and operating system version.**
* Node v8.4.0
* Yarn 1.0.1
* Ubuntu 16.04 x64

**Comment by btsuhako** [comment] 2017-09-12 19:12
probably a duplicate of #4421 and #4422

**Comment by BYK** [comment] 2017-09-13 00:02
Can you see if the latest nightly fixes this: https://yarnpkg.com/en/docs/nightly

**Comment by timsuchanek** [comment] 2017-09-15 12:12
The nightly fixes exactly this problem for me!

**Comment by BYK** [comment] 2017-09-15 13:21
@timsuchanek you don't need the nightly anymore, yarn 1.0.2 is out.

**Closed by BYK** 2017-09-15 13:21 UTC
