### ISSUE TITLE
Yarn Plug n Play,not able to resolve modules.

### ISSUE THREAD

**Issue by atishaybaid7** [yarnpkg/yarn#6523] opened 2018-10-10 07:25 UTC
@arcanis  I wanted to experiment with pnp and hence migrated to v1.12.0
and added the configuration in package.json 
`"installConfig": {
    "pnp": true
  },`
`yarn install` ran successfully, but making my build with webpack, several packages were not resolved
<img width="940" alt="screen shot 2018-10-10 at 12 52 59 pm" src="https://user-images.githubusercontent.com/40356338/46719561-dcb26780-cc8b-11e8-8b30-241ab63a8a49.png">

i am using es 6 imports
`import React, { Component } from "react";`.

is there anything i am missing,which is causing resolution issues.

**Comment by arcanis** [comment] 2018-10-10 10:49
Hey @atishaybaid7 - you need the [`pnp-webpack-plugin`](https://github.com/arcanis/pnp-webpack-plugin) 🙂

**Comment by arcanis** [comment] 2018-10-10 12:39
Interesting - can you open an issue on the Webpack plugin repo? It seems to be caused by an incompatibility with aliases. The plugin makes the resolution before the aliases are even tried.

**Comment by atishaybaid7** [comment] 2018-10-10 18:46
opened a issue https://github.com/arcanis/pnp-webpack-plugin/issues/1

**Comment by arcanis** [comment] 2018-10-10 19:12
Thanks! Will check that when I'm back from vacations :)

**Comment by waleedahmed3045** [comment] 2019-04-20 05:17
Hi @arcanis first great work!. 

I import my scss file in app.js but once I switched to PNP my imports with in scss file are not being able to resolve but previously it was able to. I am also using pnp-webpack-plugin but it didnt resolve the issue

![image](https://user-images.githubusercontent.com/5687191/56453039-31a0fb80-6309-11e9-8f47-e7c94c849fe4.png)

**Comment by rafael-fecha** [comment] 2020-08-03 16:20
same issue as @waleedahmed3045 . Were you able to find a solution ?

**Comment by merceyz** [comment] 2021-01-14 10:06
Closing as fixed in v2 where PnP has been improved a lot

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-14 10:06 UTC
Labels: cat-compatibility, plugnplay, triaged
