### ISSUE TITLE
yarn.lock doesn't update on private repository

### ISSUE THREAD

**Issue by claudiopetrini** [yarnpkg/yarn#2854] opened 2017-03-07 11:38 UTC
Current behaviour : 

A `package.json` containing a private dependency (`git+ssh`) is present and a `yarn.lock` has been generated for the version `v1.0.0` of the private dependency.
The `package.json` doesn't define a specific tag of the dependency but takes the most recent version present on `master` branch.
 
The private dependency is then updated to `v1.0.1` but  running:

`yarn upgrade git+ssh://git@domain.com:org/reponame.git --save` or 
`yarn add git+ssh://git@domain.com:org/reponame.git --save`

gets the latest version of the repo as I was expecting but the `yarn.lock` file is not updated.

The only way I've found in order to upgrade the `yarn.lock` file to the latest version is by running `yarn upgrade` but this is going to upgrade all the dependencies and not only the `reponame` one.

node `v6.10.0`
yarn  `v0.21.3`
Mac OSX `v10.12.3`

**Comment by stijnvanderlaan** [comment] 2017-03-08 09:22
Same problem, I update the yarn.lock file by hand now.

**Comment by sambernet** [comment] 2017-03-08 12:15
Probably similar issue I am having with tags - `yarn upgrade` will update to the new tag version, but `yarn upgrade package@tag` does not.

See #2788

**Comment by juanca** [comment] 2017-03-09 01:26
Is there something missing from the test implement in this [recently merged PR](https://github.com/yarnpkg/yarn/pull/2780)?

**Comment by sambernet** [comment] 2017-03-09 15:44
I will have a look at the code, but I'm not familiar with the yarn codebase yet. Thanks for caring anyway - you just answered my question from #2788 concerning support of multiple packages in `yarn upgrade <pkg>`

**Comment by juanca** [comment] 2017-03-09 17:57
Don't sweat it. 

The test is an integration tests which assumes nothing about the codebase.

Have a look at the fixture files: 

- `__tests__/fixtures/upgrade/package-not-in-registry/yarn.lock`
- `__tests__/fixtures/upgrade/package-not-in-registry/package.json`

These files represent the state of the repo before using `yarn upgrade <package>`.

Then look at the new test implement in `__tests__/commands/upgrade.js`.

It just asserts that the `yarn.lock` changes in specific ways.

P.S. The fix was released with v 0.22.0 so perhaps you might need to update (and see if the problem is still occurring).

**Comment by stijnvanderlaan** [comment] 2017-04-26 15:34
This does works in 0.22.0+ for me, yes.

**Comment by arcanis** [comment] 2017-04-26 15:36
👍 I'm going to close this issue, then. Feel free to open a new one if something else doesn't work as expected with git / file packages.

**Closed by arcanis** 2017-04-26 15:36 UTC
