### ISSUE TITLE
Installation Problem: --Without-node flag not working

### ISSUE THREAD

**Issue by Razatastic** [yarnpkg/yarn#7008] opened 2019-02-05 20:16 UTC
Config: MacOS High Sierra, NVM - Node v8.11.3, Homebrew

I tried to run the command `brew install yarn --without-node` since I'm using nvm, but it didn't recognize the flag. The error I got was "Error: invalid option: --without-node".

**Comment by Razatastic** [comment] 2019-02-05 22:12
I tried using a brew flag “—without-dependencies” and that didn’t work either. I ended up installing Yarn through NPM. Seems like the best alternative for now.

**Comment by arcanis** [comment] 2019-02-08 18:00
Duplicate of #6946

**Closed by arcanis** 2019-02-08 18:00 UTC
Labels: triaged
