### ISSUE TITLE
Blocking Node version check

### ISSUE THREAD

**Issue by olivierlambert** [yarnpkg/yarn#634] opened 2016-10-11 16:25 UTC
Hi there,

That's maybe a bug :)

Our project ([Xen Orchestra](https://raw.githubusercontent.com/vatesfr/xo-web/next-release/package.json)) have a dep (`chartist`) we use in Browserify. But `yarn` stop at:

```
[2/4] Fetching packages...
error chartist@0.9.8: The engine "node" is incompatible with this module. Expected version ">=5.5.0".
error Found incompatible module
```

This should be a warning, not an error, because we don't use this dep in Node.

Running this on Node `v4.4.7` and Debian testing.

**Comment by ChristopherBiscardi** [comment] 2016-10-11 16:27
I'll add that it seems that `yarn --ignore-engines` doesn't seem to help with this.

**Comment by kittens** [comment] 2016-10-11 16:27
@olivierlambert We're doing the right thing here. `chartist` has the required `node` version set to `>=5.5.0` but you're running version 4.

**Comment by kittens** [comment] 2016-10-11 16:28
@ChristopherBiscardi Seems like a separate bug, can you open a new issue? Thank you!

**Comment by jkrems** [comment] 2016-10-11 16:38
@kittens It's the right thing in theory. In practice it's the reason why pre-release versions of node can't install packages with engine-strict because `7.0.0-rc.1` is not in the range `>=5`. I would vote for making this a warning even though it might sound wrong.

**Comment by jlongster** [comment] 2016-10-11 16:39
I just hit this as well. Apparently the `engines` field is "advisory" according to the docs: https://docs.npmjs.com/files/package.json#engines

I think you are right to error, but it's going to cause some conflicts with the current ecosystem where packages are too strict but nobody cared because it didn't error before.

I can also repro that `--ignore-engines` does not fix it. I can file a separate bug.

**Comment by olivierlambert** [comment] 2016-10-11 16:39
@kittens it's not "the right thing" if you use this dep without Node (eg with Browserify). In this case, Node version doesn't matter because the dep won't be used in Node at all.

**Comment by jlongster** [comment] 2016-10-11 16:44
I just filed #638.

**Comment by jkrems** [comment] 2016-10-12 17:28
This affects multiple of our (Groupon's) internal apps. Including things like "years ago someone set the node engine to `0.10 || 0.11` when they dropped support for node 0.8". But even if every package would have a perfect engine field, the error behavior is wrong for node prerelease versions and packages that aren't used in node. And then there's packages that use `execSync` (random example) in one code path but are completely fine to use w/o it in 99% of the cases. Or, as others have pointed out, packages that are used in browser bundles, making the node engine field irrelevant.

I really don't want to have to patch yarn whenever I try out a beta version of node. And the only alternative is to add a boilerplate `--ignore-engines` to every single project. :/

**Comment by erikdonohoo** [comment] 2016-10-12 20:21
Would love to at least have `--ignore-engines` flag work

**Comment by samccone** [comment] 2016-10-12 20:46
as soon as a release is cut with
https://github.com/yarnpkg/yarn/pull/647

Things will work with --ignore-engines.


--ignore-engines being opt in was very much intentional, the fact that these fields were only advisory actually removed all of their value forcing package like this to be invented  https://github.com/samccone/engine-deps

Having packages respect this field is super super valuable.

**Comment by erikdonohoo** [comment] 2016-10-12 20:49
Thanks @samccone.  I don't disagree that package authors need to use that field for what it was intended.  Looking forward to next release.

**Comment by jkrems** [comment] 2016-10-12 21:02
@samccone Again, that's all great in theory. But the practice is things like this:

```
> yarn add angular2-cookie
yarn add v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error angular2-cookie@1.2.4: The engine "node" is incompatible with this module. Expected version ">=5.0.0".
error Found incompatible module
```

There's nothing in that package that actually needs node 5+. If I understand it correctly they're using "node>=5" to express "we're super excited about npm 3!!!!". A project using angular 2 w/ the latest node LTS will currently not work with yarn. It works fine without it.

I agree that having a good, reliable way to tell a user "this package will definitely not work at all unless you use node X or higher" would be great. But because of the way engine works right now and how the ecosystem is using it, `package.json#engines` just isn't it.

**Comment by wmertens** [comment] 2016-10-14 18:54
Given that #647 is merged, should this not be closed?

**Comment by jkrems** [comment] 2016-10-14 19:28
@wmertens I think it's premature to close this while it causes popular libraries like `angular` to fail to install by default.

**Comment by wmertens** [comment] 2016-10-14 19:46
Ok, so the issue is then that instead of erroring, it should warn? In that
case, there are like 3 duplicates of this request, it would be nice to have
that be only one canonical one, preferably with PR :)

I suppose it can be as simple as changing
https://github.com/yarnpkg/yarn/blob/b880d403ed9f32e724207ecbdb94c794d4c64131/src/package-compatibility.js#L164
to
be like the warning a few lines down? I don't quite follow the logic in
that function, I don't know where the ignore comes from.

**Comment by samccone** [comment] 2016-10-14 19:50
@jkrems best to open a PR into angular2-cookie to resolve that modules issues.

Closing since #647 was merged.

**Closed by samccone** 2016-10-14 19:50 UTC
Labels: compatibility

**Comment by destroyerofbuilds** [comment] 2017-03-16 19:06
Cross linking #1102
