### ISSUE TITLE
Progress bar is printed on new lines in Windows in CMD

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2530] opened 2017-01-23 11:28 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Progressbar is printing every new state in a new line in Windows 10 default CMD

<img width="916" alt="yarn-on-windows" src="https://cloud.githubusercontent.com/assets/2121048/22202220/0f1747e6-e15f-11e6-883d-0f4b14f6ffca.PNG">

**Please mention your node.js, yarn and operating system version.**
Node 7.3.0
Windows 10

**Comment by bestander** [comment] 2017-01-23 11:29
A possible solution https://github.com/lerna/lerna/pull/92/files thanks to @kentaromiura

**Comment by Daniel15** [comment] 2017-01-24 06:13
This was supposed to be fixed by #526 😢  It works for me?

**Comment by bestander** [comment] 2017-01-25 23:42
It actually works fine on my home Windows PC which has a few CMD features enabled: bash for windows, chocolatey and maybe some other developer options.
The PC I tested this on was a bare windows 10 with no additional software installed except for node and yarn 0.19

**Comment by mrmckeb** [comment] 2017-04-17 08:00
This doesn't work for me, Windows 10 Creators Update (clean install) running bash. I'm seeing the same issue. Any ideas, @bestander?

**Comment by simonbuchan** [comment] 2017-04-17 22:01
https://github.com/Microsoft/BashOnWindows/issues/1936 seems to imply the issue is specific to certain fonts, i.e. it's a rendering issue not an process output issue.

**Comment by kaiyoma** [comment] 2017-05-02 01:20
I see this issue as well when running `yarn install`. I'm running git bash (part of Node.js 6.9.1) on Windows 10.

![progress-bar-issue-1](https://cloud.githubusercontent.com/assets/10719780/25600670/c5db8d24-2e9a-11e7-8a6b-db951240affc.png)

![progress-bar-issue-2](https://cloud.githubusercontent.com/assets/10719780/25600671/c5dc6e4c-2e9a-11e7-87f2-4b8e98e43ddb.png)

**Comment by mrmckeb** [comment] 2017-05-02 06:05
It does look like this is caused by the typeface you use. @kaiyoma - which font are you using here?

**Comment by kaiyoma** [comment] 2017-05-02 15:53
11-point Consolas. Pretty popular for programmers. :-)

**Comment by mrmckeb** [comment] 2017-05-02 23:46
@kaiyoma, take a look at https://github.com/Microsoft/BashOnWindows/issues/1936. Sadly this isn't going to be fixed any time soon. I'm not sure if it's something the Yarn team could help with by doing something different...

**Comment by kaiyoma** [comment] 2017-05-03 00:14
Interesting. Are we sure this is the same issue? I'm using the git bash that comes with the Windows installer of Node.js and I haven't installed the "BashOnWindows" project for running Linux binaries. Are they the same thing?

**Comment by simonbuchan** [comment] 2017-05-03 00:25
To my knowledge the issue is due to the new support for ANSI escape codes
added to the windows console since the updates as part of support for WSL,
but are by default enabled. Perhaps yarn's progress renderer started
detecting and using ANSI support? Git bash should still be using a windows
node. You could try fiddling with fonts or sizes or disabling advanced
console features in the console options as a workaround for now?

**Comment by kaiyoma** [comment] 2017-05-03 00:32
I've disabled progress bars for now (`yarn config set no-progress true`). Having a font I like is infinitely more important than progress bars, which I never had anyway when using npm.

**Comment by sylvainpolletvillard** [comment] 2017-05-06 12:24
I have a similar problem with Hyper and IntelliJ terminal on Windows. It may be related to a new version of Yarn or a Windows update, I'm not sure. It works correctly on Powershell.

![2017-05-06_14-22-40](https://cloud.githubusercontent.com/assets/566536/25772269/8876c784-3267-11e7-92f3-c7bfdd58c2a6.gif)

**Comment by gluons** [comment] 2017-05-12 15:01
Same problem with Windows 10 Creators Update.

Copy from #3383

- **On PowerShell:**

  <img width="793" alt="1" src="https://cloud.githubusercontent.com/assets/4688092/25980299/d3c6bc14-36f7-11e7-811c-8e9918b05097.PNG">

  <img width="780" alt="2" src="https://cloud.githubusercontent.com/assets/4688092/25980301/d81fd836-36f7-11e7-8d71-28449231fc4f.PNG">

- **On CMD:**

  <img width="828" alt="3" src="https://cloud.githubusercontent.com/assets/4688092/25980342/1554bbcc-36f8-11e7-8780-2a6af9b7043b.PNG">

  <img width="826" alt="4" src="https://cloud.githubusercontent.com/assets/4688092/25980352/26d051f4-36f8-11e7-9900-3168a342f9f8.PNG">

**Comment by gluons** [comment] 2017-09-05 03:55
Excuse me. Does anyone have an idea to fix this? It's really annoying problem. 😢

**Comment by simonbuchan** [comment] 2017-09-05 04:03
Change your console font settings to a known good (Been a while, but Consolas 14pt works I think? Depends on font and size combination), or disable yarn progress bars with `yarn config set no-progress` until new console rendering arrives - see https://github.com/Microsoft/BashOnWindows/issues/1936

**Comment by gluons** [comment] 2017-09-05 04:12
@simonbuchan OK. I'm using `Fira Mono` font now. I'll `yarn config set no-progress`. Thank you. 🎉

**Comment by BYK** [comment] 2017-09-05 10:37
I'm on Windows and I don't have this problem. That said I'm using Conemu and the latest nightlies of Yarn. Just tried in PowerShell with `yarn check` and it seems fine.

Anyone can try with the latest nightlies and confirm this still exists?

**Comment by sylvainpolletvillard** [comment] 2017-09-05 11:35
The problem is solved for me with yarn 0.27.5 on default Windows CMD

**Comment by BYK** [comment] 2017-09-05 17:04
>The problem is solved for me with yarn 0.27.5 on default Windows CMD

🎉

**Comment by KayLeung** [comment] 2017-09-05 17:21
I still experienced the problem. Windows 10 Pro Insider Build 16281

**Comment by BYK** [comment] 2017-09-05 17:28
@KayLeung which version of Yarn?

**Comment by KayLeung** [comment] 2017-09-05 17:31
`yarn check v0.27.5`

I tried Powershell / CMD / Conemu

**Comment by sylvainpolletvillard** [comment] 2017-09-05 17:38
So after a few tests, it appears it depends on the terminal font. Here is my tests with Consolas 20 on the left, and Meslo LG M on the right:

![2017-09-05_19-36-55](https://user-images.githubusercontent.com/566536/30074408-bb61eaba-9271-11e7-9d64-f336a12a7ded.gif)

Yet the result is much better than what I had with yarn 0.23

**Comment by KayLeung** [comment] 2017-09-05 18:04
I also tried `yarn check v1.0.0`, same bug.

@sylvainpolletvillard,
It seems Consolas will help in CMD but some square characters like the GIF above.

Conemu with Consolas (tried diff font-size), same bug.

Just reminded the Bar in Jest is working well. Maybe Yarn could borrow some code from there: https://github.com/facebook/jest/pull/3626

**Comment by KayLeung** [comment] 2017-09-05 18:38
I've done some quick testing, it worked: https://github.com/yarnpkg/yarn/pull/4317

**Comment by gluons** [comment] 2017-09-06 02:19
`0.27.5` is still broken for me.

@BYK **Do not close the issue that isn't completely resolved.**

This issue should be opened until we get confirmed fix. (Maybe #4317 ?)

<img width="787" alt="default" src="https://user-images.githubusercontent.com/4688092/30091419-bca72ca6-92e3-11e7-89a2-52bbbf2f7a0f.PNG">

**Comment by BYK** [comment] 2017-09-06 09:06
>@BYK Do not close the issue that isn't completely resolved.

I closed the issue because I think this is a bug in Windows, not Yarn. Sorry for not being clear on that.

**Comment by BYK** [comment] 2017-09-06 09:20
Okay, I think we need to specify the output encoding when writing or simply do `process.stdout.setDefaultEncoding('utf-8');` when creating the reporter.

@KayLeung would you like to give it a try?

**Comment by gluons** [comment] 2017-09-06 09:22
Thank you for reopen.  
It will be easy to search when someone face this problem and search with default `is:issue is:open`. 😄

**Comment by swrobel** [comment] 2017-09-08 08:10
FWIW, I have this same issue in Terminal.app on macOS 10.12.6 using Hack 2.020. I've tried several different reasonable font sizes, all with the same result.

**Closed** 2017-09-13 22:59 UTC

**Comment by gluons** [comment] 2017-09-14 02:13
Wow! Interesting 🎉

**Comment by gluons** [comment] 2017-09-14 02:27
It's fixed. 🎉 

<img width="780" alt="default" src="https://user-images.githubusercontent.com/4688092/30409371-db8facdc-992e-11e7-86e4-5e3fa012a119.PNG">

**Comment by BYK** [comment] 2017-09-14 14:26
This was the same issue with #1222.
