### ISSUE TITLE
Couldn't locate the latest windows msi for the latest build

### ISSUE THREAD

**Issue by cheeshengntt** [yarnpkg/yarn#8753] opened 2021-12-17 10:01 UTC
Good Afternoon team,

Where can I find the latest Windows msi installer? I am running yarn in a no internet environment and the installer will be useful to me.

**Comment by Gemorroj** [comment] 2021-12-17 18:08
duplicate https://github.com/yarnpkg/yarn/issues/8750

**Comment by merceyz** [comment] 2021-12-17 18:19
Duplicate of #8750

**Closed by merceyz** 2021-12-17 18:19 UTC
