### ISSUE TITLE
Bug: Yarn fails to install (Exit code: 128)

### ISSUE THREAD

**Issue by andrewhavens** [yarnpkg/yarn#3303] opened 2017-05-02 18:19 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn fails to install and does not provide any helpful error message for debugging. I have already done this:

```
rm -rf node_modules
rm -rf /Users/andrew/Library/Caches/Yarn
```
..but it has not made any difference.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ yarn
yarn install v0.23.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive f1c99c8e4f13d85cedeaa9d4dc4db8dabe55a796
Directory: /Users/andrew/Library/Caches/Yarn/v1/.tmp/f1b469ac943bb80864be5dfa2512836d
Output:

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Yarn seems to install in other projects. Inspecting the directory that is mentioned in the output:

```
$ cat /Users/andrew/Library/Caches/Yarn/v1/.tmp/f1b469ac943bb80864be5dfa2512836d/package.json
{
  "name": "ember-cli-inject-live-reload",
  "version": "1.4.0",
  "description": "Plugin for ember-cli that injects live-reload script into HTML content.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "ember-addon"
  ],
  "ember-addon": {
    "before": "serve-files-middleware"
  },
  "author": "Robert Jackson",
  "license": "MIT",
  "dependencies": {},
  "devDependencies": {},
  "repository": {
    "type": "git",
    "url": "git://github.com/rwjblue/ember-cli-inject-live-reload.git"
  },
  "bugs": {
    "url": "https://github.com/rwjblue/ember-cli-inject-live-reload/issues"
  },
  "homepage": "https://github.com/rwjblue/ember-cli-inject-live-reload"
}
```

**What is the expected behavior?**

I expect install to succeed or at least provide an actionable error message.

**Please mention your node.js, yarn and operating system version.**
* Node: 7.9.0
* Yarn: 0.23.3
* macOS Sierra 10.12.4

**Comment by EugeneHlushko** [comment] 2017-05-03 13:45
Same thing, happened after `yarn cache clean` i run `yarn`

* node: 7.4.0
* yarn 0.23.2
* CentOS release 6.8 (Final)

**Comment by EugeneHlushko** [comment] 2017-05-03 14:05
Oh yes, if you fail to proceed with yarn install because of this error, just delete your lockfile (`yarn.lock`) and run `yarn install` again

**Comment by xiankai** [comment] 2017-05-18 04:31
I think this can result from trying to install a deleted git branch as well - I was using a custom fork over here https://github.com/apollographql/graphql-tag/pull/52, but when it got merged/deleted, I started encountering a similar error:

```
error Command failed.
Exit code: 128
Command: git
Arguments: archive d4b3e319206be3f7e1ec9f0ad7e90d30a748d43f
```

Where on the last line, was the commit hash of the deleted branch. I switched to the main branch since the pull request had been merged, for my fix.

**Comment by andrewhavens** [comment] 2017-05-18 23:11
I think I found the reason for my original error. I think one of the packages that was linked to a branch had a commit deleted, or force-pushed updates. Unfortunately, I don't know for sure and the yarn error message does not make it clear if that was the case or not.

**Comment by bestander** [comment] 2017-05-23 17:33
I think there are several issues discussed here.
We have fixed a git related issue in 0.25.
Feel free to open a new issue with steps to reproduce if it still remains.

**Closed by bestander** 2017-05-23 17:33 UTC

**Comment by jppellerin** [comment] 2017-05-31 15:52
I was getting the same error when trying to `yarn add` our common library from bitbucket.  After reading this and trying a few things without success I thought I'd try `npm` to see how it would behave.  Also erroring out but I got a better error message : 

```ENOTEMPTY: directory not empty, rmdir '/mnt/c/Users/[user]/Documents/workspace/[project]/node_modules/common-js/dist'```

Using WSL.  Seems like it cannot remove the old directory properly.

I know this is probably unrelated to yarn, but thought I'd post anyways for information purposes.

**Comment by juanca** [comment] 2017-06-02 00:32
I got this same error. I was able to reproduce and fix the issue (it was direct mistake from me).

Basically, I have a git dependency (and it's pointing a branch) that is tracked in the yarn lockfile. At some point during the day, I force pushed my git branch which clobbered the tracked sha. I verified that the clobbered sha was the `git archive CLOBBERED_SHA` presented in the error message.

The fix was to `yarn upgrade <git-dependency>` (if you're on latest). Otherwise, you can `yarn add <git+ssh://...#branch> --force`.

**Comment by rally25rs** [comment] 2018-07-24 11:12
I tend to get this error when using a github dependency and switching between branches.
For those that run into this issue, you can usually fix it by deleting the cace folder from the output.

```
$ yarn
yarn install v0.23.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: archive f1c99c8e4f13d85cedeaa9d4dc4db8dabe55a796
Directory: /Users/andrew/Library/Caches/Yarn/v1/.tmp/f1b469ac943bb80864be5dfa2512836d
Output:

```

Fix it by deleting: `/Users/andrew/Library/Caches/Yarn/v1/.tmp/f1b469ac943bb80864be5dfa2512836d` then rerun yarn.

I think yarn is reusing the cache directory, but git doesn't like overwriting one branch with another in that directory.

**Comment by jorisroling** [comment] 2018-07-26 09:57
I solved it by removing the enire yarn cache (/Users/<user>/Library/Caches/Yarn)

**Comment by henkelb** [comment] 2018-12-20 12:44
I had this kind of error 
![image](https://user-images.githubusercontent.com/8615775/50285715-c54ee200-0465-11e9-815a-ba9b2346a5e5.png)
I solved it by updating to the latest git version.

**Comment by NenX** [comment] 2019-09-09 07:53
```bash
yarn cache clean
```
and then run
```bash
yarn
```

**Comment by ghasemikasra39** [comment] 2020-04-28 12:57
same here

**Comment by mcrisostomo** [comment] 2020-10-02 12:39
Thank you @rally25rs. You helped me a lot!

**Comment by kennethhuang31** [comment] 2021-03-27 09:48
> Oh yes, if you fail to proceed with yarn install because of this error, just delete your lockfile (`yarn.lock`) and run `yarn install` again

Thanks! This works for me.
