### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by leehaoChen** [yarnpkg/yarn#1179] opened 2016-10-18 01:37 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your node.js, yarn and operating system version.**
windows 10  node v4.4.7
$ yarn init
yarn init v0.15.1
error Can't answer a question unless a user TTY
    at ConsoleReporter.question (C:\Program Files (x86)\Yarn\lib-legacy\reporters\console\console-reporter.js:201:59)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\lib-legacy\cli\commands\init.js:97:38)
    at next (native)
    at step (C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at run (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:87:22)
    at C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\es6.promise.js:100:28
    at flush (C:\Program Files (x86)\Yarn\node_modules\core-js\library\modules\_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.

**Comment by Daniel15** [comment] 2016-10-18 04:09
Hi @leehaoChen! Currently there are some known issues when using Yarn with Cygwin or MinGW. I'd suggest using regular `cmd.exe` instead. See #743 for more details.

Going to close this as it's a duplicate of #743. Thank you for trying Yarn! 😄

**Closed by Daniel15** 2016-10-18 04:09 UTC
