### ISSUE TITLE
Couldn't install node-sass

### ISSUE THREAD

**Issue by opjlmi** [yarnpkg/yarn#1630] opened 2016-11-03 05:06 UTC
I use yarn 0.16.1 with node7, macOS 10.12.1
When I upgrade node-sass, it shows some error.
But I use npm to upgrade node-sass, it could works.

--
error node_modules/node-sass: Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/install.js
Directory: node_modules/node-sass
Output:
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at node_modules/node-sass/scripts/install.js:122:26
    at node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:111:15)

**Comment by Daniel15** [comment] 2016-11-03 06:16
Caused by #1632. I'm going to close this issue and you can subscribe to #1632 if you like. Thank you for trying Yarn! 😄

**Closed by Daniel15** 2016-11-03 06:16 UTC
