### ISSUE TITLE
possibility to specify cache-folder in yarnrc

### ISSUE THREAD

**Issue by ptrstpp950** [yarnpkg/yarn#1316] opened 2016-10-20 21:05 UTC
**Do you want to request a _feature_ or report a _bug_?**
A feature
**What is the current behavior?**
I don't know how to specify cache-folder in yarnrc. It is possible form CLI using --cache-folder option
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
An option in config
**Please mention your node.js, yarn and operating system version.**
yarn 16.1
node 6.5.0
windows 10

**Comment by mmerickel** [comment] 2016-10-21 19:41
I think this is a duplicate of #1211.

**Comment by victornoel** [comment] 2016-11-16 15:55
Would be a great feature!

**Comment by valscion** [comment] 2016-12-05 08:54
I suppose that yarn 0.18.0 released with PR #2046 makes this issue fixed, and this could be closed?

**Comment by wyze** [comment] 2016-12-05 14:27
Yup, thanks @valscion.

**Closed by wyze** 2016-12-05 14:27 UTC
Labels: needs triage
