### ISSUE TITLE
"yarn pack" never finishing hogging 100% CPU

### ISSUE THREAD

**Issue by frank-weindel** [yarnpkg/yarn#1352] opened 2016-10-21 18:38 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn pack` hangs with nearly 100% CPU utilization. I've left it running for 20 minutes and the only output is
```
yarn pack v0.16.1
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn pack` on a project with a `node_modules` folder previously installed with `yarn install`

**What is the expected behavior?**
`yarn pack` finishes in a reasonable amount of time (or reports by progress) and a tgz of dependencies is created

**Please mention your node.js, yarn and operating system version.**
node: v6.1.0
yarn: 0.16.1
mac OSX: 10.11.6

**Comment by Daniel15** [comment] 2016-10-22 06:05
Closing as duplicate of #1114. Thanks for trying Yarn!

**Closed by Daniel15** 2016-10-22 06:05 UTC
