### ISSUE TITLE
how to publish package to nexus

### ISSUE THREAD

**Issue by rejunjie** [yarnpkg/yarn#2865] opened 2017-03-08 07:44 UTC
yarn version：0.22
when I publish a package to nexus
then：
yarn publish v0.22.0
[1/4] Bumping version...
info Current version: 1.0.0
question New version:
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

**Comment by llwt** [comment] 2017-03-13 00:21
Running into the same thing but with Artifactory.

```
> Publishing module
yarn publish v0.21.3
[1/4] Bumping version...
info Current version: 2.0.0-yarn.12
info New version: 2.0.0-yarn.13
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
```

#2717 Seems to be the same issue.

Is there a debug flag we can enable to get more information on why this is failing?

**Comment by BYK** [comment] 2017-10-27 11:49
Duplicate of #2717 so closing.

>Is there a debug flag we can enable to get more information on why this is failing?

`--verbose` may be?

**Closed by BYK** 2017-10-27 11:49 UTC
Labels: bug-publishing, triaged
