### ISSUE TITLE
create-react-app with node-express server : Yarn not listing installed dependencies in package.json

### ISSUE THREAD

**Issue by arushi011** [yarnpkg/yarn#5286] opened 2018-01-27 07:26 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**  when Yarn comes with create-react-app and I move all contents to client directory and make another server.js in the root of the project to create a node server. It only lists dependency on yarn.lock and not package.json when in the root of the project.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create-react-app myWebApp
2. Make a directory in the root of project by the name "client"
3. Move all contents generated by step 1 in this directory
4. In the root of folder make a server.js and package.js
5. In package.js in the root of project copy this content: 
{
  "name": "example-create-react-app-express",
  "version": "1.0.0",
  "scripts": {
    "client": "cd client && yarn start",
    "server": "nodemon server.js",
    "dev": "concurrently --kill-others-on-fail \"yarn server\" \"yarn client\""
  },
  "dependencies": {
    "express": "^4.16.2"
  },
  "devDependencies": {
    "concurrently": "^3.5.0"
  }
}
6. In server.js copy:
const express = require('express');
const app = express();
const port = process.env.PORT || 5000;
app.listen(port, () => console.log(`Listening on port ${port}`));

7. Nodemon is already installed globally 
8. Run in the root of project command: yarn
9. In client/package.json add the following: "proxy": "http://localhost:5000/"
10. In the root of project run command: yarn dev
11. Your project will be running well and good in the browser
12. Now start adding dependencies using npm as npm install package_name
13. Here the first problem arises as the package.json in the root of the project will not be having all dependencies listed that yarn has added in step 8 but yarn.lock has.
14. The second problem is that when you run the command in step 12 the node starts removing dependencies that are in node_modules due to yarn.lock but not listed in package.json

**What is the expected behavior?** 
So either provide me a better way to work in create-react-app with creating node-express server without using yarn as I some added scripts in package.json in the root of the project that depends on yarn CLI as what could I do instead or tell me why yarn doesn't list those dependencies in package.json itself in step 8.

**Please mention your node.js, yarn and operating system version.** 5.5.1, 1.3.2, windows10, 64 bit

**Comment by rally25rs** [comment] 2018-01-29 19:28
This is roughly a duplicate of #5240 in that npm and yarn track packages differently / separately. At the moment you can't use them fully interchangeably. `npm add` to add packages will delete yarn installed packages, and of course `yarn.lock` will not be updated. I'm going to mark this closed as a duplicate because I think once that issue is resolved, it would fix this as well.

**Closed by rally25rs** 2018-01-29 19:28 UTC
Labels: triaged
