### ISSUE TITLE
Unable to set --no-bin-links via .yarnrc

### ISSUE THREAD

**Issue by edmorley** [yarnpkg/yarn#4925] opened 2017-11-14 17:49 UTC
Using yarn 1.3.2, I've tried all of the following permutations in a `.yarn.rc`, however none of them prevented bin link creation:
`no-bin-links true`
`bin-links false`
`binLinks false`

What's strange is that I'm able to enable `--ignores-engines` successfully using:
`ignore-engines true`

Inspecting the source I can't see a significant difference between the way the two preferences are listed, which would explain why the bin links option doesn't work but yet ignore engines does?

See:
https://github.com/yarnpkg/yarn/blob/v1.3.2/src/config.js#L41-L45

**Comment by rally25rs** [comment] 2017-11-14 18:54
Odd. I wonder if this is because the flag is `no-bin-links` but the config option is `binLinks`?

You should be able to use this in `.yarnrc`

```
--install.no-bin-links true
```

which will internally route that flag to the `install` command, but it probably won't pick it up for `upgrade` or `add` unless you add those as well.

It does seem like a primary `no-bin-links true` should work. I'll poke around and see if I can figure that out...

**Comment by rally25rs** [comment] 2017-11-15 14:22
It looks like there are a couple ways that options are loaded and retrieved in the code, and `binLinks` is being retrieved in such a way that it does not check `.yarnrc`

(specifically, `config.binLinks` is called instead of `config.getOption('binLinks')`)

IMO there is some technical debt built up in the whole "config" system that needs some cleanup and refactoring. This issue could be fixed as part of a larger effort to clean up the config code.

**Comment by edmorley** [comment] 2017-11-20 13:42
Ah thank you for looking into that!

In the meantime I've found that this works:
`--*.no-bin-links true`

(The docs don't mention being able to use a wildcard, which is necessary for this flag, since it affects not just install, but add, upgrade, upgrade-interactive etc)

**Comment by kaylieEB** [comment] 2018-03-05 21:25
Closing this since it's still working as intended --

**Closed by kaylieEB** 2018-03-05 21:25 UTC
Labels: cat-bug, triaged

**Comment by edmorley** [comment] 2018-03-05 21:30
Could the docs be updated to make this clearer, given:

> (The docs don't mention being able to use a wildcard, which is necessary for this flag, since it affects not just install, but add, upgrade, upgrade-interactive etc)
