### ISSUE TITLE
can not add pkg from local registry server, because of something wrong with request URL

### ISSUE THREAD

**Issue by ronnin** [yarnpkg/yarn#4378] opened 2017-09-10 04:01 UTC
$ yarn config get registry
**http://repo.office.com/repository/npm-public**

$ yarn add elasticsearch --verbose
....
verbose 0.741 Performing "GET" request to "**http://repo.office.com/repository/elasticsearch**".
verbose 0.807 Request "http://repo.office.com/repository/elasticsearch" finished with status code 400.
verbose 0.808 Error: Couldn't find package "elasticsearch" on the "npm" registry.

$ yarn --version
1.0.1

last part of url **npm-public** has cut off

repo.office.com is my local configured domain name

**Comment by nadavsinai** [comment] 2017-09-10 13:06
I can confirm I have similar problems with version 1.0.1 - I reverted to 0.28.4 and the problem is gone.
version 1.0.1 is unusable with scoped packages on private repos, i'd be happy to help if more info is needed

**Comment by BYK** [comment] 2017-09-10 15:06
I think this is a duplicate of #4339 and is fixed on master. We are aiming for a 1.0.2 release very soon. Sorry for the inconvenience :(

In the meantime you can try the nightlies: https://yarnpkg.com/en/docs/nightly

**Closed by BYK** 2017-09-10 15:06 UTC
