### ISSUE TITLE
Yarn add <git-package> does not respect package.json-files setting

### ISSUE THREAD

**Issue by timephy** [yarnpkg/yarn#6589] opened 2018-10-27 21:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature, i guess

**What is the current behavior?**
Yarn installs git repo/package with all files and not just the files specified in package.json

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Preferably yarn should only install files listed in package.json (as if it was packaged with yarn pack)
NPM works the preferred way.

**Please mention your node.js, yarn and operating system version.**
8.11.1, 1.10.1, macOS 10.14

**Comment by rally25rs** [comment] 2018-10-29 18:51
duplicate of #2822

Yarn only considers `files` during the `pack` of the deployable tarball.

**Closed by rally25rs** 2018-10-29 18:51 UTC
Labels: triaged
