### ISSUE TITLE
Perform retry for 50x errors

### ISSUE THREAD

**Issue by ishitatsuyuki** [yarnpkg/yarn#5547] opened 2018-03-20 11:20 UTC
Things like S3 has a possibility to return 50x errors temporarily.

```
https://registry.yarnpkg.com/@theia/file-search/-/file-search-0.4.0-next.bace685a.tgz: Request failed \"503 Service Unavailable\"
```

We should implement retry on 50x just as what we do for network errors, preferably with exponential backoff.

**Comment by jbmusso** [comment] 2018-06-06 16:12
Possible duplicate of https://github.com/yarnpkg/yarn/issues/2849

**Comment by ishitatsuyuki** [comment] 2018-06-07 05:39
I think I was running yarn 1.x at that time and it seems that the patch wasn't working as intended.

**Comment by jollytoad** [comment] 2019-01-24 08:51
This definitely still a problem, i'm getting annoying failures on CI builds...

An unexpected error occurred: "https://registry.yarnpkg.com/@storybook/addon-actions/-/addon-actions-4.1.9.tgz: Request failed \"500 Internal Server Error\""

An unexpected error occurred: "https://registry.yarnpkg.com/@atlaskit/theme/-/theme-7.0.4.tgz: Request failed \"500 Internal Server Error\"".

and a couple more within the last few hours.

**Comment by jkumar-roambee** [comment] 2019-01-24 09:18
Facing the same issue..  | Yarn : v1.3.2 | 

Fetching packages...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular-devkit/build-optimizer/-/build-optimizer-0.0.13.tgz: Request failed \"500 Internal Server Error\"".

**Comment by jogendrajangid1** [comment] 2019-01-24 09:19
Facing the same issue | Yarn : v1.3.2 |

Fetching packages...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
warning There appears to be trouble with our server. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular-devkit/build-optimizer/-/build-optimizer-0.0.13.tgz: Request failed "500 Internal Server Error"".

**Comment by merceyz** [comment] 2021-01-04 01:08
Closing as fixed in v2 where failed requests are automatically retried

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-04 01:08 UTC
Labels: triaged
