### ISSUE TITLE
Does not always handle malformed package.json gracefully

### ISSUE THREAD

**Issue by panozzaj** [yarnpkg/yarn#1448] opened 2016-10-25 17:13 UTC
First, thanks for your work on this project. I was overjoyed to hear about it! It seems like it solves many problems in the Node package management space.

**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When I remove a comma in my `package.json` file that separates two sections, I get the following error message:

```
$ yarn
yarn install v0.16.1
error An unexpected error occured, please open a bug report with the information provided in "/mypath/myproject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The error log gives the following message:

```
...

Trace:
  SyntaxError: /mypath/myproject/package.json: Unexpected string
      at Object.parse (native)
      at /Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/lib/util/fs.js:271:57
      at next (native)
      at step (/Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:20
      at run (/Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
      at /Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
      at flush (/Users/apanozzo/.nvm/versions/node/v5.11.1/lib/node_modules/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

On my project I already have a `yarn.lock` file.

Take an existing working package.json file. Remove a comma from it. Attempt to run `yarn` (`yarn install`).

Example:

```
    "scripts": {
      "lint": "eslint webpack --ext .js --ext .jsx"
-   },
+   }
   "repository": {
```

**What is the expected behavior?**

I think that Yarn should attempt to parse the JSON file, and if it gets an error, to then give me hints on how to fix it. In my case it was easy since I recently changed that file, but it might have been harder to track down. It's not immediately clear from the error in the file what the issue is. I also saw what NPM says when I try to run `npm install` with the same `package.json` file:

```
npm WARN Failed to parse json
npm WARN Unexpected token 'r' at 44:4
npm WARN   "repository": {
npm WARN    ^
npm WARN File: /mypath/myproject/package.json
```

This at helps guide me to look around where the underlying problem is.

**Please mention your node.js, yarn and operating system version.**

```
$ nvm list
->      v5.11.1
```

```
$ yarn --version
0.16.1
```

Mac OS X El Capitan (10.11.6)

**Comment by alecharmon** [comment] 2016-10-25 17:54
👋 ill take a stab at it later today

**Comment by wyze** [comment] 2016-10-25 21:09
This is duplicate of #1229 and was fixed in #1424.

Now when ran against master:

```sh
$ yarn
info No lockfile found.
error Error parsing JSON at "/Users/neil/Projects/external/yarn-example/package.json", "/Users/neil/Projects/external/yarn-example/package.json: Unexpected token } in JSON at position 144".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Closed by wyze** 2016-10-25 21:09 UTC
Labels: compatibility, enhancement, good first bug

**Comment by alecharmon** [comment] 2016-10-25 21:13
@panozzaj yea, after `git pull` i could not replicate

**Comment by panozzaj** [comment] 2016-10-25 21:59
Sorry for the red herring, and thanks for taking the time to look at this!

The pull request template said to use the latest version and I interpreted
that as the last official release. But maybe it could be updated to say to
use master instead while the project is newish or in flux if that is more
accurate generally. I would be happy to amend the PR template if it would
cut down on ambiguity. Let me know if you would find that helpful and I can
make a PR. Thanks again!

**Comment by wyze** [comment] 2016-10-25 22:02
@panozzaj, thanks for your feedback. Don't quote me on this as I am new here, but I think the official releases are planned to be every 2 weeks. In the mean time, @Daniel15 is working on nightly builds to fill the gaps between official releases!

**Comment by panozzaj** [comment] 2016-10-25 22:23
Super cool, thanks again Neil!

**Comment by Daniel15** [comment] 2016-10-26 00:00
Yes, we're going to have nightly releases very soon, along with easy ways to install them 😄
