### ISSUE TITLE
The `punycode` module is deprecated

### ISSUE THREAD

**Issue by hisreal123** [yarnpkg/yarn#9022] opened 2023-12-29 20:36 UTC
Am still yet to fix the deprecation warning. 

NODE_OPTIONS='--trace-deprecation' yarn info yarn description
yarn info v1.22.21
(node:105024) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:397:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:333:10)
    at loadBuiltinModule (node:internal/modules/helpers:101:7)
    at Module._load (node:internal/modules/cjs/loader:1001:17)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/lib/node_modules/yarn/node_modules/normalize-url/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
📦🐈 Fast, reliable, and secure dependency management.
Done in 9.40s.

i hope you can help with, or point me to the fix
Thanks

**Comment by MikeMcC399** [comment] 2024-01-06 13:51
@hisreal123 

- This is a duplicate of issue https://github.com/yarnpkg/yarn/issues/9013

I suggest you close this issue and subscribe to the existing issue #9013.

**Comment by RDIL** [comment] 2024-01-23 14:18
Duplicate of #9013

**Closed by RDIL** 2024-01-23 14:18 UTC

**Comment by saoud77** [comment] 2024-08-05 19:37
By downgrading Node.js from version 22 to version 20, I was able to resolve the issue.
