### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by darrenjennings** [yarnpkg/yarn#7026] opened 2019-02-12 21:29 UTC
Been noticing `502 Bad Gateway` pretty often the last couple days. Looks like it's coming from cloudflare and is easily reproducible by just browsing to https://registry.yarnpkg.com/ and refreshing a few times.

**Comment by andypillip** [comment] 2019-07-16 18:31
I guess this got resolved in the meantime? I cannot reproduce.

**Comment by paul-soporan** [comment] 2021-01-03 00:21
Closing as this has been resolved.

**Closed by paul-soporan** 2021-01-03 00:21 UTC
Labels: triaged
