### ISSUE TITLE
`yarn install --production` checks `devDependencies`

### ISSUE THREAD

**Issue by dizel3d** [yarnpkg/yarn#7184] opened 2019-04-09 13:48 UTC
**Do you want to request a feature or report a bug?**
bug

**What is the current behavior?**
`yarn install --production` checks `devDependencies`. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create `package.json`:
```json
{
  "private": true,
  "dependencies": {
    "lodash": "*"
  },
  "devDependencies": {
    "non-existant-module": "*"
  }
}
```
Run in terminal:
```bash
yarn install --production
```
Output:
```text
error Couldn't find package "non-existant-module" on the "npm" registry.
```

**What is the expected behavior?**
Successful installation.

**Please mention your node.js, yarn and operating system version.**
Yarn 1.15.2
Node v8.6.0
Mac OS 10.13.6

**Comment by rally25rs** [comment] 2019-04-11 12:13
duplicate of #3630

**Closed by rally25rs** 2019-04-11 12:13 UTC
