### ISSUE TITLE
Error: Couldn't find the binary git

### ISSUE THREAD

**Issue by jdmunro** [yarnpkg/yarn#2083] opened 2016-11-30 11:16 UTC
I am using:

* yarn v0.17.9
* macOS Sierra 10.12.1
* Node v6.9.1

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Trying to install packages using yarn. Outputs a strange error message:

```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error Couldn't find the binary git
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn --pure-lockfile
```

Outputs the above error message.

Git is installed:

```
Admins-Mac-mini:BWA-BETA203-FAST admin$ whereis git
/usr/bin/git
```

**What is the expected behavior?**

Yarn should install the packages without emitting an error about git. If I run this command using an older version of yarn, v0.16.1, everything is fine.

**Comment by kittens** [comment] 2016-12-01 12:27
What's the result of `which git`?

**Comment by jdmunro** [comment] 2016-12-01 16:01
```
Admins-Mac-mini:~ admin$ which git
/usr/local/bin/git
```

That's a different path to ```whereis git```.

**Comment by emolchanov** [comment] 2016-12-07 09:43
+1 - same problem macOS 10.12.1

```
yarn --version
0.17.10

node -v
v6.9.1

which git                           
/usr/local/bin/git

whereis git
/usr/bin/git

```

and on windows 7 and 10 with [git-scm](https://git-scm.com/)

**Comment by Congelli501** [comment] 2016-12-22 14:39
I have the same problem under ubuntu 16.04, dans yarn 18.1.

The reported error is bad:
The node spawn call return a "ENOENT" error (https://github.com/yarnpkg/yarn/blob/master/src/util/child.js#L41)
This is not caused by the git binary not found, but by the `cwd` given in `opts` witch is not found.


This is because of the `supportsArchive` boolean:
 - either archive is not supported, and everything is cloned locally.
 - or archive is used and nothing is cloned

However, supportArchive can change while nothing was cloned (https://github.com/yarnpkg/yarn/blob/master/src/util/git.js#L338).

**Comment by vitch** [comment] 2017-01-13 11:42
Same thing happened to me after a `yarn cache clean` (trying to get a git branch dependency to update).

Removing the `node_modules` folder and running `yarn` again seemed to work around the issue.

**Comment by flocsy** [comment] 2017-01-15 08:37
this happens here too after `yarn cache clean`

**Comment by emmanuel-isaac** [comment] 2017-01-17 13:36
I am experiencing this issue too. I started seeing it after running ```yarn cache clean && yarn clean```

**Comment by flocsy** [comment] 2017-01-18 14:59
Unfortunately even deleting node_modules/ doesn't fix the problem

**Comment by sirbarrence** [comment] 2017-01-18 16:13
This seems to happen to me when using a "git+ssh" dependency where the commit hash is not at the HEAD of the branch. For example, my lockfile contains something like:

```
"foo-bar-baz@git+ssh://git@my-internal-git-host.dev:7999/asdf/foo-bar-baz.git":
  version "2.2.2"
  resolved "git@my-internal-git-host.dev:7999/asdf/foo-bar-baz.git#a5e6897042a496d70dbc57b1de8f8df5e8c0369c"
  dependencies:
...
```

At first, a5e6897042a496d70dbc57b1de8f8df5e8c0369c was the HEAD of the repo and yarn install worked fine. But when I committed some new revs to foo-bar-baz.git without updating the lockfile of the package making use of foo-bar-baz (because I didn't need to yet), then `yarn install` started failing with the 'Couldn't find the binary git' message.

a5e6897042a496d70dbc57b1de8f8df5e8c0369c still exists in the repo and npm can install it just fine.

If I manually change the commit hash in the lockfile to whatever the HEAD commit hash is in foo-bar-baz.git, `yarn install` starts working again.

Starting with an empty cache definitely triggers this behavior. Starting with previously cached packages may or may not trigger it. Not sure why.

**Comment by Nighthawk22** [comment] 2017-01-20 07:08
Had the same problem as @sirbarrence . After removing the lockfile it worked again

**Comment by vitch** [comment] 2017-01-20 12:30
Thanks @sirbarrence - that was spot on. If the commit referred to in `yarn.lock` isn't the head of the referenced branch then we get the error. The workaround is to manually edit the `yarn.lock` file and delete the section for the dependency in question. Running `yarn` again after this works and picks up the new commit.

**Comment by sirbarrence** [comment] 2017-01-20 14:29
Thanks @vitch that can work for local development. For automated builds where manual intervention is undesirable or builds where you can't use the HEAD of the dependency yet for compatibility reasons, I'm having to consider reverting to npm until this is resolved.

**Comment by jcurtis** [comment] 2017-02-02 19:35
Seeing this as well - exactly the same setup as @sirbarrence 

Looks like it might be fixed in 0.20 - https://github.com/yarnpkg/yarn/releases/tag/v0.20.0

![image](https://cloud.githubusercontent.com/assets/206295/22565087/494d59d6-e95d-11e6-9a25-f68917d69886.png)

**Comment by shprink** [comment] 2017-02-15 14:33
I confirm that 0.20 fixes it

**Comment by wufeng87** [comment] 2017-02-20 00:58
Happens with yarn 0.20.3 Node 6.9.5.

E:\codes\js\react\relax-master>yarn --version
0.20.3

E:\codes\js\react\relax-master>node -v
v6.9.5

E:\codes\js\react\relax-master>yarn install
yarn install v0.20.3
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by ricardogama** [comment] 2017-03-08 14:20
This still happens with `v0.21.3` and it doesn't seem related to the hashed resolved in `yarn.lock`.

**Comment by rjnienaber** [comment] 2017-03-14 22:31
I was having this same issue on yarn `0.21.3`. Switching from the abbreviated SHA commit hash to the full SHA commit hash solved the problem for me.

**Comment by alansouzati** [comment] 2017-04-11 17:12
I cannot experience this problem locally, but my CI (Drone CI) keeps hitting this problem. We have the same yarn version.

**Comment by ricardogama** [comment] 2017-04-11 17:23
@alansouzati I believe you need to install **git** previously, for example:

```yml
pipeline:
  test:
    image: node:7-alpine
    commands:
      - apk add --no-cache git
      - yarn
```

**Comment by alansouzati** [comment] 2017-04-11 17:37
thanks @ricardogama, my CI is passing now.

**Comment by Congelli501** [comment] 2017-04-12 06:25
I think this issue should be marked as resolved now.
The fix has been merged and is in the stable releases for a long time.

**Comment by nottrobin** [comment] 2017-09-23 09:10
I'm seeing this issue on Ubuntu 16.04, because nodejs is still at version 4.*.*. If I upgrade to 6.*.* it seems to fix it.

**Comment by BYK** [comment] 2017-10-27 12:11
Closed since this seems to be resolved in recent versions.

**Closed** 2017-10-27 12:10 UTC
Labels: cat-bug

**Comment by jdmunro** [comment] 2017-10-27 15:41
Yep - definitely resolved for me.

**Comment by mashirozx** [comment] 2017-12-02 16:22
Still meet this trouble on Windows, with Node v8.9.1;  yarn 1.3.2; npm 5.5.1.
Meet this promblem both by install with `yarn-1.3.2.msi`  and with `$ npm install -g yarn`. 😭

**Comment by simonbuchan** [comment] 2018-02-20 22:14
I just hit this on the current `node:9-alpine` image, and my `yarn.lock` doesn't have any `git+ssh` deps, but does have an `yeoman-generator "https://github.com/ev1stensberg/generator.git#Feature-getArgument"` via `webpack-cli`

```
Using Docker executor with image node:9-alpine ...
Using docker image sha256:12be62a1f685f3f79041ec45abd2d7b8cc7d6f12a7f65c9071b6a4356cd1d352 for predefined container...
Pulling docker image node:9-alpine ...
Using docker image node:9-alpine ID=sha256:e90a5bfd29f6e9ea9f7813c0bed6350d7c5a07efc689a4b553ac6ae10abf1f90 for build container...
Running on runner-b2c67c2a-project-59-concurrent-0 via b3c8740cb0fc...
Cloning repository...
Cloning into '/builds/interact/example-keyword-parser'...
Checking out 83d17370 as master...
Skipping Git submodules setup
Checking cache for default...
FATAL: file does not exist                         
Failed to extract cache
$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1
```

Do you want a new issue?

**Comment by jayalakshmis** [comment] 2018-03-16 00:15
1.5.1 and still the same issue

**Comment by p0tz** [comment] 2018-04-28 13:32
Requires git to build your computer. https://git-scm.com/﻿

**Comment by mikebridge** [comment] 2018-07-10 16:29
I am running git from Ubuntu/WSL via PowerShell on Windows 10 using this `git.bat` in my path:

```
@echo off
setlocal enabledelayedexpansion
set command=%*
If %PROCESSOR_ARCHITECTURE% == x86 (
    echo | C:\Windows\sysnative\bash.exe -c 'git %command%'
) Else (
    echo | bash.exe -c 'git %command%'
)
```

Git works OK from PowerShell but not from Yarn-within-powershell:

```
PS C:\temp> git --version
git version 2.7.4
PS C:\temp> yarn --version
1.7.0
PS C:\temp> node --version
v8.11.3
PS C:\temp> yarn install
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Rialgar** [comment] 2018-10-18 10:57
For reference: when I had this error message, adding `ssh://` resolved it for me. npm is able to deal with `git+git@github.com:etc`, but yarn required `git+ssh://git@github.com:etc`. The error message was not helpful to understand what was wrong, I had to see here that basically any error while fetching a git dependency causes this message to even consider that my dependency spec may need to be changed.

yarn -v shows 1.10.1

**Comment by em9790** [comment] 2019-05-31 10:12
Delete yarn.lock file
Try to run yarn install

**Comment by ghanbari** [comment] 2019-06-15 13:52
@ricardogama thanks, i have same problem in `node:11.5-alpine`, after install git by apk it solved

**Comment by jake-wickstrom-lb** [comment] 2019-07-11 23:57
This issue is still occurring for me when run on my Jenkins server (although fine locally).

Node: 12.6.0 
Yarn:   1.16.0

I can find the full repository that I am trying to install in the Yarn/Cache folder, so the failure must be occuring after yarn performs the git clone (so yarn also clearly has access to the git binary at some point to be able to clone)

I tried the various git+ssh://... suggestions above with no success. Any other ideas?

**Comment by inqueez** [comment] 2019-08-27 14:47
Hey! I found that problem occurs in case when you add a dependency, this way
```
    "@assets/sprintf": "https://github.com/alexei/sprintf.js#^1.1.1",
``` 

after I changed this line to 

```
    "@assets/sprintf": "alexei/sprintf.js#^1.1.1",
```

the problem is gone

**Comment by umairraza101** [comment] 2019-10-07 19:48
> For reference: when I had this error message, adding `ssh://` resolved it for me. npm is able to deal with `git+git@github.com:etc`, but yarn required `git+ssh://git@github.com:etc`. The error message was not helpful to understand what was wrong, I had to see here that basically any error while fetching a git dependency causes this message to even consider that my dependency spec may need to be changed.
> 
> yarn -v shows 1.10.1

Thanks, this is working for me now

**Comment by maycom10110** [comment] 2020-02-10 22:39
I solved this error by installing git on my computer

**Comment by milosdavidovic** [comment] 2020-03-16 10:05
Sometimes it could be just that path to git is not added to the PATH environmental variable.
For Windows add these two (adjust if git is installed on different location):
C:\Program Files\Git\bin\
C:\Program Files\Git\cmd\

**Comment by swushi** [comment] 2020-03-30 23:26
Install git at [](https://git-scm.com/)
Run `yarn cache clean` and delete node_modules folder
Restart your terminal (To make sure that it recognizes that git is now installed)

**Comment by colemars** [comment] 2020-04-20 14:55
> Hey! I found that problem occurs in case when you add a dependency, this way
> 
> ```
>     "@assets/sprintf": "https://github.com/alexei/sprintf.js#^1.1.1",
> ```
> 
> after I changed this line to
> 
> ```
>     "@assets/sprintf": "alexei/sprintf.js#^1.1.1",
> ```
> 
> the problem is gone

But why though

**Comment by syedarifandrabi** [comment] 2020-06-14 13:01
simply install git on your system

**Comment by ArchanaShahRS** [comment] 2020-06-21 16:31
1. Use the following link to download Git
     https://git-scm.com/download
2. Install it in your machine.
3. Restart your machine.
4. Try running same command again and it will no more throw error.
Thanks @swushi It worked.

**Comment by Moggieggwp** [comment] 2020-08-03 10:53
Have you correctly set your PATH to point at your Git installation?

You need to add the following paths to PATH:

C:\Program Files\Git\bin\
C:\Program Files\Git\cmd\
And check that these paths are correct – you may have Git installed on a different drive, or under Program Files (x86). Correct the paths if necessary.

**Comment by lynshashank** [comment] 2020-09-01 11:01
> @alansouzati I believe you need to install **git** previously, for example:
> 
> ```yaml
> pipeline:
>   test:
>     image: node:7-alpine
>     commands:
>       - apk add --no-cache git
>       - yarn
> ```

Can u please elaborate how you ha done this ??

**Comment by Birdy94** [comment] 2020-09-30 18:53
> Have you correctly set your PATH to point at your Git installation?
> 
> You need to add the following paths to PATH:
> 
> C:\Program Files\Git\bin
> C:\Program Files\Git\cmd
> And check that these paths are correct – you may have Git installed on a different drive, or under Program Files (x86). Correct the paths if necessary.

Had to restart windows my PC then it worked after doing this (y)

**Comment by lapwat** [comment] 2021-05-22 16:43
> > @alansouzati I believe you need to install **git** previously, for example:
> > ```yaml
> > pipeline:
> >   test:
> >     image: node:7-alpine
> >     commands:
> >       - apk add --no-cache git
> >       - yarn
> > ```
> 
> Can u please elaborate how you had done this ??

If you get this error when executing `yarn` in a `Dockerfile`, install `git` in your image.

```dockerfile
RUN apk add --no-cache git
```

**Comment by sdaminul** [comment] 2022-02-01 03:10
**### Install Git In your Computer.**

**Comment by Adison-Masih** [comment] 2022-05-12 14:12
> Had the same problem as @sirbarrence . After removing the lockfile it worked again

Yes, Delete The `yarn.lock` file and it will start working again! thanks!

**Comment by LAART66** [comment] 2022-06-25 18:00
Hello I have same problem with lunching an yarn. When I lunch commend yarn it write me this (look bold text):

yarn install v1.22.19
warning package.json: No license field
warning @hashlips-lab/nft-erc721-collection-smart-contract@1.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
**error Couldn't find the binary git**
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


Can somebody help me, please??

**Comment by lapwat** [comment] 2022-06-28 14:52
@LAART66 you need to install Git on your computer

**Comment by ackvf** [comment] 2022-11-21 20:32
I wonder why this is still necessary on my end when trying to install & build an app inside a docker?

```
RUN apk add --no-cache git
```

**Comment by lapwat** [comment] 2022-11-23 12:39
> I wonder why this is still necessary on my end when trying to install & build an app inside a docker?
> 
> ```dockerfile
> RUN apk add --no-cache git
> ```

Because `git` is not shipped by default in the image you are using, and it is needed to download the dependencies of your app with `yarn install`.

I think that you can build without `git` if you have no external dependencies or if you copy the whole source code (app + deps) inside the container.
