### ISSUE TITLE
yarn doesn't do anything when adding `socket.io` dependency

### ISSUE THREAD

**Issue by ianstormtaylor** [yarnpkg/yarn#4653] opened 2017-10-06 21:45 UTC
First, with no dependencies:

```bash
$ yarn
yarn install v1.0.1
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

info Lockfile not saved, no dependencies.
✨  Done in 0.05s.
```

Then adding `socket.io`:

```bash
$ yarn add socket.io
yarn add v1.0.1
warning package.json: No license field
info No lockfile found.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
⠁ 
[1/1] ⠂ uws
[1/1] ⢀ uws
[1/1] ⠂ uws
[1/1] ⠐ uws
[1/1] ⠄ uws
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
[-/1] ⠄ waiting...
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/ansi-regex shouldn't be copied twice in one bulk copy
[1/1] ⡀ uws
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[1/1] ⢀ uws
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
[-/1] ⢀ waiting...
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/.npmignore shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/.travis.yml shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/CHANGELOG.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/bin shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/examples shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/test shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/strip-ansi/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/strip-ansi/license shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/strip-ansi/package.json shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/strip-ansi/readme.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/LICENSE shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/README.md shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/index.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/package.json shouldn't be copied twice in one bulk copy
[1/1] ⠠ uws
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/bin/nopt.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/examples/my-program.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/test/basic.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/nopt/lib/nopt.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/create.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/extract.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/header.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/high-level-opt.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/large-numbers.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/list.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/mkdir.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/pack.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/parse.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/pax.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/read-entry.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/replace.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/types.js shouldn't be copied twice in one bulk copy
warning The case-insensitive file /Users/Storm/.config/yarn/global/node_modules/npm/node_modules/tar/lib/unpack.js shouldn't be copied twice in one bulk copy
[1/1] ⢀ uws
[1/1] ⠠ uws
[-/1] ⠠ waiting...
success Saved lockfile.
success Saved 40 new dependencies.
├─ accepts@1.3.3
├─ after@0.8.2
├─ arraybuffer.slice@0.0.6
├─ backo2@1.0.2
├─ base64-arraybuffer@0.1.5
├─ base64id@1.0.0
├─ better-assert@1.0.2
├─ blob@0.0.4
├─ callsite@1.0.0
├─ component-bind@1.0.0
├─ component-emitter@1.2.1
├─ component-inherit@0.0.3
├─ cookie@0.3.1
├─ debug@2.6.9
├─ engine.io-client@3.1.2
├─ engine.io-parser@2.1.1
├─ engine.io@3.1.2
├─ has-binary2@1.0.2
├─ has-cors@1.1.0
├─ indexof@0.0.1
├─ isarray@2.0.1
├─ mime-db@1.30.0
├─ mime-types@2.1.17
├─ ms@2.0.0
├─ negotiator@0.6.1
├─ object-assign@4.1.1
├─ object-component@0.0.3
├─ parseqs@0.0.5
├─ parseuri@0.0.5
├─ safe-buffer@5.0.1
├─ socket.io-adapter@1.1.1
├─ socket.io-client@2.0.3
├─ socket.io-parser@3.1.2
├─ socket.io@2.0.3
├─ to-array@0.1.4
├─ ultron@1.1.0
├─ uws@0.14.5
├─ ws@2.3.1
├─ xmlhttprequest-ssl@1.5.3
└─ yeast@0.1.2
✨  Done in 6.76s.
```

But `package.json` wasn't updated:

```bash
$ cat package.json 
{
  "name": "test",
  "dependencies": {}
}
```

And there's no `yarn.lock` file created:

```bash
$ ls 
node_modules package.json
```

---

System information:

```bash
$ node -v
v6.9.5
$ yarn --version
1.0.1
$ yarn global list
yarn global v1.1.0
info "lerna@2.4.0" has binaries:
   - lerna
info "node-gyp@3.6.2" has binaries:
   - node-gyp
info "npm@5.5.1" has binaries:
   - npm
   - npx
✨  Done in 5.77s.
```

And I just tried with `1.1.0`, same issue.

**Comment by ianstormtaylor** [comment] 2017-10-06 21:50
Further, if you manually add `socket.io` to `dependencies`, then any attempt to use `yarn` will not update the lock file in the future, and so every time you try to run any other yarn commands, you'll end up getting:

```bash
yarn upgrade v1.1.0
error Outdated lockfile. Please run `yarn install` and try again.
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

Basically seems impossible to use `socket.io`?

**Comment by ianstormtaylor** [comment] 2017-10-06 21:53
Sometimes, `yarn add socket.io` won't actually finish, it will just hang will building the `uws` package. So potentially this is related to https://github.com/yarnpkg/yarn/issues/3867?

**Comment by jharris4** [comment] 2017-10-06 22:22
@ianstormtaylor This is the exact issue I stumbled on in #3728 

You can work around the issue by just running `npm i -g node-gyp`

**Comment by ianstormtaylor** [comment] 2017-10-06 22:31
Ah shoot, I had been doing `yarn global add node-gyp` instead of the `npm` variant. Thank you very much @jharris4!

**Comment by BYK** [comment] 2017-10-07 18:49
Duplicate of #3728.

**Closed by BYK** 2017-10-07 18:49 UTC
