### ISSUE TITLE
"Yarn outdated" errors with @exponent/ex-navigation

### ISSUE THREAD

**Issue by wietsevenema** [yarnpkg/yarn#1234] opened 2016-10-19 06:59 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn outdated` errors if @exponent/ex-navigation is a dependency. 

**If the current behavior is a bug, please provide the steps to reproduce.**
```
$: yarn init
...
$: yarn add @exponent/ex-navigation
...
$: yarn outdated
yarn outdated v0.16.0
error An unexpected error occured, please open a bug report with the information provided in "/yarn-error.log".
```
The error says: 
`Error: https://registry.yarnpkg.com/@exponent/ex-navigation: Not found`

**What is the expected behavior?**
I would expect no error

**Please mention your node.js, yarn and operating system version.**
Yarn version: 
  0.16.0
Node version: 
  6.8.1
Platform: 
  darwin x64

**Comment by jsynowiec** [comment] 2016-10-19 07:39
Duplicate of #620

**Comment by wietsevenema** [comment] 2016-10-19 12:49
Confirmed that this is a duplicate. You can close this if you want.

**Closed** 2016-10-24 16:10 UTC
