### ISSUE TITLE
yarn pack not packaging node_modules for bundledDependencies

### ISSUE THREAD

**Issue by rufman** [yarnpkg/yarn#3423] opened 2017-05-16 17:42 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
`yarn pack` on a package with bundled dependencies does not include `node_modules`, whereas `npm pack` does.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Create a `package.json` with specifying `bundledDependencies`
- Run `npm pack`
- Run `yarn pack`
- Untar both. The tgz generated by npm includes the bundled dependencies, where as yarn does not

**What is the expected behavior?**
Bundled dependencies should be distributed with the package

**Please mention your node.js, yarn and operating system version.**
Node: v7.10.0
Yarn: 0.24.4
OS: MacOS 10.12.4

**Comment by kmdm** [comment] 2017-05-17 09:35
Probable duplicate of #2636

**Closed** 2017-05-23 16:55 UTC
Labels: triaged
