### ISSUE TITLE
Git repositories

### ISSUE THREAD

**Issue by scboffspring** [yarnpkg/yarn#604] opened 2016-10-11 15:32 UTC
Hi,

I just tried to use yarn on one of my existing projects, and it seems to no support git repositories as package source.

Example package.json:
`
...
"sequelize": "git+https://git@github.com/sequelize/sequelize.git",
...`

Is it intended, or is it a missing feature ?

Thanks

**Comment by thejameskyle** [comment] 2016-10-11 15:33
That should be working, can you paste the output you get?

**Comment by vutran** [comment] 2016-10-11 15:33
I'm getting the same issue but am using a private github repo.

**Comment by scboffspring** [comment] 2016-10-11 15:35
Here is the error I am getting : 

error Couldn't find any versions for sequelize that matches ```
git+https://git@github.com/sequelize/sequelize.git. Possible versions: 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4.0, 1.4.1, 1.5.0-alpha, 1.5.0-beta, 1.5.0-beta-2, 1.5.0, 1.6.0-alpha-1, 1.6.0-alpha-2, 1.6.0-alpha-3, 1.6.0-beta-1, 1.6.0-beta-2, 1.6.0-beta-3, 1.6.0-beta4, 1.6.0, 1.7.0-alpha1, 1.7.0-alpha2, 2.0.0-alpha1, 2.0.0-alpha2, 1.7.0-alpha3, 2.0.0-alpha3, 1.7.0-beta.0, 2.0.0-beta.0, 1.7.0-beta.1, 2.0.0-beta.1, 1.7.0-beta.2, 2.0.0-beta.2, 1.7.0-beta.3b, 2.0.0-beta.3, 1.7.0-beta.4a, 2.0.0-beta.4, 1.7.0-beta.5, 2.0.0-beta.5, 1.7.0-beta6, 2.0.0-beta.6, 1.7.0-beta7, 2.0.0-beta.7, 2.0.0-beta.8, 1.7.0-beta8, 1.7.0-rc1, 2.0.0-dev1, 1.7.0-rc2, 2.0.0-dev2, 1.7.0-rc3, 2.0.0-dev3, 1.7.0-rc4, 2.0.0-dev4, 2.0.0-dev5, 1.7.0-rc5, 1.7.0-rc6, 2.0.0-dev6, 2.0.0-dev7, 1.7.0-rc7, 2.0.0-dev8, 1.7.0-rc8, 1.7.0-rc9, 2.0.0-dev9, 2.0.0-dev10, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 2.0.0-dev11, 1.7.4, 1.7.5, 1.7.7, 1.7.8, 1.7.9, 2.0.0-dev12, 1.7.10, 2.0.0-dev13, 2.0.0-rc1, 2.0.0-rc2, 2.0.0-rc3, 2.0.0-rc4, 2.0.0-rc5, 2.0.0-rc6, 2.0.0-rc7, 2.0.0-rc8, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 3.0.0, 3.0.1, 3.1.0, 3.1.1, 3.2.0, 1.7.11, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.5.0, 3.5.1, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.9.0, 3.10.0, 3.11.0, 3.12.0, 3.12.1, 3.12.2, 3.13.0, 3.14.0, 3.14.1, 3.14.2, 3.15.0, 3.15.1, 3.16.0, 3.17.0, 3.17.1, 3.17.2, 3.17.3, 3.18.0, 3.19.0, 3.19.1, 3.19.2, 3.19.3, 3.20.0, 3.21.0, 3.22.0, 3.23.0, 3.23.1, 3.23.2, 3.23.3, 4.0.0-0, 3.23.4, 3.23.5, 3.23.6, 3.24.0, 3.24.1, 4.0.0-1, 3.24.2, 4.0.0-2, 3.24.3
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command
```

**Comment by danharper** [comment] 2016-10-11 15:36
Getting the same issue.

Section of my `package.json`:

```
"eslint-config-radweb": "git+https://git@github.com/radweb/eslint-config-radweb.git"
```

Output:

```
yarn install v0.15.0
info No lockfile found.
warning ibg@1.0.0: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "eslint-config-radweb" on the "npm" registry.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The package isn't on the registry, we're just linking the git repo url.

**Comment by montogeek** [comment] 2016-10-11 15:38
I am getting the same error with a private GH repo:
```
👉  yarn
yarn install v0.15.1
info No lockfile found.
warning mozio-next@1.3.1: No license field
[1/4] 🔍  Resolving packages...
error Couldn't find package "sdk" on the "npm" registry.
info Visit http://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

```
"sdk": "git+ssh://git@github.com/XXXXX/sdk.git#v1.8.0",
```

**Comment by kittens** [comment] 2016-10-11 15:43
Looks like this is a duplicate of #513.

**Closed by kittens** 2016-10-11 15:43 UTC
Labels: bug
