### ISSUE TITLE
Installing shows too many spinners

### ISSUE THREAD

**Issue by Haroenv** [yarnpkg/yarn#2137] opened 2016-12-04 10:34 UTC
**Do you want to request a *feature* or report a [*bug*]?**

There are three more "waiting" spinners than being used while installing

**What is the current behavior?**

```
[1/3] ⠈ electron
[2/3] ⠈ electron-chromedriver
[-/3] ⠈ waiting...
[-/3] ⠈ waiting...
[-/3] ⠈ waiting...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Running `yarn` or `yarn install`

**What is the expected behavior?**

```
[1/2] ⠈ electron
[2/2] ⠈ electron-chromedriver
```

**Please mention your node.js, yarn and operating system version.**

node v7.1.0
yarn version v0.17.8
macOS 10.12.1
terminal is fish

**Comment by olingern** [comment] 2016-12-04 18:57
By design, I believe. I think you are seeing [Yarn make concurrent requests] (https://github.com/yarnpkg/yarn/blob/master/src/package-install-scripts.js#L258), and it's just letting you know what it's up to rather than just hanging with a stalled terminal. The `waiting ...` message could be a bit more explicit saying `resolving dependency ...`

**Comment by Haroenv** [comment] 2016-12-04 18:58
The first step of the Ines that do get filled in is waiting indeed. But the bottom don't get used during install i think.

**Comment by JimmyBoh** [comment] 2016-12-07 19:40
It could be a side-effect from the lines not being cleared and redrawn correctly, at least that's what I've seen. If it's not using it already, [`log-update`](https://github.com/sindresorhus/log-update) is a great library for cross platform console screen redraws.

**Comment by paul-soporan** [comment] 2021-01-02 17:52
Closing this as fixed in v2 where the output has been revamped and the issue doesn't exist anymore.

https://yarnpkg.com/getting-started/migration

**Closed by paul-soporan** 2021-01-02 17:52 UTC
