### ISSUE TITLE
Yarn 0.17.0+ fails on travis-ci: no such file or directory, open '/home/travis/.cache/yarn

### ISSUE THREAD

**Issue by viveleroi** [yarnpkg/yarn#1926] opened 2016-11-18 00:31 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A project of mine uses yarn and travis-ci. Until yarn 0.17.0, the `yarn install` process worked correctly on my travis-ci builds. As of 0.17.0, every build on both node 6 and 7 fails with this error:

```
/home/travis/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/bin/yarn.js:47
      throw err;
      ^
Error: ENOENT: no such file or directory, open '/home/travis/.cache/yarn/.roadrunner.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at /home/travis/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/roadrunner/index.js:25:6
    at /home/travis/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/roadrunner/index.js:12:12
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at processEmit [as emit] (/home/travis/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/signal-exit/index.js:140:35)
    at process.exit (internal/process.js:146:15)
    at Command.<anonymous> (/home/travis/.nvm/versions/node/v6.9.1/lib/node_modules/yarn/node_modules/commander/index.js:825:13)
```

Example of a failed build: https://travis-ci.org/helion3/inspire-tree/jobs/175817485
Example of a working build: https://travis-ci.org/helion3/inspire-tree/jobs/176888598

I noticed that yarn 0.16.1 was the last version to build correctly so I've reverted to that version in my `travis.yml` file, and it works again.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using the following travis config:

```
language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - npm install -g webpack yarn
  - yarn -V
install:
  - yarn install
```

Deploy a project to travis. Any yarn version above 0.17.0 fails.

**What is the expected behavior?**
It should install packages correctly.

**Please mention your node.js, yarn and operating system version.**
yarn 0.17.0+, node 6/7, travis-ci

**Comment by wyze** [comment] 2016-11-18 00:36
This was fixed in yarn 0.17.4. Your failing build shows it used yarn 0.17.0. `0.17.4` is available on npm, so give it a shot. Also, duplicate of #1724.

**Closed by wyze** 2016-11-18 00:36 UTC
Labels: needs triage
