### ISSUE TITLE
Progress bar doesn't render correctly in Visual Studio Code's terminal panel

### ISSUE THREAD

**Issue by redstrike** [yarnpkg/yarn#1222] opened 2016-10-19 03:01 UTC
**Do you want to request a _feature_ or report a _bug_?**
Not sure.

**What is the current behavior?**
yarn is very buggy, slow while running. And the progress bar auto line breaks itself looks ugly.

**If the current behavior is a bug, please provide the steps to reproduce.**
yarn install / yarn upgrade

**What is the expected behavior?**
A progressive and good looking progress bar.

**Please mention your node.js, yarn and operating system version.**
- Windows 10 Pro x64 v1607
- node v6.9.0
- yarn v0.16.0

This bug still happens until now 2017/05/15:
- Windows 10 Pro x64 1703 (OS Build 15063.296)
- node v7.10
- yarn v0.24.4

**Comment by Daniel15** [comment] 2016-10-19 04:18
Can you please post a screenshot of what the progress bar looks like for you?

This is how it's supposed to look (cmder on Windows 10):
![05-22 19 37](https://cloud.githubusercontent.com/assets/91933/19141425/2a636932-8b4a-11e6-927d-38597ca3a8a8.gif)

**Comment by mnpenner** [comment] 2016-10-19 06:33
Out of curiosity, I tried it in `cmd.exe`. Works fine there too:

![](http://i.imgur.com/idmYoc1.gif)

**Comment by redstrike** [comment] 2016-10-19 06:55
@Daniel15, @mnpenner : I have tried to test yarn on cmd and PowerShell, the progress bar works normally. However, yarn's progress bar seem have some problems with Visual Studio Code 's Terminal Panel.

![screenshot 3](https://cloud.githubusercontent.com/assets/2168227/19508435/792c2054-9603-11e6-82be-2ae06262c72b.png)

- VS Code v1.6.1

**Comment by mzvast** [comment] 2016-10-25 11:29
On my machine ,all displays incorrect,including cmd, powershell, gitbash.
info:
(Windows 10 Pro x64 v1607
node v6.9.1
yarn v0.16.1)

**Comment by fluxxu** [comment] 2016-11-04 21:39
I think this is related to font
If I change font to MS Gothic, the progress bar looks normal:

<img width="734" alt="2016-11-04" src="https://cloud.githubusercontent.com/assets/4956828/20023136/63c913d0-a2b4-11e6-9757-7626cc5b2f72.png">

But this font is unusable :(

(Windows 10 Pro x64 v1607
node v6.9.1
yarn v0.16.1)

**Comment by mnpenner** [comment] 2016-11-04 21:57
I'm pretty sure this just means VS Code is not processing the `\r` (or whatever yarn uses to re-draw the progress bar) correctly.

It's not a Windows issue, a PowerShell or Cmd.exe issue, nor a font issue.

**Comment by Daniel15** [comment] 2016-11-05 04:38
> I'm pretty sure this just means VS Code is not processing the \r (or whatever yarn uses to re-draw the progress bar) correctly.

@mnpenner - It uses [readline.cursorTo](https://nodejs.org/api/readline.html#readline_readline_cursorto_stream_x_y) to reposition the cursor at the start of the line.

**Comment by mzvast** [comment] 2016-11-20 17:28
I found a way to avoid this problem on my Chinese win 10 terminal, that is to set the "Active Code Page" to 437(us-en) or 65001(UTF-8).
So this problem may have something to do with the windows charset in console.

Yarn is fine, VS code is fine, windows old terminal's charset's bad!

**Comment by andykais** [comment] 2017-01-25 03:00
A very similar issue is affecting docker containers using yarn commands 
![image](https://cloud.githubusercontent.com/assets/6627147/22276269/834b5cca-e280-11e6-86ce-159e9ae014c0.png)
 I would like to either see a permanent --no-progress option or a common fix for the problem. (I tried generating locales and setting `LANG=C.UTF-8` in the container to no avail

**Comment by redstrike** [comment] 2017-02-06 08:26
VS Code v1.9.0 has many improvements including its integrated terminal (Powershell has replaced cmd). This bug is no longer happen in VS Code (if we don't resize VS Code's window while the progress bar is running).

![yarn_vscode](https://cloud.githubusercontent.com/assets/2168227/22639310/f2ddadd2-ec7f-11e6-9c2b-4e92a8e18c09.png)

**Comment by herecydev** [comment] 2017-02-07 18:52
@redstrike I disagree, whilst it's not broken as hell. It's still not perfect, it's too large and still has some areas that "stick" around for a little while before disappearing. It's really hard to describe without recording it.

**Comment by mmoreaux** [comment] 2017-05-08 12:23
I'm seeing a similar issue on some but not all Linux hosts:

![screenshot from 2017-05-08 14 19 20](https://cloud.githubusercontent.com/assets/7665839/25803889/73be7fe2-33f9-11e7-9ff1-af95dfc4aac8.png)

Strace shows that yarn emits `\33[1G` (moving the cursor) between iterations of the progress bar when it works properly, but fails to emit this when it's not working.

Some digging lead me to the `COLORTERM` environment variable. It appears that yarns progress bar is messed up where that variable is missing. It works correctly when I run `COLORTERM=rxvt-xpm yarn install`.

It looks like this is a bug in yarn (or whatever yarn uses for the progress bar); not emitting the cursor-moving control sequences when an optional environment variable is missing.

If all else fails, may I suggest simply using `\r`?

**Comment by aalpgiray** [comment] 2017-05-11 11:39
![image](https://cloud.githubusercontent.com/assets/6337113/25947295/8a137454-3657-11e7-8813-2be38c9c4996.png)
same here on version 1.12.1

**Comment by redstrike** [comment] 2017-05-15 11:49
OMG! yarn is buggy again on the latest stable version: **0.24.4** 😭 

![yarn bug](https://cloud.githubusercontent.com/assets/2168227/26056300/ee18a876-399e-11e7-9398-86b19e34314c.png)

**Windows 10 Pro** v1703 (OS Build 15063.296)

**Comment by xakep139** [comment] 2017-05-23 07:48
Same problem, npm 4.3.0, node 7.7.2, Yarn 0.24.5, Windows 10 Enterprise 1703 (build 15063.296)

![image](https://cloud.githubusercontent.com/assets/6381023/26343502/683aead8-3fc6-11e7-9b21-103e80b6d226.png)

**Comment by xakep139** [comment] 2017-05-25 07:18
There is similar issue with Jest: https://github.com/facebook/jest/pull/3626

**Comment by snewell92** [comment] 2017-05-25 19:46
Yarn was working for me fine last week, this week it seems I am also experiencing this as well. Here is my environment, hopefully can help track it down/repro.

Windows 10Pro 64-bit Version 10.0.15063 Build 15063.

![vscodestats](https://cloud.githubusercontent.com/assets/25957964/26467533/9e986c48-4158-11e7-91a0-a7972184470d.JPG)

![nodenpmyarnstats](https://cloud.githubusercontent.com/assets/25957964/26467559/c0f8fa8c-4158-11e7-8386-02e5dac7f626.JPG)

**Comment by xakep139** [comment] 2017-06-05 08:38
https://github.com/Microsoft/vscode/issues/24604

**Comment by xakep139** [comment] 2017-06-07 05:41
Apparently, it is not Yarn issue: https://github.com/Microsoft/vscode/issues/19665
It seems like there is a bug in Windows with Creators Update, KB4020102 should fix this bug

**Comment by aalpgiray** [comment] 2017-06-07 06:45
unfortunately "KB4020102"  did not fix the issue for me .

**Comment by Daniel15** [comment] 2017-06-07 07:05
@mmoreaux 
> It looks like this is a bug in yarn (or whatever yarn uses for the progress bar); not emitting the cursor-moving control sequences when an optional environment variable is missing.

This would be Node.js' [readline.cursorTo](https://nodejs.org/api/readline.html#readline_readline_cursorto_stream_x_y) function.

**Comment by xakep139** [comment] 2017-06-09 04:37
Progress bar is now fixed for me after KB4020102 and VS Code 1.13.0

**Comment by redstrike** [comment] 2017-06-09 13:20
It seems that this **[Unicode character width improvements](https://code.visualstudio.com/updates/v1_13#_unicode-character-width-improvements)** in **VS Code 1.13** has fixed this issue.

![image](https://user-images.githubusercontent.com/2168227/26977065-aeeea37e-4d50-11e7-8a21-8076800764aa.png)

**Comment by snewell92** [comment] 2017-06-09 13:44
Woo! :D The issue can be closed now. 👍  🎉

**Comment by mmoreaux** [comment] 2017-06-09 14:03
No, the issue cannot be closed; the issue @xakep139 started talking about is different from the issue described in the starting post (different type of corruption, and the issue from the OP also happens on non-Windows hosts).

**Comment by ahundt** [comment] 2017-06-16 17:43
I can confirm this issue appears on OS X and Linux just like the other screenshots/videos with the Keras [Progbar](https://github.com/fchollet/keras/blob/master/keras/utils/generic_utils.py#L210) on 1.13.1.

**Comment by tech4him1** [comment] 2017-09-10 00:39
This bug still happens with Yarn 1.0.1 in Windows 10 (PowerShell and cmd) with some fonts.

**Comment by BYK** [comment] 2017-09-10 19:23
I think this is a duplicate of #2530 right?

**Comment by redstrike** [comment] 2017-09-11 13:16
@BYK 
No, it's not. I created this issue since **Oct 19, 2016**.
So, I think that you have to say #2530 is a duplicate of this issue :)

**Comment by BYK** [comment] 2017-09-13 00:04
@redstrike I was afraid of this when I wrote that comment! :D It is also obvious from the issue numbers that this is the "original" issue. That said the other one has a PR attached __and__ it is more generic so I was implying that closing this in favor of that.

If you are too attached to this one, we can close them at once with the PR though :D

**Comment by redstrike** [comment] 2017-09-14 11:21
Thank you for your support. We can close this issue to ease your management efforts.
Please help me do it and reference to new issue ;)

**Comment by BYK** [comment] 2017-09-14 14:25
Will do :)

**Comment by BYK** [comment] 2017-09-14 14:26
This was fixed by #4317.

**Closed by BYK** 2017-09-14 14:25 UTC
Labels: bug
