### ISSUE TITLE
Yarn install --production installs a devDependencies package

### ISSUE THREAD

**Issue by phun-ky** [yarnpkg/yarn#4646] opened 2017-10-06 09:32 UTC
Related to https://github.com/yarnpkg/yarn/issues/2304 but still reproduced in v1.1.0

Still running into this issue in v1.1.0 ...

Trying to install a private package that has `gulp-stylint` (which depends on `stylint`, which depends on `strip-json-comments`) as dev dep, and have 20 deps that all have `gulp-stylint` as a dev dep, resulting in:

    $ yarn -i --ignore-scripts --production=true
    yarn install v1.1.0
    [1/5] Validating package.json...
    [2/5] Resolving packages...
    [3/5] Fetching packages...
    error https://<provider>.myget.org/F/<feedname>/auth/<api-key>/npm/strip-json-comments/-/strip-json-comments-2.0.1.tgz: Fetch succeeded for undefined. However, extracting "https://<provider>.myget.org/F/<feedname>/auth/<api-key>/npm/strip-json-comments/-/strip-json-comments-2.0.1.tgz" resulted in hash "830b5cabb5f735264e7cc39b2163b90854b2eaa8", which did not match the requested hash "3c531942e908c2697c0ec344858c286c7ca0a60a".
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

*NOTE:* I only get the hash error in windows 10 (Git bash). In ubuntu or ubuntu bash in windows, everything is installed (with devDeps, not as intended), without the hash error

**Comment by tobyroworth** [comment] 2017-10-21 12:52
I'm getting the same (or a similar) issue in 1.2.1 still.

`yarn` seems to be ignoring the `--production` flag, it's aliases and `NODE_ENV=production`, and will go ahead and install the devDependencies.

As a workaround, if I delete the `devDependencies` object I get just the main dependencies, as expected with the `--production` flag.

**Comment by rally25rs** [comment] 2017-12-28 03:56
Duplicate of #3630 

Yarn does not _install_ the devDeps, but it does need to _resolve_ them to determine hoisting and create a deterministic install. There is discussion in the above issue.

**Closed by rally25rs** 2017-12-28 03:56 UTC
