### ISSUE TITLE
Support --registry flag from CLI commands

### ISSUE THREAD

**Issue by egoist** [yarnpkg/yarn#792] opened 2016-10-12 03:15 UTC
**Do you want to request a _feature_ or report a _bug_?**

yes, feature

**What is the current behavior?**

Only global config is available for setting registry

**What is the expected behavior?**

yarg add/install --registry https://custom.registry works

**Please mention your node.js, yarn and operating system version.**

Node. 6.4.0
macOS. 10.11
yarn. 0.15.1

**Comment by i5ting** [comment] 2016-10-12 04:31
use `yrm` module https://www.npmjs.com/package/yrm

**Comment by sindresorhus** [comment] 2016-10-12 06:07
Having a CLI flag for this is a bad idea. Imagine if you forget the registry flag and publish an internal package to the public registry. I would instead recommend Yarn support the [`publishConfig`](https://docs.npmjs.com/misc/registry) property in package.json. You could then just add `"publishConfig":{"registry":"http://my-internal-registry.local"}` to package.json.

**Comment by egoist** [comment] 2016-10-12 06:14
> Imagine if you forget the registry flag and publish an internal package to the public registry

It always happens if people are careless even if they use something like `publishConfig`. what if I thought I added this property but I just didn't really add it. 

And using `--registry` is more for installing not publishing.

**Comment by ibufu** [comment] 2016-10-13 03:09
It is necessary for network environment of China.

**Comment by ljharb** [comment] 2016-10-13 06:23
yarn should support everything npm does, full stop - `publishConfig`, `--registry`, registry set in the npmrc, and/or registry set by any of the env vars that npm looks for.

**Comment by Eladriell** [comment] 2017-02-27 09:16
Has there been any update on this since October?
It's necessary for projects in my company to migrate to Yarn.

**Comment by SimenB** [comment] 2017-02-27 11:30
You can add an .npmrc file?

**Comment by Eladriell** [comment] 2017-02-28 06:49
Sure.
All our projects that publish modules look like this:

.npmrc
```
registry=http://registry/a
stric-ssl=false
_auth=XXXXXXXXXXXXXXXXX
```

.yarnrc
```
registry "http://registry/a"
```

package.json
``` javascript
{
  "name": "yarn-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
	"foo": "0.0.0"
  },
  "publishConfig": {
    "registry": "http://registry/b"
  },
  "author": "",
  "license": "ISC"
}
```

Here both Yarn and npm will try to fetch foo from registry/a, however only npm will consider the publishConfig and try to publish on registry/b.

**Comment by SimenB** [comment] 2017-02-28 07:18
Ah, yarn doesn't respect `pubilshConfig`... Didn't know! I still publish using npm (habit, I suppose), so haven't hit that one

**Comment by bestander** [comment] 2017-05-24 14:21
Just send a PR for --registry, FYI though that config.getOption('registry') is used in multiple places

**Comment by vlkosinov** [comment] 2017-08-21 13:37
Any news here?

**Comment by arcanis** [comment] 2017-08-21 13:49
We received no pull requests, and our attention was focused on other features, so no.

**Comment by SimenB** [comment] 2017-08-21 14:35
You can use env variables.

`YARN_REGISTRY=my-registry.com yarn install`

**Comment by lirantal** [comment] 2017-08-23 13:19
yep that works.
another workaround is to specify the full url of the package with the registry you want to install.

anyway, I'm on it.

**Comment by lirantal** [comment] 2017-08-23 14:04
would be happy to get some review and feedback on https://github.com/yarnpkg/yarn/pull/4238

**Comment by lirantal** [comment] 2017-09-07 05:54
@bestander @arcanis can I get some ❤️ on the PR? :-)

**Comment by pschmoek** [comment] 2017-10-12 12:46
I can confirm `yarn publish --registry https://my-custom-registry.com/.../` is working now (1.2.1).
What's missing is a way to override the registry of a scoped package.
This still is a reason to have both yarn and npm in our environment. I really would like to change that.
With npm we are deploying with the command

`npm publish --@myscope:registry=https://my-custom-registry.com/.../`

Is there a way to achieve the same with yarn without having to use a .npmrc/.yarnrc file?

**Comment by lirantal** [comment] 2017-10-14 11:15
@pschmoek thanks.
for me the `--registry` was a reason to actually install a package from a different repo since we have our own sinopia local proxy and we use it by default in npm config.

I haven't explored `yarn publish` at all and can take a look again on the code on how the scoped packages is different.

If you use the YARN_REGISTRY environment variable will it work?
something like: `YARN_REGISTRY='https://registry.yarnpkg.com' yarn publish myscope... etc`

**Comment by pschmoek** [comment] 2017-10-16 09:23
@lirantal no it does not.

A scopes registry is different to the 'global' registry. If you were to publish `@myscope/test` to your sinopia `--registry` would be insufficient since it only affects the 'global' registry.

The funny thing though, configuring a scopes registry via npm config file works fine.

Inside .npmrc
```
'@myscope:registry': 'https://domain.com:8081/artifactory/api/npm/npm-virtual/'
```

Having multiple registry instances to support, makes the .npmrc solution a pain to work with.
`yarn --"myscope:registry=..."` would be the desired solution. As long as yarn doesn't support it, we will have to stick to use npm for publishing. But the raw functionality is present somewhere inside yarn since .npmrc is interpreted correctly.

**Comment by arcanis** [comment] 2017-10-17 10:26
I'll close this issue, as the original feature is now implemented - can you open a separate issue for the scope thing? Thanks! 😄

**Closed by arcanis** 2017-10-17 10:26 UTC
Labels: bug-configuration, cat-compatibility, cat-enhancement, good first issue, help wanted, triaged

**Comment by lirantal** [comment] 2017-10-17 21:27
@pschmoek open the ticket and I will take a look later, maybe it's a small fix in the `publish.js` command.
