### ISSUE TITLE
yarn init not working in MINGW

### ISSUE THREAD

**Issue by oliversalzburg** [yarnpkg/yarn#854] opened 2016-10-12 10:57 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```
12:50 $ yarn init
yarn init v0.15.1
error Can't answer a question unless a user TTY
    at ConsoleReporter.question (C:\Program Files (x86)\Yarn\lib\reporters\console\console-reporter.js:189:29)
    at Object.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli\commands\init.js:91:38)
    at next (native)
    at step (C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Program Files (x86)\Yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at process._tickCallback (internal/process/next_tick.js:103:7)
info Visit http://yarnpkg.com/en/docs/cli/init for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn init` in the Git Bash on Windows aka MINGW aka MSYS

**What is the expected behavior?**
`yarn` runs

**Please mention your node.js, yarn and operating system version.**
12:57 $ node -v; yarn --version
v6.7.0
0.15.1

Windows 10

**Comment by wldn** [comment] 2016-10-12 11:02
FUCK

**Comment by likealcohol** [comment] 2016-10-12 11:05
Also having the same issue on Windows 10 with v4.2.1 Node

**Comment by gcoutable** [comment] 2016-10-12 11:41
Having the issue on Windows 7 with v6.7.0 Node

**Comment by Daniel15** [comment] 2016-10-12 17:21
Duplicate of #743. Thanks for reporting this!

**Closed by Daniel15** 2016-10-12 17:21 UTC

**Comment by leehaoChen** [comment] 2016-10-18 01:42
Also having this issue on Windows 10 with v4.4.7 Node

**Comment by redDragonLH** [comment] 2016-10-19 01:43
Also having this issue on Windows 10 with v6.6.0 Node

**Comment by ae6623** [comment] 2016-11-04 02:03
Also having this issue on Windows 7 with v6.6.0 Node, v0.16.1 yarn

`
Arguments: 
  C:\Program Files\nodejs\node.exe D:\softs\yarn\bin\yarn.js init

Yarn version: 
  0.16.1

Node version: 
  6.6.0

Platform: 
  win32 x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

bower manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Can't answer a question unless a user TTY
      at ConsoleReporter.question (D:\softs\yarn\lib\reporters\console\console-reporter.js:186:29)
      at Object.<anonymous> (D:\softs\yarn\lib\cli\commands\init.js:95:34)
      at next (native)
      at step (D:\softs\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
      at D:\softs\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20

`

**Comment by herlon214** [comment] 2016-11-30 18:52
Also having this issue on Windows 10 with Node v7.1.0 and Yarn v0.16.0

**Comment by ScottyFillups** [comment] 2017-07-26 14:21
Try adding the following to your .bashrc file:

`alias yarn='node "C:\Program Files (x86)\Yarn\bin\yarn.js"'`

Running `yarn init` should work now for Windows 7. Can somebody please confirm that this works on Windows 10?

**Comment by KemoKemo** [comment] 2017-09-12 14:33
Hi, @ScottyFillups ! Thank you so much for your advice.
Your alias works fine on Windows 10.
