### ISSUE TITLE
Snap version for Linux

### ISSUE THREAD

**Issue by IlCallo** [yarnpkg/yarn#7548] opened 2019-09-13 09:02 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Needs manual installation under Linux based distribution

**What is the expected behavior?**
Create a Snap package to ease adoption
https://snapcraft.io/

**Please mention your node.js, yarn and operating system version.**
Ubuntu 18.04

**Comment by the-spyke** [comment] 2019-10-18 07:01
Duplicate of #3436

**Closed** 2019-10-22 08:13 UTC
