### ISSUE TITLE
nightly.yarnpkg.com is down

### ISSUE THREAD

**Issue by volkyeth** [yarnpkg/yarn#8811] opened 2022-03-26 16:30 UTC
When trying to install a package that fallbacks to yarn Classic I get:

> Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
>
>➤ YN0000: Retrieving https://nightly.yarnpkg.com/latest.js
>➤ YN0035: The remote server failed to provide the requested resource
>➤ YN0035:   Response Code: 530
>➤ YN0035:   Request Method: GET
>➤ YN0035:   Request URL: https://nightly.yarnpkg.com/latest.js
>➤ YN0000: Failed with errors in 0s 105ms

**Comment by Daniel15** [comment] 2022-03-26 18:07
Duplicate of https://github.com/yarnpkg/berry/issues/4274

**Closed by Daniel15** 2022-03-26 18:07 UTC
