### ISSUE TITLE
Commands run with Yarn don't print content from process.stdout.write

### ISSUE THREAD

**Issue by LandonSchropp** [yarnpkg/yarn#5030] opened 2017-12-02 22:53 UTC
**Do you want to request a *feature* or report a *bug*?**

🐛 

**What is the current behavior?**

I have a simple script that writes to `stdout`:

```
process.stdout.write("hello");
```

My `package.json` file contains a `scripts` command to run my script.

```
{
  "name": "Example",
  "author": "Landon Schropp <schroppl@gmail.com>",
  "license": "UNLICENSED",
  "private": true,
  "scripts": {
    "example": "node example.js"
  }
}
```

If I run the script with `node example.js`, this is my output:

```
hello
```

However, if I run the script with `yarn run example`, this is what I see:

```
yarn run v1.3.2
$ node example.js
✨  Done in 0.42s.
```

If I add a console.log after the write, `hello` is included in the output.

Weirdly, if I run yarn with the `--silent` flag then I see`hello` in the output. I also see it if add a `console.log` following the call to `write`.

**What is the expected behavior?**

Yarn should output the string passed into `system.stdout.write`.

**Please mention your node.js, yarn and operating system version.**

* Node.js: 9.2.0
* Yarn: 1.3.2
* macOS 10.13.1

**Comment by rally25rs** [comment] 2017-12-04 13:22
duplicate of #5005 

It looks like Yarn's `reporter` that is used to print output starts by clearing the current line of output. As a temporary workaround, if you add a `\n` (newline) to the end of your output, then it should be displayed.

**Closed by rally25rs** 2017-12-04 13:22 UTC
Labels: triaged
