### ISSUE TITLE
npm publish inside yarn run sometask fail with "npm ERR! code ENEEDAUTH"

### ISSUE THREAD

**Issue by elmariofredo** [yarnpkg/yarn#2935] opened 2017-03-17 00:54 UTC
**Do you want to request a *feature* or report a *bug*?**

bug as mentioned here https://github.com/yarnpkg/yarn/issues/2445#issuecomment-273284359 as a side note

**What is the current behavior?**

command $ `yarn semantic-release` will end with npm auth error if npm publish is called anywhere in the semantic-release script

**If the current behavior is a bug, please provide the steps to reproduce.**

1. add `npm publish` to package.json scripts like this
```json
{
  "name": "test-lerna-semantic-release",
  "version": "1.0.0",
  "scripts": {
    "semantic-release": "npm publish"
  }
}
```
2. run $ `yarn semantic-release` you will get "npm ERR! code ENEEDAUTH"

**What is the expected behavior?**

npm publish should work as it's working when running script with command $ `npm run semantic-release`

**Please mention your node.js, yarn and operating system version.**

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32

$ node --version
v6.9.2

$ yarn --version
0.21.3

**Comment by whitecolor** [comment] 2017-04-17 22:21
Yeah that is really strange case, had to run scripts that run `npm publish` without using **ing YARN. Ha ha.

**Comment by vvo** [comment] 2017-06-19 12:43
Had the same issue and same workaround: that's the only command we run inside an npm run'ed script rather than yarn script.

**Comment by BYK** [comment] 2017-10-27 11:50
We don't intend to support or debug this so closing. Feel free to reopen if you can determine the root cause and want to fix it.

**Closed by BYK** 2017-10-27 11:50 UTC
Labels: bug-publishing, triaged

**Comment by elmariofredo** [comment] 2017-10-27 12:15
@BYK you don't have to necessary support this specific use case, but I guess it would be nice to know what is root cause of this issue so yarn users know what limitation it has, if any. 

If it's not some npm specific issue it could be easily affecting other commands within package.json scripts.

**Comment by elmariofredo** [comment] 2017-10-27 12:29
ok after quick google i have found possible explanation of what is happening check lerna discussion here https://github.com/lerna/lerna/issues/896#issuecomment-311894609 seems like yarn is setting env variable which is npm using for publishing `npm_config_registry` this feels like yarn issue to me.

**Comment by RayBenefield** [comment] 2018-01-04 14:16
@BYK Here to second the above comment. I ran into this yesterday attempting to setup my pipeline to publish via script in [**Travis**](https://travis-ci.org/) rather than through the `npm` deployment system. It uses a `yarn run` script and as a result it is attempting to publish to the wrong registry as `yarn` hijacks the `env` variable `npm_config_registry`. Took me a while to find the issue, but thanks to the linked Lerna issue I've confirmed that is the problem. The `npm_config_registry` was pointing to `https://registry.yarnpkg.com` even if `registry` is set in `.npmrc`. This can be circumvented by adding the following to `.yarnrc` for anyone else that may run into this:

```
registry "https://registry.npmjs.org/"
```

**Comment by pleunv** [comment] 2018-03-01 16:22
> @BYK you don't have to necessary support this specific use case, but I guess it would be nice to know what is root cause of this issue so yarn users know what limitation it has, if any.

Seconded, ran into this and it took way too long to figure out :/. Never expected the behavior between `yarn run` and `npm run` to be so different so was the last thing I went to look.

**Comment by peterjwest** [comment] 2019-04-26 11:10
If you're running an npm command from inside yarn, you can use the following to strip out the problem variable added by yarn:
```
const environment = { ...process.env, npm_config_registry: undefined };
await dependencies.exec('npm whoami', { env: environment }));
```
