### ISSUE TITLE
`yarn outdated` fails and advises to report a bug

### ISSUE THREAD

**Issue by celikmus** [yarnpkg/yarn#1309] opened 2016-10-20 16:12 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn outdated` fails and advises to raise a bug report.

**If the current behavior is a bug, please provide the steps to reproduce.**
Run `yarn outdated` in my repository's root directory.

**What is the expected behavior?**
Yarn should list the outdated packages.

**Please mention your node.js, yarn and operating system version.**
Mac Sierra v10.12, node 6.8.1, yarn 0.16.0
[yarn-error.log.txt](https://github.com/yarnpkg/yarn/files/542209/yarn-error.log.txt)

**Comment by hawkrives** [comment] 2016-10-20 16:43
Do you have any scoped packages in your `package.json`?

**Comment by jsynowiec** [comment] 2016-10-20 16:44
Related to #620

**Comment by wyze** [comment] 2016-10-24 16:10
Closing as duplicate of #620 as mentioned by @jsynowiec.

**Closed by wyze** 2016-10-24 16:10 UTC
