### ISSUE TITLE
i have problem with yarn /tmp/yarn--* a lot of files

### ISSUE THREAD

**Issue by usback** [yarnpkg/yarn#8414] opened 2020-10-26 14:19 UTC
i use os linux ubuntu 
i install with nodejs and yarn  

when i execute yarn at that time make /tmp/yarn--* folder 

/tmp/yarn--*
node //file
yarn //file
so how can i stop make folder and files??

my yarn version is 1.22.10

**Comment by RDIL** [comment] 2022-09-07 16:37
Duplicate of #6685

**Closed by RDIL** 2022-09-07 16:37 UTC
