### ISSUE TITLE
yarn does not verify tarballs put to the offline folder

### ISSUE THREAD

**Issue by ohir** [yarnpkg/yarn#3697] opened 2017-06-22 13:24 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Yarn likely does not verify tarball written to the configured offline folder. On chocked (mobile) connection
happens that it writes even zero sized one. Then yarn fails with uninformative message of mysterious bad hash:
```
error Bad hash. Expected "8c2a5ef2472fd9ea742b04c77a75093ba2757c93" but got "da39a3ee5e6b4b0d3255bfef95601890afd80709" 
```
without even a failed package name.

*Note, that "__da39a .... 80709__" is a sha1 hash of the __zero__ size file*.

Full incident described at [create-react-native-app 272 issue](https://github.com/react-community/create-react-native-app/issues/272).  Also there is separate yarn [issue about uninformative message](https://github.com/yarnpkg/yarn/issues/3689).

**If the current behavior is a bug, please provide the steps to reproduce.**

Use [toxiproxy](https://github.com/Shopify/toxiproxy) to emulate cellular network conditions (bandwidth<1Mbps, latency>1000, jitter 800, with slicer and timeout toxics) set for registry then invoke yarn to install something with many dependencies (e.g. react-native) on a system with cleaned global, offline storage and cache. Or just use real poor cellular connection instead of toxiproxy.

**What is the expected behavior?**
 * Yarn should be able to deal with network errors and outages.
 * Yarn should write to offline cache and use only VERIFIED tarballs.
 * Error message should give full path to the offending tarball. 

**Please mention your node.js, yarn and operating system version.**
node v6.11.0
yarn v0.24.6
Linux 4.4.70 #23 SMP Wed May 27 05:11:55 UTC 2017 (d45547b) x86_64 x86_64 x86_64 GNU/Linux

```
$ yarn config list|sed -r"s/\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]//g"
yarn config v0.24.6
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': true,
  'version-git-message': 'v%s',
  'init-version': '0.1.0',
  'init-license': 'GPLv3',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.24.6 npm/? node/v4.7.3 linux x64',
  'cache-folder': '[scrubbed]/.yarn_cache',
  lastUpdateCheck: 1498045409214,
  'yarn-offline-mirror': '[scrubbed]/.yarn_offline' }
info npm config
{}
```

**Comment by bestander** [comment] 2017-06-23 21:40
Yes, that is a great idea.
Please send a PR, code is here https://github.com/yarnpkg/yarn/blob/master/src/fetchers/tarball-fetcher.js#L162

**Comment by kaylieEB** [comment] 2017-08-20 18:59
I started looking into this but actually am not sure what needs to be updated..
> Yarn should be able to deal with network errors and outages.

This is already the case imo. If the cache doesn't exist or the hash received from the request is incorrect, it _should_ throw an error.

> Yarn should write to offline cache and use only VERIFIED tarballs.

AFAIK, yarn doesn't write to the offline cache if the request fails

> Error message should give full path to the offending tarball.

This is fixed as of v0.25.0 through https://github.com/yarnpkg/yarn/commit/90095543c6adff0b5f09d0a6d9242e4251da2975
Maybe worth adding `This may due to a slow internet connection`? But hash can be different due to other reasons too. Thoughts, @BYK @bestander ?

**Comment by BYK** [comment] 2017-08-20 20:27
@kaylieEB the fact that there was an empty tarball indicates me that either the network connection or something during the file-write went wrong. As you've pointed out, the new error message is better but we can also provide the package name explicitly to be even more helpful.

On top of that we can look at all the code around writing these tar files and make sure to delete them if something bad happens during the write operation. Makes sense?

**Comment by kaylieEB** [comment] 2017-08-20 21:52
Thanks @BYK! It turns out I was checking the normal cache dir and not the offline mirror directory. Now I think have enough steps to reproduce.
The warning `error Bad hash. Expected "8c2a5ef2472fd9ea742b04c77a75093ba2757c93" but got "da39a3ee5e6b4b0d3255bfef95601890afd80709" 
` will be logged regardless of whether the tarball is written to fs. But when the mirror-offline directory is set, it includes the tarball file when it shouldn't.

Do you think we need to include the name when the path includes it?

<img width="676" alt="screen shot 2017-08-20 at 2 50 44 pm" src="https://user-images.githubusercontent.com/18429494/29498745-fc1eb6b8-85b6-11e7-9588-b24836a7bc9b.png">

**Comment by BYK** [comment] 2017-08-20 22:18
No problem! The behavior you describe is not really user-friendly. I think yarn should actually be even more explicit and aware and say "The dependency X@<version> cannot be found in offline cache." if the file is missing and "Hash check failed for offline package <file path> failed for dependency X@<version> failed. Expected <hash1> but got <hash2>. The file seems corrupted."

What do you think? I know these are wordy but it should really be clear to the user and guide them as much as possible IMO.

**Closed** 2017-08-29 09:49 UTC
Labels: bug-fetching, bug-reporters, cat-feature, good-first-contribution, triaged
