### ISSUE TITLE
Yarn@0.17.0 cannot install node-sass on Windows@10

### ISSUE THREAD

**Issue by navarroaxel** [yarnpkg/yarn#1829] opened 2016-11-14 23:18 UTC
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
When I try to run ``yard add --dev node-sass`` I get the following error:

Trace: 
  Error: ENOENT: no such file or directory, chmod 'C:\myProject\node_modules\.bin\mkdirp.cmd'
      at Error (native)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I can install ``node-sass`` using Yarn@0.16.1

**Please mention your node.js, yarn and operating system version.**
Windows@10 (latest updates installed)
Node@6.9.1
Yarn@0.17.0

**Comment by jbruni** [comment] 2016-11-14 23:26
I just reported same issue in the node-sass project: https://github.com/sass/node-sass/issues/1804

**Comment by faddee** [comment] 2016-11-15 07:53
Duplicate of #1823

**Comment by wyze** [comment] 2016-11-15 13:51
Thanks @faddee!

**Closed by wyze** 2016-11-15 13:51 UTC
Labels: needs triage
