### ISSUE TITLE
yarn upgrade might need to support --dev options

### ISSUE THREAD

**Issue by 6zz** [yarnpkg/yarn#1664] opened 2016-11-03 18:31 UTC
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`yarn upgrade` automatically saves a package in the `dependencies` list even the package was in the `devDependencies` list.

**If the current behavior is a bug, please provide the steps to reproduce.**
try `yarn upgrade` a package that's in the `devDependencies` list

**What is the expected behavior?**
upgrade the package in their proper list.  Alternatively, support the `--dev` option.

**Please mention your node.js, yarn and operating system version.**
node-v6.3.1
yarn-0.16.1
MacOS X - 10.11.6

**Comment by zeke** [comment] 2016-11-03 18:55
I think this was fixed by #1620

**Comment by wyze** [comment] 2016-11-03 19:59
Duplicate of #1458 and as @zeke pointed out there is #1620 pending to fix this.

**Closed by wyze** 2016-11-03 19:59 UTC

**Comment by 6zz** [comment] 2016-11-03 20:45
thanks!  I'll wait for the release
