### ISSUE TITLE
Binnary files are not symlinked

### ISSUE THREAD

**Issue by FDiskas** [yarnpkg/yarn#2493] opened 2017-01-18 19:30 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I installing https://github.com/imagemin/imagemin-optipng
binary files are not present in `node_modules/.bin` after installing this module

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `npm install imagemin-optipng --save` binary files are present and accessible by the npm scripts 
1. `yarn add imagemin-optipng` binary files are missing. No errors after installing

**What is the expected behavior?**
There should be created a link to binary file of `imagemin-optipng` module

**Please mention your node.js, yarn and operating system version.**
YARN 0.18.1
NODE v7.3.0
NPM 4.1.1
Kernel Version: 4.9.3-200.fc25.x86_64
Operating System: Fedora 25 (Workstation Edition)
OSType: linux
Architecture: x86_64

**Comment by mathieutu** [comment] 2017-01-19 16:39
This issue is duplicated of :
 - yarnpkg/yarn#733
 - yarnpkg/yarn#735

**Comment by adriaanzon** [comment] 2017-01-19 16:46
No, those issues were about not being able to execute scripts that contain spaces. That's not a problem anymore.

This issue is about the binaries not being symlinked to the correct path in order for `yarn run` to find and execute them.

**Comment by mathieutu** [comment] 2017-01-19 17:00
Ok, my bad I don't know where I've seen exactly the same issue so let's make a new one ¯\_(ツ)_/¯ ! 

I can reproduce exactly the same problem now with the last version of yarn (0.19.1) .

With `yarn add laravel-mix` which install `webpack`, `cross-env`, and others, there is no root `.bin` folder, and so we can't launch them with package.json scripts.

**Comment by adriaanzon** [comment] 2017-01-21 00:33
Found the duplicate: #1487

**Comment by mathieutu** [comment] 2017-01-21 08:57
Ahhh I knew I saw it! 😀

**Comment by raniesantos** [comment] 2017-01-25 19:08
I just updated yarn to 0.19.1, I'm still having this problem.

**Comment by adabru** [comment] 2021-02-17 12:09
Same problem here when trying to install either of `node`, `node@15`, `node@10`. No link in `node_modules/.bin` is created when running `yarn install` or `yarn add -D node`. But running `yarn add -D node` AFTER the installation adds the link to `node_modules/.bin` as wished. `npm install` works fine.

yarn 1.22.10
node v15.8.0
npm 6.13.4
OS: 64-bit Arch Linux

**Comment by merceyz** [comment] 2021-02-17 12:20
Closing as duplicate of #1487

**Closed by merceyz** 2021-02-17 12:20 UTC
