### ISSUE TITLE
bundledDependencies don't get packed as of >= v0.19.0

### ISSUE THREAD

**Issue by selkhateeb** [yarnpkg/yarn#2636] opened 2017-02-05 16:42 UTC
**Do you want to request a *feature* or report a *bug*?**
*BUG*

**What is the current behavior?**
`yarn pack` does not package bundledDependecies in v0.19.0, v0.19.1 and v0.20.0

**If the current behavior is a bug, please provide the steps to reproduce.**
```
{
  "name": "test-bundled-deps",
  "version": "0.0.0",
  "dependencies": {
    "bcryptjs": "^2.0.0",
  },
  "bundledDependencies": [
    "bcryptjs",
  ]
}

```
then run `yarn` followed by `yarn pack`
check the tgz file. It will not contain the node_modules folder.

**What is the expected behavior?**
to work as in version 0.18.1
**Please mention your node.js, yarn and operating system version.**
```
$ node -v
v7.4.0
```
OS X El Capitan 10.11.6

**Comment by kmdm** [comment] 2017-05-16 10:32
Would seem to at least be caused by:-

 * 'node_modules' being added to FOLDERS_IGNORE d1d5343082cd5a3b2020962c0bb6f2d6fb1ac4f3
 *  Accessing of bundledDependencies incorrect in commands/pack.js
  - src/cli/commands/pack.js:  const {bundledDependencies, main, files: onlyFiles} = pkg;
  - src/util/normalize-manifest/fix.js:    info.bundleDependencies = info.bundledDependencies;
  - src/util/normalize-manifest/fix.js:    delete info.bundledDependencies;

Resolving those gives me node_modules/module in the packed .tgz but no subdirectories/files.

**Comment by bestander** [comment] 2017-05-23 16:56
A PR with a test is welcome

**Comment by cameronhunter** [comment] 2017-09-30 22:03
@bestander: I've added a PR with a failing test case (#4598)

**Comment by paul-soporan** [comment] 2021-01-03 20:37
Closed in https://github.com/yarnpkg/yarn/pull/5966.

**Closed by paul-soporan** 2021-01-03 20:37 UTC
Labels: cat-bug, good first issue, help wanted, high-priority, triaged
