### ISSUE TITLE
Workspaces: package A can use a dependency of package B

### ISSUE THREAD

**Issue by lcswillems** [yarnpkg/yarn#7562] opened 2019-09-19 18:01 UTC
Full reproduction and description found here: https://github.com/lcswillems/yarn-dependency-bug

**Do you want to request a *feature* or report a *bug*?**

I don't know if it is intended. I would say it is a bug.

**What is the current behavior?**

In the repository, `package-a` has `string` as dependency. `package-b` has no dependency. However, `package-b` is able to use `string` package. Execute:

```
node package-b/index.js
```

It logs:
```
false
true
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone this: https://github.com/lcswillems/yarn-dependency-bug

**What is the expected behavior?**

`package-b` should not access `package-a`'s dependencies.

**Please mention your node.js, yarn and operating system version.**

- Kubuntu 19.04
- Node.js v10.16.3
- Yarn 1.17.3

**Comment by lcswillems** [comment] 2019-09-26 06:37
Hi,

Any update? Is it a bug or is it expected?

Thank you,
Lucas Willems

**Comment by elliotdavies** [comment] 2019-10-18 09:29
Even if this is intended behaviour, it would still be useful to see a warning in this scenario.

**Comment by merceyz** [comment] 2021-01-02 19:19
That's just how hoisting and node_modules work.

Closing as fixed in v2 where you can use [nmHoistingLimits](https://yarnpkg.com/configuration/yarnrc#nmHoistingLimits) to limit the amount of hoisting or PnP to prevent this in general

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-02 19:19 UTC
