### ISSUE TITLE
Yarn Offline Install with GitHub Hash Fails

### ISSUE THREAD

**Issue by nwestbury** [yarnpkg/yarn#4710] opened 2017-10-14 05:14 UTC
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
I have a simple package.json with the following dependency:
```
"dependencies": {
    "mapbox-gl": "^0.22.0"
}
```
mapbox-gl in turn has the following problematic dependencies:
```
"dependencies": {
   [...]
    "mapbox-gl-shaders": "mapbox/mapbox-gl-shaders#de2ab007455aa2587c552694c68583f94c9f2747",
    "mapbox-gl-style-spec": "mapbox/mapbox-gl-style-spec#83b1a3e5837d785af582efd5ed1a212f2df6a4ae", 
}
```
With the usual offline .yarnrc:
```
yarn-offline-mirror "./offline-cache"
yarn-offline-mirror-pruning true
```

Then I run:
```
$ yarn install # works fine
$ rm -r node_modules
$ yarn install --offline
[1/4] Resolving packages...
error Can't make a request in offline mode ("https://github.com/mapbox/mapbox-gl-shaders")
```

**What is the expected behavior?**
I expect the offline-cache to contain two tgz archives containing the internal github packages. Instead I get the two hashes (de2ab007455aa2587c552694c68583f94c9f2747 & 83b1a3e5837d785af582efd5ed1a212f2df6a4ae) in the folder and `yarn install --offline` fails to find either package. I can manually change these hashes to tgz files and the yarn.lock with explicit version numbers to get it to work but this is far from ideal because it will reset when I add/remove/update a package.

**Please mention your node.js, yarn and operating system version.**
Tried on Windows 7 / Debian, yarn v1.2.1, node v6.11.2

**Extra details**
Unlike #4266 and #4324, this problem disappears in later version where scoped packages are used (e.g. mapbox-gl: "^0.41.0"), but I need this earlier version of the project because of a parent dependency (plotly.js) requires it.

**Comment by BYK** [comment] 2017-10-16 10:10
This seems related or duplicate of #2671. What do you think?

**Comment by nwestbury** [comment] 2017-10-16 12:08
@BYK Thanks for your response, it may be somewhat related. Unlike that issue though, I am getting the git dependencies compressed as a tar file, but it just has the hash number as a filename instead of something with the .tgz. I know this because can rename these files to something like 'mapbox-gl-shaders-1.0.0.tgz' and change the yarn.lock version number to get these to work without making a request in offline mode.

Perhaps the archive naming is intended behavior and it is not picking them up because the packages aren't at the root of the Github directory (e.g. mapbox/mapbox-gl-shaders instead of mapbox-gl-shaders)? I'm not sure, as soon as I find a repository like this I will test it.

**Comment by jordwalke** [comment] 2017-10-23 07:19
I'm seeing this same issue - inside the offline mirror directory, I have just a few files whose file names are long hashes, not the names of packages. I believe something in my dependency tree also have git hash dependencies. `npm`'s support for `git` hash dependencies is increasing (with git tag ranges) so I suspect this is going to be a big issue.

**Comment by QuentinLB** [comment] 2020-08-03 13:40
Sorry to dig this issue but I just encountered the same problem today. One of my project dependencies declare the following dependecy : 

```json
"dependecies": {
...
"xmlrpc": "chfritz/node-xmlrpc"
...
}
```

During an offline installation it get resolved as a hash-only tarball, juste as described by @nwestbury.

Is there any hope for @nwestbury PR (#4798) to be still usable 2 years later or should I try yarn2 or npm ?

Thanks

**Comment by merceyz** [comment] 2021-01-04 02:00
Closing as fixed in v2

https://yarnpkg.com/getting-started/migration

**Closed by merceyz** 2021-01-04 02:00 UTC
Labels: cat-bug, good first issue, help wanted, high-priority, triaged
