### ISSUE TITLE
PnP and Flow resolution

### ISSUE THREAD

**Issue by goodmind** [yarnpkg/yarn#6957] opened 2019-01-24 19:27 UTC
We had this discussion in https://github.com/yarnpkg/website/issues/869#issuecomment-450510731

Let's track it here

**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** 

```
Cannot resolve module
/Users/goodmind/Library/Caches/Yarn/v4/npm-react-16.7.0-b674ec396b0a5715873b350446f7ea0802ab6381/node_modules/react/inde
x.js.

     1│ //@flow
     2│
     3│ import * as React from 'react'
     4│ import styled from 'styled-components'
     5│ import {Tag} from '@blueprintjs/core'
     6│ import type {Scope as ScopeType} from '../service'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/goodmind/pnp-flow-resolving

**What is the expected behavior?** Resolving packages

**Please mention your node.js, yarn and operating system version.**

node v11.7.0
yarn v1.13.0
macOS High Sierra 10.13.6

**Comment by arcanis** [comment] 2019-01-24 19:51
Oh I see! Yes, sorry I didn't think about mentioning it, but the cache folder must (by design) be included in the Flow-covered paths indeed (ie the `[include]` section, as you mentioned). My bad!

Does that make sense?

**Comment by langri-sha** [comment] 2019-02-05 09:47
Maybe a `.yarnrc` in the project directory could work. `yarn config current` shows absolute paths, but perhaps we can use relative paths when configuring.

**Comment by alexkrolick** [comment] 2019-04-16 23:59
Which paths need to be added? This is still erroring for me.

.flowconfig

```
[include]
.pnp
```

**Comment by meatwallace** [comment] 2019-06-11 03:52
didn't spend much time on it but to get everything working running `flow` via a `package.json` script, i used the following setup:

**`.pnp.sh`** - ensure to make executable via `chmod +x ./.pnp.sh`:

```sh
#!bin/sh

NODE_OPTIONS='' node ./.pnp.js
```

**`.yarnrc`**:
```
cache-folder ".yarn-cache"
```

**`.flowconfig`**:

```
[include]
.yarn-cache
; ...other directories

[options]
module.resolver=<PROJECT_ROOT>/.pnp.sh
module.system=haste
```

**`package.json`**:

```json
  "scripts": {
    "run-flow-as-a-script": "flow"
  },
  ...
```

@arcanis - is all of this required / the recommended way to get things working / recommended workflow in the current state?

**Comment by goodmind** [comment] 2019-06-11 03:55
This doesn't make sense, would cache live in project folder? Then what the difference with node_modules?

**Comment by meatwallace** [comment] 2019-06-11 05:04
@goodmind - i'm far from an authority on this so it would be good if someone can confirm or advise, but my conclusion:

yes, this config puts yarn's cache in the project folder - this doesn't seem ideal to me either, but if flow requires your cache is included by design, then i'm not sure you would want to use your global cache. in dev, if you're working on other projects/use global modules etc, then flow will potentially include unrelated code. i think this would occur (likely slower) in if you never cleaned your project's cache, too, unless yarn is pruning it.

in CI, you've lost your cache anyway unless you're explicitly preserving it, and in that case the location becomes irrelevant as you can persist and remount it however you choose.

i don't know PnP intimately enough to list all the benefits, but unless you're blowing your cache away all the time, you should see a speed up as you're minimizing disk I/O with a warm cache. if rebuilding your cache is time intensive, then you could look into setting up yarn's offline package mirror to minimize network I/O.

**Comment by paul-soporan** [comment] 2021-01-02 01:40
Closing as PnP Flow support is tracked in https://github.com/yarnpkg/berry/issues/634.

**Closed by paul-soporan** 2021-01-02 01:40 UTC
Labels: triaged
