### ISSUE TITLE
release v1.22.17 has disappeared

### ISSUE THREAD

**Issue by iwt-marceleffinger** [yarnpkg/yarn#8800] opened 2022-03-15 06:53 UTC
Since today? version 1.22.17 is no longer available at https://github.com/yarnpkg/yarn/releases. Could you check that out? Thank you!

**Comment by gkista** [comment] 2022-03-15 11:08
Hi, 
do we have any update on this issue?
`# yarn set version 1.22.17
Resolving 1.22.17 to a url...
error An unexpected error occurred: "Release not found: 1.22.17".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/html/timmi-ssr/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
`

**Comment by pmaoui** [comment] 2022-03-15 13:31
It looks like the 1.22.17 is also the most recent one on NPM (https://www.npmjs.com/package/yarn)
Running `yarn set version` leads to unexpected behaviors :/

**Comment by kapso** [comment] 2022-03-15 20:28
Our CI is failing as well - `yarn policies set-version 1.22.17`

Does that mean `1.22.17` is no longer valid and should not be used?

**Comment by arcanis** [comment] 2022-03-15 21:52
No, 1.22.17 should still be there, no reason it disappeared 🤔

I'll restore it on 2d73345, as it was in the [archives](http://web.archive.org/web/20220227072441/https://github.com/yarnpkg/yarn/releases)

**Comment by arcanis** [comment] 2022-03-15 22:02
Strangely the release still existed, cf: https://github.com/yarnpkg/yarn/releases

All the release reactions, artifacts were still there. It was just unlisted. Something weird on GH's side?

**Closed** 2022-03-16 06:20 UTC
