### ISSUE TITLE
Global packages unavailable

### ISSUE THREAD

**Issue by ihackalot** [yarnpkg/yarn#3162] opened 2017-04-16 09:36 UTC
Whenever I switch node version via `nvm` it's a module relinking nightmare. However with v0.23.2 I have issues even using modules I have just installed.
```
yarn versions v0.23.2
{ yarn: '0.23.2',
  http_parser: '2.7.0',
  node: '6.10.2',
  v8: '5.1.281.98',
  uv: '1.9.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  icu: '58.2',
  modules: '48',
  openssl: '1.0.2k' }
```
![screen shot 2017-04-16 at 11 13 52 am](https://cloud.githubusercontent.com/assets/28128/25070211/f6edf87e-2298-11e7-8cb5-fe43d57da7cf.png)

**Comment by voxsim** [comment] 2017-05-01 10:55
This is a duplicate of https://github.com/yarnpkg/yarn/issues/3142. @bestander you can close it ;)

**Closed** 2017-05-01 12:42 UTC
