### ISSUE TITLE
`yarn add` with non-existent version saves wrong version to package.json

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2466] opened 2017-01-16 15:49 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**

```
$ ../yarn/bin/yarn add is-array@100
yarn add v0.20.0-0
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "is-array" that matches "100"
? Please choose a version from this list: 1.0.1
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
└─ is-array@1.0.1
✨  Done in 2.80s.
$ ls
node_modules	package.json	yarn.lock
$ cat package.json
{
  "dependencies": {
    "is-array": "100"
  }
}
$ cat yarn.lock
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


is-array@100:
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/is-array/-/is-array-1.0.1.tgz#e9850cc2cc860c3bc0977e84ccf0dd464584279a"
```

The node_modules is correct but package.json and yarn.lock have the incorrect version.

**Please mention your node.js, yarn and operating system version.**
0.19 branch cut

**Comment by bestander** [comment] 2017-01-16 15:50
cc @warpy

**Comment by warpy** [comment] 2017-01-17 17:25
It looks like the `savePackages` step in Add uses the same pattern that was originally requested by the user (see https://github.com/yarnpkg/yarn/blob/edd1a07968d8d2e526d0c5ca00fd18ef80b553b3/src/cli/commands/add.js#L66) We would need to update this logic to make it smarter by checking the actually resolved version.

I still need to see where the pattern gets saved to the manifest for the Install command, but we'd have to make it happen there too.

**Comment by bestander** [comment] 2017-01-17 17:37
I think the logic should be similar to this https://github.com/yarnpkg/yarn/blob/edd1a07968d8d2e526d0c5ca00fd18ef80b553b3/src/cli/commands/add.js#L93 - replace the pattern in resolver so that it stops tracking @latest

**Comment by warpy** [comment] 2017-01-17 22:31
One possible solution (see https://github.com/warpy/yarn/commit/b2545323747ba7b6bc5dfaf7ece9b0e38efeefaf):
- Resolution Step: Restrict the version inquiry only Add command only
- Save Packages Step: After Add command completes, in the `add.savePackages()` step, try to determine the what to use as version depending on the initial request and the resolved package version. I'm doing an `endsWIth` check here.
- For the install command with an invalid version in package.json, we will go back to displaying the old "Can't find matches" error message.

Here's some use-cases and their corresponding results:
1. `yarn add is-array@100`: 
-- Asks to choose new version. We choose `1.0.1`
-- package.json gets saved with `"is-array": "1.0.1"`
2. `yarn add is-array@^100`:
-- Same as 1
3. `yarn add is-array@^1.0.1`:
-- Resolves to `1.0.1` (no inquirer needed).
-- package.json gets saved with `"is-array": "^1.0.1"`
4. `yarn add is-array@^1.0`:
-- Resolves to `1.0.1` (no inquirer needed).
-- package.json gets saved with `"is-array": "1.0.1"` **(minus the `^`)**

**Comment by bestander** [comment] 2017-01-18 15:56
Saving package.json in the middle of the run is risky - what if Yarn crashes between 1 and 4?

**Comment by warpy** [comment] 2017-01-18 17:05
Not sure I follow; I'm not saving package.json in the middle of the run.

**Comment by bestander** [comment] 2017-01-18 17:06
Oh, I got silly, I thought 1,2,3,4 are some complex steps :)

**Comment by bestander** [comment] 2017-01-18 17:07
@warpy, the usecases look great, loosing ^ does not bother me.
Would be great to cover it with unit tests

**Comment by warpy** [comment] 2017-01-18 17:13
Ok sounds good. PR inc soon. Thanks :)

**Comment by warpy** [comment] 2017-01-18 20:08
Hey @bestander, looks like there's one more problem - the lockFile gets saved before we do the version resolution I described above. So even though the package.json gets saved with "1.0.1", the lockFile still contains "100"...

Going to need to investigate more on how to solve this.

**Comment by bestander** [comment] 2017-01-18 23:38
Thanks for looking into it, @warpy, feel free to ping me here if anything is needed.

**Comment by warpy** [comment] 2017-01-23 18:44
Opened PR. I finally came to the conclusion that we can just restart the install command (which add extends from) if there is an inquiry. This results in the command saving the correct pattern in the next run. The above use-cases and results still hold true - (`^` and `~` will be lost because the inquirer response will contain an exact version match.)

**Comment by bestander** [comment] 2017-05-23 12:57
This is still an issue, help to fix it is welcome.

**Comment by mnpenner** [comment] 2017-05-23 15:32
I think it'd be nicer if the `^` or `~` from the original request was retained, regardless of what version was actually picked. And if not that, then default to to adding `^` which is the most common scenario, no?

Omitting the symbol seems nearly as bad as saving the wrong version to package.json. In either scenario, you'll have to manually correct it.

**Comment by bestander** [comment] 2017-05-23 15:33
totally, where is the PR? :)

**Comment by arcanis** [comment] 2017-10-17 10:30
Original repro steps doesn't reproduce the issue anymore, so I'm going to close this. Feel free to open a new issue if you still experience it!

**Closed by arcanis** 2017-10-17 10:30 UTC
Labels: bug-resolution, good first issue, help wanted, triaged

**Comment by mnpenner** [comment] 2017-10-17 16:46
Just tested this on Yarn 1.0.1. It will ask you to pick a version as before:

```
❯ yarn add is-array@100 
yarn add v1.0.1
[1/4] Resolving packages...
Couldn't find any versions for "is-array" that matches "100"
? Please choose a version of "is-array" from this list: (Use arrow keys)
❯ 1.0.1 
```

But will now add the chosen version to your package.json:

```
  "dependencies": {
    "is-array": "^1.0.1"
  },
```

Note that `yarn add is-array@~100` will yield the same result, i.e., the operator is ignored and it will always use `^`.
