### ISSUE TITLE
Different relative file paths to same project needs to be the same.

### ISSUE THREAD

**Issue by thomaspersson** [yarnpkg/yarn#1772] opened 2016-11-10 12:16 UTC
I have found a bug in how Yarn handles relative file paths to other packages.

I have three packages, Main, Util and Shared. The Main project has dependency towards both Util and Shared.

From the Main project the file path in package.json is "../../Shared" for the project Shared.
From the Util project which also has a dependency towards Shared the file path is "../Shared".

When I try todo "yarn install" (also tried yarn install --flat) from the Main project, it threats the file path as "../Shared" and therefore fails (but in package.json it's "../../Shared". If I however change the file path to Shared in the Util project to "../../Shared" the yarn install works from the Main project.

So it seems that file paths can't be different for the same package but i expect my setup to work.

I have only tested this with Yarn version 0.16.1 on Mac OS Sierra with Node version 5.5.0.

**Comment by wyze** [comment] 2016-11-10 13:53
Does it work correctly if you change `../../Shared` to `file:../../Shared`?

**Comment by thomaspersson** [comment] 2016-11-10 13:55
Sorry, should have been clearer. All search paths has "file:" at the beginning.

**Comment by wyze** [comment] 2016-11-10 13:59
Would you be able to provide some `package.json` files to represent your modules? Should be a little more helpful than deciphering the text.

**Comment by thomaspersson** [comment] 2016-11-10 14:05
Directory structure.

Main :: /Main/Customer/package.json
Util :: /Util/package.json
Shared :: /Shared/package.json

Main package.json would look like this
{
 "Shared": "file:../../Shared",
 "Util": "file:../../Util"
}

Util's package.json would look like this
{
  "Shared": "file:../Shared",
}

**Comment by wyze** [comment] 2016-11-10 16:08
Duplicate of #815 and a pending PR #1498 open to fix.

**Closed by wyze** 2016-11-10 16:08 UTC
Labels: needs triage
