### ISSUE TITLE
feature req: --quiet option on yarn install

### ISSUE THREAD

**Issue by jcollum** [yarnpkg/yarn#2368] opened 2017-01-02 18:42 UTC
```
$ yarn --version
0.17.10
```

Just would be nice to have the option to suppress output if nothing fails. Sometimes you don't need the text saying "all good".

**Comment by jarijokinen** [comment] 2017-01-03 11:08
I have added --quiet option to my local fork: https://github.com/jarijokinen/yarn/commit/b8591c10b758a9b1d40985914e894c5b219c80fc

Missing tests and not sure if that's best way to implement it anyway.

**Comment by danherd** [comment] 2017-01-24 15:59
This is a duplicate of #788

**Comment by bestander** [comment] 2017-06-26 22:50
We have --silent now

**Closed by bestander** 2017-06-26 22:50 UTC
